# -*- coding: utf-8 -*-
import json
import os

novel = {
    "title": "Vua Yến Sào Bị Hào Môn Cướp Bằng Sáng Chế Trăm Tỷ Lật Kèo Đè Bẹp Tập Đoàn Yến Hóa Chất",
    "author": "Antigravity",
    "genre": "Sảng Văn",
    "cover_prompt": "An elegant luxury anime illustration of a handsome Vietnamese bio-chemist in a modern laboratory and a powerful beautiful elite female CEO in a business suit, standing next to premium golden bird nest jars, crystal clear lighting, 1:1, no text",
    "intro": """<p><strong>&ldquo;Đôi bàn tay thô ráp đầy sẹo mổ yến này của anh, có chùi sạch ba đời cũng không xứng chạm vào tấm thảm nhung đỏ tại đại sảnh Ngọc Khánh Đường!&rdquo;</strong></p>
<p>Lê Khắc Huy cúi đầu, lặng nhìn khay yến sào huyết hữu cơ quý hiếm mà anh đã dành ba tháng ròng rã leo ròng rọc trên những vách đá chênh vênh ở vịnh Vân Phong để khai thác, nay bị mẹ vợ tương lai ném thẳng xuống sàn gạch men láng bóng, giẫm lên nát vụn. Bên cạnh bà, vị hôn thê Nguyễn Khánh Linh quay đi đầy kiêu hãnh, khoác tay gã thiếu gia hóa chất Trần Minh Hải, mỉa mai coi thường gã kỹ sư sinh học nghèo hèn bám váy hào môn.</p>
<p>Bọn họ không biết rằng, đằng sau chiếc áo sờn vai của Huy là bằng sáng chế độc quyền về quy trình lên men enzym sinh học tách tạp chất yến không dùng hóa chất tẩy rửa. Càng không biết rằng, gã thiếu gia kia đang nhập hàng ngàn tấn yến giả làm từ mủ trôm và rau câu tẩy bằng sodium hydroxide cực độc hòng thổi phồng tài sản trước ngày IPO nghìn tỷ.</p>
<p>Khi liên minh xảo quyệt dùng quyền lực đóng băng tài khoản Vietcombank của anh và phong tỏa khu nhà yến công nghệ cao, Huy bắt tay cùng Lâm Hoàng Yến – nữ CFO lý tính và đầy quyền lực của Vạn An Capital. Bằng một đòn phản công sắc bén từ sắc lệnh của C03, báo cáo kiểm toán Big 4 và một cái bẫy y khoa Đông - Tây y kết hợp hoàn hảo, Lê Khắc Huy bắt cả gia tộc kiêu ngạo phải quỳ rạp khóc than trong vũng bùn ô nhục do chính họ tạo ra.</p>""",
    "chapters": [
        {
            "title": "Chương 1: Khay Huyết Yến Vỡ Vụn Giữa Sảnh Đường Hào Môn",
            "content": """<p>Đêm trung tuần tháng năm, đại sảnh Diamond Ballroom của khách sạn năm sao InterContinental Nha Trang rực rỡ trong ánh đèn chùm pha lê nhập khẩu từ Ý. Hôm nay là đại tiệc kỷ niệm mười lăm năm thành lập Tập đoàn Ngọc Khánh – một trong những thế lực yến sào lớn nhất tỉnh Khánh Hòa, đồng thời cũng là lễ đính hôn được đồn đoán từ lâu của tiểu thư Nguyễn Khánh Linh.</p>
<p>Giữa những tà áo dài gấm hoa lệ và những bộ âu phục đắt tiền của giới thượng lưu phố biển, sự xuất hiện của Lê Khắc Huy trở nên lạc lõng đến kỳ lạ. Anh mặc một chiếc áo sơ mi linen màu xanh nhạt đã sờn nhẹ ở cổ tay, làn da rám nắng sạm đi vì ba tháng ròng rã bám đá, leo ròng rọc dọc các vách núi chênh vênh ở vịnh Vân Phong để canh giữ và khai thác những tổ yến tự nhiên quý hiếm nhất. Trên tay Huy là một hộp sơn mài màu đỏ sẫm, bên trong đựng ba tổ huyết yến hữu cơ nguyên bản – thành quả của mồ hôi, máu và tri thức sinh học mà anh đã dốc lòng nghiên cứu suốt bảy năm.</p>
<p><strong>&ldquo;Đôi bàn tay thô ráp đầy sẹo mổ yến này của anh, có chùi sạch ba đời cũng không xứng chạm vào tấm thảm nhung đỏ tại đại sảnh Ngọc Khánh Đường!&rdquo;</strong> Giọng nói chói lót, đầy vẻ khinh miệt của bà Trần Thị Ngọc – Chủ tịch HĐQT Ngọc Khánh, cũng là mẹ vợ tương lai của anh – vang lên cắt ngang tiếng nhạc cổ điển êm dịu.</p>
<p>Bà Ngọc nhìn khay huyết yến trong tay Huy bằng ánh mắt đầy ghê tởm. Không đợi Huy kịp giải thích, bà ta giật phắt chiếc hộp sơn mài, thản nhiên hất tung ba tổ yến vô giá xuống nền đá marble bóng loáng. Những sợi yến huyết đỏ tươi như máu, chứa hàm lượng vi chất tự nhiên cực cao, vỡ vụn dưới gót giày cao gót mạ vàng của bà ta. Tiếng vỡ vụn khô khốc vang lên giữa sự im lặng đến đáng sợ của hàng trăm vị khách VIP.</p>
<p>Huy siết chặt nắm tay, lồng ngực phập phồng nhưng ánh mắt vẫn lạnh lùng, tĩnh lặng như mặt hồ không đáy. Anh nhìn thẳng vào Nguyễn Khánh Linh, vị hôn thê đã kề vai sát cánh cùng anh từ những ngày gian khó ở phòng thí nghiệm cũ kỹ vùng Diên Khánh. Linh hôm nay lộng lẫy trong chiếc váy dạ hội đính kim sa trị giá hàng trăm triệu đồng, nhưng ánh mắt cô nhìn anh chỉ còn là sự xa cách lạnh băng và chán ghét tột cùng.</p>
<p>Linh khoác chặt tay Trần Minh Hải – thiếu gia của Tập đoàn Hóa chất Vạn Hải kiêu ngạo đứng bên cạnh. Hải nhìn Huy bằng ánh mắt nửa đùa cợt nửa bố thí, khinh bỉ nói: <em>&ldquo;Huy này, làm người thì phải biết vị trí của mình. Một gã kỹ sư sinh học quèn, suốt ngày chỉ biết ngửi mùi phân chim yến và leo vách đá như khỉ thì làm sao mang lại tương lai cho Linh? Nhìn chiếc nhẫn kim cương ba carat trên tay cô ấy đi, đó là thứ mà cả đời cào yến của anh cũng không bao giờ mua nổi.&rdquo;</em></p>
<p>Khánh Linh khẽ thở dài, giọng nói điệu đà nhưng tàn nhẫn găm thẳng vào tim Huy: <em>&ldquo;Huy ạ, chúng ta không cùng đẳng cấp nữa rồi. Từ khi anh Hải đồng ý rót bốn trăm tỷ đồng vào dự án IPO của Ngọc Khánh, tôi mới nhận ra thế nào là tầm nhìn hào môn. Anh giữ lại mấy cái tổ yến dại kia mà tự bồi bổ đi. Ký vào bản thỏa thuận hủy hôn và bàn giao công việc này, rồi cút khỏi cuộc đời tôi.&rdquo;</em></p>
<p>Bà Ngọc cười khẩy, vứt một xấp tài liệu dày cộp xuống vũng nước mưa còn đọng trên bệ cửa kính: <em>&ldquo;Bản quyền sáng chế thiết bị điều trị vi khí hậu nhà yến IoT và công thức lên men enzym sinh học sạch lông yến mang số hiệu VN-2024-009876 là tài sản của tập đoàn Ngọc Khánh. Sáng nay chúng tôi đã hoàn tất thủ tục chuyển nhượng quyền sở hữu trí tuệ đứng tên Trần Minh Hải tại Cục Sở Hữu Trí Tuệ. Mày chỉ là một thằng làm thuê ăn lương mười lăm triệu, đừng mơ mộng mang nó đi.&rdquo;</em></p>
<p>Huy cười nhạt, vết sẹo dài trên lòng bàn tay do vách đá cứa sưng đỏ lên vì lạnh. Anh khẽ nói: <em>&ldquo;Bằng sáng chế đó là công sức độc lập của tôi từ thời đại học, đăng ký dưới tên cá nhân trước khi bước chân vào Ngọc Khánh một ngày. Hợp đồng lao động của tôi ghi rõ mọi nghiên cứu độc lập ngoài giờ làm việc thuộc quyền sở hữu cá nhân. Các người nghĩ dùng giấy tờ giả mạo chữ ký là có thể cướp trắng sao?&rdquo;</em></p>
<p>Trần Minh Hải tiến lên một bước, dí sát mặt vào Huy, phả ra mùi rượu ngoại nồng nặc: <em>&ldquo;Ở cái đất Khánh Hòa này, tiền của Vạn Hải có thể biến không thành có, biến giả thành thật. Bảo vệ! Lôi thằng ăn mày rách rưới này ra ngoài. Đừng để nó làm bẩn không khí tiệc đính hôn của chúng ta!&rdquo;</em></p>
<p>Bốn gã bảo vệ to lớn lập tức ập vào, thô bạo bẻ ngoặt tay Huy ra sau, kéo lê anh dọc theo hành lang trải thảm nhung đỏ rực. Vai áo Huy bị giằng rách, những ngón tay anh cào vào lan can gỗ mun rỉ máu để cố giữ thăng bằng nhưng vô hiệu. Phía sau anh, tiếng cười nói vui vẻ, tiếng nâng ly chúc mừng cho phi vụ IPO nghìn tỷ của Ngọc Khánh và Vạn Hải lại tiếp tục vang lên réo rắt, lấn át cả tiếng sóng biển Nha Trang gầm thét ngoài khơi xa.</p>"""
        },
        {
            "title": "Chương 2: Lòng Tham Không Đáy Và Bản Hợp Đồng Cướp Đoạt",
            "content": """<p>Cơn mưa rào đêm mùa hạ trút xuống Nha Trang xối xả, gột rửa đi những vệt máu tươi rỉ ra từ ngón tay trầy xước của Lê Khắc Huy. Anh đứng một mình dưới hiên khách sạn InterContinental, mái tóc ướt đẫm bết vào trán, nhưng đôi mắt anh không hề có lấy một tia yếu đuối. Chỉ có sự lạnh lùng đến tột cùng, tựa như băng tuyết ngàn năm đang cô đọng lại thành những lưỡi dao sắc bén.</p>
<p>Bỗng nhiên, một chiếc Mercedes-Maybach S680 màu đen tuyền từ từ lăn bánh đến trước mặt anh. Cửa kính phía sau hạ xuống, để lộ khuôn mặt thanh tú nhưng vô cùng kiêu sa của một người phụ nữ. Đó là Lâm Hoàng Yến, nữ CFO kiêu hãnh và lý tính của Quỹ đầu tư Vạn An Capital – nhân vật đứng sau những thương vụ M&A đình đám trị giá hàng ngàn tỷ đồng của giới tài phiệt miền Nam.</p>
<p><strong>&ldquo;Lên xe đi. Tôi không thích nhìn một thiên tài y học sinh học phải tắm mưa như một kẻ thất bại,&rdquo;</strong> giọng nói của Yến rõ ràng, dứt khoát và mang theo một áp lực vô hình khiến người đối diện không thể từ chối.</p>
<p>Huy khẽ nhíu mày bước lên xe. Không gian bên trong chiếc Maybach ấm áp, thoang thoảng mùi hương gỗ đàn hương đắt đỏ. Lâm Hoàng Yến đưa cho Huy một chiếc khăn lau ấm và một chiếc máy tính bảng iPad Pro đang hiển thị hồ sơ thẩm định tài chính của Tập đoàn Ngọc Khánh.</p>
<p>Yến không hề vòng vo, cô nhìn thẳng vào đôi mắt Huy bằng ánh mắt sắc sảo của một nhà đầu tư chuyên nghiệp: <em>&ldquo;Ngọc Khánh vừa nộp hồ sơ IPO lên Sở Giao dịch Chứng khoán TP.HCM (HOSE) với định giá một nghìn hai trăm tỷ đồng. Giá trị cốt lõi giúp họ thổi phồng con số này chính là Bằng sáng chế công nghệ tách tạp chất yến hữu cơ không hóa chất VN-2024-009876. Nhưng tôi biết bằng sáng chế đó thực chất là của anh. Tôi đã cử đội ngũ pháp lý kiểm tra tiến trình đăng ký tại Cục Sở Hữu Trí Tuệ và phát hiện chữ ký ủy quyền chuyển nhượng của anh bị làm giả thô thiển.&rdquo;</em></p>
<p>Huy lau vệt nước mưa trên mặt, thản nhiên rút từ trong túi quần ra một chiếc ví lạnh chứa ổ cứng di động SSD mã hóa quân đội. Anh đặt nó lên bàn trà mini của xe: <em>&ldquo;Trong này là toàn bộ nhật ký commit Git của hệ thống điều khiển vi khí hậu nhà yến IoT, các báo cáo phân tích phổ khối lượng của protein yến từ Viện Công nghệ Sinh học Munich có đóng dấu bảo chứng số thời gian từ năm năm trước. Tôi đã cài mã hóa định danh sinh học dạng blockchain ẩn trong từng dòng code của hệ thống điều khiển. Chỉ cần tôi kích hoạt khóa chính, toàn bộ dữ liệu vận hành nhà yến của Ngọc Khánh sẽ tự động khóa cứng vì vi phạm bản quyền sáng chế.&rdquo;</em></p>
<p>Lâm Hoàng Yến khẽ mỉm cười, một nụ cười hiếm hoi nhưng đầy sự tán thưởng đối với trí tuệ vượt trội của người đàn ông trước mặt. Cô là người thực tế tuyệt đối, không bao giờ tin vào những lời hứa hẹn sáo rỗng. Cô mở một bản hợp đồng đầu tư bằng tiếng Anh dày hơn năm mươi trang đặt trước mặt Huy:</p>
<p><em>&ldquo;Tôi muốn đầu tư vào anh, chứ không phải cứu giúp anh. Vạn An Capital sẽ rót một trăm năm mươi tỷ đồng tiền mặt ngay lập tức để thành lập Công ty Cổ phần Yến Sào Vạn An. Anh nắm giữ sáu mươi phần trăm cổ phần bằng công nghệ và bằng sáng chế độc quyền. Vạn An giữ bốn mươi phần trăm cổ phần bằng tiền mặt và chịu trách nhiệm phân phối quốc tế. Điều kiện duy nhất của tôi là: anh phải dùng công nghệ của mình đè bẹp hoàn toàn dòng yến sào hóa chất bẩn của Ngọc Khánh và Vạn Hải trước khi bọn họ kịp niêm yết lên sàn.&rdquo;</em></p>
<p>Huy nhìn lướt qua những điều khoản cực kỳ sòng phẳng và chặt chẽ của bản hợp đồng. Lâm Hoàng Yến không hề lợi dụng lúc anh sa cơ để ép giá, ngược lại còn cung cấp một hành lang pháp lý bảo vệ tối đa cho nhà khoa học sáng chế. Anh cầm bút, ký tên &ldquo;Lê Khắc Huy&rdquo; bằng nét chữ dứt khoát, rành mạch.</p>
<p><em>&ldquo;Rất sòng phẳng,&rdquo;</em> Huy ngẩng đầu lên, ánh mắt phản chiếu ánh đèn đường Nha Trang lung linh qua cửa kính xe. <em>&ldquo;Hợp tác vui vẻ. Tôi sẽ cho họ biết, thế nào là cái giá của sự phản bội.&rdquo;</em></p>"""
        },
        {
            "title": "Chương 3: Bẫy Sâu Bủa Vây: Khi Dòng Tiền Bị Đóng Băng",
            "content": """<p>Chỉ trong vòng chưa đầy ba tuần kể từ khi ký kết hợp đồng, thương hiệu Yến Sào Vạn An đã tạo nên một cơn địa chấn thực sự trong giới y học và dinh dưỡng Việt Nam. Với dòng sản phẩm yến tinh chế hữu cơ 100% được làm sạch bằng enzym sinh học, loại bỏ hoàn toàn tạp chất mà vẫn giữ nguyên vẹn cấu trúc chuỗi glycoprotein tự nhiên, Vạn An nhanh chóng chiếm lĩnh phân khúc cao cấp. Các đơn hàng xuất khẩu đi Singapore, Nhật Bản liên tục được ký kết, đe dọa trực tiếp đến thị phần của liên minh Ngọc Khánh - Vạn Hải.</p>
<p>Sự trỗi dậy quá nhanh của Huy khiến bà Trần Thị Ngọc và Trần Minh Hải đứng ngồi không yên. Bọn chúng biết rằng nếu để Vạn An tiếp tục phát triển, phi vụ IPO nghìn tỷ của Ngọc Khánh sẽ tan thành mây khói.</p>
<p>Một buổi sáng thứ ba âm u, khi Huy đang cùng Lâm Hoàng Yến kiểm tra mẻ yến mẫu tại văn phòng đại diện ở Nha Trang, một đoàn thanh tra liên ngành gồm đại diện Sở Y tế, Cục Quản lý Thị trường và Cảnh sát Môi trường bất ngờ ập vào. Dẫn đầu đoàn thanh tra là gã Phó phòng quản lý dịch vụ y tế Lê Hữu Tài – một kẻ nổi tiếng nhận hối lộ và là vây cánh thân tín của gia tộc họ Trần.</p>
<p><em>&ldquo;Chúng tôi nhận được đơn thư tố cáo nặc danh kèm theo bằng chứng cho thấy Công ty Yến Sào Vạn An sử dụng nguyên liệu không rõ nguồn gốc và vi phạm nghiêm trọng quy chuẩn an toàn sinh học. Kể từ thời điểm này, chúng tôi ra lệnh đình chỉ hoạt động sản xuất của nhà xưởng Diên Khánh trong vòng hai mươi tư giờ để phục vụ thanh tra toàn diện,&rdquo;</em> Tài lớn tiếng đọc sắc lệnh, khuôn mặt đầy vẻ hách dịch.</p>
<p>Chưa dừng lại ở đó, điện thoại của Lâm Hoàng Yến liên tục đổ chuông báo động. Gương mặt thanh tú của cô hơi đanh lại khi đọc tin nhắn từ hệ thống quản trị tài chính. <strong>Tài khoản thanh toán doanh nghiệp của Yến Sào Vạn An tại Vietcombank Chi nhánh Khánh Hòa đột ngột bị phong tỏa tạm thời</strong> theo yêu cầu phối hợp điều tra của cơ quan quản lý thuế địa phương, lấy lý do nghi ngờ có dấu hiệu trốn thuế và giao dịch dòng tiền bất thường.</p>
<p>Cùng lúc đó, trên mạng xã hội bùng nổ một chiến dịch truyền thông bẩn quy mô lớn. Hàng chục fanpage lớn đồng loạt chia sẻ những hình ảnh giả mạo về những chiếc tổ yến mốc xanh mốc đỏ, đầy giòi bọ được chú thích là &ldquo;hiện trạng bên trong xưởng sản xuất của Vạn An&rdquo;. Một nữ streamer nổi tiếng được trả tiền để thực hiện buổi livestream trực tiếp, khóc lóc kể lể rằng người thân của cô ta đã bị ngộ độc thực phẩm nặng, suýt hỏng thận sau khi sử dụng yến chưng của Vạn An.</p>
<p>Những đòn đánh dồn dập từ pháp lý, tài chính đến truyền thông bẩn ập xuống như một cơn bão cấp mười hai, muốn bóp nghẹt Yến Sào Vạn An ngay từ trong trứng nước. Đứng trước tình thế ngàn cân treo sợi tóc, nếu là một doanh nghiệp bình thường chắc chắn đã lâm vào hoảng loạn và tuyên bố phá sản.</p>
<p>Nhưng Lâm Hoàng Yến chỉ lạnh lùng gập chiếc iPad lại, khóe miệng khẽ nhếch lên đầy khinh bỉ: <em>&ldquo;Họ nghĩ dùng mấy chiêu trò phong tỏa tài khoản ngân hàng và dùng truyền thông bẩn là có thể cắt đứt dòng tiền của tôi sao? Nực cười. Vạn An Capital hoạt động trên cấu trúc dòng vốn quốc tế đa tầng. Tôi đã thiết lập một hạn mức tín dụng dự phòng trị giá mười triệu đô la Mỹ thông qua ngân hàng Standard Chartered Singapore để thanh toán trực tiếp cho nhà cung cấp và trả lương công nhân. Mọi hoạt động của Vạn An vẫn sẽ tiếp diễn bình thường.&rdquo;</em></p>
<p>Huy nhấp một ngụm trà xanh, ánh mắt anh nhìn ra ngoài khơi xa đầy ẩn ý: <em>&ldquo;Cứ để bọn chúng tự đắc trong hai mươi tư giờ này đi. Cái bẫy mà Trần Minh Hải tự giăng ra cho chính mình đã chuẩn bị kích hoạt rồi. Hắn cướp bằng sáng chế của tôi nhưng không hề biết rằng công thức đó có một lỗ hổng sinh học chí mạng mà chỉ người trực tiếp viết mã nghiên cứu như tôi mới nắm rõ. Không có hoạt chất enzym xúc tác SB-09 độc quyền do tôi điều chế từ nấm men hoang dã rừng Chợ Gạo, lượng sodium hydroxide cực độc mà chúng dùng để tẩy trắng yến công nghiệp sẽ phản ứng mạnh với các ion kim loại nặng, biến mẻ yến thành một khối độc chất phá hủy động mạch tim sau đúng ba mươi ngày đóng hộp dưới điều kiện độ ẩm cao của mùa hè Nha Trang.&rdquo;</em></p>
<p>Anh khẽ vuốt ve vết sẹo trên tay, giọng nói trầm ấm nhưng lạnh lẽo vô cùng: <em>&ldquo;Ngày mai chính là tròn ba mươi ngày kể từ khi mẻ yến thương phẩm đầu tiên của Ngọc Khánh được đóng hộp để phục vụ đại tiệc VIP giới thiệu cổ đông lớn. Để xem, ai mới là kẻ phải quỳ xuống cầu xin.&rdquo;</em></p>"""
        },
        {
            "title": "Chương 4: Đêm Gió Nổi Ở Vịnh Vân Phong",
            "content": """<p>Đêm muộn, tại khu nhà yến công nghệ cao của Ngọc Khánh nằm sừng sững trên vách đá sát bờ biển vịnh Vân Phong, sóng biển đập vào gành đá tung bọt trắng xóa, phát ra những âm thanh gầm rú ghê rợn. Gió biển thổi thốc vào những ô thông gió của tòa nhà yến khổng lồ, mang theo hơi muối mặn chát và ẩm ướt.</p>
<p>Bên trong phòng điều khiển trung tâm, Trần Minh Hải đang điên cuồng đập phá đồ đạc. Gã thiếu gia hóa chất mất đi vẻ lịch lãm thường ngày, chiếc cà vạt xộc xệch, trán đẫm mồ hôi hột. Màn hình máy tính trung tâm liên tục nhấp nháy những dòng chữ cảnh báo màu đỏ chói mắt: <strong>&ldquo;ACCESS DENIED - FIRMWARE CORRUPTED&rdquo;</strong>.</p>
<p><em>&ldquo;Chúng mày làm ăn cái kiểu gì thế hả? Có mỗi cái hệ thống điều khiển vi khí hậu nhà yến IoT mà ba ngày nay không vận hành nổi? Nhiệt độ trong phòng nuôi yến đã vọt lên ba mươi sáu độ C rồi! Đàn chim yến đang hoảng loạn bay đi hết kìa!&rdquo;</em> Hải túm cổ áo gã kỹ sư trưởng Nguyễn Văn Hùng, gầm rú như một con thú bị dồn vào chân tường.</p>
<p>Hùng mặt cắt không còn giọt máu, đôi vai run rẩy bần bật, giọng nói đứt quãng vì sợ hãi: <em>&ldquo;Thưa... thưa thiếu gia, chúng tôi đã cố gắng nạp lại firmware mới theo đúng bản thiết kế cướp được từ máy tính của Lê Khắc Huy. Thế nhưng hệ thống IoT này có một lớp bảo mật phần cứng sâu được liên kết trực tiếp với địa chỉ MAC của vi xử lý do Huy đặt làm riêng từ Đức. Khi chúng tôi cố tình thay đổi thông số nhiệt độ để ép chim yến sản sinh huyết yến nhanh hơn, hệ thống bảo mật tự hủy đã kích hoạt, khóa chặt toàn bộ van điều áp khí tự động.&rdquo;</em></p>
<p>Hải đẩy mạnh Hùng ngã nhào xuống sàn nhà đầy dây cáp mạng, rít qua kẽ răng: <em>&ldquo;Đồ vô dụng! Ngày mai là buổi Tiệc VIP giới thiệu cổ đông lớn để chuẩn bị cho đợt IPO. Chủ tịch Tập đoàn Trịnh Gia – lão tài phiệt Trịnh Vạn Nam – sẽ đích thân tới thẩm định sản phẩm và ký hợp đồng cam kết đầu tư bốn trăm tỷ đồng. Nếu không có mười kilôgam huyết yến thượng hạng của Ngọc Khánh để làm món súp Hoàng Gia đãi lão Nam, phi vụ IPO coi như vứt đi!&rdquo;</em></p>
<p>Hùng lồm cồm bò dậy, lau vệt mồ hôi lạnh trên trán, hiến kế với vẻ mặt vô cùng gian xảo: <em>&ldquo;Thiếu gia... chúng ta không còn lựa chọn nào khác. Trong kho của Vạn Hải hiện vẫn còn lưu trữ năm mươi kilôgam yến thô giá rẻ nhập khẩu từ Indonesia. Mặc dù mẻ yến này bị lẫn nhiều lông và tạp chất độc hại, lại nhiễm độc chì do khai thác gần khu công nghiệp, nhưng chúng tôi đã cho tẩy trắng ba lần bằng sodium hydroxide và nhuộm màu huyết yến bằng màu thực phẩm tổng hợp đặc chế của công ty hóa chất. Đảm bảo chưng lên thơm phức, nhìn đỏ tươi lộng lẫy, người phàm không thể nào phân biệt được!&rdquo;</em></p>
<p>Ánh mắt Trần Minh Hải lóe lên một tia độc địa tàn nhẫn. Hắn biết rõ tác hại khủng khiếp của sodium hydroxide đối với hệ tiêu hóa và hô hấp, đặc biệt là với một người già có tiền sử hen suyễn nặng như Trịnh Vạn Nam. Thế nhưng, hào quang của con số một nghìn hai trăm tỷ đồng định giá IPO đã hoàn toàn che mờ đi phần nhân tính cuối cùng trong lòng hắn.</p>
<p><em>&ldquo;Mẹ kiếp, làm ngay đi!&rdquo;</em> Hải nghiến răng ra lệnh, ngón tay bấu chặt vào mép bàn gỗ rỉ máu từ vết xước cũ. <em>&ldquo;Tẩy rửa thật kỹ, chưng cách thủy với đường phèn hảo hạng và nhân sâm để át đi mùi hóa chất. Lão Nam đã bảy mươi lăm tuổi, phổi lão có vấn đề nhưng lão rất háo danh và thích ăn đồ quý hiếm để kéo dài tuổi thọ. Chỉ cần lão ký vào hợp đồng đầu tư ngày mai, sau khi Ngọc Khánh lên sàn, có chết ai ta cũng không quan tâm!&rdquo;</em></p>
<p>Bên ngoài, một tia chớp đột ngột rạch ngang bầu trời đêm Vân Phong, soi rõ khuôn mặt vặn vẹo, xám ngoét vì tham vọng điên cuồng của gã thiếu gia phản bội. Cơn giông bão thực sự đã bắt đầu nổi lên, và nó sẽ quét sạch mọi sự dối trá vào ngày mai.</p>"""
        },
        {
            "title": "Chương 5: Bữa Tiệc VIP Và Cơn Nguy Kịch Của Lão Tài Phiệt",
            "content": """<p>Tối hôm sau, Grand Ballroom của khách sạn Sheraton Nha Trang chật kín người. Không khí buổi đại tiệc VIP giới thiệu cổ đông chiến lược của Ngọc Khánh vô cùng náo nhiệt và xa hoa. Những lẵng hoa tươi rực rỡ, những tháp rượu champagne năm tầng lấp lánh dưới ánh đèn vàng ấm áp. Truyền thông địa phương và các phóng viên kinh tế tề tựu đông đủ để đưa tin về sự kiện được coi là &ldquo;bom tấn&rdquo; tài chính của năm.</p>
<p>Bà Trần Thị Ngọc khoác trên mình bộ áo dài gấm thêu rồng phượng bằng chỉ vàng 24K, nụ cười hãnh diện không ngớt trên môi khi liên tục được các đại gia bắt tay chúc mừng. Bên cạnh bà ta, Nguyễn Khánh Linh diện chiếc đầm đuôi cá lộng lẫy, ngón tay đeo chiếc nhẫn kim cương lấp lánh liên tục nâng ly cùng các quý phu nhân thượng lưu.</p>
<p>Vị khách danh dự tối cao của buổi tiệc – lão tài phiệt Trịnh Vạn Nam – ngồi ở vị trí trung tâm của chiếc bàn VIP số 1. Ông lão bảy mươi lăm tuổi tuy có phần gầy gò và thỉnh thoảng khẽ ho khan do chứng hen suyễn mãn tính, nhưng ánh mắt ông vẫn toát lên uy nghiêm của người đứng đầu đế chế Trịnh Gia nghìn tỷ. Trần Minh Hải đứng khom lưng bên cạnh ông, khuôn mặt đầy vẻ nịnh hợt và tự đắc.</p>
<p><em>&ldquo;Thưa Chủ tịch Nam, hôm nay để chào mừng sự hợp tác vĩ đại giữa Trịnh Gia và Ngọc Khánh, chúng tôi xin kính dâng lên ngài món &lsquo;Hoàng Gia Huyết Yến chưng nhân sâm cổ thụ&rsquo;. Đây là mẻ huyết yến đặc biệt nhất được thu hoạch trực tiếp từ vùng đá ngầm vịnh Vân Phong bằng công nghệ sinh học đột phá của chúng tôi, cam kết mang lại nguồn dinh dưỡng tái tạo phổi tuyệt đối cho ngài,&rdquo;</em> Hải vừa nói vừa tự tay bưng chiếc bát sứ dát vàng chứa những sợi huyết yến đỏ rực rỡ, bốc khói nghi ngút và tỏa ra mùi sâm nồng đậm đặt trước mặt vị tỷ phú.</p>
<p>Trịnh Vạn Nam nhìn bát huyết yến đỏ rực vô cùng đẹp mắt, gật đầu hài lòng: <em>&ldquo;Ngọc Khánh quả danh bất hư truyền. Huyết yến tự nhiên quý hiếm thế này, lại được xử lý bằng công nghệ sinh học không hóa chất thì đúng là thần dược.&rdquo;</em> Nói rồi, ông múc một thìa lớn đưa vào miệng, từ từ thưởng thức.</p>
<p>Bà Ngọc và Khánh Linh nín thở quan sát, khi thấy Trịnh Vạn Nam liên tục ăn hết nửa bát yến huyết, hai mụ đàn bà tham lam khẽ nhìn nhau mỉm cười đắc thắng. Bản hợp đồng cam kết đầu tư bốn trăm tỷ đồng đã được đặt sẵn trên bàn ký kết, chỉ chờ đại tiệc kết thúc là sẽ đóng dấu đỏ.</p>
<p>Thế nhưng, biến cố kinh hoàng ập đến chỉ mười phút sau đó.</p>
<p>Trịnh Vạn Nam đột ngột buông chiếc thìa bạc xuống đĩa sứ vang lên một tiếng &ldquo;coong&rdquo; chói tai. Khuôn mặt hồng hào của ông lão nhanh chóng chuyển sang màu xám ngoét rồi tím tái dần. Ông lấy tay bóp chặt lấy cổ họng mình, miệng há to cố gắng hớp lấy từng ngụm không khí nhưng lồng ngực hoàn toàn bị bó chặt. Cơn hen suyễn cấp tính dữ dội phối hợp với tình trạng dị ứng hóa chất cực mạnh của sodium hydroxide phản ứng ngược khiến toàn bộ đường thở của ông bị co thắt hoàn toàn.</p>
<p><em>&ldquo;Khẹc... khẹc... không... thở... được...&rdquo;</em> Trịnh Vạn Nam ú ớ ra những âm thanh đứt quãng, toàn thân ông co giật mạnh, ngã nhào từ trên ghế xuống sàn nhà, làm đổ vỡ hàng loạt ly tách pha lê đắt tiền. Máu mũi ông bắt đầu rỉ ra, thấm đỏ cả cổ áo sơ mi trắng muốt.</p>
<p><em>&ldquo;Chủ tịch! Ngài làm sao thế này? Bác sĩ đâu! Gọi cấp cứu mau lên!&rdquo;</em> Gã vệ sĩ trưởng hét lên trong hoảng loạn, lập tức lao vào đỡ lấy cơ thể đang run rẩy bần bật của ông lão. Bác sĩ riêng của Trịnh Gia lập tức xông lên, điên cuồng tiêm thuốc giãn phế quản và dùng bình xịt cắt cơn cấp tốc, thế nhưng lồng ngực của Trịnh Vạn Nam vẫn không hề phập phồng. <strong>Độc chất hóa chất tẩy rửa ẩn sâu trong sợi yến giả đã gây bỏng niêm mạc hô hấp sâu, khiến phế quản phù nề hoàn toàn</strong>, thuốc xịt hoàn toàn vô tác dụng.</p>
<p><em>&ldquo;Không xong rồi! Nhịp tim của Chủ tịch đang tụt dốc không phanh! Chỉ còn bốn mươi nhịp trên phút! Oxy trong máu tụt xuống dưới bảy mươi phần trăm! Ông ấy đang bị suy hô hấp cấp cấp tính, nếu không mở nội khí quản ngay lập tức thì chỉ trong ba phút nữa não sẽ chết vĩnh viễn!&rdquo;</em> Bác sĩ riêng run rẩy hét lên, trán đẫm mồ hôi lạnh, đôi bàn tay giữ ống thở run bần bật không dám hạ dao mổ.</p>
<p>Đại sảnh Sheraton hỗn loạn tột độ. Những tiếng la hét, khóc lóc vang lên khắp nơi. Bà Trần Thị Ngọc đứng chết trân tại chỗ, sắc mặt xám ngoét không còn một giọt máu, hai chân bủn rủn khuỵu xuống cạnh bàn. Trần Minh Hải thì sợ hãi đến mức đái ra cả quần, ngón tay run rẩy liên tục bấm điện thoại gọi cứu viện trong vô vọng. Hắn biết rõ, nếu Trịnh Vạn Nam chết ở đây, cả gia tộc họ Trần và Ngọc Khánh sẽ phải đền mạng trước pháp luật!</p>"""
        },
        {
            "title": "Chương 6: Đông Tây Y Biện Chứng: Mũi Kim Định Giang Sơn",
            "content": """<p>Giữa lúc cả đại sảnh Sheraton đang chìm trong sự hoảng loạn tột độ và thần chết đã cận kề sát bên vị tỷ phú, cánh cửa đôi của Grand Ballroom đột ngột bị đẩy mạnh ra. Ánh sáng từ hành lang tràn vào, rọi bóng hai nhân vật đang sải bước tiến vào với phong thái tự tin và uy nghiêm tuyệt đối.</p>
<p>Đó là Lê Khắc Huy và Lâm Hoàng Yến.</p>
<p><em>&ldquo;Tất cả tránh ra nếu không muốn lão già kia tắt thở ngay tại chỗ!&rdquo;</em> Giọng nói của Huy vang lên như sấm bên tai mọi người, mang theo một sức mạnh áp chế tinh thần cực kỳ mạnh mẽ khiến gã bác sĩ riêng đang luống cuống phải dừng tay.</p>
<p>Trần Minh Hải nhìn thấy Huy thì như phát điên, gầm lên: <em>&ldquo;Lê Khắc Huy! Thằng rác rưởi kia! Mày đến đây để phá hoại đại tiệc của tao đúng không? Bảo vệ đâu, đập chết nó cho tao! Nó muốn mưu sát Chủ tịch Nam!&rdquo;</em></p>
<p>Thế nhưng, Lâm Hoàng Yến lập tức bước lên phía trước Huy, ánh mắt cô lạnh lùng quét qua đám đông, tỏa ra khí thế kiêu sa của một CFO tối cao: <em>&ldquo;Ai dám động vào anh ấy? Tôi là Lâm Hoàng Yến của Vạn An Capital. Nếu hôm nay Trịnh lão gia tử có mệnh hệ gì ở đây, tôi cam đoan ngày mai toàn bộ cổ phiếu của Ngọc Khánh sẽ bị hủy tư cách niêm yết vĩnh viễn, và gia tộc họ Trần các người sẽ phải ra hầu tòa vì tội ngộ sát do sử dụng thực phẩm độc hại. Chỉ có Huy mới cứu được ông ấy lúc này!&rdquo;</em></p>
<p>Lời nói đanh thép của Yến như một gáo nước lạnh dội thẳng vào đầu gã vệ sĩ trưởng của Trịnh Gia. Gã nhìn khuôn mặt đã chuyển sang màu tím đen của Trịnh Vạn Nam, nghiến răng quyết định: <em>&ldquo;Xin mời thần y ra tay! Nếu cứu được Chủ tịch, Trịnh Gia sẽ mang ơn ngài suốt đời!&rdquo;</em></p>
<p>Huy không lãng phí một giây nào. Anh lập tức quỳ một chân xuống bên cạnh cơ thể đang co quắp của Trịnh Vạn Nam. Với đôi bàn tay đầy sẹo mổ yến cực kỳ vững chãi và khéo léo, Huy rút từ trong ngực áo ra một cuộn da dê chứa chín mũi kim châm cứu bằng bạc ròng dài mảnh – bộ &ldquo;Cửu Châm Điều Khí&rdquo; gia truyền của dòng họ Lê danh giá.</p>
<p>Huy hít sâu một hơi, nhắm mắt lại tập trung toàn bộ tinh thần lực. Tay anh cử động nhanh như chớp giật, chuẩn xác đến từng milimét. Mũi châm thứ nhất cắm thẳng vào huyệt Hợp Cốc để kích thích hệ thần kinh trung ương, mũi thứ hai cắm sâu vào huyệt Đản Trung trên ngực để giải phóng cơ trơn phế quản bị co thắt, tiếp theo là huyệt Phế Du sau lưng. Động tác của Huy uyển chuyển như một nghệ sĩ đang độc tấu vĩ cầm, không một động tác thừa.</p>
<p><strong>&ldquo;Đông y giữ mạng tạm thời!&rdquo;</strong> Huy trầm giọng quát lớn. Khi những mũi kim bạc vừa cắm xuống, một hiện tượng kỳ diệu đã xảy ra trước sự kinh ngạc tột độ của toàn bộ các bác sĩ Tây y có mặt tại sảnh. Lồng ngực của Trịnh Vạn Nam – vốn đang đông cứng như đá – đột ngột phập phồng trở lại. Một tiếng <em>&ldquo;Hộc...&rdquo;</em> sâu hoắm vang lên từ trong cổ họng ông lão, đờm đặc và dịch độc lẫn hóa chất được tống ra ngoài, đường thở bị chặn đứng suốt năm phút qua bỗng chốc được thông suốt hoàn toàn.</p>
<p>Ngay lập tức, Huy rút từ trong túi áo ra một lọ tinh chất &ldquo;Huyết Yến Enzym Vạn An&rdquo; nguyên chất dạng lỏng siêu phân tử, nhẹ nhàng đổ vào miệng vị tỷ phú. Những hoạt chất glycoprotein hữu cơ tự nhiên kết hợp với các kháng thể EGF sinh học nhanh chóng bao phủ lấy niêm mạc thực quản bị bỏng do hóa chất của ông lão, làm dịu cơn co thắt phế quản từ gốc rễ.</p>
<p>Chỉ ba phút sau, sắc mặt xám ngoét của Trịnh Vạn Nam bắt đầu hồng hào trở lại. Chỉ số oxy trên máy đo cầm tay vọt từ 68% lên thẳng 98%, nhịp tim ổn định ở mức 75 nhịp trên phút. Ông lão khẽ mở mắt, hít thở một hơi thật sâu và sảng khoái, run rẩy nói: <em>&ldquo;Tôi... tôi sống lại rồi! Luồng khí mát lành này... thật là kỳ diệu! Cảm ơn thần y!&rdquo;</em></p>
<p>Đúng lúc này, còi xe cấp cứu của bệnh viện đa khoa quốc tế Nha Trang vang dội bên ngoài sảnh. Các y bác sĩ Tây y nhanh chóng đưa Trịnh Vạn Nam lên cáng thương để chuyển vào phòng hồi sức cấp cứu thực hiện các xét nghiệm lâm sàng chuyên sâu.</p>
<p>Trước khi đi, Huy đứng thẳng người dậy, ánh mắt lạnh lùng như thần chết nhìn thẳng vào Trần Minh Hải và bà Trần Thị Ngọc đang run rẩy như cầy sấy: <em>&ldquo;Kết quả xét nghiệm máu và phân tích độc chất HPLC của bệnh viện Tây y sau một tiếng nữa sẽ là bản án chung thân dành cho sự độc ác và gian dối của các người. Trò chơi kết thúc rồi.&rdquo;</em></p>"""
        },
        {
            "title": "Chương 7: Trước Giờ G: Bản Báo Cáo Của Big 4 Và Sắc Lệnh C03",
            "content": """<p>Đêm đã về khuya, nhưng tại phòng VIP đặc biệt của Bệnh viện Đa khoa Quốc tế Nha Trang, ánh đèn vẫn sáng trưng. Kết quả xét nghiệm lâm sàng và phân tích sắc ký lỏng hiệu năng cao (HPLC) phối hợp sắc ký khí - khối phổ (GC-MS) từ Viện Kiểm nghiệm Vệ sinh An toàn Thực phẩm Quốc gia đã được trả về trực tiếp cho gia tộc họ Trịnh.</p>
<p>Báo cáo ghi rõ: <strong>Trong máu của bệnh nhân Trịnh Vạn Nam có chứa hàm lượng sulfur dioxide vượt mức cho phép 250 lần</strong>, cùng với các mảnh vi nhựa polymer có chứa các hợp chất tẩy rửa công nghiệp sodium hydroxide cực độc, trùng khớp hoàn toàn với mẫu huyết yến thu giữ tại hiện trường bữa tiệc của Ngọc Khánh. Trong khi đó, tinh chất huyết yến sinh học mà Lê Khắc Huy sử dụng để cứu mạng ông lại được chứng minh chứa hàm lượng axit sialic tinh khiết lên tới 12.4%, hoàn toàn không có bất kỳ dư lượng hóa chất nào, có tác dụng tái tạo tế bào phế quản kỳ diệu.</p>
<p>Sau khi giải quyết xong các thủ tục bảo an cho Trịnh lão gia tử, Huy và Lâm Hoàng Yến cùng nhau bước ra ban công lộng gió của một quán cà phê vắng người nằm trên đỉnh đồi La San, hướng tầm mắt ra vịnh Nha Trang lung linh ánh đèn của những con tàu đánh cá ngoài khơi.</p>
<p>Gió biển đêm mát rượi thổi tung làn tóc mây của Yến. Rũ bỏ vẻ lạnh lùng, nghiêm nghị thường ngày của một nữ CFO quyền lực, cô khẽ nhấp một ngụm rượu vang đỏ, ánh mắt nhìn Huy tràn đầy sự dịu dàng và tin cậy sâu sắc:</p>
<p><em>&ldquo;Huy này, anh có biết lúc anh châm cứu cứu mạng ông Nam, anh trông giống cái gì không?&rdquo;</em> Yến khẽ cười, đôi má ửng hồng dưới ánh trăng khuyết.</p>
<p>Huy khẽ mỉm cười, đôi mắt anh vẫn tĩnh lặng nhưng đã có thêm hơi ấm: <em>&ldquo;Trông giống một gã thợ mổ yến quê mùa đúng không?&rdquo;</em></p>
<p>Yến lắc đầu, cô tiến lại gần anh hơn, khoảng cách gần đến mức Huy có thể ngửi thấy mùi hương nước hoa nhẹ nhàng kiêu sa từ cơ thể cô: <em>&ldquo;Không, trông anh giống như một vị vua đang ngự trị trên ngai vàng của mình vậy. Rất kiên định, rất đáng tin cậy. Tôi đã không nhìn lầm người. Sòng phẳng mà nói, thương vụ đầu tư vào Yến Sào Vạn An là quyết định sáng suốt nhất trong sự nghiệp tài chính của tôi.&rdquo;</em></p>
<p>Cô đặt bàn tay thon thả, mềm mại của mình lên bàn tay đầy những vết sẹo thô ráp của Huy, nhẹ nhàng siết chặt: <em>&ldquo;Đội ngũ kiểm toán điều tra độc lập của Big 4 (EY) do tôi thuê đã hoàn tất việc trích xuất dữ liệu tài chính của Ngọc Khánh và Vạn Hải. Chúng ta đã có trong tay toàn bộ sao kê ngân hàng đóng dấu đỏ của Vietcombank, chứng minh bọn chúng đã chuyển hơn hai trăm tỷ đồng ra các công ty ma ở nước ngoài để nhập khẩu yến sào công nghiệp giá rẻ hóa chất bẩn dưới danh nghĩa nguyên liệu cao cấp. Hợp đồng chuyển nhượng bằng sáng chế giả mạo cũng đã được Bộ Công an giám định chữ ký số và kết luận là giả mạo hoàn toàn.&rdquo;</em></p>
<p>Huy nhìn sâu vào đôi mắt lấp lánh của Yến, cảm nhận được hơi ấm và sự đồng điệu kỳ diệu giữa hai tâm hồn lý tính nhưng đầy nhiệt huyết. Anh khẽ lật tay, đan chặt những ngón tay mình vào tay cô: <em>&ldquo;Cảm ơn em, Yến. Nếu không có sự hỗ trợ pháp lý và tài chính sắc bén của em, con đường đòi lại công lý của tôi chắc chắn sẽ gian nan hơn rất nhiều. Ngày mai tại Triển lãm Specialty Food Expo quốc tế, tôi sẽ cho họ thấy sức mạnh thực sự của yến sào truyền thống Việt Nam kết hợp với khoa học chân chính.&rdquo;</em></p>
<p>Yến khẽ tựa đầu vào vai Huy, dưới sự chứng kiến của vầng trăng khuyết vịnh Nha Trang và tiếng sóng biển rì rào, một tình yêu bền chặt, lý tính nhưng vô cùng lãng mạn đã chính thức được đơm hoa kết trái trước giờ quyết chiến.</p>"""
        },
        {
            "title": "Chương 8: Ván Bài Lật Ngửa Tại Triển Lãm Quốc Tế",
            "content": """<p>Sáng hôm sau, Trung tâm Hội nghị và Triển lãm Quốc tế tỉnh Khánh Hòa ngập tràn cờ hoa và biểu ngữ của Triển lãm Specialty Food Expo Châu Á. Hàng ngàn doanh nghiệp nông sản, thực phẩm cao cấp từ khắp nơi trên thế giới đổ về đây. Hôm nay cũng là ngày Tập đoàn Ngọc Khánh chính thức tổ chức lễ gõ búa IPO giả định ngay tại gian hàng trung tâm, được phát sóng trực tiếp trên đài truyền hình quốc gia và các kênh thông tấn lớn.</p>
<p>Bà Trần Thị Ngọc và Trần Minh Hải, dù sắc mặt vẫn còn đôi nét mệt mỏi và lo lắng sau biến cố đêm qua, nhưng dưới áp lực của phi vụ nghìn tỷ, bọn chúng đã dùng lớp phấn trang điểm dày cộp để che giấu và cố nở nụ cười tự tin trước hàng trăm ống kính phóng viên. Nguyễn Khánh Linh đứng bên cạnh gã chồng sắp cưới, cố tỏ ra kiêu hãnh nhưng ánh mắt liên tục đảo quanh đầy bất an.</p>
<p>Khi Trần Minh Hải chuẩn bị bước lên bục danh dự để thực hiện nghi thức gõ búa khai mạc phiên giao dịch giả định trước sự chứng kiến của đại diện Ủy ban Chứng khoán Nhà nước, một giọng nói trầm ấm nhưng đanh thép như sấm sét vang lên từ phía cửa vào của khán phòng:</p>
<p><em>&ldquo;Dừng nghi lễ lừa đảo này lại ngay lập tức!&rdquo;</em></p>
<p>Cả hội trường chấn động. Hàng trăm phóng viên đồng loạt quay camera lại. Lê Khắc Huy trong bộ vest đen sang trọng, lịch lãm bước vào, bên cạnh anh là Lâm Hoàng Yến với khí thế kiêu sa của một CFO tối cao, đi cùng họ là tổ công tác đặc biệt của Cơ quan Cảnh sát Điều tra Bộ Công an (C03) trong sắc phục cảnh sát nghiêm chỉnh.</p>
<p>Bà Trần Thị Ngọc mặt biến sắc, shrieking lớn tiếng: <em>&ldquo;Lê Khắc Huy! Mày là gã kỹ sư bị sa thải vì bất tài! Mày lấy tư cách gì bước vào hội nghị quốc tế này phá hoại? Bảo vệ đâu, đuổi cổ bọn chúng ra ngoài cho tao!&rdquo;</em></p>
<p>Thế nhưng, các gã bảo vệ của triển lãm vừa định tiến lên đã bị các chiến sĩ cảnh sát C03 đưa thẻ ngành ngăn chặn chặn đứng. Thượng tá Nguyễn Văn Nam – trưởng đoàn điều tra – dõng dạc tuyên bố: <em>&ldquo;Chúng tôi có lệnh khởi tố vụ án, khởi tố bị can và lệnh bắt tạm giam đối với Trần Minh Hải và Trần Thị Ngọc về hành vi lừa đảo chiếm đoạt tài sản, làm giả con dấu tài liệu của cơ quan tổ chức, và vi phạm quy định về an toàn vệ sinh thực phẩm gây hậu quả nghiêm trọng!&rdquo;</em></p>
<p>Lâm Hoàng Yến lạnh lùng bước lên bục điều khiển thiết bị trình chiếu kỹ thuật số của hội nghị. Cô cắm chiếc USB chứa bằng chứng thép vào hệ thống điều khiển trung tâm. Ngay lập tức, trên màn hình LED khổng lồ rộng hơn một trăm mét vuông của triển lãm hiện lên những tài liệu vô giá trị pháp lý tuyệt đối:</p>
<p><strong>1. Nhật ký commit Git gốc của hệ thống IoT nhà yến vịnh Vân Phong</strong>, chứng minh rõ ràng quyền tác giả độc quyền đứng tên Lê Khắc Huy từ năm năm trước, lột trần sự dối trá về việc &ldquo;Ngọc Khánh tự nghiên cứu phát triển&rdquo;.</p>
<p><strong>2. Bằng sáng chế số VN-2024-009876 chính thức đứng tên cá nhân Lê Khắc Huy</strong> được Cục Sở Hữu Trí Tuệ bảo chứng thời gian độc bản.</p>
<p><strong>3. Bản báo cáo kiểm toán pháp y dòng tiền của Big 4 (EY)</strong> với con dấu đỏ chói, vạch trần đường dây rửa tiền hơn hai trăm tỷ đồng của Vạn Hải và Ngọc Khánh để nhập khẩu chất độc hóa học yến giả.</p>
<p><strong>4. Đoạn video trích xuất từ camera ẩn</strong> ghi lại rõ ràng cảnh Trần Minh Hải trực tiếp chỉ đạo công nhân phun chất tẩy độc hại sodium hydroxide và phẩm màu đỏ hóa chất vào các mẻ yến thô phế thải để làm giả huyết yến.</p>
<p>Toàn bộ sự thật kinh hoàng được phơi bày trực tiếp trước hàng triệu khán giả đang xem truyền hình trực tiếp và toàn thể giới đầu tư quốc tế có mặt tại hội trường. Sàn diễn hào môn hoành tráng của Ngọc Khánh trong tích tắc biến thành hiện trường của một vụ án hình sự chấn động quốc gia.</p>
<p>Trần Minh Hải sắc mặt xám ngoét không còn một giọt máu. Đầu gối hắn bủn rủn, quỵ sụp hoàn toàn xuống sàn gạch men lạnh lẽo. Hắn thở dốc lâm vào tình trạng hoảng loạn tột độ, mồ hôi lạnh chảy ra đầm đìa ướt sũng cả bộ âu phục đắt giá. Hắn cố bò lại gần bục phát biểu để giải thích nhưng toàn thân co giật, ngón tay cào xuống thảm nhung rỉ máu.</p>
<p>Bà Trần Thị Ngọc đứng bên cạnh run rẩy dữ dội, hàm răng va vào nhau lập cập. Bà ta cố bám lấy mép bàn gỗ gụ để đứng vững, thế nhưng lực lượng cảnh sát đã nhanh chóng tiến lên khóa tay bà ta bằng chiếc còng số tám lạnh ngắt. Móng tay dài sơn son thếp vàng của bà ta cào rách cả mặt bàn gỗ, rỉ máu tươi đầy ghê tởm.</p>
<p>Nguyễn Khánh Linh khóc lóc thảm thiết, quỳ rạp dưới chân Huy, bàn tay đính kim cương cố ôm lấy ống quần anh: <em>&ldquo;Huy ơi! Em sai rồi! Là mẹ em ép em phải làm thế! Em vẫn còn yêu anh mà, xin anh hãy cứu Ngọc Khánh, cứu lấy em! Chúng ta sẽ làm lại từ đầu có được không anh?&rdquo;</em></p>
<p>Huy lạnh lùng lùi lại một bước, ánh mắt nhìn cô ta đầy sự khinh bỉ và thờ ơ tột cùng: <em>&ldquo;Nguyễn Khánh Linh, cô chê đôi bàn tay đầy sẹo mổ yến của tôi không xứng với thảm nhung đỏ của cô. Cô chọn vàng kim hóa chất bẩn thỉu của Trần Minh Hải. Hôm nay, hãy tự mình tận hưởng nấm mồ do chính lòng tham của các người đào sẵn đi.&rdquo;</em></p>
<p>Dưới sự chứng kiến của giới truyền thông toàn quốc, Trần Minh Hải, bà Trần Thị Ngọc và toàn bộ ban lãnh đạo gian xảo của Ngọc Khánh bị cảnh sát thô bạo giải đi trong tiếng la ó, ném chai lọ phẫn nộ của hàng ngàn người tiêu dùng có mặt tại triển lãm.</p>
<p>Lê Khắc Huy đứng sừng sững giữa sảnh đường ngập tràn ánh sáng hào quang, bàn tay anh đan chặt lấy bàn tay mềm mại của Lâm Hoàng Yến. Phía sau họ, thương hiệu Yến Sào Vạn An chính thức được vinh danh là thương hiệu yến sào hữu cơ đạt tiêu chuẩn vàng quốc tế đầu tiên của Việt Nam, bước lên đỉnh vinh quang rực rỡ với giá trị vốn hóa hàng ngàn tỷ đồng của sự tử tế và trí tuệ chân chính. Vị Vua Yến Sào đích thực của Việt Nam đã vương giả quy lai đầy kiêu hãnh!</p>"""
        }
    ]
}

target_file = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_novel.json"

with open(target_file, "w", encoding="utf-8") as f:
    json.dump(novel, f, ensure_ascii=False, indent=2)

print("SUCCESSFULLY COMPILED AND SAVED THE NOVEL DRAFT TO", target_file)
