# -*- coding: utf-8 -*-
import json
import os

def generate_novel():
    novel = {
        "title": "Vua Trà Shan Tuyết Bị Hào Môn Đuổi Khỏi Cửa Lật Kèo Nhờ Bằng Sáng Chế Trăm Tỷ Tiễn Kẻ Phản Bội",
        "author": "Antigravity",
        "genre": "Sảng Văn",
        "intro": """<p><strong>&ldquo;Loại nghèo hèn bốc mùi bùn đất như mày thì lấy gì làm sính lễ bước vào hào môn Lâm Gia? Mang mấy cân lá trà dại hái trên vách đá khô cằn Hoàng Su Phì này đi cút khỏi đây ngay!&rdquo;</strong></p>
<p>Lời sỉ nhục đanh thép của bà mẹ vợ tương lai cùng cái tát trời giáng của gã Giám đốc Vương Quốc Bảo đã đập nát tôn nghiêm của Lê Trọng Nhân ngay giữa tiệc đính hôn xa hoa tại Metropole Hà Nội. Hôn thê Lâm Mỹ Linh khoanh tay lạnh lùng đứng nhìn, mặc cho Nhân bị bảo vệ kéo lê ra cổng dưới cơn mưa tầm tã, hành lý và hộp Bạch Trà Shan Tuyết cổ thụ bị giẫm đạp nát bấy trong bùn lầy.</p>
<p>Nhưng bọn họ không biết rằng, những búp chè Shan Tuyết dại ấy được xử lý bằng công nghệ lên men vi sinh yếm khí men rễ SB-09 &ndash; công trình độc quyền đã được Cục Sở hữu Trí tuệ cấp bằng sáng chế đứng tên anh. Khi Lâm Gia cấu kết cướp đoạt tập tài liệu nghiên cứu dang dở của Nhân để hòng IPO định giá nghìn tỷ, bọn họ đã vô tình kích hoạt quả bom sinh học tự hủy do thiếu đi bí quyết then chốt từ rễ dâu tằm cổ thụ.</p>
<p>Bắt tay cùng nữ tổng tài lý tính Nguyễn Khánh An của Quỹ đầu tư Vạn An, người sẵn sàng chi hàng trăm tỷ sau khi cử Big 4 kiểm toán pháp lý gắt gao, Lê Trọng Nhân từng bước lật ngược thế cờ. Từ những dòng nhật ký commit Git trên máy chủ IoT đến sắc lệnh điều tra đóng dấu đỏ của C03, anh đã biến ngày ra mắt sản phẩm mới của Lâm Gia thành nấm mồ chôn vùi cả một gia tộc xảo quyệt.</p>""",
        "cover_prompt": "A luxurious anime book cover, 1:1 ratio, depicting a handsome young Vietnamese agricultural scientist with sharp features and a strong posture, wearing modern stylish outdoor researcher clothing, standing on a misty high mountain slope in Hoang Su Phi. In his hand, he gently holds premium glowing green tea leaves. Beside him stands a beautiful, elegant, and highly rational modern business woman in a sleek dark blue blazer, looking confident and sharp. Background shows ancient majestic tea trees growing on rugged cliff sides, with golden sunbeams breaking through the foggy clouds, highly detailed, dramatic lighting, premium quality, no text.",
        "chapters": []
    }

    # Chapter 1
    ch1_content = """<p>Đêm mưa Hà Nội lạnh buốt thấu xương, nhưng bầu không khí bên trong khán phòng VIP của khách sạn Sofitel Legend Metropole lại nóng rực bởi ánh đèn pha lê lấp lánh và tiếng cười nói của giới thượng lưu. Hôm nay là tiệc đính hôn của Lê Trọng Nhân &ndash; một thạc sĩ trẻ ngành công nghệ sinh học nông nghiệp vừa trở về từ Hoàng Su Phì, Hà Giang &ndash; và Lâm Mỹ Linh, đại tiểu thư của tập đoàn Trà Việt Group trị giá hàng trăm tỷ đồng. Toàn bộ sảnh tiệc được trang hoàng bằng hàng ngàn đóa hoa hồng nhập khẩu, những ly rượu vang đỏ đắt tiền đong đưa trên tay những vị khách quý sang trọng bậc nhất thủ đô.</p>
<p>Nhân đứng ở góc phòng, bộ vest cũ màu ghi đã bạc sờn ở gấu áo có vẻ lạc lõng giữa những bộ tuxedo sang trọng và váy dạ hội lộng lẫy đính kim cương đắt giá. Gương mặt anh thanh tú nhưng mang theo nét phong sương của sương gió vùng cao, đôi mắt sáng như sao trời, tay có những vết chai của người quanh năm trèo đèo lội suối. Trong tay anh ôm khư khư một hộp gỗ lũa phong sương, được chạm khắc hoa văn cổ của người Mông vùng cao, phảng phất mùi thơm của gỗ thông đá cổ thụ. Bên trong hộp gỗ đó là mười hai búp Bạch Trà Shan Tuyết đặc biệt được ủ men rễ tự nhiên SB-09 &ndash; thành quả bảy năm ròng rã ăn ngủ giữa rừng sâu, leo lên những vách đá dựng đứng cao hơn hai nghìn mét để bảo tồn giống trà cổ thụ năm trăm năm tuổi. Đây là sính lễ anh tự tay chuẩn bị, chứa đựng tất cả tâm huyết và tình yêu của mình dành cho Mỹ Linh.</p>
<p>&ldquo;Trọng Nhân, anh mang cái gì đến thế kia? Đừng bảo tôi đó là đống sính lễ mà anh nói nhé?&rdquo; Lâm Mỹ Linh bước lại gần, giọng điệu thanh tao nhưng lạnh lùng thấu xương. Cô ta mặc chiếc váy cưới đuôi cá đính đá quý lấp lánh, khoác tay Vương Quốc Bảo &ndash; vị Giám đốc điều hành mới của Trà Việt, một kẻ có mái tóc chải chuốt bóng lộn và nụ cười khinh khỉnh ngạo nghễ.</p>
<p>Nhân mỉm cười ôn hòa, nhẹ nhàng mở chiếc hộp gỗ lũa ra: &ldquo;Mỹ Linh, đây là Bạch Trà Shan Tuyết cổ thụ ủ men sinh học SB-09. Loại trà này có khả năng ổn định huyết áp, phục hồi thành mạch và điều hòa nhịp tim cực kỳ tốt. Anh đã dành bảy năm để lai tạo và hoàn thiện công thức độc quyền này, nó thực sự là vô giá đối với sức khỏe của gia đình em...&rdquo;</p>
<p>&ldquo;Ha ha ha! Vô giá sao?&rdquo; Tiếng cười lớn đầy châm biếm của Vương Quốc Bảo cắt ngang lời anh, thu hút sự chú ý của toàn bộ quan khách trong hội trường rộng lớn. Hắn giật phắt chiếc hộp gỗ từ tay Nhân, thô bạo đổ mười hai búp trà trắng muốt như tuyết xuống sàn gạch lấp lánh bóng loáng. &ldquo;Mọi người nhìn xem! Đây là sính lễ của một thạc sĩ nông nghiệp vùng cao! Mấy cọng lá cây khô nhặt từ đống củi dại trên vách đá khô cằn Hoàng Su Phì! Trà Việt chúng tôi chiếm giữ bảy mươi phần trăm thị phần trà xuất khẩu cả nước, mỗi cân trà thượng hạng giá vài chục triệu đồng, mà anh dám mang đống rác rưởi bốc mùi bùn đất này đến để làm sính lễ đính hôn với đại tiểu thư sao?&rdquo;</p>
<p>Nói xong, Quốc Bảo dùng đôi giày da Berluti bóng lộn của mình giẫm mạnh lên những búp chè Shan Tuyết trắng muốt. Búp chè vỡ vụn dưới gót giày thô bạo của hắn, nát bấy lẫn vào những giọt rượu champagne vương vãi trên sàn. Tiếng xì xào khinh bỉ vang lên từ khắp phía, những ánh mắt chế giễu đổ dồn về phía Nhân như nhìn một gã hề.</p>
<p>Bà mẹ vợ tương lai &ndash; Lâm phu nhân &ndash; bước tới từ hàng ghế danh dự, sắc mặt bà lạnh tanh như tiền. Bà nhìn Nhân bằng nửa con mắt, khinh miệt nói: &ldquo;Loại nghèo hèn bốc mùi bùn đất như mày thì lấy gì làm sính lễ bước vào hào môn Lâm Gia? Thằng Bảo nói đúng, Lâm Gia chúng ta không thể dung nạp một kẻ làm vườn vô tích sự. Mỹ Linh, đưa thỏa thuận hủy hôn ước cho nó ký, rồi bảo vệ đuổi nó đi ngay lập tức!&rdquo;</p>
<p>Lâm Mỹ Linh không chút do dự, cô ta rút từ trong túi xách ra một bản thỏa thuận hủy hôn ước đã soạn sẵn, ném thẳng vào ngực Nhân. &ldquo;Nhân, chúng ta không cùng một thế giới. Anh suốt đời chỉ có thể chui rúc trên những vách đá sương mù cùng đống cây dại. Còn tôi là đại tiểu thư Lâm Gia, tôi cần một người đàn ông có thể giúp tập đoàn vươn tầm quốc tế, chứ không phải một gã nông dân nghèo nàn kiết xác.&rdquo;</p>
<p>Nhân lặng yên nhìn những búp trà bị giẫm nát dưới gót giày của Vương Quốc Bảo. Khớp xương ngón tay anh siết chặt đến mức kêu răng rắc, nhưng gương mặt anh vẫn bình thản lạ lùng. Anh cúi xuống, nhặt một búp trà nát lấm bẩn lên, ánh mắt chợt lóe lên một tia sáng sắc lạnh như dao cạo.</p>
<p>&ldquo;Lâm Gia các người hôm nay từ chối hạt ngọc của núi rừng, sỉ nhục công sức nghiên cứu của tôi. Ngày sau, khi cả gia tộc sụp đổ, dù có quỳ gối van xin dưới chân đèo Hoàng Su Phì, các người cũng đừng hòng nếm được một giọt trà cứu mạng của tôi.&rdquo; Giọng Nhân trầm ấm nhưng vang vọng khắp gian phòng rộng lớn.</p>
<p>&ldquo;Câm miệng! Đồ rác rưởi huyễn hoặc! Bảo vệ, kéo cổ nó ra ngoài cho tôi!&rdquo; Lâm phu nhân giận dữ hét lên.</p>
<p>Two gã bảo vệ to khỏe lập tức ập tới, nắm chặt lấy bả vai Nhân và thô bạo kéo lê anh ra khỏi sảnh khánh tiết lộng lẫy. Dưới cơn mưa phùn Hà Nội lạnh ngắt, Nhân bị ném ra lề đường Metropole như một kẻ thừa thãi. Chiếc vali cũ kỹ của anh bị ném theo, bung ra khiến vài cuốn sổ ghi chép sạm màu đất ướt đẫm nước mưa. Nhân đứng dưới mưa, nhìn bóng dáng lộng lẫy của Lâm Gia khuất sau cánh cửa kính xoay của khách sạn năm sao. Anh khẽ lau giọt nước mưa trên mặt, mỉm cười lạnh lùng. Thời gian của Lâm Gia không còn nhiều nữa rồi.</p>"""
    novel["chapters"].append({"title": "Chương 1: Sính Lễ Lá Trà Dại", "content": ch1_content})

    # Chapter 2
    ch2_content = """<p>Ba ngày sau khi chịu đựng sự sỉ nhục cay đắng tại Hà Nội, Lê Trọng Nhân đã trở lại căn nhà gỗ nhỏ nằm cheo leo bên sườn núi Hoàng Su Phì, nơi sương mù quanh năm bao phủ những gốc chè Shan Tuyết cổ thụ hàng trăm năm tuổi. Tiếng gió hú qua khe núi và tiếng chim rừng hót líu lo như xoa dịu phần nào nỗi lòng phong sương của anh. Thế nhưng, khi anh đẩy cửa bước vào phòng thí nghiệm thực nghiệm nông nghiệp của mình, đập vào mắt anh là một cảnh tượng hỗn loạn kinh hoàng. Các khay ủ men sinh học bị lật tung, hóa chất vương vãi trên nền đất, tài liệu nghiên cứu vứt bừa bãi, và chiếc tủ bảo mật chứa ổ cứng dự phòng đã bị cạy phá thô bạo bằng xà beng.</p>
<p>Nhân lập tức tiến đến bàn làm việc. Ổ cứng vật lý chứa toàn bộ các bản ghi chép công thức ủ men vi sinh yếm khí SB-09 &ndash; công trình nghiên cứu mà anh tích lũy suốt bảy năm ròng rã &ndash; đã biến mất không dấu vết. Camera an ninh lắp đặt trong phòng đã bị cắt nguồn điện một cách chuyên nghiệp từ trước.</p>
<p>Anh khẽ nhếch môi cười nhạt, không hề có một chút hoảng loạn hay sợ hãi nào hiện lên trên gương mặt phong sương. Nhân ngồi xuống trước máy tính, ngón tay gõ nhanh trên bàn phím. Anh đăng nhập vào hệ thống điều khiển cảm biến IoT nông nghiệp theo dõi nhiệt độ, độ ẩm đất và nồng độ oxy lên men tự động do anh tự thiết lập qua sóng LoRaWAN. Trên màn hình máy tính, những dòng lệnh chạy đều đặn. Nhân đã kích hoạt hệ thống Git lưu trữ mã nguồn cảm biến và nhật ký commit tự động đồng bộ hóa lên máy chủ đám mây cá nhân bảo mật ba lớp, sử dụng xác thực vân tay và khóa bảo mật phần cứng Yubikey độc quyền.</p>
<p>Bọn trộm cắp do Vương Quốc Bảo thuê chỉ lấy đi được ổ cứng vật lý chứa bản nháp thô sơ chưa hoàn thiện và các ghi chép vòng ngoài của năm cũ. Bí quyết then chốt nhất của men sinh học SB-09 &ndash; tỷ lệ phối trộn vi khuẩn cộng sinh rễ tự nhiên và hoạt chất xúc tác hữu cơ từ rễ cây dâu tằm cổ thụ ủ ở nhiệt độ chuẩn xác &ndash; chỉ nằm duy nhất trong bộ não của Lê Trọng Nhân và được mã hóa trên Git cá nhân của anh với lịch sử commit rõ ràng từng ngày, từng giờ suốt ba năm qua.</p>
<p>&ldquo;Vương Quốc Bảo, mày nghĩ ăn cắp được cái ổ cứng thô sơ đó là chiếm đoạt được cả tương lai sao? Mày quá ngây thơ và ngu xuẩn rồi.&rdquo; Nhân thầm nghĩ, đôi mắt ánh lên tia nhìn sắc bén.</p>
<p>Ngay lúc đó, điện thoại của anh rung lên bần bật. Đó là tin nhắn thông báo tự động từ ngân hàng Vietcombank. Nhân mở tin nhắn ra, sắc mặt anh hơi trầm xuống. Tài khoản tiết kiệm cá nhân duy nhất của anh chứa hai trăm triệu đồng &ndash; toàn bộ số tiền anh tích góp từ việc bán chè hữu cơ để duy trì phòng thí nghiệm và hợp tác xã &ndash; đã bị phong tỏa tạm thời theo lệnh yêu cầu từ cơ quan thanh tra tài chính.</p>
<p>Lý do được đưa ra là có đơn tố cáo nặc danh cáo buộc Lê Trọng Nhân &ldquo;chiếm dụng bất hợp pháp nguồn vốn tài trợ phát triển cộng đồng nông thôn&rdquo; trị giá một trăm triệu đồng từ quỹ từ thiện cũ của Trà Việt Group tài trợ từ ba năm trước. Đây rõ ràng là một đòn hiểm độc và bẩn thỉu của Lâm Gia nhằm cắt đứt hoàn toàn nguồn tài chính của anh, dồn anh vào con đường cùng không lối thoát để ép anh phải đầu hàng và dâng hiến toàn bộ công trình nghiên cứu. Nhân nắm chặt điện thoại, nụ cười lạnh lùng nở trên môi. Bọn chúng không chỉ cướp công trình mà còn muốn tuyệt đường sống của anh, bôi nhọ danh dự của anh trước pháp luật. Nhưng Nhân biết rõ, mỗi dòng tiền, mỗi chứng từ thu chi của hợp tác xã chè do anh điều hành đều được lưu trữ cực kỳ minh bạch và có hóa đơn đỏ đóng dấu đầy đủ. Sự bẩn thỉu của Lâm Gia sẽ là bằng chứng đắt giá nhất trước tòa án pháp lý sau này.</p>"""

    ch2_expanded = ch2_content + """
<p>Căn nhà gỗ nhỏ của Nhân được ghép từ những thớ gỗ sa mộc già dặn, trải qua bao mùa mưa nắng trên cao nguyên đá nên đã ngả sang màu xám bạc phong sương. Ở nơi đây, ranh giới giữa đất và trời dường như bị xóa nhòa bởi những dải mây trắng bảng lảng luồn qua khe cửa. Phòng thí nghiệm thô sơ này chính là thánh đường của anh, nơi anh đặt những chiếc máy đo quang phổ cũ kỹ, những ống nghiệm thủy tinh xếp gọn gàng và chiếc tủ cấy vi sinh tự chế. Mỗi góc nhỏ đều thấm đẫm mồ hôi và những đêm thức trắng theo dõi sự biến đổi sinh học của từng mẫu men. Việc phòng lab bị lục lọi và cướp phá trắng trợn giống như một nhát dao đâm thẳng vào những gì thiêng liêng nhất mà anh nâng niu suốt bao năm qua.</p>
<p>Nhân khẽ thở dài, bước đến chiếc cửa sổ gỗ nhìn ra thung lũng sâu thẳm bên dưới. Những cây trà Shan Tuyết cổ thụ đứng trầm mặc trong sương sớm, cành lá khẳng khiu nhưng tràn đầy nhựa sống mãnh liệt. Chúng đã sinh trưởng ở đây hàng thế kỷ, bám rễ sâu vào vách đá vôi cằn cỗi để chắt chiu từng giọt dưỡng chất tinh túy của đất trời. Anh hiểu rằng, sức mạnh của trà cổ thụ Hoàng Su Phì không nằm ở những trang thiết bị hiện đại, mà nằm ở sức sống nội sinh hoang dã của nó. Bất kỳ kẻ nào muốn dùng hóa chất nhân tạo hay công nghệ ép chín để thao túng dòng chảy tự nhiên của loài cây linh thiêng này đều sẽ phải nhận một bài học đích đáng. Sự kiêu ngạo của Lâm Gia và Vương Quốc Bảo chỉ chứng tỏ sự nông cạn và thiếu hiểu biết của những kẻ chốn phồn hoa đô hội đối với linh khí của đại ngàn Hà Giang.</p>
<p>Điện thoại trên bàn lại tiếp tục sáng lên, hiện lên danh sách dài những cuộc gọi nhỡ từ các hộ nông dân liên kết trong hợp tác xã. Bọn họ đều là những người Mông, người Dao thật thà chất phác, cả đời chỉ biết bám lấy gốc trà để mưu sinh. Tin đồn ác ý từ Hà Nội đang bắt đầu lan truyền đến bản làng, reo rắc nỗi sợ hãi về việc hợp tác xã bị phá sản và nguồn chè bị nhiễm độc. Nhân hít một hơi thật sâu, anh biết mình không thể gục ngã lúc này. Anh là chỗ dựa duy nhất của hàng trăm hộ dân nơi đây. Với số vốn đầu tư và sự bảo trợ pháp lý vững chắc từ Quỹ Vạn An sắp tới, anh sẽ không chỉ đòi lại công lý cho bản thân mà còn xây dựng một đế chế trà vững mạnh, bảo vệ sinh kế bền vũ cho bà con vùng cao nghèo khó. Đòn phản công này sẽ bắt đầu từ những vách đá sương mù này và quét sạch mọi dối trá của những kẻ hào môn xảo quyệt.</p>"""
    novel["chapters"].append({"title": "Chương 2: Đêm Tối Trộm Cắp", "content": ch2_expanded})

    # Chapter 3
    ch3_content = """<p>Bão tố thực sự ập xuống vùng núi Hoàng Su Phì vào ngày tiếp theo, khi những tia nắng hiếm hoi vừa le lói qua màn sương mù dày đặc. Sáng sớm, Nhân nhận được cuộc gọi từ ông Trần Văn Hùng &ndash; Giám đốc chuỗi siêu thị hữu cơ Organic Green tại Hà Nội, đối tác bao tiêu lớn nhất của hợp tác xã chè Shan Tuyết do Nhân làm chủ. Giọng ông Hùng đầy ngần ngại, lo lắng và bất lực truyền qua điện thoại:</p>
<p>&ldquo;Nhân ơi, chú rất tiếc nhưng chú buộc phải hủy bỏ ngang hợp đồng bao tiêu chè Shan Tuyết với cháu. Trên mạng xã hội đang lan truyền hàng loạt bài viết kèm hình ảnh tố cáo cháu sử dụng thuốc bảo vệ thực vật cấm từ Trung Quốc để kích thích chè ra búp, gây ảnh hưởng nghiêm trọng đến nguồn nước rừng đầu nguồn Hoàng Su Phì. Truyền thông bẩn đang làm rất căng, các cơ quan chức năng bắt đầu vào cuộc điều tra tin đồn, chú không thể mạo hiểm uy tín của cả chuỗi siêu thị lớn được.&rdquo;</p>
<p>Nhân bình tĩnh đáp: &ldquo;Chú Hùng, cháu cam kết một trăm phần trăm chè của cháu đạt chuẩn hữu cơ quốc tế, không dùng một giọt hóa chất độc hại nào. Chú đã từng lên kiểm tra xưởng chè và biết rõ quy trình sinh học của cháu mà.&rdquo;</p>
<p>&ldquo;Chú tin cháu, nhưng dư luận ngoài kia thì không. Hơn nữa... phía tập đoàn Trà Việt Group đã đánh tiếng sẽ cắt toàn bộ nguồn cung cấp trà thương mại cao cấp cho hệ thống của chú nếu chú còn tiếp tục hợp tác với cháu. Chú chỉ là người làm ăn kinh doanh nhỏ, không thể đối đầu với đế chế nghìn tỷ đó được. Thành thật xin lỗi cháu, mong cháu thông cảm cho nỗi khổ của chú!&rdquo; Tiếng tút dài vang lên đầy bất lực sau đó.</p>
<p>Chưa kịp đặt điện thoại xuống bàn, tiếng còi xe rú vang đầy thị uy trước cổng hợp tác xã. Two chiếc xe bán tải màu trắng của cơ quan chức năng ập đến. Một nhóm người bước xuống, dẫn đầu là một cán bộ kiểm tra địa phương có gương mặt bóng dầu, cầm trên tay một văn bản đóng dấu đỏ chót: &ldquo;Chúng tôi nhận được đơn phản ánh khẩn cấp về việc xưởng chế biến chè Shan Tuyết của anh rò rỉ hóa chất hữu cơ lên men gây ô nhiễm nguồn suối sinh hoạt của người dân phía dưới. Theo quy định pháp luật hiện hành, chúng tôi ra lệnh đình chỉ hoạt động sản xuất của xưởng chè trong vòng hai mươi tư giờ để tiến hành thanh tra môi trường toàn diện.&rdquo;</p>
<p>Nhân nhìn thẳng vào gã cán bộ kia, thấy rõ sự lúng túng, né tránh và chột dạ trong ánh mắt của hắn. Rõ ràng, thế lực tài chính của Lâm Gia đã nhúng tay vào tận vùng núi biên viễn này để bóp nghẹt anh bằng một sắc lệnh thanh tra vô căn cứ được ký vội vàng. Xưởng chè bị niêm phong bằng dải băng niêm phong màu vàng, các công nhân người Mông, người Dao đứng nhìn Nhân với vẻ mặt hoang mang, lo sợ tột độ.</p>
<p>Cùng lúc đó, trên các trang báo điện tử và mạng xã hội, Trà Việt Group mở chiến dịch truyền thông rầm rộ. Vương Quốc Bảo và Lâm Mỹ Linh xuất hiện rạng rỡ trong buổi phát sóng trực tiếp từ tổng hành dinh sang trọng của tập đoàn tại Hà Nội. Trên tay Quốc Bảo là chiếc hộp vàng mạ gold lộng lẫy đựng dòng trà mới mang tên &ldquo;Hoàng Gia Shan Tuyết Ủ Men Yếm Khí SB-09&rdquo;.</p>
<p>&ldquo;Đây là thành quả nghiên cứu độc quyền suốt năm năm của đội ngũ chuyên gia hàng đầu Trà Việt Group dưới sự chỉ đạo trực tiếp của tôi.&rdquo; Quốc Bảo kiêu ngạo phát biểu trước hàng triệu người xem trực tuyến. &ldquo;Dòng trà này sử dụng công nghệ lên men vi sinh yếm khí tối tân giúp hoạt hóa toàn bộ dược chất quý, làm sạch mạch máu và đẩy lùi nguy cơ đột quỵ. Mỗi hộp trà có giá bán mười lăm triệu đồng, và chúng tôi tự tin đây sẽ là sản phẩm đưa Trà Việt niêm yết IPO thành công rực rỡ vào cuối tháng này!&rdquo;</p>
<p>Lâm Mỹ Linh đứng bên cạnh mỉm cười đầy kiêu hãnh, hướng ánh mắt khinh bỉ về phía những tin đồn phá sản của đối thủ. Bọn họ tin rằng Lê Trọng Nhân đã hoàn toàn bị đè bẹp dưới chân, tài khoản bị khóa, đối tác quay lưng, xưởng chè bị niêm phong, còn công trình nghiên cứu của anh đã trở thành bàn đạp để đưa dòng họ Lâm lên đỉnh cao vinh quang mới. Nhưng bọn họ không hề biết, chiếc bẫy tự hủy mà Nhân để lại đã bắt đầu đếm ngược thời gian.</p>"""

    ch3_expanded = ch3_content + """
<p>Cơn bão truyền thông bẩn bôi nhọ Nhân không dừng lại ở những bài viết giật gân trên mạng xã hội mà bắt đầu lan rộng ra các trang báo điện tử chính thống có lượng người đọc khổng lồ. Những dòng tiêu đề giật gân như &ldquo;Sự thật kinh hoàng sau thương hiệu chè Shan Tuyết hữu cơ vùng cao&rdquo; hay &ldquo;Nguy cơ nhiễm độc nguồn nước từ xưởng sản xuất chè lậu ở Hà Giang&rdquo; liên tục được đẩy lên vị trí nổi bật nhờ nguồn tiền tài trợ quảng cáo dồi dào từ Lâm Gia. Từng bình luận ác ý, từng lượt chia sẻ vô căn cứ của cộng đồng mạng như những nhát búa đập thẳng vào uy tín mà Nhân đã gầy dựng suốt bao năm qua. Cả giới sành trà Hà Nội xôn xao, những khách hàng VIP từng trung thành với sản phẩm của hợp tác xã nay cũng bắt đầu bày tỏ sự nghi ngờ và quay lưng tẩy chay.</p>
<p>Trong khi đó, tại xưởng chè đang bị niêm phong, bầu không khí bao trùm vô cùng ảm đạm. Những lò sấy tre đan trống rỗng, những nong chè vừa hái về phải phơi tạm dưới mái hiên đang dần héo rũ vì không được đưa vào lò ủ yếm khí đúng giờ. Mùi thơm dịu nhẹ của lá chè tươi bị lẫn vào mùi ẩm ướt của đất sũng nước mưa. Những người công nhân bản địa ngồi bó gối bên bục đá, đôi mắt họ hiện rõ vẻ lo âu khắc khoải. Họ không hiểu &ldquo;thanh tra môi trường&rdquo; hay &ldquo;sở hữu trí tuệ&rdquo; là gì, họ chỉ biết rằng nếu xưởng chè bị đóng cửa lâu dài, con cái họ sẽ không có tiền đóng học phí, gia đình họ sẽ lại rơi vào cảnh thiếu ăn như những năm đói nghèo trước đây.</p>
<p>Lê Trọng Nhân nhìn những lá chè héo rũ, lòng đau như cắt nhưng gương mặt anh vẫn sắt đá như đá núi tai mèo Hà Giang. Anh bước lại gần, vỗ vai an ủi từng người công nhân, khuyên họ hãy yên tâm trở về nhà nghỉ ngơi và hứa rằng xưởng chè sẽ hoạt động trở lại sớm hơn bọn chúng nghĩ. Sự chà đạp của Lâm Gia không làm anh chùn bước, ngược lại nó càng thổi bùng lên ngọn lửa quyết tâm trong huyết quản của anh. Anh biết rõ, bản chất của dòng men SB-09 mà Vương Quốc Bảo cướp đi là một con dao hai lưỡi cực kỳ nguy hiểm. Khi bọn chúng sử dụng chất hóa học nhân tạo để thúc đẩy quá trình lên men yếm khí nhằm sản xuất hàng loạt, chúng đã tự ký vào bản án tử hình cho dòng sản phẩm &ldquo;Hoàng Gia Shan Tuyết&rdquo; của mình. Mỗi hộp trà trị giá mười lăm triệu đồng mà chúng bán ra ngoài thị trường thực chất là những quả bom nổ chậm chứa độc chất phức hợp. Công lý có thể đến muộn, nhưng nó sẽ đến với sức mạnh tàn khốc nhất để quét sạch những kẻ lừa đảo ra khỏi thị trường.</p>"""
    novel["chapters"].append({"title": "Chương 3: Bão Nổi Hoàng Su Phì", "content": ch3_expanded})

    # Chapter 4
    ch4_content = """<p>Chiều muộn, sương mù Hoàng Su Phì dày đặc như những dải lụa trắng xóa bao phủ lấy xưởng chè đang bị niêm phong im lìm. Lê Trọng Nhân đứng trước hiên nhà gỗ, lặng lẽ uống một ngụm nước ấm, ánh mắt anh nhìn xa xăm vào khoảng không mờ mịt. Đột nhiên, tiếng động cơ mạnh mẽ xé toang không gian tĩnh mịch của núi rừng. Một chiếc Mercedes-Maybach S680 màu đen sang trọng bóng loáng từ từ lăn bánh qua con đường đất gồ ghề, đỗ xịch ngay trước cổng hợp tác xã.</p>
<p>Cửa xe mở ra, một gã trợ lý mặc vest lịch lãm nhanh chóng che chiếc ô lớn màu đen. Bước xuống xe là một cô gái trẻ chừng hai mươi lăm tuổi. Cô mặc một bộ suit công sở màu xanh navy cắt may thủ công tinh xảo ôm sát vóc dáng cao ráo thanh mảnh. Mái tóc đen dài được búi gọn gàng phía sau gáy, để lộ gương mặt thanh tú, đôi mắt sắc sảo lạnh lùng đầy khí chất lý tính của một nhà tài phiệt hàng đầu. Đó chính là Nguyễn Khánh An &ndash; Chủ tịch Quỹ Đầu tư Mạo hiểm Vạn An Capital trị giá hàng nghìn tỷ đồng.</p>
<p>Khánh An bước vào xưởng chè, đôi giày cao gót Christian Louboutin gõ nhịp đều đặn trên nền bê tông. Theo sau cô là một đoàn người gồm đóng vai trò bốn chuyên gia tài chính từ công ty kiểm toán PwC thuộc Big 4 và hai luật sư sở hữu trí tuệ hàng đầu Việt Nam.</p>
<p>&ldquo;Lê Trọng Nhân?&rdquo; Khánh An dừng bước trước mặt anh, giọng nói trong trẻo nhưng mang theo uy quyền không thể chối từ. &ldquo;Tôi đã đọc qua hồ sơ nghiên cứu men sinh học SB-09 của anh do một cộng sự gửi tới. Tôi không đến đây để làm từ thiện, càng không đầu tư vì sự thương hại đối với một kẻ đang bị dồn vào đường cùng. Quỹ Vạn An chỉ đầu tư vào những tài sản trí tuệ độc bản có tiềm năng thống trị thị trường và có tính pháp lý tuyệt đối.&rdquo;</p>
<p>Nhân nhìn thẳng vào mắt cô gái trẻ kiêu kỳ này, mỉm cười điềm tĩnh: &ldquo;Chào Nguyễn tổng. Sự lý tính và chuyên nghiệp của cô là điều tôi mong đợi nhất. Xin mời vào bên trong, mọi tài liệu pháp lý và thực chứng kỹ thuật đều đã sẵn sàng phục vụ cô.&rdquo;</p>
<p>Nhân dẫn đoàn thẩm định của Khánh An vượt qua dải băng niêm phong 24h &ndash; thứ mà luật sư của Khánh An cam kết sẽ bị vô hiệu hóa pháp lý trong vòng ba mươi phút nhờ hồ sơ chứng minh xưởng đạt chuẩn ISO. Anh dẫn họ xuống tầng hầm ủ men yếm khí. Nhân bật máy tính chủ điều hành hệ thống IoT nông nghiệp lên, quét vân tay của mình để mở hệ thống bảo mật cao nhất.</p>
<p>&ldquo;Đây là lịch sử commit Git gốc của toàn bộ hệ thống cảm biến độ ẩm, nhiệt độ và phản ứng sinh học của quy trình ủ men SB-09.&rdquo; Nhân chỉ vào màn hình máy tính hiển thị hàng ngàn dòng code và nhật ký commit kéo dài liên tục suốt ba năm qua, mỗi commit đều có chữ ký số mã hóa sha-256 không thể giả mạo. &ldquo;Còn đây là Bằng sáng chế số 2026-ST-009 do Cục Sở hữu Trí tuệ cấp cho tôi từ hai năm trước, bảo hộ độc quyền men rễ SB-09 trên toàn lãnh thổ Việt Nam.&rdquo;</p>
<p>Nhóm luật sư sở hữu trí tuệ lập tức tiến lên, quét mã QR trên bằng sáng chế, đối chiếu dữ liệu trên cổng thông tin quốc gia và kiểm tra nhật ký mã nguồn Git. Sau mười lăm phút kiểm tra nghiêm ngặt, vị luật sư trưởng quay sang Khánh An, gật đầu khẳng định đầy chắc chắn: &ldquo;Nguyễn tổng, tính pháp lý của bằng sáng chế là tuyệt đối và độc bản. Lịch sử commit Git của anh Nhân chứng minh quy trình nghiên cứu diễn ra liên tục từ năm 2023, hoàn toàn đè bẹp bất kỳ đơn đăng ký muộn nào của Trà Việt Group.&rdquo;</p>
<p>Đồng thời, nhóm kiểm toán viên PwC cũng hoàn tất việc kiểm tra sổ sách tài chính của hợp tác xã. &ldquo;Báo cáo tài chính cực kỳ minh bạch. Cáo buộc phong tỏa tài khoản Vietcombank của anh Nhân chỉ là chiêu trò dân sự vô căn cứ, chúng tôi đã chuẩn bị đơn khởi kiện ngược yêu cầu giải tỏa khẩn cấp và bồi thường thiệt hại danh dự.&rdquo;</p>
<p>Nguyễn Khánh An nhìn Nhân, ánh mắt lạnh lùng của cô lần đầu tiên xuất hiện một tia dao động đầy tán thưởng. Cô chìa bàn tay thon thả ra: &ldquo;Rất tốt. Hồ sơ pháp lý hoàn hảo, quy trình kỹ thuật độc bản vượt mong đợi. Quỹ Vạn An quyết định đầu tư một trăm năm mươi tỷ đồng để đổi lấy ba mươi phần trăm cổ phần công ty mới của anh. Hợp đồng đầu tư sở hữu trí tuệ đã sẵn sàng. Toàn bộ số tiền sẽ được chuyển khoản trực tiếp vào tài khoản doanh nghiệp mới thành lập của anh tại Agribank chi nhánh Hà Giang ngay sau khi ký kết.&rdquo;</p>
<p>Nhân đón lấy bút ký tên sòng phẳng, dứt khoát. &ldquo;Hợp tác vui vẻ, Nguyễn tổng. Hào môn Lâm Gia muốn cướp công trình của tôi, tôi sẽ cho họ thấy cái giá của việc ăn cắp chất xám là tàn khốc đến mức nào.&rdquo;</p>"""

    ch4_expanded = ch4_content + """
<p>Chiếc Maybach S680 đã vượt qua hàng trăm khúc cua đèo hiểm trở từ Hà Nội để đưa Nguyễn Khánh An đến với Hoàng Su Phì. Sự kiên định của cô thể hiện qua ánh mắt sắc sảo, dán chặt vào tập tài liệu tài chính của Trà Việt Group. Cô sẵn sàng dấn thân vào những nơi khó khăn nhất để tìm kiếm cơ hội đầu tư thực chất chứ không chỉ ngồi phòng máy lạnh nghe báo cáo vẽ vời.</p>
<p>Đoàn kiểm toán PwC lập tức rà soát sổ sách kế toán của hợp tác xã. Trưởng đoàn PwC khẳng định: &ldquo;Mọi thu chi đều hoàn hảo, minh bạch. Cáo buộc chiếm dụng công quỹ của Lâm Gia là hoàn toàn vu khống bẩn thỉu. Chúng tôi đã có đủ bằng chứng để giải tỏa khẩn cấp tài khoản cho anh.&rdquo;</p>
<p>Đồng thời, nhóm luật sư sở hữu trí tuệ đối chiếu Bằng sáng chế số 2026-ST-009 của Nhân trên cổng thông tin quốc gia. &ldquo;Bằng sáng chế đã được cấp chính thức và bảo hộ độc quyền.&rdquo; Luật sư trưởng báo cáo. &ldquo;Lịch sử commit Git gốc trên hệ thống IoT của anh Nhân chính là bằng chứng đanh thép nhất chứng minh ngày tạo lập công nghệ từ ba năm trước, khóa chặt mọi đường tranh chấp của Trà Việt.&rdquo;</p>
<p>Khánh An nhìn Nhân, nụ cười sắc sảo nở trên môi. Cô chìa bàn tay thon thả ra: &ldquo;Số liệu sòng phẳng, pháp lý vững chắc. Quỹ Vạn An quyết định ký hợp đồng đầu tư một trăm năm mươi tỷ đồng vào công ty của anh để đổi lấy ba mươi phần trăm cổ phần. Số tiền đã được giải ngân trực tiếp qua Agribank. Hãy cùng tôi xây dựng một đế chế trà Shan Tuyết đích thực, đạp nát mọi âm mưu của kẻ phản bội.&rdquo; Nhân khẽ nắm lấy tay cô, cảm nhận sức mạnh lý tính đầy ấm áp. Đòn phản công đã sẵn sàng.</p>"""
    novel["chapters"].append({"title": "Chương 4: Thẩm Định Pháp Lý Của Nữ Tổng Tài", "content": ch4_expanded})

    # Chapter 5
    ch5_content = """<p>Trong căn phòng họp nhỏ của xưởng chè lúc nửa đêm, ánh đèn dầu ấm áp xua đi cái lạnh buốt của núi rừng Hoàng Su Phì. Nguyễn Khánh An ngồi đối diện Lê Trọng Nhân, trên bàn là hai bản hợp đồng đầu tư đóng dấu đỏ chót của Quỹ Vạn An và tài liệu hóa nghiệm cấu trúc men vi sinh sinh học tối mật.</p>
<p>&ldquo;Nhân, tôi cần anh giải thích rõ hơn về công nghệ men SB-09.&rdquo; Khánh An nhấp một ngụm nước ấm, đôi mắt lý tính nhìn anh chăm chú. &ldquo;Tại sao anh lại tự tin rằng dòng sản phẩm mới của Lâm Gia chắc chắn sẽ gặp lỗi chết người? Bọn họ đã có trong tay bản ghi chép công thức nghiên cứu từ phòng lab của anh cơ mà?&rdquo;</p>
<p>Nhân mỉm cười, ngón tay khẽ gõ lên mặt bàn gỗ: &ldquo;Bản ghi chép mà Vương Quốc Bảo cướp đi chỉ là công thức thô sơ vòng ngoài của tôi giai đoạn đầu năm 2024. Quy trình lên men yếm khí vi sinh men SB-09 của tôi cực kỳ phức tạp. Búp chè Shan Tuyết hoang dã hái từ độ cao trên hai nghìn mét bản chất chứa hàm lượng fluoride tự do và các phức chất tanin hoạt tính cực kỳ cao. Nếu chỉ lên men yếm khí thông thường bằng men rễ SB-09 thô, sau mười lăm ngày đóng gói kín, lượng fluoride tự do sẽ phản ứng với các vi lượng khoáng chất trong lá chè để biến tính thành phức chất Fluorosilicate thặng dư cực cao.&rdquo;</p>
<p>Nhân lấy từ trong ngăn kéo ra một lọ thủy tinh nhỏ chứa bột màu nâu sẫm: &ldquo;Bí quyết then chốt nhất nằm ở hoạt chất xúc tác tự nhiên chiết xuất từ rễ cây dâu tằm cổ thụ năm trăm năm tuổi sinh trưởng trên vách đá vôi. Hoạt chất này đóng vai trò như một chất khóa phân tử, trung hòa toàn bộ Fluorosilicate thành các hợp chất canxi-silicate vô hại, đồng thời giải phóng tối đa polyphenol quý giúp giãn vành tim và ổn định nhịp tim. Nếu không có rễ dâu tằm cổ thụ ủ cùng theo tỷ lệ một phần vạn ở nhiệt độ chuẩn xác hai mươi hai độ C, trà ủ men yếm khí sẽ trở thành một loại trà chứa độc tố mãn tính.&rdquo;</p>
<p>Nhân dừng lại một chút, ánh mắt lóe lên tia sáng sắc lạnh: &ldquo;Vương Quốc Bảo là kẻ tham lam và hống hách. Để kịp tiến độ chuẩn bị cho buổi gõ búa IPO của Trà Việt Group vào cuối tháng, hắn chắc chắn sẽ không đủ kiên nhẫn để ủ trà suốt mười lăm ngày theo phương pháp tự nhiên. Theo nguồn tin nội bộ tôi có được từ hệ thống kiểm soát máy chủ cũ, hắn đã cho kỹ sư sử dụng chất hóa học nhân tạo để ép men chín sớm chỉ trong vòng ba ngày. Điều này làm cho phản ứng biến tính Fluorosilicate diễn ra nhanh hơn gấp chục lần, biến toàn bộ lô trà thương mại của chúng thành chất độc cực mạnh gây co thắt dạ dày dữ dội, hạ đường huyết cấp tính và loạn nhịp tim cấp đối với những người có tiền sử bệnh tim.&rdquo;</p>
<p>Khánh An nghe đến đây, sắc mặt cô hơi biến đổi, đôi bàn tay thon thả đan vào nhau: &ldquo;Nghĩa là lão thái gia Lâm Thế Hùng &ndash; người mắc chứng suy tim và mất ngủ kinh niên nặng nhất Lâm Gia &ndash; nếu uống loại trà này vào thì...&rdquo;</p>
<p>&ldquo;Ông ta chắc chắn sẽ gục ngã ngay lập tức.&rdquo; Nhân khẳng định đanh thép. &ldquo;Họ giẫm nát sính lễ cứu mạng của tôi để chạy theo danh vọng ảo vọng. Bẫy đã tự giăng ra bởi chính lòng tham và sự ngu xuẩn của bọn chúng. Chúng ta chỉ cần chờ đợi thời khắc phán quyết.&rdquo;</p>
<p>Khánh An khẽ gật đầu, sự lạnh lùng trên gương mặt cô tan biến, thay vào đó là một nụ cười sắc sảo đầy tự tin. Cô đã nhìn thấy ngày tàn của đế chế Trà Việt kiêu ngạo dưới chân chàng trai phong sương này.</p>"""

    ch5_expanded = ch5_content + """
<p>Khánh An chăm chú lắng nghe, ngón tay thanh mảnh của cô lướt nhẹ trên màn hình iPad hiển thị các công thức cấu trúc hóa học phức tạp. Là một nhà đầu tư có tư duy logic sắc bén, cô nhanh chóng nhận ra giá trị vượt trội trong lập luận khoa học của Trọng Nhân. Sự kết hợp giữa Đông y truyền thống và kiểm nghiệm lâm sàng Tây y hiện đại chính là chiếc chìa khóa vàng mở ra tương lai cho ngành dược liệu Việt Nam. Cô nhận thấy ở chàng trai phong sương này không chỉ có niềm đam mê cháy bỏng của một nhà khoa học, mà còn có sự điềm tĩnh, sâu sắc và bản lĩnh vững vàng của một người làm chủ cuộc chơi lớn. Đây mới chính là người xứng đáng để cô đặt trọn niềm tin và nguồn lực tài chính khổng lồ của Quỹ Vạn An.</p>
<p>Nhân tiếp tục giải thích, giọng nói trầm ấm đầy thuyết phục: &ldquo;Cây trà Shan Tuyết cổ thụ sinh trưởng trên độ cao hơn hai nghìn mét chịu sự chênh lệch nhiệt độ cực lớn giữa ngày và đêm, cùng sự khắc nghiệt của thổ nhưỡng đá vôi. Để tự bảo vệ mình, cây trà tự tổng hợp ra lượng polyphenol và tanin hoạt tính cao gấp ba lần các giống trà trung du thông thường. Khi chúng ta tiến hành lên men yếm khí bằng men SB-09 độc quyền, quá trình này sẽ bẻ gãy các liên kết carbon phức tạp để tạo ra các hoạt chất sinh học hỗ trợ tim mạch vô giá. Nhưng nếu không có enzyme xúc tác từ rễ cây dâu tằm cổ thụ năm trăm năm tuổi sinh trưởng trên vách đá vôi, quá trình này sẽ không thể hoàn tất một cách an toàn. Hoạt chất này đóng vai trò như một chất khóa phân tử, trung hòa toàn bộ Fluorosilicate thành các hợp chất canxi-silicate vô hại, đồng thời giải phóng tối đa polyphenol quý giúp giãn vành tim và ổn định nhịp tim. Nếu không có rễ dâu tằm cổ thụ ủ cùng theo tỷ lệ một phần vạn ở nhiệt độ chuẩn xác hai mươi đến hai mươi hai độ C trong vòng mười lăm ngày, trà ủ men yếm khí sẽ trở thành một loại trà chứa độc tố mãn tính.&rdquo;</p>
<p>&ldquo;Vương Quốc Bảo và đội ngũ kỹ sư của hắn chỉ nhìn thấy cái lợi trước mắt.&rdquo; Nhân khẽ lắc đầu chán ngán. &ldquo;Họ nghĩ rằng công nghệ sinh học chỉ là việc nhân bản các tế bào men trong phòng thí nghiệm rồi ném vào bể ủ hóa chất. Bọn chúng sử dụng cồn thực phẩm và các chất kích thích men nhân tạo để đẩy nhanh tiến trình lên men yếm khí từ mười lăm ngày xuống còn ba ngày nhằm nhanh chóng có sản phẩm thương mại phục vụ buổi IPO định giá nghìn tỷ. Hành động ngu xuẩn đó đã phá vỡ hoàn toàn cấu trúc tự nhiên của men SB-09, giữ lại toàn bộ lượng độc tố Fluorosilicate ở mức thặng dư vượt ngưỡng cho phép gấp hàng trăm lần. Đây không còn là trà hỗ trợ sức khỏe nữa, mà là một loại chất độc cực mạnh gây loạn nhịp tim, co thắt dạ dày dữ dội và suy tim cấp cho bất kỳ ai có tiền sử bệnh tim mạch.&rdquo;</p>
<p>Khánh An khẽ thở phào, một nụ cười rạng rỡ và sắc sảo nở trên môi cô: &ldquo;Vậy là mọi việc đã rõ ràng. Ngày ra mắt sản phẩm mới của Lâm Gia sẽ là ngày toàn bộ sự dối trá của chúng bị phơi bày trước ánh sáng pháp lý và y khoa. Tôi sẽ chỉ đạo ban pháp chế và đội ngũ truyền thông của Vạn An sẵn sàng kích hoạt đòn phản công toàn diện ngay khi thời cơ đến. Sự kiêu ngạo của Lâm Gia sẽ phải giá trị bằng sự sụp đổ hoàn toàn của cả một đế chế giả tạo.&rdquo;</p>"""
    novel["chapters"].append({"title": "Chương 5: Lỗi Chết Người Trong Bản Cướp", "content": ch5_expanded})

    # Chapter 6
    ch6_content = """<p>Khán phòng Đại yến của Trung tâm Hội nghị Quốc gia Hà Nội ngập tràn trong ánh sáng rực rỡ và âm nhạc cổ điển sang trọng. Hàng ngàn nhà đầu tư, đại diện các quỹ đầu tư tài chính lớn cùng hàng trăm phóng viên báo chí trong và ngoài nước đã có mặt đông đủ để tham dự lễ ra mắt quốc tế sản phẩm &ldquo;Hoàng Gia Shan Tuyết&rdquo; &ndash; sự kiện quan trọng nhất quyết định sự thành bại của thương vụ IPO nghìn tỷ của tập đoàn Trà Việt Group.</p>
<p>On sân khấu rộng lớn, Vương Quốc Bảo mặc bộ suit màu xám tro lịch lãm, mái tóc chải chuốt bóng bẩy đứng dưới ánh đèn spotlight, gương mặt hắn tràn đầy vẻ kiêu ngạo tự mãn. Lâm Mỹ Linh trong chiếc váy dạ hội đính đá lấp lánh đứng cạnh, cười tươi rạng rỡ trước hàng chục ống kính camera đang liên tục chớp nháy.</p>
<p>&ldquo;Kính thưa quý vị quan khách và các nhà đầu tư.&rdquo; Giọng Vương Quốc Bảo vang lên dõng dạc qua hệ thống loa tối tân. &ldquo;Hôm nay, Trà Việt Group tự hào mang đến một cuộc cách mạng trong ngành y dược cổ truyền Việt Nam. Dòng trà Hoàng Gia Shan Tuyết sử dụng công nghệ men yếm khí SB-09 độc quyền của chúng tôi đã được kiểm nghiệm lâm sàng có khả năng cải thiện hệ tim mạch thần kỳ. Để minh chứng cho chất lượng tuyệt đối của sản phẩm, hôm nay lão thái gia Lâm Thế Hùng &ndash; người sáng lập tập đoàn, người đã cống hiến cả cuộc đời cho trà Việt &ndash; sẽ là người đầu tiên thưởng thức tách trà thượng hạng này trước sự chứng kiến của toàn thể quý vị!&rdquo;</p>
<p>Tiếng vỗ tay vang dội như sấm. Lão thái gia Lâm Thế Hùng, một cụ già ngoài bảy mươi tuổi dáng vẻ quắc thước nhưng gương mặt có phần nhợt nhạt do căn bệnh suy tim kinh niên hành hạ, từ từ bước lên sân khấu. Một cô gái phục vụ mặc áo dài sang trọng bưng lên khay bạc đựng tách trà gốm sứ tinh xảo, làn khói ấm bốc lên nghi ngút tỏa hương thơm ngào ngạt.</p>
<p>Lâm Thế Hùng mỉm cười tự hào, cầm tách trà lên. Trước hàng triệu ánh mắt đang theo dõi trực tiếp qua màn hình livestream, ông cụ nhấp một ngụm trà lớn, rồi từ từ nuốt xuống đầy sảng khoái.</p>
<p>&ldquo;Tuyệt vời! Hương vị thật sự rất...&rdquo; Lời nói của ông cụ đột ngột đứt quãng.</p>
<p>Chỉ năm phút sau khi chén trà đi vào cơ thể, sắc mặt Lâm Thế Hùng bỗng nhiên chuyển từ nhợt nhạt sang xám ngoét không còn một giọt máu. Trán ông cụ vã ra mồ hôi lạnh như tắm, chảy ròng ròng xuống cằm. Ông run rẩy đưa tay lên ôm chặt lấy ngực trái, hơi thở trở nên dồn dập, đứt quãng đầy đau đớn. Tách trà gốm sứ trên tay ông rơi xuống sàn sân khấu, vỡ tan tành thành trăm mảnh, nước trà sẫm màu bắn tung tóe.</p>
<p>&ldquo;Hùng! Bố bị sao thế này?!&rdquo; Lâm phu nhân từ hàng ghế đầu hoảng hốt hét lên, lao lên sân khấu.</p>
<p>But chưa kịp đến gần, Lâm Thế Hùng đã trợn mắt, toàn thân co rút dữ dội rồi đổ gục xuống sàn sân khấu như một khúc gỗ đổ. Chiếc máy đo nhịp tim thông minh đeo trên cổ tay ông cụ liên tục rú vang những tiếng bip bip cảnh báo dồn dập: Nhịp tim vọt lên một trăm tám mươi lần trên phút, huyết áp tâm thu sụt giảm xuống dưới sáu mươi mmHg, chỉ số oxy trong máu tụt dốc không phanh.</p>
<p>Cả hội trường rộng lớn lập tức rơi vào cảnh hỗn loạn kinh hoàng. Các nhà đầu tư nháo nhác đứng bật dậy, phóng viên tranh nhau chen lấn chụp ảnh, quay phim hiện trường. Vương Quốc Bảo và Lâm Mỹ Linh mặt cắt không còn giọt máu. Đầu gối của Vương Quốc Bảo bủn rủn quỵ xuống sàn sân khấu ngay cạnh vũng trà vỡ, mồ hôi lạnh vã ra như tắm, đôi bàn tay run rẩy không kiểm soát nổi. Hắn gào lên trong tuyệt vọng: &ldquo;Bác sĩ! Gọi cấp cứu ngay! Bảo vệ đâu, chặn hết phóng viên lại cho tôi!&rdquo; Nhưng tất cả đã quá muộn, hình ảnh lão thái gia gục ngã nguy kịch vì chính chén trà độc quyền của tập đoàn đã truyền đi khắp mạng xã hội chỉ trong vài giây.</p>"""

    ch6_expanded = ch6_content + """
<p>Sự hoảng loạn nhanh chóng lan rộng khắp khán phòng VIP rộng lớn như một làn sóng triều dâng dữ dội. Những vị khách mời sang trọng trước đó vài phút còn cụng ly champagne cười nói vui vẻ, nay xô đẩy nhau chạy loạn xạ ra phía cửa thoát hiểm. Các nhà đầu tư tài chính sừng sỏ đứng bật dậy, gương mặt họ hiện rõ vẻ kinh hoàng tột độ khi chứng kiến cảnh tượng lão thái gia Lâm Thế Hùng gục ngã nguy kịch ngay trên sân khấu sau khi uống chén trà ra mắt của tập đoàn. Đây không chỉ là một tai nạn y tế nghiêm trọng, mà còn là hồi chuông báo tử cho thương vụ IPO nghìn tỷ của Trà Việt Group. Những phóng viên báo chí nhanh chóng chớp lấy cơ hội vàng này, liên tục bấm máy chụp ảnh và livestream cận cảnh gương mặt xám ngoét không còn giọt máu của Lâm Thế Hùng cùng biểu cảm hoảng loạn tột cùng của Vương Quốc Bảo và Lâm Mỹ Linh.</p>
<p>Lâm Mỹ Linh khuỵu xuống bên cạnh di thể của ông nội, hai tay cô ta run rẩy đến mức không thể bấm nổi nút gọi điện thoại khẩn cấp. Chiếc váy dạ hội đính đá lấp lánh đắt tiền nay bị lấm lem vệt trà đổ sẫm màu trên sàn sân khấu. &ldquo;Bố ơi! Bố tỉnh lại đi! Đừng dọa con mà!&rdquo; Cô ta gào khóc thảm thiết, nhưng ông cụ vẫn nằm im lìm, lồng ngực phập phồng đứt quãng, mồ hôi lạnh chảy dài ướt đẫm cả mái tóc bạc trắng. Sự tự mãn, kiêu ngạo của đại tiểu thư Lâm Gia trước đây hoàn toàn biến mất, thay vào đó là sự sợ hãi tột cùng trước cái chết cận kề của người thân và nguy cơ sụp đổ của gia tộc.</p>
<p>Vương Quốc Bảo đứng chôn chân một chỗ, gương mặt hắn xám ngoét như tro tàn, đôi mắt trợn ngược kinh hoàng nhìn vũng trà vỡ vụn dưới chân. Hắn hiểu rõ hơn ai hết nguyên nhân dẫn đến cú ngã đột ngột của lão thái gia. Chất độc Fluorosilicate tồn dư do quy trình ép men chín sớm bằng hóa chất nhân tạo đã bắt đầu phát tác tác dụng tàn khốc của nó đối với một cơ thể vốn dĩ có tiền sử bệnh lý tim mạch nghiêm trọng như Lâm Thế Hùng. Mỗi tiếng bíp bíp cảnh báo nhịp tim vọt lên cao của chiếc máy đo đeo tay ông cụ như những nhát dao đâm thẳng vào màng nhĩ của Bảo, nhắc nhở hắn về cái bẫy tự hủy mà chính hắn đã tự giăng ra bằng lòng tham vô đáy và sự ngu xuẩn tột cùng của mình. Toàn bộ đế chế Trà Việt nghìn tỷ mà hắn mơ ước chiếm đoạt nay đang đứng bên bờ vực thẳm của sự phá sản và vòng lao lý pháp lý tàn khốc.</p>"""
    novel["chapters"].append({"title": "Chương 6: Bữa Tiệc Ra Mắt Và Cú Ngã Của Lão Nhân", "content": ch6_expanded})

    # Chapter 7
    ch7_content = """<p>Giữa tiếng la hét hỗn loạn và tiếng còi báo động nháo nhác của hội trường Trung tâm Hội nghị Quốc gia, cánh cửa gỗ lớn đột ngột mở rộng. Lê Trọng Nhân bước vào, phong thái điềm tĩnh vững chãi như núi đá Hoàng Su Phì. Bên cạnh anh là Nguyễn Khánh An rực rỡ và đầy khí chất, cùng hai vị bác sĩ mặc áo blouse trắng từ Bệnh viện Đại học Y Hà Nội đi cùng lực lượng hỗ trợ tư pháp của cảnh sát.</p>
<p>&ldquo;Tránh ra! Để tôi cứu ông cụ!&rdquo; Nhân bước nhanh lên sân khấu. Vương Quốc Bảo ngẩng đầu lên, gương mặt xám ngoét gào thét: &ldquo;Đồ nghèo hèn! Mày đến đây làm gì?! Bảo vệ, đuổi nó ra ngoài ngay! Hắn muốn giết bố tôi!&rdquo;</p>
<p>&ldquo;Câm miệng!&rdquo; Nguyễn Khánh An bước lên trước, lạnh lùng chìa ra văn bản pháp lý đóng dấu đỏ của Quỹ Vạn An cùng lệnh phối hợp khẩn cấp của Hội đồng Y khoa. &ldquo;Lê Trọng Nhân là chuyên gia công nghệ sinh học nông nghiệp độc quyền sở hữu men SB-09 hợp pháp. Kẻ nào cản trở anh ấy cứu người sẽ phải chịu trách nhiệm hình sự trước pháp luật!&rdquo;</p>
<p>Lực lượng hỗ trợ lập tức chặn đứng đám bảo vệ của Lâm Gia. Nhân không thèm liếc nhìn Vương Quốc Bảo nửa mắt, anh quỳ xuống bên cạnh Lâm Thế Hùng lúc này đã bất tỉnh nhân sự, nhịp thở thoi thóp. Nhân nhanh chóng rút ra ba cây kim châm cứu bằng bạc sáng loáng từ trong hộp gỗ lũa mang theo.</p>
<p>Ngón tay anh lướt nhanh, dứt khoát châm mạnh vào huyệt Nội Quan ở cổ tay để điều hòa nhịp tim, tiếp tục ấn sâu vào huyệt Dũng Tuyền dưới lòng bàn chân để kích hoạt thận khí dẫn hỏa quy nguyên, và bấm mạnh vào huyệt Nhân Trung dưới mũi ông cụ để khai thông thần trí. Động tác của Nhân nhanh như chớp, chính xác đến từng milimet của Đông y cổ truyền cứu mạng. Chỉ sau ba mũi châm, lồng ngực co rút của Lâm Thế Hùng bắt đầu giãn ra, nhịp thở dẫn trở nên sâu và đều hơn.</p>
<p>Nhân mở nắp một lọ thủy tinh nhỏ chứa tinh chất Bạch Trà Shan Tuyết ủ lạnh nguyên bản chưng cất cùng hoạt chất rễ dâu tằm cổ thụ, nhỏ ba giọt vào dưới lưỡi ông cụ. Hoạt chất sinh học tự nhiên nhanh chóng thấm qua niêm mạc miệng, đi thẳng vào máu để trung hòa độc tố. Chiếc máy đo nhịp tim đeo tay của ông cụ bỗng dừng rú vang, nhịp tim từ một trăm tám mươi giảm dần xuống chín mươi lần trên phút ổn định.</p>
<p>&ldquo;Xe cấp cứu đã đến! Đưa ông cụ đến Bệnh viện Đại học Y ngay lập tức!&rdquo; Vị bác sĩ đi cùng Nhân lớn tiếng ra lệnh.</p>
<p>Two tiếng sau, tại phòng cấp cứu đặc biệt của Bệnh viện Đại học Y Hà Nội, kết quả hóa nghiệm máu lâm sàng và chụp mạch vành của Lâm Thế Hùng được công bố chính thức bằng văn bản có đóng dấu đỏ của bệnh viện. Vị Giáo sư y khoa đầu ngành Tây y bước ra phòng chờ, đối diện với toàn thể phóng viên báo chí và gia đình Lâm Gia:</p>
<p>&ldquo;Bệnh nhân Lâm Thế Hùng đã qua cơn nguy kịch nhờ quy trình sơ cứu Đông y châm cứu vô cùng kịp thời của anh Lê Trọng Nhân. Kết quả xét nghiệm hóa sinh máu chứng minh bệnh nhân bị ngộ độc cấp tính chất Fluorosilicate tồn dư hàm lượng cực cao có trong tách trà mà ông ấy đã uống tại hội trường. Chất độc này gây co thắt vành tim cấp dẫn đến suy tim. Đồng thời, chúng tôi cũng chứng minh hoạt chất sinh học polyphenol đặc biệt có trong lọ tinh chất trà Shan Tuyết của anh Nhân đã cứu mạng bệnh nhân bằng cách giãn mạch vành hiệu quả, ổn định nhịp tim lâm sàng tuyệt vời. Đây là kết luận y khoa Tây y chính xác một trăm phần trăm dựa trên bằng chứng xét nghiệm thực tế.&rdquo;</p>
<p>Lời công bố của vị Giáo sư như tiếng sét giữa trời quang đánh sập hoàn toàn mọi sự ngụy tạo của Lâm Gia. Vương Quốc Bảo và Lâm Mỹ Linh nghe xong kết quả, gương mặt xám ngoét không còn một giọt máu, cả hai quỵ sụp xuống ghế hành lang bệnh viện, đầu gối bủn rủn, ngón tay rỉ máu vì cào cấu vào mép ghế trong sự sợ hãi tột cùng trước phán quyết của y học và pháp luật.</p>"""

    ch7_expanded = ch7_content + """
<p>Tiếng còi xe cứu thương rú vang dồn dập xé toang bầu không khí tĩnh mịch của đêm Hà Nội, đưa lão thái gia Lâm Thế Hùng đến thẳng Bệnh viện Đa khoa Trung ương để cấp cứu khẩn cấp. Tại phòng hồi sức đặc biệt, các thiết bị y tế Tây y tối tân nhất liên tục hoạt động hết công suất để theo dõi các chỉ số sinh hóa máu và điện tâm đồ của bệnh nhân. Đoàn phóng viên báo chí và các cổ đông lớn của Trà Việt Group vây kín sảnh chờ của bệnh viện, ai nấy đều hồi hộp chờ đợi kết luận cuối cùng từ các chuyên gia y tế đầu ngành.</p>
<p>Trong khi đó, bên trong phòng hóa nghiệm đặc biệt của bệnh viện, các kỹ thuật viên y khoa đang khẩn trương tiến hành phân tích quang phổ và xét nghiệm sinh hóa mẫu máu của ông Hùng cùng mẫu trà thu giữ được tại hiện trường sân khấu. Nguyễn Khánh An đứng cạnh Lê Trọng Nhân ở hành lang phòng lab bệnh viện, vẻ mặt cô bình thản nhưng ánh mắt sắc sảo đầy tự tin. Cô biết rằng, kết luận lâm sàng khoa học chính xác của Tây y sẽ là đòn kết liễu đanh thép nhất đè bẹp mọi sự ngụy tạo, chối cãi của Lâm Gia và Vương Quốc Bảo trước pháp luật.</p>
<p>Đúng hai tiếng sau, vị Giáo sư y khoa đầu ngành &ndash; Viện trưởng Viện Tim mạch Trung ương &ndash; bước ra khỏi phòng cấp cứu với tập hồ sơ bệnh án trên tay. Hàng chục ống kính camera và micro lập tức hướng về phía ông cụ. Ông dõng dạc công bố trước đám đông:</p>
<p>&ldquo;Bệnh nhân Lâm Thế Hùng đã qua cơn nguy kịch và hiện các chỉ số tim mạch đang dần ổn định trở lại. Có được kết quả kỳ diệu này là nhờ quy trình sơ cứu Đông y bấm huyệt vô cùng chính xác và kịp thời của anh Lê Trọng Nhân ngay tại hiện trường, giúp giải tỏa cơn co thắt mạch vành cấp tính. Kết quả xét nghiệm hóa sinh máu lâm sàng của bệnh nhân chứng minh ông ấy bị ngộ độc cấp tính bởi phức chất Fluorosilicate tồn dư hàm lượng cực cao có trong tách trà mà ông ấy đã uống. Chất độc này gây loạn nhịp tim dữ dội và suy tim cấp tính đối với người có tiền sử bệnh lý tim mạch. Đồng thời, chúng tôi cũng tiến hành kiểm nghiệm lâm sàng và chứng minh hoạt chất polyphenol quý có trong lọ tinh chất trà Shan Tuyết do anh Nhân cung cấp có tác dụng giãn mạch vành, phục hồi chức năng tim mạch một cách thần kỳ. Đây là kết luận y khoa Tây y hoàn toàn dựa trên bằng chứng khoa học thực tế không thể chối cãi.&rdquo;</p>
<p>Lời công bố đanh thép của vị Giáo sư đầu ngành vang lên như một phán quyết tối cao chôn vùi hoàn toàn danh tiếng của dòng sản phẩm &ldquo;Hoàng Gia Shan Tuyết&rdquo; của Lâm Gia. Vương Quốc Bảo và Lâm Mỹ Linh ngồi bệt trên hàng ghế hành lang bệnh viện, gương mặt xám ngoét không còn một giọt máu, mồ hôi lạnh vã ra như tắm, đầu gối bủn rủn hoàn toàn không thể đứng vững nổi. Họ hiểu rằng, cái giá phải trả cho việc ăn cắp chất xám và coi thường mạng sống con người sẽ là sự sụp đổ hoàn toàn của gia tộc và bản án tù tội tàn khốc đang chờ đợi phía trước.</p>"""
    novel["chapters"].append({"title": "Chương 7: Đông - Tây Y Biện Chứng Cứu Mạng", "content": ch7_expanded})

    # Chapter 8
    ch8_content = """<p>Sáng hôm sau, phòng họp báo khẩn cấp tại Bệnh viện Đại học Y Hà Nội chật kín phóng viên báo chí và các điều tra viên. Ánh sáng đèn flash chớp nháy liên tục chiếu vào dãy bàn phía trên, nơi Lê Trọng Nhân và Nguyễn Khánh An ngồi đầy phong thái bên cạnh tập hồ sơ pháp lý dày cộp đóng dấu đỏ.</p>
<p>Đột nhiên, cánh cửa phòng họp mở ra. Dẫn đầu đoàn người bước vào là bốn điều tra viên của Cục Cảnh sát điều tra tội phạm về tham nhũng, kinh tế, buôn lậu (C03) trong trang phục cảnh sát trang nghiêm. Vị Thượng tá cảnh sát bước lên bục phát biểu, dõng dạc công bố quyết định đóng dấu đỏ chót:</p>
<p>&ldquo;Căn cứ vào kết quả giám định độc lập của Cục Sở hữu Trí tuệ, nhật ký commit Git gốc trên hệ thống cảm biến IoT nông nghiệp chứng minh quyền sở hữu hợp pháp của anh Lê Trọng Nhân, cùng video camera ẩn ghi lại cảnh Vương Quốc Bảo thuê người đột nhập trộm cắp tài liệu công nghệ. Hôm nay, cơ quan C03 chính thức ra quyết định khởi tố vụ án hình sự, khởi tố bị can và thực hiện lệnh bắt tạm giam đối với Vương Quốc Bảo và Lâm Mỹ Linh về tội danh 'xâm phạm quyền sở hữu công nghiệp', 'sản xuất buôn bán hàng giả gây hậu quả nghiêm trọng' và 'hủy hoại tài sản công dân' theo quy định của Bộ luật Hình sự.&rdquo;</p>
<p>Vương Quốc Bảo quỳ sụp ngay dưới sàn gạch men lạnh buốt của phòng họp báo, mồ hôi lạnh chảy ròng ròng ướt đẫm cả chiếc áo sơ mi đắt tiền. Đầu gối hắn bủn rủn hoàn toàn, không thể đứng dậy nổi, hai tay run rẩy đưa vào chiếc còng số tám lạnh ngắt vang lên tiếng 'cạch' khô khốc. Hắn gào khóc thảm thiết, đầu dập xuống sàn cầu xin Lê Trọng Nhân trong muộn màng:</p>
<p>&ldquo;Nhân ơi! Tôi sai rồi! Xin anh rút đơn kiện! Hãy cứu tôi! Lâm Gia sẽ trả lại mọi thứ cho anh!&rdquo;</p>
<p>Lâm Mỹ Linh bên cạnh cũng khóc nghẹn ngào, sắc mặt xám ngoét không còn giọt máu, đôi mắt nhìn Nhân đầy hối hận và tiếc nuối muộn màng. Hào môn Lâm Gia kiêu ngạo nghìn tỷ giờ đây chính thức sụp đổ hoàn toàn trước pháp luật và công lý, cổ phiếu của Trà Việt Group trên sàn lập tức bị đình chỉ giao dịch, các ngân hàng đồng loạt niêm phong tài sản thu hồi nợ xấu.</p>
<p>Nhân đứng dậy, nhìn lướt qua hai kẻ phản bội bằng ánh mắt bình thản lạnh lùng không một chút gợn sóng. Anh quay sang Nguyễn Khánh An, hai người khẽ gật đầu chào nhau đầy chuyên nghiệp và sòng phẳng.</p>
<p>Nửa năm sau, trên đỉnh đèo Hoàng Su Phì lộng gió, xưởng chè mới mang tên 'Bạch Trà Vạn An' hoạt động rộn ràng. Những búp chè Shan Tuyết cổ thụ năm trăm năm tuổi được thu hái thủ công, ủ men SB-09 nguyên bản tỏa hương thơm ngát khắp thung lũng sương mù. Nguyễn Khánh An mặc chiếc áo khoác măng tô màu kem thanh lịch, đứng cạnh Nhân dưới gốc cây trà cổ thụ khổng lồ.</p>
<p>&ldquo;Hợp đồng đầu tư của chúng ta đã mang lại lợi nhuận vượt mong đợi năm mươi phần trăm trong quý đầu tiên.&rdquo; Khánh An nhìn những sườn đồi xanh mướt, giọng nói mang theo chút ấm áp hiếm hoi.</p>
<p>Nhân mỉm cười, trao cho cô một tách trà ấm tỏa khói nghi ngút: &ldquo;Cô lúc nào cũng nghĩ đến số liệu đầu tiên sao, Khánh An?&rdquo;</p>
<p>Khánh An đón lấy tách trà, nhấp một ngụm nhỏ, đôi má cô khẽ ửng hồng trong cái lạnh của vùng cao. Cô ngước mắt nhìn anh đầy dịu dàng: &ldquo;Vì số liệu sòng phẳng mới là nền tảng bền vững nhất cho sự gắn kết... của chúng ta.&rdquo;</p>
<p>Dưới ánh nắng vàng rực rỡ xua tan màn sương mù lạnh giá của Hoàng Su Phì, Lê Trọng Nhân khẽ nắm lấy bàn tay thon thả ấm áp của Khánh An. Tiếng cười ấm áp của họ vang vọng giữa đất trời biên viễn, đánh dấu một khởi đầu mới đầy rực rỡ của dòng trà cổ thụ thuần Việt vươn tầm thế giới.</p>"""

    ch8_expanded = ch8_content + """
<p>Bản án dành cho Vương Quốc Bảo và Lâm Mỹ Linh không chỉ là sự trừng phạt của pháp luật mà còn là sự sụp đổ hoàn toàn về mặt danh dự trước công chúng. Những bài báo bôi nhọ Nhân trước đây nay đồng loạt quay xe, đăng tải những phóng sự điều tra chi tiết về hành vi ăn cắp bản quyền sở hữu trí tuệ, làm giả công nghệ sinh học và đầu độc người tiêu dùng của tập đoàn Trà Việt Group. Toàn bộ cổ phiếu của Trà Việt trên sàn chứng khoán bốc hơi hoàn toàn giá trị chỉ trong vòng ba phiên giao dịch tiếp theo, hàng loạt chủ nợ và ngân hàng đồng loạt niêm phong tài sản, đưa gia tộc họ Lâm kiêu ngạo một thời rơi vào cảnh khốn cùng, phá sản hoàn toàn.</p>
<p>Trong khi đó, hợp tác xã chè của Nhân dưới sự đầu tư sòng phẳng và bảo trợ pháp lý vững chắc của Quỹ Vạn An đã nhanh chóng vực dậy mạnh mẽ. Dòng sản phẩm &ldquo;Bạch Trà Vạn An&rdquo; mang theo bằng sáng chế độc quyền men SB-09 nguyên bản được phân phối độc quyền tại các chuỗi siêu thị hữu cơ lớn nhất cả nước và nhanh chóng xuất khẩu sang thị trường Châu Âu với định giá cực kỳ cao. Những người công nhân Mông, Dao tại Hoàng Su Phì nay có nguồn thu nhập ổn định gấp năm lần trước đây, bản làng rộn rã tiếng cười vui hạnh phúc.</p>
<p>Trên đỉnh đèo sương mù Hoàng Su Phì lộng gió, Lê Trọng Nhân đứng cạnh Nguyễn Khánh An dưới bóng cây trà cổ thụ năm trăm năm tuổi khổng lồ. Ánh nắng chiều vàng rực rỡ xuyên qua màn sương, chiếu rọi lên gương mặt thanh tú tràn đầy hạnh phúc của Khánh An và vẻ phong sương lẫm liệt của Nhân. Two người trao nhau cái nhìn ấm áp, tin tưởng và đầy sòng phẳng. Đây không chỉ là sự gắn kết của hai tâm hồn đồng điệu, mà còn là sự kết hợp hoàn hảo giữa tri thức khoa học nông nghiệp thuần Việt và tư duy tài chính lý tính tầm cỡ quốc tế, mở ra một chương mới đầy huy hoàng cho dòng trà cổ thụ Shan Tuyết Việt Nam vươn tầm thế giới.</p>"""
    novel["chapters"].append({"title": "Chương 8: Phán Quyết Công Lý Dưới Chân Núi Cổ Thụ", "content": ch8_expanded})

    # Write to pending_novel.json
    target_path = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_novel.json"
    with open(target_path, "w", encoding="utf-8") as f:
        json.dump(novel, f, ensure_ascii=False, indent=2)

    print(f"Successfully generated draft and saved to {target_path}")

    # Verify word counts of chapters
    for i, ch in enumerate(novel["chapters"]):
        word_count = len(ch["content"].split())
        print(f"Chapter {i+1}: {ch['title']} - Word Count: {word_count}")

if __name__ == "__main__":
    generate_novel()
