# -*- coding: utf-8 -*-
import json
import os

OUTPUT_FILE = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_novel.json"

def main():
    print("🚀 GENERATING PERFECT LACQUER NOVEL - V13 GOLD STANDARD (1000-1500 WORDS PER CHAPTER)")
    
    novel_blueprint = {
        "title": "Nghệ Nhân Sơn Mài Bị Khinh Rẻ Đuổi Khỏi Xưởng Tìm Ra Màu Sơn Thất Truyền Đè Bẹp Tập Đoàn Tranh Giả",
        "author": "Lâm Hoài Nam",
        "genre": "Sảng Văn",
        "intro": "<p><strong>\"Cút khỏi xưởng sơn mài họ Lâm ngay lập tức, loại tàn phế tay run như mày chỉ làm bẩn danh tiếng tranh truyền thống trăm năm!\"</strong></p>\n<p>Lời mắng chửi tàn nhẫn của Lâm Thế Hùng - ông chủ xưởng sơn mài Hùng Cát danh tiếng Bình Dương - như nhát búa đập tan sáu năm cống hiến thầm lặng của Trần Hoài Nam. Cứu bức họa bảo vật khỏi đám cháy, bàn tay Nam bị bỏng hóa chất nghiêm trọng, nhưng đổi lại chỉ là sự phản bội từ người thầy mình kính trọng và vị hôn thê Lâm Mỹ Hạnh, kẻ sẵn sàng huỷ hôn ước để chạy theo thiếu gia tập đoàn hóa chất công nghiệp.</p>\n<p>Giữa lúc bị đẩy vào đường cùng với đôi tay rỉ máu, Nam gặp Trịnh Hoàng Yến, nữ CFO lý tính và sắc sảo của Quỹ Nghệ thuật Vạn An. Bằng sự kết hợp kỳ diệu giữa bài thuốc Đông y phục hồi làn da và kiểm tra da liễu Tây y hiện đại, Nam lấy lại đôi tay thiên tài, tìm ra công thức sơn ta thất truyền ngàn năm. Cùng nhau, họ vạch trần âm mưu bôi nhọ của truyền thông bẩn, dùng sao kê ngân hàng đóng dấu đỏ, báo cáo kiểm toán Big 4 của EY và lệnh khởi tố từ C03 để đè bẹp đế chế tranh giả nghìn tỷ, đưa những kẻ phản bội ra trước ánh sáng công lý.</p>",
        "cover_prompt": "A highly detailed, luxury anime book cover depicting a handsome 28-year-old Vietnamese lacquer painting master meticulously painting glowing golden patterns on a dark wooden canvas. Beside him stands a beautiful, elegant 26-year-old corporate woman in a premium beige business suit, looking at the painting with admiration. In the background, ancient traditional Vietnamese wooden villa garden with beautiful moonlight and glowing golden fireflies, 1:1 ratio, without text, masterpiece, elegant cinematic lighting.",
        "chapters": []
    }
    
    # CHAPTER 1: Bàn tay phế và nhát búa đuổi khỏi xưởng
    ch1 = """<p>Mùi nhựa sơn ta hăng nồng quen thuộc quyện với mùi khói đen khét lẹt của dầu hỏa phả ra từ đống gỗ vụn cháy dở ở góc sân. Trần Hoài Nam đứng im lìm như một pho tượng đá trước cửa phòng trưng bày lớn của xưởng sơn mài Hùng Cát danh tiếng khắp đất Bình Dương. Đôi mắt anh đờ đẫn, nhìn chăm trừng vào tờ quyết định sa thải đóng dấu đỏ chói lọi đặt lạnh lùng trên chiếc bàn gỗ trắc bóng loãng. Mười đầu ngón tay của anh, vốn là thứ báu vật tinh hoa nhất của xưởng, có thể cảm nhận từng hạt bụi mịn nhỏ nhất trên màng sơn khi thực hiện kỹ thuật mài nước dưới ánh trăng, giờ đây lại quấn chặt bằng những lớp băng gạc trắng toát, rỉ ra những vệt dịch vàng nhạt đầy đau đớn. Vết bỏng hóa chất từ vụ hỏa hoạn kinh hoàng ba tuần trước, khi anh lao mình vào đám cháy để cứu bức tranh bảo vật "Bản sắc ngàn năm" - công trình tâm huyết của cả gia đình nhạc phụ tương lai - vẫn chưa hề khép miệng, thỉnh thoảng lại nhói lên từng cơn giật thắt tận xương tủy.</p>
<p>"Cút khỏi xưởng sơn mài họ Lâm ngay lập tức! Loại tàn phế tay run như mày chỉ làm bẩn danh tiếng tranh truyền thống trăm năm của dòng họ chúng tao!" Lời mắng chửi tàn nhẫn, lạnh lùng phát ra từ miệng Lâm Thế Hùng - người nhạc phụ tương lai và cũng là người thầy mà anh từng tôn kính, phụng dưỡng suốt sáu năm qua như cha ruột. Ông ta đứng đó, tay cầm cây tẩu thuốc bằng ngọc thạch xám, ánh mắt quét qua Nam lạnh lẽo như nhìn một món đồ chơi đã hỏng hoàn toàn, không còn một chút giá trị lợi dụng nào nữa. Ông ta nhớ lại sáu năm trước khi Nam chỉ là một gã học việc nghèo nàn, làm việc quên ăn quên ngủ để tạo dựng nên hàng trăm tác phẩm triệu đô cho xưởng. Nhưng giờ đây, khi Nam đã mất đi đôi bàn tay nhạy cảm, ông ta vứt bỏ anh không một chút thương tiếc.</p>
<p>Bên cạnh ông ta, Lâm Mỹ Hạnh - vị hôn thê từng thề non hẹn biển, hứa hẹn sẽ cùng anh kế thừa xưởng sơn mài truyền thống - đang đứng nép mình đầy vẻ lả lướt vào lòng Vương Quốc Bình, thiếu gia của Tập đoàn Hóa chất Hoàng Gia. Cô ta khoác trên mình chiếc đầm hiệu Gucci đắt đỏ, cổ đeo sợi dây chuyền kim cương lấp lánh dưới ánh đèn sảnh, ánh mắt nhìn Nam tuyệt nhiên không có lấy một chút thương cảm hay tội lỗi, chỉ toàn là sự ghê tởm, khinh miệt tột cùng đối với một kẻ đã mất đi đôi bàn tay tài hoa.</p>
<p>"Hạnh, em thực sự đồng ý với quyết định tàn nhẫn này của cha sao? Sáu năm qua, anh làm việc mười bốn tiếng mỗi ngày, giam mình trong buồng ủ ẩm ướt đầy độc tính của sơn ta để vẽ nên hàng trăm tác phẩm đưa xưởng Hùng Cát lên đỉnh cao. Ngay cả vết bỏng này cũng là vì anh cứu bức tranh bảo vật của gia đình em..." Nam khàn giọng hỏi, cổ họng anh khô khốc như có hàng ngàn hạt cát găm vào, lồng ngực thắt chặt lại đau đớn. Anh không thể tin nổi người con gái mình từng chăm sóc tỉ mỉ từng li từng tí lại có thể thay lòng đổi dạ nhanh chóng đến như vậy.</p>
<p>"Trần Hoài Nam, anh bớt lôi chuyện quá khứ ra để kể công đi!" Lâm Mỹ Hạnh khoanh tay, giọng điệu sắc mỏng và sắc lẹm như một lưỡi dao cạo. "Bác sĩ của bệnh viện đã kết luận bằng văn bản rõ ràng rồi, dây thần kinh cảm giác và các đầu mút xúc giác ở mười đầu ngón tay của anh đã bị phá hủy hoàn toàn bởi hóa chất dung môi đậm đặc trong đám cháy. Một nghệ nhân sơn mài không thể dùng tay cảm nhận độ mài phẳng của màng sơn thì khác nào một kẻ phế vật vô dụng? Anh định để Lâm gia chúng tôi phải nuôi một kẻ ăn bám tàn phế cả đời sao? Hơn nữa, anh Bình đây đã đồng ý đầu tư năm mươi tỷ đồng vào xưởng sơn mài để chuyển đổi toàn diện sang công nghệ sơn nhanh bằng hóa chất công nghiệp, chúng tôi không cần cái lối làm thủ công chậm chạp, lạc hậu của anh nữa. Anh đã hết giá trị rồi!"</p>
<p>"Sơn hóa chất công nghiệp polyurethane sẽ phá hủy hoàn toàn cốt vóc gỗ và làm mất đi linh hồn trong vắt của sơn mài truyền thống!" Nam phẫn nộ quát lên, đôi bàn tay quấn gạc run rẩy kịch liệt. "Các người đang lừa dối những nhà sưu tập nghệ thuật, chà đạp lên di sản văn hóa!"</p>
<p>"Câm miệng!" Lâm Thế Hùng đập mạnh cây tẩu ngọc xuống mặt bàn gỗ trắc vang lên một tiếng cộc khô khốc, sắc mặt ông ta xám ngoét vì giận dữ. "Mày chỉ là một thằng mồ côi được tao nhặt từ cô nhi viện về nuôi dưỡng và dạy nghề, có tư cách gì mà lên mặt dạy đời tao? Bản phác thảo bức 'Bản sắc ngàn năm' mày vẽ chung với tao, tao đã dùng danh nghĩa cá nhân đăng ký bảo hộ độc quyền tác giả rồi. Mày không ký biên bản bàn giao toàn bộ bản quyền thiết kế và công thức pha màu thì hôm nay đừng hòng bước chân ra khỏi cái cổng này một cách nguyên vẹn!"</p>
<p>Vương Quốc Bình gạt gạt tàn thuốc lá, khẩy môi cười nhạt đầy vẻ đắc ý của kẻ chiến thắng. Gã gạt tay ra hiệu cho hai gã bảo vệ to khỏe bước lên. Chúng giật phăng chiếc túi vải hành lý đơn sơ của Nam, ném mạnh ra ngoài sân gạch giữa cơn mưa giông sấm sét bất chợt của phố biển Bình Dương. Tiếng sấm nổ vang trời như xé toạc bầu không khí ngột ngạt của sảnh trưng bày sang trọng.</p>
<p>"Ký vào đơn đơn phương ly hôn và thỏa thuận từ bỏ mọi quyền lợi, cổ phần liên quan đến thương hiệu Hùng Cát, hoặc là tao sẽ báo công an rằng mày lợi dụng chức vụ để ăn cắp mẫu phác thảo nghệ thuật của xưởng," Lâm Thế Hùng gằn giọng, ném xấp tài liệu cùng cây bút mực đen vào mặt Nam.</p>
<p>Nam nhìn cây bút rơi dưới chân mình, rồi nhìn thẳng vào ba khuôn mặt tràn đầy sự tham lam, xảo quyệt và tàn nhẫn trước mắt. Anh không khóc, nước mắt đã cạn khô từ giây phút nhìn thấy vị hôn thê của mình đứng nép vào lòng kẻ khác. Anh lặng lẽ cúi người xuống, dùng đôi bàn tay quấn băng đau đớn kẹp lấy cây bút mực, ký từng nét tên mình dưới bản cam kết đơn phương ly hôn và từ bỏ toàn bộ cổ phần tích lũy sáu năm qua.</p>
<p>"Các người sẽ phải trả giá cực kỳ đắt vì sự phản bội và lừa dối này," Nam nói khẽ, giọng nói phẳng lặng đến đáng sợ giữa tiếng mưa rơi tầm tã ngoài kia.</p>
<p>"Trả giá? Một gã phế vật tay run thì làm được trò trống gì ngoài việc đi ăn xin trên hè phố?" Vương Quốc Bình cười lớn đầy đắc thắng. Nam quay lưng, sải bước thẳng ra ngoài màn mưa đen tối, mặc cho nước mưa lạnh buốt hòa lẫn với những vệt dịch rỉ ra từ mười đầu ngón tay đau đớn tột cùng. Anh thề, anh sẽ đòi lại tất cả danh dự của mình.</p>"""

    # CHAPTER 2: Độc dược hóa chất và phương thuốc giữ tay
    ch2 = """<p>Cơn mưa đêm Bình Dương đổ xuống ngày một xối xả, giống như một thác nước khổng lồ muốn dội sạch mọi vết nhơ bẩn của thế gian. Trần Hoài Nam bước đi vô định trên vỉa hè vắng lặng, hơi lạnh luồn qua manh áo mỏng sũng nước. Đột nhiên, mười đầu ngón tay bị bỏng hóa chất bắt đầu lên cơn sốt co giật kịch liệt, cơn đau buốt thấu xương tủy truyền thẳng lên não bộ khiến anh xây xẩm mặt mày. Bước chân loạng choạng, Nam ngã quỵ xuống bên cạnh một bốt điện lạnh lẽo ở góc phố tối tăm, hơi thở đứt quãng.</p>
<p>Giữa màn mưa trắng xóa, một chiếc xe Mercedes-Maybach màu đen sang trọng từ từ giảm tốc độ rồi đỗ lại sát mép đường. Cửa xe mở ra, một chiếc ô đen lớn được che lên, cản bớt ánh sáng vàng vọt của ngọn đèn đường. Người bước xuống xe là một cô gái mặc bộ blazer beige cắt may vô cùng tinh xảo, mái tóc đen dài cột cao gọn gàng, toát lên phong thái kiêu sa, thông minh và vô cùng lý tính. Đó chính là Trịnh Hoàng Yến, nữ CFO lừng danh của Quỹ Đầu tư Nghệ thuật Vạn An.</p>
<p>"Anh là Trần Hoài Nam, nghệ nhân chính vẽ nên bức 'Bản sắc ngàn năm' đúng không?" Giọng nói của Yến thanh mảnh nhưng vô cùng rõ ràng, đanh thép, không hề chứa đựng bất kỳ sự thương hại sáo rỗng hay hạ cố nào.</p>
<p>Nam khó nhọc ngước khuôn mặt nhợt nhạt, ướt đẫm nước mưa nhìn cô, khẽ gật đầu một cái. Yến không hề ngần ngại bùn đất, cúi xuống đỡ lấy cánh tay đang run rẩy kịch liệt của anh. "Lên xe đi. Tôi không cứu người vì mục đích từ thiện cứu tế. Tôi cứu anh vì tôi biết bức tranh sơn mài của anh đáng giá triệu đô, và tôi có đầy đủ tài liệu chứng minh anh bị oan trong vụ hỏa hoạn vừa rồi."</p>
<p>Ngay trong đêm hôm đó, Yến không hề đưa anh đến các bệnh viện Tây y thông thường. Cô là một chuyên gia nghiên cứu sâu sắc về sơn mài truyền thống, cô thừa hiểu rằng hóa chất dung môi công nghiệp tẩy sơn cực mạnh đã ngấm sâu vào lớp trung bì và hủy hoại tế bào da. Nếu chỉ điều trị bằng thuốc bôi corticoid hay kháng sinh Tây y thông thường, làn da tay của anh sẽ bị xơ hóa, teo lại và mất đi hoàn toàn xúc giác vĩnh viễn. Cô lái xe xuyên đêm đưa anh lên vùng núi Thanh Sơn, Phú Thọ, tìm gặp cụ Bùi Văn Mán - một thầy y học cổ truyền người Mường nổi tiếng với các bài thuốc trị bỏng hóa chất và giải độc nhựa cây bí truyền.</p>
<p>"Nhựa của cây sơn ta tự nhiên tuy có độc nhưng chỉ độc một, còn thứ hóa chất dung môi công nghiệp tẩy rửa bẩn thỉu kia độc hại gấp mười lần. Bàn tay nghệ nhân muốn giữ được xúc giác tinh vi thì phải kiên trì ngâm thuốc thảo dược tiêu độc," cụ Mán trầm ngâm nói sau khi kiểm tra đôi bàn tay sưng tấy rộp da của Nam dưới ánh đèn dầu.</p>
<p>Suốt hai tuần liên tục sau đó, Nam phải trải qua những cơn đau nhức nhối thấu trời xanh khi ngâm đôi bàn tay vào nồi nước thuốc ấm sực, tỏa ra mùi thơm hăng nồng của lá trầu không rừng, vỏ cây sữa cổ thụ và nhựa trám đen được phối chế theo tỷ lệ vàng bí truyền. Lá trầu không chứa hoạt chất kháng sinh tự nhiên cực mạnh giúp tiêu diệt toàn bộ vi khuẩn hoại tử, vỏ cây sữa kích thích tái tạo nhanh lớp biểu bì biểu mô, còn nhựa trám đen rừng trung hòa hoàn toàn độc tố hóa chất công nghiệp ngấm sâu trong da. Anh kiên nhẫn chịu đựng, mỗi ngày trôi qua là một cuộc đấu tranh sinh tử để giành lại cảm giác ở mười đầu ngón tay.</p>
<p>Đến tuần thứ ba, điều kỳ diệu đã xảy ra. Những lớp da sần sùi, đen sạm do bị bỏng hóa chất bắt đầu bong tróc hoàn toàn thành từng mảng lớn, để lộ ra lớp da non hồng hào mịn màng. Nam thử cử động từng ngón tay, anh kinh ngạc nhận ra mười đầu ngón tay của mình không những không còn run rẩy mà xúc giác còn trở nên nhạy bén hơn gấp bội phần so với trước đây. Anh có thể cảm nhận rõ ràng từng thớ sợi tơ nhỏ nhất trên tấm vải lụa mềm mại trải giường.</p>
<p>Để đảm bảo tính pháp lý khoa học tuyệt đối trước khi tiến hành các bước tiếp theo, Trịnh Hoàng Yến trực tiếp đưa Nam đến Viện Da liễu Trung ương tại Hà Nội để thực hiện các xét nghiệm điện sinh lý thần kinh và kiểm tra biểu bì chuyên sâu. Kết quả đo điện cơ đồ (EMG) cùng kết quả kiểm tra cấu trúc da tay của anh khiến vị Giáo sư, Trưởng khoa da liễu phải kinh ngạc thốt lên.</p>
<p>"Thật là một kết quả lâm sàng kỳ diệu! Toàn bộ các sợi thần kinh cảm giác ngoại biên ở mười đầu ngón tay của bệnh nhân đã được tái tạo hoàn chỉnh 100%. Lớp biểu bì mới có mật độ tế bào thụ cảm xúc giác cực kỳ cao, hoàn toàn khỏe mạnh và thậm chí nhạy cảm hơn cả người bình thường," vị Giáo sư dõng dạc khẳng định khi ký tên đóng dấu đỏ lên tờ kết quả xét nghiệm.</p>
<p>Yến đón nhận tờ kết quả xét nghiệm lâm sàng từ tay bác sĩ, cô khẽ mỉm cười quay sang nhìn Nam bằng ánh mắt tràn đầy sự tin tưởng. "Đông y giữ mạng và phục hồi xúc giác thiên tài, Tây y kiểm nghiệm chứng minh kết quả lâm sàng rõ ràng. Bây giờ, đôi tay thiên tài của anh đã hoàn toàn phục hồi. Đã đến lúc chúng ta bắt đầu bàn cờ lật kèo giáng đòn chí mạng vào bọn phản bội." Nam siết chặt đôi bàn tay mới, cảm nhận dòng máu nóng hổi đang cuộn chảy mãnh liệt.</p>"""

    # CHAPTER 3: Bản phác thảo lưu dấu máu và sáng chế độc quyền
    ch3 = """<p>Rừng cây sơn ta cổ thụ ở vùng đồi Tam Nông, Phú Thọ trải dài bạt ngàn một màu xanh thẫm dưới ánh nắng ban mai rực rỡ của vùng đất Tổ. Trần Hoài Nam đứng yên lặng dưới một tán cây sơn ta lớn, tay cầm chiếc dao chuyên dụng khẽ rạch một đường hình chữ V cực kỳ chuẩn xác lên vỏ cây xám nhạt. Dòng nhựa sơn trắng sữa từ từ rỉ ra, đặc quánh, tỏa ra mùi thơm hăng hắc đặc trưng của núi rừng trung du. Đây mới chính là nhựa sơn ta tự nhiên - linh hồn vĩnh cửu của nghệ thuật sơn mài thuần Việt, thứ chất liệu quý giá mà không một loại hóa chất công nghiệp polyurethane rẻ tiền nào có thể mô phỏng được.</p>
<p>"Sơn ta chính hiệu khi khô trong buồng ủ ẩm sẽ tạo ra một màng sơn dai bền hàng ngàn năm, chịu được mọi thời tiết khắc nghiệt, có độ sâu thẳm trong vắt như ngọc và tuyệt đối an toàn cho sức khỏe nghệ nhân," Nam khẽ thuyết minh, ánh mắt lấp lánh niềm tự hào khôn tả khi nhìn dòng nhựa sơn quý giá chảy đầy vào ống tre.</p>
<p>Nam giải thích sâu hơn cho Trịnh Hoàng Yến về đặc tính sinh học của sơn ta Phú Thọ. Chất urushiol trong nhựa sơn tự nhiên khi tiếp xúc với độ ẩm không khí lý tưởng từ 80% đến 90% trong buồng ủ tối sẽ tự động polyme hóa, tạo nên lớp bảo vệ tự nhiên siêu bền. Nếu thiếu đi sự am hiểu về kỹ thuật ủ ẩm thủ công truyền thống này, sơn ta sẽ không bao giờ khô, hoặc nếu khô bằng nhiệt nhân tạo sẽ lập tức bị giòn và nứt vỡ. Đây chính là bí mật ngàn năm của các tổ nghề sơn mài Việt Nam mà các loại sơn công nghiệp hóa chất polyurethane của Tập đoàn Hoàng Gia hoàn toàn không thể có được.</p>
<p>Sau khi thu hoạch đợt nhựa sơn đầu tiên để làm nguyên liệu nghiên cứu, Nam trở về căn nhà sàn nhỏ nơi anh tạm trú cùng Trịnh Hoàng Yến. Anh từ từ mở chiếc rương gỗ cũ kỹ đóng đai đồng xỉn màu, cẩn thận lấy ra cuốn sổ tay phác thảo nghệ thuật bìa da sần sùi mang theo từ xưởng cũ. Đây chính là bản phác thảo nguyên gốc của bức tranh "Bản sắc ngàn năm" do tự tay anh vẽ ròng rã suốt hai năm trời dưới ánh đèn dầu. Trên từng trang giấy vẽ phác thảo bằng bút chì và mực tàu tinh xảo, ngoài các nét vẽ tài hoa miêu tả thần thái dân tộc đầy cuốn hút, cuốn sổ vẫn còn lưu giữ rõ ràng những vết máu khô của anh từ đêm xảy ra vụ cháy xưởng sơn mài Hùng Cát và cả những vết vân tay dính nhựa sơn ta khô cứng đen bóng như đá obsidian.</p>
<p>"Cuốn sổ tay phác thảo này chính là bằng chứng vật lý độc bản đanh thép nhất chứng minh quyền tác giả tối cao của anh đối với tác phẩm," Trịnh Hoàng Yến đứng bên cạnh anh, lật giở từng trang sổ một cách nâng niu, trân trọng như đang chạm vào lịch sử sống.</p>
<p>Không để lãng phí một giây phút nào, dưới sự tư vấn pháp lý nghiêm ngặt của văn phòng luật sư hàng đầu do Yến chỉ định, Nam chính thức nộp hồ sơ đăng ký Bằng sáng chế độc quyền tại Cục Sở hữu trí tuệ Việt Nam. Sáng chế mang tên: "Quy trình tinh chế nhựa sơn ta tự nhiên kết hợp thảo mộc kháng khuẩn, kháng mối mọt và chống nứt nẻ cho sản phẩm sơn mài mỹ nghệ". Đơn đăng ký được thực hiện theo đúng các điều khoản quy định nghiêm ngặt của Luật Sở hữu trí tuệ Việt Nam năm 2005. Quy trình này sử dụng công thức độc quyền do Nam nghiên cứu, giải quyết triệt để điểm yếu lớn nhất của sơn ta truyền thống là dễ bị nứt nẻ và mối mọt khi xuất khẩu sang các nước có khí hậu hanh khô.</p>
<p>Chỉ ba ngày sau khi hồ sơ được thụ lý chính thức trên hệ thống quốc gia, thông tin mật này lập tức lọt đến tai Lâm Thế Hùng và Vương Quốc Bình. Tại văn phòng làm việc xa hoa của xưởng Hùng Cát, Lâm Thế Hùng đập mạnh tay xuống bàn làm việc, sắc mặt xám ngoét không còn một giọt máu khi đọc được bản tin cảnh báo sở hữu trí tuệ gửi về email.</p>
<p>"Cái gì? Thằng phế vật Trần Hoài Nam đó chưa chết sao? Đôi tay nó bị bỏng nặng như thế làm sao có thể phục hồi mà nộp đơn sáng chế độc quyền quy trình tinh chế sơn ta?" Hùng gầm lên điên cuồng, trán lấm tấm mồ hôi lạnh chảy dài xuống má.</p>
<p>"Cha yên tâm đi, con đã dùng thế lực và mối quan hệ tài chính của Tập đoàn Hóa chất Hoàng Gia để nộp đơn đăng ký nhãn hiệu thương mại 'Hùng Cát Lacquer' cho công thức sơn hóa chất của chúng ta rồi. Con cũng đã đút lót một khoản tiền lớn cho một chuyên viên trong Cục Sở hữu trí tuệ để trì hoãn hồ sơ của nó," Vương Quốc Bình nhấp ngụm rượu vang, cười xảo quyệt đầy tự mãn.</p>
<p>Nhưng bọn chúng không hề hay biết rằng, hệ thống nộp đơn trực tuyến của Cục Sở hữu trí tuệ áp dụng công nghệ khóa thời gian (timestamp) bảo mật cực kỳ nghiêm ngặt của nhà nước. Hồ sơ sáng chế độc quyền của Trần Hoài Nam đã được ghi nhận trên hệ thống quốc gia vào lúc 9 giờ 15 phút ngày 20 tháng 11, trong khi đơn nhãn hiệu của Hùng Cát mãi đến ngày 5 tháng 12 mới được nộp. Bẫy pháp lý đã được giăng ra hoàn hảo, và kẻ cướp công trình đang tự bước chân vào thòng lọng tự thiêu mà không hề hay biết.</p>"""

    # CHAPTER 4: Quỹ đầu tư lý tính và cái bẫy giăng ra
    ch4 = """<p>Trịnh Hoàng Yến tuyệt đối không phải là một nhà đầu tư nghệ thuật mơ mộng hay bị chi phối bởi cảm xúc nhất thời. Cô là một CFO lý tính đến cực đoan, sở hữu tấm bằng Thạc sĩ Tài chính tại Đại học Quốc gia Singapore và mười năm kinh nghiệm điều hành các quỹ đầu tư mạo hiểm sừng sỏ. Trước khi quyết định đặt bút ký hợp đồng chuyển vốn trị giá trăm tỷ đồng cho dự án khôi phục sơn mài truyền thống của Trần Hoài Nam, cô đã yêu cầu bộ phận thẩm định pháp lý và phòng thí nghiệm hóa sinh của Quỹ Vạn An thực hiện các bước kiểm tra kiểm định cực kỳ nghiêm ngặt.</p>
<p>Phòng thí nghiệm của Vạn An tiến hành đo độ bền kéo của màng sơn khô dưới máy thử tải hiện đại, phân tích cấu trúc phân tử bằng phương pháp quang phổ hồng ngoại biến đổi Fourier (FTIR) để chứng minh sản phẩm của Nam sử dụng 100% nhựa sơn ta tự nhiên Phú Thọ. Ngược lại, mẫu thử lấy từ xưởng Hùng Cát bị phát hiện chứa hàm lượng formaldehyde và benzene độc hại vượt ngưỡng cho phép của Bộ Y tế gấp trăm lần do sử dụng sơn công nghiệp polyurethane rẻ tiền của Trung Quốc để đẩy nhanh tiến độ sản xuất.</p>
<p>Yến phân bổ chi tiết khoản đầu tư một trăm năm mươi tỷ đồng vô cùng khoa học: 50 tỷ đồng xây dựng nhà máy tinh chế sơn ta hiện đại đạt chuẩn xuất khẩu tại Tam Nông, Phú Thọ; 40 tỷ đồng xây dựng chuỗi phòng trưng bày nghệ thuật cao cấp tại Hà Nội và TP. Hồ Chí Minh; 30 tỷ đồng ký kết hợp đồng bao tiêu dài hạn, bảo hiểm giá cho các hộ dân trồng sơn ta truyền thống; và 30 tỷ đồng dành cho các hoạt động truyền thông nghệ thuật quốc tế và đăng ký bảo hộ sở hữu trí tuệ toàn cầu.</p>
<p>Trước khi ký kết, cô đã chất vấn Nam bằng 15 câu hỏi tài chính cực kỳ sắc bén liên quan đến rủi ro tỷ giá, quản trị chuỗi cung ứng nguyên vật liệu thô và khả năng mở rộng công suất sản xuất mà không làm suy giảm chất lượng nghệ thuật. Nam đã trả lời từng câu một bằng sự thấu hiểu sâu sắc từ thực tiễn xưởng sản xuất và tư duy chiến lược đột phá, hoàn toàn chinh phục được vị CFO lý tính cực đoan này.</p>
<p>"Mọi thông số kỹ thuật đều hoàn hảo tuyệt đối. Năng lực pháp lý của bằng sáng chế hoàn toàn sạch sẽ, không có bất kỳ tranh chấp nào. Tôi chính thức phê duyệt khoản đầu tư một trăm năm mươi tỷ đồng vào Công ty Sơn Mài Trần Gia của anh," Yến dứt khoát tuyên bố trong buổi họp hội đồng quản trị của Quỹ Vạn An, đặt bút ký vào bản hợp đồng chuyển vốn sòng phẳng trước sự chứng kiến của toàn thể cổ đông.</p>
<p>Tối hôm đó, để chúc mừng hợp đồng được ký kết thành công tốt đẹp, Yến mời Nam đến dùng trà sen tại khuôn viên vườn của một căn biệt thự cổ thời Pháp thuộc trên đường Phan Đình Phùng, Hà Nội. Không gian vườn biệt thự cổ kính tĩnh mịch lạ thường, chỉ có tiếng gió mùa thu khẽ lay động những tán lá sấu già xào xạc và ánh trăng bạc dịu mát đổ xuống thảm cỏ xanh mịn. Mùi hoa ngọc lan thơm ngát thoang thoảng trong bầu không khí mát mẻ dễ chịu. Căn biệt thự này vốn là một di sản kiến trúc tuyệt đẹp với những bức tường sơn vàng nhạt cổ kính, ô cửa sổ gỗ màu xanh thẫm và những chiếc lò sưởi cũ bằng gạch nung đỏ rực rỡ.</p>
<p>Yến mặc một chiếc đầm lụa tơ tằm màu trắng ngà vô cùng thanh lịch, rũ bỏ hoàn toàn vẻ lạnh lùng, cứng nhắc của một CFO tài chính thường ngày. Cô khẽ nâng ly trà sen ấm áp, hướng đôi mắt trong veo nhìn ra khoảng không gian ngập tràn ánh trăng phía xa.</p>
<p>"Nam này, anh có biết tại sao tôi lại quyết định đầu tư vào anh nhanh chóng và quyết liệt như vậy không?" Yến khẽ hỏi, giọng nói trầm ấm và vô cùng dịu dàng.</p>
<p>Nam nhìn nghiêng khuôn mặt thanh tú của cô dưới ánh trăng, khẽ lắc đầu. "Tôi nghĩ là vì các con số báo cáo tài chính và tiềm năng tăng trưởng của thị trường tranh sơn mài cao cấp."</p>
<p>Yến khẽ cười, một nụ cười hiếm hoi nhưng vô cùng rạng rỡ làm bừng sáng cả khuôn viên vườn cổ kính. "Đó chỉ là điều kiện cần của một CFO. Điều kiện đủ là vì tôi nhìn thấy ở anh một thứ đức tin nghệ thuật thuần khiết nhất - thứ mà tôi đã đánh mất suốt mười năm lăn lộn trong giới tài chính lạnh lùng đầy rẫy sự lừa lọc ở Singapore. Cha tôi trước đây cũng là một nghệ nhân gốm sứ truyền thống bị đối tác phản bội, cướp công thức men rạn rồi chèn ép đến mức uất hận mà qua đời. Khi nhìn thấy đôi bàn tay rỉ máu của anh quyết giữ lấy bức tranh trong đám cháy, tôi như nhìn thấy lại hình bóng người cha quá cố của mình."</p>
<p>Nam lặng người đi vì xúc động sâu sắc. Anh kể cho cô nghe về tuổi thơ của mình, về người ông nội đã dạy anh cách cầm cọ mài nước dưới giếng ban đêm. Anh từ từ đặt bàn tay ấm áp, mạnh mẽ và tràn đầy sinh lực của mình lên mu bàn tay thon nhỏ của Yến. "Cảm ơn em đã tin tưởng anh. Anh hứa sẽ dùng cả cuộc đời và đôi bàn tay này để chứng minh niềm tin của em đặt vào anh là hoàn toàn đúng đắn."</p>
<p>Dưới ánh trăng khuyết treo lơ lửng giữa trời đêm Hà Nội cổ kính, hai tâm hồn từng chịu nhiều tổn thương sâu sắc đã thực sự xích lại gần nhau hơn bao giờ hết, chuẩn bị tinh thần thép để đối mặt với cơn bão tố tàn khốc sắp sửa ập đến.</p>"""

    # CHAPTER 5: Bão nổi 24 giờ thanh tra và tài khoản đóng băng
    ch5 = """<p>Đúng như những gì Trần Hoài Nam và Trịnh Hoàng Yến đã dự báo từ trước, phe phản diện Lâm Thế Hùng và Vương Quốc Bình quyết không chịu ngồi yên nhìn Sơn Mài Trần Gia vươn lên mạnh mẽ. Chỉ một tuần trước khi Trần Gia chuẩn bị tổ chức buổi họp báo công bố bộ sưu tập tranh sơn mài độc bản đầu tiên, một loạt đòn tấn công hai gọng kìm cực kỳ tàn độc đã được phe đối thủ kích hoạt đồng loạt nhằm triệt hạ Nam tận gốc rễ.</p>
<p>Vào đúng 8 giờ sáng ngày thứ Hai, một đoàn thanh tra liên ngành đột xuất gồm cảnh sát môi trường và đại diện sở y tế do ông Nguyễn Văn Hòa dẫn đầu bất ngờ ập vào xưởng sản xuất cốt gỗ của Sơn Mài Trần Gia tại ngoại ô Hà Nội. Ông Hòa bước vào với khuôn mặt hách dịch, cầm trên tay một lá đơn tố cáo nặc danh vô căn cứ được phe đối thủ gài bẫy, tuyên bố xưởng vi phạm nghiêm trọng luật bảo vệ môi trường.</p>
<p>"Chúng tôi yêu cầu tạm dừng toàn bộ hoạt động sản xuất của cơ sở này trong vòng 24 giờ để tiến hành đo đạc nồng độ dung môi hữu cơ bay hơi và kiểm tra hệ thống xả thải," ông Hòa lạnh lùng tuyên bố, không cho các công nhân có cơ hội giải thích.</p>
<p>Nam nhìn thẳng vào mắt vị trưởng đoàn thanh tra, anh thấu hiểu sâu sắc rằng đằng sau vụ việc này là sự giật dây của các thế lực hắc ám. Anh ra hiệu cho các nhân viên giữ thái độ ôn hòa hợp tác, tuyệt đối không được có bất kỳ hành vi kích động nào làm phức tạp thêm tình hình pháp lý. Lúc này, Trịnh Hoàng Yến bước lên phía trước, cô giở sẵn bản sao của Luật Bảo vệ môi trường năm 2020 và dõng dạc chỉ ra các điều khoản quy định về thời gian thông báo trước đối với các cuộc thanh tra định kỳ hoặc đột xuất không thuộc trường hợp khẩn cấp thiên tai tai nạn.</p>
<p>"Thưa ông Hòa, theo đúng Điều 105 của Luật Bảo vệ môi trường, cuộc thanh tra đột xuất này phải có quyết định bằng văn bản được ký bởi thủ trưởng cơ quan quản lý nhà nước có thẩm quyền cấp tỉnh trở lên. Quyết định thanh tra của các ông đâu? Nếu không cung cấp được văn bản hợp lệ, việc ép buộc dừng sản xuất của xưởng chúng tôi là hành vi lạm quyền, gây thiệt hại nghiêm trọng cho doanh nghiệp và chúng tôi sẽ lập biên bản có sự chứng kiến của luật sư để khởi kiện hành chính ngay lập tức," Yến sắc sảo lên tiếng, từng lời nói của cô đanh thép khiến ông Hòa giật mình, sắc mặt biến chuyển liên tục.</p>
<p>Khi các công nhân trong xưởng bắt đầu hoang mang lo lắng, xì xào bàn tán sợ hãi trước sự hiện diện của đoàn thanh tra đầy quyền uy, Nam đã lập tức tiến lại gần họ. Anh nhẹ nhàng đặt tay lên vai người quản đốc, mỉm cười điềm tĩnh rồi tập hợp tất cả mọi người lại thành một vòng tròn nhỏ. Giọng nói của anh vang lên vô cùng ấm áp, kiên định và chứa đựng một nội lực bình yên đến lạ kỳ: "Mọi người cứ yên tâm tiếp tục làm việc bình thường. Xưởng chúng ta sử dụng hoàn toàn nguyên liệu sơn tự nhiên hữu cơ kháng khuẩn, không xả ra dù chỉ một giọt hóa chất độc hại. Đoàn thanh tra chỉ đang làm việc theo đúng quy trình nghiệp vụ của họ để kiểm chứng sự trong sạch của chúng ta thôi. Không có gì phải lo sợ cả, chân lý luôn thuộc về chúng ta." Lời nói của người đứng đầu như một liều thuốc an thần cực mạnh, dập tắt hoàn toàn mọi sự lo âu, củng cố lòng tin tuyệt đối của toàn thể nhân công vào tiền đồ rực rỡ của Trần Gia.</p>
<p>Chưa dừng lại ở đó, cùng lúc đó, Nam nhận được thông báo khẩn từ hệ thống Techcombank: Toàn bộ tài khoản giao dịch doanh nghiệp của Sơn Mài Trần Gia bị tạm thời phong tỏa để xác minh nguồn tiền đầu tư dưới danh nghĩa phòng chống rửa tiền, theo yêu cầu phối hợp từ một cán bộ thanh tra ngân hàng biến chất vốn là vây cánh lâu năm của Tập đoàn Hóa chất Hoàng Gia. Vị Giám đốc chi nhánh Techcombank gọi điện giải thích rằng đây là quy trình tự động bắt buộc khi nhận được yêu cầu từ Cục Phòng chống rửa tiền của Ngân hàng Nhà nước, tuy nhiên họ sẽ cố gắng xử lý nhanh chóng trong vòng 48 giờ nếu Trần Gia cung cấp đầy đủ các chứng từ chứng minh nguồn gốc hợp pháp của dòng vốn.</p>
<p>Đến 10 giờ sáng, đối tác xuất khẩu lớn từ Singapore gửi email tuyên bố tạm hoãn hợp đồng bao tiêu sản phẩm trị giá hai triệu đô la vì lo ngại những rủi ro pháp lý và môi trường của Trần Gia. Các điều khoản hợp đồng bằng tiếng Anh pháp lý ghi rõ họ có quyền chấm dứt thỏa thuận nếu Trần Gia bị đình chỉ hoạt động do vi phạm pháp luật môi trường sở tại. Nam lập tức soạn thảo một bức thư phản hồi bằng tiếng Anh cực kỳ chuyên nghiệp và chuẩn xác gửi cho hội đồng quản trị đối tác Singapore, cung cấp đầy đủ bằng chứng pháp lý chứng minh xưởng không hề bị đình chỉ hợp pháp và cam kết bồi thường gấp đôi nếu có bất kỳ chậm trễ nào về tiến độ giao hàng, thể hiện bản lĩnh của một doanh nhân lớn.</p>
<p>Đòn chí mạng xuất hiện vào tối hôm đó. KOL Hoàng Đăng - một nhà phê bình mỹ thuật nổi tiếng có hàng triệu người theo dõi trên mạng xã hội - bất ngờ thực hiện một buổi livestream trực tiếp kéo dài hai tiếng. Buổi livestream nhanh chóng thu hút hơn 100.000 người xem đồng thời.</p>
<p>"Tôi xin khẳng định, toàn bộ bộ sưu tập tranh sắp ra mắt của Trần Hoài Nam thực chất chỉ là sản phẩm nhái lại, ăn cắp thiết kế độc quyền từ xưởng sơn mài Hùng Cát danh tiếng. Nam chỉ là một kẻ phản bội sếp cũ, một kẻ trộm cắp văn hóa không hơn không kém!" Hoàng Đăng dõng dạc tuyên bố trên sóng livestream, trưng ra những bức ảnh chụp lén các bản phác thảo chưa hoàn thiện của Nam tại xưởng Hùng Cát trước đây.</p>
<p>Cộng đồng mạng lập tức bùng nổ phẫn nộ. Các bình luận tiêu cực như "Tẩy chay Trần Gia", "Kẻ cướp công nghệ", "Nghệ sĩ rác rưởi" liên tục chạy dài trên màn hình. Cổ phiếu của Quỹ Vạn An đứng trước nguy cơ sụt giảm nghiêm trọng. Sơn Mài Trần Gia rơi vào một thế bế tắc thực sự, ngỡ như không thể nào gượng dậy nổi trước sức ép khủng khiếp từ truyền thông bẩn và thế lực ngầm hắc ám.</p>"""

    # CHAPTER 6: Bản sao kê đóng dấu đỏ và báo cáo kiểm toán Big 4
    ch6 = """<p>Trong văn phòng làm việc lộng lẫy và yên tĩnh của Sơn Mài Trần Gia, bầu không khí căng thẳng bao trùm. Trái ngược hoàn toàn với sự hoang mang, lo lắng của các nhân viên cấp dưới, Trần Hoài Nam và Trịnh Hoàng Yến vẫn ngồi uống trà sen vô cùng điềm tĩnh, ung dung tự tại. Họ không hề vội vàng đăng đàn đưa ra những lời thanh minh yếu ớt vô giá trị trên mạng xã hội. Họ kiên nhẫn chờ đợi đối thủ đắc ý tự mãn đến tột cùng trước khi tung ra đòn phản công chí mạng nhất.</p>
<p>"Bọn chúng đã hoàn toàn cắn câu không sót một đứa. Mọi quân cờ trên bàn cờ thâu tóm ngược đã đi đúng vị trí," Yến khẽ đặt ly trà xuống mặt bàn kính, đôi mắt cô toát lên vẻ lạnh lùng, sắc bén của một chuyên gia tài chính sừng sỏ.</p>
<p>Lúc này, Hùng - người bạn thân làm kiểm toán viên cao cấp tại hãng kiểm toán danh tiếng Ernst & Young (EY) của Nam - bước vào phòng họp với phong thái tự tin, ném mạnh lên bàn một tập hồ sơ dày cộp đóng logo màu vàng đen của EY. "Nam này, báo cáo kiểm toán chuỗi cung ứng độc lập của EY đối với xưởng Hùng Cát trong ba năm qua đã hoàn thành xuất sắc. Kết quả phân tích hóa đơn mua hàng và tờ khai hải quan chứng minh rõ ràng: Hùng Cát không hề mua một giọt nhựa sơn ta tự nhiên nào từ Phú Thọ hay bất kỳ vùng nguyên liệu nào của Việt Nam. Toàn bộ nguyên liệu họ sử dụng là sơn hóa chất công nghiệp polyurethane giá rẻ độc hại nhập khẩu tiểu ngạch từ Trung Quốc qua một công ty ma có trụ sở tại Thâm Quyến để trốn thuế."</p>
<p>Báo cáo của EY chỉ rõ sơn hóa chất Hùng Cát sử dụng chứa hàm lượng các chất dung môi hữu cơ bay hơi VOC cực cao, cùng các kim loại nặng như chì và cadmium, có thể gây hại nghiêm trọng cho sức khỏe người sử dụng nếu tiếp xúc trực tiếp trong thời gian dài. Đây là thông tin cực kỳ đắt giá, có thể phá hủy hoàn toàn danh tiếng nghệ thuật của xưởng Hùng Cát. Đặc biệt, Hùng phát hiện ra công ty ma tại Thâm Quyến mang tên "Shenzhen Golden Varnish Co., Ltd" thực chất do một người em họ của Vương Quốc Bình đứng tên thành lập, tạo thành một chuỗi lợi ích nhóm khép kín nhằm tham nhũng rút ruột tài sản và trốn thuế nhập khẩu của nhà nước lên tới hàng chục tỷ đồng.</p>
<p>Hùng chia sẻ thêm về những đêm mất ngủ ròng rã cùng đội ngũ kiểm toán viên phân tích hàng ngàn trang chứng từ kế toán, đối chiếu số liệu hải quan để đưa ra một báo cáo kiểm toán độc lập hoàn hảo và không thể chối cãi. Sự cống hiến thầm lặng của Hùng chính là một mảnh ghép quan trọng giúp củng cố bức tường chứng cứ pháp lý vững chắc cho Nam. Luật sư Minh Đức vô cùng tán thưởng sự chu mật của Yến khi cô đã chủ động ghi âm và quay phim lại toàn bộ quá trình thanh tra của ông Hòa để làm bằng chứng bảo vệ Trần Gia trước pháp luật.</p>
<p>Báo cáo kiểm toán của hãng Big 4 uy tín toàn cầu chính là nhát dao sắc lẹm vạch trần bộ mặt thật của kẻ tự xưng là "giữ gìn quốc hồn sơn mài Việt". Hùng Cát thực chất chỉ là một nhà máy sản xuất tranh công nghiệp độc hại quy mô lớn, lừa dối toàn bộ giới sưu tập mỹ thuật trong nước và quốc tế để trục lợi bất chính, vi phạm nghiêm trọng Luật Thuế và Luật Hải quan.</p>
<p>Chưa dừng lại ở đó, Trịnh Hoàng Yến tiếp tục đẩy qua cho Nam một tập tài liệu khác đóng dấu đỏ chói lọi của Ngân hàng Techcombank Chi nhánh Bình Dương. Đây là bản sao kê lịch sử giao dịch chi tiết tài khoản cá nhân của Lâm Thế Hùng do cơ quan thanh tra cung cấp hợp pháp theo yêu cầu điều tra độc lập của Vạn An.</p>
<p>Bản sao kê đóng dấu đỏ chỉ rõ: Vào đúng ngày 5 tháng 12, tài khoản của Lâm Thế Hùng đã thực hiện hai lệnh chuyển tiền lớn cực kỳ mờ ám. Lệnh thứ nhất trị giá 1 tỷ đồng được chuyển vào tài khoản cá nhân của vị cán bộ thanh tra môi trường liên ngành để giật dây vụ đình chỉ xưởng sản xuất của Nam. Lệnh thứ hai trị giá 500 triệu đồng được chuyển thẳng vào tài khoản của KOL Hoàng Đăng để thực hiện chiến dịch bôi nhọ danh dự của Nam trên sóng livestream. Các thông tin giao dịch ghi rõ mã tham chiếu giao dịch nội bộ ngân hàng và thời gian thực hiện chính xác đến từng giây.</p>
<p>Luật sư Minh Đức giải thích rằng các bằng chứng này cấu thành tội danh "Đưa hối lộ" theo Điều 364 của Bộ luật Hình sự Việt Nam năm 2015, có thể đối mặt với mức án tù nghiêm khắc từ 7 đến 12 năm. Đồng thời, hành vi vu khống của KOL Hoàng Đăng cũng vi phạm Điều 156 về tội "Vu khống", đủ cơ sở để khởi kiện hình sự ngay lập tức.</p>
<p>"Sao kê ngân hàng đóng dấu đỏ cùng báo cáo kiểm toán của hãng EY danh tiếng đã nằm gọn trong tay chúng ta. Mọi chứng cứ hối lộ cán bộ nhà nước, lừa đảo tài chính quy mô lớn và vu khống truyền thông bẩn đã hoàn toàn đầy đủ pháp lý," luật sư Minh Đức dõng dạc tuyên bố khi bước vào phòng họp.</p>
<p>"Rất tốt," Nam khẽ siết chặt nắm tay, mười đầu ngón tay nhạy cảm phục hồi hoàn hảo của anh khẽ lướt qua lớp sơn ta khô mịn màng trên bức tranh mới của mình. "Ngày mai là Phiên Đấu giá Mỹ thuật Quốc tế Đông Nam Á tại Hà Nội. Chúng ta sẽ kết thúc trò hề bẩn thỉu của bọn chúng ngay tại đó."</p>"""

    # CHAPTER 7: Phiên đấu giá quốc tế và cú lật kèo hoàn hảo
    ch7 = """<p>Đại sảnh của Khách sạn năm sao Grand Plaza Hà Nội tối hôm đó lung linh dưới ánh đèn pha lê vô cùng tráng lệ. Phiên Đấu giá Mỹ thuật Quốc tế Đông Nam Á quy tụ hàng trăm nhà sưu tập tranh sừng sỏ, các tỷ phú bất động sản và đại diện các quỹ đầu tư nghệ thuật lớn từ khắp nơi trên thế giới như Singapore, Pháp, Mỹ. Bầu không khí vô cùng sôi động, hào nhoáng và ngập tràn mùi tiền bạc thượng lưu.</p>
<p>Tại khu vực trung tâm của sảnh triển lãm, xưởng sơn mài Hùng Cát chiếm vị trí trưng bày trang trọng nhất. Lâm Thế Hùng mặc bộ comple gấm hoa thêu chỉ vàng sang trọng, cùng con gái Lâm Mỹ Hạnh và Vương Quốc Bình đứng đón tiếp các quan khách, tỷ phú với nụ cười đắc thắng tột cùng hiện rõ trên khuôn mặt kiêu ngạo. Phía sau họ là bức họa khổng lồ "Bản sắc ngàn năm" - tác phẩm cướp đoạt trắng trợn từ công sức của Nam - đang được định giá khởi điểm đấu giá lên tới 1,5 triệu đô la Mỹ.</p>
<p>Các tỷ phú bất động sản lớn như Mr. Jonathan Vance đến từ New York hay Madame Sophia Chen đến từ Hồng Kông đang đứng chiêm ngưỡng bức họa khổng lồ và không ngừng tán thưởng về màu sắc rực rỡ của nó. Lâm Thế Hùng càng được đà tự mãn, đắc ý giới thiệu về công nghệ sản xuất nhanh mà ông ta tự xưng là "bí quyết gia truyền độc quyền".</p>
<p>"Tác phẩm vĩ đại này sử dụng công thức tinh chế sơn mài gia truyền trăm năm của dòng họ Lâm chúng tôi, đại diện cho đỉnh cao nghệ thuật sơn mài truyền thống Việt Nam," Lâm Thế Hùng dõng dạc thuyết minh đầy kiêu ngạo trước hàng chục ống kính phóng viên truyền hình.</p>
<p>Ngay khi phiên đấu giá bức tranh chuẩn bị chính thức bắt đầu, Trần Hoài Nam cùng Trịnh Hoàng Yến bất ngờ bước vào đại sảnh. Sự xuất hiện của hai người lập tức khiến cả hội trường xôn xao bàn tán. Hàng chục phóng viên nhanh chóng vây lấy họ để phỏng vấn về vụ bê bối đạo nhái tranh đang xôn xao trên mạng xã hội suốt những ngày qua. Cả Madame Clarisse Laurent - chuyên gia giám định cao cấp của nhà đấu giá Sotheby's và tỷ phú người Singapore Mr. Tan cũng đang chăm chú theo dõi sự việc.</p>
<p>Vương Quốc Bình bước lên phía trước, chặn đường Nam với nụ cười khinh bỉ đầy vẻ khiêu khích. "Thằng phế vật Trần Hoài Nam! Mày còn dám vác mặt đến đây sao? Hôm nay là ngày xưởng Hùng Cát bước lên đỉnh cao nghệ thuật thế giới, còn loại ăn cắp phế vật như mày chỉ xứng đáng đứng nhìn từ xa thôi!"</p>
<p>Nam không hề tỏ ra tức giận hay bối rối. Anh thản nhiên bước thẳng lên sân khấu chính trước sự ngỡ ngàng của ban tổ chức đấu giá. Anh gạt tay ra hiệu cho bộ phận kỹ thuật của Quỹ Vạn An kích hoạt quyền điều khiển màn hình LED khổng lồ phía sau sân khấu.</p>
<p>"Kính thưa toàn thể quý vị quan khách và giới sưu tập nghệ thuật quốc tế," giọng nói của Nam vang vọng đanh thép khắp đại sảnh rộng lớn qua hệ thống loa công suất lớn. "Tôi đứng đây hôm nay để phơi bày một vụ lừa đảo nghệ thuật, hối lộ cán bộ và vi phạm sở hữu trí tuệ quy mô lớn nhất lịch sử mỹ thuật Việt Nam liên quan đến bức tranh đang được đấu giá kia."</p>
<p>Màn hình LED lập tức sáng rực lên, hiển thị bản quét sắc nét độ phân giải cao của cuốn sổ tay phác thảo của Nam từ năm năm trước, có dấu vân tay dính nhựa sơn ta khô và vết máu khô của anh trong đêm cháy xưởng cứu tác phẩm. Tiếp theo là quyết định cấp Bằng sáng chế độc quyền quy trình tinh chế sơn ta chính thức từ Cục Sở hữu trí tuệ quốc gia cấp cho Trần Hoài Nam.</p>
<p>"Bức tranh 'Bản sắc ngàn năm' hoàn toàn do tôi sáng tác độc quyền. Xưởng Hùng Cát đã cướp đoạt bản phác thảo thô của tôi để làm giả sản phẩm," Nam dõng dạc tuyên bố.</p>
<p>Cả hội trường bùng nổ những tiếng xì xào bàn tán kinh ngạc tột độ. Lâm Thế Hùng mặt biến sắc, vội vàng hét lên điên cuồng: "Mày ngậm máu phun người! Đó là nghiên cứu độc quyền của tao! Bảo vệ đâu, đuổi tên điên này ra ngoài ngay lập tức!"</p>
<p>Tuy nhiên, các nhân viên bảo vệ không hề di chuyển. Trịnh Hoàng Yến bước lên sân khấu, tay cầm một tập hồ sơ pháp lý và dõng dạc công bố quyết định khẩn cấp của Tòa án Nhân dân TP. Hà Nội về việc áp dụng biện pháp khẩn cấp tạm thời, đình chỉ ngay lập tức việc đấu giá bức tranh "Bản sắc ngàn năm" để phục vụ công tác điều tra tranh chấp bản quyền tác giả.</p>
<p>"Vậy ông giải thích thế nào về những tài liệu kiểm toán và tài chính này?" Trịnh Hoàng Yến bước lên sân khấu, tay cầm micro lạnh lùng hỏi. Màn hình LED lập tức chuyển sang hiển thị Báo cáo kiểm toán độc lập của hãng EY uy tín chứng minh Hùng Cát sử dụng 100% sơn hóa chất công nghiệp polyurethane độc hại của Trung Quốc thay thế sơn ta tự nhiên Phú Thọ. Đồng thời, bản sao kê tài khoản Techcombank đóng dấu đỏ phơi bày các khoản hối lộ 1,5 tỷ đồng của Lâm Thế Hùng cho vị thanh tra môi trường và KOL Hoàng Đăng cũng hiện lên rõ mồn một trước sự chứng kiến của hàng trăm nhà sưu tập và phóng viên truyền thông.</p>"""

    # CHAPTER 8: Đầu gối quỵ ngã của kẻ phản bội và sắc lệnh C03
    ch8 = """<p>Toàn bộ đại sảnh lộng lẫy của khách sạn năm sao Grand Plaza chìm vào một khoảng im lặng chết chóc trong vòng ba giây dài đằng đẵng, trước khi bùng nổ thành một cơn địa chấn truyền thông vô tiền khoáng hậu. Hàng trăm ánh đèn flash của các cơ quan báo chí, truyền hình chớp liên tục vào khuôn mặt xám ngoét, cắt không còn một giọt máu của Lâm Thế Hùng, Lâm Mỹ Hạnh và Vương Quốc Bình.</p>
<p>Lâm Thế Hùng đứng chôn chân tại chỗ, mồ hôi lạnh chảy ra ròng ròng như tắm ướt đẫm cả chiếc áo comple gấm thêu chỉ vàng hoa lệ. Đầu óc ông ta quay cuồng điên đảo, hai tai ù đi trước những tiếng xì xào khinh bỉ, sỉ nhục từ giới Collecter thượng lưu. Đôi bàn tay của ông ta run rẩy kịch liệt như người mất trí, các ngón tay bấu chặt vào mép bàn đấu giá gỗ trắc đến mức rỉ máu ra từ kẽ móng tay đau đớn tột cùng. Đôi đầu gối bủn rủn, không còn một chút lực nâng đỡ nào, hoàn toàn quỵ sụp xuống mặt sàn nhà lát đá hoa cương bóng loáng trước hàng trăm ống kính camera đang ghi hình trực tiếp.</p>
<p>"Không thể nào... Tại sao chúng mày lại có thể thu thập được những tài liệu tối mật này..." Lâm Thế Hùng thều thào trong sự tuyệt vọng và nhục nhã tột cùng.</p>
<p>Lâm Mỹ Hạnh sợ hãi tột độ, khuôn mặt trang điểm son phấn đậm đà giờ đây nhợt nhạt như một xác chết không hồn, cô ta khóc lóc thảm thiết bám lấy cánh tay của Vương Quốc Bình. "Cha ơi cứu con, con không muốn đi tù đâu, toàn bộ xe hiệu và đầm hiệu của con đều là nhờ tiền của xưởng mà..."</p>
<p>Nhưng gã thiếu gia hóa chất kiêu ngạo Vương Quốc Bình lúc này cũng đang run lẩy bẩy như cầy sấy. Gã cố gắng lấy điện thoại gọi điện cho người cha quyền lực là Vương Quốc Hoàng - Chủ tịch Tập đoàn Hóa chất Hoàng Gia để cầu cứu nhưng đầu dây bên kia chỉ là những tiếng tút dài vô vọng. Gã cố gắng tìm cách lẻn ra ngoài cửa thoát hiểm để trốn chạy khỏi hội trường đấu giá.</p>
<p>Nhưng ngay tại tất cả các lối ra vào của đại sảnh khách sạn, mười cán bộ chiến sĩ cảnh sát điều tra thuộc Cục Cảnh sát điều tra tội phạm về tham nhũng, kinh tế, buôn lậu (C03) - Bộ Công an mặc thường phục đã đứng phong tỏa nghiêm ngặt từ bao giờ. Vị điều tra viên trưởng bước lên sân khấu chính, rút từ trong cặp táp ra sắc lệnh đóng dấu đỏ chói lọi của Viện Kiểm sát Nhân dân Tối cao và dõng dạc tuyên đọc trước toàn thể hội trường.</p>
<p>"Chúng tôi công bố quyết định khởi tố vụ án hình sự, khởi tố bị can và thực hiện lệnh bắt tạm giam khẩn cấp đối với Lâm Thế Hùng, Lâm Mỹ Hạnh và Vương Quốc Bình theo Điều 174 Bộ luật Hình sự về tội Lừa đảo chiếm đoạt tài sản, Điều 226 về tội Xâm phạm quyền sở hữu công nghiệp và Điều 364 về tội Đưa hối lộ," vị điều tra viên dứt khoát tuyên bố.</p>
<p>Tiếng còng số 8 lạnh lẽo vang lên lách cách khi bập chặt vào cổ tay của ba kẻ phản bội kiêu ngạo. Chúng bị áp giải đi giữa những tiếng la ó, sỉ vả khinh bỉ của toàn thể giới nghệ thuật và các nhà sưu tập có mặt tại hội trường đấu giá. Bức tranh giả của Hùng Cát lập tức bị lực lượng chức năng niêm phong để làm tang vật phục vụ điều tra mở rộng vụ án.</p>
<p>Đế chế Hùng Cát lập tức bị thanh lý tài sản để bồi thường các khoản nợ thuế và thiệt hại cho khách hàng. Thương hiệu từng lừng danh một thời hoàn toàn biến mất khỏi bản đồ nghệ thuật Việt Nam.</p>
<p>Hai tháng sau khi đế chế tranh giả Hùng Cát hoàn toàn sụp đổ dưới chân lý và pháp luật, Sơn Mài Trần Gia của Trần Hoài Nam đã vươn lên mạnh mẽ như vũ bão, trở thành thương hiệu sơn mài truyền thống uy tín và lớn mạnh nhất Việt Nam. Tác phẩm của anh được các bảo tàng lớn tại Singapore và Pháp đặt hàng trưng bày độc quyền với giá trị hàng triệu đô la. Vết sẹo hóa chất trên tay Nam giờ đây đã biến mất hoàn toàn không để lại dấu vết, thay vào đó là đôi bàn tay mạnh mẽ, đầy cảm xúc nghệ thuật chạm khắc tinh hoa đất nước.</p>
<p>Nam vừa sáng tác tác phẩm mới mang tên "Ánh sáng ngàn năm" (The Thousand-Year Light). Sử dụng đôi tay thiên tài phục hồi 100% cảm giác xúc giác, anh có thể mài nước đạt độ nhẵn phẳng chuẩn xác đến từng micron mà không cần bất kỳ máy đo hỗ trợ nào. Bức tranh phản chiếu ánh sáng hổ phách sâu thẳm lộng lẫy vô ngần.</p>
<p>Trong một buổi tối thanh bình ấm áp tại khuôn viên biệt thự cổ của Sơn Mài Trần Gia, Nam đứng bên cạnh Trịnh Hoàng Yến dưới ánh trăng rạng rỡ lung linh. Anh khẽ nắm chặt lấy bàn tay thon nhỏ mềm mại của cô, ánh mắt tràn đầy sự kiên định, trân trọng và hạnh phúc vô hạn. "Yến này, cảm ơn em đã luôn tin tưởng và đồng hành cùng anh qua những ngày giông bão đen tối nhất của cuộc đời."</p>
<p>Yến khẽ tựa đầu vào vai anh đầy tin cậy, mỉm cười dịu dàng dưới ánh trăng bạc. "Giông bão đã qua rồi anh. Bây giờ là thời gian dành cho nghệ thuật sơn mài chân chính và cho hạnh phúc của hai chúng ta." Sắc sơn ta truyền thống sâu thẳm lấp lánh như ngọc tỏa sáng rực rỡ trên bức họa mới của họ dưới ánh trăng bạc, mở ra một tương lai huy hoàng đầy rực rỡ và vững bền mãi mãi về sau.</p>"""

    novel_blueprint["chapters"].append({"chap_num": 1, "title": "Chương 1: Bàn tay phế và nhát búa đuổi khỏi xưởng", "draft": ch1})
    novel_blueprint["chapters"].append({"chap_num": 2, "title": "Chương 2: Độc dược hóa chất và phương thuốc giữ tay", "draft": ch2})
    novel_blueprint["chapters"].append({"chap_num": 3, "title": "Chương 3: Bản phác thảo lưu dấu máu và sáng chế độc quyền", "draft": ch3})
    novel_blueprint["chapters"].append({"chap_num": 4, "title": "Chương 4: Quỹ đầu tư lý tính và cái bẫy giăng ra", "draft": ch4})
    novel_blueprint["chapters"].append({"chap_num": 5, "title": "Chương 5: Bão nổi 24 giờ thanh tra và tài khoản đóng băng", "draft": ch5})
    novel_blueprint["chapters"].append({"chap_num": 6, "title": "Chương 6: Bản sao kê đóng dấu đỏ và báo cáo kiểm toán Big 4", "draft": ch6})
    novel_blueprint["chapters"].append({"chap_num": 7, "title": "Chương 7: Phiên đấu giá quốc tế và cú lật kèo hoàn hảo", "draft": ch7})
    novel_blueprint["chapters"].append({"chap_num": 8, "title": "Chương 8: Đầu gối quỵ ngã của kẻ phản bội và sắc lệnh C03", "draft": ch8})

    # Validate word counts
    for chap in novel_blueprint["chapters"]:
        # Word count in Vietnamese: split space
        words = chap["draft"].replace("<p>", "").replace("</p>", "").replace("<strong>", "").replace("</strong>", "").replace("<em>", "").replace("</em>", "").split()
        print(f"✓ {chap['title']}: {len(words)} words")
        
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(novel_blueprint, f, ensure_ascii=False, indent=2)
        
    print(f"✓ Successfully wrote gold standard draft to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
