# -*- coding: utf-8 -*-
import json
import os
import requests

def main():
    print("Generating the blockbuster novel pending_novel.json...")
    
    title = "Vua Sâm Ngọc Linh Đất Kon Tum: Kẻ Bị Sỉ Nhục Lật Kèo Thâu Tóm Tập Đoàn Dược Liệu Nghìn Tỷ"
    author = "Antigravity"
    genre = "Sảng Văn"
    
    intro = (
        "<p><strong>\"Đôi bàn tay thô kệch dính bùn đất Tây Nguyên của mày, có lau sạch mười đời cũng không xứng chạm vào chậu sâm Ngọc Linh F2 đột biến trị giá mười tỷ này! Ký tên vào bản cam kết từ bỏ quyền sáng chế này rồi cút xéo khỏi Kon Tum!\"</strong></p>\n"
        "<p>Lời sỉ nhục cay đắng của Lâm Vĩnh Khang – Tổng Giám đốc chi nhánh Tây Nguyên thuộc Tập đoàn Dược liệu Lâm Gia – vang lên đanh thép giữa sảnh tòa nhà sang trọng ở Măng Đen. Đứng bên cạnh hắn, Nguyễn Cát Tường – vị hôn thê cũ phản bội của Lâm Gia Bảo – nở nụ cười khinh bỉ, thản nhiên giẫm nạt chậu sâm giống đột biến mà Bảo đã dành 5 năm thanh xuân nghiên cứu trên đỉnh núi sương mù. Bọn chúng cấu kết chiếm đoạt công trình khoa học của Bảo, vu khống anh chiếm đoạt tài sản công ty, tống cổ anh ra đường dưới cơn mưa rừng buốt giá, thậm chí cắt đứt viện phí điều trị của cha anh đang hôn mê sâu.</p>\n"
        "<p>Nhưng bọn chúng không hề biết rằng, công nghệ nhân bản sâm Ngọc Linh bán tự nhiên mà chúng vừa ăn cắp thực chất chứa một độc tố saponin loại R chết người, chỉ có thuật toán trung hòa độc quyền trong đầu Bảo mới có thể xử lý. Càng không ngờ, đồng hành cùng Bảo trong cuộc chiến sinh tử này lại là Nguyễn Trịnh Khánh Vy – đại ái nữ kiêu kỳ của Hoàng Cầu Capital. Vy là một nữ tổng tài cực kỳ lý tính, người chỉ ký hợp đồng đầu tư ba trăm tỷ đồng sau khi đã thông qua kiểm toán độc lập Big 4 và xác thực tính pháp lý vững chắc từ Cục Sở hữu Trí tuệ.</p>\n"
        "<p>Từ báo cáo kiểm toán vạch trần sâm lậu Trung Quốc, sự phục sinh kỳ diệu từ Đông - Tây y kết hợp của cha anh, đến sắc lệnh bắt giữ khẩn cấp từ C03... Lâm Gia Bảo sẽ từng bước lật ngược thế cờ, khiến kẻ thù sắc mặt xám ngoét không còn giọt máu, đầu gối bủn rủn quỵ xuống sàn đá cẩm thạch rỉ máu tươi, tận mắt chứng kiến đế chế nghìn tỷ sụp đổ tan tành!</p>"
    )
    
    cover_prompt = (
        "A premium, cinematic anime-style book cover, a sharp, confident young Vietnamese man with short black hair, "
        "wearing a sleek modern dark blue suit, holding a glowing wild Ngoc Linh ginseng root with golden glowing roots. "
        "In the background, the majestic misty mountains of Mang Den, Kon Tum combined with an elegant, modern "
        "scientific laboratory. Dramatic lighting, vibrant colors, highly detailed, 1:1, no text."
    )
    
    chapters = []
    
    # ------------------ CHAPTER 1 ------------------
    ch1_content = (
        "<p>Cơn mưa rừng tầm tã của vùng cao nguyên Măng Đen trút xuống xối xả, mang theo cái lạnh buốt xương của sương mù bao phủ khắp các ngọn đồi thông xanh ngắt. Thế nhưng, bầu không khí bên trong sảnh VIP của chi nhánh Tập đoàn Dược liệu Lâm Gia tại Kon Tum còn lạnh lẽo và căng thẳng hơn gấp bội. Dưới những ngọn đèn chùm pha lê đắt đỏ tỏa ra ánh sáng rực rỡ, Lâm Gia Bảo đứng lặng im, đôi mắt đen sâu thẳm nhìn chằm chằm vào chậu sâm Ngọc Linh F2 đang bị giẫm nát dưới chân. Những nhánh sâm giống xanh mướt, kết tinh từ năm năm lao động miệt mài của anh ở đỉnh Ngọc Linh, giờ đây chỉ còn là đống bùn đất hỗn độn trên sàn đá cẩm thạch sáng loang.</p>"
        "<p>\"Nhìn cái gì? Mày tiếc nuối đống cỏ rác này sao?\" Lâm Vĩnh Khang – gã anh họ hống hách, kiêm Tổng Giám đốc chi nhánh – nở nụ cười khẩy đầy ác độc. Hắn thong thả dùng đôi giày da cá sấu đắt tiền di di lên ngọn sâm cuối cùng, vỗ vỗ tay vào chiếc áo vest hiệu Armani sang trọng. \"Đôi bàn tay thô kệch dính bùn đất Tây Nguyên của mày, có lau sạch mười đời cũng không xứng chạm vào chậu sâm Ngọc Linh F2 đột biến trị giá mười tỷ này! Mày chỉ là một thằng kỹ sư quèn ăn bám danh tiếng gia tộc. Ký tên vào bản cam kết từ bỏ quyền sáng chế này rồi cút xéo khỏi Kon Tum!\"</p>"
        "<p>Đứng ngay sát bên cạnh Khang là Nguyễn Cát Tường – vị hôn thê cũ của Gia Bảo. Cô ta mặc chiếc đầm dạ hội trễ vai đắt đỏ, tay khoác chặt lấy cánh tay của Khang, ánh mắt nhìn Bảo với sự khinh miệt tột cùng. Mới chỉ vài tháng trước, khi Bảo còn là ngôi sao nghiên cứu của tập đoàn, cô ta còn ngọt ngào thề non hẹn biển. Nhưng ngay khi cha của Bảo – ông Lâm Quốc Vệ – bị tai biến mạch máu não lâm vào trạng thái hôn mê sâu, và thế lực của bác ruột Bảo là Chủ tịch Lâm Vĩnh Thế hoàn toàn thâu tóm hội đồng quản trị, Cát Tường đã lập tức quay xe, dâng hiến toàn bộ thông tin dự án của Bảo cho Khang để đổi lấy một tấm vé bước chân vào giới thượng lưu.</p>"
        "<p>\"Gia Bảo, mày đừng có cứng đầu nữa.\" Cát Tường nhếch môi, giọng nói lanh lảnh chứa đầy sự chế giễu. \"Anh Khang nói đúng đó. Mày ôm khát vọng nghiên cứu sâm Ngọc Linh tự nhiên để làm gì khi không có tiền? Gia đình mày giờ chỉ là gánh nặng. Cha mày đang nằm ở phòng hồi sức tích cực bệnh viện tỉnh, mỗi ngày tiêu tốn hàng chục triệu tiền máy thở. Nếu mày không ký bản cam kết từ bỏ quyền sáng chế này, anh Khang sẽ lập tức yêu cầu bệnh viện dừng mọi dịch vụ điều trị và phong tỏa toàn bộ tài khoản tiết kiệm của gia đình mày dưới danh nghĩa kiểm toán nội bộ của tập đoàn!\"</p>"
        "<p>Gia Bảo hít một hơi thật sâu, hai bàn tay siết chặt đến mức các khớp xương kêu răng rắc. Anh không đau đớn vì sự phản bội của Cát Tường, bởi loại phụ nữ hư vinh đó không xứng đáng với một giọt nước mắt của anh. Điều khiến anh phẫn nộ tột cùng là sự tàn nhẫn của Lâm Vĩnh Khang và Lâm Vĩnh Thế. Bọn họ sẵn sàng đẩy cha anh – người em ruột từng cùng bọn họ gầy dựng tập đoàn từ thuở sơ khai – vào con đường chết chỉ để cướp đoạt công trình nghiên cứu sâm Ngọc Linh đột biến F2 có hàm lượng Saponin hoạt tính cao gấp ba lần bình thường.</p>"
        "<p>\"Lâm Vĩnh Khang, các người nghĩ rằng cướp được tập tài liệu nghiên cứu và giẫm nát sâm giống của tôi là có thể sở hữu được công nghệ này sao?\" Bảo trầm giọng, ánh mắt lóe lên một tia sáng sắc bén như dao cạo. \"Bằng sáng chế gốc đã được tôi đăng ký bảo hộ độc quyền trên hệ thống Cục Sở hữu Trí tuệ dưới danh nghĩa cá nhân từ ba năm trước. Các người có cướp đi bản thảo thử nghiệm trong phòng lab này cũng vô dụng mà thôi.\"</p>"
        "<p>\"Ha ha ha!\" Lâm Vĩnh Khang cười lớn đầy ngạo mạn, tiếng cười vang vọng khắp sảnh tòa nhà. \"Bằng sáng chế cá nhân? Mày nghĩ Cục Sở hữu Trí tuệ sẽ nghe lời một thằng kỹ sư bị sa thải hay nghe theo thế lực của Tập đoàn Dược liệu Lâm Gia nghìn tỷ? Cha tao đã dùng quan hệ để gửi đơn khiếu nại, tố cáo mày ăn cắp tài nguyên của tập đoàn để nghiên cứu riêng. Toàn bộ tài khoản Vietcombank của mày đã bị đóng băng tạm thời để phục vụ điều tra thuế. Mày lấy tiền đâu để trả viện phí cho cha mày vào ngày mai? Ký vào đây, tao sẽ cho mày năm trăm triệu để lo hậu sự cho ông già. Nếu không, ngày mai mày chỉ có nước nhìn xác cha mày bị tống ra khỏi bệnh viện!\"</p>"
        "<p>Gia Bảo nhìn tờ giấy cam kết từ bỏ quyền sáng chế đặt trước mặt. Anh khẽ nhếch môi nở một nụ cười lạnh lùng đến xương tủy. Anh không ký, mà thản nhiên quay lưng bước thẳng ra khỏi sảnh tòa nhà dưới cơn mưa rừng giông bão. Sự độc ác của bọn chúng đã chạm đến giới hạn cuối cùng của anh. Hân hoan đi, Lâm Vĩnh Khang, bởi vì kể từ giây phút này, tôi sẽ bắt toàn bộ tập đoàn Lâm Gia phải trả một cái giá đắt gấp vạn lần!</p>"
    )
    chapters.append({"title": "Chương 1: Đạp Đổ Sâm Giống", "content": ch1_content})
    
    # ------------------ CHAPTER 2 ------------------
    ch2_content = (
        "<p>Cơn mưa rừng xối xả gào thét bên ngoài cửa kính phòng hồi sức tích cực của Bệnh viện Đa khoa Kon Tum. Trên giường bệnh, ông Lâm Quốc Vệ nằm bất động, gương mặt xám ngoét không còn một giọt máu, các chỉ số trên máy đo nhịp tim liên tục phát ra những tiếng bíp bíp dồn dập đầy nguy hiểm. Nhịp tim của ông đã sụt giảm nghiêm trọng xuống chỉ còn 40 lần/phút, huyết áp tụt dốc không phanh. Bác sĩ trưởng khoa ái ngại nhìn Gia Bảo, khẽ lắc đầu: \"Bệnh nhân bị xuất huyết não diện rộng, mạch máu bị chèn ép nghiêm trọng. Hơn nữa, phía Tập đoàn Lâm Gia vừa gửi văn bản cắt tài trợ viện phí và yêu cầu phong tỏa tài khoản đồng sở hữu. Chúng tôi buộc phải yêu cầu anh chuyển viện hoặc ngừng sử dụng các thiết bị hỗ trợ đặc biệt nếu không thể thanh toán khoản nợ 150 triệu đồng trước 12 giờ trưa nay.\"</p>"
        "<p>Đứng bên cạnh, gã kế toán trưởng của chi nhánh Lâm Gia cười khẩy ném tập hóa đơn nợ viện phí lên đùi Bảo: \"Chủ tịch đã nói rồi, không ký giấy chuyển nhượng bằng sáng chế thì một xu viện phí cũng đừng hòng có. Cứ chuẩn bị quan tài cho ông già đi là vừa!\"</p>"
        "<p>Gia Bảo không nói một lời. Ánh mắt anh lạnh lùng như băng tuyết ngàn năm trên đỉnh Ngọc Linh. Anh dứt khoát đuổi gã kế toán ra khỏi phòng bệnh, khóa chặt cửa lại. Nhìn người cha gầy gò đang thoi thóp giữa ranh giới sinh tử, Bảo biết mình không thể chần chừ thêm một giây nào nữa. Anh lập tức rút từ trong ba lô ra một hộp gỗ trắc nhỏ sờn cũ – bảo vật mà anh luôn mang theo bên người. Bên trong hộp là ba cây kim bạc châm cứu gia truyền và một lọ thủy tinh nhỏ chứa ba lát sâm Ngọc Linh rừng tự nhiên đột biến F0 hơn 50 năm tuổi mà anh đã tự tay đào được trên vách đá cheo leo của đỉnh núi Ngọc Linh trong một chuyến thực địa sinh tử.</p>"
        "<p>Bảo sát trùng nhanh các cây kim bạc dưới ánh đèn vàng ấm áp của phòng bệnh. Đôi bàn tay chai sạn của anh lúc này vô cùng vững chãi và chuẩn xác. Anh dứt khoát châm sâu vào huyệt Nhân Trung để khai khiếu tỉnh thần, tiếp tục hạ kim vào huyệt Bách Hội để bình can tức phong, điều hòa dòng máu não đang bị tắc nghẽn. Cuối cùng, anh châm nhẹ vào mười đầu ngón tay ở huyệt Thập Tuyên để nặn ra những giọt máu đen kịt nhằm giải tỏa áp lực nội sọ cấp bách đang tàn tạ não bộ của cha.</p>"
        "<p>Sau khi châm cứu xong, Bảo cẩn thận lấy một lát sâm Ngọc Linh tự nhiên 50 năm tuổi đặt vào dưới lưỡi của cha mình. Hoạt chất Saponin tự nhiên nồng độ cực cao từ lát sâm quý hiếm hòa tan nhanh chóng vào các mạch máu dưới lưỡi, trực tiếp truyền thẳng về tim để kích hoạt nguồn sinh mệnh lực đang lụi tàn. Đây chính là phương pháp Đông y cổ truyền \"Độc Sâm Thang\" kết hợp châm cứu thông mạch đỉnh cao mà Bảo đã học được từ những y thư cổ xưa.</p>"
        "<p>Chỉ mười lăm phút sau, phép màu Đông y đã xuất hiện ngay trước mắt. Nhịp tim của ông Lâm Quốc Vệ trên màn hình máy đo bắt đầu tăng dần ổn định từ 40 lên 75 lần/phút. Hơi thở đứt quãng dần trở nên sâu và đều đặn, sắc mặt xám ngoét biến mất, thay vào đó là làn da hồng hào đầy sức sống. Đúng lúc này, Vy – một người phụ nữ quyền lực mà Bảo vừa hẹn gặp qua điện thoại – đã điều phối xe cấp cứu chuyên dụng của Bệnh viện Đa khoa Quốc tế Vinmec đến đón cha anh sang phòng VIP đặc biệt.</p>"
        "<p>Tại phòng chẩn đoán hình ảnh cao cấp của Vinmec, vị Trưởng khoa Tây y cầm kết quả chụp MRI sọ não và xét nghiệm máu lâm sàng bước ra, gương mặt tràn đầy sự kinh ngạc tột độ. Ông nhìn Gia Bảo giống như đang nhìn một vị thần y: \"Kỳ tích! Hoàn toàn là kỳ tích y học! Bệnh nhân bị xuất huyết não nặng, thông thường tỷ lệ tử vong là 95% nếu không mổ phẫu thuật mở hộp sọ ngay lập tức. Nhưng các chỉ số lâm sàng hiện tại cho thấy dòng máu não đã tự động lưu thông hoàn hảo, các vùng hoại tử thần kinh đang tự động tái tạo với tốc độ kinh ngạc nhờ một hàm lượng hoạt chất Saponin quý hiếm cực cao trong máu. Phương pháp Đông y sơ cứu của anh đã bảo toàn hoàn hảo tế bào não của ông cụ! Tây y chúng tôi chỉ cần điều trị hỗ trợ nhẹ nhàng là ông cụ sẽ tỉnh lại hoàn toàn trong vài ngày tới!\"</p>"
        "<p>Nghe lời khẳng định đanh thép từ vị bác sĩ Tây y hàng đầu, Gia Bảo thở phào nhẹ nhõm. Anh siết chặt nắm tay, ánh mắt hướng về phía tòa nhà Tập đoàn Lâm Gia ở trung tâm thành phố. Lâm Vĩnh Khang, trò chơi bẩn thỉu của các người đã chính thức thất bại. Bây giờ, hãy chuẩn bị đón nhận cơn cuồng phong thịnh nộ của tôi!</p>"
    )
    chapters.append({"title": "Chương 2: Giọt Máu Độc Bản", "content": ch2_content})
    
    # ------------------ CHAPTER 3 ------------------
    ch3_content = (
        "<p>Chiều hôm sau, tại phòng VIP riêng tư của khách sạn năm sao Indochine Măng Đen, một cuộc gặp gỡ mang tính bước ngoặt lịch sử diễn ra dưới sự chứng kiến của các chuyên gia pháp lý hàng đầu. Ngồi đối diện với Lâm Gia Bảo là Nguyễn Trịnh Khánh Vy – Giám đốc đầu tư (CFO) của Hoàng Cầu Capital, quỹ đầu tư có tổng tài sản quản lý lên đến mười ngàn tỷ đồng. Vy diện một bộ âu phục màu đen cắt may tinh xảo của thương hiệu Chanel, ôm sát vóc dáng mảnh mai nhưng vô cùng quyến rũ. Khuôn mặt thanh tú với đôi mắt sắc sảo ẩn sau chiếc kính gọng vàng mỏng toát lên vẻ thông tuệ, lạnh lùng và kiêu sa của một nữ tài phiệt cực kỳ lý tính.</p>"
        "<p>Khánh Vy nổi tiếng trong giới tài chính là người phụ nữ lạnh lùng, chỉ nói chuyện bằng những con số, báo cáo kiểm toán pháp lý và giá trị thực tế của dự án, hoàn toàn không bị ảnh hưởng bởi cảm xúc hay dư luận bẩn bôi nhọ xung quanh. Cô nhấp một ngụm trà cổ thụ Shan Tuyết, nhìn thẳng vào mắt Bảo, giọng nói trong trẻo nhưng đầy uy lực: \"Anh Bảo, Tập đoàn Lâm Gia đang ráo riết truyền thông bẩn rằng anh là kẻ trộm cắp công nghệ giống sâm F2 của họ để tự ý ra ngoài thành lập công ty riêng. Hoàng Cầu Capital đang có kế hoạch đầu tư 300 tỷ đồng vào chuỗi sản xuất dược liệu cao cấp chuẩn quốc tế tại Kon Tum. Nhưng tôi cần những bằng chứng thép về mặt pháp lý và khoa học thực tế, chứ không phải những lời hứa hẹn suông.\"</p>"
        "<p>Gia Bảo thản nhiên mỉm cười. Anh mở chiếc laptop Lenovo ThinkPad sờn cũ, đẩy về phía cô bản hồ sơ kỹ thuật chi tiết cùng kết quả phân tích quang phổ: \"Tôi thích sự thực tế của cô, cô Vy. Hãy xem kỹ bản thiết kế này. Đây là bằng sáng chế độc quyền về quy trình chiết xuất Saponin tinh khiết từ sâm Ngọc Linh F2 bằng công nghệ lên men sinh học bán tự nhiên. Tôi đã đăng ký bảo hộ độc quyền dưới tên cá nhân tôi từ 3 năm trước, mã số sáng chế đã được Cục Sở hữu Trí tuệ Việt Nam phê duyệt đóng dấu đỏ bất biến.\"</p>"
        "<p>Bảo rút ra tiếp một tập tài liệu dày cộp: \"Còn đây là nhật ký commit mã nguồn hệ thống điều khiển môi trường nuôi cấy sâm trên Git server cá nhân của tôi. Từng dòng code, từng mốc thời gian commit đều có chữ ký số bất biến của tôi suốt 5 năm qua. Thứ mà Lâm Vĩnh Khang ăn cắp được từ phòng lab chi nhánh thực chất chỉ là phiên bản thử nghiệm sơ khai F1. Phiên bản đó chứa một lỗi cấu trúc sinh học vô cùng nguy hiểm: nếu nuôi cấy kích thích bằng hóa chất kích thích tăng trưởng nồng độ cao để rút ngắn thời gian thu hoạch, sâm sẽ sản sinh ra hoạt chất độc tính Saponin loại R, gây co thắt cơ tim cấp tính cho người sử dụng. Chỉ có thuật toán điều chỉnh môi trường đột biến F2 của tôi mới kiểm soát được hoạt chất này.\"</p>"
        "<p>Khánh Vy nheo mắt nhìn kỹ từng trang báo cáo. Đội ngũ luật sư độc lập đi cùng cô cũng lập tức truy cập vào hệ thống dữ liệu quốc gia của Cục Sở hữu Trí tuệ để xác minh pháp lý. Sau mười lăm phút thẩm định vô cùng tỉ mỉ và nghẹt thở, vị luật sư trưởng đại diện của văn phòng Baker McKenzie khẽ gật đầu với Vy: \"Thưa cô Vy, tất cả giấy tờ pháp lý bằng sáng chế của anh Lâm Gia Bảo hoàn toàn Bulletproof – vững chắc 100%. Tập đoàn Lâm Gia không hề có quyền sở hữu trí tuệ đối với công nghệ F2 đột biến này. Những gì họ đang tuyên bố hoàn toàn là giả mạo pháp lý.\"</p>"
        "<p>Ánh mắt Khánh Vy lóe lên một tia sáng kinh ngạc xen lẫn sự thán phục tột cùng dành cho chàng kỹ sư trẻ tuổi đứng trước mặt cô. Sự kiên cường, chuẩn xác và tầm nhìn khoa học vĩ đại của Bảo hoàn toàn vượt xa những gã thiếu gia hào môn rỗng tuếch mà cô thường gặp trong các bữa tiệc thượng lưu ở Sài Gòn và Hà Nội. Cô đặt ly trà xuống bàn, nở nụ cười kiêu sa đầy quyết đoán: \"Rất xuất sắc! Tôi quyết định Hoàng Cầu Capital sẽ chính thức đầu tư ba trăm tỷ đồng để thành lập Tập đoàn Dược liệu Ngọc Linh Vương do anh làm Chủ tịch kiêm Giám đốc công nghệ nắm giữ 60% cổ phần, chúng tôi nắm giữ 40% cổ phần. Hợp đồng đầu tư sẽ được ký kết ngay bây giờ!\"</p>"
    )
    chapters.append({"title": "Chương 3: Nữ Tổng Tài Lý Tính", "content": ch3_content})
    
    # ------------------ CHAPTER 4 ------------------
    ch4_content = (
        "<p>Dòng tiền giải ngân đợt một trị giá một trăm tỷ đồng từ Hoàng Cầu Capital lập tức được chuyển thẳng vào tài khoản doanh nghiệp mới thành lập của Tập đoàn Dược liệu Ngọc Linh Vương. Lâm Gia Bảo nhanh chóng thuê mặt bằng xây dựng nhà máy chế biến công nghệ cao quy mô lớn ngay tại khu công nghiệp Măng Đen, đồng thời thu mua 20 hecta đất rừng tự nhiên ven sườn núi Ngọc Linh để lập trang trại bảo tồn sâm giống F2 đột biến. Sự hợp tác chấn động giới tài chính giữa đại ái nữ tập đoàn Hoàng Cầu và chàng kỹ sư bị Lâm Gia sa thải đã giáng một đòn đau điếng vào tham vọng IPO nghìn tỷ của Lâm Vĩnh Khang và Lâm Vĩnh Thế.</p>"
        "<p>Tại biệt thự sang trọng của Lâm Vĩnh Khang ở Kon Tum, hắn điên cuồng ném vỡ những ly rượu vang đắt tiền xuống sàn nhà khi nhìn thấy thông cáo báo chí chung của Ngọc Linh Vương và Hoàng Cầu Capital. Cát Tường ngồi bên cạnh, mặt mũi xanh mét lo sợ: \"Anh Khang, làm sao bây giờ? Nếu Hoàng Cầu Capital đầu tư mạnh như vậy, công nghệ F2 đột biến thật sự nằm trong tay Lâm Gia Bảo thì đợt phát hành cổ phiếu IPO của chúng ta vào tháng tới sẽ bị Ủy ban Chứng khoán hủy bỏ vì thiếu tài sản trí tuệ hợp pháp mất!\"</p>"
        "<p>Lâm Vĩnh Khang nghiến răng ken két, gương mặt đỏ gay đầy dữ tợn: \"Con mẹ nó! Tao không tin một thằng kỹ sư quèn không có gốc gác lại có thể lật kèo được tao! Tao đã chuẩn bị sẵn một kế hoạch tàn khốc để bóp chết nó ngay tại Măng Đen này. Tao sẽ dùng toàn bộ thế lực quan hệ ngầm để đóng băng dòng tiền đầu tư của nó, đồng thời bôi nhọ thương hiệu mới của nó trên khắp các phương tiện truyền thông cho đến khi nó phá sản hoàn toàn!\"</p>"
        "<p>Ngay đêm hôm đó, Lâm Vĩnh Khang bắt đầu kích hoạt mạng lưới quan hệ tối tăm của mình. Hắn đút lót một khoản tiền khổng lồ cho tên trưởng đoàn thanh tra liên ngành Lê Văn Huân – một kẻ khét tiếng tham nhũng và biến chất. Hắn yêu cầu Huân lập tức tổ chức một cuộc thanh tra đột xuất quy mô lớn nhằm vào nhà máy đang xây dựng và trang trại sâm giống của Bảo tại Măng Đen để tìm mọi cách đình chỉ hoạt động của anh. Đồng thời, hắn thuê hàng loạt KOL bẩn trên Tiktok và các streamer nổi tiếng của giới dược liệu để tung ra những video clip dàn dựng cảnh cụ già uống sâm Ngọc Linh Vương bị ngộ độc cấp cứu, tạo nên một cơn bão truyền thông bẩn quét sạch uy tín của Bảo chỉ trong một đêm.</p>"
    )
    chapters.append({"title": "Chương 4: Ký Kết Trăm Tỷ", "content": ch4_content})
    
    # ------------------ CHAPTER 5 ------------------
    ch5_content = (
        "<p>Sáng sớm thứ Năm, bầu không khí tại khu công nghiệp Măng Đen bao phủ bởi sương mù lạnh lẽo. Bất ngờ, một đoàn xe biển xanh của đoàn thanh tra liên ngành do Lê Văn Huân dẫn đầu ầm ầm kéo đến cổng nhà máy Ngọc Linh Vương. Chúng ngang ngược vượt qua hàng rào bảo vệ, đưa ra quyết định tạm đình chỉ hoạt động khẩn cấp trong vòng 24 giờ để điều tra toàn bộ quy trình môi trường, an toàn sinh học và nguồn gốc xuất xứ của sâm giống F2. Bất kể các chuyên gia pháp lý của Bảo đưa ra đầy đủ giấy tờ hợp lệ của Cục Sở hữu Trí tuệ và Bộ Y tế, Lê Văn Huân vẫn ngang tàng ra lệnh dán giấy niêm phong đỏ lên toàn bộ hệ thống máy móc chiết xuất laser hiện đại của nhà máy.</p>"
        "<p>Cùng lúc đó, Gia Bảo nhận được thông báo khẩn từ ngân hàng Techcombank và Vietcombank: Toàn bộ tài khoản thanh toán đứng tên doanh nghiệp Ngọc Linh Vương tạm thời bị phong tỏa trong vòng 48 giờ để phục vụ công tác điều tra thuế khẩn cấp theo yêu cầu của cơ quan thuế tỉnh. Trên các trang mạng xã hội, hàng chục ngàn tài khoản ảo liên tục chia sẻ video clip bôi nhọ của các KOL bẩn, cáo buộc sâm Ngọc Linh Vương sử dụng hóa chất kích thích tăng trưởng cực độc hại nhập khẩu từ Trung Quốc gây suy thận cho người tiêu dùng. Dư luận phẫn nộ đổ dồn gạch đá vào Bảo và Hoàng Cầu Capital.</p>"
        "<p>Bế tắc hoàn toàn bao trùm lên doanh nghiệp mới thành lập. Tại văn phòng chi nhánh Hoàng Cầu Capital ở trung tâm thành phố, không khí cuộc họp ban hội đồng quản trị căng thẳng tột độ như một lò lửa chuẩn bị phát nổ. Các cổ đông lớn của quỹ liên tục đập bàn giận dữ, la hét yêu cầu Nguyễn Trịnh Khánh Vy phải lập tức ký quyết định rút toàn bộ nguồn vốn 300 tỷ đồng để bảo vệ an toàn danh tiếng của quỹ trước làn sóng phẫn nộ của dư luận. Bọn họ đe dọa sẽ bãi nhiệm chức vụ CFO của cô nếu cô tiếp tục ngoan cố bảo vệ một kẻ đang bị phong tỏa tài khoản ngân hàng và bị đình chỉ hoạt động nhà máy.</p>"
        "<p>\"Gia Bảo, tình hình bên anh thế nào rồi?\" Giọng Khánh Vy vang lên qua điện thoại, dù cô vẫn cố giữ sự bình tĩnh lý tính thường ngày nhưng không giấu nổi sự nghiêm trọng tột cùng trước sức ép nghẹt thở của ban hội đồng quản trị. \"Hội đồng quản trị của tôi đang bỏ phiếu khẩn cấp để rút vốn đầu tư. Tôi chỉ có thể trì hoãn họ bằng uy tín cá nhân của mình trong vòng đúng 24 giờ nữa mà thôi. Nếu trước sáng mai anh không thể đập tan toàn bộ những cáo buộc bẩn thỉu kia và gỡ niêm phong nhà máy, tôi buộc phải ký quyết định phong tỏa nguồn vốn theo quy định bắt buộc của quỹ đầu tư!\"</p>"
        "<p>Gia Bảo đứng trước cổng nhà máy đang bị niêm phong đỏ, nhìn những người công nhân đang hoang mang dừng việc dưới cơn mưa rừng lác đác. Gương mặt anh không hề có một chút hoang mang hay sợ hãi, trái lại, đôi mắt anh lóe lên một tia sáng sắc bén đầy tự tin và lạnh lùng. Anh khẽ cười nhạt, trầm giọng nói qua điện thoại: \"Vy, hãy tin tôi. Sự bế tắc này thực chất là bước đi cuối cùng nằm trong kế hoạch phản công của tôi. Khi Lâm Vĩnh Khang sử dụng đến những quân bài bẩn thỉu nhất và nghĩ rằng đã dồn chúng ta vào đường cùng, hắn sẽ tự mãn nhất và cũng chính là lúc hắn sơ hở nhất. Hãy chuẩn bị cho tôi một buổi livestream công nghệ trực tiếp vào tối mai ngay tại đại hội công bố đối tác chiến tác nghìn tỷ của Tập đoàn Lâm Gia. Tôi sẽ cho cô thấy màn lật kèo hoàn hảo nhất cuộc đời tôi!\"</p>"
    )
    chapters.append({"title": "Chương 5: Bão Tố Măng Đen", "content": ch5_content})
    
    # ------------------ CHAPTER 6 ------------------
    ch6_content = (
        "<p>Đêm trước ngày diễn ra sự kiện trọng đại quyết định sinh tử của hai doanh nghiệp, bầu trời Măng Đen dịu mát, sương mù bảng lảng trôi nhẹ qua những rặng thông già cổ thụ. Trên ban công tầng thượng của một biệt thự cổ kính thời Pháp thuộc nhìn thẳng ra thung lũng thông reo rì rào dưới ánh trăng rằm sáng vằng vặc, Lâm Gia Bảo và Nguyễn Trịnh Khánh Vy ngồi bên nhau bên chiếc bàn gỗ nhỏ ấm áp. Ánh nến lung linh tỏa ra những luồng sáng vàng ấm áp dịu dàng, chiếu lên khuôn mặt kiều diễm nhưng mang đầy vẻ mỏi mệt của nữ tổng tài kiêu sa. Cô đã cởi bỏ bộ vest công sở cứng nhắc hàng ngày, thay bằng chiếc váy lụa màu trắng ngọc trai thanh lịch ôm sát cơ thể quyến rũ.</p>"
        "<p>\"Báo cáo kiểm toán độc lập của PwC đối với kho sâm giống của Tập đoàn Lâm Gia đã hoàn thành.\" Khánh Vy đặt một tập hồ sơ mỏng lên bàn kính, khẽ nâng ly rượu vang đỏ chạm nhẹ vào ly của Bảo, đôi mắt sắc sảo của cô ánh lên sự thán phục tột cùng dành cho trí tuệ của anh. \"Đúng như những gì anh đã dự đoán chính xác tuyệt đối, báo cáo kiểm toán cho thấy hơn 90% trữ lượng sâm Ngọc Linh mà Lâm Gia công bố trong hồ sơ IPO thực chất chỉ là sâm giả giá rẻ được nhập lậu qua biên giới Trung Quốc, rồi được đưa về Măng Đen ngâm tẩm hóa chất kích thích tăng trưởng cực mạnh để rút ngắn thời gian thu hoạch từ 6 năm xuống còn 6 tháng. Quy trình cấy mô của chúng hoàn toàn sản sinh ra hoạt chất độc tính Saponin loại R chết người. Chúng đã nâng khống giá trị kho dược liệu lên gấp trăm lần để lừa dối hàng ngàn nhà đầu tư.\"</p>"
        "<p>Gia Bảo nhấp một ngụm rượu vang ấm nóng, ánh mắt lạnh lùng nhìn ra thung lũng sương mù: \"Lâm Vĩnh Khang và Lâm Vĩnh Thế đã tự đào mồ chôn mình khi cố tình dùng sâm giả tẩm hóa chất độc hại để làm đẹp sổ sách tài chính trước ngày IPO. Chúng nghĩ rằng công nghệ nhuộm màu và làm giả của chúng có thể che mắt được toàn bộ giới y học Việt Nam. Nhưng chúng không biết rằng thuật toán quang phổ laser của tôi có thể phát hiện ra dư lượng hóa chất và độc tố R đó chỉ trong vòng ba giây quét trực tiếp. Ngày mai, tôi sẽ kích hoạt quả bom này ngay trước mặt hàng triệu người xem truyền hình.\"</p>"
        "<p>Khánh Vy nhìn chàng trai trẻ ngồi bên cạnh mình dưới ánh trăng huyền ảo. Lần đầu tiên trong đời, trái tim lý tính và lạnh lùng của nữ tài phiệt hào môn khẽ rung động mạnh mẽ trước sự kiên định vững chãi như núi Ngọc Linh của Bảo. Cô khẽ đặt bàn tay mềm mại, mịn màng của mình lên bàn tay chai sạn vì dầm mưa dãi nắng của anh, chân thành thổ lộ: \"Nam, cuộc sống hào môn từ nhỏ đã dạy tôi không được tin tưởng bất kỳ ai ngoài những con số và báo cáo pháp lý sòng phẳng. Nhưng những ngày giông bão vừa qua, nhìn cách anh kiên cường đứng vững bảo vệ tri thức khoa học và danh dự của cha mình, tôi biết mình đã tìm thấy điểm tựa thực sự của cuộc đời. Anh không giống những gã thiếu gia rỗng tuếch ngoài kia luôn dùng tiền của cha mẹ để khoe khoang quyền lực ảo. Anh có linh hồn của một người nghệ sĩ mài ngọc chân chính, sắc bén và kiên định không thể bị bẻ gãy. Tôi tin Ngọc Linh Vương dưới tay anh sẽ vươn tầm thế giới.\"</p>"
        "<p>Gia Bảo nhìn thẳng vào đôi mắt trong veo đầy cảm xúc của Vy. Anh rút từ túi áo ra một sợi dây chuyền bạc vô cùng tinh xảo, mặt dây chuyền là một viên sâm ngọc thạch tự nhiên tuyệt đẹp màu đỏ rực rỡ như một giọt máu tinh khiết, được anh tự tay cắt gọt mài bóng tỉ mỉ trong phòng lab: \"Vy, đây là viên sâm ngọc thạch quý hiếm nhất tôi đào được trên đỉnh núi. Nó là biểu tượng cho sự kiên cường và lòng tin tuyệt đối giữa tôi và cô. Hãy để tôi tự tay đeo sợi dây chuyền này cho cô, như một lời thề sẽ luôn đứng bên cạnh bảo vệ cô trước mọi giông bão cuộc đời.\"</p>"
        "<p>Khánh Vy khẽ đỏ mặt dưới ánh nến huyền ảo. Cô nhẹ nhàng quay lưng để Bảo tự tay đeo sợi dây chuyền lên chiếc cổ cao trắng ngần của mình. Làn da mịn màng chạm vào bàn tay ấm áp của Bảo tạo nên một luồng điện xúc cảm dịu ngọt lan tỏa khắp hai cơ thể. Dưới bầu trời đêm đầy sao lấp lánh của vùng cao nguyên Măng Đen, hai tâm hồn kiên cường và lý tính đã chính thức hòa chung một nhịp đập, sẵn sàng bước vào trận chiến quyết tử vào ngày mai để quét sạch toàn bộ lũ gian thương phản bội.</p>"
    )
    chapters.append({"title": "Chương 6: Lời Hứa Trên Đỉnh Đồi", "content": ch6_content})
    
    # ------------------ CHAPTER 7 ------------------
    ch7_content = (
        "<p>Sự kiện đại hội công bố đối tác chiến lược và giới thiệu dự án IPO nghìn tỷ của Tập đoàn Dược liệu Lâm Gia diễn ra vô cùng hoành tráng tại đại sảnh lộng lẫy rộng một ngàn mét vuông của khách sạn năm sao Sheraton Hà Nội. Khắp đại sảnh được trang hoàng bằng thảm đỏ cao cấp, hoa hồng trắng nhập khẩu và hàng trăm bức ảnh trưng bày những củ sâm Ngọc Linh khổng lồ được gắn mác sâm cổ thụ tự nhiên. Hàng trăm khách mời thuộc giới siêu giàu, các quỹ đầu tư quốc tế lớn, các chuyên gia dược liệu hàng đầu Đông Nam Á và giới truyền thông báo chí tài chính đều có mặt đông đủ dưới ánh đèn chùm pha lê rực rỡ tỏa sáng lung linh.</p>"
        "<p>Trên sân khấu lớn được thiết kế hoành tráng, Lâm Vĩnh Khang khoác trên mình bộ vest đặt may riêng đắt đỏ, gương mặt tròn trịa ngập tràn sự đắc ý và kiêu ngạo tột cùng. Hắn vênh váo đi lại, trên tay luôn thường trực ly champagne đắt giá để chúc mừng các nhà đầu tư lớn. Đi bên cạnh hắn là Nguyễn Cát Tường diện chiếc đầm đính hàng ngàn viên kim cương lấp lánh, liên tục cười nói vui vẻ trước các ống kính phóng viên chụp ảnh liên hồi để khoe khoang sự giàu có ảo của mình.</p>"
        "<p>\"Kính thưa toàn thể quý vị khách quý và các nhà đầu tư chiến lược!\" Giọng Lâm Vĩnh Khang vang dội đanh thép khắp khán phòng qua hệ thống âm thanh hiện đại, thu hút toàn bộ sự chú ý của mọi người. \"Đêm nay, Tập đoàn Dược liệu Lâm Gia vô cùng tự hào công bố dự án sâm Ngọc Linh F2 đột biến sinh học quy mô lớn nhất Việt Nam. Đây là công trình độc quyền của chúng tôi đã được đăng ký quyền sở hữu trí tuệ toàn quốc, chuẩn bị đưa tập đoàn đạt giá trị vốn hóa hàng chục ngàn tỷ đồng sau đợt IPO thành công rực rỡ vào tuần tới! Chúng tôi khẳng định không có bất kỳ sản phẩm sâm nào trên thế giới có thể so sánh được với cực phẩm sâm Ngọc Linh F2 của Lâm Gia về hàm lượng Saponin tự nhiên siêu việt!\"</p>"
        "<p>Theo hiệu lệnh của Khang, chiếc tủ kính cường lực chống đạn ở trung tâm sân khấu từ từ mở ra. Dưới ánh đèn rọi chuyên dụng có độ sáng cực cao, củ sâm Ngọc Linh khổng lồ nặng gần 1kg được đặt trên bục gỗ trắc hiện ra trước sự trầm trồ, kinh ngạc và thán phục của toàn bộ khán phòng. Những tiếng vỗ tay vang dội như sấm dậy, các ống kính phóng viên liên tục chớp nháy tạo nên những luồng sáng trắng liên hồi bao trùm toàn bộ sân khấu. Cát Tường kiêu ngạo hếch cằm nhìn xuống khán phòng, thầm nghĩ Lâm Gia Bảo giờ này chắc đang nhục nhã khóc lóc trong đống bùn đất Măng Đen vì bị phong tỏa tài sản hoàn toàn.</p>"
    )
    chapters.append({"title": "Chương 7: Buổi Đấu Thầu Sóng Gió", "content": ch7_content})
    
    # ------------------ CHAPTER 8 ------------------
    ch8_content = (
        "<p>\"Củ sâm đó hoàn toàn là giả! Đó chỉ là sâm lậu rẻ tiền được bơm tẩm hóa chất kích thích tăng trưởng cực độc hại gây suy thận cấp!\"</p>"
        "<p>Một giọng nói trầm tĩnh, vang vọng đầy uy lực đột ngột cắt ngang bầu không khí náo nhiệt và tiếng vỗ tay của đại hội. Cánh cửa gỗ lớn của đại sảnh Sheraton bị đẩy mạnh ra. Lâm Gia Bảo bước vào, đĩnh đạc và phong trần trong bộ vest đen cắt may tinh xảo, đi bên cạnh anh là Nguyễn Trịnh Khánh Vy kiêu sa đeo sợi dây chuyền sâm ngọc thạch lấp lánh tỏa sáng dịu dàng. Sự xuất hiện bất ngờ của hai người khiến toàn bộ khách mời, các phóng viên tài chính và các nhà đầu tư lớn xôn xao đứng dậy, các ống kính máy quay lập tức xoay chuyển hướng về phía cửa ra vào tạo nên một làn sóng xầm xì cực lớn khắp khán phòng.</p>"
        "<p>\"Lâm Gia Bảo? Thằng ăn cắp bị sa thải kia, ai cho phép mày bước vào đây phá hoại đại hội của tập đoàn tao? Bảo vệ đâu, lập tức còng tay ném nó ra ngoài đường!\" Lâm Vĩnh Khang đỏ gay mặt vì giận dữ, hắn chỉ tay hét lớn đầy hung hãn trên sân khấu.</p>"
        "<p>\"Ai dám đuổi Chủ tịch của chúng tôi?\" Nguyễn Trịnh Khánh Vy bước lên trước một bước, giơ cao quyết định của tòa án và tập văn bản đóng dấu đỏ của Quỹ Hoàng Cầu. \"Theo quy chế công bố thông tin IPO quốc gia, bất kỳ cổ đông và đại diện hợp pháp sở hữu trí tuệ nào cũng có quyền yêu cầu đối chất công khai nếu phát hiện doanh nghiệp có hành vi gian lận thương mại và lừa dối nhà đầu tư nghiêm trọng. Lâm Gia Bảo là tác giả duy nhất sở hữu bằng sáng chế độc quyền quy trình F2 đã được Cục Sở hữu Trí tuệ cấp chứng nhận hợp pháp. Anh ấy hoàn toàn có quyền kiểm tra củ sâm kia trước khi đại hội tiếp tục!\"</p>"
        "<p>Trước sức ép của hàng trăm khách mời siêu giàu, giới truyền thông lớn và các phóng viên đang livestream trực tiếp trên khắp các kênh tài chính quốc gia, Lâm Vĩnh Khang không thể từ chối mà không làm dấy lên sự nghi ngờ về tính minh bạch của tập đoàn. Hắn nghiến răng tự đắc, nghĩ rằng công nghệ nhuộm màu và ngâm hóa chất kích thích tinh vi của mình không thể bị phát hiện bằng mắt thường: \"Được, tao cho mày quét! Nếu mày không chứng minh được nó là giả bằng khoa học thực tế, tao sẽ khởi tố mày tội phá hoại thương mại và bắt mày ngồi tù mọt xương ngay lập tức!\"</p>"
        "<p>Gia Bảo đĩnh đạc bước lên sân khấu trước hàng trăm ánh mắt nghẹt thở của toàn bộ khán phòng. Anh rút từ trong túi da ra chiếc máy quét laser quang phổ di động do chính anh chế tạo, kết nối trực tiếp với hệ thống màn hình LED khổng lồ rộng 100 inch của hội trường qua cổng HDMI. Tia laser màu xanh lục sắc lẹm bắn thẳng vào cấu trúc tinh thể của củ sâm đang đặt trên bục gỗ trắc trước sự chứng kiến của mọi người.</p>"
        "<p>Chỉ ba giây sau, một biểu đồ phân tích sóng hồng ngoại hiện ra trên màn hình lớn. Các đường cong quang phổ liên tục dao động phức tạp rồi đột ngột hiển thị một đường đỏ chót kéo dài cùng dòng chữ cảnh báo nhấp nháy màu đỏ rực: **\"CẤU TRÚC SÂM LẬU TRUNG QUỐC - HÓA CHẤT KÍCH THÍCH NỒNG ĐỘ CAO - ĐỘC TỐ SAPONIN R: 100% TOXIC\"**. Kết quả quét rõ ràng chứng minh củ sâm Ngọc Linh tự nhiên cực phẩm kia thực chất chỉ là sâm giả giá rẻ được ngâm tẩm hóa chất tăng trưởng cực mạnh sản sinh ra hoạt chất độc tính Saponin loại R chết người, hoàn toàn thiếu đi tạp chất tự nhiên – dấu vân tay địa chất duy nhất của sâm Ngọc Linh thật.</p>"
        "<p>Toàn bộ khán phòng vỡ òa trong sự kinh hoàng tột độ. Tiếng xôn xao, bàn tán vang lên như sấm dậy. Các phóng viên liên tục chụp ảnh màn hình LED hiển thị kết quả phân tích rõ ràng. </p>"
        "<p>Chưa dừng lại ở đó, Nguyễn Trịnh Khánh Vy bước lên bục phát biểu, dứt khoát công bố tập tài liệu thứ hai lên màn hình lớn: \"Đây là báo cáo kiểm toán độc lập của Big 4 PwC chứng minh Tập đoàn Lâm Gia đã cố ý nhập lậu hàng tấn sâm giá rẻ từ biên giới Trung Quốc, rồi đưa về trang trại Măng Đen ngâm hóa chất để làm giả sâm Ngọc Linh đột biến F2, nhằm nâng khống giá trị tài sản ròng lên gấp trăm lần để lừa dối nhà đầu tư. Và đây...\" Vy bấm nút điều khiển trên tay, màn hình LED lập tức chuyển sang một đoạn video clip camera ẩn vô cùng sắc nét ghi lại cảnh Lâm Vĩnh Khang tự tay chỉ đạo đám thuộc hạ ngâm tẩm hóa chất kích thích vào sâm giả trong hầm kín đêm trước nhằm tẩu tán tài sản.</p>"
        "<p>\"Không... việc này không thể... làm sao mày có được...\" Lâm Vĩnh Khang nhìn màn hình hiển thị những bằng chứng sắt đá và đoạn video clip vạch trần tội ác, đầu gối bỗng chốc bủn rủn rụng rời hoàn toàn. Sắc mặt hắn xám ngoét không còn một giọt máu, toàn thân khuỵu xuống nền gạch đá cẩm thạch mát lạnh của phòng đấu giá Sofitel. Mồ hôi lạnh chảy thành dòng bên thái dương ướt sũng cả chiếc áo sơ mi đắt tiền, hơi thở dồn dập rồi nghẹn ứ ở cổ họng, hắn hoảng loạn đến mức nghiến răng quá chặt làm rỉ ra một vệt máu tươi bên khóe môi. Hắn biết rõ đời hắn, sự nghiệp và đế chế của hắn đã hoàn toàn kết thúc tàn khốc.</p>"
        "<p>Nguyễn Cát Tường đứng bên cạnh cũng hét lên một tiếng đầy kinh hoàng trước sự sụp đổ của giấc mơ hào môn. Đôi chân cô ta run rẩy lẩy bẩy rồi quỵ xuống dưới chân bàn đấu giá như một con búp bê đứt dây. Cô ta điên cuồng cào cấu vào thành gỗ của bục gỗ trắc đến mức móng tay rỉ máu tươi, lớp trang điểm đắt tiền lem luốc khắp mặt mày vì nước mắt hoảng sợ tột cùng. Cô ta nhìn Bảo với ánh mắt đầy hối hận và van xin, nhưng tất cả đã quá muộn màng. Sự kiêu ngạo vô bờ bến của bọn họ đã phải trả một cái giá đắt nhất dưới chân tri thức và công lý.</p>"
    )
    chapters.append({"title": "Chương 8: Vạch Trần Sự Thật", "content": ch8_content})
    
    # ------------------ CHAPTER 9 ------------------
    ch9_content = (
        "<p>Cánh cửa gỗ lớn của khách sạn Sheraton một lần nữa bị đẩy mạnh ra bởi những bước chân đĩnh đạc và nghiêm nghị. Một đội cảnh sát điều tra mặc thường phục bước vào, dẫn đầu là đồng chí phó cục trưởng của Cục Cảnh sát Điều tra Tội phạm về Tham nhũng, Kinh tế, Buôn lậu (C03 Bộ Công an). Ông giơ cao tấm thẻ ngành màu đỏ quyền lực và đọc to sắc lệnh khởi tố đanh thép cùng lệnh bắt tạm giam đối với Lâm Vĩnh Khang và Lâm Vĩnh Thế về hành vi buôn lậu dược liệu trái phép, trốn thuế quy mô lớn và gian lận tài chính nghiêm trọng lừa đảo hàng trăm tỷ đồng của các nhà đầu tư.</p>"
        "<p>\"Các anh công an, có sự nhầm lẫn gì ở đây rồi! Tập đoàn của tôi hoàn toàn tuân thủ pháp luật!\" Lâm Vĩnh Thế – vị Chủ tịch kiêu hãnh của Lâm Gia lúc này vừa chạy từ phòng VIP ra, gương mặt nhăn nheo xám xịt, lớn tiếng chống chế đầy bất lực.</p>"
        "<p>\"Nhầm lẫn sao?\" Đồng chí phó cục trưởng lạnh lùng cười nhạt, vẫy tay ra hiệu cho cấp dưới công bố tập hồ sơ tài liệu thứ ba lên màn hình máy chiếu lớn của hội trường. \"Đây là bản sao kê chi tiết tất cả tài khoản ngân hàng đóng dấu đỏ của Tập đoàn Lâm Gia và các công ty vỏ bọc tại Singapore, ghi nhận rõ ràng các giao dịch chuyển tiền hàng chục triệu USD để thanh toán cho các lô sâm lậu từ Trung Quốc. Đồng thời, đây là kết quả đối chiếu mã nguồn LIMS của phòng nghiên cứu lâm sàng do chuyên gia Lâm Gia Bảo cung cấp, chứng minh các anh đã biết rõ sâm giống nuôi cấy kích thích sản sinh độc tố R nguy hại tính mạng nhưng vẫn cố tình phát tán ra thị trường. Lệnh bắt giữ đã được Viện Kiểm sát Nhân dân Tối cao phê chuẩn chính thức!\"</p>"
        "<p>Từng lời đọc đanh thép của cơ quan điều tra vang vọng khắp đại sảnh Sheraton giống như những hồi chuông báo tử vang dội giáng thẳng vào đầu hai cha con Lâm Vĩnh Thế. Hàng chục phóng viên tài chính liên tục chớp nháy ống kính máy ảnh để ghi lại khoảnh khắc lịch sử sụp đổ của một đế chế dược liệu nghìn tỷ. Đội cảnh sát dứt khoát bước lên, nhanh chóng khóa chặt hai tay Lâm Vĩnh Khang và Lâm Vĩnh Thế bằng chiếc còng số 8 bằng thép lạnh ngắt trước sự chứng kiến của toàn thể giới tinh hoa Hà Thành.</p>"
        "<p>Lâm Vĩnh Khang lúc này hoàn toàn suy sụp, đầu gối bủn rủn khuỵu sụp xuống sàn nhà Sofitel, mồ hôi lạnh chảy thành dòng ướt sũng vạt áo vest Armani đắt đỏ. Sắc mặt hắn xám ngoét như tro tàn không còn một giọt máu, đôi mắt trợn ngược hoảng sợ tột cùng nhìn Lâm Gia Bảo đang đứng đĩnh đạc trên sân khấu bên cạnh ái nữ tài phiệt Nguyễn Trịnh Khánh Vy. Hắn biết rõ từ nay cuộc đời hắn sẽ chỉ còn là những ngày tháng tăm tối sau song sắt nhà tù. Sự trả giá tàn khốc và nhục nhã nhất đã chính thức ập xuống đầu những kẻ vong ân bội nghĩa, khinh rẻ tri thức khoa học chân chính.</p>"
    )
    chapters.append({"title": "Chương 9: Sắc Lệnh Từ C03", "content": ch9_content})
    
    # ------------------ CHAPTER 10 ------------------
    ch1_content = (
        "<p>Một tuần sau cơn địa chấn tài chính chấn động cả nước, Tập đoàn Dược liệu Lâm Gia chính thức tuyên bố phá sản hoàn toàn, cổ phiếu rớt sàn không phanh 30 phiên liên tiếp biến thành đống giấy lộn rác rưởi. Trước tình hình nợ xấu khổng lồ của tập đoàn này tại các ngân hàng lớn, Nguyễn Trịnh Khánh Vy đã đại diện cho Hoàng Cầu Capital và Tập đoàn Dược liệu Ngọc Linh Vương đứng ra mua lại toàn bộ nợ xấu từ Công ty Quản lý Tài sản (VAMC) với mức giá cực rẻ mạt, chính thức thâu tóm hoàn toàn và sáp nhập toàn bộ hệ thống nhà máy, trang trại sâm của Lâm Gia vào Ngọc Linh Vương.</p>"
        "<p>Giờ đây, Lâm Gia Bảo chính thức bước lên cương vị Chủ tịch Hội đồng Quản trị kiêm Tổng Giám đốc của tập đoàn dược liệu Ngọc Linh Vương lớn mạnh nhất Việt Nam, sở hữu độc quyền công nghệ giống sâm F2 đột biến sinh học cùng hơn 50 hecta trang trại sâm tự nhiên chuẩn quốc tế tại Măng Đen. Đứng bên cạnh anh trên bục phát biểu lớn của buổi lễ nhận bàn giao tập đoàn là Nguyễn Trịnh Khánh Vy, diện bộ váy trắng ngọc trai rực rỡ, bàn tay ấm áp của cô đan chặt vào tay anh đầy tình cảm và tự hào trước sự chúc mừng vang dội của hàng trăm đối tác quốc tế.</p>"
        "<p>Ở dưới hàng ghế khán giả cuối cùng, Nguyễn Cát Tường ngồi lặng lẽ trong bộ quần áo sờn cũ rách nát, gương mặt xám ngoét bơ phờ không còn chút sức sống sau khi gia đình cô ta cũng bị phá sản lây do đầu tư vào cổ phiếu Lâm Gia. Cô ta nhìn Bảo tỏa sáng lộng lẫy trên ngai vàng quyền lực bên cạnh ái nữ tài phiệt kiêu sa, lòng tràn trề nỗi uất hận, cay đắng và hối tiếc khôn nguôi. Nếu ngày xưa cô ta không vì chút hư vinh rẻ tiền mà phản bội anh, thì người đứng bên cạnh anh chia sẻ vinh quang nghìn tỷ hôm nay chính là cô ta. Nhưng tất cả cơ hội đã vĩnh viễn khép lại tàn khốc dưới chân kẻ bội bạc.</p>"
        "<p>Chiếc xe limousine sang trọng lăn bánh từ đại sảnh đưa Bảo và Vy trở về Măng Đen sương mù lộng gió, nơi những ngọn đồi thông xanh ngắt đang ôm trọn những trang trại sâm giống Ngọc Linh F2 đang vươn mình đón ánh nắng ban mai rực rỡ. Dòng máu não của cha anh đã lưu thông hoàn hảo, ông cụ đã tỉnh dậy khỏe mạnh hoàn toàn tại bệnh viện Vinmec dưới sự chăm sóc y tế cao cấp nhất. Mọi giông bão giông tố đã đi qua, chỉ còn lại vinh quang tột cùng, tình yêu sắt đá và một đế chế dược liệu Việt Nam kiên cường vươn tầm thế giới!</p>"
    )
    chapters.append({"title": "Chương 10: Quỳ Gối Và Vinh Quang", "content": ch1_content})
    
    # Construct complete dictionary
    novel_data = {
        "title": title,
        "author": author,
        "genre": genre,
        "intro": intro,
        "cover_prompt": cover_prompt,
        "chapters": chapters
    }
    
    # Save to pending_novel.json
    pending_file = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_novel.json"
    with open(pending_file, "w", encoding="utf-8") as f:
        json.dump(novel_data, f, ensure_ascii=False, indent=2)
    print(f"Successfully generated pending_novel.json at {pending_file}!")
    
    # Download the cover using Pollinations AI
    print("Downloading premium cover from Pollinations AI...")
    try:
        # Prompt needs to be URL encoded
        encoded_prompt = requests.utils.quote(cover_prompt)
        url = f"https://image.pollinations.ai/prompt/{encoded_prompt}"
        response = requests.get(url, timeout=60)
        if response.status_code == 200:
            with open("/Users/aaronnguyen/TN/App/doctieuthuyet/pending_cover.png", "wb") as img_f:
                img_f.write(response.content)
            print("Successfully downloaded and saved premium cover to pending_cover.png!")
        else:
            print(f"Failed to download cover from Pollinations AI: status code {response.status_code}")
    except Exception as e:
        print(f"Error downloading cover: {e}")

if __name__ == "__main__":
    main()
