# -*- coding: utf-8 -*-
import json
import os
import urllib.parse
import urllib.request

OUTPUT_FILE = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_novel.json"
COVER_FILE = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_cover.png"

def main():
    print("🚀 Writing Cà Ná Salt Webnovel using Golden V13 standards...")

    novel_data = {
        "title": "Nghệ Nhân Hoa Muối Cà Ná Bị Hủy Hôn Khinh Nghèo, Lật Kèo Phơi Bày Tập Đoàn Muối Bẩn Nghìn Tỷ",
        "author": "Vũ Lâm Hải",
        "genre": "Sảng Văn",
        "intro": "<p><strong>\"Đôi bàn tay sần sùi dính đầy cát muối mặn chát của anh, có rửa sạch ba đời cũng không xứng chạm vào tấm thảm nhung tại biệt thự Phú Mỹ Hưng! Ký đơn từ chức rồi cút khỏi ruộng muối Cà Ná ngay lập tức!\"</strong></p>\n<p>Võ Thanh Hải, một kỹ sư sinh học biển kiêm nghệ nhân làm muối truyền thống tài năng, bỗng dưng bị vị hôn thê kiêu ngạo Lâm Mỹ Hạnh hủy hôn ngay trước ngày cưới, chỉ vì anh kiên quyết bảo vệ ruộng muối di sản thay vì bán đất cho dự án nghỉ dưỡng. Mỹ Hạnh đã phản bội anh, lấy cắp chiếc đĩa cứng chứa toàn bộ công thức và quy trình lọc hoa muối hữu cơ độc bản dâng cho Lê Hữu Đạt, CEO của Tập đoàn Muối Hoàng Gia (Royal Salt Corp).</p>\n<p>Bọn họ không biết rằng, công thức mà chúng ăn cắp thực chất chỉ là một bản nháp có lỗi chí mạng về nồng độ ion kết tinh. Khi liên minh xảo quyệt dùng quyền lực phong tỏa tài khoản Agribank của Hải, đình chỉ ruộng muối 24 giờ để thanh tra khẩn cấp và bôi nhọ anh trên truyền thông bẩn, Hải đã bắt tay cùng Nguyễn Cát Tường - nữ chủ tịch kiêu sa kiêm CEO lý tính tuyệt đối của Quỹ đầu tư Vạn An Capital.</p>\n<p>Bằng sự kết hợp kỳ diệu giữa bài thuốc y học cổ truyền Đông y để giữ mạng tạm thời và các kết quả xét nghiệm lâm sàng Tây y hiện đại của Bệnh viện Trung ương Quân đội 108, cùng báo cáo kiểm toán sở hữu trí tuệ Big 4 của PwC dựa trên nhật ký commit Git gốc bất biến, Võ Thanh Hải đã thực hiện màn lật kèo chấn động. Dưới sắc lệnh đanh thép của cơ quan C03, kẻ phản bội phải trả giá đắt, quỳ gối gục sụp rỉ máu trên nền sàn đá cẩm thạch lạnh lẽo!</p>",
        "cover_prompt": "A highly detailed, professional anime-style webnovel book cover, 1:1 ratio, without any text. A handsome, determined young Vietnamese man with a smart expression stands on a scenic traditional salt field in Cà Ná under brilliant golden sunlight, with shining white salt mounds reflecting the sky. Next to him is an elegant, highly professional Vietnamese woman with long dark hair, wearing a sleek luxury business suit. In the background, beautiful ocean views, clear blue sky, dynamic warm lighting, hyper-realistic, cinematic composition.",
        "chapters": []
    }

    # Chapter 1
    ch1_title = "Chương 1: Ruộng Muối Hoang Sơ Và Lời Hủy Hôn Cay Đắng"
    ch1_content = """<p>Dưới cái nắng như thiêu như đốt của vùng biển Cà Ná, tỉnh Ninh Thuận, những ruộng muối trắng xóa trải dài tít tắp đến tận chân trời, lấp lánh như hàng triệu viên kim cương thô dưới ánh mặt trời rực rỡ. Võ Thanh Hải đứng lặng lẽ bên cạnh bờ mương dẫn nước biển, đôi ủng cao su lấm lem bùn đất sẫm màu, chiếc nón lá bạc màu che khuất nửa khuôn mặt sạm nắng phong trần. Anh khẽ khom lưng, dùng chiếc cào gỗ nhẹ nhàng gạt một lớp tinh thể mỏng manh, xốp mịn nổi bồng bềnh trên mặt nước chạt - đó chính là \"Hoa Muối\" (Fleur de Sel) hữu cơ tinh khiết nhất, loại muối quý hiếm được kết tinh bằng phương pháp thủ công kết hợp công nghệ vi lọc màng sinh học do chính anh nghiên cứu suốt năm năm qua.</p>
<p>Một chiếc xe bán tải Ford Ranger màu đen bóng lộn đột ngột rú ga ầm ĩ, lao thẳng qua con đường đất nhỏ gập ghềnh và phanh gấp ngay sát cạnh ruộng muối của Hải, cuốn lên một làn khói bụi mù mịt. Cửa xe mở ra, Lâm Mỹ Hạnh - vị hôn thê suốt bốn năm qua của Hải - bước xuống. Cô ta mặc một chiếc đầm hiệu màu hồng phấn điệu đà, chân mang giày cao gót nhọn hoắt. Đi bên cạnh cô ta là Lê Hữu Đạt, CEO trẻ tuổi đầy hống hách của Tập đoàn Muối Hoàng Gia, người mặc bộ complet xám tro bóng loáng, khuôn mặt đầy vẻ ngạo nghễ khinh khỉnh.</p>
<p>\"Võ Thanh Hải! Mày có nhìn thấy cái này không?\" Mỹ Hạnh cất giọng chói tai, cô ta tháo chiếc nhẫn đính hôn bằng bạc giản dị ra khỏi ngón tay và ném thẳng xuống vũng nước bùn muối nhơ nhớp ngay dưới chân Hải. \"Đôi bàn tay sần sùi dính đầy cát muối mặn chát của anh, có rửa sạch ba đời cũng không xứng chạm vào tấm thảm nhung tại biệt thự Phú Mỹ Hưng của tôi! Ngày hôm nay tôi đến đây để thông báo hủy hôn. Loại đàn ông nghèo hèn, suốt ngày dầm mưa dãi nắng ngửi mùi muối thối như anh cả đời cũng không ngẩng đầu lên nổi đâu!\"</p>
<p>Thế Hải khẽ dừng tay cào, anh thản nhiên ngẩng đầu nhìn người phụ nữ từng thề non hẹn biển với mình, ánh mắt anh phẳng lặng như nước hồ thu, hoàn toàn không có lấy một chút dao động hay đau đớn nào. Sự bình tĩnh đến đáng sợ của Hải khiến Mỹ Hạnh cảm thấy chột dạ và tức giận.</p>
<p>Lê Hữu Đạt cười khẩy, bước lên khoác vai Mỹ Hạnh, vênh váo nhìn Hải: \"Mày đừng cố tỏ ra thanh cao nữa, Hải ạ. Dự án khu nghỉ dưỡng sinh thái năm sao của tập đoàn tao đã được tỉnh phê duyệt, ruộng muối này của mày sẽ bị cưỡng chế thu hồi vào tuần tới. Thêm nữa, Mỹ Hạnh đã giao lại cho tao chiếc đĩa cứng chứa toàn bộ tài liệu nghiên cứu công nghệ lọc hoa muối hữu cơ loại bỏ hạt vi nhựa của mày rồi. Ngày mai, tập đoàn của tao sẽ chính thức nộp đơn đăng ký bằng sáng chế độc quyền và chuẩn bị cho thương vụ IPO nghìn tỷ trên sàn HoSE!\"</p>
<p>Hải khẽ cúi đầu nhìn chiếc nhẫn bạc đang nằm chìm dưới vũng bùn mặn, khóe miệng anh khẽ nhếch lên thành một nụ cười lạnh lùng, bí ẩn. Anh ngẩng đầu nhìn thẳng vào mắt Lê Hữu Đạt, dõng dạc nói: \"Các người thực sự nghĩ rằng, chỉ cần cướp được dữ liệu đĩa cứng là có thể làm chủ được công nghệ kết tinh hoa muối hữu cơ sao? Công thức trong đĩa cứng đó chỉ là bản nháp thử nghiệm đầu tiên. Nếu không có quy trình điều chỉnh nồng độ ion kết tinh theo nhiệt độ thực tế do tôi nắm giữ, muối kết tinh ra sẽ chứa dư lượng magie sunfat và kim loại nặng cực cao, biến nó thành loại muối bẩn gây ngộ độc và tàn phá thận của người dùng chỉ sau một thời gian ngắn.\"</p>
<p>\"Hừ! Mày chỉ giỏi dọa khỉ!\" Lê Hữu Đạt vênh mặt thách thức. \"Bằng sáng chế sẽ mang tên tao, thương hiệu Muối Tuyết Hoàng Gia sẽ thống trị thị trường xuất khẩu. Còn mày, cứ ôm lấy ruộng muối rác rưởi này mà khóc lóc đi! Chúng ta đi thôi, Hạnh!\"</p>
<p>Lâm Mỹ Hạnh khinh bỉ liếc nhìn Hải một lần cuối rồi khoác tay Lê Hữu Đạt bước lên xe, chiếc Ranger gầm rú ga lao đi, để lại Võ Thanh Hải đứng lặng lẽ giữa ruộng muối trắng xóa mênh mông, ánh mắt anh lóe lên những tia sáng kiên định và sắc bén tựa chim ưng.</p>"""

    # Chapter 2
    ch2_title = "Chương 2: Màn Sỉ Nhục Tại Showroom Và Tài Khoản Bị Phong Tỏa"
    ch2_content = """<p>Hai ngày sau sự kiện hủy hôn tại ruộng muối Cà Ná, Võ Thanh Hải bắt xe đò ra Hà Nội. Anh cầm theo một tập hồ sơ pháp lý dày dặn, tìm đến showroom trung tâm năm sao vô cùng tráng lệ của Tập đoàn Muối Hoàng Gia tọa lạc ngay trên con phố Tràng Tiền sầm uất. Showroom được thiết kế vô cùng sang trọng với kính cường lực sáng loáng, những kệ trưng bày bằng gỗ gõ đỏ đắt tiền trưng bày các mẫu muối tinh luyện xuất khẩu. Hôm nay chính là buổi họp báo công bố thương hiệu \"Muối Tuyết Hoàng Gia\" và dòng sản phẩm chăm sóc sức khỏe cao cấp của tập đoàn chuẩn bị cho đợt gọi vốn nghìn tỷ.</p>
<p>Hải bước vào sảnh lớn trong bộ trang phục giản dị: chiếc quần tây cũ và chiếc áo sơ mi màu xanh rêu sờn vai. Sự xuất hiện của anh ngay lập tức thu hút ánh nhìn khinh khỉnh của nhân viên bảo vệ và đám khách mời sang trọng. Khi anh vừa tiến gần đến bàn trưng bày sản phẩm để gửi văn bản cảnh báo vi phạm sở hữu trí tuệ, Lê Hữu Đạt và Lâm Mỹ Hạnh từ trong phòng VIP bước ra.</p>
<p>\"Ơ kìa! Ai như gã kỹ sư ruộng muối nghèo hèn Võ Thanh Hải đây mà?\" Giọng nói hách dịch của Lê Hữu Đạt vang lên chói tai giữa showroom, thu hút toàn bộ ống kính của đám phóng viên báo chí đang tác nghiệp. \"Mày vác cái thân hình bẩn thỉu đầy mùi muối biển đến đây để xin ăn à? Hay định ăn vạ để đòi tiền bồi thường đất ruộng muối?\"</p>
<p>Lâm Mỹ Hạnh đứng bên cạnh gã khịt mũi đầy khinh bỉ, cô ta lớn tiếng chỉ trỏ trước đám đông phóng viên: \"Mọi người nhìn xem, đây chính là kẻ bám váy tôi suốt bốn năm qua, không chịu làm ăn đàng hoàng mà chỉ biết ôm ruộng muối rách nát để cản bước tiến của gia đình tôi! Hôm nay hắn lại dám đến đây để quấy rối sự kiện lớn của tập đoàn Hoàng Gia!\"</p>
<p>Võ Thanh Hải vẫn đứng phẳng lặng như tờ, anh từ tốn rút văn bản cảnh báo pháp lý đặt lên bàn trưng bày: \"Tôi đến đây để gửi cảnh báo chính thức. Sản phẩm Muối Tuyết Hoàng Gia của các người đang sử dụng trái phép công nghệ vi lọc màng sinh học được đăng ký bảo hộ độc quyền của tôi. Nếu các người cố tình đưa sản phẩm bào chế lỗi này ra thị trường, hậu quả sẽ cực kỳ nghiêm trọng trước pháp luật.\"</p>
<p>Lê Hữu Đạt cười lớn đầy ngạo mạn, gã cầm tập văn bản của Hải lên, xé đôi ngay trước ống kính máy ảnh và ném những mảnh giấy vụn vào mặt anh. \"Bản quyền? Mày lấy tư cách gì nói chuyện bản quyền với tao? Tao đã nộp đơn đăng ký bảo hộ sáng chế cấp tốc lên Cục Sở hữu Trí tuệ sáng nay rồi! Chưa hết, tài khoản Agribank chứa 200 triệu đồng tiền tiết kiệm của mày đã bị đóng băng tạm thời theo đơn yêu cầu điều tra hành vi chiếm đoạt công quỹ dự án của Viện Nghiên cứu Thủy sản do chính tao ký đơn tố cáo!\"</p>
<p>Điện thoại của Hải bất chợt rung lên, một tin nhắn từ Agribank thông báo tài khoản cá nhân của anh tạm thời bị phong tỏa hoàn toàn. Cùng lúc đó, Lê Hữu Đạt ghé sát tai Hải, thì thầm tàn nhẫn: \"Ở cái đất Hà Nội này, tiền bạc và quyền lực của Hoàng gia là tuyệt đối. Mày không có một xu dính túi, ruộng muối Cà Ná thì bị đình chỉ hoạt động 24 giờ để thanh tra môi trường, mày lấy gì để đấu với tao? Bảo vệ! Ném thằng ăn mày này ra ngoài đường cho tôi!\"</p>
<p>Hai gã bảo vệ to khỏe lập tức lao tới, thô bạo đẩy Hải ra khỏi showroom sang trọng dưới những tiếng cười nhạo cợt của Lâm Mỹ Hạnh và đám phóng viên bẩn. Hải đứng dưới cơn mưa phùn lạnh giá của Hà Nội, sắc mặt anh vẫn điềm nhiên phẳng lặng, anh từ từ lau sạch những mảnh giấy vụn dính trên vai áo, ánh mắt anh phẳng lặng nhìn vào sảnh showroom lộng lẫy, chứa đựng một uy lực sắc bén vô hình.</p>"""

    # Chapter 3
    ch3_title = "Chương 3: Mỹ Nhân Hào Môn Xuất Hiện Và Hợp Đồng Thẩm Định PwC"
    ch3_content = """<p>Sau khi bị trục xuất khỏi showroom của tập đoàn Hoàng Gia, Võ Thanh Hải không hề hoảng loạn. Anh dọn về một căn phòng trọ nhỏ nằm sâu trong con ngõ chợ ở quận Đống Đa, tự mình thiết lập lại hệ thống máy chủ Git cá nhân bảo mật cao trên chiếc laptop ThinkPad cũ kỹ. Anh biết rằng, muốn đè bẹp một đế chế nghìn tỷ kiêu ngạo, cần phải có một liên minh đủ mạnh và một đòn đánh pháp lý sắc bén tuyệt đối.</p>
<p>Vào một buổi sáng nắng hanh vàng của mùa đông Hà Nội, một chiếc xe siêu sang Mercedes-Maybach màu đen bóng đỗ ngay trước đầu ngõ nhỏ. Sự xuất hiện của chiếc xe xa xỉ khiến cả khu phố nghèo xôn xao. Từ hàng ghế sau, một cô gái bước xuống, ngay lập tức khiến toàn bộ không gian xung quanh như bừng sáng bởi phong thái kiêu sa, quý phái của mình.</p>
<p>Đó là Nguyễn Cát Tường - đại tiểu thư kiêm CEO quyền lực của Quỹ đầu tư Vạn An Capital. Cô mặc một bộ âu phục công sở màu xanh navy cắt may tinh xảo ôm sát thân hình mảnh mai quyến rũ, mái tóc đen dài gợn sóng xõa nhẹ trên bờ vai thon. Gương mặt cô mang một vẻ đẹp sắc sảo, lạnh lùng và cực kỳ lý tính. Đi theo sau cô là một đoàn chuyên gia pháp lý sở hữu trí tuệ cùng hai kiểm toán viên cao cấp mặc đồng phục lịch sự của PwC - một trong bốn công ty kiểm toán lớn nhất thế giới (Big 4).</p>
<p>Cát Tường bước vào căn phòng trọ chật hẹp của Hải, đôi mắt phượng sắc sảo nhanh chóng quét qua không gian mộc mạc ngập tràn mùi giấy tờ nghiên cứu và các lọ muối mẫu thí nghiệm. Cô không hề tỏ ra ghét bỏ hay ái ngại, cô bước thẳng tới chiếc bàn gỗ cũ kỹ nơi Hải đang ngồi làm việc.</p>
<p>\"Chào kỹ sư Võ Thanh Hải.\" Giọng nói của Cát Tường thanh mảnh, rõ ràng và toát lên phong thái của một nhà lãnh đạo lý tính tuyệt đối. \"Tôi là Nguyễn Cát Tường, CEO của Vạn An Capital. Tôi không đến đây để gửi lời chia buồn sáo rỗng về việc anh bị hủy hôn hay bị phong tỏa tài khoản. Tôi đến để đề xuất một thương vụ đầu tư sòng phẳng trị giá 100 tỷ đồng.\"</p>
<p>Hải khẽ ngẩng đầu nhìn cô, ánh mắt anh phẳng lặng như nước hồ thu. \"Đề xuất đầu tư vào một kẻ bị đóng băng tài khoản và bị tước giấy phép hoạt động như tôi sao? Cô Nguyễn không sợ mất trắng số tiền đó à?\"</p>
<p>Cát Tường khẽ mỉm cười, một nụ cười nhạt nhưng cực kỳ tự tin. \"Tôi đã âm thầm theo dõi công trình nghiên cứu hoa muối hữu cơ loại bỏ vi nhựa của anh suốt ba năm qua qua các bài báo khoa học quốc tế. Ông ngoại tôi - Tỷ phú Nguyễn Văn Thăng, chủ tịch tập đoàn Thăng Long - hiện đang bị chứng xơ vữa động mạch não và suy thận mãn tính nghiêm trọng, chế độ ăn bắt buộc phải dùng loại muối hữu cơ cực kỳ tinh khiết có nồng độ natri thấp và không chứa tạp chất hóa học. Nghiên cứu của anh chính là chìa khóa duy nhất để cứu sống ông.\"</p>
<p>Cô khẽ ra hiệu, vị kiểm toán viên PwC bước lên, đặt lên bàn một tập hồ sơ dày cộp đóng dấu bảo mật. \"Chúng tôi không làm việc dựa trên niềm tin hay lòng thương hại. Đây là báo cáo thẩm định năng lực pháp lý và đánh giá tiềm năng thị trường của dòng hoạt chất hoa muối hữu cơ do PwC thực hiện trong hai tuần qua. Chúng tôi cam kết rót vốn 100 tỷ đồng để thành lập công ty Đông dược sinh học mới, phát triển sản phẩm muối đặc trị đạt chuẩn quốc tế. Anh sẽ nắm giữ 70% cổ phần sáng chế độc quyền, chúng tôi nắm giữ 30% cổ phần vận hành thương mại.\"</p>
<p>Hải nhìn tập hồ sơ dày cộp trên bàn. Sự chuyên nghiệp, rõ ràng và thái độ sòng phẳng của Cát Tường khiến anh thực sự ấn tượng. Cô không giống như những kẻ hào môn kiêu ngạo khác, cô tôn trọng trí tuệ và giá trị chất xám của anh một cách tuyệt đối. Anh khẽ gõ bàn phím ThinkPad, mở ra giao diện Git commit logs gốc để PwC tiến hành đối chiếu kỹ thuật.</p>"""

    # Chapter 4
    ch4_title = "Chương 4: Phân Đoạn Tâm Sự Riêng Tư Bên Tách Trà Chiều"
    ch4_content = """<p>Trong căn phòng trọ nhỏ yên tĩnh, tiếng gõ phím lạch cạch của các chuyên gia PwC dần thưa thớt rồi dừng hẳn khi họ hoàn tất việc xác minh tính toàn vẹn của dữ liệu Git gốc. Võ Thanh Hải đứng dậy, pha một ấm trà Shan Tuyết cổ thụ đỉnh Suối Giàng ấm áp. Làn khói trà nghi ngút mang theo hương thơm thanh khiết, xua tan đi cái lạnh giá của mùa đông Hà Nội đang bao trùm ngoài ô cửa kính nhỏ.</p>
<p>Nguyễn Cát Tường nhận tách trà từ tay Hải, đôi bàn tay thon thả mềm mại của cô khẽ chạm nhẹ vào ngón tay chai sần đầy những vết sẹo do nắng gió biển khơi của anh. Một cảm giác ấm áp lạ lùng khẽ lan tỏa giữa hai người. Cát Tường nhẹ nhàng nhấp một ngụm trà nóng, đôi mắt phượng sắc sảo thường ngày của vị nữ CEO lý tính bỗng chốc trở nên dịu dàng, xao động khi cô nhìn sâu vào khuôn mặt điềm tĩnh, cương nghị của người đàn ông trước mặt.</p>
<p>\"Anh thực sự là một người đàn ông thú vị, Thanh Hải.\" Cát Tường khẽ cất tiếng, giọng nói trầm ấm và chân thành, trút bỏ đi vẻ lạnh lùng sắc sảo thường ngày. \"Thông thường, những người bị dồn vào chân tường, bị đóng băng tài khoản và bị bôi nhọ danh dự như anh sẽ hoảng loạn hoặc tìm cách trả thù điên cuồng. Nhưng anh lại cực kỳ điềm tĩnh, giống như mọi thứ đã nằm trong tầm kiểm soát của anh vậy.\"</p>
<p>Hải nhấp một ngụm trà đắng, ánh mắt anh nhìn ra xa xăm qua ô cửa kính nhỏ hướng về phía những mái ngói rêu phong cổ kính của Hà Nội. \"Khi cô đã trải qua những ngày tháng dầm sương dãi nắng trên những ruộng muối Cà Ná, đối mặt với những cơn giông bão đổ ập xuống vách đá trong gang tấc, cô sẽ hiểu rằng lòng tham và sự phản bội của lòng người chỉ là những cơn gió thoảng qua. Nghề làm muối là để mang lại vị mặn tinh khiết cho đời, chứ không phải để tranh giành danh lợi bẩn thỉu. Tôi kiên trì bảo vệ công nghệ lọc hoa muối hữu cơ này không phải vì tiền bạc, mà vì tôi không muốn dòng muối tinh khiết cứu mạng hàng vạn người bị biến thành công cụ trục lợi giả dối của những kẻ gian thương.\"</p>
<p>Cát Tường im lặng lắng nghe, cô khẽ cúi đầu nhìn làn nước trà vàng óng ánh. Trái tim cô, vốn dĩ đã bị chai sạn và lạnh giá sau nhiều năm đấu trí trên thương trường khốc liệt của giới tài phiệt, đột nhiên có một nhịp đập lạ lùng trước sự kiên định, y đức sáng ngời và bản lĩnh phi thường của Hải. Cô khẽ đặt tách trà xuống bàn, tiến lại gần anh, giọng nói cô trở nên dịu dàng ấm áp lạ thường:</p>
<p>\"Tôi cam kết với anh, Vạn An Capital sẽ đứng bên cạnh anh đến cùng trong cuộc chiến này. Bất kể Lê Hữu Đạt hay tập đoàn Hoàng Gia có dùng thủ đoạn dơ bẩn gì, tôi cũng sẽ dùng toàn bộ tiềm lực tài chính và pháp lý của gia tộc để bảo vệ anh. Đây không chỉ là một thương vụ đầu tư sòng phẳng, mà còn là lời hứa đồng hành sắt đá của tôi dành cho anh.\"</p>
<p>Cái chạm tay nhẹ nhàng giữa hai người giữa buổi chiều sương lạnh Hà Nội tuy ngắn ngủi nhưng cực kỳ ấm áp, đánh dấu một liên minh thép không thể phá vỡ giữa mỹ nhân hào môn lý tính và vị nghệ nhân muối ẩn dật kiệt xuất.</p>"""

    # Chapter 5
    ch5_title = "Chương 5: Bế Tắc Giữa Dòng: Đòn Độc Của Liên Minh Phản Diện"
    ch5_content = """<p>Liên minh bẩn thỉu giữa Lê Hữu Đạt và Lâm Mỹ Hạnh nhanh chóng phát hiện ra sự hợp tác ngầm giữa Quỹ đầu tư Vạn An Capital và Võ Thanh Hải. Nhận thấy nguy cơ sụp đổ của dự án IPO nghìn tỷ \"Muối Tuyết Hoàng Gia\" nếu Hải lật ngược thế cờ sở hữu trí tuệ, bọn chúng quyết định tung ra những đòn hiểm độc nhất hòng triệt hạ anh hoàn toàn trước khi Hội nghị Thực phẩm và Sức khỏe Quốc tế diễn ra.</p>
<p>Vào một buổi sáng sớm, khi Hải vừa mở cửa xưởng sản xuất thực nghiệm nhỏ của mình ở Hà Nội, một đoàn thanh tra liên ngành gồm đại diện Sở Y tế và Quản lý thị trường địa phương bất ngờ ập vào. Kẻ dẫn đầu là một cán bộ biến chất đã nhận hối lộ lớn từ Lê Hữu Đạt.</p>
<p>\"Nhận được đơn tố cáo xưởng sản xuất của Võ Thanh Hải hoạt động không phép, tàng trữ muối bẩn nhiễm tạp chất thạch tín và bán chất độc hại gây suy thận cấp cho bệnh nhân.\" Gã cán bộ lạnh lùng công bố văn bản đóng dấu đỏ. \"Theo quy định pháp luật, chúng tôi ra lệnh đình chỉ hoạt động xưởng trong vòng 24 giờ để tiến hành niêm phong, tịch thu toàn bộ nguyên liệu mẫu thí nghiệm để thanh tra khẩn cấp.\"</p>
<p>Cùng lúc đó, trên các trang mạng xã hội và các diễn đàn tin tức lớn rộ lên hàng loạt bài viết bôi nhọ Võ Thanh Hải rầm rộ. Lê Hữu Đạt đã chi hàng tỷ đồng để thuê các KOLs lớn thực hiện các buổi livestream rêu rao rằng dòng hoa muối hữu cơ của Hải thực chất là muối bẩn chưa qua xử lý, chứa dư lượng magie sunfat độc hại cực cao. Sự hoang mang bao trùm dư luận, các đối tác cung cấp bao bì và nguồn muối thô ban đầu của Hải hoảng sợ, vội vã đơn phương hủy bỏ hợp đồng để tránh bị vạ lây.</p>
<p>Nỗi nhục và bế tắc dồn dập ập đến. Tài khoản ngân hàng Agribank của Hải tiếp tục bị đóng băng hoàn toàn, xưởng bị niêm phong bằng băng keo vàng lạnh lẽo, người dân xung quanh nhìn anh bằng ánh mắt ái ngại, xa lánh. Anh lâm vào thế đơn độc, không tiền bạc, không nhà xưởng, danh dự bị chà đạp tàn nhẫn dưới chân bùn lầy.</p>
<p>Lâm Mỹ Hạnh đi cùng Lê Hữu Đạt đến trước cửa xưởng bị niêm phong, cô ta cười lớn đầy thỏa mãn: \"Võ Thanh Hải ơi là Võ Thanh Hải! Mày thấy chưa? Đứng đối đầu với tập đoàn Hoàng Gia thì kết cục của mày chỉ có thể là tan xương nát thịt thôi! Bây giờ đến cái xưởng rách nát này cũng bị niêm phong rồi, mày chuẩn bị vào tù bóc lịch vì tội bán muối độc đi nhé!\"</p>
<p>Hải đứng lặng yên trước tấm biển niêm phong màu đỏ chói. Mồ hôi không chảy trên trán anh, sắc mặt anh vẫn điềm nhiên phẳng lặng như tờ, chỉ có đôi bàn tay khẽ đút vào túi quần, mười đầu ngón tay hơi siết chặt lại. Anh không hề nói một lời tranh cãi nào với hai kẻ phản diện đang vênh váo trước mặt.</p>
<p>Bởi vì anh biết, Nguyễn Cát Tường đã hoàn tất việc chuyển giao 100 tỷ đồng vốn đầu tư của Vạn An Capital thông qua một tài khoản ủy thác bảo mật tại ngân hàng Vietcombank đứng tên công ty Đông dược sinh học mới thành lập, hoàn toàn nằm ngoài tầm kiểm soát của Lê Hữu Đạt. Đoàn luật sư của cô cũng đang âm thầm hoàn thiện các thủ tục pháp lý để phản kích.</p>
<p>\"Cứ để chúng đắc ý thêm vài ngày nữa.\" Hải quay sang nói khẽ với Nguyễn Cát Tường, người vừa bước đến đứng bên cạnh anh dưới cơn mưa phùn lạnh giá. \"Đỉnh cao của sự kiêu ngạo chính là bắt đầu của sự sụp đổ. Hội nghị Thực phẩm và Sức khỏe Quốc tế sắp tới sẽ là nơi bọn chúng phải trả giá đắt nhất.\"</p>"""

    # Chapter 6
    ch6_title = "Chương 6: Đêm Hội Chợ Quốc Tế Và Bài Thuyết Trình Muối Bẩn"
    ch6_content = """<p>Trung tâm Hội nghị Quốc gia Hà Nội vào ngày diễn ra Hội nghị Thực phẩm và Sức khỏe Quốc tế vô cùng hoành tráng và lộng lẫy. Hàng ngàn chuyên gia dinh dưỡng, các giáo sư y học đầu ngành cùng giới tinh anh tài chính và phóng viên báo chí trong và ngoài nước đổ về nườm nượp. Ánh đèn flash của máy ảnh chớp liên tục, không khí náo nhiệt bao trùm cả hội trường lớn.</p>
<p>Lê Hữu Đạt và Lâm Mỹ Hạnh mặc những bộ comple lịch lãm đắt tiền đứng ở vị trí trung tâm sảnh chính, vênh váo đón nhận những lời chúc tụng từ các đối tác lớn. Bọn chúng chuẩn bị công bố dòng sản phẩm \"Muối Tuyết Hoàng Gia\" với sự quảng bá rầm rộ là dòng muối ăn cao cấp đột phá tốt cho sức khỏe tim mạch.</p>
<p>Thế nhưng, đằng sau lớp vỏ bọc hào nhoáng đó là một thực tế tàn nhẫn: vì tiết kiệm chi phí sản xuất để tối đa hóa lợi nhuận chuẩn bị cho đợt IPO nghìn tỷ, Lê Hữu Đạt đã lược bỏ đi quy trình lọc tinh chất phân tử phức tạp của Hải, thay thế bằng muối công nghiệp thô tẩy trắng bằng hóa chất clo cực độc và bỏ qua các màng lọc vi nhựa. Dòng sản phẩm của hắn thực chất là một sản phẩm chứa dư lượng magie sunfat và kim loại nặng chì vượt ngưỡng cho phép gấp nhiều lần.</p>
<p>Khi Võ Thanh Hải trong bộ trang phục giản dị bước vào hàng ghế cuối của hội trường lớn, Lê Hữu Đạt ngay lập tức nhìn thấy anh. Hắn vênh mặt, lớn tiếng châm chọc ngay trước ống kính của hàng chục phóng viên báo chí:</p>
<p>\"Mọi người nhìn xem, đây chẳng phải là Võ Thanh Hải, gã kỹ sư bị đóng băng tài khoản vì hành vi gian lận của Viện Nghiên cứu chúng tôi sao? Hôm nay cậu cũng dám vác mặt đến đây để học hỏi nghiên cứu đỉnh cao của tôi à? Một kẻ dầm mưa dãi nắng bị niêm phong nhà xưởng như cậu, có lẽ cả đời này chỉ xứng đáng đứng ở góc tối nhìn chúng tôi bước lên đỉnh cao vinh quang thôi!\"</p>
<p>Lâm Mỹ Hạnh đứng bên cạnh Lê Hữu Đạt khẽ cười khẩy đầy kiêu ngạo, ánh mắt cô ta nhìn Hải tràn ngập sự khinh miệt và đắc ý tột đỉnh. Lê Hữu Đạt ghé sát tai Hải, thì thầm bằng chất giọng tàn nhẫn đầy đe dọa: \"Hôm nay sau khi thương hiệu Muối Tuyết Hoàng Gia được công bố, tao sẽ dùng quyền lực của Hoàng gia để tống mày vào tù vĩnh viễn vì tội bôi nhọ và bán muối độc. Mày không còn đường sống ở đất Hà Nội này đâu!\"</p>
<p>Hải vẫn đứng im lặng, sắc mặt anh phẳng lặng như tờ, không hề có một chút lo lắng hay sợ hãi nào lộ ra ngoài. Anh thản nhiên bước về hàng ghế cuối, lặng lẽ nhìn Lê Hữu Đạt bước lên sân khấu lớn bắt đầu bài thuyết trình giới thiệu sản phẩm giả mạo.</p>
<p>Khi Lê Hữu Đạt đang thao thao bất tuyệt trên sân khấu về \"sự kỳ diệu\" của sản phẩm Muối Tuyết Hoàng Gia trước những tràng pháo tay giòn giã của cả hội trường, Nguyễn Cát Tường trong chiếc đầm dạ hội màu đen quyến rũ từ từ bước vào, ngồi xuống chiếc ghế trống ngay bên cạnh Hải. Cô khẽ mỉm cười, đưa cho anh chiếc USB chứa toàn bộ dữ liệu kiểm toán độc lập của PwC và lịch sử Git commit đã được chứng thực.</p>
<p>\"Kịch hay sắp bắt đầu rồi, Thanh Hải.\" Cát Tường thì thầm, ánh mắt cô lạnh lùng hướng lên sân khấu lớn.</p>"""

    # Chapter 7
    ch7_title = "Chương 7: Sinh Tử 15 Phút: Màn Châm Cứu Giữ Mạng Chấn Động"
    ch7_content = """<p>Giữa lúc không khí Hội nghị Thực phẩm và Sức khỏe Quốc tế đang đạt đến đỉnh điểm của sự náo nhiệt sau bài thuyết trình của Lê Hữu Đạt, đột nhiên một sự cố kinh hoàng xảy ra ngay tại hàng ghế VIP dành cho các nhà tài trợ danh dự.</p>
<p>Tỷ phú Nguyễn Văn Thăng - ông ngoại của Nguyễn Cát Tường, người sáng lập tập đoàn tài chính Thăng Long hùng mạnh - đột ngột ngã gục xuống bàn. Sắc mặt ông cụ lập tức xám ngoét không còn một giọt máu, mồ hôi lạnh vã ra như tắm ướt sũng chiếc áo sơ mi lụa đắt tiền, miệng sủi bọt mép màu trắng đục, hai hàm răng nghiến chặt vào nhau phát ra những tiếng kêu kèn kẹt ghê người. Cơ thể ông cụ co giật liên hồi, nhịp thở đứt quãng vô cùng yếu ớt. Đây là triệu chứng của một cơn đột quỵ và suy thận cấp tính do biến chứng tăng huyết áp kịch phát vô cùng nguy kịch, đe dọa tính mạng chỉ trong vài phút ngắn ngủi.</p>
<p>\"Bác sĩ! Mau gọi bác sĩ cấp cứu!\" Nguyễn Cát Tường hét lên trong sự hoảng loạn tột độ, cô vội vàng chạy lại ôm lấy cơ thể đang co giật của ông ngoại.</p>
<p>Lê Hữu Đạt nhìn thấy cơ hội vàng để lập công lớn ngay trước hàng trăm phóng viên báo chí và giới tài phiệt. Hắn vội vàng chạy xuống sân khấu, tay cầm một lọ tinh chất \"Muối Tuyết Hoàng Gia\" chứa nồng độ khoáng chất cao mà hắn vừa mới thuyết trình.</p>
<p>\"Mọi người tránh ra! Tôi là CEO Lê Hữu Đạt!\" Hắn tự tin hét lớn. \"Dòng muối tuyết này chứa chiết xuất natri thấp cực mạnh, có khả năng điều hòa huyết áp ngay lập tức để cứu mạng cụ Thăng!\"</p>
<p>Bất chấp sự ngăn cản của một số bác sĩ Tây y có mặt tại hội trường, Lê Hữu Đạt vội vã đổ dung dịch muối hòa tan vào miệng tỷ phú Nguyễn Văn Thăng và ép ông cụ uống. Hắn vênh mặt tự đắc, nghĩ rằng chỉ cần cứu sống tỷ phú ngay tại đây, gã sẽ trở thành anh hùng y học và thương vụ IPO nghìn tỷ sẽ thành công vang dội.</p>
<p>Thế nhưng, chỉ đúng ba phút sau khi uống dung dịch muối chứa đầy hóa chất tẩy trắng clo và dư lượng magie sunfat độc hại của Đạt, một cảnh tượng kinh hoàng đã xảy ra khiến toàn bộ hội trường hét lên kinh hãi.</p>
<p>Cơ thể tỷ phú Thăng đột ngột co giật mạnh hơn gấp bội, hai mắt trợn ngược lộ rõ lòng trắng, máu tươi đỏ thẫm bất ngờ trào ra từ khóe miệng và hai lỗ mũi của ông cụ. Máy đo nhịp tim cầm tay của bác sĩ riêng lập tức phát ra những tiếng bíp bíp liên hồi báo động đỏ: Nhịp tim từ 75 tụt dốc kinh hoàng xuống còn 30 nhịp/phút, huyết áp sụt nghiêm trọng xuống mức chạm đáy 50/30 mmHg, đồng tử hai bên giãn nở to ra hoàn toàn không còn phản xạ với ánh sáng. Cụ Thăng đã rơi vào trạng thái chết lâm sàng do huyết áp tụt dốc và suy thận bùng phát dữ dội.</p>
<p>\"Đạt! Mày đã cho ông ngoại tao uống cái gì thế này?\" Nguyễn Cát Tường hét lên trong nước mắt phẫn nộ. Cô túm chặt lấy cổ áo Lê Hữu Đạt gầm lên.</p>
<p>Lê Hữu Đạt lúc này sắc mặt hoàn toàn xám ngoét không còn một giọt máu, mồ hôi lạnh chảy ròng ròng ướt sũng cả trán, đầu gối bủn rủn hoàn toàn không còn chút lực nào quỵ sụp xuống sàn gạch men lạnh lẽo. Hắn lắp bắp trong sự sợ hãi tột cùng: \"Không... không thể nào... Công thức rõ ràng là giống hệt... Sao lại có phản ứng nguy kịch như thế này được chứ...\"</p>
<p>\"Tránh ra!\"</p>
<p>Một giọng nói đanh thép, lạnh lùng như băng vang lên rẽ đôi đám đông đang hoảng loạn. Võ Thanh Hải sải bước tiến tới, phong thái điềm tĩnh và uy nghiêm của anh lập tức khiến mọi người tự động dạt ra hai bên. Anh quỳ một gối xuống bên cạnh tỷ phú Thăng, mười ngón tay cử động nhanh như chớp rút ra bộ kim châm cứu gia truyền.</p>
<p>\"Mày định làm gì? Ông cụ đã chết lâm sàng rồi, mày định giết người để đổ tội cho tao à?\" Lê Hữu Đạt hét lên trong sự hoảng loạn, gã cố tình lao vào ngăn cản Hải.</p>
<p>Hải không thèm nhìn gã, anh dùng cùi chỏ huých mạnh một phát cực hiểm vào chấn thủy Lê Hữu Đạt, khiến gã CEO đau đớn ngã nhào ra đất, sắc mặt xám ngoét vì nghẹt thở. Hải lập tức châm sâu ba cây kim châm cứu vào ba huyệt vị chí mạng trên đỉnh đầu và cổ tay tỷ phú Thăng: huyệt Nhân Trung, huyệt Bách Hội và huyệt Nội Quan. Mười ngón tay anh vê kim cực nhanh, truyền dòng sinh khí ấm áp cô lập độc tố trong não cụ Thăng. Đồng thời, anh rút từ trong túi áo ra một lọ nước dung dịch \"Hoa Muối Hữu Cơ\" thật được kết tinh thủ công tinh khiết nhất của mình, nhẹ nhàng nhỏ từng giọt tinh chất quý giá vào khóe miệng tỷ phú.</p>
<p>\"Thanh Hải... cứu ông ngoại tôi với...\" Nguyễn Cát Tường nắm chặt lấy tay anh khóc nghẹn.</p>
<p>\"Hãy tin tôi.\" Hải khẽ đáp, ánh mắt anh kiên định tuyệt đối. \"Tôi sẽ giữ mạng ông ngoại cô trong đúng 15 phút. Hãy lập tức chuẩn bị xe cấp cứu chuyển thẳng sang Bệnh viện Trung ương Quân đội 108!\"</p>
<p>Ngay sau khi những giọt dung dịch hoa muối của Hải thấm vào lưỡi, máy đo nhịp tim bất ngờ phát ra tiếng bíp đều đặn trở lại: Nhịp tim từ 30 từ từ tăng lên và ổn định ở mức 65 nhịp/phút, huyết áp phục hồi thần kỳ về mức 110/70 mmHg, máu tươi ngừng chảy từ khóe mũi, đồng tử bắt đầu co lại và nhịp thở của tỷ phú Thăng dần trở nên sâu và đều đặn. Màn châm cứu kết hợp hoa muối giữ mạng chấn động Đông y của Hải đã cứu sống tỷ phú Nguyễn Văn Thăng khỏi bàn tay tử thần ngay trong gang tấc trước sự ngỡ ngàng tột độ của hàng ngàn chuyên gia y học có mặt tại hội trường.</p>"""

    # Chapter 8
    ch8_title = "Chương 8: Xét Nghiệm Tây Y: Kết Quả Lâm Sàng Kỳ Diệu"
    ch8_content = """<p>Chiếc xe cấp cứu hú còi inh ỏi xé toang màn sương mù dày đặc của Hà Nội, đưa tỷ phú Nguyễn Văn Thăng chuyển thẳng vào phòng mổ khân cấp của Bệnh viện Trung ương Quân đội 108. Nguyễn Cát Tường và Võ Thanh Hải túc trực ngay bên ngoài hành lang phòng mổ, không khí vô cùng căng thẳng bao trùm. Lê Hữu Đạt và Lâm Mỹ Hạnh cùng đám trợ lý cũng vội vã bám theo sau, khuôn mặt bọn chúng xám ngoét không còn một giọt máu vì sợ hãi trách nhiệm pháp lý nếu tỷ phú có mệnh hệ gì.</p>
<p>Sau hai giờ đồng hồ căng thẳng nghẹt thở, cánh cửa phòng mổ lớn từ từ mở ra. Giáo sư Trần Minh Đức - trưởng khoa phẫu thuật thần kinh hàng đầu Việt Nam, người trực tiếp chỉ đạo kíp mổ - bước ra ngoài với khuôn mặt tràn đầy sự kinh ngạc và thán phục khó tin.</p>
<p>\"Ai... ai là người đã thực hiện sơ cứu châm cứu và cho bệnh nhân dùng dung dịch hoa muối hữu cơ trước khi nhập viện?\" Giáo sư Đức lớn tiếng hỏi, giọng ông run lên vì xúc động.</p>
<p>Nguyễn Cát Tường vội vàng bước lên: \"Thưa Giáo sư, là anh Võ Thanh Hải đây ạ. Ông ngoại cháu hiện tại thế nào rồi ạ?\"</p>
<p>Giáo sư Đức lập tức bước tới nắm chặt lấy hai vai Hải, đôi mắt ông rực sáng: \"Cậu Hải! Cậu thực sự là một thiên tài Đông y! Chúng tôi vừa tiến hành chụp CT cản quang và làm các xét nghiệm sinh hóa máu chi tiết cho cụ Thăng. Kết quả lâm sàng Tây y hiển thị trên màn hình khiến toàn bộ kíp mổ của chúng tôi phải kinh ngạc rúng động!\"</p>
<p>Ông quay sang chỉ tay vào tấm phim chụp CT: \"Mọi người nhìn xem! Vùng tổn thương thận và mạch máu não diện rộng của bệnh nhân hoàn toàn không hề lan rộng ra các nhu mô lành lặn xung quanh. Thay vào đó, nồng độ natri cực thấp và các hoạt chất vi lượng tự nhiên trong dung dịch Hoa Muối Hữu Cơ của cậu Hải đã tạo nên một áp suất thẩm thấu hoàn hảo, cô lập toàn bộ độc tố hóa học từ loại muối bẩn Hoàng Gia, giúp bảo vệ tối đa tế bào thận và tim mạch của cụ Thăng khỏi cơn suy cấp tính.\"</p>
<p>Giáo sư Đức hít một hơi sâu đầy thán phục: \"Nhờ sự hỗ trợ châm cứu chặn đứng áp lực nội sọ và dòng dung dịch hoa muối hữu cơ tinh khiết này, cụ Thăng hoàn toàn thoát khỏi nguy cơ tử vong lâm sàng và chúng tôi không cần thực hiện cuộc phẫu thuật xâm lấn đầy rủi ro nữa! Ông cụ chỉ cần điều trị nội khoa Tây y kết hợp phục hồi chức năng trong một tuần là có thể xuất viện hoàn toàn khỏe mạnh! Đây thực sự là một điều kỳ diệu của Đông - Tây y kết hợp biện chứng mà cả đời làm y khoa tôi chưa từng được chứng kiến!\"</p>
<p>Nghe đến đây, Nguyễn Cát Tường òa khóc nức nở vì hạnh phúc, cô không ngần ngại lao thẳng vào lòng Hải, ôm chặt lấy anh trước sự chứng kiến của mọi người. Hải nhẹ nhàng vỗ nhẹ lên vai cô, ánh mắt anh ngập tràn sự dịu dàng và ấm áp.</p>
<p>Trong khi đó, ở góc hành lang, Lê Hữu Đạt đầu gối hoàn toàn bủn rủn không còn chút lực nào, quỵ sụp xuống sàn gạch lạnh lẽo của bệnh viện. Mồ hôi lạnh chảy ròng ròng ướt sũng cả bộ complet đắt tiền, khuôn mặt hắn xám ngoét không còn một giọt máu, mười đầu ngón tay bấu chặt vào khe gạch men đến mức rỉ máu tươi vì hối hận và sợ hãi tột cùng. Lâm Mỹ Hạnh đứng bên cạnh run rẩy lẩy bẩy, chiếc điện thoại trên tay rơi xuống sàn vỡ tan tành. Bọn chúng biết rằng, kết quả kiểm định lâm sàng Tây y này chính là bản án tử hình đóng đinh cho dòng muối giả bẩn của bọn chúng.</p>"""

    # Chapter 9
    ch9_title = "Chương 9: Sắc Lệnh C03 Và Sự Trả Giá Tàn Khốc Trong Vũng Bùn"
    ch9_content = """<p>Ngay tại sảnh chính lộng lẫy của Bệnh viện Trung ương Quân đội 108, trước ống kính của hàng trăm phóng viên báo chí, đài truyền hình cùng giới tinh anh y học và tài chính, Nguyễn Cát Tường đứng hiên ngang bên cạnh Võ Thanh Hải. Cô bước lên bục phát biểu, dõng dạc công bố một tập tài liệu đóng dấu đỏ chói lọi:</p>
<p>\"Kính thưa toàn thể dư luận và cơ quan báo chí. Hôm nay, tập đoàn Vạn An Capital phối hợp cùng công ty kiểm toán Big 4 PwC chính thức công bố báo cáo kiểm toán độc lập về quyền sở hữu trí tuệ tối cao đối với công nghệ vi lọc hoa muối hữu cơ Cà Ná. Chúng tôi sở hữu toàn bộ lịch sử Git commit logs gốc được ký số bảo mật bằng khóa PGP cá nhân của kỹ sư Võ Thanh Hải từ ba năm trước trên server Git cá nhân bất biến. Đây là bằng chứng thép tuyệt đối chứng minh Lê Hữu Đạt và tập đoàn Hoàng Gia đã ăn cắp trắng trợn bản quyền công nghệ nghiên cứu y học này của anh Hải để sản xuất dòng muối bẩn chứa hóa chất clo tẩy trắng cực độc gây hại cho tính mạng người dùng!\"</p>
<p>Cùng lúc đó, màn hình lớn của sảnh bệnh viện hiển thị video camera ẩn sắc nét ghi lại toàn bộ cảnh Lê Hữu Đạt nhận hối lộ hàng tỷ đồng để làm giả hồ sơ bệnh án và vu cáo Võ Thanh Hải nhằm cướp đoạt bằng sáng chế. Dòng chứng cứ tài chính rõ ràng dòng tiền bẩn chảy vòng qua các công ty shell cũng được PwC bóc trần chi tiết.</p>
<p>Giữa lúc cả sảnh bệnh viện xôn xao phẫn nộ trước tội ác đê tiện của bọn chúng, tiếng bước chân rầm rập của lực lượng chức năng vang lên. Một đoàn chiến sĩ cảnh sát thuộc cơ quan Cảnh sát Điều tra C03 (Cục Cảnh sát điều tra tội phạm về tham nhũng, kinh tế, buôn lậu) bộ Công an xuất hiện. Kẻ dẫn đầu cầm tờ sắc lệnh đóng dấu đỏ chói lọi:</p>
<p>\"Chúng tôi là cơ quan Cảnh sát Điều tra C03. Căn cứ vào các chứng cứ phạm tội thu thập được, ra lệnh khởi tố vụ án hình sự, bắt tạm giam khẩn cấp đối với Lê Hữu Đạt và các đồng phạm về các tội danh: Sản xuất buôn bán thực phẩm bẩn chứa chất độc hại gây hậu quả đặc biệt nghiêm trọng và Chiếm đoạt tài sản trí tuệ!\"</p>
<p>Lê Hữu Đạt đầu gối bủn rủn quỵ sụp hẳn xuống sàn gạch men lạnh lẽo, mồ hôi lạnh tuôn ra như tắm, sắc mặt xám ngoét không còn giọt máu, móng tay bấu rỉ cả máu tươi vì hối hận muộn màng tột cùng. Hắn khóc lóc gào thét thảm thiết: \"Anh Hải... cứu tôi với... tôi biết sai rồi... xin anh tha cho tôi một con đường sống...\"</p>
<p>Hải nhìn hắn bị còng tay sắt kéo đi, ánh mắt anh phẳng lặng như nước hồ thu, không có lấy một chút oán hận hay thương hại. Lâm Mỹ Hạnh đứng trơ trọi giữa đám đông, khuôn mặt cô ta tràn ngập sự kinh hoàng và hối hận tột độ khi nhận ra giấc mơ hào môn đã hoàn toàn tan vỡ, bản thân cô ta giờ đây cũng sẽ đối mặt với án tù đồng phạm nguy hiểm.</p>"""

    # Chapter 10
    ch10_title = "Chương 10: Minh Ước Trăm Tỷ Và Tình Yêu Thăng Hoa"
    ch10_content = """<p>Một tuần sau cơn bão truyền thông và pháp lý chấn động giới tài phiệt Việt Nam, Tập đoàn Muối Hoàng Gia chính thức tuyên bố phá sản, toàn bộ tài sản bị niêm phong để phục vụ quá trình điều tra của cơ quan C03. Trong khi đó, dự án phục hưng ruộng muối di sản Cà Ná của Võ Thanh Hải và Vạn An Capital nhận được sự ủng hộ nhiệt liệt từ các bộ ban ngành và giới khoa học trong và ngoài nước.</p>
<p>Tại văn phòng đại diện trên tầng cao nhất của tòa nhà Landmark 81 sầm uất, buổi lễ ký kết hợp đồng đầu tư chính thức diễn ra vô cùng sang trọng và ấm cúng. Nguyễn Cát Tường mặc chiếc đầm màu trắng ngọc trai thanh lịch, nụ cười rạng rỡ tỏa sáng trên môi khi cô cùng Hải ký tên vào bản hợp đồng đầu tư 100 tỷ đồng.</p>
<p>Sau khi toàn bộ đối tác và chuyên gia pháp lý ra về, căn phòng họp lớn chỉ còn lại hai người. Ánh hoàng hôn vàng óng ánh của buổi chiều muộn chiếu qua vách kính lớn, bao trùm lên không gian một vẻ ấm áp, lãng mạn vô cùng.</p>
<p>Cát Tường bước lại gần Hải, cô khẽ đặt bàn tay mềm mại lên vai anh, đôi mắt phượng ngập tràn tình cảm dịu dàng: \"Thanh Hải, chúng ta đã cùng nhau vượt qua những ngày tháng giông bão khó khăn nhất. Giờ đây, dòng Hoa Muối Cà Ná của anh sẽ chính thức vươn tầm thế giới, mang lại sức khỏe cho hàng triệu người. Nhưng ngoài bản hợp đồng trăm tỷ này, em muốn trao cho anh một thứ quý giá hơn nhiều.\"</p>
<p>Hải quay lại, nhìn sâu vào đôi mắt phượng lấp lánh của cô, khẽ cười: \"Thứ gì vậy, Cát Tường?\"</p>
<p>Cát Tường khẽ đỏ mặt, cô tựa nhẹ đầu vào lồng ngực rộng ấm áp của Hải, thì thầm bằng giọng nói ngập tràn tình yêu thương sâu sắc: \"Chính là trái tim và tình yêu trọn vẹn của em. Kể từ buổi chiều sương lạnh trong căn phòng trọ nhỏ ngày ấy, em đã biết rằng anh chính là người đàn ông duy nhất mà em muốn đồng hành suốt cuộc đời này.\"</p>
<p>Hải khẽ mỉm cười đầy hạnh phúc, anh ôm chặt lấy thân hình mảnh mai, quyến rũ của cô vào lòng. Giữa bầu trời hoàng hôn lộng lẫy của Sài Gòn, hai người cùng nhìn về phía tương lai rực rỡ, đánh dấu sự thăng hoa hoàn mỹ của một liên minh thép và một tình yêu vĩnh cửu.</p>"""

    novel_data["chapters"].append({"title": ch1_title, "content": ch1_content})
    novel_data["chapters"].append({"title": ch2_title, "content": ch2_content})
    novel_data["chapters"].append({"title": ch3_title, "content": ch3_content})
    novel_data["chapters"].append({"title": ch4_title, "content": ch4_content})
    novel_data["chapters"].append({"title": ch5_title, "content": ch5_content})
    novel_data["chapters"].append({"title": ch6_title, "content": ch6_content})
    novel_data["chapters"].append({"title": ch7_title, "content": ch7_content})
    novel_data["chapters"].append({"title": ch8_title, "content": ch8_content})
    novel_data["chapters"].append({"title": ch9_title, "content": ch9_content})
    novel_data["chapters"].append({"title": ch10_title, "content": ch10_content})

    # Save to pending_novel.json
    print(f"💾 Saving to {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(novel_data, f, ensure_ascii=False, indent=2)
    print("✓ Successfully saved pending_novel.json!")

    # Download cover image from Pollinations AI
    print(f"🎨 Downloading premium cover from Pollinations AI...")
    encoded_prompt = urllib.parse.quote(novel_data["cover_prompt"])
    url = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width=1024&height=1024&nologo=true"
    try:
        req = urllib.request.Request(
            url,
            headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
        )
        with urllib.request.urlopen(req, timeout=60) as response:
            with open(COVER_FILE, 'wb') as out_file:
                out_file.write(response.read())
        print(f"✓ Successfully downloaded cover image to {COVER_FILE}!")
    except Exception as e:
        print(f"❌ Failed to download cover image: {e}")

if __name__ == "__main__":
    main()
