# -*- coding: utf-8 -*-
import json
import os

def build_novel():
    title = "Thần Dược Liệu Sapa: Nhà Nghiên Cứu Bị Sa Thải Lật Kèo Bẫy IPO Dược Phẩm Nghìn Tỷ Của Kẻ Phản Bội"
    author = "Antigravity"
    genre = "Sảng Văn / Vả Mặt"
    
    intro = (
        "<p><strong>\"Đôi bàn tay thối rữa đầy mùi thuốc của mày có rửa sạch mười đời cũng không xứng đứng chung sàn diễn với Bách Dược Group! Cầm đống rác rưởi này rồi cút khỏi Sapa đi!\"</strong></p>\n"
        "<p>Lời sỉ nhục của Tạ Khắc Bách – CEO Bách Dược Group – vang lên chói tai giữa hội trường hội nghị y dược năm sao tại khách sạn Sofitel Legend Metropole Hà Nội. Kẻ phản bội không chỉ ăn cắp công trình nghiên cứu gel thảo dược \"Sapaderm\" mà tôi đã dành bảy năm dầm sương dãi nắng trên đỉnh Fansipan để phát triển, mà còn cấu kết với truyền thông bẩn bôi nhọ tôi ăn cắp hóa chất, dùng thế lực để phong tỏa tài khoản Vietcombank và bôi nhọ tên tuổi tôi trong ngành dược phẩm.</p>\n"
        "<p>Nhưng hắn không hề biết rằng, công thức \"Sapaderm\" mà hắn chuẩn bị mang đi IPO trị giá ba nghìn tỷ đồng chỉ là một bản nháp thô chưa hoàn thiện. Nếu không có enzyme \"Lectin HL-26\" chiết xuất từ Sâm Hoàng Liên Sapa theo quy trình ly tâm lạnh độc quyền do tôi nắm giữ, chất gel ấy sẽ bị oxy hóa sau đúng mười bốn ngày và biến thành một loại độc tố cực mạnh tàn phá tế bào.</p>\n"
        "<p>Khi Đặng Uyển Lâm – nữ chủ tịch lý tính của quỹ đầu tư Nam Phương Capital – thẳng thừng từ chối chuyển vốn trăm tỷ sau khi đối chiếu pháp lý và kiểm tra lâm sàng từ các bác sĩ Tây y, chính là lúc tôi thực hiện cuộc phản kích nghẹt thở. Từ nhật ký commit Git của hệ thống quản lý phòng thí nghiệm LIMS, bản kiểm toán độc lập của Big 4, đến sắc lệnh khởi tố từ C03... Tạ Khắc Bách sẽ phải quỳ gối dưới chân tôi, quỵ xuống sàn rỉ máu vì sự kiêu ngạo của mình!</p>"
    )
    
    cover_prompt = (
        "A premium, highly detailed anime-style book cover, a confident and handsome young Vietnamese pharmacologist "
        "with short black hair, wearing a white clinical lab coat over a dark blue turtleneck, holding a glowing green "
        "botanical gel vial. In the background, the majestic mist-covered Fansipan mountain peaks of Sapa, blended "
        "with the high-tech glowing chemical equipment of a modern laboratory. Elegant and dramatic lighting, vibrant "
        "harmonious colors, HSL tailored palette, 1:1 ratio, clean premium art, no text."
    )
    
    chapters = []
    
    # ------------------ CHAPTER 1 ------------------
    ch1_content = (
        "<p>Không khí bên trong phòng hội nghị thượng đỉnh của khách sạn năm sao Sofitel Legend Metropole Hà Nội ngột ngạt đến mức kim rơi cũng có thể nghe tiếng. Dưới những ngọn đèn chùm pha lê nhập khẩu từ Ý tỏa ra những luồng sáng lộng lẫy và huyền ảo, từng góc phòng đều toát lên mùi tiền và sự xa hoa tột bậc của giới tài phiệt y dược. Cao Vĩnh An đứng lặng im giữa không gian tráng lệ ấy, đôi mắt đen sâu thẳm của anh thản nhiên nhìn thẳng vào gã đàn ông trung niên đang vênh váo trước mặt, không một chút biểu cảm dao động.</p>"
        "<p>\"Đôi bàn tay thối rữa đầy mùi thuốc của mày có rửa sạch mười đời cũng không xứng đứng chung sàn diễn với Bách Dược Group! Cầm đống rác rưởi này rồi cút khỏi Sapa đi!\" Tạ Khắc Bách – CEO kiêu ngạo của Bách Dược Group – đập mạnh xấp hồ sơ dày cộp lên mặt bàn kính cường lực. Tiếng động chói tai vang vọng khắp sảnh tiệc. Trên ngón tay mập mạp của hắn, chiếc nhẫn ngọc bích sáng rực rỡ lóe lên những tia sáng chói mắt đầy đe dọa. Hắn chỉnh lại chiếc cà vạt lụa Hermès và nở nụ cười đắc thắng, như thể sinh sát trong tay hắn hoàn toàn thuộc về hắn. Hắn vừa cướp đoạt công trình nghiên cứu cả đời của Vĩnh An – loại gel thảo dược \"Sapaderm\" đột phá chuyên trị hoại tử chi cho bệnh nhân tiểu đường – để chuẩn bị cho thương vụ IPO trị giá ba nghìn tỷ đồng trên sàn HoSE.</p>"
        "<p>Đứng ngay bên cạnh Bách là Nguyễn Khánh Linh, ái nữ kiêu ngạo của một tập đoàn phân phối dược phẩm lớn đất Bắc. Cô ta diện chiếc đầm dạ hội Haute Couture màu đỏ thẫm đắt đỏ, khoanh tay trước ngực, ánh mắt quét qua bộ trang phục giản dị và đôi giày da đã bạc màu của Vĩnh An với sự khinh miệt tột cùng. Mới chỉ tháng trước, cô ta còn ngọt ngào hẹn ước trăm năm với Vĩnh An khi anh đang ngày đêm lao lực trong phòng thí nghiệm. Thế nhưng, ngay khi biết Bách Dược Group quyết định cướp quyền sở hữu trí tuệ của dự án và sa thải anh, cô ta đã lập tức hủy hôn ước, ngả vào vòng tay của Tạ Khắc Bách để đổi lấy một suất cổ phần ưu đãi trước đợt phát hành cổ phiếu nghìn tỷ.</p>"
        "<p>\"Cao Vĩnh An, mày đừng cố chấp làm gì nữa.\" Giọng Khánh Linh sắc lẹm, lạnh lùng như dao cạo cắt ngang sự im lặng. \"Đôi bàn tay chai sạn vì đào rễ cây của mày, có rửa sạch mười đời cũng không xứng đặt cạnh chiếc nhẫn ngọc bích trị giá năm tỷ này của anh Bách! Mày chỉ là một thằng nghiên cứu sinh quèn xuất thân từ vùng núi nghèo Sapa, không tiền không thế lực. Nếu không nhờ Bách Dược Group cung cấp thiết bị lab, mày làm sao có cơ hội chế tạo ra loại gel đó? Bây giờ mày dám to gan cáo buộc anh Bách ăn cắp công trình sao? Bản quyền sáng chế đã đóng dấu đỏ của Cục Sở hữu Trí tuệ đứng tên anh Bách rồi, mày cãi thế nào được?\"</p>"
        "<p>Vĩnh An khẽ nhếch môi, nụ cười bình thản đến lạ lùng đối lập hoàn toàn với sự giận dữ của hai kẻ trước mặt. Anh đút hai tay vào túi quần, nhìn sâu vào mắt Khánh Linh: \"Khánh Linh, bảy năm qua anh dầm sương dãi nắng trên những vách đá Fansipan để tìm kiếm nguồn dược liệu Sâm Hoàng Liên và Thất Diệp Nhất Chi Hoa hoang dã. Bản thiết kế quy trình ly tâm lạnh để chiết xuất enzyme Lectin HL-26 kia cũng là do anh thức trắng hàng trăm đêm trong phòng lab chật hẹp để viết ra từng dòng nhật ký thử nghiệm. Các người tự dựng lên vở kịch vu khống anh ăn cắp hóa chất phòng lab để sa thải anh, chẳng phải là vì muốn cướp trắng công thức Sapaderm để làm đẹp sổ sách IPO sao?\"</p>"
        "<p>\"Mày câm miệng!\" Tạ Khắc Bách nhổ nước bọt thẳng xuống đôi giày da sờn rách của Vĩnh An, mặt đỏ gay sỉ nhục. \"Mã nguồn và công thức đó đã được đăng ký bảo hộ độc quyền dưới tên tao từ sáng nay rồi. Hợp đồng lao động của mày ghi rõ: mọi phát minh trong quá trình làm việc đều thuộc về sở hữu của công ty. Còn tài khoản Vietcombank của mày đã bị ngân hàng phong tỏa theo yêu cầu điều tra khẩn cấp từ chúng tao vì hành vi phá hoại tài sản công nghiệp. Hiện tại, mày không có quyền lực, không có tiền bạc, cũng không có bất kỳ ai tin mày cả! Mày chỉ là một con kiến hôi trên thương trường dược phẩm Hà Nội này thôi!\"</p>"
        "<p>Tạ Khắc Bách tiến sát lại, gằn từng giọng đầy đe dọa, ngón tay mập mạp dí sát vào mặt Vĩnh An: \"Ký tên vào giấy cam kết từ bỏ mọi quyền khiếu nại công nghệ này, nhận tội phá hoại lab rồi cút khỏi ngành dược Việt Nam! Nếu không, tao sẽ khiến mày ngồi tù mọt xương, cả đời này không ngẩng đầu lên được!\"</p>"
        "<p>Vĩnh An nhìn xấp tài liệu chuyển nhượng, rồi nhìn sang Khánh Linh – người phụ nữ từng thề non hẹn biển với anh, nay lại vì hư vinh mà cấu kết với Bách để cướp đoạt công sức của anh. Bọn họ nghĩ rằng đã dồn anh vào chân tường khi đóng băng tài khoản ngân hàng và tung tin đồn bẩn trên các hội nhóm y dược. Bọn họ nghĩ rằng thế lực hào môn có thể đè bẹp tất cả tri thức và lòng tự trọng của anh.</p>"
        "<p>Nhưng bọn họ hoàn toàn không biết một điều cực kỳ chí mạng. Công thức \"Sapaderm\" mà Bách đang sở hữu thực chất chỉ là một bản nháp thô chưa hoàn thiện. Nếu không có enzyme Lectin HL-26 chiết xuất từ Sâm Hoàng Liên Sapa theo quy trình ly tâm lạnh độc quyền do Vĩnh An nắm giữ, chất gel ấy sẽ bị oxy hóa sau đúng mười bốn ngày và biến thành một loại độc tố cực mạnh tàn phá tế bào, khiến vết thương hoại tử nghiêm trọng hơn gấp bội lần.</p>"
        "<p>\"Tôi sẽ không ký.\" Vĩnh An trầm giọng, ánh mắt kiên định đứng dậy. Anh không thèm nhìn lại hai kẻ tham lam đang trợn mắt giận dữ kia, xoay người thẳng bước ra khỏi phòng hội nghị lộng lẫy, bỏ lại tiếng thét phẫn nộ của Tạ Khắc Bách và cái nhìn khinh bỉ của Nguyễn Khánh Linh phía sau. Trận chiến này, ai thắng ai thua, giờ mới thực sự bắt đầu.</p>"
    )
    chapters.append({"title": "Chương 1: Lời Sỉ Nhục Tại Metropole", "content": ch1_content})
    
    # ------------------ CHAPTER 2 ------------------
    ch2_content = (
        "<p>Cơn mưa lạnh mùa hạ trút xuống xối xả khắp các con phố Hà Nội, từng dòng nước táp thẳng vào cửa kính phòng VIP của Bệnh viện Trung ương Quân đội 108. Bên trong phòng bệnh, không khí căng thẳng bao trùm khi vị giáo sư đầu ngành Tây y cùng hội đồng bác sĩ đang vây quanh giường bệnh của Đặng Trường Giang – nhà sáng lập và là Chủ tịch Tập đoàn Nam Phương danh tiếng. Dưới lớp chăn bông trắng toát, bàn chân phải của ông Giang lộ ra với những mảng da đen kịt, thối rữa và bốc mùi hoại tử nồng nặc – hậu quả tàn khốc của biến chứng tiểu đường cấp độ bốn. Các mạch máu bị tắc nghẽn hoàn toàn, dòng máu không thể lưu thông để nuôi dưỡng các tế bào thần kinh ngoại vi.</p>"
        "<p>\"Thưa cô Uyển Lâm, chúng tôi đã tiến hành chụp Doppler mạch máu và làm tất cả các xét nghiệm lâm sàng cần thiết.\" Vị giáo sư Tây y thở dài, gương mặt vô cùng nghiêm trọng. \"Chỉ số nhiễm trùng máu Procalcitonin đã tăng lên mức nguy hiểm. Nếu không tiến hành phẫu thuật cắt cụt chi đùi phải trong vòng hai mươi tư giờ tới để ngăn chặn vi khuẩn hoại tử tấn công vào hệ tuần hoàn trung ương, Chủ tịch Giang chắc chắn sẽ rơi vào tình trạng sốc nhiễm khuẩn và tử vong. Đây là giải pháp Tây y duy nhất vào lúc này.\"</p>"
        "<p>Đặng Uyển Lâm – con gái độc nhất của ông Giang và cũng là Chủ tịch Quỹ đầu tư Nam Phương Capital – đứng lặng bên giường bệnh. Cô mặc một bộ âu phục đen cắt may tinh xảo của Chanel, gương mặt thanh tú, sắc sảo ẩn sau cặp kính gọng vàng mỏng toát lên vẻ thông tuệ, kiên định và kiêu sa của một nữ tổng tài kiệt xuất. Mặc dù vô cùng lo lắng cho tính mạng của cha, Uyển Lâm vẫn giữ được sự lý tính đáng kinh ngạc. Cô không hề khóc lóc hay hoảng loạn như những cô gái hào môn thông thường, mà lập tức yêu cầu xem xét toàn bộ các chỉ số y khoa và báo cáo kiểm tra độc lập.</p>"
        "<p>\"Cắt cụt chi sẽ khiến cha tôi mất đi khả năng vận động vĩnh viễn và ảnh hưởng nghiêm trọng đến tinh thần của ông.\" Uyển Lâm trầm giọng, giọng nói trong trẻo nhưng đầy uy lực. \"Tôi cần một giải pháp khác. Có phương pháp điều trị bảo tồn nào có thể giữ lại bàn chân cho cha tôi hay không?\"</p>"
        "<p>Đúng lúc đó, cánh cửa phòng bệnh mở ra, Tạ Khắc Bách bước vào với vẻ mặt tràn đầy tự tin, theo sau là hai trợ lý bưng một chiếc hộp y tế chuyên dụng được thiết kế vô cùng sang trọng. Hắn cúi chào Uyển Lâm đầy lịch lãm: \"Cô Uyển Lâm, tôi là Tạ Khắc Bách, CEO của Bách Dược Group. Tôi mang đến đây giải pháp cứu mạng cho Chủ tịch Giang mà không cần phải cắt cụt chân. Đây là 'Bách Dược Linh' – siêu gel sinh học thảo dược được phát triển độc quyền bởi phòng lab của chúng tôi, đã được cấp bằng sáng chế quốc gia. Chất gel này có khả năng tái tạo tế bào hoại tử thần kỳ nhờ sự kết hợp giữa tinh hoa thảo dược cổ truyền Sapa và công nghệ nano Tây y hiện đại.\"</p>"
        "<p>Bách Dược Group đang điên cuồng tìm kiếm nguồn vốn đầu tư ba trăm tỷ đồng từ Nam Phương Capital để bảo chứng cho thương vụ IPO sắp tới. Hắn biết rõ nếu chữa khỏi cho ông Giang, khoản tiền khổng lồ đó sẽ lập tức được giải ngân và cổ phiếu của hắn sẽ tăng phi mã khi niêm yết. Hắn nhìn Uyển Lâm đầy ẩn ý: \"Chỉ cần Nam Phương Capital đặt bút ký vào hợp đồng đầu tư chiến lược trị giá ba trăm tỷ đồng tối nay, tôi sẽ lập tức cho các bác sĩ áp dụng liệu trình Sapaderm đặc trị này cho Chủ tịch Giang. Tôi cam đoan chân của ông ấy sẽ lành lặn hoàn toàn sau một tuần.\"</p>"
        "<p>Uyển Lâm nheo mắt nhìn chiếc hộp y tế, rồi nhìn sang Tạ Khắc Bách với ánh mắt sắc sảo đầy cảnh giác. Sự lý tính của một chuyên gia tài chính hàng đầu khiến cô không dễ dàng tin vào những lời quảng cáo đường mật: \"Anh Bách, tôi chỉ ký hợp đồng đầu tư sau khi đã tiến hành thẩm định pháp lý toàn diện đối với bằng sáng chế của anh và có kết quả thử nghiệm lâm sàng thực tế trên cha tôi. Tôi đồng ý cho anh sử dụng loại gel này để điều trị thử nghiệm dưới sự giám sát chặt chẽ của hội đồng y khoa bệnh viện 108. Nhưng dòng vốn ba trăm tỷ của Nam Phương Capital sẽ chỉ được giải ngân từng phần sau khi các chỉ số sinh hóa của cha tôi chứng minh vết thương thực sự phục hồi một cách sòng phẳng. Hãy bắt đầu điều trị thử nghiệm đi.\"</p>"
    )
    chapters.append({"title": "Chương 2: Cơn Nguy Kịch Của Trùm Tài Phiệt", "content": ch2_content})
    
    # ------------------ CHAPTER 3 ------------------
    ch3_content = (
        "<p>Dưới sự giám sát nghiêm ngặt của hội đồng y khoa Bệnh viện 108 và Đặng Uyển Lâm, Tạ Khắc Bách tự tay mở hộp y tế, lấy ra tuýp gel \"Bách Dược Linh\" màu xanh nhạt. Hắn cẩn thận thoa một lớp gel dày lên vùng da hoại tử đen kịt ở bàn chân phải của Chủ tịch Đặng Trường Giang. Chỉ mười phút sau khi tiếp xúc với chất gel, một phép màu dường như đã xảy ra. Sắc mặt ông Giang vốn đang xám ngoét vì đau đớn bỗng giãn ra, nhịp thở trở nên nhẹ nhàng hơn và ông khẽ mở mắt, thều thào nói rằng cảm giác đau nhức bỏng rát kinh hoàng đã biến mất hoàn toàn. Các bác sĩ Tây y đo các chỉ số sinh tồn và ngạc nhiên thấy huyết áp của bệnh nhân đã ổn định trở lại ở mức 120/80.</p>"
        "<p>Tạ Khắc Bách đắc ý tột cùng, hắn lập tức rút điện thoại ra, yêu cầu đội ngũ truyền thông của Bách Dược Group khởi động một buổi livestream trực tiếp trên các nền tảng mạng xã hội lớn để báo cáo tiến độ điều trị của Chủ tịch Nam Phương Group. Hắn hướng ống kính máy quay vào bàn chân đang có vẻ khô ráo của ông Giang, giọng nói hống hách vang lên đầy kiêu ngạo: \"Kính thưa toàn thể các cổ đông và nhà đầu tư! Như quý vị đã thấy, siêu sản phẩm Bách Dược Linh của chúng tôi đã tạo nên kỳ tích y học ngay trước giờ IPO! Chỉ sau mười phút áp dụng, vết hoại tử tiểu đường nặng của Chủ tịch Giang đã được khống chế hoàn toàn! Tiện đây, tôi cũng muốn gửi lời cảnh cáo đến tên nghiên cứu sinh ăn cắp Cao Vĩnh An – kẻ đã đê tiện vu khống rằng công thức của tôi chứa lỗi độc tính. Hãy nhìn vào kết quả lâm sàng thực tế này đi! Tri thức giả tạo của mày chỉ là trò hề trước công nghệ đỉnh cao của Bách Dược Group!\"</p>"
        "<p>Buổi livestream lập tức thu hút hàng trăm ngàn lượt xem trực tiếp và hàng ngàn bình luận ca ngợi Bách Dược Group từ giới đầu tư chứng khoán. Giá trị cổ phiếu của Bách Dược trên thị trường phi tập trung (OTC) lập tức bị thổi phồng lên gấp đôi, đẩy sự tự tin của Bách lên mức cực hạn. Khánh Linh đứng bên cạnh liên tục cười rạng rỡ trước ống kính, thầm nghĩ giấc mơ trở thành phu nhân tỷ phú đã ở ngay trước mắt.</p>"
        "<p>Thế nhưng, niềm vui ngắn chẳng tày gang. Đúng bốn tiếng sau khi buổi livestream kết thúc, tai họa kinh hoàng ập xuống mà không một ai kịp trở tay. Chất gel \"Bách Dược Linh\" thiếu đi enzyme Lectin HL-26 và quy trình ly tâm lạnh độc quyền của Vĩnh An bắt đầu xảy ra phản ứng oxy hóa mãnh liệt dưới tác động của nhiệt độ cơ thể và các gốc tự do trong mô hoại tử. Chất gel màu xanh nhạt đột ngột chuyển sang màu đen xám xịt, bốc lên một mùi hóa chất hắc ín vô cùng nồng nặc và tàn nhẫn tàn phá tế bào.</p>"
        "<p>\"Bác sĩ! Mau vào đây!\" Tiếng hét thất thanh của Đặng Uyển Lâm vang lên xé toạc sự yên tĩnh của hành lang VIP. Trên giường bệnh, Chủ tịch Đặng Trường Giang đang co giật dữ dội, toàn thân ướt sũng mồ hôi lạnh, miệng sùi bọt mép và rơi vào trạng thái hôn mê sâu. Trên màn hình máy giám sát y khoa, nhịp tim của ông Giang đột ngột sụt giảm nghiêm trọng xuống mức 40 lần/phút, huyết áp tụt dốc không phanh xuống mức cực kỳ nguy kịch 70/40. Vết hoại tử ở bàn chân phải lan rộng một cách khủng khiếp, chuyển sang màu đen thẫm như than đá và rỉ ra những dòng dịch mủ thối rữa màu vàng nhạt.</p>"
        "<p>Hội đồng y khoa Bệnh viện 108 lập tức ập vào phòng bệnh, tiến hành các biện pháp hồi sức cấp cứu khẩn cấp nhưng vô hiệu. Vị giáo sư Tây y lau mồ hôi lạnh trên trán, gương mặt xám ngoét không còn giọt máu: \"Nguy rồi! Chất gel kia đã xảy ra phản ứng oxy hóa ngược, tạo ra một loại độc tố gốc axit cực mạnh tàn phá hoàn toàn các tế bào biểu mô đang suy yếu của bệnh nhân, trực tiếp đẩy vi khuẩn hoại tử vào máu gây ra sốc nhiễm trùng máu cấp tính! Bệnh nhân đã rơi vào tình trạng suy đa tạng cực kỳ bế tắc. Bây giờ ngay cả việc cắt cụt chân cũng chỉ có 10% cơ hội sống sót! Chúng tôi buộc phải đưa bệnh nhân vào phòng mổ khẩn cấp để cắt bỏ toàn bộ chi đùi ngay lập tức, nếu không ông ấy sẽ chết trong vòng hai tiếng nữa!\"</p>"
        "<p>Uyển Lâm đứng sững sờ trước giường bệnh, đôi bàn tay thanh tú bám chặt vào thành giường đến mức các đốt ngón tay rỉ máu tươi. Sự bế tắc tột cùng đè nặng lên vai cô gái trẻ. Cha cô – người thân duy nhất còn lại trên đời – đang đứng trước lằn ranh sinh tử mà tất cả các giải pháp y khoa hàng đầu đều trở nên bất lực. Cô quay sang nhìn Tạ Khắc Bách – kẻ vừa nãy còn vênh váo tự đắc, nay đang đứng run rẩy ở góc phòng, mồ hôi lạnh chảy ròng ròng trên mặt, sắc mặt xám ngoét không còn một giọt máu khi nhận ra thương vụ IPO trị giá ba nghìn tỷ đồng của mình sắp sửa biến thành một bản án tù chung thân vì tội ngộ sát.</p>"
    )
    chapters.append({"title": "Chương 3: Bẫy Độc Dưới Vỏ Bọc Thần Dược", "content": ch3_content})
    
    # ------------------ CHAPTER 4 ------------------
    ch4_content = (
        "<p>\"Dừng phẫu thuật cắt cụt chi ngay lập tức! Các người làm thế chỉ đẩy nhanh cái chết của bệnh nhân mà thôi!\"</p>"
        "<p>Một giọng nói trầm ổn, vang dội đầy uy lực đột ngột cắt ngang bầu không khí hoảng loạn của phòng cấp cứu. Cao Vĩnh An bước vào, đĩnh đạc trong chiếc áo khoác đơn giản nhưng đôi mắt đen sâu thẳm toát lên sự tự tin sắt đá của một bậc thầy y dược thực thụ. Đi bên cạnh anh là hai nhân viên bảo vệ của khách sạn Metropole đã được Uyển Lâm bí mật liên hệ để đưa anh vượt qua hàng rào an ninh nghiêm ngặt của bệnh viện.</p>"
        "<p>\"Cao Vĩnh An? Thằng nghiên cứu sinh quèn bị sa thải kia, ai cho phép mày bước vào đây phá hoại? Các bác sĩ mau đuổi nó ra ngoài!\" Tạ Khắc Bách hét lên đầy hoảng loạn, cố gắng che giấu sự tội lỗi của mình.</p>"
        "<p>\"Im miệng!\" Đặng Uyển Lâm quay phắt lại, ánh mắt sắc sảo như dao cạo găm thẳng vào Bách khiến hắn lập tức câm lặng. Cô nhìn sang Vĩnh An, giọng nói run rẩy nhưng vẫn giữ được sự lý tính tột cùng: \"Anh An, anh biết cách cứu cha tôi đúng không? Hãy chứng minh bằng khoa học thực tế, tôi không thể đặt cược sinh mạng của cha tôi vào những lời nói suông.\"</p>"
        "<p>Vĩnh An không hề phí một giây nào. Anh bước nhanh đến giường bệnh, mở chiếc túi da chuyên dụng, lấy ra một tuýp gel màu xanh ngọc trong suốt – phiên bản Sapaderm hoàn thiện được chiết xuất từ Sâm Hoàng Liên Sapa hoang dã chứa enzyme Lectin HL-26 tinh khiết theo đúng quy trình ly tâm lạnh độc quyền: \"Cô Uyển Lâm, chất gel Bách Dược Linh của Tạ Khắc Bách bị thiếu đi liên kết peptide của enzyme Lectin HL-26 nên khi tiếp xúc với dịch vết thương sẽ bị oxy hóa thành axit corrosive tàn phá tế bào. Bản chất của Đông y là dùng thảo dược để kích hoạt năng lượng tự chữa lành của cơ thể, nhưng phải kết hợp với y lý Tây y để kiểm chứng lâm sàng. Tôi sẽ dùng bài thuốc đắp từ Sâm Hoàng Liên này để trung hòa hoàn toàn độc tố gốc axit tại chỗ, cứu mạng ông Giang tạm thời trong mười lăm phút. Sau đó, tôi cần các bác sĩ Tây y tiến hành kiểm tra Doppler mạch máu để chứng minh kết quả kỳ diệu.\"</p>"
        "<p>Vĩnh An nhanh chóng dùng nước muối sinh lý rửa sạch lớp gel đen bẩn thỉu của Bách, rồi thoa lớp gel Sapaderm màu xanh ngọc trong suốt lên bàn chân hoại tử của ông Giang. Tiếp đó, anh lấy từ hộp châm cứu bạc ra năm cây kim dài, nhanh châm vào các huyệt huyết hải, túc tam lý, tam âm giao để thông mạch hoạt huyết, kích hoạt hệ tuần hoàn ngoại vi hoạt động trở lại dưới tác dụng hoạt chất của sâm Hoàng Liên. Mùi thảo dược thơm dịu mát lan tỏa khắp căn phòng, át đi mùi mủ hoại tử tanh tao.</p>"
        "<p>Chỉ mười phút sau, phép màu Đông - Tây y biện chứng đã xuất hiện trước sự chứng kiến của toàn thể hội đồng y khoa. Nhịp tim của Chủ tịch Đặng Trường Giang trên máy giám sát từ từ tăng trở lại từ 40 lên 75 lần/phút, huyết áp ổn định hoàn hảo ở mức 115/75. Sắc mặt xám ngoét của ông dần trở nên hồng hào, hơi thở sâu và đều đặn, ông khẽ mở mắt nhìn con gái rồi ngủ say một cách bình yên, không còn một chút dấu hiệu co giật.</p>"
        "<p>\"Bác sĩ, mau tiến hành siêu âm Doppler mạch máu ngoại vi ngay lập tức!\" Vị giáo sư Tây y hô to đầy phấn khích. Kỹ thuật viên nhanh chóng đưa máy siêu âm đến giường bệnh, di chuyển đầu dò dọc theo cẳng chân phải của ông Giang. Trên màn hình máy siêu âm Doppler, những đường sóng màu đỏ và xanh biểu thị dòng máu chảy xiết bất ngờ bùng nổ dữ dội. Vị giáo sư chỉ vào màn hình, giọng run rẩy vì kinh ngạc tột độ: \"Thật kỳ diệu! Dòng máu động mạch chày sau vốn bị tắc nghẽn hoàn toàn nay đã lưu thông trơn tru trở lại! Nồng độ oxy hóa tế bào biểu mô đã tăng từ 30% lên mức bình thường 95%! Các tế bào hoại tử đang được đào thải tự nhiên, và các mô hạt mới đang tái tạo với tốc độ kinh ngạc! Bàn chân phải của Chủ tịch Giang đã được cứu sống hoàn toàn mà không cần cắt cụt chi! Đây là một kỳ tích lâm sàng xuất sắc nhất lịch sử y dược Việt Nam!\"</p>"
        "<p>Nghe lời khẳng định của vị giáo sư Tây y hàng đầu, toàn bộ các bác sĩ trong phòng bệnh đồng loạt vỗ tay rền vang. Cao Vĩnh An nhẹ nhàng rút các cây kim bạc, lau sạch mồ hôi trên trán và mỉm cười nhìn Uyển Lâm. Sự bế tắc tột cùng đã được đập tan bằng tri thức khoa học và bản lĩnh sắt đá. Anh quay sang nhìn Tạ Khắc Bách đang đứng như trời trồng ở góc phòng, đầu gối bủn rủn run bần bật, sắc mặt xám ngoét không còn một giọt máu khi nhận ra quả bom dối trá của mình đã hoàn toàn bị tháo ngòi nổ tàn khốc.</p>"
    )
    chapters.append({"title": "Chương 4: Đông Tây Y Biện Chứng Phục Hồi", "content": ch4_content})
    
    # ------------------ CHAPTER 5 ------------------
    ch5_content = (
        "<p>Đêm muộn, bầu trời Hà Nội dịu mát và yên tĩnh sau cơn mưa dài tầm tã. Trên ban công tầng thượng của Bệnh viện 108, nơi được thiết kế thành một khu vườn nhỏ với những khóm hoa nhài và hoa quỳnh tỏa hương thơm ngát dưới ánh trăng huyền ảo, Đặng Uyển Lâm đứng lặng yên nhìn xuống dòng sông Hồng lung linh ánh đèn cầu Long Biên phía xa. Cô đã cởi bỏ bộ vest công sở cứng nhắc ban ngày, chỉ mặc một chiếc đầm lụa màu trắng đơn giản thanh lịch, để mái tóc đen dài thả tự nhiên bay nhẹ trong gió đêm. Vẻ kiều diễm, kiêu sa thường ngày của cô giờ đây nhường chỗ cho một chút dịu dàng, mệt mỏi nhưng vô cùng cuốn hút của một người con gái vừa trải qua giông bão cuộc đời.</p>"
        "<p>Nghe tiếng bước chân đĩnh đạc phía sau, Uyển Lâm khẽ quay lại. Khi thấy Cao Vĩnh An bước đến với hai ly nước ấm trên tay, đôi môi đỏ mọng của cô khẽ nở một nụ cười nhẹ ấm áp – nụ cười đầu tiên của cô sau ba ngày căng thẳng nghẹt thở vừa qua. Cô đón lấy ly nước, khẽ chạm nhẹ vào tay anh, cảm nhận được hơi ấm và sự chai sạn đầy tin cậy từ lòng bàn tay của người đàn ông đã cứu mạng cha mình.</p>"
        "<p>\"Cảm ơn anh, anh An.\" Uyển Lâm trầm giọng, giọng nói trong trẻo của cô lúc này chứa đựng sự chân thành và dịu dàng hiếm thấy ở một nữ tổng tài lạnh lùng. \"Tối nay, nếu không có anh xuất hiện kịp thời cùng chất gel Sapaderm và những cây kim bạc đó, tôi thực sự không biết mình sẽ phải sống thế nào nếu mất đi cha mình. Sự lý tính của tôi trước đây đã khiến tôi nghi ngờ anh, tôi thực sự xin lỗi vì sự bất cẩn đó.\"</p>"
        "<p>Vĩnh An đứng bên cạnh cô, lưng tựa vào lan can ban công, mắt nhìn về phía những ngọn đèn lung linh của thành phố: \"Cô Uyển Lâm, cô không cần phải xin lỗi. Trong thế giới tài chính sòng phẳng của cô, việc thẩm định kỹ lưỡng pháp lý và kiểm tra lâm sàng thực tế trước khi đầu tư là hoàn toàn chính xác. Y dược cũng vậy, nếu chỉ dựa vào những lời quảng cáo truyền thống mà thiếu đi các chỉ số xét nghiệm Tây y hiện đại để chứng minh hiệu quả lâm sàng, chúng ta sẽ chỉ tạo ra những kẻ lừa đảo như Tạ Khắc Bách. Tôi chọn y học cổ truyền không phải vì muốn làm thần y ẩn thế, mà vì tôi muốn chứng minh cho thế giới thấy thảo dược Việt Nam hoàn toàn có thể được khoa học hóa để cứu sống hàng triệu người một cách sòng phẳng.\"</p>"
        "<p>Uyển Lâm nhìn nghiêng gương mặt cương nghị, đôi mắt đen sâu thẳm đầy lý tưởng của Vĩnh An dưới ánh trăng sáng tỏ. Cô cảm thấy trái tim kiêu kỳ, lạnh giá suốt nhiều năm qua của mình lần đầu tiên bị rung động mạnh mẽ bởi một người đàn ông. Anh không dùng những lời tán tỉnh ngọt ngào hay gia thế giàu sang để thu hút cô, mà chinh phục cô hoàn toàn bằng trí tuệ sắc bén, sự kiên cường và tấm lòng chân thành không vụ lợi. Cô khẽ tiến lại gần anh hơn một chút, khoảng cách giữa hai cơ thể thu hẹp lại dưới bầu trời đêm đầy sao lấp lánh của Hà Nội, tạo nên một luồng điện xúc cảm nhẹ nhàng lan tỏa khắp không gian yên tĩnh.</p>"
        "<p>\"Anh An, cha tôi đã qua cơn nguy kịch và sẽ phục hồi hoàn toàn sau một tuần nữa nhờ công thức của anh.\" Uyển Lâm khẽ nghiêng đầu, ánh mắt lộ vẻ dịu dàng tột cùng nhìn anh. \"Tôi đã yêu cầu đội ngũ luật sư hủy bỏ toàn bộ mọi đàm phán đầu tư với Bách Dược Group. Ngày mai, tôi muốn đề xuất một sự hợp tác mới giữa quỹ Nam Phương Capital và cá nhân anh để thành lập tập đoàn An Dược Sapa. Chúng ta sẽ cùng nhau đưa công thức Sapaderm thật sự ra thị trường toàn cầu. Nhưng tối nay, tôi không muốn nói về các con số hay hợp đồng đầu tư nữa. Tôi chỉ muốn đứng đây bên cạnh anh, tận hưởng làn gió mát của Hồ Tây sau cơn bão lớn. Anh đồng ý chứ?\"</p>"
        "<p>Vĩnh An nhìn thẳng vào đôi mắt trong veo lấp lánh của cô, mỉm cười ấm áp và nhẹ nhàng nắm lấy bàn tay thanh tú của cô trên lan can ban công. Hai bàn tay đan chặt vào nhau dưới ánh trăng đêm huyền ảo, chứng minh cho một liên minh bền vững được xây dựng trên lòng tin, tri thức và sự chân thành sâu sắc nhất. Trận chiến pháp lý và tài chính ngày mai vẫn đang chờ đợi phía trước, nhưng lúc này, thế giới đối với họ chỉ có sự bình yên và đồng điệu hoàn hảo giữa hai tâm hồn kiên cường.</p>"
    )
    chapters.append({"title": "Chương 5: Sân Thượng Trong Đêm Sương", "content": ch5_content})
    
    # ------------------ CHAPTER 6 ------------------
    ch6_content = (
        "<p>Sáng thứ Năm, đúng chín giờ, tại phòng họp VIP tầng thượng của tòa nhà Nam Phương Center trên đường Lý Thường Kiệt, Hà Nội, một cuộc họp thẩm định đầu tư đặc biệt được diễn ra dưới sự chủ trì trực tiếp của Đặng Uyển Lâm. Khác hoàn toàn với những buổi ký kết hợp đồng mang tính hình thức thông thường, không khí phòng họp vô cùng nghiêm túc và chuyên nghiệp với sự hiện diện của đầy đủ ban cố vấn pháp lý hàng đầu, đại diện kiểm toán độc lập của Big 4 PwC và các chuyên gia nghiên cứu từ Viện Kiểm nghiệm Thuốc Trung ương. Uyển Lâm ngồi ở vị trí trung tâm bàn họp gỗ sồi dài, diện bộ âu phục màu xám tro thanh lịch, cặp mắt sắc sảo lật xem từng trang tài liệu pháp lý một cách vô cùng tỉ mỉ.</p>"
        "<p>\"Thưa Chủ tịch Uyển Lâm, chúng tôi đã hoàn tất việc rà soát toàn bộ lịch sử sở hữu trí tuệ của dự án gel Sapaderm.\" Luật sư trưởng Đỗ Quốc Tuấn đứng lên báo cáo, tay chỉ vào sơ đồ pháp lý hiển thị trên màn hình lớn. \"Bằng sáng chế gốc về quy trình tách chiết enzyme Lectin HL-26 từ thảo dược Sapa thực chất đã được ông nội của anh Cao Vĩnh An – cụ Cao Vĩnh Khang, một danh y nổi tiếng – đăng ký bảo hộ độc quyền dưới dạng bí mật gia truyền tại Cục Sở hữu Trí tuệ từ năm 2005. Bản quyền mà Tạ Khắc Bách đăng ký cho Bách Dược Group tuần trước chỉ là một đơn xin bảo hộ phiên bản sửa đổi thô sơ dựa trên các báo cáo thí nghiệm bị đánh cắp, hoàn toàn vi phạm luật sở hữu trí tuệ và có thể bị tuyên hủy bỏ hiệu lực ngay lập tức khi chúng ta nộp đơn khiếu nại kèm hồ sơ gốc.\"</p>"
        "<p>Tiếp đó, đại diện Viện Kiểm nghiệm Thuốc Trung ương cũng công bố kết quả kiểm định độc học độc lập: \"Chúng tôi đã tiến hành phân tích mẫu gel Sapaderm do anh Cao Vĩnh An cung cấp. Kết quả thử nghiệm lâm sàng trên ba mươi mẫu bệnh phẩm hoại tử biểu mô chứng minh chất gel này hoàn toàn đạt độ ổn định pH lý tưởng 6.5 nhờ sự bảo vệ của liên kết peptide Lectin HL-26, không phát sinh bất kỳ phản ứng oxy hóa độc hại nào sau ba mươi ngày theo dõi. Thuốc đạt tiêu chuẩn an toàn sinh học cấp A quốc tế, sẵn sàng cho việc xuất khẩu chính ngạch sang thị trường Mỹ và Châu Âu.\"</p>"
        "<p>Uyển Lâm gật đầu hài lòng, đôi môi nở nụ cười thỏa mãn. Cô là người cực kỳ lý tính và sòng phẳng, luôn yêu cầu mọi thứ phải rõ ràng minh bạch về mặt pháp luật và khoa học trước khi đặt bút chuyển tiền. Cô đẩy bản hợp đồng đầu tư chính thức sang phía Cao Vĩnh An: \"Anh An, mọi thẩm định pháp lý và kiểm tra lâm sàng độc lập đã hoàn toàn Bulletproof. Quỹ đầu tư Nam Phương Capital quyết định giải ngân trọn gói ba trăm tỷ đồng để thành lập Tập đoàn An Dược Sapa. Anh sẽ giữ 60% cổ phần với tư cách Chủ tịch kiêm Giám đốc R&D độc quyền, Nam Phương Capital giữ 40% cổ phần và chịu trách nhiệm toàn bộ về mảng phân phối, tài chính quốc tế. Đây là sự hợp tác sòng phẳng, tôn trọng tuyệt đối giá trị tri thức của anh.\"</p>"
        "<p>Cao Vĩnh An cầm cây bút ký tên vào bản hợp đồng một cách dứt khoát. Dòng tiền ba trăm tỷ đồng từ quỹ Nam Phương Capital lập tức được kích hoạt trên hệ thống tài chính quốc tế, mang đến cho anh một nguồn lực khổng lồ để bắt đầu cuộc tổng tấn công đè bẹp những kẻ phản bội. Anh nhìn Uyển Lâm, chân thành nói: \"Sự lý tính và sòng phẳng của cô hôm nay chính là bệ phóng lớn nhất để chấn hưng y dược Việt Nam. Tôi sẽ chứng minh cho cô thấy khoản đầu tư này là quyết định sáng suốt nhất của Nam Phương Capital.\"</p>"
        "<p>Uyển Lâm đứng dậy, kiêu sa chỉnh lại cổ áo vest Chanel, ánh mắt lộ vẻ sắc sảo tột cùng: \"Tôi đầu tư vì lợi nhuận sạch, và tôi cũng rất ghét những kẻ gian thương dùng quyền lực tiền bạc để cướp đoạt công sức của người khác, hủy hoại danh tiếng y dược nước nhà. Hãy dùng ba trăm tỷ này để tiễn Tạ Khắc Bách và tập đoàn lừa đảo của hắn vào nấm mồ tài chính ngay trong đêm nay. Đội ngũ truyền thông và pháp lý của tôi đã sẵn sàng hỗ trợ anh tối đa.\"</p>"
    )
    chapters.append({"title": "Chương 6: Bản Hợp Đồng Trăm Tỷ Sòng Phẳng", "content": ch6_content})
    
    # ------------------ CHAPTER 7 ------------------
    ch7_content = (
        "<p>Tối thứ Sáu, Trung tâm Hội nghị Quốc gia Hà Nội rực rỡ ánh đèn chùm pha lê khổng lồ tỏa ra những luồng sáng lộng lẫy, chào đón hàng ngàn khách mời thuộc giới siêu giàu, các quỹ đầu tư tài chính, các nhà báo quốc tế và các chuyên gia y dược hàng đầu đến tham dự Đêm hội Lễ công bố niêm yết cổ phiếu và IPO trị giá ba nghìn tỷ đồng của Bách Dược Group. Khắp đại sảnh rộng lớn được trang hoàng bằng thảm đỏ cao cấp và những khóm hoa ly trắng ngát hương thơm. Trên sân khấu lớn, Tạ Khắc Bách diện bộ vest Savile Row đắt tiền đặt may riêng, gương mặt tròn trịa tràn đầy sự đắc ý và hống hách tột cùng. Hắn vênh váo đi lại trên sân khấu, trên tay luôn thường trực chiếc ly pha lê chứa champagne đắt tiền, liên tục cúi chào các phóng viên để chụp ảnh chụp hình.</p>"
        "<p>\"Kính thưa toàn thể quý vị khách quý và các nhà đầu tư lớn!\" Giọng Tạ Khắc Bách vang dội khắp khán phòng qua hệ thống loa công suất lớn, thu hút toàn bộ sự chú ý của mọi người. \"Đêm nay chính là thời khắc lịch sử khi cổ phiếu của Bách Dược Group chính thức được niêm yết trên sàn chứng khoán với mức giá chào sàn kỷ lục, đưa giá trị vốn hóa của tập đoàn đạt mức ba nghìn tỷ đồng! Sự thành công vượt bậc này được bảo chứng vững chắc bởi siêu sản phẩm trị hoại tử tiểu đường Bách Dược Linh – một thần dược y dược độc quyền sẽ thay đổi hoàn toàn cục diện y học thế giới! Chúng tôi tự hào khẳng định không có một sản phẩm nào trên thị trường có thể so sánh được với cực phẩm này về cả giá trị thương mại lẫn hiệu quả điều trị bảo tồn!\"</p>"
        "<p>Khánh Linh đứng bên cạnh Bách, mặc chiếc đầm đính hàng ngàn viên pha lê lấp lánh kiêu kỳ, liên tục cười nói rạng rỡ trước các ống kính phóng viên báo chí để phỏng vấn. Cô ta hếch cằm kiêu ngạo nhìn xuống dưới khán phòng, thầm nghĩ Cao Vĩnh An giờ này chắc đang trốn trong một góc tối tăm nào đó của vùng núi Sapa nghèo nàn, khóc lóc nhục nhã vì bị phong tỏa hoàn toàn tài sản và danh tiếng bị hủy hoại vĩnh viễn. Mọi người dưới khán phòng đổ dồn mắt nhìn nhau, vỗ tay rầm rộ chào mừng thương vụ IPO thành công của gã CEO hống hách.</p>"
        "<p>\"Viên thuốc đó là một sản phẩm độc hại chưa hoàn thiện! Các người đang dùng sinh mạng của hàng triệu bệnh nhân tiểu đường để đánh cược cho một trò lừa đảo IPO giả tạo!\"</p>"
        "<p>Một giọng nói trầm tĩnh, vang vọng đầy uy lực đột ngột cắt ngang tiếng vỗ tay náo nhiệt và tiếng nhạc mừng của ban nhạc. Cánh cửa gỗ lớn của đại sảnh bị đẩy mạnh ra. Cao Vĩnh An bước vào, đĩnh đạc trong bộ vest đen may đo thủ công sang trọng lịch lãm, đi bên cạnh anh là Đặng Uyển Lâm kiêu sa như một nữ hoàng tuyết với chiếc cổ cao đeo sợi dây chuyền Sâm Hoàng Liên lấp lánh ánh đỏ bồ câu tinh khiết. Sự xuất hiện bất ngờ của hai người cùng đoàn tùy tùng pháp lý lập tức khiến toàn bộ hàng ngàn khách mời và giới truyền thông tài chính xôn xao đứng dậy, các ống kính máy quay lập tức xoay chuyển hướng về phía cửa ra vào tạo nên một làn sóng xầm xì cực lớn.</p>"
        "<p>\"Cao Vĩnh An? Thằng nghiên cứu sinh bị sa thải kia, ai cho phép mày bước vào đây phá hoại lễ hội của tao? Bảo vệ đâu, lập tức ném nó ra ngoài đường!\" Tạ Khắc Bách đỏ gay mặt vì giận dữ, hắn chỉ tay hét lớn đầy hung hãn trên sân khấu.</p>"
        "<p>\"Ai dám đuổi Chủ tịch của An Dược Sapa?\" Đặng Uyển Lâm bước lên trước một bước, giơ cao tập tài liệu đóng dấu đỏ của Quỹ Nam Phương Capital cùng quyết định khẩn cấp của Cục Sở hữu Trí tuệ. \"Theo quy chế niêm yết quốc gia, bất kỳ cổ đông lớn hay đơn vị thẩm định độc lập nào cũng có quyền yêu cầu tạm dừng lễ IPO nếu phát hiện doanh nghiệp có hành vi gian lận thông tin và vi phạm nghiêm trọng luật sở hữu trí tuệ công nghiệp. Cao Vĩnh An là chủ sở hữu hợp pháp duy nhất của bằng sáng chế công thức Sapaderm gốc. Chúng tôi yêu cầu công bố sự thật trước toàn thể đại hội sòng phẳng!\"</p>"
        "<p>Trước sự chứng kiến của hàng ngàn khách mời siêu giàu, giới truyền thông lớn và các phóng viên đang truyền hình trực tiếp, Bách không thể từ chối mà không làm dấy lên sự nghi ngờ về tính minh bạch của tập đoàn. Hắn nghiến răng tự đắc, nghĩ rằng công thức thô của mình đã được đăng ký thành công: \"Được! Tao cho mày công bố! Để xem một thằng nghèo hèn như mày có thể đưa ra được bằng chứng gì ngoài những lời vu khống rẻ tiền!\"</p>"
    )
    chapters.append({"title": "Chương 7: Hào Quang Giả Tạo Và Sân Khấu Vả Mặt", "content": ch7_content})
    
    # ------------------ CHAPTER 8 ------------------
    ch8_content = (
        "<p>Cao Vĩnh An đĩnh đạc bước lên sân khấu lớn trước hàng ngàn ánh mắt nghẹt thở của toàn bộ khán phòng. Anh không hề phí một giây nào, nhanh chóng kết nối chiếc laptop bảo mật của mình với hệ thống máy chiếu màn hình LED khổng lồ rộng 200 inch ở trung tâm sân khấu qua cổng HDMI. Chỉ ba giây sau, một giao diện dòng lệnh lập trình phức tạp của hệ thống quản lý phòng thí nghiệm LIMS (Laboratory Information Management System) hiện ra trên màn hình lớn trước sự kinh ngạc của mọi người.</p>"
        "<p>\"Hãy nhìn vào nhật ký commit Git gốc này.\" Vĩnh An chỉ tay vào các dòng mã nguồn được mã hóa bất biến hiển thị rõ ràng trên màn hình. \"Từng dòng code phân tích enzyme Lectin HL-26 và công thức gel Sapaderm đều được tôi commit với chữ ký số cá nhân và timestamp bất biến trên hệ thống LIMS của phòng thí nghiệm từ ba năm trước, khi Tạ Khắc Bách còn chưa hề biết Sâm Hoàng Liên là gì. Mỗi commit đều có mã hash SHA-256 không thể giả mạo, chứng minh quyền tác giả tuyệt đối của tôi đối với công trình nghiên cứu này. Tạ Khắc Bách đã lợi dụng quyền quản trị hệ thống để copy toàn bộ file thiết kế và đổi tên tác giả sang tên hắn tuần trước. Nhưng hắn không hề biết rằng, tôi đã cài đặt một chữ ký chìm ẩn sâu trong cấu trúc thuật toán mà chỉ có khóa bảo mật cá nhân của tôi mới có thể kích hoạt hiển thị.\"</p>"
        "<p>Vĩnh An gõ một dòng lệnh ngắn trên bàn phím. Ngay lập tức, trên màn hình LED khổng lồ, toàn bộ mã nguồn của bằng sáng chế Bách Dược Linh tự động phân rã, hiển thị một dòng chữ chìm sáng rực rỡ màu xanh ngọc: **\"PROPRIETARY PROPERTY OF CAO VINH AN - ALL RIGHTS RESERVED 2023\"**. Bằng chứng đanh thép rõ ràng chứng minh Bách Dược Group đã thực hiện một vụ trộm cắp sở hữu trí tuệ trắng trợn nhất lịch sử công nghệ Việt Nam.</p>"
        "<p>Chưa dừng lại ở đó, Đặng Uyển Lâm bước lên bục phát biểu, dứt khoát công bố tập tài liệu thứ hai của Big 4 PwC lên màn hình lớn: \"Đây là báo cáo kiểm toán độc lập của PwC và hồ sơ thanh tra tài chính chứng minh Bách Dược Group đã sử dụng hơn hai mươi tỷ đồng từ quỹ dự phòng để hối lộ cho các thành viên của hội đồng thử nghiệm lâm sàng nhằm làm giả kết quả thử nghiệm y khoa, che giấu lỗi độc tính nghiêm trọng của Bách Dược Linh. Họ đã lừa dối hàng ngàn nhà đầu tư bằng những con số ảo để thực hiện vụ lừa đảo IPO ba nghìn tỷ này!\"</p>"
        "<p>Đúng lúc đó, cánh cửa lớn của đại sảnh một lần nữa bị đẩy mạnh ra bởi những bước chân nghiêm nghị. Một đội cảnh sát điều tra thuộc Cục Cảnh sát Điều tra Tội phạm về Tham nhũng, Kinh tế, Buôn lậu (C03 Bộ Công an) bước vào. Vị chỉ huy trưởng giơ cao tấm thẻ ngành màu đỏ quyền lực và công bố sắc lệnh đanh thép: \"Tạ Khắc Bách! Theo quyết định của Bộ Công an, anh bị khởi tố và bắt tạm giam ngay lập tức về tội danh trộm cắp sở hữu trí tuệ công nghiệp, hối lộ làm giả hồ sơ lâm sàng và thao túng thông tin niêm yết chứng khoán! Yêu cầu anh hợp tác!\"</p>"
        "<p>\"Không... việc này không thể... làm sao các người có được...\" Tạ Khắc Bách nhìn màn hình hiển thị những bằng chứng sắt đá và những chiếc còng số tám đang tiến lại gần, đầu gối bỗng chốc bủn rủn rụng rời hoàn toàn. Sắc mặt hắn xám ngoét không còn một giọt máu, toàn thân khuỵu xuống nền gạch đá cẩm thạch mát lạnh của phòng hội nghị. Mồ hôi lạnh chảy thành dòng bên thái dương ướt sũng cả chiếc áo sơ mi đắt tiền, hơi thở dồn dập rồi nghẹn ứ ở cổ họng, hắn hoảng loạn đến mức nghiến răng quá chặt làm rỉ ra một vệt máu tươi bên khóe môi. Hắn biết rõ đời hắn, sự nghiệp và đế chế của hắn đã hoàn toàn kết thúc tàn khốc trong nháy mắt.</p>"
        "<p>Nguyễn Khánh Linh đứng bên cạnh cũng hét lên một tiếng đầy kinh hoàng trước sự sụp đổ của giấc mơ hào môn phu nhân tỷ phú. Đôi chân cô ta run rẩy lẩy bẩy rồi quỵ xuống dưới chân bục phát biểu như một con búp bê đứt dây, lớp trang điểm đắt tiền lem luốc khắp mặt mày vì nước mắt hoảng sợ tột cùng. Cô ta điên cuồng cào cấu vào thành sàn sân khấu đến mức móng tay rỉ máu tươi, nhìn Vĩnh An với ánh mắt đầy hối hận và van xin cứu vớt, nhưng tất cả đã quá muộn màng. Sự kiêu ngạo vô bờ bến của bọn họ đã phải trả một cái giá đắt nhất dưới chân tri thức, công lý và tình yêu chân chính.</p>"
        "<p>Cao Vĩnh An và Đặng Uyển Lâm đứng bên nhau trên sân khấu lớn rực rỡ ánh sáng, tay trong tay nhìn những kẻ phản bội bị dẫn đi trong tiếng vỗ tay rền vang như sóng biển của hàng ngàn khách mời. Tập đoàn An Dược Sapa chính thức được công bố thành lập, bắt đầu hành trình đưa thần dược thảo dược Việt Nam vươn ra thế giới một cách sòng phẳng và kiêu hãnh nhất. Ánh sáng công lý đã chiến thắng trọn vẹn, mở ra một chương mới rực rỡ cho y dược nước nhà và tình yêu bền vững của họ.</p>"
    )
    chapters.append({"title": "Chương 8: Ánh Sáng Công Lý Và Sự Trả Giá", "content": ch8_content})
    
    novel_data = {
        "title": title,
        "author": author,
        "genre": genre,
        "intro": intro,
        "cover_prompt": cover_prompt,
        "chapters": chapters
    }
    
    # Save to pending_novel.json
    output_path = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_novel.json"
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(novel_data, f, ensure_ascii=False, indent=2)
        
    print("Novel generated successfully and saved to pending_novel.json!")

if __name__ == "__main__":
    build_novel()
