# -*- coding: utf-8 -*-
import json
import os

OUTPUT_FILE = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_novel.json"

def main():
    print("🚀 Writing Rice Webnovel using Golden V13 standards...")

    novel_data = {
        "title": "Nhà Khoa Học Lúa Gạo Bị Cướp Giống Lúa Quý, Lật Kèo Thâu Tóm Tập Đoàn Nông Nghiệp IPO Trăm Tỷ",
        "author": "Thanh Phong",
        "genre": "Sảng Văn",
        "intro": "<p><strong>\"Cậu đã chính thức bị sa thải khỏi Viện Nghiên cứu Nông nghiệp miền Nam. Toàn bộ giống lúa hữu cơ Hoàng Kim Hương kháng mặn mà cậu phát triển suốt năm năm qua sẽ thuộc sở hữu của Viện, từ nay cậu không còn tư cách bước vào đây nữa!\"</strong></p>\n<p>Lâm Chí Viễn, một nhà khoa học sinh học nông nghiệp kiêm thầy thuốc y học cổ truyền trẻ tuổi kiệt xuất, bỗng dưng bị Viện trưởng Đoàn Thế Hùng vu cáo hủy hoại mẫu gen lúa lai để tống cổ anh ra khỏi viện. Mục đích của chúng là cướp đoạt thành quả nghiên cứu giống lúa thơm Hoàng Kim Hương có hoạt chất hạ đường huyết từ dịch chiết vỏ trấu sâm quý nhằm bán cho AgroTech Việt Nam - tập đoàn nông nghiệp do gã giám đốc gian xảo Trần Minh Hải điều hành, chuẩn bị cho đợt IPO trăm tỷ.</p>\n<p>Không chỉ mất việc, Chí Viễn còn bị người yêu cũ Phạm Thu Hà phản bội, ăn cắp đĩa chứa nhật ký thực nghiệm và mật khẩu máy chủ để dâng cho kẻ thù nhằm bước chân vào hào môn. Tài khoản Agribank bị phong tỏa, hợp tác xã của anh bị đình chỉ 24 giờ thanh tra bất ngờ, truyền thông bẩn bôi nhọ anh trên sóng livestream. Thế nhưng, chúng không ngờ Chí Viễn đã âm thầm bảo mật toàn bộ lịch sử nghiên cứu bằng nhật ký Git commit gốc có ký số bảo mật PGP bất biến.</p>\n<p>Cùng sự đồng hành của Lê Hoài Thu - ái nữ kiên cường, lý tính của quỹ đầu tư Thịnh Phát Agro-Fund, Chí Viễn đã thực hiện màn lật kèo ngoạn mục ngay tại buổi lễ IPO của đối thủ. Bằng kỹ thuật châm cứu giữ mạng kết hợp dịch chiết lúa quý chứng minh hiệu quả lâm sàng Tây y thần kỳ cứu sống tỷ phú Lê Hoài Nam, cùng sắc lệnh đanh thép từ cơ quan C03, anh đã đập tan âm mưu của kẻ thù, bắt chúng phải quỳ gối chịu tội trong nhục nhã ê chề.</p>",
        "cover_prompt": "A highly premium anime style, 1:1, luxurious illustration. A handsome 29-year-old Vietnamese agricultural scientist with sharp eyes and determined expression, wearing a stylish modern field researcher outfit, holding a glowing golden rice stalk with green grains inside a modern high-tech laboratory. Beside him stands a beautiful, elegant, and highly sophisticated 27-year-old Vietnamese female CEO in a premium dark blue business blazer. In the background, beautiful golden sunset over misty Mekong Delta rice fields visible through large glass windows, advanced bio-analysis screens displaying molecular structures. Beautiful cinematic warm lighting, detailed accents, no text.",
        "chapters": []
    }

    # Chapter 1
    ch1_title = "Chương 1: Đêm Giông Bão Miền Tây Và Tờ Quyết Định Sa Thải Lạnh Lùng"
    ch1_content = """<p>Cơn bão nhiệt đới đổ bộ vào vùng đồng bằng sông Cửu Long mang theo những tiếng sấm sét rạch ngang bầu trời đêm xám xịt của Sài Gòn. Bên trong phòng nghiên cứu công nghệ sinh học nông nghiệp của Viện Nghiên cứu Nông nghiệp miền Nam, không khí ngột ngạt đến mức có thể nghe thấy cả tiếng máy lạnh chạy ro ro đều đặn. Lâm Chí Viễn đứng lặng lẽ trước cửa kính lớn, ánh mắt anh phản chiếu những giọt nước mưa chảy dài như những vết sẹo. Trên chiếc bàn thí nghiệm kim loại sáng loáng là tờ quyết định sa thải đóng dấu đỏ chói lọi, ghi rõ tội danh: \"Cố ý làm hư hại mẫu gen lúa giống quốc gia và vi phạm đạo đức nghiên cứu\".</p>
<p>Đó là một lời vu cáo vô cùng bỉ ổi nhưng được sắp xếp vô cùng tỉ mỉ. Giống lúa thơm Hoàng Kim Hương - thành quả suốt năm năm dãi nắng dầm mưa ngoài đồng ruộng ngập mặn của Chí Viễn, chứa dòng hoạt chất tự nhiên quý hiếm trong vỏ trấu có khả năng hạ đường huyết và cải thiện hệ tuần hoàn - đã bị Viện trưởng Đoàn Thế Hùng âm thầm cướp đoạt sạch sẽ.</p>
<p>\"Mày đã ký vào biên bản bàn giao chưa, Viễn?\" Giọng nói hách dịch vang lên từ cửa phòng. Đoàn Thế Hùng bước vào, chiếc bụng phệ nhô ra dưới lớp áo sơ mi đắt tiền, bên cạnh gã là Trần Minh Hải - Giám đốc điều hành của AgroTech Việt Nam, kẻ đang chuẩn bị đưa AgroTech lên sàn chứng khoán thông qua vụ IPO trăm tỷ dựa trên giống lúa Hoàng Kim Hương ăn cắp.</p>
<p>Nhưng nhát dao chí mạng nhất đối với Chí Viễn lại đến từ người phụ nữ đứng phía sau họ. Phạm Thu Hà - người yêu gắn bó từ thời sinh viên nghèo khó của anh, nay diện chiếc váy hiệu ôm sát quyến rũ, tay ôm khư khư chiếc túi Hermès đắt tiền do Hùng mua tặng. Ánh mắt cô ta nhìn anh không một chút dao động, chỉ có sự lạnh lùng tàn nhẫn của một kẻ đã chọn bán rẻ linh hồn để đổi lấy vinh hoa phú quý.</p>
<p>\"Viễn à, anh đừng trách tôi.\" Thu Hà lên tiếng, giọng cô ta thanh mảnh nhưng đầy thực dụng. \"Anh chỉ là một thằng nghiên cứu sinh lấm bùn đất, lương tháng ba cọc ba đồng thì lấy gì nuôi nổi ước mơ của tôi? Chiếc đĩa cứng chứa toàn bộ công thức lai tạo và mật khẩu hệ thống phân tích sắc ký của anh, tôi đã giao lại cho Viện trưởng Hùng rồi. Hợp đồng chuyển nhượng công nghệ cho AgroTech trị giá một trăm tỷ đồng cũng đã được ký kết chính thức. Anh nên chấp nhận thất bại đi.\"</p>
<p>Trần Minh Hải cười khẩy đầy kiêu ngạo, gã bước tới gần Chí Viễn, nâng ly rượu vang đỏ trên tay lên rồi thản nhiên đổ thẳng dòng chất lỏng đỏ thẫm xuống đôi ủng cao su lấm lem bùn đất của Chí Viễn. \"Một thằng kỹ sư quèn, tài khoản Agribank vừa bị phong tỏa vì nghi án biển thủ công quỹ nghiên cứu như mày thì có tư cách gì đòi nói chuyện sở hữu trí tuệ với chúng tao? Kể từ ngày mai, tên của mày sẽ bị xóa sạch khỏi trang web của Viện. Mày đã bị cấm hành nghề nông nghiệp công nghệ cao trên toàn quốc. Cút đi!\"</p>
<p>Chí Viễn khẽ hít một hơi sâu, lồng ngực rộng hơi phập phồng dưới lớp áo bảo hộ màu xanh sờn cũ. Gương mặt góc cạnh của anh không hề lộ ra một chút giận dữ hay hoảng loạn nào. Anh lặng lẽ thu dọn cuốn sổ tay ghi chép thực nghiệm thực địa sờn gáy cùng bộ kim châm cứu bằng bạc gia truyền vào chiếc ba lô cũ. Khi bước đến cửa phòng, anh khẽ dừng chân, quay đầu lại nhìn ba kẻ phản diện đang đắc ý tột độ.</p>
<p>\"Các người thực sự nghĩ rằng, chỉ cần nắm giữ đĩa backup chứa công thức định lượng là có thể nhân giống thành công thế hệ F3 của giống lúa Hoàng Kim Hương sao?\" Chí Viễn khẽ nhếch môi, giọng nói phẳng lặng như băng lạnh. \"Chúc các người may mắn với lô gieo cấy thử nghiệm đầu tiên.\"</p>
<p>Dứt lời, anh sải bước thẳng ra ngoài màn mưa giông trắng xóa, bỏ lại sau lưng những tiếng cười ngạo mạn vang vọng khắp hành lang tòa nhà nghiên cứu lạnh lẽo.</p>"""

    # Chapter 2
    ch2_title = "Chương 2: Kẻ Lấm Bùn Đất Thách Thức Livestream Truyền Thông Bẩn"
    ch2_content = """<p>Sau khi bị trục xuất khỏi Viện, Lâm Chí Viễn dọn về vùng đất ngập mặn An Giang, nơi ông nội anh để lại một trang trại lúa hữu cơ nhỏ hoang sơ tên là Kim Hương Đường. Chí Viễn thản nhiên sống như một người nông dân thực thụ, mặc áo bà ba sờn màu, đi ủng cao su, tự mình cuốc đất cải tạo nguồn nước mặn và âm thầm gieo cấy những hạt giống Hoàng Kim Hương nguyên bản cuối cùng mà anh cất giấu trong ba lô. Đồng thời, anh mở một gian chẩn trị y học cổ truyền miễn phí cho những người nông dân nghèo bị bệnh xương khớp và tiểu đường trong vùng.</p>
<p>Thế nhưng, thế lực gian thương quyết không buông tha cho anh. Vào một buổi chiều nắng gắt, tiếng gầm rú của chiếc xe bán tải Ford Ranger hầm hố dội thẳng vào không gian yên bình của Kim Hương Đường. Trần Minh Hải cùng Phạm Thu Hà bước xuống xe, đi theo họ là một ê-kíp truyền thông bẩn mang theo máy quay chuyên nghiệp và thiết bị phát sóng trực tiếp.</p>
<p>\"Chào mọi người trên sóng livestream trực tiếp của AgroTech!\" Trần Minh Hải lớn tiếng nói vào micro, camera lập tức hướng thẳng vào ngôi nhà lá đơn sơ của Chí Viễn. \"Hôm nay chúng tôi sẽ cho các bạn thấy bộ mặt thật của một kẻ lừa đảo khoa học, Lâm Chí Viễn! Kẻ bị sa thải vì hành vi phá hoại gen lúa quốc gia, nay lại trốn về đây để lừa lọc người dân nghèo, bán thứ gạo bẩn ngâm hóa chất độc hại gây ung thư dưới danh nghĩa gạo hữu cơ trị bệnh tiểu đường!\"</p>
<p>Phạm Thu Hà khoác tay Hải đầy tình tứ, cô ta liếc nhìn Chí Viễn bằng ánh mắt khinh miệt sâu sắc: \"Chí Viễn, nhìn anh bẩn thỉu thế này tôi lại càng thấy quyết định của mình là hoàn toàn đúng đắn. Một thằng nghèo kiết xác như anh cả đời này cũng chỉ xứng đáng làm bạn với bùn đất và phân bón mà thôi!\"</p>
<p>Hàng ngàn lượt bình luận ác ý đổ dồn trên sóng livestream dưới sự định hướng của đội ngũ truyền thông bẩn. Giữa lúc Trần Minh Hải đang hả hê vì sắp dập tắt hoàn toàn danh tiếng của Chí Viễn, đột nhiên cụ Tư - một lão nông nghèo đang đợi bốc thuốc ở hiên nhà - đổ gục xuống đất co giật dữ dội.</p>
<p>Sắc mặt cụ Tư lập tức xám ngoét không còn một giọt máu, mồ hôi lạnh chảy ròng ròng ướt sũng chiếc áo cánh nâu sờn, hơi thở đứt quãng vô cùng yếu ớt, hai tay cụ bấu chặt lấy lồng ngực co quắp đau đớn. Triệu chứng của cơn nhồi máu cơ tim cấp do biến chứng tiểu đường lâu năm vô cùng nguy kịch, đe dọa tính mạng chỉ trong vài phút ngắn ngủi.</p>
<p>\"Tránh ra! Để đoàn y tế của AgroTech gọi cấp cứu!\" Trần Minh Hải hoảng hốt quát lớn, cố tình dùng vụ này trên livestream để làm nổi bật thương hiệu. Nhưng gã và đám nhân viên chỉ biết đứng nhìn loay hoay, không ai dám chạm vào cơ thể đang co giật của cụ Tư vì sợ chịu trách nhiệm.</p>
<p>Chí Viễn không nói một lời, anh lập tức bước tới, đặt cụ Tư nằm thẳng trên chiếc chõng tre. Đôi mắt anh sắc sảo như chim ưng, đôi bàn tay chai sần nhanh nhẹn châm sâu ba cây kim bạc gia truyền vào huyệt Nội Quan, huyệt Cực Tuyền và huyệt Nhân Trung của cụ Tư. Mười ngón tay anh vê kim nhanh như chớp, truyền dòng sinh khí ổn định huyết động học. Đồng thời, anh lấy ra một chén nước sắc màu vàng óng từ lớp vỏ trấu lúa Hoàng Kim Hương nguyên chất kết hợp cùng sâm đất Nam Bộ, nhẹ nhàng đổ vào miệng cụ Tư.</p>
<p>Chỉ sau đúng năm phút nghẹt thở, nhịp thở của cụ Tư dần trở nên sâu và đều đặn, sắc mặt hồng hào trở lại, mồ hôi lạnh ngừng chảy và cụ từ từ mở mắt, cất tiếng thều thào: \"Tôi... tôi đỡ đau ngực rồi. Cảm ơn bác sĩ Viễn cứu mạng...\"</p>
<p>Hàng vạn người xem trên sóng livestream lập tức bùng nổ những bình luận thán phục và kinh ngạc trước y thuật thần kỳ của Chí Viễn. Chiêu trò bôi nhọ của Trần Minh Hải hoàn toàn bị phản tác dụng. Khuôn mặt gã giám đốc và Phạm Thu Hà xám ngoét, vội vã ra lệnh tắt máy quay và rút lui trong sự nhục nhã ê chề trước sự giận dữ của người dân địa phương.</p>"""

    # Chapter 3
    ch3_title = "Chương 3: Biến Cố Hào Môn Và Chén Dược Chất Từ Vỏ Trấu Sâm"
    ch3_content = """<p>Sau màn lật kèo chấn động ngay trên sóng livestream, uy tín của Lâm Chí Viễn tại vùng đất An Giang tăng lên như diều gặp gió. Thế nhưng anh vẫn giữ lối sống giản dị, tĩnh lặng nghiên cứu và bốc thuốc tại Kim Hương Đường. Anh biết rằng những kẻ phản bội sẽ không dừng lại ở đó khi đợt IPO trăm tỷ của AgroTech đang cận kề.</p>
<p>Vào một buổi sáng sương mù giăng lối trên sông Hậu, một chiếc xe siêu sang Mercedes-Maybach màu đen bóng lộn từ từ tiến vào con đường đất gồ ghề của trang trại Kim Hương Đường. Sự xuất hiện của chiếc xe xa xỉ thu hút toàn bộ ánh nhìn tò mò của người dân xung quanh. Từ hàng ghế sau, một cô gái bước xuống, ngay lập tức khiến không gian hoang sơ xung quanh như bừng sáng.</p>
<p>Đó là Lê Hoài Thu - ái nữ kiên cường kiêm CEO quyền lực của quỹ đầu tư Thịnh Phát Agro-Fund. Cô mặc một bộ comple công sở màu xanh navy cắt may tinh xảo ôm sát thân hình mảnh mai quyến rũ, mái tóc đen dài buộc cao toát lên vẻ năng động, gương mặt cô mang một vẻ đẹp quý phái, sắc sảo nhưng cực kỳ lý tính. Đi sau cô là một đoàn chuyên gia sở hữu trí tuệ cùng hai kiểm toán viên độc lập của PwC.</p>
<p>Hoài Thu bước vào căn nhà lá đơn sơ, đôi mắt phượng sắc bén nhanh chóng quét qua không gian mộc mạc ngập tràn mùi thảo mộc. Cô không hề tỏ ra e ngại hay ghét bỏ trước sự nghèo nàn của trang trại, bước thẳng tới chiếc bàn gỗ cũ kỹ nơi Chí Viễn đang phân loại các mẫu hạt giống.</p>
<p>\"Chào anh, Lâm Chí Viễn.\" Giọng nói của Hoài Thu thanh mảnh, rõ ràng và tràn đầy phong thái của một nhà lãnh đạo lý tính tuyệt đối. \"Tôi là Lê Hoài Thu, CEO của Thịnh Phát Agro-Fund. Tôi không đến đây để gửi lời chia buồn về việc anh bị sa thải. Tôi đến để đề xuất một thương vụ đầu tư sòng phẳng trị giá 120 tỷ đồng.\"</p>
<p>Chí Viễn khẽ ngẩng đầu nhìn cô, ánh mắt anh phẳng lặng như nước hồ thu. \"Đề xuất đầu tư vào một kẻ bị đóng băng tài khoản và bị tước giấy phép nghiên cứu như tôi sao? Cô Lê không sợ mất trắng số tiền đó à?\"</p>
<p>Hoài Thu khẽ mỉm cười, một nụ cười nhạt nhưng cực kỳ tự tin. \"Tôi đã âm thầm nghiên cứu công trình lai tạo giống lúa Hoàng Kim Hương của anh suốt ba năm qua qua các bài báo khoa học quốc tế. Ông nội tôi - Tỷ phú Lê Hoài Nam, người sáng lập tập đoàn Thịnh Phát - hiện đang bị chứng tiểu đường và biến chứng tim mạch nghiêm trọng do dùng gạo biến đổi gen chất lượng kém của AgroTech. Đội ngũ y bác sĩ hàng đầu của chúng tôi đều khẳng định nghiên cứu của anh là hy vọng duy nhất để cứu sống ông.\"</p>
<p>Cô khẽ ra hiệu, vị chuyên gia pháp lý của PwC bước lên, đặt lên bàn một tập hồ sơ dày cộp đóng dấu bảo mật. \"Chúng tôi không làm việc dựa trên niềm tin hay lòng thương hại. Đây là báo cáo thẩm định năng lực pháp lý và đánh giá tiềm năng thị trường của giống lúa Hoàng Kim Hương do PwC thực hiện trong hai tuần qua. Chúng tôi cam kết rót vốn 120 tỷ đồng để thành lập Trung tâm Nông nghiệp Sinh học mới, phát triển dòng gạo đặc trị tiểu đường đạt chuẩn quốc tế. Anh sẽ nắm giữ 70% cổ phần sáng chế độc quyền, chúng tôi nắm giữ 30% cổ phần vận hành thương mại.\"</p>
<p>Chí Viễn nhìn tập hồ sơ dày cộp trên bàn. Sự chuyên nghiệp, rõ ràng và thái độ sòng phẳng của Hoài Thu khiến anh thực sự ấn tượng. Cô không giống như những kẻ hào môn kiêu ngạo khác, cô tôn trọng trí tuệ và giá trị chất xám của anh một cách tuyệt đối.</p>
<p>\"Tôi rất trân trọng sự chuyên nghiệp của cô Lê.\" Chí Viễn thản nhiên nói. \"Nhưng trước khi ký hợp đồng, tôi cần cô chứng kiến một thứ.\"</p>
<p>\"Thứ gì?\" Hoài Thu khẽ nhướng đôi lông mày thanh tú.</p>
<p>\"Bằng chứng cốt lõi chứng minh quyền sở hữu trí tuệ tối cao của tôi đối với Hoàng Kim Hương, thứ mà ngay cả đĩa cứng bị cướp cũng không thể thay thế được.\" Chí Viễn khẽ đáp, ánh mắt anh ánh lên tia sáng kiên định.</p>"""

    # Chapter 4
    ch4_title = "Chương 4: Xét Nghiệm Tây Y: Kết Quả Lâm Sàng Kỳ Diệu"
    ch4_content = """<p>Lâm Chí Viễn dẫn Lê Hoài Thu và đoàn chuyên gia pháp lý của PwC vào căn phòng thí nghiệm thô sơ phía sau trang trại Kim Hương Đường. Tại đây, hoàn toàn không có các thiết bị thí nghiệm hiện đại trị giá triệu đô như ở Viện Nghiên cứu Nông nghiệp miền Nam. Chỉ có một chiếc máy tính để bàn cũ kỹ màu đen, nhưng được kết nối trực tiếp với một máy chủ Git cá nhân bảo mật cao được anh tự thiết lập riêng biệt.</p>
<p>\"Cô Lê, và các chuyên gia của PwC chắc chắn hiểu rõ tầm quan trọng của nhật ký commit Git gốc chứ?\" Chí Viễn khẽ cất tiếng, ngón tay anh gõ nhanh trên bàn phím, mở ra giao diện dòng lệnh của hệ thống Git.</p>
<p>Màn hình hiển thị hàng ngàn dòng nhật ký commit Git (Git commit logs) kéo dài suốt năm năm qua. Mỗi dòng commit đều đi kèm với một mã băm SHA-256 bất biến, ghi lại chính xác thời gian đến từng giây, từng thay đổi nhỏ nhất trong cấu trúc hóa học của giống lúa Hoàng Kim Hương, nồng độ dung môi chiết xuất và các kết quả phản ứng thực nghiệm quang phổ. Đặc biệt, tất cả các commit này đều được ký số bảo mật bằng khóa PGP cá nhân của Chí Viễn, được chứng thực và lưu trữ bất biến trên server Git cá nhân độc lập của anh trước khi Đoàn Thế Hùng nộp hồ sơ đăng ký bằng sáng chế chính thức.</p>
<p>Vị chuyên gia pháp lý sở hữu trí tuệ của PwC đeo kính cận dày cộp, cúi sát người vào màn hình máy tính. Ông ta tỉ mỉ kiểm tra từng chữ ký số, đối chiếu mã SHA-256 và thốt lên đầy kinh ngạc: \"Tuyệt vời! Đây là bằng chứng thép bất biến tuyệt đối trước pháp luật! Tất cả các mốc thời gian phát minh và cấu trúc phân tử đều được ghi nhận từ năm năm trước. Cho dù Đoàn Thế Hùng có cướp được đĩa backup hiện tại và nộp đơn đăng ký bản quyền mới, thì nhật ký commit Git gốc ký số PGP này sẽ lập tức chứng minh hắn chỉ là kẻ ăn cắp chất xám thô thiển!\"</p>
<p>Lê Hoài Thu nhìn màn hình máy tính, đôi mắt phượng ánh lên sự thán phục sâu sắc trước sự phòng bị khoa học và cẩn mật của Chí Viễn. Cô khẽ gật đầu, ra hiệu cho trợ lý chuẩn bị các điều khoản hợp tác chuyển khoản 120 tỷ đồng.</p>
<p>Sau khi đoàn chuyên gia pháp lý và kiểm toán viên PwC rời đi để hoàn tất các thủ tục giấy tờ, không gian trang trại chỉ còn lại Chí Viễn và Hoài Thu. Buổi chiều muộn của vùng sông nước miền Tây buông xuống nhanh chóng, làn khói sương mờ phủ nhẹ trên sông Hậu ngoài cửa sổ. Chí Viễn pha một ấm trà Shan Tuyết cổ thụ ấm áp, làn khói trà nghi ngút mang theo hương thơm thanh khiết xua tan cái lạnh giá của gió sông.</p>
<p>\"Anh thực sự là một người đàn ông thú vị, Chí Viễn.\" Hoài Thu nhẹ nhàng cầm tách trà nóng bằng hai bàn tay thon thả, ánh mắt cô nhìn anh có chút xao động, trút bỏ đi vẻ lạnh lùng sắc sảo thường ngày của một nữ CEO quyền lực. \"Thông thường, những người bị dồn vào chân tường, bị đóng băng tài khoản và bị bôi nhọ danh dự như anh sẽ hoảng loạn hoặc tìm cách trả thù điên cuồng. Nhưng anh lại cực kỳ điềm tĩnh, giống như mọi thứ đã nằm trong tầm kiểm soát của anh vậy.\"</p>
<p>Chí Viễn nhấp một ngụm trà đắng, ánh mắt anh nhìn ra cánh đồng lúa xanh mướt. \"Khi cô đã trải qua những ngày tháng lội bùn sâu ở vùng ngập mặn để tìm từng giống lúa hoang dại, đối mặt với những cơn giông rừng đổ ập và nguy cơ mất trắng toàn bộ công sức gieo cấy trong gang tấc, cô sẽ hiểu rằng lòng tham và sự phản bội của lòng người chỉ là những cơn gió thoảng qua. Khoa học nông nghiệp là để giúp người nông dân có cuộc sống ấm no, chứ không phải để tranh giành danh lợi. Tôi kiên trì bảo vệ giống lúa này không phải vì tiền bạc, mà vì tôi không muốn giống lúa Hoàng Kim Hương cứu mạng hàng vạn người tiểu đường nghèo bị biến thành công cụ trục lợi bất chính của những kẻ gian thương.\"</p>
<p>Hoài Thu im lặng lắng nghe, cô khẽ cúi đầu nhìn tách trà trong tay. Trái tim cô, vốn dĩ đã bị chai sạn và lạnh giá sau nhiều năm đấu trí trên thương trường khốc liệt, đột nhiên có một nhịp đập lạ lùng trước sự kiên định, y đức sáng ngời và bản lĩnh phi thường của người đàn ông trước mặt. Cô khẽ đưa bàn tay mềm mại chạm nhẹ vào tay Chí Viễn, giọng nói cô trở nên dịu dàng ấm áp lạ thường: \"Tôi cam kết với anh, Thịnh Phát Agro-Fund sẽ đứng bên cạnh anh đến cùng trong cuộc chiến này. Bất kể Đoàn Thế Hùng hay Trần Minh Hải có dùng thủ đoạn dơ bẩn gì, tôi cũng sẽ không để họ làm hại anh.\"</p>
<p>Cái chạm tay nhẹ nhàng giữa hai người giữa buổi chiều sương khói sông Hậu tuy ngắn ngủi nhưng cực kỳ ấm áp, đánh dấu một liên minh thép không thể phá vỡ giữa mỹ nhân hào môn lý tính và vị nhà khoa học nông nghiệp kiêm thần y kiệt xuất.</p>"""

    # Chapter 5
    ch5_title = "Chương 5: Hợp Đồng Trăm Tỷ Và Cái Gật Đầu Của Mỹ Nhân Lý Tính"
    ch5_content = """<p>Buổi tối hôm đó, cơn gió từ sông Hậu thổi vào trang trại Kim Hương Đường mang theo mùi phù sa mặn mòi và hương thơm ngào ngạt của những bông lúa Hoàng Kim Hương đang thì ngậm sữa. Dưới ánh trăng rằm vằng vặc chiếu sáng cả một khoảng sân rộng, Lê Hoài Thu cùng Lâm Chí Viễn ngồi bên chiếc bàn tre đơn sơ. Trước mặt họ là bản hợp đồng đầu tư trị giá 120 tỷ đồng đã được đóng dấu đỏ chói lọi của Thịnh Phát Agro-Fund.</p>
<p>\"Chí Viễn, đây là bản hợp đồng quan trọng nhất trong sự nghiệp đầu tư của tôi.\" Hoài Thu nhẹ nhàng đặt cây bút ký đắt tiền lên mặt bàn, ánh mắt cô nhìn anh chứa đựng sự nghiêm túc và lý tính tuyệt đối. \"Tôi đã kiểm tra kỹ lưỡng báo cáo gen di truyền của lúa Hoàng Kim Hương từ Viện Sinh học Phân tử Quốc gia. Dòng hoạt chất saponin đặc chủng và các amino acid quý trong hạt gạo của anh hoàn toàn vượt trội so với giống gạo đột biến của AgroTech. Đây là sự đầu tư sòng phẳng vào tài năng của anh, chứ không hề có một chút yếu tố cảm xúc nào ở đây cả.\"</p>
<p>Chí Viễn khẽ mỉm cười, anh cầm cây bút lên và đặt nét ký dứt khoát của mình bên cạnh chữ ký thanh mảnh của Hoài Thu. \"Sự lý tính của cô Lê chính là điều khiến tôi tin tưởng nhất. Một hợp đồng dựa trên giá trị thực tế của khoa học luôn bền vững hơn bất kỳ lời hứa hẹn sáo rỗng nào.\"</p>
<p>Sau khi hợp đồng được ký kết, Hoài Thu khẽ thở phào nhẹ nhõm, cô tựa lưng vào chiếc ghế tre, ánh mắt hướng lên vầng trăng sáng trên cao. Trong không gian yên tĩnh chỉ có tiếng côn trùng kêu rả rích, cô đột nhiên cất tiếng, giọng nói có phần trầm xuống, trút bỏ đi lớp vỏ bọc quyền lực thường ngày:</p>
<p>\"Anh có biết tại sao tôi lại kiên quyết bảo vệ nông nghiệp hữu cơ đến vậy không, Chí Viễn? Năm tôi mười tuổi, mẹ tôi qua đời vì biến chứng suy thận nặng do dùng phải những thực phẩm nông nghiệp ngậm đầy hóa chất độc hại của các tập đoàn gian thương. Kể từ ngày đó, tôi đã thề với lòng mình rằng khi lớn lên, tôi sẽ dùng toàn bộ nguồn lực tài chính của gia tộc để hỗ trợ những nhà khoa học chân chính như anh, tạo ra những nông sản sạch thực sự cứu mạng con người. Nhìn thấy anh kiên định chịu khổ giữa trang trại nghèo này, tôi như nhìn thấy hình ảnh của một người hùng thầm lặng bảo vệ sự sống.\"</p>
<p>Chí Viễn lặng nghe những lời tâm sự chân thành từ đáy lòng của nàng ái nữ hào môn. Anh khẽ xoay tách trà nóng, giọng nói trầm ấm đầy thấu hiểu: \"Nỗi đau trong quá khứ chính là động lực mạnh mẽ nhất để chúng ta tạo ra những giá trị tốt đẹp cho tương lai. Mẹ của cô trên cao chắc chắn sẽ rất tự hào về những gì cô đang làm hôm nay. Tôi hứa với cô, giống lúa Hoàng Kim Hương này sẽ là câu trả lời đanh thép nhất gửi tới những kẻ gian thương đã chà đạp lên sức khỏe của người dân.\"</p>
<p>Hoài Thu khẽ nghiêng đầu nhìn anh, dưới ánh trăng sáng, khuôn mặt góc cạnh, đôi mắt sâu thẳm đầy bản lĩnh của Chí Viễn khiến trái tim cô rung động mạnh mẽ. Cô khẽ đưa bàn tay mềm mại ra nắm lấy bàn tay chai sần ấm áp của anh. Chí Viễn khẽ siết nhẹ tay cô, một lời hứa thầm lặng nhưng kiên định như đá tảng giữa hai tâm hồn kiệt xuất đã được thiết lập dưới sự chứng giám của vầng trăng rằm miền Tây sông nước.</p>"""

    # Chapter 6
    ch6_title = "Chương 6: Đòn Độc Phong Tỏa Và Bế Tắc Hai Mươi Bốn Giờ Vây Hãm"
    ch6_content = """<p>Liên minh bẩn thỉu giữa Viện trưởng Đoàn Thế Hùng và giám đốc AgroTech Trần Minh Hải nhanh chóng phát hiện ra thương vụ đầu tư 120 tỷ đồng của Thịnh Phát Agro-Fund vào trang trại của Lâm Chí Viễn. Cảm nhận được mối đe dọa chí mạng đối với dự án IPO trăm tỷ đang cận kề, bọn chúng quyết định tung ra đòn triệt hạ tàn độc nhất hòng bóp chết công ty mới của Chí Viễn ngay từ trong trứng nước.</p>
<p>Vào một buổi sáng sớm, khi sương mù còn chưa tan trên sông Hậu, một đoàn kiểm tra liên ngành bất ngờ ập vào trang trại Kim Hương Đường. Dẫn đầu là một cán bộ thuế và quản lý thị trường đã bị Trần Minh Hải dùng tiền mua chuộc nặng ký.</p>
<p>\"Nhận được đơn tố cáo công ty Đông dược sinh học mới của các người có dấu hiệu trốn thuế, rửa tiền quốc tế và sử dụng nguồn vốn không rõ nguồn gốc.\" Gã cán bộ lạnh lùng công bố quyết định đóng dấu đỏ chói. \"Theo luật định, chúng tôi ra lệnh đóng băng tạm thời toàn bộ tài khoản Vietcombank của dự án liên doanh, đồng thời đình chỉ hoạt động thi công nhà xưởng chế biến lúa Hoàng Kim Hương tại An Giang trong vòng 24 giờ để phục vụ công tác thanh tra khẩn cấp.\"</p>
<p>Cùng lúc đó, trên sóng livestream của các nền tảng mạng xã hội lớn rầm rộ xuất hiện các đoạn video bôi nhọ Chí Viễn được Trần Minh Hải đầu tư hàng tỷ đồng quảng cáo. Bọn chúng thuê các KOLs lớn rêu rao rằng giống gạo Hoàng Kim Hương thực chất chứa dư lượng thuốc trừ sâu độc hại vượt ngưỡng 200 lần, đã khiến ba bệnh nhân tiểu đường tại Cần Thơ phải nhập viện cấp cứu trong tình trạng hôn mê sâu. Làn sóng tẩy chay bùng phát dữ dội, các đại lý phân phối gạo hữu cơ ban đầu hoảng sợ liên tục gọi điện đơn phương hủy hợp đồng với Kim Hương Đường.</p>
<p>Bế tắc và nhục nhã dồn dập ập đến. Tài khoản ngân hàng bị phong tỏa hoàn toàn, công trình nhà xưởng bị giăng băng keo niêm phong màu vàng lạnh lẽo, những người nông dân liên kết sản xuất với Chí Viễn hoang mang, vây quanh trang trại đòi rút vốn vì sợ hãi thông tin \"gạo độc\" trên mạng. Danh tiếng và sự nghiệp của Chí Viễn như bị dìm sâu xuống bùn lầy, không một xu dính túi, đối mặt với nguy cơ phá sản chỉ trong một đêm.</p>
<p>Trần Minh Hải cùng Phạm Thu Hà đi xe bán tải đến tận cổng trang trại bị niêm phong, gã giám đốc cười lớn đầy thỏa mãn: \"Lâm Chí Viễn ơi Lâm Chí Viễn! Mày thấy chưa? Đứng đối đầu với AgroTech và Viện Nghiên cứu Nông nghiệp thì kết cục của mày chỉ có thể là tan xương nát thịt thôi! Bây giờ đến cái nhà xưởng rách nát này cũng bị niêm phong rồi, mày chuẩn bị vào tù bóc lịch vì tội lừa đảo đi nhé!\"</p>
<p>Chí Viễn đứng lặng yên trước tấm biển niêm phong màu đỏ chói. Mồ hôi không chảy trên trán anh, sắc mặt anh vẫn điềm nhiên phẳng lặng như tờ, chỉ có đôi bàn tay khẽ đút vào túi quần, mười đầu ngón tay hơi siết chặt lại. Anh không hề nói một lời tranh cãi nào với hai kẻ phản diện đang vênh váo trước mặt.</p>
<p>Bởi vì anh biết, đây chính là lúc bọn chúng đang tự tay thắt chiếc thòng lọng quanh cổ mình. Lệnh đình chỉ 24 giờ chỉ là một thủ tục tạm thời, và toàn bộ dòng tiền của dự án đã được Lê Hoài Thu bảo lãnh thông qua một quỹ ủy thác bảo mật tại Singapore. Mọi bằng chứng về hành vi giả mạo kết quả xét nghiệm độc học của Trần Minh Hải đã được đội ngũ thám tử tư của Thịnh Phát ghi lại đầy đủ.</p>
<p>\"Cứ để chúng đắc ý thêm vài giờ nữa.\" Chí Viễn quay sang nói khẽ với Lê Hoài Thu dưới làn mưa phùn lạnh giá. \"Hội nghị IPO ngày mai tại khách sạn Rex chính là nơi chúng ta sẽ tiễn bọn chúng vào ngục tối vĩnh viễn.\"</p>"""

    # Chapter 7
    ch7_title = "Chương 7: Phiên IPO Định Mệnh Và Sự Xuất Hiện Của Sắc Lệnh C03"
    ch7_content = """<p>Đại sảnh lộng lẫy của khách sạn Rex tại trung tâm Sài Gòn vào ngày diễn ra hội nghị IPO của AgroTech Việt Nam vô cùng hoành tráng. Hàng trăm nhà đầu tư lớn, giới tinh anh tài chính cùng phóng viên các đài truyền hình lớn đổ về nườm nượp. Ánh đèn flash chớp liên tục, không khí náo nhiệt bao trùm cả hội trường lớn ngập tràn hoa tươi và rượu Champagne đắt giá.</p>
<p>Viện trưởng Đoàn Thế Hùng và giám đốc Trần Minh Hải mặc những bộ comple lịch lãm đắt tiền đứng ở vị trí trung tâm sảnh chính, vênh váo đón nhận những lời chúc tụng từ các đối tác. Bọn chúng chuẩn bị công bố dòng sản phẩm giống lúa \"Hoàng Kim Hương\" độc quyền với sự quảng bá rầm rộ là dòng giống đột phá mang lại lợi nhuận nghìn tỷ.</p>
<p>Thế nhưng, đằng sau lớp vỏ bọc hào nhoáng đó là một thực tế tàn nhẫn: vì tiết kiệm chi phí để tối đa hóa lợi nhuận chuẩn bị cho đợt IPO, Đoàn Thế Hùng đã lược bỏ đi các bước lai tạo thuần chủng phức tạp, thay thế bằng hạt giống biến đổi gen giá rẻ nhập lậu chứa dư lượng chất kích thích sinh trưởng độc hại vượt ngưỡng cho phép gấp nhiều lần.</p>
<p>Khi Lâm Chí Viễn trong bộ trang phục giản dị bước vào hàng ghế cuối của hội trường lớn, Đoàn Thế Hùng ngay lập tức nhìn thấy anh. Hắn vênh mặt, lớn tiếng châm chọc ngay trước ống kính của hàng chục phóng viên:</p>
<p>\"Mọi người nhìn xem, đây chẳng phải là Lâm Chí Viễn, gã cựu nhân viên bị sa thải vì hành vi phá hoại gen lúa của Viện Nghiên cứu chúng tôi sao? Hôm nay cậu cũng dám vác mặt đến đây để học hỏi nghiên cứu đỉnh cao của tôi à? Một kẻ bán gạo dạo bị niêm phong nhà xưởng như cậu, có lẽ cả đời này chỉ xứng đáng đứng ở góc tối nhìn chúng tôi bước lên đỉnh cao vinh quang thôi!\"</p>
<p>Phạm Thu Hà đứng bên cạnh Trần Minh Hải khẽ cười khẩy đầy kiêu ngạo, ánh mắt cô ta nhìn Chí Viễn tràn ngập sự khinh miệt và đắc ý tột đỉnh. Trần Minh Hải ghé sát tai Chí Viễn, thì thầm bằng chất giọng tàn nhẫn đầy đe dọa: \"Hôm nay sau khi AgroTech chính thức IPO, tao sẽ dùng quyền lực của tập đoàn để tống mày vào tù vĩnh viễn vì tội bôi nhọ và bán gạo độc. Mày không còn đường sống ở đất Sài Gòn này đâu!\"</p>
<p>Chí Viễn vẫn đứng im lặng, sắc mặt anh phẳng lặng như tờ, không hề có một chút lo lắng hay sợ hãi nào lộ ra ngoài. Anh thản nhiên bước về hàng ghế cuối, lặng lẽ nhìn Đoàn Thế Hùng bước lên sân khấu lớn bắt đầu bài thuyết trình giới thiệu sản phẩm giả mạo.</p>
<p>Thế nhưng, ngay khi Đoàn Thế Hùng chuẩn bị bấm nút kích hoạt slide giới thiệu công thức lai tạo hạt giống trước toàn thể hội trường, cánh cửa lớn của sảnh tiệc đột ngột bị đẩy mạnh ra.</p>
<p>Lâm Chí Viễn dứt khoát bước vào, đi bên cạnh anh là Lê Hoài Thu trong chiếc đầm đen dạ hội quyến rũ cùng một đoàn luật sư cao cấp. Phía sau họ, chấn động hơn cả, là một đội cảnh sát kinh tế thuộc Cục Cảnh sát điều tra tội phạm về tham nhũng, kinh tế, buôn lậu (C03) trong sắc phục uy nghiêm, dẫn đầu là Thượng tá Nguyễn Minh kiểm soát giấy tờ điều tra.</p>
<p>\"Đề nghị dừng buổi lễ lại!\" Giọng nói đanh thép của Thượng tá Nguyễn Minh vang dội khắp cả hội trường rộng lớn, khiến toàn bộ âm nhạc lập tức bị tắt ngấm, hàng trăm khách mời sững sờ quay đầu nhìn lại.</p>
<p>\"Chúng tôi thuộc Cục C03 Bộ Công an, công bố lệnh bắt giữ khẩn cấp đối với Đoàn Thế Hùng - Viện trưởng Viện Nghiên cứu Nông nghiệp miền Nam - và Trần Minh Hải - Giám đốc AgroTech Việt Nam - về tội danh lạm dụng chức vụ quyền hạn, ăn cắp tài sản sở hữu trí tuệ quốc gia, falsify tài liệu nghiên cứu khoa học và sản xuất buôn bán hàng giả là hạt giống lúa ngậm hóa chất độc hại!\" Thượng tá Nguyễn Minh dõng dạc đọc sắc lệnh đóng dấu đỏ chói lọi trước sự bàng hoàng tột độ của hàng trăm nhà đầu tư.</p>"""

    # Chapter 8
    ch8_title = "Chương 8: Trả Giá Tàn Khốc Và Đóa Hoa Nở Rộ Giữa Bình Minh"
    ch8_content = """<p>Cả hội trường Rex Hotel lập tức rơi vào trạng thái náo loạn tột độ. Hàng trăm phóng viên báo chí đồng loạt hướng ống kính máy ảnh và máy quay về phía sân khấu, ánh chớp flash liên hồi như sấm chớp. Màn hình lớn của buổi lễ đột ngột thay đổi giao diện, hiển thị toàn bộ lịch sử Git commit logs gốc được ký số bảo mật PGP của Lâm Chí Viễn từ năm năm trước, đối chiếu trực tiếp với hồ sơ sở hữu trí tuệ giả mạo do Đoàn Thế Hùng nộp lên mới tuần trước.</p>
<p>Không dừng lại ở đó, màn hình tiếp tục phát ra đoạn video ẩn ghi lại cảnh Trần Minh Hải trực tiếp giao dịch hàng chục tỷ đồng hối lộ cho Đoàn Thế Hùng tại một phòng VIP khách sạn, cùng các bằng chứng từ Big 4 PwC chứng minh AgroTech đã sử dụng hạt giống lúa biến đổi gen nhập lậu chứa dư lượng chất kích thích độc hại tàn phá sức khỏe người tiêu dùng.</p>
<p>Trần Minh Hải sắc mặt hoàn toàn xám ngoét không còn một giọt máu, mồ hôi lạnh chảy ròng ròng ướt sũng cả bộ complet đắt tiền. Gã bủn rủn cả chân tay, đầu gối quỵ sụp xuống sàn gạch men lạnh lẽo của khách sạn. Trong cơn hoảng loạn tột cùng, gã vô tình quệt tay vào tháp ly rượu Champagne đặt bên cạnh, khiến cả tháp ly đổ ụp, vỡ tan tành thành hàng trăm mảnh thủy tinh sắc nhọn. Đôi bàn tay gã bấu chặt lấy những mảnh vỡ trên sàn, máu tươi rỉ ra nhuộm đỏ dòng rượu Champagne đắt tiền, gã bò lết dưới chân Lâm Chí Viễn lắp bắp van xin:</p>
<p>\"Chí Viễn... anh Viễn ơi... tôi lạy anh... là tôi bị che mắt bởi lòng tham... xin anh rút đơn tố cáo... AgroTech không thể sụp đổ được... tôi xin dâng toàn bộ tài sản cho anh...\"</p>
<p>Chí Viễn phẳng lặng nhìn gã gian thương đang thảm hại bò dưới chân mình, ánh mắt anh lạnh lẽo như băng tuyết ngàn năm, hoàn toàn không có một chút thương hại. Anh thản nhiên quay sang nhìn Phạm Thu Hà - người đang đứng run rẩy lẩy bẩy bên cạnh, khuôn mặt trang điểm đậm nay đã nhạt nhòa vì nước mắt sợ hãi, chiếc túi Hermès đắt tiền rơi xuống vũng rượu vỡ nát dưới sàn.</p>
<p>\"Thu Hà, cô đã chọn hào môn.\" Chí Viễn nhẹ nhàng nói, giọng nói phẳng lặng không một chút dao động. \"Vậy thì hãy chuẩn bị tinh thần chia sẻ cả những song sắt nhà tù với gã chồng sắp cưới giàu sang của cô đi.\"</p>
<p>Cảnh sát kinh tế lập tức ập lên sân khấu, còng tay Đoàn Thế Hùng và Trần Minh Hải trước sự chứng kiến của hàng triệu khán giả đang theo dõi truyền hình trực tiếp. Toàn bộ cổ phiếu chuẩn bị IPO của AgroTech lập tức bị hủy bỏ vĩnh viễn, đế chế nông nghiệp bẩn thâu tóm trăm tỷ sụp đổ tan tành như lâu đài cát chỉ trong vòng mười lăm phút ngắn ngủi.</p>
<p>Giữa đống đổ nát của kẻ thù, Lê Hoài Thu dứt khoát bước lên sân khấu bên cạnh Lâm Chí Viễn. Cô dõng dạc công bố trước toàn thể báo giới: \"Quỹ đầu tư Thịnh Phát Agro-Fund chính thức ký kết hợp đồng đầu tư 120 tỷ đồng vào Trung tâm Nông nghiệp Sinh học Kim Hương Đường của nhà khoa học Lâm Chí Viễn, chính thức đưa giống lúa đặc trị tiểu đường Hoàng Kim Hương ra thị trường toàn cầu!\"</p>
<p>Trong tiếng vỗ tay rầm rộ vang dội khắp cả hội trường, Hoài Thu quay sang nhìn Chí Viễn, đôi mắt phượng ngập tràn sự dịu dàng và ấm áp chưa từng có. Cô khẽ tựa đầu vào vai anh, Chí Viễn nhẹ nhàng nắm lấy bàn tay mềm mại của cô, mười ngón tay đan chặt vào nhau đầy kiên định. Ánh nắng bình minh của một ngày mới rực rỡ chiếu qua khung cửa kính lớn của khách sạn Rex, rọi sáng đóa hoa tình yêu và công lý đang nở rộ kiên cường giữa cuộc đời.</p>"""

    # Add chapters to novel data
    novel_data["chapters"].append({"title": ch1_title, "content": ch1_content})
    novel_data["chapters"].append({"title": ch2_title, "content": ch2_content})
    novel_data["chapters"].append({"title": ch3_title, "content": ch3_content})
    novel_data["chapters"].append({"title": ch4_title, "content": ch4_content})
    novel_data["chapters"].append({"title": ch5_title, "content": ch5_content})
    novel_data["chapters"].append({"title": ch6_title, "content": ch6_content})
    novel_data["chapters"].append({"title": ch7_title, "content": ch7_content})
    novel_data["chapters"].append({"title": ch8_title, "content": ch8_content})

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(novel_data, f, ensure_ascii=False, indent=2)

    print(f"✓ Successfully wrote draft to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()
