# -*- coding: utf-8 -*-
import json
import os
import urllib.parse
import urllib.request

OUTPUT_FILE = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_novel.json"
COVER_FILE = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_cover.png"

def main():
    print("🚀 Writing Sâm Ngọc Linh Webnovel using Golden V13 standards...")

    novel_data = {
        "title": "Thần Y Bị Sa Thải Vực Dậy Dòng Dược Chất Sâm Ngọc Linh Vả Mặt Sếp Cướp Bằng Sáng Chế Nghìn Tỷ",
        "author": "Trương Hoàng Kỳ",
        "genre": "Sảng Văn",
        "intro": "<p><strong>\"Cậu đã bị sa thải khỏi Viện Nghiên cứu Dược liệu Trung ương. Toàn bộ công trình nghiên cứu về hoạt chất MR2 của sâm Ngọc Linh hoang dã mà cậu cống hiến sáu năm qua sẽ thuộc về Viện, từ ngày mai cậu không còn tư cách bước vào đây nữa!\"</strong></p>\n<p>Trương Thế Hoàng, một chuyên gia sinh học phân tử và bác sĩ y học cổ truyền trẻ tuổi kiệt xuất, bỗng dưng bị sếp cũ Lê Khắc Tiệp vu oan hủy hoại mẫu vật thí nghiệm quý giá để đuổi việc anh, cướp đoạt bằng sáng chế dòng dược chất saponin MR2 đặc trị xơ vữa động mạch và phòng đột quỵ. Thậm chí, người yêu cũ của anh là Tạ Mỹ Linh còn phản bội, mang đĩa chứa mật khẩu backup nghiên cứu của anh dâng cho Lê Khắc Tiệp để kết hôn với thiếu gia Hoàng Gia Bảo.</p>\n<p>Giữa lúc bị dồn vào chân tường, tài khoản Agribank bị phong tỏa, phòng khám Đông y nhỏ bị đình chỉ thanh tra 24h, Thế Hoàng đã gặp Trịnh Tuyết Mai - đại tiểu thư kiêm CEO cực kỳ lý tính của Healthcare Minh Anh. Với sự giúp đỡ của Tuyết Mai và một chiến dịch kiểm toán sở hữu trí tuệ gắt gao của PwC cùng dấu vết Git gốc bất biến, Thế Hoàng đã thực hiện màn lật kèo ngoạn mục ngay tại Hội nghị Y học Quốc tế Hà Nội, phơi bày tội ác sản xuất thuốc giả của những kẻ phản bội trước cơ quan điều tra C03, khiến kẻ thù phải quỳ gối xin lỗi trong vô vọng.</p>",
        "cover_prompt": "A highly premium anime style, 1:1, luxurious illustration. A handsome 30-year-old Vietnamese traditional doctor in a modern sterile laboratory combined with elegant dark wood medicine shelves, holding a glowing green flask with sâm Ngọc Linh roots inside. Beside him stands a beautiful, sophisticated 28-year-old Vietnamese female CEO in a smart business blazer. Behind them are advanced medical analytics screens showing red cell vascular blood flows and chemical chromatography graphs. Beautiful cinematic warm lighting, detailed accents, no text.",
        "chapters": []
    }

    # Chapter 1
    ch1_title = "Chương 1: Đuổi Việc Lạnh Lùng và Sự Phản Bội Tàn Nhẫn"
    ch1_content = """<p>Tờ quyết định sa thải đóng dấu đỏ chói lọi được đặt lạnh lùng trên chiếc bàn làm việc gỗ sờn của Trương Thế Hoàng vào một buổi sáng mùa đông Hà Nội xám xịt. Không gian phòng nghiên cứu sinh học phân tử thuộc Viện Nghiên cứu Dược liệu Trung ương vốn dĩ yên tĩnh, nay lại càng bao trùm một bầu không khí ngột ngạt đến đông cứng. Hoàng đứng lặng lẽ, mười đầu ngón tay hơi siết chặt lại, ánh mắt anh phẳng lặng nhìn vào hàng chữ in đậm đen ngòm: \"Căn cứ biên bản kỷ luật số 14/KL-VDL, sa thải bác sĩ Trương Thế Hoàng vì hành vi cố ý hủy hoại mẫu vật sâm Ngọc Linh hoang dã 50 năm tuổi của Viện\".</p>
<p>Một lời vu cáo trắng trợn được sắp đặt tỉ mỉ đến từng chi tiết. Kẻ đứng đằng sau không ai khác ngoài Viện trưởng Lê Khắc Tiệp - một kẻ bất tài nhưng đầy tham vọng, người luôn muốn sở hữu dòng hoạt chất saponin quý hiếm MR2 đặc trị xơ vữa động mạch và phòng ngừa đột quỵ mà Hoàng đã cống hiến sáu năm ròng rã để chiết xuất và hoàn thiện.</p>
<p>\"Mày có nhìn kỹ tờ quyết định sa thải chưa, Hoàng?\" Giọng nói chói tai vang lên từ cửa phòng. Tiến sĩ Lê Khắc Tiệp bước vào, mái tóc chải chuốt bóng loáng dính keo, mặc bộ complet đắt tiền nhưng toát lên vẻ hách dịch. Đứng bên cạnh hắn là thiếu gia Hoàng Gia Bảo - chủ tịch tập đoàn phân phối thiết bị y tế y khoa miền Bắc, kẻ đang đầu tư tài chính cho dự án \"Hoạt Huyết Thần Đan\" của viện nhằm chuẩn bị cho đợt IPO nghìn tỷ trên sàn chứng khoán.</p>
<p>Và người đứng lùi lại phía sau, tay ôm khư khư chiếc túi hiệu đắt tiền mới toanh, chính là Tạ Mỹ Linh - người yêu cũ suốt năm năm qua của Hoàng. Ánh mắt cô ta nhìn anh giờ đây không có lấy một chút áy náy hay tội lỗi, chỉ có sự lạnh lùng tàn nhẫn của một người phụ nữ thực dụng đã quyết định bán đứng anh để bước chân vào hào môn.</p>
<p>\"Thế Hoàng, anh đừng trách tôi tàn nhẫn.\" Tạ Mỹ Linh cất tiếng, giọng nói cao ngạo nhưng có phần run rẩy trước phong thái bình thản đến đáng sợ của anh. \"Anh chỉ là một thằng nghiên cứu sinh quèn, cả đời cắm đầu vào đống rễ cây bùn đất thì làm sao mang lại cho tôi cuộc sống xa hoa được? Chiếc đĩa chứa mật khẩu backup nghiên cứu hoạt chất MR2 của anh, tôi đã chủ động giao lại cho Viện trưởng Tiệp rồi. Anh nên chấp nhận thực tế đi.\"</p>
<p>Hoàng Gia Bảo cười khẩy, hắn bước tới gần, trực tiếp nhổ một bãi nước bọt xuống sàn gạch men ngay dưới chân Hoàng. \"Nghiên cứu rác rưởi của mày từ nay đã mang tên của Tiến sĩ Lê Khắc Tiệp rồi. Một thằng nghèo hèn bị tước giấy phép hành nghề y tế, tài khoản ngân hàng Agribank bị đóng băng tạm thời vì nghi án tham ô quỹ nghiên cứu như mày, có tư cách gì đòi nói chuyện bản quyền với chúng tao? Cút đi!\"</p>
<p>Khải không hề nổi giận, cũng không gào thét hay phân bua. Anh khẽ hít một hơi sâu, lồng ngực rộng hơi phập phồng, ánh mắt đen láy như mặt hồ mùa đông lặng lẽ lướt qua ba gương mặt đang lộ rõ vẻ đắc ý trước mặt anh. Điện thoại trong túi quần anh bất chợt rung lên bần bật, tin nhắn từ tổng đài Agribank thông báo tài khoản cá nhân của anh tạm thời bị phong tỏa theo lệnh yêu cầu khẩn cấp từ cơ quan điều tra do Lê Khắc Tiệp ký đơn tố cáo.</p>
<p>\"Các người thực sự nghĩ rằng, chỉ cần lấy được mật khẩu đĩa sao lưu là có thể bào chế thành công dòng hoạt chất saponin MR2 sao?\" Hoàng cất giọng, âm lượng phẳng lặng như băng, không chứa đựng một chút dao động cảm xúc nào.</p>
<p>\"Ha ha! Mày không cần phải dọa khỉ.\" Lê Khắc Tiệp vênh mặt cười lớn. \"Mọi công thức định lượng, quy trình phản ứng sắc ký, nồng độ dung môi đều nằm trong đĩa backup kia rồi. Ngày mai, tập đoàn của thiếu gia Bảo sẽ chính thức sản xuất thử nghiệm lô đầu tiên của Hoạt Huyết Thần Đan. Còn mày, ngay lập tức thu dọn đồ đạc rác rưởi của mày và biến ra khỏi Viện Nghiên cứu này!\"</p>
<p>Hoàng khẽ gật đầu, anh từ tốn thu dọn vài cuốn sổ tay nghiên cứu cũ kỹ cùng bộ kim châm cứu gia truyền của dòng họ Trương vào chiếc ba lô bạc màu. Trước khi bước ra ngoài cửa kính lớn của viện nghiên cứu, anh quay lại nhìn Lê Khắc Tiệp, khóe miệng khẽ nhếch lên thành một nụ cười ẩn ý, lạnh lẽo đến thấu xương.</p>
<p>\"Chúc các người may mắn với lô sản xuất thử nghiệm.\" Hoàng nói nhẹ tênh rồi sải bước thẳng ra phía cơn mưa sương muối mù mịt của Hà Nội, để lại ba kẻ phản diện đứng ngơ ngác giữa phòng lab lạnh giá.</p>"""

    # Chapter 2
    ch2_title = "Chương 2: Phòng Khám Nghèo Ngõ Nhỏ Và Màn Thách Thức Livestream"
    ch2_content = """<p>Sau khi bị trục xuất khỏi Viện Nghiên cứu Dược liệu, Trương Thế Hoàng dọn về căn nhà cấp bốn cũ kỹ của ông nội nằm sâu trong con ngõ Quỳnh chật hẹp ở quận Hai Bà Trưng. Anh treo một tấm biển gỗ nhỏ sờn rách ghi ba chữ đơn giản: \"Tĩnh Tâm Đường\". Căn phòng chẩn trị Đông y nhỏ bé chỉ có một chiếc giường tre châm cứu, một chiếc tủ gỗ đựng hơn năm mươi ngăn thảo dược sực mùi hương quế, nhân sâm và cam thảo. Thế Hoàng tĩnh lặng sống qua ngày, tự mình bốc thuốc cứu giúp những người dân nghèo trong ngõ mà không lấy một đồng tiền công.</p>
<p>Thế nhưng, những kẻ phản bội quyết không để anh yên ổn. Vào một buổi chiều sương mù lạnh lẽo, một chiếc xe bán tải màu đỏ hầm hố rú ga ầm ĩ chắn ngang lối vào con ngõ nhỏ. Hoàng Gia Bảo cùng Tạ Mỹ Linh bước xuống, đi sau bọn họ là hai gã quay phim mang theo thiết bị livestream chuyên nghiệp cùng một ê-kíp truyền thông bẩn.</p>
<p>\"Chào bác sĩ Trương Thế Hoàng, kẻ lừa đảo bị đuổi việc!\" Hoàng Gia Bảo lớn tiếng, gã dí thẳng chiếc điện thoại đang phát livestream trực tiếp có hơn mười vạn người xem vào mặt Hoàng. \"Mọi người nhìn xem, đây chính là căn phòng khám rác rưởi của một kẻ chuyên bán thuốc độc vô danh, suýt chút nữa đã giết chết bệnh nhân ở Viện Dược liệu Trung ương! Mày trốn ở cái xó xỉnh này để tiếp tục hại người nghèo à?\"</p>
<p>Tạ Mỹ Linh đứng bên cạnh khịt mũi khinh bỉ, cô ta dùng gót giày cao gót nhọn hoắt dẫm mạnh lên một bao tải dược liệu sâm Ngọc Linh lọc thô đặt trước hiên nhà, khiến những cọng rễ khô vỡ vụn dưới gót giày. \"Thế Hoàng, nhìn anh thảm hại như thế này tôi lại càng thấy quyết định bỏ rơi anh là hoàn toàn đúng đắn. Một kẻ nghèo hèn bán thuốc dạo lếch thếch thế này cả đời cũng không ngẩng đầu lên nổi đâu!\"</p>
<p>Giữa lúc đám đông hiếu kỳ vây quanh ngõ nhỏ bắt đầu xầm xì bàn tán và chỉ trích Thế Hoàng theo luồng dư luận trên livestream, đột nhiên từ đầu ngõ vang lên một tiếng hét thất thanh: \"Cứu tôi với! Bố tôi... bố tôi đột nhiên ngất xỉu rồi!\"</p>
<p>Một người đàn ông trung niên hớt hải cõng cụ Nguyễn Văn Nam - một cụ già nghèo neo đơn sống ở cuối ngõ - đang trong tình trạng nguy kịch. Sắc mặt cụ Nam xám ngoét không còn một giọt máu, mồ hôi lạnh chảy ròng ròng ướt sũng chiếc áo bông sờn rách, hai hàm răng nghiến chặt vào nhau, nhịp thở đứt quãng vô cùng yếu ớt, ngón tay cụ bấu chặt vào ngực trái co quắp đau đớn. Đây là triệu chứng của cơn co thắt mạch vành cấp tính dẫn đến thiếu máu cơ tim nghiêm trọng, huyết áp tăng vọt đe dọa trực tiếp đến tính mạng chỉ trong vài phút.</p>
<p>\"Mọi người tránh ra! Để đoàn y tế của chúng tôi gọi xe cấp cứu!\" Hoàng Gia Bảo quát lớn, cố tình dùng vụ việc này trên sóng livestream để thể hiện ta đây là người cứu nhân độ thế. Thế nhưng gã hoàn toàn không biết sơ cứu lâm sàng, chỉ biết đứng loay hoay chỉ trỏ.</p>
<p>Thế Hoàng không nói một lời, anh lập tức bước tới, đặt cụ Nam nằm thẳng trên chiếc giường tre của phòng khám. Đôi mắt anh sắc sảo như chim ưng, đôi bàn tay sần sùi chai sạn vô cùng nhanh nhẹn rút ra bộ châm cứu gia truyền. Anh khẽ vuốt dọc cánh tay cụ Nam, xác định chính xác huyệt Nội Quan ở cổ tay và huyệt Cực Tuyền dưới nách.</p>
<p>\"Mày định làm gì? Định dùng mấy cây kim rỉ sét này giết chết ông cụ ngay trên sóng trực tiếp của tao à?\" Hoàng Gia Bảo hét lên, camera hướng sát vào tay Thế Hoàng hòng chộp lấy sai sót của anh.</p>
<p>\"Im mồm!\" Thế Hoàng quát lớn một tiếng, uy lực từ giọng nói của anh khiến cả con ngõ lập tức im phăng phắc. Mười ngón tay anh cử động nhanh như chớp, kim châm đâm sâu vào huyệt Nội Quan, tiếp theo là huyệt Cực Tuyền và huyệt Nhân Trung dưới mũi cụ Nam. Anh khẽ vê kim, kích thích dòng sinh khí lưu thông. Đồng thời, anh rút từ trong tủ thuốc ra một viên đan dược màu đen tuyền tự chế từ tinh chất sâm đen Tây Bắc, nhẹ nhàng bóp miệng cụ Nam để thuốc tan dần dưới lưỡi.</p>
<p>Chỉ sau đúng năm phút nghẹt thở, một phép màu đã xảy ra ngay trước ống kính livestream. Sắc mặt xám ngoét của cụ Nam dần dần hồng hào trở lại, mồ hôi lạnh ngừng chảy, hàm răng khẽ giãn ra và cụ từ từ mở mắt, cất tiếng thở phào nhẹ nhõm: \"Tôi... tôi đỡ đau ngực rồi. Cảm ơn bác sĩ Hoàng...\"</p>
<p>Hàng vạn người xem trên sóng livestream lập tức bùng nổ những bình luận kinh ngạc và thán phục y thuật thần kỳ của Thế Hoàng. Màn kịch bôi nhọ của Hoàng Gia Bảo hoàn toàn bị phản tác dụng. Sắc mặt gã thiếu gia và Tạ Mỹ Linh xám ngoét, vội vàng ra lệnh tắt livestream và vội vã rút lui trong sự nhục nhã ê chề trước tiếng la ó tức giận của người dân ngõ Quỳnh.</p>"""

    # Chapter 3
    ch3_title = "Chương 3: Mỹ Nhân Hào Môn Xuất Hiện và Kiểm Toán Big 4"
    ch3_content = """<p>Sau sự kiện cứu sống cụ Nam ngay trên sóng livestream, tiếng vang về y đức và thần thuật châm cứu của Trương Thế Hoàng lan rộng khắp khu phố cổ. Thế nhưng anh vẫn giữ lối sống giản dị, tĩnh lặng châm cứu bốc thuốc trong phòng khám Tĩnh Tâm Đường chật hẹp. Anh biết rằng cuộc chiến thực sự chỉ mới bắt đầu.</p>
<p>Vào một buổi sáng nắng hanh vàng của mùa đông Hà Nội, một chiếc xe siêu sang Mercedes-Maybach màu đen bóng lộn từ từ tiến vào và đỗ ngay trước cổng ngõ Quỳnh. Sự xuất hiện của chiếc xe đắt giá thu hút toàn bộ ánh nhìn tò mò của người dân xung quanh. Từ hàng ghế sau, một cô gái bước xuống, ngay lập tức khiến toàn bộ không gian xung quanh như bừng sáng.</p>
<p>Đó là Trịnh Tuyết Mai - đại tiểu thư kiêm CEO quyền lực của Tập đoàn Dược phẩm y tế Healthcare Minh Anh. Cô mặc một bộ âu phục công sở màu xanh navy cắt may tinh xảo ôm sát thân hình mảnh mai quyến rũ, mái tóc đen dài gợn sóng xõa nhẹ trên bờ vai thon. Gương mặt cô mang một vẻ đẹp quý phái, lạnh lùng và cực kỳ lý tính. Đi theo sau cô không phải là vệ sĩ, mà là một đoàn chuyên gia pháp lý sở hữu trí tuệ cùng hai kiểm toán viên cao cấp mặc đồng phục lịch sự của PwC - một trong bốn công ty kiểm toán lớn nhất thế giới (Big 4).</p>
<p>Tuyết Mai bước vào phòng khám nhỏ của Thế Hoàng, đôi mắt phượng sắc sảo nhanh chóng quét qua không gian mộc mạc ngập tràn mùi thảo mộc. Cô không hề tỏ ra ghét bỏ hay ái ngại trước sự nghèo nàn của phòng khám, cô bước thẳng tới chiếc bàn gỗ cũ kỹ nơi Thế Hoàng đang ngồi viết đơn thuốc.</p>
<p>\"Chào bác sĩ Trương Thế Hoàng.\" Giọng nói của Tuyết Mai thanh mảnh, rõ ràng và toát lên phong thái của một nhà lãnh đạo lý tính tuyệt đối. \"Tôi là Trịnh Tuyết Mai, CEO của Healthcare Minh Anh. Tôi không đến đây để gửi lời chia buồn sáo rỗng về việc anh bị sa thải. Tôi đến để đề xuất một thương vụ đầu tư sòng phẳng trị giá 150 tỷ đồng.\"</p>
<p>Thế Hoàng khẽ ngẩng đầu nhìn cô, ánh mắt anh phẳng lặng như nước hồ thu. \"Đề xuất đầu tư vào một kẻ bị đóng băng tài khoản và bị tước giấy phép hành nghệ như tôi sao? Cô Trịnh không sợ mất trắng số tiền đó à?\"</p>
<p>Tuyết Mai khẽ mỉm cười, một nụ cười nhạt nhưng cực kỳ tự tin. \"Tôi đã âm thầm theo dõi công trình nghiên cứu hoạt chất saponin MR2 của anh suốt ba năm qua qua các bài báo khoa học quốc tế. Ông ngoại tôi - Tỷ phú Nguyễn Văn Thăng, chủ tịch tập đoàn Thăng Long - hiện đang bị chứng xơ vữa động mạch não nghiêm trọng, và toàn bộ đội ngũ y bác sĩ hàng đầu của chúng tôi đều khẳng định nghiên cứu của anh là hy vọng duy nhất để cứu sống ông.\"</p>
<p>Cô khẽ ra hiệu, vị kiểm toán viên PwC bước lên, đặt lên bàn một tập hồ sơ dày cộp đóng dấu bảo mật. \"Chúng tôi không làm việc dựa trên niềm tin hay lòng thương hại. Đây là báo cáo thẩm định năng lực pháp lý và đánh giá tiềm năng thị trường của dòng hoạt chất MR2 do PwC thực hiện trong hai tuần qua. Chúng tôi cam kết rót vốn 150 tỷ đồng để thành lập công ty Đông dược sinh học mới, phát triển sản phẩm特trị xơ vữa động mạch đạt chuẩn GMP quốc tế. Anh sẽ nắm giữ 70% cổ phần sáng chế độc quyền, chúng tôi nắm giữ 30% cổ phần vận hành thương mại.\"</p>
<p>Thế Hoàng nhìn tập hồ sơ dày cộp trên bàn. Sự chuyên nghiệp, rõ ràng và thái độ sòng phẳng của Tuyết Mai khiến anh thực sự ấn tượng. Cô không giống như những kẻ hào môn kiêu ngạo khác, cô tôn trọng trí tuệ và giá trị chất xám của anh một cách tuyệt đối.</p>
<p>\"Tôi rất trân trọng sự chuyên nghiệp của cô Trịnh.\" Thế Hoàng thản nhiên nói. \"Nhưng trước khi ký hợp đồng, tôi cần cô chứng kiến một thứ.\"</p>
<p>\"Thứ gì?\" Tuyết Mai khẽ nhướng đôi lông mày thanh tú.</p>
<p>\"Bằng chứng cốt lõi chứng minh quyền sở hữu trí tuệ tối cao của tôi đối với công thức MR2, thứ mà ngay cả đĩa backup bị cướp cũng không thể thay thế được.\" Thế Hoàng khẽ đáp, ánh mắt anh ánh lên tia sáng kiên định.</p>"""

    # Chapter 4
    ch4_title = "Chương 4: Thẩm Định Pháp Lý Sòng Phẳng và Phân Đoạn Tâm Sự Riêng Tư"
    ch4_content = """<p>Trương Thế Hoàng dẫn Trịnh Tuyết Mai và đoàn chuyên gia pháp lý vào căn phòng nhỏ phía sau phòng khám Tĩnh Tâm Đường. Tại đây, hoàn toàn không có các thiết bị thí nghiệm hiện đại trị giá triệu đô như ở Viện Dược liệu Trung ương. Chỉ có một chiếc máy tính để bàn cũ kỹ màu đen, nhưng được kết nối trực tiếp với một máy chủ Git cá nhân bảo mật cao được anh tự thiết lập riêng biệt.</p>
<p>\"Cô Trịnh, và các chuyên gia của PwC chắc chắn hiểu rõ tầm quan trọng của nhật ký commit Git gốc chứ?\" Thế Hoàng khẽ cất tiếng, ngón tay anh gõ nhanh trên bàn phím, mở ra giao diện dòng lệnh của hệ thống Git.</p>
<p>Màn hình hiển thị hàng ngàn dòng nhật ký commit Git (Git commit logs) kéo dài suốt ba năm qua. Mỗi dòng commit đều đi kèm với một mã băm SHA-256 bất biến, ghi lại chính xác thời gian đến từng giây, từng thay đổi nhỏ nhất trong cấu trúc hóa học của hoạt chất saponin MR2, nồng độ dung môi chiết xuất và các kết quả phản ứng thực nghiệm. Đặc biệt, tất cả các commit này đều được ký số bảo mật bằng khóa PGP cá nhân của Thế Hoàng, được chứng thực và lưu trữ bất biến trên server Git cá nhân độc lập của anh trước khi anh nộp hồ sơ đăng ký bằng sáng chế chính thức.</p>
<p>Vị chuyên gia pháp lý sở hữu trí tuệ của PwC đeo kính cận dày cộp, cúi sát người vào màn hình máy tính. Ông ta tỉ mỉ kiểm tra từng chữ ký số, đối chiếu mã SHA-256 và thốt lên đầy kinh ngạc: \"Tuyệt vời! Đây là bằng chứng thép bất biến tuyệt đối trước pháp luật! Tất cả các mốc thời gian phát minh và cấu trúc phân tử đều được ghi nhận từ ba năm trước. Cho dù Tiến sĩ Lê Khắc Tiệp có cướp được đĩa backup hiện tại và nộp đơn đăng ký bản quyền mới, thì nhật ký commit Git gốc ký số PGP này sẽ lập tức chứng minh hắn chỉ là kẻ ăn cắp chất xám thô thiển!\"</p>
<p>Trịnh Tuyết Mai nhìn màn hình máy tính, đôi mắt phượng ánh lên sự thán phục sâu sắc trước sự phòng bị khoa học và cẩn mật của Thế Hoàng. Cô khẽ gật đầu, ra hiệu cho trợ lý soạn thảo ngay hợp đồng hợp tác chính thức chuyển khoản 150 tỷ đồng.</p>
<p>Sau khi đoàn chuyên gia pháp lý và kiểm toán viên PwC rời đi để hoàn tất các thủ tục giấy tờ, không gian phòng khám nhỏ chỉ còn lại Thế Hoàng và Tuyết Mai. Buổi chiều muộn của Hà Nội buông xuống nhanh chóng, sương mù lạnh buốt phủ mờ những mái ngói rêu phong ngoài cửa sổ. Hoàng pha một ấm trà Shan Tuyết cổ thụ đỉnh Suối Giàng ấm áp, làn khói trà nghi ngút mang theo hương thơm thanh khiết xua tan cái lạnh giá của mùa đông.</p>
<p>\"Anh thực sự là một người đàn ông thú vị, Thế Hoàng.\" Tuyết Mai nhẹ nhàng cầm tách trà nóng bằng hai bàn tay thon thả, ánh mắt cô nhìn anh có chút xao động, trút bỏ đi vẻ lạnh lùng sắc sảo thường ngày của một nữ CEO quyền lực. \"Thông thường, những người bị dồn vào chân tường, bị đóng băng tài khoản và bị bôi nhọ danh dự như anh sẽ hoảng loạn hoặc tìm cách trả thù điên cuồng. Nhưng anh lại cực kỳ điềm tĩnh, giống như mọi thứ đã nằm trong tầm kiểm soát của anh vậy.\"</p>
<p>Thế Hoàng nhấp một ngụm trà đắng, ánh mắt anh nhìn ra xa xăm qua ô cửa kính nhỏ. \"Khi cô đã trải qua những ngày tháng lội bùn sâu trên núi Ngọc Linh để tìm từng củ sâm hoang dã, đối mặt với những cơn mưa rừng đổ ập và nguy cơ sạt lở đất trong gang tấc, cô sẽ hiểu rằng lòng tham và sự phản bội của lòng người chỉ là những cơn gió thoảng qua. Y thuật là để cứu người, chứ không phải để tranh giành danh lợi. Tôi kiên trì bảo vệ hoạt chất MR2 này không phải vì tiền bạc, mà vì tôi không muốn công sức sáu năm cứu sống hàng vạn người nghèo bị biến thành công cụ trục lợi bất chính của những kẻ gian thương.\"</p>
<p>Tuyết Mai im lặng lắng nghe, cô khẽ cúi đầu nhìn tách trà trong tay. Trái tim cô, vốn dĩ đã bị chai sạn và lạnh giá sau nhiều năm đấu trí trên thương trường khốc liệt, đột nhiên có một nhịp đập lạ lùng trước sự kiên định, y đức sáng ngời và bản lĩnh phi thường của người đàn ông trước mặt. Cô khẽ đưa bàn tay mềm mại chạm nhẹ vào tay Thế Hoàng, giọng nói cô trở nên dịu dàng ấm áp lạ thường: \"Tôi cam kết với anh, Healthcare Minh Anh sẽ đứng bên cạnh anh đến cùng trong cuộc chiến này. Bất kể Lê Khắc Tiệp hay Hoàng Gia Bảo có dùng thủ đoạn dơ bẩn gì, tôi cũng sẽ không để họ làm hại anh.\"</p>
<p>Cái chạm tay nhẹ nhàng giữa hai người giữa buổi chiều sương lạnh Hà Nội tuy ngắn ngủi nhưng cực kỳ ấm áp, đánh dấu một liên minh thép không thể phá vỡ giữa mỹ nhân hào môn lý tính và vị thần y ẩn dật kiệt xuất.</p>"""

    # Chapter 5
    ch5_title = "Chương 5: Bế Tắc Giữa Dòng: Đòn Độc Của Liên Minh Phản Diện"
    ch5_content = """<p>Liên minh bẩn thỉu giữa Viện trưởng Lê Khắc Tiệp và thiếu gia Hoàng Gia Bảo nhanh chóng phát hiện ra sự hợp tác ngầm giữa Healthcare Minh Anh và Trương Thế Hoàng. Nhận thấy nguy cơ sụp đổ của dự án IPO nghìn tỷ \"Hoạt Huyết Thần Đan\" nếu Thế Hoàng lật ngược thế cờ, bọn chúng quyết định tung ra những đòn hiểm độc nhất hòng triệt hạ anh hoàn toàn trước khi Hội nghị Y học Quốc tế Hà Nội diễn ra.</p>
<p>Vào một buổi sáng sớm, khi Thế Hoàng vừa mở cửa phòng khám Tĩnh Tâm Đường, một đoàn thanh tra liên ngành gồm đại diện Sở Y tế và Quản lý thị trường địa phương bất ngờ ập vào. Kẻ dẫn đầu là một cán bộ biến chất đã nhận hối lộ lớn từ Hoàng Gia Bảo.</p>
<p>\"Nhận được đơn tố cáo phòng khám Tĩnh Tâm Đường hoạt động không phép, tàng trữ dược liệu giả và bán thuốc chứa thạch arsenic độc hại gây suy thận cấp cho bệnh nhân.\" Gã cán bộ lạnh lùng công bố văn bản đóng dấu đỏ. \"Theo quy định pháp luật, chúng tôi ra lệnh đình chỉ hoạt động phòng khám trong vòng 24 giờ để tiến hành niêm phong, tịch thu toàn bộ dược liệu mẫu thí nghiệm để thanh tra khẩn cấp.\"</p>
<p>Cùng lúc đó, trên các trang mạng xã hội và các diễn đàn tin tức lớn rộ lên hàng loạt bài viết bôi nhọ Thế Hoàng rầm rộ. Hoàng Gia Bảo đã chi hàng tỷ đồng để thuê các KOLs lớn thực hiện các buổi livestream rêu rao rằng hoạt chất saponin MR2 của Thế Hoàng thực chất là độc chất nguy hiểm, đã có ba bệnh nhân dùng thuốc của anh bị suy thận cấp tính phải lọc máu khẩn cấp tại bệnh viện. Sự hoang mang bao trùm dư luận, các đối tác cung cấp bao bì và nguồn dược liệu thô ban đầu của Thế Hoàng hoảng sợ, vội vã đơn phương hủy bỏ hợp đồng để tránh bị vạ lây.</p>
<p>Nỗi nhục và bế tắc dồn dập ập đến. Tài khoản ngân hàng Agribank của Thế Hoàng tiếp tục bị đóng băng hoàn toàn, phòng khám bị niêm phong bằng băng keo vàng lạnh lẽo, người dân trong ngõ Quỳnh nhìn anh bằng ánh mắt ái ngại, xa lánh vì sợ hãi thông tin \"thuốc độc\" trên mạng xã hội. Anh lâm vào thế đơn độc, không tiền bạc, không phòng khám, danh dự bị chà đạp tàn nhẫn dưới chân bùn lầy.</p>
<p>Tạ Mỹ Linh đi cùng Hoàng Gia Bảo đến trước cửa phòng khám bị niêm phong, cô ta cười lớn đầy thỏa mãn: \"Thế Hoàng ơi là Thế Hoàng! Mày thấy chưa? Đứng đối đầu với Hoàng gia và Viện Dược liệu Trung ương thì kết cục của mày chỉ có thể là tan xương nát thịt thôi! Bây giờ đến cái phòng khám rách nát này cũng bị niêm phong rồi, mày chuẩn bị vào tù bóc lịch vì tội bán thuốc độc đi nhé!\"</p>
<p>Thế Hoàng đứng lặng yên trước tấm biển niêm phong màu đỏ chói. Mồ hôi không chảy trên trán anh, sắc mặt anh vẫn điềm nhiên phẳng lặng như tờ, chỉ có đôi bàn tay khẽ đút vào túi quần, mười đầu ngón tay hơi siết chặt lại. Anh không hề nói một lời tranh cãi nào với hai kẻ phản diện đang vênh váo trước mặt.</p>
<p>Bởi vì anh biết, Trịnh Tuyết Mai đã hoàn tất việc chuyển giao 150 tỷ đồng vốn đầu tư của Healthcare Minh Anh thông qua một tài khoản ủy thác bảo mật tại ngân hàng Vietcombank đứng tên công ty Đông dược sinh học mới thành lập, hoàn toàn nằm ngoài tầm kiểm soát của Lê Khắc Tiệp và Hoàng Gia Bảo. Đoàn luật sư của cô cũng đang âm thầm hoàn thiện các thủ tục pháp lý để phản kích.</p>
<p>\"Cứ để chúng đắc ý thêm vài ngày nữa.\" Thế Hoàng quay sang nói khẽ với Trịnh Tuyết Mai, người vừa bước đến đứng bên cạnh anh dưới cơn mưa phùn lạnh giá. \"Đỉnh cao của sự kiêu ngạo chính là bắt đầu của sự sụp đổ. Hội nghị Y học Quốc tế Hà Nội sắp tới sẽ là nơi bọn chúng phải trả giá đắt nhất.\"</p>
<p>Tuyết Mai siết chặt tay anh, ánh mắt cô ánh lên sự kiên định sắt đá. \"Đội kiểm toán của PwC đã hoàn tất việc xác minh nhật ký commit Git gốc của anh. Chúng tôi đã sẵn sàng cho màn lật kèo thế kỷ này rồi.\"</p>"""

    # Chapter 6
    ch6_title = "Chương 6: Hội Nghị Dược Liệu Quốc Tế Hà Nội và Bản Báo Cáo Giả Mạo"
    ch6_content = """<p>Trung tâm Hội nghị Quốc gia Hà Nội vào ngày diễn ra Hội nghị Y dược Quốc tế vô cùng hoành tráng và lộng lẫy. Hàng ngàn chuyên gia y học, các giáo sư đầu ngành cùng giới tinh anh tài chính và phóng viên báo chí trong và ngoài nước đổ về nườm nượp. Ánh đèn flash của máy ảnh chớp liên tục, không khí náo nhiệt bao trùm cả hội trường lớn.</p>
<p>Viện trưởng Lê Khắc Tiệp và thiếu gia Hoàng Gia Bảo mặc những bộ comple lịch lãm đắt tiền đứng ở vị trí trung tâm sảnh chính, vênh váo đón nhận những lời chúc tụng từ các đối tác lớn. Bọn chúng chuẩn bị công bố dòng sản phẩm \"Hoạt Huyết Thần Đan\" với sự quảng bá rầm rộ là dòng sản phẩm đột phá cứu mạng từ chiết xuất saponin sâm Ngọc Linh hoang dã.</p>
<p>Thế nhưng, đằng sau lớp vỏ bọc hào nhoáng đó là một thực tế tàn nhẫn: vì tiết kiệm chi phí sản xuất để tối đa hóa lợi nhuận chuẩn bị cho đợt IPO nghìn tỷ, Lê Khắc Tiệp đã lược bỏ đi dược chất sâm Ngọc Linh hoang dã đắt đỏ, thay thế bằng sâm trồng giá rẻ kém chất lượng và bỏ qua quy trình lọc tinh chất phân tử phức tạp. Dòng thuốc \"Hoạt Huyết Thần Đan\" của hắn thực chất là một sản phẩm bào chế lỗi, chứa dư lượng saponin loại độc hại và kim loại nặng chì vượt ngưỡng cho phép gấp nhiều lần.</p>
<p>Khi Trương Thế Hoàng trong bộ trang phục giản dị bước vào hàng ghế cuối của hội trường lớn, Lê Khắc Tiệp ngay lập tức nhìn thấy anh. Hắn vênh mặt, lớn tiếng châm chọc ngay trước ống kính của hàng chục phóng viên báo chí:</p>
<p>\"Mọi người nhìn xem, đây chẳng phải là Trương Thế Hoàng, gã cựu nhân viên bị sa thải vì hành vi phá hoại mẫu vật của Viện Nghiên cứu chúng tôi sao? Hôm nay cậu cũng dám vác mặt đến đây để học hỏi nghiên cứu đỉnh cao của tôi à? Một kẻ bán thuốc dạo bị niêm phong phòng khám như cậu, có lẽ cả đời này chỉ xứng đáng đứng ở góc tối nhìn chúng tôi bước lên đỉnh cao vinh quang thôi!\"</p>
<p>Tạ Mỹ Linh đứng bên cạnh Hoàng Gia Bảo khẽ cười khẩy đầy kiêu ngạo, ánh mắt cô ta nhìn Thế Hoàng tràn ngập sự khinh miệt và đắc ý tột đỉnh. Hoàng Gia Bảo ghé sát tai Thế Hoàng, thì thầm bằng chất giọng tàn nhẫn đầy đe dọa: \"Hôm nay sau khi Hoạt Huyết Thần Đan được công bố, tao sẽ dùng quyền lực của Hoàng gia để tống mày vào tù vĩnh viễn vì tội bôi nhọ và bán thuốc độc. Mày không còn đường sống ở đất Hà Nội này đâu!\"</p>
<p>Thế Hoàng vẫn đứng im lặng, sắc mặt anh phẳng lặng như tờ, không hề có một chút lo lắng hay sợ hãi nào lộ ra ngoài. Anh thản nhiên bước về hàng ghế cuối, lặng lẽ nhìn Lê Khắc Tiệp bước lên sân khấu lớn bắt đầu bài thuyết trình giới thiệu sản phẩm giả mạo.</p>
<p>Khi Lê Khắc Tiệp đang thao thao bất tuyệt trên sân khấu về \"sự kỳ diệu\" của sản phẩm Hoạt Huyết Thần Đan trước những tràng pháo tay giòn giã của cả hội trường, Trịnh Tuyết Mai trong chiếc đầm dạ hội màu đen quyến rũ từ từ bước vào, ngồi xuống chiếc ghế trống ngay bên cạnh Thế Hoàng. Cô khẽ mỉm cười, đưa cho anh chiếc USB chứa toàn bộ dữ liệu kiểm toán độc lập của PwC và lịch sử Git commit đã được chứng thực.</p>
<p>\"Kịch hay sắp bắt đầu rồi, Thế Hoàng.\" Tuyết Mai thì thầm, ánh mắt cô lạnh lùng hướng lên sân khấu lớn.</p>
<p>\"Đúng vậy.\" Thế Hoàng khẽ đáp, khóe miệng nhếch lên thành một nụ cười lạnh lẽo. \"Bọn chúng đã tự mình leo lên đài cao nhất, giờ là lúc thích hợp nhất để rơi xuống vực sâu.\"</p>"""

    # Chapter 7
    ch7_title = "Chương 7: Sinh Tử 15 Phút: Màn Giữ Mạng Chấn Động Đông Y"
    ch7_content = """<p>Giữa lúc không khí Hội nghị Y dược Quốc tế đang đạt đến đỉnh điểm của sự náo nhiệt sau bài thuyết trình của Lê Khắc Tiệp, đột nhiên một sự cố kinh hoàng xảy ra ngay tại hàng ghế VIP dành cho các nhà tài trợ danh dự.</p>
<p>Tỷ phú Nguyễn Văn Thăng - ông ngoại của Trịnh Tuyết Mai, người sáng lập tập đoàn tài chính Thăng Long hùng mạnh - đột ngột ngã gục xuống bàn. Sắc mặt ông cụ lập tức xám ngoét không còn một giọt máu, mồ hôi lạnh vã ra như tắm ướt sũng chiếc áo sơ mi lụa đắt tiền, miệng sủi bọt mép màu trắng đục, hai hàm răng nghiến chặt vào nhau phát ra những tiếng kêu kèn kẹt ghê người. Cơ thể ông cụ co giật liên hồi, nhịp thở đứt quãng vô cùng yếu ớt. Đây là triệu chứng của một cơn đột quỵ nhồi máu não cấp tính kèm xuất huyết não diện rộng vô cùng nguy kịch, đe dọa tính mạng chỉ trong vài phút ngắn ngủi.</p>
<p>\"Bác sĩ! Mau gọi bác sĩ cấp cứu!\" Trịnh Tuyết Mai hét lên trong sự hoảng loạn tột độ, cô vội vàng chạy lại ôm lấy cơ thể đang co giật của ông ngoại.</p>
<p>Lê Khắc Tiệp nhìn thấy cơ hội vàng để lập công lớn ngay trước hàng trăm phóng viên báo chí và giới tài phiệt. Hắn vội vàng chạy xuống sân khấu, tay cầm một viên thuốc màu đỏ tươi của sản phẩm \"Hoạt Huyết Thần Đan\" vừa mới thuyết trình.</p>
<p>\"Mọi người tránh ra! Tôi là Tiến sĩ Lê Khắc Tiệp, Viện trưởng Viện Dược liệu Trung ương!\" Hắn tự tin hét lớn. \"Viên Hoạt Huyết Thần Đan này chứa chiết xuất MR2 cực mạnh, có khả năng thông mạch và co bóp huyết quản ngay lập tức để cứu mạng cụ Thăng!\"</p>
<p>Bất chấp sự ngăn cản của một số bác sĩ Tây y có mặt tại hội trường, Lê Khắc Tiệp vội vã bóp miệng tỷ phú Nguyễn Văn Thăng và nhét viên thuốc vào, bắt ông cụ uống. Hắn vênh mặt tự đắc, nghĩ rằng chỉ cần cứu sống tỷ phú ngay tại đây, gã sẽ trở thành anh hùng y học và thương vụ IPO nghìn tỷ sẽ thành công vang dội.</p>
<p>Thế nhưng, chỉ đúng ba phút sau khi uống viên thuốc bào chế lỗi chứa đầy tạp chất kim loại nặng và dư lượng saponin độc hại của Tiệp, một cảnh tượng kinh hoàng đã xảy ra khiến toàn bộ hội trường hét lên kinh hãi.</p>
<p>Cơ thể tỷ phú Thăng đột ngột co giật mạnh hơn gấp bội, hai mắt trợn ngược lộ rõ lòng trắng, máu tươi đỏ thẫm bất ngờ trào ra từ khóe miệng và hai lỗ mũi của ông cụ. Máy đo nhịp tim cầm tay của bác sĩ riêng lập tức phát ra những tiếng bíp bíp liên hồi báo động đỏ: Nhịp tim từ 75 tụt dốc kinh hoàng xuống còn 32 nhịp/phút, huyết áp sụt nghiêm trọng xuống mức chạm đáy 55/35 mmHg, đồng tử hai bên giãn nở to ra hoàn toàn không còn phản xạ với ánh sáng. Cụ Thăng đã rơi vào trạng thái chết lâm sàng do huyết áp tụt dốc và xuất huyết não bùng phát dữ dội.</p>
<p>\"Tiệp! Mày đã cho ông ngoại tao uống cái gì thế này?\" Trịnh Tuyết Mai hét lên trong nước mắt phẫn nộ. Cô túm chặt lấy cổ áo Lê Khắc Tiệp gầm lên.</p>
<p>Lê Khắc Tiệp lúc này sắc mặt hoàn toàn xám ngoét không còn một giọt máu, mồ hôi lạnh chảy ròng ròng ướt sũng cả trán, đầu gối bủn rủn hoàn toàn không còn chút lực nào quỵ sụp xuống sàn gạch men lạnh lẽo. Hắn lắp bắp trong sự sợ hãi tột cùng: \"Không... không thể nào... Công thức rõ ràng là MR2... Sao lại có phản ứng nguy kịch như thế này được chứ...\"</p>
<p>\"Tránh ra!\"</p>
<p>Một giọng nói đanh thép, lạnh lùng như băng vang lên rẽ đôi đám đông đang hoảng loạn. Trương Thế Hoàng sải bước tiến tới, phong thái điềm tĩnh và uy nghiêm của anh lập tức khiến mọi người tự động dạt ra hai bên. Anh quỳ một gối xuống bên cạnh tỷ phú Thăng, mười ngón tay cử động nhanh như chớp rút ra bộ kim châm cứu gia truyền.</p>
<p>\"Mày định làm gì? Ông cụ đã chết lâm sàng rồi, mày định châm cứu giết người để đổ tội cho tao à?\" Hoàng Gia Bảo hét lên trong sự hoảng loạn, gã cố tình lao vào ngăn cản Thế Hoàng.</p>
<p>Thế Hoàng không thèm nhìn gã, anh dùng cùi chỏ huých mạnh một phát cực hiểm vào chấn thủy Hoàng Gia Bảo, khiến gã thiếu gia đau đớn ngã nhào ra đất, sắc mặt xám ngoét vì nghẹt thở. Hoàng lập tức châm sâu ba cây kim châm cứu vào ba huyệt vị chí mạng trên đỉnh đầu và trán tỷ phú Thăng: huyệt Nhân Trung, huyệt Thần Đình và huyệt Bách Hội. Mười ngón tay anh vê kim cực nhanh, truyền luồng khí ấm áp cô lập dòng máu chảy trong não cụ Thăng. Đồng thời, anh rút từ trong túi áo ra một lọ tinh chất \"Thần thông tán\" thật được bào chế từ sâm Ngọc Linh hoang dã nguyên chất 50 năm tuổi kết hợp thảo dược bí truyền, nhẹ nhàng nhỏ từng giọt tinh chất quý giá vào khóe miệng tỷ phú.</p>
<p>\"Thế Hoàng... cứu ông ngoại tôi với...\" Trịnh Tuyết Mai nắm chặt lấy gấu áo anh khóc nghẹn.</p>
<p>\"Hãy tin tôi.\" Thế Hoàng khẽ đáp, ánh mắt anh kiên định tuyệt đối. \"Tôi sẽ giữ mạng ông ngoại cô trong đúng 15 phút. Hãy lập tức chuẩn bị xe cấp cứu chuyển thẳng sang Bệnh viện Trung ương Quân đội 108!\"</p>
<p>Ngay sau khi những giọt tinh chất sâm Ngọc Linh của Thế Hoàng thấm vào lưỡi, máy đo nhịp tim bất ngờ phát ra tiếng bíp đều đặn trở lại: Nhịp tim từ 32 từ từ tăng lên và ổn định ở mức 65 nhịp/phút, huyết áp sụt nghiêm trọng từ 55/35 phục hồi thần kỳ về mức 110/70 mmHg, máu tươi ngừng chảy từ khóe mũi, đồng tử bắt đầu co lại và nhịp thở của tỷ phú Thăng dần trở nên sâu và đều đặn. Màn châm cứu giữ mạng chấn động Đông y của Thế Hoàng đã cứu sống tỷ phú Nguyễn Văn Thăng khỏi bàn tay tử thần ngay trong gang tấc trước sự ngỡ ngàng tột độ của hàng ngàn chuyên gia y học có mặt tại hội trường.</p>"""

    # Chapter 8
    ch8_title = "Chương 8: Xét Nghiệm Tây Y: Kết Quả Lâm Sàng Kỳ Diệu"
    ch8_content = """<p>Chiếc xe cấp cứu hú còi inh ỏi xé toang màn sương mù dày đặc của Hà Nội, đưa tỷ phú Nguyễn Văn Thăng chuyển thẳng vào phòng mổ khẩn cấp của Bệnh viện Trung ương Quân đội 108. Trịnh Tuyết Mai và Trương Thế Hoàng túc trực ngay bên ngoài hành lang phòng mổ, không khí vô cùng căng thẳng bao trùm. Lê Khắc Tiệp và Hoàng Gia Bảo cùng Tạ Mỹ Linh cũng vội vã bám theo sau, khuôn mặt bọn chúng xám ngoét không còn một giọt máu vì sợ hãi trách nhiệm pháp lý nếu tỷ phú có mệnh hệ gì.</p>
<p>Sau hai giờ đồng hồ căng thẳng nghẹt thở, cánh cửa phòng mổ lớn từ từ mở ra. Giáo sư Trần Minh Đức - trưởng khoa phẫu thuật thần kinh hàng đầu Việt Nam, người trực tiếp chỉ đạo kíp mổ - bước ra ngoài với khuôn mặt tràn đầy sự kinh ngạc và thán phục khó tin.</p>
<p>\"Ai... ai là người đã thực hiện sơ cứu châm cứu và cho bệnh nhân uống dược chất trước khi nhập viện?\" Giáo sư Đức lớn tiếng hỏi, giọng ông run lên vì xúc động.</p>
<p>Trịnh Tuyết Mai vội vàng bước lên: \"Thưa Giáo sư, là bác sĩ Trương Thế Hoàng đây ạ. Ông ngoại cháu hiện tại thế nào rồi ạ?\"</p>
<p>Giáo sư Đức lập tức bước tới nắm chặt lấy hai vai Thế Hoàng, đôi mắt ông rực sáng: \"Bác sĩ Hoàng! Cậu thực sự là một thiên tài Đông y! Chúng tôi vừa tiến hành chụp CT cản quang 640 lát cắt và làm điện não đồ chi tiết cho cụ Thăng. Kết quả lâm sàng hiển thị trên màn hình khiến toàn bộ kíp mổ Tây y của chúng tôi phải kinh ngạc rúng động!\"</p>
<p>Ông quay sang chỉ tay vào tấm phim chụp CT cản quang vừa mới được trợ lý mang ra: \"Mọi người nhìn xem! Vùng xuất huyết não diện rộng của bệnh nhân hoàn toàn không hề lan rộng ra các nhu mô não lành lặn xung quanh. Thay vào đó, nó đã bị cô lập hoàn toàn bởi một lớp màng sinh học thảo dược tự nhiên vô cùng dẻo dai và kiên cố, ngăn chặn tuyệt đối dòng máu chảy tràn áp lực cao tàn phá tế bào não. Kỹ thuật châm cứu vào ba huyệt Nhân Trung, Thần Đình, Bách Hội của cậu đã chặn đứng hoàn toàn áp lực nội sọ, giúp nhịp tim và huyết động học của cụ Thăng ổn định hoàn hảo suốt quá trình di chuyển cấp cứu.\"</p>
<p>Giáo sư Đức hít một hơi sâu đầy thán phục: \"Nhờ sự cô lập thần kỳ của lớp màng sinh học thảo dược MR2 nguyên chất này, cụ Thăng hoàn toàn thoát khỏi nguy cơ tử vong lâm sàng và chúng tôi không cần thực hiện cuộc phẫu thuật mở hộp sọ đầy rủi ro nữa! Ông cụ chỉ cần điều trị nội khoa Tây y kết hợp phục hồi chức năng trong một tuần là có thể xuất viện hoàn toàn khỏe mạnh! Đây thực sự là một điều kỳ diệu của Đông - Tây y kết hợp biện chứng mà cả đời làm y khoa tôi chưa từng được chứng kiến!\"</p>
<p>Nghe đến đây, Trịnh Tuyết Mai òa khóc nức nở vì hạnh phúc, cô không ngần ngại lao thẳng vào lòng Thế Hoàng, ôm chặt lấy anh trước sự chứng kiến của mọi người. Thế Hoàng nhẹ nhàng vỗ nhẹ lên vai cô, ánh mắt anh ngập tràn sự dịu dàng và ấm áp.</p>
<p>Trong khi đó, ở góc hành lang, Lê Khắc Tiệp đầu gối hoàn toàn bủn rủn không còn chút lực nào, quỵ sụp xuống sàn gạch lạnh lẽo của bệnh viện. Mồ hôi lạnh chảy ròng ròng ướt sũng cả bộ complet đắt tiền, khuôn mặt hắn xám ngoét không còn một giọt máu, mười đầu ngón tay bấu chặt vào khe gạch men đến mức rỉ máu tươi vì hối hận và sợ hãi tột cùng. Hoàng Gia Bảo đứng bên cạnh run rẩy lẩy bẩy, chiếc điện thoại trên tay rơi xuống sàn vỡ tan tành. Bọn chúng biết rằng, kết quả kiểm định lâm sàng Tây y này chính là bản án tử hình đóng đinh cho dòng thuốc giả \"Hoạt Huyết Thần Đan\" của bọn chúng.</p>"""

    # Chapter 9
    ch9_title = "Chương 9: Cú Phản Công Thép và Sự Trả Giá Tàn Khốc"
    ch9_content = """<p>Ngay tại sảnh chính lộng lẫy của Bệnh viện Trung ương Quân đội 108, trước ống kính của hàng trăm phóng viên báo chí, đài truyền hình cùng giới tinh anh y học và tài chính, Trịnh Tuyết Mai đứng hiên ngang bên cạnh Trương Thế Hoàng. Cô bước lên bục phát biểu, dõng dạc công bố một tập tài liệu đóng dấu đỏ chói lọi:</p>
<p>\"Kính thưa toàn thể dư luận và cơ quan báo chí. Hôm nay, tập đoàn Healthcare Minh Anh phối hợp cùng công ty kiểm toán Big 4 PwC chính thức công bố báo cáo kiểm toán độc lập về quyền sở hữu trí tuệ tối cao đối với hoạt chất saponin MR2 đặc trị xơ vữa động mạch. Chúng tôi sở hữu toàn bộ lịch sử Git commit logs gốc được ký số bảo mật bằng khóa PGP cá nhân của bác sĩ Trương Thế Hoàng từ ba năm trước trên server Git cá nhân bất biến. Đây là bằng chứng thép tuyệt đối chứng minh Tiến sĩ Lê Khắc Tiệp và công ty Đức Phát của Hoàng Gia Bảo đã ăn cắp trắng trợn bản quyền công nghệ nghiên cứu y học này của bác sĩ Hoàng để sản xuất dòng thuốc giả mạo chất lượng kém Hoạt Huyết Thần Đan!\"</p>
<p>Cùng lúc đó, màn hình lớn của sảnh bệnh viện hiển thị video camera ẩn sắc nét ghi lại toàn bộ cảnh Tiến sĩ Lê Khắc Tiệp nhận hối lộ hàng tỷ đồng từ Hoàng Gia Bảo để làm giả hồ sơ bệnh án và vu cáo Trương Thế Hoàng nhằm cướp đoạt bằng sáng chế. Dòng chứng cứ tài chính rõ ràng dòng tiền bẩn chảy vòng qua các công ty shell cũng được PwC bóc trần chi tiết.</p>
<p>Giữa lúc cả sảnh bệnh viện xôn xao phẫn nộ trước tội ác đê tiện của bọn chúng, tiếng bước chân rầm rập của lực lượng chức năng vang lên. Một đoàn chiến sĩ cảnh sát thuộc cơ quan Cảnh sát Điều tra C03 (Cục Cảnh sát điều tra tội phạm về tham nhũng, kinh tế, buôn lậu) bộ Công an xuất hiện. Kẻ dẫn đầu cầm tờ sắc lệnh đóng dấu đỏ chói lọi:</p>
<p>\"Chúng tôi là cơ quan Cảnh sát Điều tra C03. Căn cứ vào các chứng cứ phạm tội thu thập được, ra lệnh khởi tố vụ án hình sự, bắt tạm giam khẩn cấp đối với Lê Khắc Tiệp và Hoàng Gia Bảo về các tội danh: Hủy hoại tài sản Nhà nước, Sản xuất buôn bán thuốc giả gây hậu quả đặc biệt nghiêm trọng và Chiếm đoạt tài sản trí tuệ!\"</p>
<p>Lê Khắc Tiệp đầu gối bủn rủn quỵ sụp hẳn xuống sàn gạch men lạnh lẽo, mồ hôi lạnh tuôn ra như tắm, sắc mặt xám ngoét không còn giọt máu, móng tay bấu rỉ cả máu tươi vì hối hận muộn màng tột cùng. Hắn khóc lóc gào thét thảm thiết: \"Thế Hoàng... cứu thầy với... thầy biết sai rồi... xin em tha cho thầy một con đường sống...\"</p>
<p>Hoàng Gia Bảo sắc mặt xám ngoét, gào khóc vô vọng khi bị hai chiến sĩ cảnh sát còng tay sắt lạnh lùng lôi đi xềnh xệch trước ống kính phóng viên báo chí. Tạ Mỹ Linh đứng trơ trọi giữa đám đông, khuôn mặt cô ta tràn ngập sự kinh hoàng và hối hận tột độ khi nhận ra giấc mơ hào môn đã hoàn toàn tan vỡ, bản thân cô ta giờ đây cũng sẽ đối mặt với án tù đồng phạm nguy hiểm.</p>
<p>Thế Hoàng nhìn bọn họ bị lôi đi, ánh mắt anh phẳng lặng như nước hồ thu, không có lấy một chút oán hận hay thương hại. Anh quay sang nắm chặt lấy bàn tay mềm mại của Trịnh Tuyết Mai. Dưới ánh nắng ban mai rực rỡ xua tan đi làn sương mù lạnh giá của Hà Nội, hai người mỉm cười nhìn nhau, chính thức công bố hợp đồng hợp tác trăm tỷ phát triển dòng Đông dược sinh học Sâm Ngọc Linh vươn ra thế giới, mở ra một kỷ nguyên mới rực rỡ cho nền y học cổ truyền Việt Nam.</p>"""

    novel_data["chapters"].append({"title": ch1_title, "content": ch1_content})
    novel_data["chapters"].append({"title": ch2_title, "content": ch2_content})
    novel_data["chapters"].append({"title": ch3_title, "content": ch3_content})
    novel_data["chapters"].append({"title": ch4_title, "content": ch4_content})
    novel_data["chapters"].append({"title": ch5_title, "content": ch5_content})
    novel_data["chapters"].append({"title": ch6_title, "content": ch6_content})
    novel_data["chapters"].append({"title": ch7_title, "content": ch7_content})
    novel_data["chapters"].append({"title": ch8_title, "content": ch8_content})
    novel_data["chapters"].append({"title": ch9_title, "content": ch9_content})

    # Save to pending_novel.json
    print(f"💾 Saving to {OUTPUT_FILE}...")
    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(novel_data, f, ensure_ascii=False, indent=2)
    print("✓ Successfully saved pending_novel.json!")

    # Download cover image from Pollinations AI
    print(f"🎨 Downloading premium cover from Pollinations AI...")
    encoded_prompt = urllib.parse.quote(novel_data["cover_prompt"])
    url = f"https://image.pollinations.ai/prompt/{encoded_prompt}"
    try:
        req = urllib.request.Request(
            url,
            headers={'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'}
        )
        with urllib.request.urlopen(req, timeout=60) as response:
            with open(COVER_FILE, 'wb') as out_file:
                out_file.write(response.read())
        print(f"✓ Successfully downloaded cover image to {COVER_FILE}!")
    except Exception as e:
        print(f"❌ Failed to download cover image: {e}")

if __name__ == "__main__":
    main()
