#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build the 800-chapter planning manifest from 80 ten-chapter sub-arcs.
No network/API/publish actions. Safe to rerun; output is deterministic.
"""
from __future__ import annotations
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "planning" / "master_manifest.json"

VOLUME_TITLES = {
    1: "Thiên Hạ Sao Yếu Vậy?",
    2: "Thái Huyền Có Một Tên Khốn",
    3: "Vạn Yêu Bí Cảnh",
    4: "Hội Không Muốn Chết",
    5: "Ngày Thái Huyền Cháy",
    6: "Cửu Châu Thiên Kiêu",
    7: "Người Trong Bức Họa",
    8: "Kiếm Của Lục Thanh Nghi",
    9: "Thiên Môn Không Dẫn Lên Trời",
    10: "Trung Thiên",
    11: "Bảy Năm",
    12: "Ta Trở Về",
    13: "Lạc Kê Thôn Không Có Người Thường",
    14: "Cửu Thiên Từng Là Một",
    15: "Thiên Ngoại Giáng Lâm",
    16: "Ta Luyện Nhân Gian",
}


def A(v, n, title, goal, conflict, romance, mystery, power, *events):
    if len(events) < 4:
        raise ValueError(f"Arc {v}.{n} needs at least 4 event beats; got {len(events)}")
    opening = events[0]
    midpoint = " ".join(events[1:-2])
    climax = events[-2]
    payoff = events[-1]
    return {
        "volume": v,
        "arc_in_volume": n,
        "title": title,
        "goal": goal,
        "conflict": conflict,
        "romance": romance,
        "mystery": mystery,
        "power": power,
        "opening": opening,
        "midpoint": midpoint,
        "climax": climax,
        "payoff": payoff,
    }

ARCS = [
    # V1
    A(1,1,"Mười Ba Năm Ở Lạc Kê","Cho độc giả yêu Tiểu Bảo và cảm thấy Lạc Kê rất bình thường theo góc nhìn hắn.","Tiểu Bảo liên tục gây họa nhỏ trong làng và không biết các bài tập đời thường phi lý đến mức nào.","Chưa gặp Thanh Nghi; thiết lập nhu cầu có một mái nhà.","Gieo thân pháp bắt gà, thế chẻ củi, nhịp thở gánh nước, ba đồng tiền và cái nồi đen.","Không ghi cảnh giới; cơ thể đã được rèn quá chuẩn tu sĩ phổ thông.","Tiểu Bảo truy Ô Gia quanh làng.","Dân làng họp bí mật quyết định cho hắn xuống núi.","Tiểu Bảo tưởng mình bị ghét rồi biết một phần lý do là hắn phá/ăn quá nhiều.","Rời làng với ba đồng, nồi đen, dao cũ; Ô Gia lén đi theo."),
    A(1,2,"Không Phải Ta Mạnh","Cho Tiểu Bảo va vào chuẩn sức mạnh bên ngoài.","Thương đội bị cướp tu sĩ; hắn muốn trốn nhưng không chịu nhìn trẻ con bị giết.","Chưa romance; định hình giới hạn đạo đức của main.","Linh khí vào người biến mất; nồi đen phản ứng với linh thạch.","Lần đầu thử Dẫn Khí thất bại trên bề mặt; sức thân thể đánh văng Dẫn Khí cao tầng.","Tiểu Bảo gia nhập thương đội.","Một cái tát vô tình hạ tên cướp mạnh nhất.","Hắn buộc phải chiến đấu để cứu người và nhận túi trữ vật đầu tiên.","Đến Thanh Hà, thấy thông báo tuyển đồ Thái Huyền."),
    A(1,3,"Tiền Mới Là Đại Đạo","Đưa main vào kinh tế tu giới và thành thị.","Tiểu Bảo nghèo, thiếu kiến thức, Ô Gia ăn vụng linh dược.","Thoáng thấy Thanh Nghi lần đầu nhưng chưa tương tác.","Linh dược Lạc Kê bị thương nhân nhận ra là hàng hiếm; nguồn gốc làng càng khả nghi với độc giả.","Main chưa giữ được linh khí nhưng phản xạ/thể lực tiếp tục phi lý.","Tiểu Bảo trả phí vào thành và đau như mất thịt.","Bán rẻ linh dược rồi phát hiện bị mua lại giá gấp nhiều lần.","Ô Gia gây vụ náo loạn cả phường tu sĩ.","Ô Gia tha nhầm túi trữ vật của Thanh Nghi về cho chủ."),
    A(1,4,"Cô Nương, Đây Là Hiểu Lầm","Đưa cặp chính vào xung đột và lần đầu phối hợp.","Thanh Nghi đòi lại túi; kẻ truy sát nàng khiến Tiểu Bảo cũng bị cuốn vào.","Oan gia; nàng thấy hắn đáng ghét nhưng không hèn, hắn thấy nàng mạnh nhưng rất khó nói chuyện.","Người truy sát nhắm vào Thái Huyền Lệnh, gợi có tranh đấu lớn quanh tuyển đồ.","Tiểu Bảo dùng thân thể + địa hình đối đầu Khai Mạch sơ kỳ trong thời gian ngắn.","Thanh Nghi bắt quả tang Tiểu Bảo cầm túi.","Cuộc rượt đuổi biến thành trận chống nhóm truy sát.","Cặp đôi lần đầu phối hợp: nàng phá lực, hắn phá thế.","Thanh Nghi mời hắn cùng đi Thái Huyền sau khi nợ hắn một mạng."),
    A(1,5,"Thái Huyền Tuyển Đồ","Đưa main vào tông môn và chốt mystery Lạc Kê đầu tiên.","Khảo hạch linh căn cho kết quả bằng không; main chỉ có thể vào bằng đường tạp dịch/thể lực.","Thanh Nghi lần đầu cười trước hắn; bắt đầu coi hắn là người có thể đồng hành.","Đá linh căn nứt sau khi hắn rời; trưởng lão nhận ra bộ pháp Lạc Kê.","Tiểu Bảo chính thức chưa Dẫn Khí ổn định; năng lực thân thể được che dưới thân phận tạp dịch.","Hai người đi chung tới Thái Huyền.","Khảo linh căn: Thanh Nghi Thiên phẩm, Tiểu Bảo không sáng.","Khảo leo núi cho thấy thể lực của hắn vượt chuẩn nhưng hắn cố giấu.","Một trưởng lão nói: 'Lạc Kê Thôn cuối cùng cũng thả người ra rồi sao?'"),
    # V2
    A(2,1,"Tạ Ký Tạp Vụ","Cho Tiểu Bảo xây chỗ đứng bằng đầu óc chứ không chỉ sức mạnh.","Tạp dịch nghèo và bị bóc sức; hắn biến việc người khác ngại làm thành dịch vụ.","Thanh Nghi chủ động mang thuốc; quan hệ chuyển từ nợ mạng sang quan tâm nhỏ.","Linh khí vẫn biến mất khỏi đan điền nhưng cơ thể càng mạnh.","Chuẩn bị đột phá Dẫn Khí thật sự.","Tiểu Bảo khám phá cơm tạp dịch miễn phí.","Dịch vụ xếp hàng/giao cơm bùng nổ rồi gây phản ứng từ quản sự.","Hắn dùng quy tắc tông môn để giữ việc làm mà không đánh nhau.","Một lão say ăn quỵt ba đồng và bị Tiểu Bảo đuổi qua ba ngọn núi."),
    A(2,2,"Sư Phụ Nghèo Nhất","Thiết lập Mộc Vô Nhai và cơ chế tu luyện thật của main.","Tiểu Bảo không muốn nhận sư phụ nghèo; Mộc nghi ngờ nền tảng cơ thể hắn.","Thanh Nghi kính trọng Mộc khiến Tiểu Bảo lần đầu nhận ra sư phụ không đơn giản.","Mộc nhận ra thế chẻ củi/nhịp thở cổ nhưng không biết toàn bộ nguồn gốc.","Mộc chỉnh một nhịp thở giúp Tiểu Bảo đạt Dẫn Khí tầng 1; khí tan vào thân thay vì đan điền.","Mộc thử cành cây và bị thế chẻ củi làm rung tay.","Tiểu Bảo nhận sư phụ vì bao cơm.","Mộc tái dựng các 'việc nhà' thành bài kiểm tra đại đạo.","Tiểu Bảo đột phá và ăn bảy suất cơm vì Nhân Gian Lô ngầm tiêu hao.","Mộc lén ghi hắn vào nhiệm vụ chung với Thanh Nghi."),
    A(2,3,"Hắc Phong Lâm","Cho cặp chính chứng minh họ bổ sung nhau.","Yêu thú mạnh hơn dự kiến và có người âm thầm quan sát.","Tin tưởng tăng; họ chia sẻ kỹ năng, không còn chỉ là oan gia.","Kẻ quan sát gửi báo cáo 'nghi có dị thể'.", "Dẫn Khí tăng dần; Tiểu Bảo vô thức phát tia đao ý khi dùng dao cũ.","Hai người nhận nhiệm vụ hái Thanh Nguyệt Thảo.","Thanh Nghi bị lạc và Tiểu Bảo dẫn đường bằng kinh nghiệm rừng.","Huyết Nha Trư phá túi thảo dược khiến main lần đầu đánh nghiêm túc.","Kẻ bí mật xác nhận Tiểu Bảo cần bị theo dõi."),
    A(2,4,"Ta Chỉ Muốn Thua","Đại bỉ cho thấy main thông minh trong việc giấu sức.","Tiền thưởng hấp dẫn nhưng Mộc cấm hắn nổi quá sớm; đối thủ cứ tự khiến hắn thắng.","Thanh Nghi hiểu hắn đủ sâu để biết khi nào hắn cố tình nhường và không coi đó là xúc phạm.","Tông môn chú ý nhiều hơn; Bạch Đồng thu thêm dữ liệu.","Tiểu Bảo đạt khoảng Dẫn Khí 7–8, chiến lực chạm Khai Mạch sơ.","Thông báo ngoại môn đại bỉ với thưởng lớn.","Các trận thắng ngoài ý muốn biến hắn thành trò cười/ẩn số.","Trận Tần Kính Sơn khiến hắn lộ một quyền thật vì Ô Gia.","Thanh Nghi thắng trận đối đầu; Mộc nhận ra Tiểu Bảo đã học cách bảo vệ người khác."),
    A(2,5,"Cánh Cửa Dưới Núi","Mở mystery Nhân Gian Lô/Thái Huyền Cổ Môn.","Ô Gia mất tích; di tích dưới núi thu hút cả kẻ theo dõi Thiên Mệnh.","Thanh Nghi không cần lý do để đi tìm Tiểu Bảo; lòng tin thành thói quen.","Chín vòng tròn vỡ, 'Đừng mở Cửu Môn', ảo ảnh thế giới vỡ chín và câu 'Lò vẫn còn'.", "Tiểu Bảo khoảng Dẫn Khí 8–9; nồi đen lần đầu hoạt động như chìa khóa/van.","Mảnh kim loại thưởng đại bỉ làm nồi phản ứng.","Tiểu Bảo nghe tiếng gõ dưới núi và đi tìm Ô Gia.","Nồi mở phong ấn; Tiểu Bảo thấy ảo ảnh Cửu Thiên.","Mộc chặn Bạch Đồng; Thiên Mệnh nhận tin 'xác nhận mục tiêu'."),
    # V3
    A(3,1,"Vạn Yêu Mở Cửa","Mở map bí cảnh và tăng cảm giác khảo cổ Cửu Thiên.","Các đội tranh tài nguyên, quy tắc bí cảnh biến đổi bất thường.","Tiểu Bảo và Thanh Nghi tự chọn đi cùng dù có thể vào đội mạnh hơn.","Một số ký hiệu trùng Cổ Môn và Lạc Kê.","Tiểu Bảo bước Khai Mạch; Thanh Nghi củng cố kiếm đạo vượt cùng thế hệ.","Thái Huyền nhận suất vào Vạn Yêu.","Bí cảnh mở lệch giờ như có thứ bên trong thức dậy.","Một đội bị quy tắc không gian tách; cặp chính kẹt ở tầng cấm.","Họ thấy đường dẫn đến thần điện cổ không có trong bản đồ."),
    A(3,2,"Hai Người Trong Tầng Cấm","Buộc hai người dựa vào nhau khi không còn hậu viện.","Thanh Nghi bị thương; Tiểu Bảo có cơ hội chạy nhưng chọn ở lại.","Lần đầu Thanh Nghi ngủ khi để Tiểu Bảo canh, dấu hiệu tin người.","Tầng cấm dường như nhận ra cái nồi/khí tức Tiểu Bảo.","Tiểu Bảo học dùng Khai Mạch để phối thân pháp chứ không chỉ cơ bắp.","Hai người tìm đường ra qua rừng yêu thực.","Thanh Nghi trúng độc yêu và mất phần lớn chiến lực.","Tiểu Bảo dùng kiến thức bà Mạnh + bản năng luyện hóa cứu nàng.","Cửa thần điện mở khi máu Tiểu Bảo chạm phù văn."),
    A(3,3,"Chín Tượng Đá","Đưa bằng chứng trực tiếp đầu tiên rằng dân làng có quá khứ cổ.","Thần điện có cơ chế thử người và ký ức bị cắt vụn.","Thanh Nghi chứng kiến sự hoang mang thật của Tiểu Bảo và không ép hắn giải thích.","Một tượng rất giống Thôi đồ tể; danh hiệu bị mài mất.","Nhân Gian Lô phản ứng với tàn hỏa nhưng main chỉ hấp thu được một tia, phải trả giá sốt cao.","Khám phá điện và chín tượng.","Thử thách buộc mỗi người đối diện nỗi sợ bị định nghĩa bởi người khác.","Tiểu Bảo chạm tượng Thôi và thấy chiến trường thoáng qua.","Mang ra một mảnh bia có chữ 'Thủ Mộ'."),
    A(3,4,"Ô Gia Là Gà Gì?","Trao arc riêng đầu tiên cho Ô Gia và mở huyết mạch Kim Ô.","Một yêu vương trong bí cảnh muốn nuốt huyết mạch Ô Gia.","Thanh Nghi phối hợp với Tiểu Bảo cứu Ô Gia như thành viên gia đình, không chỉ pet.","Phong ấn huyết mạch Ô Gia có dấu của Lạc Kê.","Ô Gia thức tỉnh sơ cấp Thái Cổ Kim Ô; Tiểu Bảo không được hưởng power trực tiếp.","Ô Gia bị hút về tổ địa yêu cầm.","Huyết mạch thức tỉnh gây truy đuổi toàn khu.","Nhóm dùng trận địa/lừa gạt giết thế mạnh hơn thay vì solo.","Ô Gia nói được câu đầu tiên rồi vẫn bị Tiểu Bảo hỏi sao ăn giun."),
    A(3,5,"Người Đứng Ngoài Bí Cảnh","Kết Vạn Yêu bằng hậu quả và nâng Thiên Mệnh thành mối đe dọa.","Bạch Đồng và người Thiên Mệnh chờ ngoài; trong bí cảnh có phe muốn cướp tàn bia.","Thanh Nghi công khai đứng cùng Tiểu Bảo trước trưởng lão các tông.","Tàn bia xác nhận từ 'Cửu Thiên' nhưng chưa giải nghĩa.","Tiểu Bảo Khai Mạch ổn định, Thanh Nghi chạm Trúc Đài sớm hơn.","Các đội hội tụ ở cổng ra.","Một trận tranh đoạt khiến bí cảnh sắp sập.","Tiểu Bảo chọn bỏ bảo vật để kéo đồng đội ra.","Bạch Đồng báo về: mục tiêu không chỉ có dị thể, còn kích hoạt di tích."),
    # V4
    A(4,1,"Chợ Đen Thanh Cốt","Đưa nhóm ra giang hồ tu tiên thật và cho main chơi trí.","Chợ đen bán đồ từ Vạn Yêu; tàn bia bị săn giá.","Thanh Nghi bắt đầu tự nhiên đứng cạnh Tiểu Bảo trong các quyết định, không cần nhiệm vụ chung.","Một mẩu tin đầu tiên nhắc tới tổ chức 'Thiên Mệnh'.", "Tiểu Bảo học giấu khí/đổi nhịp Khai Mạch; Thanh Nghi Trúc Đài sơ bộ.","Nhóm tới chợ đen đổi tài nguyên.","Tiểu Bảo phát hiện đấu giá giả và lật trò bằng chính quy tắc chợ.","Kẻ mua tàn bia cố thủ tiêu người biết.","Họ lấy được bản đồ dẫn tới Quỷ Thành và một phù hiệu Thiên Mệnh."),
    A(4,2,"Hai Kẻ Không Bình Thường","Tuyển Hồ Tam Đa và Ninh Tiểu Cửu.","Hai nhân vật mới ban đầu vì lợi ích riêng gây rắc rối cho nhóm.","Thanh Nghi và Tiểu Bảo bắt đầu có những trò phối hợp không cần nói, khiến người ngoài hiểu lầm họ là đạo lữ; cả hai phủ nhận quá nhanh.","Hồ từng thấy trận văn giống Cửu Môn; Ninh nhận ra tro lạ trong cơ thể Tiểu Bảo.","Nhóm chiến đấu theo vai trò; sức mạnh tập thể quan trọng hơn cảnh giới main.","Gặp Hồ khi hắn bán bản đồ thật nhưng thiếu một nửa.","Gặp Ninh qua vụ đan dược gây tác dụng phụ toàn quán.","Cả bốn bị kéo vào cùng một vụ săn người.","Họ buộc phải ký 'khế ước chia chiến lợi phẩm' do Tiểu Bảo soạn."),
    A(4,3,"Quỷ Thành Không Có Người Chết","Cho nhóm trải một mystery horror-hài nhưng có hậu quả thật.","Cư dân Quỷ Thành mất ký ức theo đêm; thành chủ che giấu một pháp khí thu hồn.","Tiểu Bảo ưu tiên kéo Thanh Nghi khỏi ảo cảnh dù mất manh mối; nàng bắt đầu nhận ra vị trí của mình với hắn.","Pháp khí thu hồn là mô hình nhỏ của cơ chế thu khí vận Thiên Mệnh.","Nhân Gian Lô luyện được một mảnh tà khí nhưng khiến Tiểu Bảo mất tạm một ký ức nhỏ, cảnh báo giá của năng lực.","Nhóm vào Quỷ Thành tìm người mất tích.","Phát hiện người sống bị gọi là quỷ vì ký ức bị hút.","Họ phá lõi trận nhưng Tiểu Bảo suýt mất ký ức về Lạc Kê.","Mang được cấu trúc trận ra cho Mộc xem; ông lần đầu thật sự sợ."),
    A(4,4,"Hội Không Muốn Chết","Biến nhóm thành found-family chính thức.","Yêu Vực săn người ngoài; một nhiệm vụ lợi ích biến thành cứu dân.","Thanh Nghi chủ động chọn ở lại cùng Tiểu Bảo khi Lục gia gửi lệnh về.","Một yêu lão gọi Ô Gia bằng danh xưng cổ và biết từ 'Thủ Mộ Nhân'.", "Tiểu Bảo Khai Mạch hậu; Thanh Nghi Trúc Đài vững; đồng đội có tiến bộ riêng.","Nhóm chạy vào Yêu Vực vì bị truy nã chợ đen.","Họ cứu một thôn bán yêu và bị cuốn vào xung đột địa phương.","Cả nhóm phối hợp đánh trận sống còn và tự đặt tên Hội Không Muốn Chết.","Khẩu hiệu vui trở thành lời thề không bỏ người của mình."),
    A(4,5,"Tên Của Thiên Mệnh","Lần đầu va trực tiếp với Thiên Mệnh Điện.","Bạch Đồng nhận lệnh bắt sống Tiểu Bảo; nhóm chưa đủ sức đối đầu đội chấp hành.","Thanh Nghi bị thương vì chặn một đòn; Tiểu Bảo lần đầu giận đến mức không đùa.","Thiên Mệnh gọi Tiểu Bảo là 'lô thể' nhưng chưa giải thích; Mộc buộc phải nói mình từng biết tổ chức.","Tiểu Bảo chạm Trúc Đài nhưng chưa hoàn thiện, dùng nền móng thân thể khác thường để thoát.","Đội Thiên Mệnh khóa đường về.","Bạch Đồng thử thuyết phục: đi cùng sẽ không ai bị liên lụy.","Nhóm dùng trận Hồ + độc Ninh + kiếm Thanh Nghi + lừa của Tiểu Bảo phá vòng bắt.","Mộc nói cái tên Thiên Mệnh Điện và yêu cầu tất cả lập tức về Thái Huyền."),
    # V5
    A(5,1,"Mùi Khói Trong Tông","Bắt đầu siege arc bằng dấu hiệu nhỏ và paranoia.","Nội bộ Thái Huyền có người bị mua/khống chế; không biết ai.","Tiểu Bảo muốn đẩy Thanh Nghi ra khỏi nguy hiểm, nàng phản đối việc hắn tự quyết thay mình.","Cổ Môn dưới núi bắt đầu rò khí; có nội ứng tìm chìa.","Tiểu Bảo hoàn thiện Trúc Đài đặc dị 'Nhân Gian Đài' nhưng chưa gọi tên công khai.","Nhóm trở về thấy quy củ tông môn bất thường.","Một loạt đệ tử mất tích gắn với địa đạo.","Tiểu Bảo và Thanh Nghi tranh cãi đầu tiên về quyền được cùng chịu rủi ro.","Tìm ra dấu vết nội ứng dẫn tới một trưởng lão thân cận chưởng môn."),
    A(5,2,"Người Trong Cửa","Biến xung đột nội bộ thành phản bội có động cơ.","Nội ứng tin hi sinh Tiểu Bảo có thể cứu tông khỏi Thiên Mệnh.","Thanh Nghi đứng về quyền lựa chọn của Tiểu Bảo, foreshadow arc Lục gia.","Thiên Mệnh cần Cổ Môn như tọa độ, không chỉ cần main.","Mộc mở một phần phong ấn kiếm lực; Tiểu Bảo học dùng Trúc Đài phối hợp.","Đối chất với nội ứng.","Biết kẻ này từng mất gia đình vì chiến tranh và thật sự sợ tông diệt.","Nội ứng mở phong ấn ngoài ý muốn khi cố giao Tiểu Bảo.","Thiên Mệnh đại quân xuất hiện ngoài sơn môn."),
    A(5,3,"Ngày Thái Huyền Cháy","Đẩy tông môn vào chiến tranh thật và xóa cảm giác an toàn.","Thiên Mệnh tấn công đa tuyến; tông không thể thắng bằng một main.","Cặp chính chiến ở hai vị trí khác nhau, chứng minh mỗi người có agency.","Cổ Môn mở một khe, phóng hình bóng Cửu Thiên vỡ.","Tiểu Bảo Trúc Đài trung; Thanh Nghi Trúc Đài đỉnh/chạm Kim Đan tùy nhịp.","Sơn môn bị công kích.","Hội Không Muốn Chết chia đội cứu đệ tử/dân thường.","Kẻ địch dùng thiết bị thu khí vận làm phòng hộ tông suy yếu.","Mộc Vô Nhai quyết định dùng cấm kiếm đổi mạng để đóng khe."),
    A(5,4,"Một Kiếm Cuối Của Mộc Vô Nhai","Payoff sư phụ và truyền chủ đề đạo đức trung tâm.","Mộc biết mình khó sống; Tiểu Bảo tìm mọi cách không chấp nhận.","Thanh Nghi là người giữ Tiểu Bảo lại để Mộc tự chọn cách chết của mình; bài học quyền lựa chọn đau đớn.","Mộc tiết lộ quá khứ từng hi sinh một thành 'vì đại cục' và hối hận.","Mộc thiêu đạo cơ; Tiểu Bảo không nhận power inheritance miễn phí, chỉ nhận một kiếm ý/triết lý chưa hiểu hết.","Mộc giao nhiệm vụ cuối cho từng người.","Tiểu Bảo cố tìm phương án thứ ba nhưng thời gian hết.","Mộc chém đứt tọa độ Thiên Mệnh và chết/tiêu tán thật.","Câu cuối: nếu ai bảo ngươi phải cứu thiên hạ, hỏi mình trước ngươi có muốn không."),
    A(5,5,"Sau Đám Cháy","Cho grief có trọng lượng và biến Tiểu Bảo thành người chủ động truy chân tướng.","Thái Huyền tổn thất; phe trong tông muốn giao main để tránh lần hai.","Tiểu Bảo và Thanh Nghi hòa giải xung đột quyền lựa chọn; hắn xin lỗi vì từng định đẩy nàng đi.","Di vật Mộc chứa tọa độ Cửu Châu Đại Hội và dấu vết chiến trường cổ.","Tiểu Bảo ổn định Trúc Đài; không đột phá vì grief.","Chôn người chết, sửa sơn môn.","Tranh luận ở đại điện về việc giữ hay trục xuất Tiểu Bảo.","Tiểu Bảo tự chọn rời tông dự Cửu Châu để kéo chiến tuyến đi và tìm nguồn Thiên Mệnh.","Thanh Nghi nói nàng đi vì chính nàng muốn đi, không phải vì hắn cần."),
    # V6
    A(6,1,"Đường Tới Cửu Châu","Mở quy mô chính trị và cho nhóm thở sau siege.","Các tông môn coi Thái Huyền suy yếu là cơ hội; đoàn bị gây khó.","Tiểu Bảo/Thanh Nghi có những khoảnh khắc đời thường thân hơn nhưng chưa gọi tên.","Di vật Mộc phản ứng với cột mốc cổ trên đường.","Tiểu Bảo học kiểm soát Trúc Đài, Thanh Nghi bắt đầu Kim Đan chuẩn bị.","Đoàn rời Thái Huyền.","Đi qua thành lớn thấy tin đồn Tạ Vô Sỉ bị thổi phồng.","Một cuộc phục kích chính trị buộc Tiểu Bảo giải quyết bằng luật đại hội.","Họ đến Cửu Châu Thành và nghe tên Sở Thiên Tử."),
    A(6,2,"Sở Thiên Tử","Tạo rival có giá trị tư tưởng, không phản diện giấy.","Sở coi cách sống của Tiểu Bảo là thiếu trách nhiệm; Tiểu Bảo coi Sở là người tự đeo gánh thiên hạ.","Thanh Nghi thấy Tiểu Bảo thoải mái tranh cãi với Sở theo cách hắn hiếm làm với người khác.","Sở mang huyết mạch liên hệ một phe từng bảo vệ Cửu Thiên nhưng bản thân không biết.","Sở mạnh hơn Tiểu Bảo chính diện; main phải chấp nhận mình không phải người giỏi nhất.","Gặp nhau vì tranh chỗ ở/đăng ký.","Đấu nhỏ không phân thắng bại theo kiểu hài nhưng cho thấy chênh kỹ thuật.","Cùng giải một vụ gian lận loại thí sinh và buộc phải hợp tác.","Sở tuyên bố sẽ đánh bại Tiểu Bảo công khai trên đài."),
    A(6,3,"Thiên Kiêu Không Chỉ Biết Đánh","Làm tournament đa dạng bằng puzzle, team, chiến thuật.","Thiên Mệnh cài bài test bí mật vào đại hội để sàng lọc khí vận.","Thanh Nghi có trận riêng và được nhìn như nhân vật mạnh độc lập.","Một vòng thi dùng cổ trận có cấu trúc thu khí vận.","Tiểu Bảo Trúc Đài hậu; Thanh Nghi kết Kim Đan; Sở cùng tầng cao hơn.","Vòng sinh tồn/tìm cờ.","Vòng giải trận cho Hồ tỏa sáng.","Thanh Nghi thắng thiên kiêu kiếm đạo bằng lựa chọn không theo giáo trình Lục gia.","Tiểu Bảo phát hiện đại hội đang đo thứ gì ngoài thắng thua."),
    A(6,4,"Trận Mà Ta Muốn Thắng","Cho main chủ động cạnh tranh thay vì chỉ né nổi tiếng.","Thiên Mệnh định đánh dấu người thắng; Tiểu Bảo vẫn quyết đấu vì cần quyền vào chiến trường cổ.","Thanh Nghi là người đầu tiên nhận ra hắn thật sự muốn thắng và không trêu hắn.","Phần thưởng top dẫn vào Thượng Cổ Chiến Trường.","Tiểu Bảo chạm Kim Đan theo hướng Nhân Gian Lô; cần hậu quả lớn chứ không đột phá tiện tay.","Tiểu Bảo vượt các vòng cuối.","Đấu Sở lần hai, cả hai buộc dùng bản lĩnh thật.","Tiểu Bảo thắng sát nút bằng chiến thuật nhưng trả giá thương tích/đạo cơ quá nhiệt.","Ấn đánh dấu Thiên Mệnh bám vào chiến thắng của hắn."),
    A(6,5,"Dấu Trên Người Kẻ Thắng","Kết đại hội bằng lựa chọn đi chiến trường cổ.","Ấn Thiên Mệnh không thể gỡ bằng cách thường; nếu phá bừa sẽ hủy đạo cơ.","Thanh Nghi chọn cùng vào chiến trường dù suất của nàng có đường an toàn hơn.","Mộc để lại cách đọc một phần ấn; chiến trường cổ có chìa khóa còn lại.","Tiểu Bảo Kim Đan sơ nhưng trạng thái không ổn; cần học cân bằng.","Các phe chia phần thưởng.","Sở phát hiện mình cũng bị đánh dấu ở mức nhẹ.","Ba phe từng cạnh tranh quyết định tạm liên minh.","Cổng Thượng Cổ Chiến Trường mở bằng âm thanh giống tiếng gõ dưới Thái Huyền."),
    # V7
    A(7,1,"Đất Không Có Người Sống","Biến chiến trường thành bằng chứng lịch sử chứ không kho báu thuần.","Quy tắc chết sót lại tấn công mọi người; tài nguyên hấp dẫn khiến đồng minh rạn.","Tiểu Bảo và Thanh Nghi tự chia quyền quyết định đội thay vì một người dẫn tuyệt đối.","Xương tiên, vũ khí gãy và chữ cổ gợi một cuộc chiến lớn hơn lịch sử hiện tại.","Kim Đan của Tiểu Bảo học lọc tử khí nhưng phải tránh nghiện khả năng luyện hóa.","Đặt chân vào chiến trường.","Một đội tham bảo vật bị quy tắc giết, cảnh báo thật.","Sở cứu đối thủ cũ và bị thương, phá khuôn thiên kiêu lạnh.","Nhóm tìm thấy một hành lang ký ức lưu chiến tranh Cửu Thiên."),
    A(7,2,"Ký Ức Của Người Chết","Cho quá khứ xuất hiện qua fragment không đáng tin hoàn toàn.","Ký ức cổ thiếu đoạn, dễ dẫn tới kết luận sai.","Thanh Nghi nhận ra Tiểu Bảo sợ biết sự thật về làng hơn sợ kẻ địch.","Thoáng thấy các Thủ Mộ Nhân trẻ hơn, không đủ rõ mặt.","Tiểu Bảo học một cách dùng Kim Đan để neo thần trí trước ký ức ngoại lai.","Nhóm kích hoạt trường ký ức.","Mỗi người thấy một góc khác nhau và tranh luận về sự thật.","Tiểu Bảo suýt bị ký ức của một chiến sĩ cổ hòa tan bản ngã.","Một tên thật 'Kỷ Vô Phong' xuất hiện nhưng hắn chưa nối với lão què."),
    A(7,3,"Người Trong Bức Họa","Payoff bằng chứng dân làng là đại nhân vật.","Nhiều phe cùng tìm bức họa vì nó chỉ vị trí Cửu Thiên Tàn Phiến.","Thanh Nghi không trấn an bằng lời sáo; nàng chỉ ở cạnh khi Tiểu Bảo đối diện cú sốc.","Bức họa có Thôi Đại Tráng, Kỷ Vô Phong, Mạnh Dao Quân, Hàn Luyện; danh hiệu Cửu Thiên Thủ Mộ Nhân.","Không breakthrough; tập trung tâm lý/lore để tránh power treadmill.","Tìm kho lưu tranh.","Tiểu Bảo nhận ra khuôn mặt Thôi trước tiên và cố tự lừa mình.","Bức họa bị các phe tranh cướp, buộc hắn công khai bảo vệ.","Hắn lấy được bản sao ký ức và lần đầu quyết định sau này phải về làng hỏi thẳng."),
    A(7,4,"Cửu Thiên Tàn Phiến","Đưa MacGuffin lớn nhưng đặt luật rõ.","Tàn phiến gây cộng hưởng với nồi và ấn Thiên Mệnh; nhiều phe săn.","Cặp chính cùng quyết định giữ mảnh dù biết sẽ nguy hiểm, không phải Tiểu Bảo quyết hộ.","Tàn phiến là mảnh 'luật', không chỉ chìa khóa; cho thấy thế giới từng là một.","Nhân Gian Lô luyện quá sức khiến Tiểu Bảo mất cảm giác tay tạm thời.","Tìm tàn phiến trong chiến trường lõi.","Tàn phiến cộng hưởng làm lộ vị trí cả nhóm.","Trận ba phe; Tiểu Bảo dùng ấn Thiên Mệnh làm mồi ngược.","Giành mảnh nhưng chiến trường bắt đầu sập."),
    A(7,5,"Ra Khỏi Người Chết","Thoát chiến trường với tổn thất và đổi niềm tin.","Quy tắc sập đóng đường; Thiên Mệnh chờ ngoài.","Thanh Nghi chăm tay mất cảm giác của Tiểu Bảo; intimacy nhỏ nhưng rõ với độc giả.","Một tín hiệu từ tàn phiến hướng tới Lục gia/Kiếm Vực bất ngờ.","Tiểu Bảo phục hồi dần nhờ nghỉ/đan, không instant heal.","Chạy qua vùng sập.","Sở ở lại chặn để dân/tán tu ra trước, thay đổi cách Tiểu Bảo nhìn hắn.","Nhóm phá cổng khác thay vì lao vào phục kích Thiên Mệnh.","Lục gia gửi lệnh bắt Thanh Nghi phải trở về ngay."),
    # V8
    A(8,1,"Trở Về Lục Gia","Đổi trọng tâm POV/agency sang Thanh Nghi.","Gia tộc dùng nghĩa vụ, bệnh của trưởng bối và danh dự để ép nàng ở lại.","Tiểu Bảo muốn đi cùng; Thanh Nghi nói đây trước hết là việc nàng phải tự đối diện.","Kiếm Vực có một mảnh luật liên quan Cửu Thiên nhưng gia tộc không biết toàn bộ.","Thanh Nghi Kim Đan trung/hậu; Tiểu Bảo giữ ổn định, không lấn spotlight.","Đoàn tới Lục gia.","Cha con gặp lại lạnh nhưng không vô tình.","Lục Tĩnh Hàn công bố nghi thức Kiếm Thai sắp tới.","Thanh Nghi yêu cầu được tự quyết và bị khóa quyền rời Kiếm Vực."),
    A(8,2,"Tiên Thiên Kiếm Thai","Lộ bản chất 'vinh quang' thực ra là hiến tế cá nhân.","Lục Trường Uyên tin con hi sinh là cách cứu gia tộc khỏi tiên kiếm phản phệ.","Tiểu Bảo và Thanh Nghi bất đồng: hắn muốn phá ngay, nàng muốn hiểu để tự chém đúng chỗ.","Tiên kiếm dùng tàn luật Cửu Thiên làm lõi; gia tộc đã hiểu sai cơ chế qua nhiều thế hệ.","Thanh Nghi học kiếm đạo đối nghịch giáo trình: kiếm không phải chủ nhân của nàng.","Khám phá nghi thức.","Đối thoại cha-con cho thấy ông không phải ác nhân giấy.","Tiểu Bảo tìm ra lỗ hổng nhưng tôn trọng kế hoạch của Thanh Nghi.","Nghi thức bắt đầu trước thời hạn vì phe bảo thủ sợ nàng đổi ý."),
    A(8,3,"Kiếm Vực Vỡ Một Đường","Cặp đôi hợp tác nhưng Thanh Nghi là người quyết định cú chém.","Kiếm Vực khóa linh lực ngoài; Tiểu Bảo chỉ hỗ trợ phá trận/giữ người.","Tiểu Bảo nói 'nàng muốn đi hay ở là chuyện của nàng' — câu then chốt nhưng không tuyên bố sở hữu.","Tàn luật đáp lại Nhân Gian Lô và cho thấy hai hệ có thể nối chứ không cần nuốt nhau.","Thanh Nghi bẻ giới hạn Kim Đan bằng kiếm ý tự chủ; Tiểu Bảo chịu phản chấn khi giữ trận.","Nhóm phá vào tầng nghi thức.","Cha nàng đứng chắn vì tin đó là nghĩa vụ.","Thanh Nghi tự chém sợi khế ước Kiếm Thai gắn vào thần hồn.","Kiếm Vực nứt nhưng không sập; gia tộc không bị diệt như lời dọa nhiều đời."),
    A(8,4,"Kiếm Của Ta","Cho Thanh Nghi xây lại quan hệ với kiếm, gia đình, bản thân.","Gia tộc chia phe; nàng có thể trả thù nhưng chọn tái lập luật.","Nàng nhận ra người đầu tiên không định nghĩa nàng bằng hữu dụng là Tiểu Bảo.","Mảnh luật trong tiên kiếm cung cấp tọa độ Thiên Môn thật.","Thanh Nghi chạm Kim Đan viên mãn/Nguyên Anh seed; Tiểu Bảo hiểu một lớp Nhân Gian Lô qua cộng hưởng.","Hậu quả nghi thức.","Thanh Nghi đấu kiếm công khai với Lục Tĩnh Hàn để giành quyền định lại quy chế.","Lục Trường Uyên chọn không can thiệp lần đầu tiên.","Thanh Nghi thắng và rời Lục gia bằng ý chí của mình, không bị 'cướp đi'."),
    A(8,5,"Tiền Cho Nàng Giữ","Xác nhận romance sau 400 chương build-up.","Cả hai đều vụng nói thật; hiểm họa Thiên Môn vẫn tiến gần.","Tiểu Bảo tỏ tình kiểu thực dụng; Thanh Nghi chấp nhận nhưng đặt rõ họ là hai người đồng hành, không ai sở hữu ai.","Tọa độ Thiên Môn trùng đường ấn Thiên Mệnh.","Không breakthrough; để romance có không gian.","Rời Kiếm Vực và xử lý dư âm.","Một trận nhỏ cho thấy họ đã phối hợp như cặp trước khi gọi tên.","Tiểu Bảo nói 'sau này tiền của ta cho nàng giữ'.", "Hai người thành đôi; ngay sau đó nhận tin Thiên Môn sắp mở."),
    # V9
    A(9,1,"Hai Người Biết Yêu Kiểu Gì?","Viết couple arc có đời sống và ranh giới.","Cả hai giỏi đánh nhau nhưng dở biểu đạt; nhiệm vụ mới không chờ họ học yêu.","Những cảnh quà tặng, ghen rất nhẹ, phối hợp và tranh luận phương pháp.","Dấu Thiên Mệnh phản ứng mạnh mỗi khi gần Thiên Môn.","Tiểu Bảo/Thanh Nghi tiến hướng Nguyên Anh theo đường riêng.","Bạn bè phát hiện họ thành đôi.","Một món quà nhặt từ kẻ truy sát trở thành joke nhưng có tình.","Họ cãi thật về việc ai được nhận phần nguy hiểm.","Thống nhất nguyên tắc: không tự hi sinh thay người kia nếu còn phương án bàn bạc."),
    A(9,2,"Dấu Hiệu Thiên Môn","Biến sự kiện phi thăng thành mystery điều tra.","Các lão tổ tranh suất, tạo hỗn loạn; người phi thăng đầu tiên để lại dấu hiệu bị rút khí vận.","Thanh Nghi và Tiểu Bảo điều tra như partner; mỗi người có manh mối riêng.","Thiên Môn có cấu trúc giống Quỷ Thành nhưng ở quy mô giới.","Cả hai chạm Nguyên Anh; không cùng lúc, mỗi đột phá có arc riêng.","Thiên tượng xuất hiện.","Một cường giả phi thăng trước và khí vận tông của ông suy sụp bất thường.","Nhóm đo được dòng năng lượng bị hút lên cửa.","Họ quyết định không tranh suất mà phá cơ chế."),
    A(9,3,"Người Muốn Lên Trời","Đặt xung đột với người tốt có niềm tin khác.","Nhiều cường giả biết có giá nhưng vẫn muốn phi thăng vì giới sắp cạn tài nguyên.","Cặp chính học rằng không thể ép người khác chọn giống mình.","Một trưởng bối giải thích các thế hệ trước coi mất khí vận là 'thuế phi thăng'.", "Nguyên Anh mới còn bất ổn; cần chiến đấu thông minh.","Điều trần giữa các tông.","Sở Thiên Tử đứng giữa vì gia tộc cần suất.","Một vụ cưỡng đoạt suất làm dân chết, đẩy khủng hoảng.","Tiểu Bảo đưa bằng chứng Thiên Môn không chỉ thu thuế mà biến người thành tài nguyên."),
    A(9,4,"Cái Giá Của Phi Thăng","Reveal cơ chế thu hoạch và tạo đồng minh bất đắc dĩ.","Thiên Mệnh kích hoạt cửa sớm; những người đã đánh dấu bị hút.","Thanh Nghi tự cắt một phần kiếm khí để giữ Tiểu Bảo, trả giá thật.","Dòng hút dẫn tới Trung Thiên và kho khí vận.","Tiểu Bảo dùng Nhân Gian Lô đảo chiều một đoạn, nguy cơ đốt Nguyên Anh.","Cửa mở cưỡng bức.","Ấn trên Tiểu Bảo/Sở biến thành móc câu.","Nhóm phá neo dưới phàm giới trong trận nhiều phe.","Biết muốn chấm dứt phải đi qua chính cánh cửa."),
    A(9,5,"Đập Vỡ Thiên Môn","Kết phàm giới bằng hành động phá hệ thống chứ không 'được chọn'.", "Thiên Môn sập có thể làm đường giới đóng vĩnh viễn; các phe phản đối.","Tiểu Bảo và Thanh Nghi cùng quyết định sang Trung Thiên, không ai kéo người kia.","Sau cánh cửa là mạng lưới nhiều tiểu thế giới bị thu hoạch.","Nguyên Anh ổn định qua đại chiến; Sở/Hội cũng trưởng thành.","Chuẩn bị trận cuối phàm giới.","Hồ tìm cách phá cửa mà giữ đường tạm.","Tiểu Bảo/Thanh Nghi chém và luyện hai neo chính.","Cửa vỡ; họ rơi sang Trung Thiên trong khi phàm giới được giải phóng khỏi đợt thu hoạch tức thời."),
    # V10
    A(10,1,"Người Phàm Ở Trung Thiên","Reset địa vị mà không reset nhân vật.","Ở Trung Thiên, cảnh giới cũ chỉ tầm thấp; nhóm thiếu tiền/giấy tờ/quan hệ.","Couple chia việc sinh tồn, tạo cảm giác đời sống.","Các 'phi thăng giả' được phân loại như tài sản/nhân lực.","Nguyên Anh/Hóa Thần trở thành chuẩn mới; main không được bỗng mạnh nhất.","Rơi vào vùng biên.","Bị đòi phí đăng giới và suýt thành lao dịch.","Dùng kỹ năng/kinh doanh để tự mua tự do.","Nghe lần đầu về Thiên Mệnh Thành như cơ quan hợp pháp."),
    A(10,2,"Thành Phố Của Người Phi Thăng","Cho thấy hệ thống bóc lột tinh vi, không chỉ villain hangout.","Nhiều người chấp nhận Thiên Mệnh vì nó cung cấp trật tự, việc làm, bảo hộ.","Thanh Nghi phản đối Tiểu Bảo muốn phá ngay khi chưa hiểu hệ quả; cãi nhau có lý.","Khí vận được định lượng thành tín dụng/thuế.","Hóa Thần setup; Thanh Nghi kiếm đạo mở rộng sang pháp tắc.","Nhóm vào thành.","Tiểu Bảo tìm cách kiếm tiền từ sửa đồ/đấu trận.","Phát hiện người dân phụ thuộc thật vào hạ tầng Thiên Mệnh.","Hai người thống nhất phải thay cơ chế chứ không đập mù."),
    A(10,3,"Sổ Cái Khí Vận","Điều tra lõi kinh tế của Thiên Mệnh.","Một kiểm toán viên/quan lại trung lập bị săn vì thấy số liệu biến mất.","Cặp chính tin nhau giao nhiệm vụ riêng dài hơn, thể hiện relationship trưởng thành.","Sổ cái cho thấy hàng ngàn tiểu giới bị trích khí vận theo quota.","Tiểu Bảo thử luyện một token khí vận và bị ký ức người lạ tràn vào, chứng minh nó chứa đời sống thật.","Tìm người giữ sổ.","Đột nhập kho dữ liệu bằng trận pháp/kiếm.","Phát hiện 'quota cứu thế' liên quan nỗi sợ Thiên Ngoại.","Tư Không Dạ chú ý trực tiếp đến tên Tạ Tiểu Bảo."),
    A(10,4,"Đánh Vào Một Nút","Cho nhóm giành thắng lợi cục bộ nhưng làm boss học theo.","Phá trạm thu hoạch sẽ khiến vùng biên mất bảo hộ khỏi giới thú.","Thanh Nghi đề xuất kế hoạch thay nguồn trước khi phá, tránh main-centric solution.","Nút mạng dùng công nghệ/tàn luật Cửu Thiên bị bóp méo.","Tiểu Bảo Hóa Thần sơ qua hiểu cấu trúc luyện hóa, phải dưỡng dài sau trận.","Chọn một trạm thử nghiệm.","Xây nguồn thay bằng trận Hồ + đan Ninh + pháp tắc Thanh Nghi.","Trận đánh với chấp hành Thiên Mệnh.","Nút sập nhưng Tư Không Dạ dùng dữ liệu trận xác định tần số Nhân Gian Lô."),
    A(10,5,"Rơi Xuống Vô Gian","Tách cặp ở peak nguy cơ nhưng do lựa chọn chiến thuật, không hiểu lầm.","Tư Không Dạ dựng bẫy dùng tần số Nhân Gian Lô; cả nhóm bị khóa.","Tiểu Bảo đẩy Thanh Nghi khỏi khe trong một quyết định tức thời; điều này vi phạm nguyên tắc đôi bên và sẽ có hậu quả quan hệ khi tái hợp.","Vô Gian là vết thương của Cửu Thiên, nơi luật/linh khí bị đốt mất.","Tiểu Bảo Hóa Thần bị bóc gần hết khả năng dùng linh khí khi rơi.","Thiên Mệnh phản kích.","Nhóm cố thoát bẫy nhưng khe Vô Gian mở.","Tiểu Bảo dùng thân mình chặn xung để người khác ra.","Thanh Nghi thấy hắn rơi xuống vùng được ghi là 'không ai trở về'."),
    # V11
    A(11,1,"Nơi Không Có Linh Khí","Bóc bỏ lợi thế tu sĩ và trả main về kỹ năng nền.","Vô Gian không có linh khí; Nhân Gian Lô càng luyện càng đốt chính hắn.","Tiểu Bảo nhớ lời hứa và cảm giác có lỗi vì đã tự quyết.","Đá/vết nứt trong Vô Gian là phần thế giới bị Thiên Ngoại 'ăn dở'.", "Tu vi hiệu dụng tụt mạnh; main sống nhờ thân thể, chẻ củi/gánh nước/bắt gà skills.","Tỉnh một mình.","Thử dùng linh lực và suýt tự thiêu đạo cơ.","Học lấy năng lượng từ vận động/vật chất cực ít thay vì hút khí.","Tìm dấu một cộng đồng sống sót trong Vô Gian."),
    A(11,2,"Thanh Nghi Kiếm Các","Cho nữ chính có arc độc lập song song.","Thiên Mệnh săn nhóm; nhiều đồng minh muốn coi Tiểu Bảo đã chết và rút lui.","Thanh Nghi không sống để chờ; nàng biến đau thành mục tiêu cụ thể tìm đường vào Vô Gian.","Kiếm của nàng cảm được gió giới từ khe, manh mối duy nhất.","Thanh Nghi Hóa Thần/Vấn Thiên seed; nàng tự định 'kiếm của ta bảo vệ lựa chọn'.", "Nàng tập hợp người sống sót.","Từ chối đề nghị làm biểu tượng bù nhìn của phe chống Điện.","Lập Thanh Nghi Kiếm Các vừa đánh vừa nghiên cứu khe.","Tìm được chu kỳ bảy năm một lần Vô Gian có gió giới ngược."),
    A(11,3,"Bảy Năm Không Cùng Nhau","Time progression có các biến cố thật, không montage rỗng.","Tiểu Bảo xây quan hệ với cư dân Vô Gian; Thanh Nghi giữ liên minh ngoài không tan.","Hai tuyến cho thấy họ giữ ảnh hưởng của nhau nhưng không đóng băng cuộc sống.","Cư dân kể truyền thuyết về 'lò người' từng xuất hiện mỗi khi thế giới bị rách.","Tiểu Bảo tái cấu trúc tu luyện hướng Vấn Thiên không dựa linh khí; Thanh Nghi cũng tiến độc lập.","Năm 1–2: sống sót/lập Kiếm Các.","Năm 3–4: mỗi bên thất bại lớn riêng.","Năm 5–6: tìm cùng một loại ký hiệu từ hai phía.","Năm 7: chu kỳ gió giới tới; cả hai chuẩn bị mở đường."),
    A(11,4,"Gió Từ Bên Kia","Cho cả hai chủ động tạo reunion, không phép màu.","Mở khe cần tín hiệu đồng thời; sai nhịp sẽ xé nát người qua.","Mỗi người tin người kia còn sống dựa trên chứng cứ chứ không chỉ tình yêu thần kỳ.","Gió là motif lão què; nhịp gió giống bài gánh nước.","Tiểu Bảo Vấn Thiên: câu trả lời tạm 'ta muốn trở về' chứ chưa phải thiên hạ.","Hai bên gửi thử tín hiệu.","Ô Gia nhận ra một nhịp nhiệt trong gió.","Thanh Nghi chém đường, Tiểu Bảo từ trong luyện mép khe.","Một bàn tay xuyên được qua khe nhưng đường còn sập."),
    A(11,5,"Ta Về Rồi","Payoff thất lạc và xử lý hậu quả hành vi cũ.","Đường về chỉ mở ngắn; Thiên Mệnh phát hiện và tấn công bên ngoài.","Reunion: Thanh Nghi tát rồi ôm; hai người phải nói về việc Tiểu Bảo tự quyết hi sinh.","Tiểu Bảo mang ra một mảnh 'tro luật' chứng minh Thiên Ngoại có thật.","Vấn Thiên của Tiểu Bảo ổn, Thanh Nghi Vấn Thiên/Đạp Thiên seed.","Khe mở.","Tiểu Bảo vừa ra đã phải cùng nhóm chống đợt tấn công.","Sau trận mới có không gian reunion thật.","Hai người đặt lại nguyên tắc: trong tình huống không kịp bàn vẫn phải chấp nhận hậu quả, không dùng 'bảo vệ' làm lý do phủ quyền của người kia."),
    # V12
    A(12,1,"Đội Hình Sau Bảy Năm","Cho thấy mọi người đã đổi nhưng vẫn nhận ra nhau.","Hội Không Muốn Chết giờ có trách nhiệm/thuộc hạ riêng, không thể quay lại tuổi trẻ đơn giản.","Couple học thân mật sau khoảng cách thời gian thay vì reset về trước.","Tro luật tương tác với tàn phiến chiến trường.","Các nhân vật cập nhật cảnh giới hợp lý sau 7 năm; Tiểu Bảo không auto vượt hết.","Tái ngộ từng người.","Xung đột nhỏ do vai trò mới.","Tổ chức lại thành liên minh đánh Thiên Mệnh.","Chọn mục tiêu: kho trung tâm lưu dữ liệu hàng ngàn giới."),
    A(12,2,"Chiến Tranh Không Có Một Người Hùng","Xây chiến dịch nhiều mặt trận và agency đồng đội.","Muốn đánh Điện phải bảo vệ dân khỏi hạ tầng sập.","Tiểu Bảo/Thanh Nghi chia quyền chỉ huy, có bất đồng nhưng thống nhất qua dữ liệu.","Một số trạm Thiên Mệnh thực ra đang giữ phong ấn Thiên Ngoại.","Đạp Thiên setup; team synergy quan trọng hơn realm.","Lập bản đồ hệ thống.","Hồ thiết kế mạng thay thế; Ninh giải bài toán năng lượng; Sở lo liên minh.","Một mặt trận thất bại thật, gây tổn thất và buộc đổi kế hoạch.","Nhận ra phải chiếm lõi chứ không phá toàn mạng."),
    A(12,3,"Hạch Tâm Của Một Cái Lò","Reveal lớn Nhân Gian Lô là hạch Cửu Thiên.","Thiên Mệnh dùng hồ sơ cổ để dụ Tiểu Bảo tin mình sinh ra như vũ khí.","Thanh Nghi không phủ nhận đau của hắn bằng 'em tin anh'; nàng nhắc hắn quyền chọn hiện tại.","Hồ sơ: Cửu Thiên Hỏa Chủng được đặt vào đứa bé, cơ thể thích nghi thành Nhân Gian Lô.","Tiểu Bảo Đạp Thiên sơ bằng cách chấp nhận năng lực không định nghĩa con người.","Đột nhập kho lõi.","Tìm hồ sơ mười ba năm trước.","Tư Không Dạ cho xem bằng chứng thật lẫn framing.","Tiểu Bảo lấy được tọa độ Lạc Kê và hiểu muốn biết phần còn lại phải về nhà."),
    A(12,4,"Tư Không Dạ","Cho phản diện trung kỳ đối thoại triết lý và gần thắng.","Tư Không tin thu hoạch là giá nhỏ để giữ hàng nghìn giới khỏi Thiên Ngoại.","Cặp chính cùng phản biện từ trải nghiệm quyền lựa chọn, nhưng không có câu trả lời hoàn hảo ngay.","Thiên Ngoại đã ép Thiên Mệnh thành hệ thống nộp 'thuế thế giới'.", "Đạp Thiên chiến đấu; không tiêu diệt boss bằng realm áp đảo mà phá tính chính danh/mạng lưới.","Đối thoại trực tiếp.","Tư Không cho thấy nếu phá lõi ngay, phong ấn hàng trăm giới sẽ đổ.","Liên minh thực hiện takeover thay vì destroy.","Tư Không thua nhưng để lại tọa độ cảnh báo: thứ ngoài trời đã bắt đầu thức."),
    A(12,5,"Đường Về Lạc Kê","Kết chiến tranh Thiên Mệnh và chuyển về family truth.","Mạng lưới mới mong manh; các phe tranh quyền sau khi Điện sụp.","Thanh Nghi chọn đi cùng nhưng nhắc Tiểu Bảo phải tự hỏi gia đình, không để nàng trả lời thay.","Tàn phiến/tro luật/cái nồi cùng chỉ một điểm: Lạc Kê.","Không breakthrough; focus hậu quả/chuyển map.","Ổn định các giới vừa giải phóng.","Sở ở lại dẫn liên minh thay vì đi theo main mọi nơi.","Tiểu Bảo giao quyền, cho thấy trưởng thành không ôm hết việc.","Hắn và Thanh Nghi bước qua đường giới về quê."),
    # V13
    A(13,1,"Về Nhà Mà Không Biết Nhà Là Gì","Payoff homecoming vừa hài vừa bất an.","Dân làng cư xử như hắn chỉ đi vài hôm dù hắn đã thay đổi rất nhiều.","Thanh Nghi lần đầu chính thức bước vào 'gia đình' của Tiểu Bảo và bị cả làng soi.","Mỗi đồ vật quen lộ tầng không bình thường.","Các trưởng bối khóa aura nên cảnh giới không dùng làm thước; Tiểu Bảo nhận ra mình vẫn không nhìn thấu.","Tiểu Bảo về làng.","Bữa cơm hỗn loạn, elders hỏi chuyện Thanh Nghi.","Một sự cố nhỏ khiến Thôi tiện tay chém đứt pháp tắc như chặt xương.","Tiểu Bảo đặt bức họa cổ lên bàn và hỏi: mọi người là ai?"),
    A(13,2,"Làng Này Không Có Người Thường","Reveal danh tính elders nhưng giữ chiều sâu.","Mỗi người có lý do tránh kể quá khứ; Tiểu Bảo giận vì bị giấu.","Thanh Nghi giữ khoảng cách để gia đình tự nói, chỉ can thiệp khi Tiểu Bảo tự đổ lỗi.","Thôi=Sát Thần, Kỷ=Kiếm Tổ, Mạnh=Thái Âm Đạo Chủ, Hàn=Binh Tổ, Trư Bá=Yêu Hoàng.","Tiểu Bảo thấy khoảng cách realm thật và hiểu những bài tập tuổi thơ là đại đạo đã bóc hết huyền học.","Reveal từng người qua việc đời thường.","Tiểu Bảo vừa sốc vừa nhớ lại hàng loạt chuyện vô lý.","Hắn nổi giận vì cảm giác cuộc đời bị thiết kế.","Bà Mạnh nói: đúng, ban đầu họ có kế hoạch cho hắn."),
    A(13,3,"Cha Mẹ Ta Chỉ Là Người Thường","Chống trope huyết thống thần thánh và trả câu hỏi nguồn gốc.","Tiểu Bảo muốn một lý do đặc biệt cho cái chết cha mẹ nhưng sự thật giản dị đau hơn.","Thanh Nghi hiểu cảm giác bị biến thành chức năng và ở cạnh không giải hộ.","Cha mẹ là phàm nhân cứu người trong vết rách Thiên Ngoại; chết khi bảo vệ đứa bé khác/đứa con.","Không power gain; emotional progression là chính.","Kỷ kể ngày tìm thấy Tiểu Bảo.","Tiểu Bảo xem ký ức cha mẹ.","Biết họ không phải đại năng, chỉ là người chọn làm điều đúng.","Ba đồng tiền được tiết lộ là số tiền lẻ còn lại trong túi cha mẹ, elders giữ rồi đưa hắn ngày xuống núi."),
    A(13,4,"Đứa Trẻ Và Cái Lò","Reveal kế hoạch ban đầu và cái nồi.","Elders từng đặt Cửu Thiên Hỏa Chủng vào Tiểu Bảo để cứu thế, dù đứa bé không thể đồng ý.","Thanh Nghi nổi giận thay hắn nhưng để hắn tự quyết quan hệ với họ.","Hàn Luyện làm nồi đen thành van điều áp; Mạnh Dao phản đối kế hoạch từ ngày đầu.","Tiểu Bảo có thể mở Nhân Gian Lô sâu hơn nhưng từ chối làm ngay khi đang tức giận.","Kể kế hoạch hậu chiến.","Tranh luận đạo đức giữa elders, lộ họ không đồng lòng.","Tiểu Bảo hỏi nếu quay lại họ có làm nữa không; câu trả lời không đồng nhất và chân thật.","Kỷ nói sau mười ba năm họ đã quyết: dù thế giới chết, không ai được ép hắn nữa."),
    A(13,5,"Con Cháu Trong Nhà","Hòa giải không xóa sai lầm và chuẩn bị Cửu Thiên thật.","Tiểu Bảo phải chọn có tiếp tục gánh vấn đề mà người lớn từng đặt lên mình.","Thanh Nghi được elders công nhận không vì 'vợ tương lai' mà vì lựa chọn/kiếm của nàng.","Cửu Thiên từng là một; elders giữ tọa độ chín tàn vực.","Tiểu Bảo chủ động mở một tầng Nhân Gian Lô vì chính hắn muốn hiểu, không vì mệnh lệnh.","Những cuộc nói chuyện riêng với từng elder.","Ô Gia biết phong ấn huyết mạch do làng đặt để cứu nó.","Tiểu Bảo tha thứ một phần nhưng đặt ranh giới: mọi quyết định về cơ thể hắn từ nay phải do hắn.","Cả nhóm lên đường tìm mảnh hạch cuối trước khi Thiên Ngoại tới."),
    # V14
    A(14,1,"Chín Mảnh Một Bầu Trời","Khám phá Cửu Thiên Tàn Vực và lịch sử thật.","Các tàn vực có dân sống khác nhau, không thể đơn giản hợp lại bằng lực.","Cặp chính bàn về 'nhà' ở quy mô nhiều thế giới, liên hệ lựa chọn cá nhân.","Mỗi mảnh giữ một luật và ký ức chiến tranh khác nhau.","Tiểu Bảo/Thanh Nghi tiến gần Đạo Chủ nhưng chưa vượt vì cần hiểu chứ không farm.","Vào tàn vực đầu.","Thấy dân đã xây văn minh mới trên mảnh vỡ.","Thử ghép hai tàn luật gây thảm họa nhỏ, chứng minh hợp nhất không thể cưỡng ép.","Tìm manh mối mảnh lõi cuối nằm trong Tiên Đình."),
    A(14,2,"Lạc Kê Quán Ở Tiên Đình","Đưa hài lớn cuối trước chiến tranh và infiltrate bằng đời sống.","Tiên Đình giám sát người lạ; điều tra trực tiếp khó.","Thanh Nghi và Tiểu Bảo vận hành quán như couple, tạo domestic comedy trưởng thành.","Khách quán vô tình lộ các phe biết về mảnh lõi.","Không cần breakthrough; dùng kỹ năng xã hội/trí.","Mở quán làm vỏ.","Ô Gia ăn vụng hàng VIP, gây mối quan hệ với quan chức.","Quán thành nơi mọi phe tới vì đồ ăn/neutral ground.","Nhóm xác định mảnh lõi ở kho pháp tắc của Tiên Đình."),
    A(14,3,"Tiên Đình Không Có Một Ý Chí","Làm chính trị đa phe thay vì boss palace.","Phe bảo thủ muốn dùng mảnh lõi củng cố Tiên Đình; phe khác muốn trả tàn vực.","Thanh Nghi có quan hệ ngoại giao riêng với kiếm tu Tiên Đình.","Hồ sơ cho biết elders Lạc Kê từng là kẻ bị lịch sử chính thức xóa tên vì phản đối reset Cửu Thiên.","Thanh Nghi chạm Đạo Chủ Kiếm qua định nghĩa của riêng mình; Tiểu Bảo không cùng lúc.","Gặp phe cải cách.","Một phiên nghị sự biến thành bẫy.","Thanh Nghi thắng duel pháp lý/kiếm để giành quyền tiếp cận kho.","Họ thấy bản đồ ghi vùng 'Thiên Ngoại ăn mất' ngoài Cửu Thiên."),
    A(14,4,"Lịch Sử Bị Xóa","Hoàn thiện lịch sử Cửu Thiên và làm rõ sai lầm thế hệ trước.","Bản ghi của các phe mâu thuẫn; phải ghép nhiều nguồn.","Tiểu Bảo chia sẻ với Thanh Nghi nỗi sợ mình sẽ lặp lại người lớn khi có quyền quá lớn.","Cửu Thiên bị đánh vỡ; phe reset muốn hi sinh dân còn sống; Lạc Kê phản đối và giấu hạch.","Tiểu Bảo chạm Đạo Chủ của Nhân Gian Lô bằng hiểu biết 'luyện để nối, không luyện để xóa'.", "Đột nhập/được cấp quyền kho.","Đọc ba bản lịch sử khác nhau.","Ghép ra sự thật và vị trí lõi.","Lấy mảnh lõi nhưng cảm ứng ngay một thứ ngoài trời đã khóa tọa độ."),
    A(14,5,"Bầu Trời Nứt","Chuyển từ mystery sang chiến tranh Thiên Ngoại.","Tiên Đình chia rẽ về việc giao hạch để cầu hòa.","Cặp chính đứng cùng nhưng không có câu trả lời dễ.","Con mắt/thiết bị Thiên Ngoại xuyên bầu trời; lần đầu Mặc Vô Sinh lên tiếng.","Elders lộ sức Đạo Tổ để chắn cú thăm dò, trả giá thọ nguyên.","Dị tượng xuất hiện.","Thiên Ngoại gửi thông điệp không cần quân vào.","Một phe Tiên Đình cố giao Tiểu Bảo/mảnh lõi.","Mặc Vô Sinh tuyên bố thời hạn: giao hạch hoặc Cửu Thiên bị thu hoạch."),
    # V15
    A(15,1,"Lời Đề Nghị Rất Hợp Lý","Cho antagonist cuối trình bày logic sinh tồn thuyết phục.","Thiên Ngoại đề nghị cứu Tiểu Bảo, Thanh Nghi, Lạc Kê đổi lấy Cửu Thiên.","Thanh Nghi không trả lời thay; Tiểu Bảo hỏi 'còn người khác?'.", "Thiên Ngoại là văn minh cạn tài nguyên, ăn thế giới để duy trì hàng tỷ sinh linh của họ.","Không breakthrough; debate + strategic stakes.","Mặc Vô Sinh gặp trực tiếp qua hóa thân.","Cho xem bằng chứng các thế giới từng từ chối đã chết.","Một số phe cho rằng chấp nhận là đạo đức vì cứu được phần nhỏ.","Tiểu Bảo từ chối khi nghe người khác 'không liên quan tới ngươi'."),
    A(15,2,"Gọi Tất Cả Người Còn Sống","Mobilization không chỉ montage cameo.","Các phe cũ có lợi ích khác, không tự nhiên đoàn kết.","Thanh Nghi dẫn một chuỗi đàm phán riêng, chứng minh leadership.","Thiên Mệnh tàn dư có dữ liệu chiến đấu chống Thiên Ngoại và phải được quyết định có tin không.","Sở/Thanh Nghi/Hồ/Ninh tiến các mốc riêng; Tiểu Bảo học điều phối hạch.","Gửi lời kêu gọi.","Từng phe đưa điều kiện/hiềm khích.","Một cuộc tấn công thử buộc kẻ thù cũ cứu nhau.","Liên minh Cửu Thiên thành lập nhưng mong manh."),
    A(15,3,"Ba Mặt Trận","Cho chiến tranh chiến lược và thất bại thật.","Thiên Ngoại đánh đồng thời vào tàn vực, Tiên Đình, đường phàm giới.","Couple phải xa nhau theo nhiệm vụ nhưng không mất liên lạc cảm xúc.","Kẻ địch dùng công nghệ triệt luật, khắc chế Đạo Chủ.","Nhân Gian Lô không thể luyện triệt luật vô hạn; mỗi lần hấp thu làm hạch quá nhiệt.","Mặt trận 1 giữ dân.","Mặt trận 2 mất một thành lớn dù đã chuẩn bị.","Mặt trận 3 phản công giành được mẫu công nghệ.","Nhóm hiểu chiến tranh kéo dài chắc chắn thua vì tài nguyên."),
    A(15,4,"Người Già Ra Trận","Payoff elders Lạc Kê và cái giá thế hệ cũ.","Elders biết một trận có thể đổi mạng lấy thời gian, nhưng không ai muốn Tiểu Bảo lặp logic ép hi sinh.","Tiểu Bảo buộc phải tôn trọng lựa chọn của họ như Thanh Nghi từng buộc hắn tôn trọng Mộc.","Elders tiết lộ điểm yếu Thiên Ngoại: mạng lưới đồng bộ hóa năng lượng giữa các thế giới đã nuốt.","Một số Đạo Tổ tiêu tán thật; không hồi sinh toàn bộ sau đó.","Lạc Kê giữ cửa.","Từng elder có scene riêng trả motif dạy trẻ.","Một hoặc vài người hy sinh để phá mạng đồng bộ cục bộ.","Liên minh có cửa phản công duy nhất nhưng thời gian rất ngắn."),
    A(15,5,"Trước Ngày Không Còn Trời","Đẩy mọi state tới trận cuối.","Thiên Ngoại mở thiết bị thu hoạch chính; Cửu Thiên bắt đầu mất ánh sáng/luật.","Tiểu Bảo/Thanh Nghi có đêm yên ngắn không phải scene sex quota mà là nói về nếu không sống sót.","Hạch cho thấy hai lựa chọn: reset Cửu Thiên hoặc thử nối chín mảnh chưa ai làm.","Tiểu Bảo đạt ngưỡng Giới Chủ nhưng chưa hoàn thiện; Thanh Nghi Đạo Chủ đỉnh.","Chuẩn bị tổng phản công.","Phát hiện phương án reset từ người xưa nhanh hơn và tỷ lệ thành công cao.","Tiểu Bảo không quyết ngay vì cái giá chưa rõ hết.","Thiên Ngoại bắt đầu thu hoạch; Quyển 16 mở giữa chiến tranh."),
    # V16
    A(16,1,"Ngày Cửu Thiên Rơi","Mở final battle bằng hậu quả quy mô lớn nhưng giữ POV người cụ thể.","Các tuyến phòng thủ gãy; thời gian giới hạn.","Cặp chính chiến chung ở vài cảnh nhưng cũng tin đồng đội gánh phần riêng.","Reset protocol bắt đầu tự hiện khi Nhân Gian Lô gần hạch.","Tiểu Bảo bước Giới Chủ tạm thời qua cộng hưởng, không phải thống trị tuyệt đối.","Mặt trận sụp.","Sở/Hồ/Ninh/Ô Gia giữ các nút để Tiểu Bảo vào lõi.","Mặc Vô Sinh đẩy main tới lựa chọn reset.","Lò mở hoàn toàn và cho Tiểu Bảo thấy giá của phương án dễ."),
    A(16,2,"Một Thế Giới Hoàn Mỹ Không Có Người","Đặt quyết định đạo đức cuối trước quyết chiến.","Reset sẽ xóa sinh linh hiện tại nhưng tạo Cửu Thiên hoàn chỉnh đủ chống Thiên Ngoại.","Thanh Nghi nói nàng sẽ không bảo hắn chọn gì; nàng chỉ yêu cầu hắn nhớ người đang sống.","Đây là kế hoạch gốc của một phe cổ; Lạc Kê từng chống nó.","Tiểu Bảo hiểu quyền Giới Chủ không phải quyền sở hữu người khác.","Xem mô phỏng reset.","Mặc Vô Sinh lập luận đây là toán học sinh tồn.","Tiểu Bảo nhớ cha mẹ phàm, Mộc, ba đồng, bữa cơm.","Hắn nói không và chọn phương án nối thế giới cực khó."),
    A(16,3,"Ta Không Luyện Trời, Ta Luyện Đường Về","Thực hiện giải pháp thứ ba đã foreshadow từ Nhân Gian Lô/đường nối.","Nối chín mảnh cần mọi tàn vực tự đồng thuận/cấp lực, không thể cưỡng ép.","Thanh Nghi dùng kiếm mở 'đường', Tiểu Bảo dùng lò nung mép nối; partnership cuối là cơ chế thật.","Motif gió nối chín giới; tàn luật từng không tương thích được luyện thành khớp chứ không đồng hóa.","Thanh Nghi chạm Đạo Tổ trong kiếm của mình; Tiểu Bảo ổn định Giới Chủ qua consent của các giới.","Gửi yêu cầu tới chín mảnh.","Có một mảnh từ chối vì sợ bị nuốt, buộc phải thuyết phục bằng hành động.","Nối mảnh đầu gây phản chấn gần chết.","Chín luồng gió cuối cùng bắt đầu thông nhau."),
    A(16,4,"Trận Cuối Không Có Tiên Đế","Đánh bại cơ chế thu hoạch và Mặc Vô Sinh mà không phủ nhận sinh linh Thiên Ngoại.","Nếu phá toàn mạng Thiên Ngoại, hàng tỷ sinh linh bên họ cũng có thể chết; lặp bài toán đạo đức.","Tiểu Bảo/Thanh Nghi chọn cắt khả năng ăn thế giới, không diệt sạch văn minh đối phương.","Mạng đồng bộ yếu từ sacrifice của elders là chìa khóa.","Không thêm cảnh giới mới; dùng toàn bộ payoff kỹ năng/đồng minh.","Liên minh đánh vào mạng đồng bộ.","Mặc Vô Sinh gần thắng khi buộc Tiểu Bảo chọn diệt họ hoặc thua.","Nhóm tách nguồn khỏi thế giới bị nuốt và khóa cổng, buộc Thiên Ngoại phải tìm cách sống khác.","Chiến tranh kết thúc; Tiểu Bảo từ chối lời mời đăng vị Tiên Đế."),
    A(16,5,"Về Nhà Ăn Cơm","Hậu chiến 10 chương đóng nhân vật, motif và thế giới.","Xây lại khó hơn thắng; người chết không quay lại; quyền lực sau chiến thắng có nguy cơ biến thành đế chế mới.","Ch791–795 hôn lễ Lạc Kê; Ch796–799 đời sống/hậu chiến; Ch800 epilogue cặp đôi già hơn nhưng vẫn là họ.","Cửu Thiên không thành một khối đồng nhất; chín mảnh được nối bằng đường giới tự nguyện.","Không power progression; progression là buông quyền và sống.","Ch791 chuẩn bị hôn lễ hỗn loạn.","Ch795 bữa cưới và ba đồng tiền/cái nồi payoff.","Ch796–799 tưởng niệm, tái thiết, Thanh Nghi mở kiếm viện, Tiểu Bảo mở Lạc Kê Quán.","Ch800: đứa trẻ hỏi vì sao cứu Cửu Thiên; Thanh Nghi gọi ăn cơm; Tiểu Bảo trả lời vì muốn về nhà ăn cơm."),
]

BEATS = [
    ("Mở Cửa", "setup", "Thiết lập tình trạng mới và mục tiêu cụ thể của sub-arc; dùng opening làm set-piece đầu."),
    ("Một Việc Không Đúng", "complication", "Đưa chi tiết lệch chuẩn đầu tiên khiến kế hoạch ban đầu khó hơn; conflict phải hiện thành hành động."),
    ("Giá Của Một Lựa Chọn", "choice", "Buộc nhân vật chọn giữa hai lợi ích thật, đồng thời đẩy character/romance beat tiến một nấc."),
    ("Dấu Vết", "investigation", "Đưa bằng chứng mystery/foreshadow cụ thể nhưng chưa giải quá mốc; tăng câu hỏi đúng hướng."),
    ("Giữa Đường", "midpoint", "Set-piece midpoint theo nội dung midpoint; thay đổi cách hiểu mục tiêu hoặc thế trận."),
    ("Không Thể Đi Như Cũ", "setback", "Cho đối phương/hoàn cảnh phản công thật; phải mất tài nguyên, vị trí, niềm tin hoặc thời gian."),
    ("Đổi Cách Chơi", "counterplan", "Nhân vật dùng điều đã học để thiết kế cách phản công mới; không deus ex machina."),
    ("Người Đứng Cạnh", "character", "Đẩy quan hệ/agency nhân vật phụ trong khi áp lực bên ngoài tiếp tục; romance chỉ theo mốc canon."),
    ("Đụng Mặt", "climax", "Thực hiện climax của sub-arc; chiến thắng/thất bại phải tuân power + cost đã ghi."),
    ("Sau Khi Bụi Lắng", "payoff", "Trả payoff, cập nhật state và mở hook sang sub-arc kế; không reset hậu quả."),
]


def build_chapter(arc, local_idx, chap_num):
    suffix, function, generic = BEATS[local_idx - 1]
    focus_map = {
        1: arc["opening"],
        2: arc["conflict"],
        3: arc["romance"],
        4: arc["mystery"],
        5: arc["midpoint"],
        6: arc["conflict"],
        7: arc["goal"],
        8: arc["romance"],
        9: arc["climax"],
        10: arc["payoff"],
    }
    focus = focus_map[local_idx]
    chapter = {
        "chapter": chap_num,
        "volume": arc["volume"],
        "volume_title": VOLUME_TITLES[arc["volume"]],
        "subarc": f"V{arc['volume']:02d}A{arc['arc_in_volume']}",
        "subarc_title": arc["title"],
        "title": f"Chương {chap_num}: {arc['title']} — {suffix}",
        "title_status": "provisional_until_batch_draft",
        "beat_function": function,
        "objective": f"{generic} Trọng tâm riêng chương: {focus}",
        "conflict": arc["conflict"],
        "character_beat": arc["romance"],
        "mystery_beat": arc["mystery"],
        "power_guardrail": arc["power"],
        "foreshadow_or_payoff": (
            arc["mystery"] if local_idx in {1,4,5,10} else arc["payoff"] if local_idx == 9 else "Giữ continuity; không reveal ngoài mốc sub-arc."
        ),
        "cliffhanger_type": ["arrival","anomaly","choice","evidence","reversal","consequence","plan","emotional_shift","impact","transition"][local_idx-1],
        "status": "planned",
        "draft_file": f"chapters/chapter_{chap_num:03d}.md",
    }
    if chap_num == 800:
        chapter["title"] = "Chương 800: Ta Chỉ Muốn Về Nhà Ăn Cơm"
        chapter["title_status"] = "locked"
        chapter["objective"] = "Epilogue: một đứa trẻ hỏi Tạ Tiểu Bảo vì sao từng cứu Cửu Thiên; hắn từ chối mọi mỹ từ, nghe Lục Thanh Nghi gọi ăn cơm và trả lời rằng hắn chỉ muốn về nhà ăn cơm. Cái nồi đen trở lại đúng chức năng nấu bữa tối; gió nối chín giới thổi qua Lạc Kê."
        chapter["cliffhanger_type"] = "closure"
    return chapter


def main():
    assert len(ARCS) == 80, len(ARCS)
    chapters = []
    for arc_idx, arc in enumerate(ARCS):
        for local_idx in range(1, 11):
            chap_num = arc_idx * 10 + local_idx
            chapters.append(build_chapter(arc, local_idx, chap_num))
    assert len(chapters) == 800
    assert [c["chapter"] for c in chapters] == list(range(1, 801))
    payload = {
        "title": "Ta Chỉ Muốn Ăn No, Sao Lại Thành Tiên Đế?",
        "version": 1,
        "chapter_count": 800,
        "volume_count": 16,
        "subarc_count": 80,
        "note": "Titles are planning titles and are refined before each 5-chapter prose batch; locked canon events and reveal order come from Story Bible + subarc fields.",
        "arcs": ARCS,
        "chapters": chapters,
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {OUT} with {len(chapters)} chapters and {len(ARCS)} sub-arcs")

if __name__ == "__main__":
    main()
