import json
import os

# Define the novel metadata
novel = {
    "title": "Cô Vợ Hào Môn Khinh Tôi Vô Dụng, Cả Hà Ngoại Biết Tôi Là Chủ Tịch Tập Đoàn Thép",
    "subtitle": "Chủ Tịch Thép Ẩn Thân",
    "author": "Đông Hải Cư Sĩ",
    "genre": "Sảng Văn",
    "intro": "<p><strong>\"Anh chỉ là một gã kỹ thuật viên quèn quanh năm bám đầy bụi lò cao và dầu mỡ của máy nén thử tải kéo. Lê Gia chúng tôi là hào môn Hà Ngoại, không dung nạp loại phế vật như anh!\"</strong></p><p>Trần Đông Hải khẽ ký vào tờ đơn ly hôn đơn phương, thu dọn chiếc hộp thiếc rỉ sét đựng cây bút mực cũ kỹ, rồi lặng lẽ bước ra khỏi biệt thự Vinhomes Riverside giữa cơn mưa phùn lạnh giá.</p><p>Họ không hề biết rằng, 80% lượng thép cường độ cao CB400-V và cấu kiện SS400 chịu lực đang neo giữ móng tòa siêu dự án Hà Ngoại Sky Line đều thuộc quyền sinh sát của Tập đoàn Thép Đông Hải do anh đứng đầu.</p><p>Càng không biết rằng, khoản nợ gốc khổng lồ 1.200 tỷ đồng tại Agribank Chi nhánh Hà Ngoại đang đè nặng lên cổ Lê Gia thực chất đã được anh âm thầm mua lại.</p><p>Khi vương giả quy lai, cả Hà Ngoại chấn động, kẻ kiêu ngạo chỉ có thể quỳ gối khóc than trong tiếc nuối muộn màng.</p>",
    "cover_prompt": "A high-end book cover, highly detailed web novel illustration style, a powerful and handsome young Vietnamese man in a sharp navy suit, standing near a high-tech steel smelting furnace with sparks flying in a modern industrial setting. Beside him is a beautiful female luxury lawyer in professional clothes. In the background are giant industrial structures and modern Hanoi skyline. Cinematic neon lighting, rich dramatic shadows, premium colors.",
    "chapters": []
}

# Chapter 1 lines (Target ~1300-1400 words, strictly >= 1100)
chap1_lines = [
    "Cơn mưa phùn cuối đông ở vùng Hà Ngoại mang theo cái lạnh thấu xương thấu tủy.",
    "Những rặng chà là trồng dọc theo bờ kênh nhân tạo của khu biệt thự Vinhomes Riverside Long Biên rủ lá xám xịt dưới bầu trời chì nặng trĩu.",
    "Trong căn biệt thự đơn lập trị giá hơn trăm tỷ đồng của Lê gia, không khí bên trong còn đóng băng hơn cả thời tiết ngoài trời.",
    "Trần Đông Hải ngồi lặng lẽ dưới tầng hầm ẩm thấp, nơi anh tự tay cải tạo thành một phòng thí nghiệm cơ tính mini.",
    "Tiếng động duy nhất phát ra là tiếng rên rỉ cơ khí nhè nhẹ từ chiếc máy nén thủy lực kiểm định mẫu tải trọng kéo một trăm tấn.",
    "Bàn tay thô ráp của Đông Hải bám đầy dầu bôi trơn chuyên dụng dùng cho hệ thống lò thổi oxy khổng lồ.",
    "Anh đang chăm chú dùng thước kẹp panme đo đạc giới hạn chảy của một thanh thép cacbon kết cấu mác SS400 bị nứt gãy.",
    "Đôi mắt anh bình thản, sâu thẳm như giếng cổ, hoàn toàn phớt lờ những tiếng bước chân dồn dập, kiêu ngạo đang đi xuống cầu thang.",
    "\"Trần Đông Hải! Anh vẫn còn tâm trí ngồi ôm đống sắt vụn phế thải này được sao?\"",
    "Một giọng nói chói tai, đầy sự khinh miệt vang lên từ phía lối đi tối tăm.",
    "Lê Quốc Bảo - cậu em vợ ăn chơi trác táng của anh - bước xuống với đôi giày da cá sấu bóng loáng.",
    "Hắn thản nhiên dùng mũi giày đá mạnh vào chiếc hộp dụng cụ bằng thép không gỉ đặt bên cạnh chân Đông Hải.",
    "Tiếng kim loại va chạm loảng xoảng vang dội trong không gian hầm chật hẹp, nhưng nét mặt Đông Hải không hề có một chút gợn sóng.",
    "\"Nhìn cái bộ dạng lấm lem bùn đất, dầu mỡ lò cao rỉ sét này của anh xem, thật làm bẩn mắt người khác!\"",
    "Quốc Bảo khoanh tay trước ngực, hếch cằm lên trời đầy ngạo mạn.",
    "\"Chị gái tôi đường đường là Tổng giám đốc Công ty Bất động sản Lê Gia, xinh đẹp sắc sảo đứng top đầu giới thượng lưu Hà Ngoại.\"",
    "\"Vậy mà lại phải gánh vác một gã chồng phế vật, chỉ biết làm kỹ thuật viên quèn chuyên lau chùi máy móc như anh!\"",
    "\"Anh có biết hôm nay là ngày gì không? Dự án Hà Ngoại Sky Line đang đứng trước bờ vực đổ vỡ vì thiếu thép chịu lực cường độ cao!\"",
    "\"Trong khi cả gia đình họ Lê đang vắt óc suy nghĩ tìm cách cứu vãn, thì anh lại chui lủi dưới này nghịch mấy thanh sắt vụn!\"",
    "Đông Hải khẽ đặt chiếc thước kẹp xuống tấm giẻ lau, ngẩng đầu lên nhìn gã em vợ bằng ánh mắt lạnh lùng.",
    "Sự bình tĩnh đến đáng sợ của anh khiến Quốc Bảo thoáng chút rùng mình, nhưng ngay lập tức bị sự kiêu ngạo khỏa lấp.",
    "Chưa kịp để Quốc Bảo lên tiếng sỉ vả tiếp, một bóng hình kiêu sa kiều diễm đã xuất hiện ở đầu cầu thang.",
    "Lê Mỹ Hạnh bước xuống, diện chiếc đầm dạ hội đen tuyền may đo thủ công từ thương hiệu xa xỉ của Pháp.",
    "Gương mặt cô thanh tú, đôi môi tô son đỏ thẫm kiêu kỳ, nhưng ánh mắt nhìn Đông Hải lại tràn ngập sự thất vọng và lạnh nhẽo.",
    "Cô không nói một lời, thản nhiên ném một tập tài liệu bọc da mỏng xuống mặt bàn gỗ bám đầy bụi dầu mỡ máy cán nóng.",
    "Trên trang bìa hiển thị dòng chữ in đậm rõ ràng: \"ĐƠN PHƯƠNG XIN LY HÔN VÀ THỎA THUẬN PHÂN CHIA TÀI SẢN\".",
    "\"Ký đi, Trần Đông Hải. Tôi đã ký sẵn phần của mình rồi.\"",
    "Giọng nói của Lê Mỹ Hạnh đều đều, lạnh lùng như đang đọc một bản báo cáo tài chính thường niên.",
    "Đông Hải nhìn lướt qua tập hồ sơ ly hôn rẻ tiền đó, khóe môi khẽ nhếch lên một đường cong chế giễu vô hình.",
    "\"Lý do là gì? Ba năm qua, tôi chưa từng làm điều gì có lỗi với cô hay Lê gia.\"",
    "Giọng nói của anh trầm thấp, vững chãi như tiếng chuông đồng cổ, vang vọng khắp bốn bức tường bê tông cốt thép.",
    "Lê Mỹ Hạnh hít một hơi thật sâu, ngực phập phồng dưới lớp vải lụa đắt tiền, ánh mắt lộ rõ vẻ sốt ruột.",
    "\"Đông Hải, anh là người tốt, nhưng thực tế cuộc sống này quá tàn nhẫn đối với những kẻ chỉ biết làm kỹ thuật quèn.\"",
    "\"Lê Gia hiện tại không còn là một doanh nghiệp địa phương nhỏ bé của ba năm trước nữa.\"",
    "\"Dự án siêu đô thị Hà Ngoại Sky Line trị giá hàng ngàn tỷ đồng của chúng tôi đang bị Agribank Chi nhánh Hà Ngoại siết nợ gốc 1.200 tỷ.\"",
    "\"Bên cạnh đó, toàn bộ nguồn cung thép thanh vằn cường độ cao CB400-V cho phần móng tòa tháp đã bị đứt gãy hoàn toàn.\"",
    "\"Nếu không có dòng vốn mới và nguồn cung thép chuẩn kỹ thuật, Lê Gia sẽ phá sản, tôi sẽ phải ngồi tù vì nợ nần chồng chất.\"",
    "\"Trong lúc tôi cần một người đàn ông có quyền thế, có mối quan hệ để đứng ra gánh vác phong ba bão táp cùng tôi...\"",
    "\"Thì anh làm được gì? Anh chỉ biết ngồi đây đo đạc mấy mác thép SS400 vô giá trị này sao?\"",
    "\"Anh có thể giúp tôi giải quyết khoản nợ 1.200 tỷ tại Nông Ngân không? Hay anh có thể hô biến ra hàng vạn tấn thép chịu lực đạt chuẩn Bộ Xây dựng?\"",
    "Mỹ Hạnh càng nói càng kích động, những dồn nén ấm ức suốt ba năm qua như dòng nước lũ vỡ đê thoát ra ngoài.",
    "Quốc Bảo đứng bên cạnh lập tức phụ họa, vẻ mặt đắc ý tột cùng.",
    "\"Đúng vậy! Chị tôi đã tìm được lối thoát rồi! Thiếu gia Trịnh Khắc Huy của Tập đoàn Bất động sản Thịnh Phát đã hứa sẽ giúp đỡ!\"",
    "\"Anh Huy có hạn mức tín dụng khổng lồ tại Agribank, lại có mối quan hệ mật thiết với các đại lý thép lớn ở vùng biên giới.\"",
    "\"Chỉ cần chị tôi ly hôn với gã phế vật nhà nghèo như anh và kết hôn với anh Huy, Lê Gia sẽ lập tức hóa rồng!\"",
    "\"Anh Huy là rồng phượng trong loài người, đi xe Rolls-Royce Phantom, tay đeo đồng hồ Patek Philippe cả tỷ bạc.\"",
    "\"Còn anh? Anh nhìn lại bộ quần áo bảo hộ lao động xanh bạc màu, bốc mùi dầu mỡ blast furnace này của mình đi!\"",
    "\"Anh đứng cạnh chị tôi chỉ làm trò cười cho cả giới thượng lưu Hà Ngoại mà thôi!\"",
    "Đông Hải khẽ khép mắt lại, trong đầu anh hiện lên những ký ức của ba năm trước.",
    "Khi Lê Gia chỉ là một nhà thầu xây dựng nhỏ bên bờ sông Đuống, bị giang hồ siết nợ, chính anh đã âm thầm dùng thế lực của mình cứu họ.",
    "Anh chấp nhận che giấu thân phận, làm một người chồng ở rể bình lặng, chỉ vì muốn trả ơn nghĩa cứu mạng của người cha quá cố của Mỹ Hạnh.",
    "Nhưng lòng tham và sự phù phiếm của hào môn Hà Ngoại đã hoàn toàn tha hóa người con gái thuần khiết năm xưa.",
    "\"Thịnh Phát... Trịnh Khắc Huy sao?\" Đông Hải khẽ mở mắt, ánh mắt anh lóe lên tia sáng lạnh lẽo như thép tôi trong bể dầu.",
    "\"Lê Mỹ Hạnh, cô thực sự tin rằng gã Trịnh Khắc Huy đó có thể giải quyết được đống hỗn độn của Lê gia sao?\"",
    "\"Cô có từng tự hỏi, tại sao Agribank lại đột ngột phong tỏa khoản nợ 1.200 tỷ ngay trước khi các người đổ móng dự án không?\"",
    "Lê Mỹ Hạnh khẽ biến sắc, nhưng sự kiêu ngạo lấn át khiến cô lập tức gạt đi sự nghi ngờ.",
    "\"Anh câm miệng đi! Trần Đông Hải, anh không giúp được gì thì đừng ở đây dùng cái đầu óc hạn hẹp của kẻ nghèo hèn để suy đoán!\"",
    "\"Quyết định của tôi là tuyệt đối. Hãy ký vào đơn ly hôn và bước ra khỏi Lê gia với chút tự trọng cuối cùng của anh đi!\"",
    "Đông Hải im lặng nhìn Mỹ Hạnh trong vài giây, rồi khẽ thở dài một tiếng thật nhẹ.",
    "\"Được, nếu đây là con đường cô tự chọn, tôi tôn trọng nó.\"",
    "Anh vươn tay mở chiếc hộp thiếc rỉ sét đặt trên bàn, lấy ra cây bút mực Pelikan cũ kỹ màu xanh lá cây.",
    "Đó là cây bút anh dùng để ký hợp đồng thành lập Tập đoàn Thép Đông Hải mười năm trước, khi anh đặt những viên gạch đầu tiên cho đế chế thép của mình.",
    "Đặt bút xuống tờ đơn ly hôn rẻ tiền, Đông Hải ký một đường sắc lẹm, dứt khoát như nhát chém của lưỡi dao cắt thép thủy lực.",
    "\"Xong rồi. Từ nay về sau, Trần Đông Hải tôi và Lê gia các người không còn bất kỳ mối liên hệ nào nữa.\"",
    "Anh đứng dậy, tháo chiếc áo bảo hộ lao động lấm lem dầu mỡ ra, để lộ chiếc áo sơ mi trắng phẳng phiu bên trong.",
    "Dù quần áo đơn giản, nhưng bờ vai rộng, vóc dáng cao lớn và khí chất uy nghiêm toát ra từ anh khiến hai chị em Lê gia bất giác lùi lại một bước.",
    "Đông Hải khẽ cầm chiếc hộp thiếc rỉ sét lên, bước qua người Quốc Bảo mà không thèm liếc mắt nhìn hắn lấy một cái.",
    "\"Đồ kiêu ngạo! Để xem sau khi rời khỏi Lê gia, anh lấy gì để sống ở mảnh đất Hà Ngoại này!\" Quốc Bảo hét lớn sau lưng anh để vớt vát thể diện.",
    "Lê Mỹ Hạnh nhìn theo bóng lưng thẳng tắp của người chồng cũ đang bước dần ra ngoài cơn mưa phùn lạnh giá.",
    "Trái tim cô đột nhiên nhói lên một nhịp, một cảm giác bất an cực hạn dâng trào trong lòng, giống như cô vừa tự tay vứt bỏ đi báu vật vô giá nhất cuộc đời.",
    "Nhưng khi nhìn thấy tờ đơn ly hôn đã có chữ ký của Đông Hải nằm trên bàn, cô lại tự trấn an bản thân.",
    "\"Mỹ Hạnh, mày làm đúng rồi. Vì tương lai của Lê gia, mày không thể bị trói buộc bởi một gã kỹ thuật viên quèn vô dụng.\"",
    "Bên ngoài biệt thự, Trần Đông Hải ngửa mặt lên nhìn bầu trời xám xịt của Hà Ngoại, những giọt mưa lạnh buốt rơi trên mặt anh.",
    "Anh bấm số điện thoại gọi đi, giọng nói khôi phục lại sự lạnh lùng, uy nghiêm của một vị hoàng đế nắm giữ huyết mạch ngành công nghiệp nặng.",
    "\"Hoàng Nam, chuẩn bị xe. Tôi quay lại tổng bộ.\"",
    "\"Ngoài ra, thông báo cho phía Agribank Hà Ngoại, kế hoạch siết nợ đặc biệt đối với Lê Gia có thể bắt đầu vận hành.\"",
    "\"Tôi muốn xem, không có dòng thép của Đông Hải Steel, tòa tháp Hà Ngoại Sky Line của họ sẽ đứng vững bằng niềm tin của Trịnh Khắc Huy như thế nào.\"",
    "Đầu dây bên kia vang lên giọng nói vô cùng kính cẩn của người trợ lý cấp cao.",
    "\"Tuân lệnh Chủ tịch! Toàn bộ hệ thống lò thổi oxy và mười vạn tấn thép thành phẩm mác CB400-V đã sẵn sàng theo ý ngài!\""
]

# Chapter 2 lines (Target ~1300-1400 words, strictly >= 1100)
chap2_lines = [
    "Tại phòng họp VIP tầng cao nhất của trụ sở Công ty Bất động sản Lê Gia tại quận Long Biên, bầu không khí căng thẳng đến nghẹt thở.",
    "Những tấm kính cường lực lớn nhìn ra dòng sông Hồng cuộn đỏ và cây cầu Đông Trù sừng sững không thể làm giảm đi sự ngột ngạt bên trong.",
    "Lê Mỹ Hạnh và Lê Quốc Bảo đang ngồi khúm núm ở một bên bàn họp mặt kính dài.",
    "Đối diện họ là một người phụ nữ có khí chất lạnh lùng, áp đảo toàn bộ không gian phòng họp.",
    "Trịnh Băng Dao - đối tác quản lý của hãng luật quốc tế danh tiếng Baker & Partners chi nhánh Hà Nội.",
    "Cô diện bộ vest may đo thủ công màu xám tro từ chất liệu len cao cấp Savile Row, mái tóc đen nhánh búi cao gọn gàng sau gáy.",
    "Đôi mắt cô sắc bén như dao mổ, ẩn sau cặp kính gọng titanium thanh mảnh.",
    "Mỗi cử chỉ của Trịnh Băng Dao, từ cách lật tài liệu đến cách đặt chiếc bút ký Montblanc xuống bàn, đều toát lên sự chuyên nghiệp và lạnh lùng tột độ.",
    "Cô đang thực hiện quy trình due diligence - thẩm định pháp lý và cấu trúc nợ đặc biệt cho dự án Hà Ngoại Sky Line.",
    "\"Luật sư Trịnh, tình hình hồ sơ của Lê gia chúng tôi thế nào rồi ạ?\" Lê Mỹ Hạnh cẩn trọng lên tiếng, giọng nói có phần run rẩy.",
    "Cô hoàn toàn không còn vẻ kiêu ngạo, lẫm liệt như lúc đối xử với Trần Đông Hải dưới tầng hầm biệt thự.",
    "Trước mặt cô lúc này là vị nữ luật sư thượng lưu có mức phí tư vấn lên tới hàng ngàn USD mỗi giờ, người nắm giữ vận mệnh pháp lý của dự án.",
    "Trịnh Băng Dao không vội trả lời, cô thong thả nhấp một ngụm trà Earl Grey nóng hổi.",
    "Tiếng chiếc tách sứ chạm khẽ vào đĩa đựng kêu \"cộp\" một tiếng thanh mảnh, vang lên giữa phòng họp im phăng phắc như một tiếng sấm.",
    "\"Tổng giám đốc Lê, tôi phải thẳng thắn chia sẻ rằng, tình hình của Lê Gia tệ hơn rất nhiều so với những gì cô báo cáo trong hồ sơ sơ bộ.\"",
    "Băng Dao dùng ngón tay sơn đỏ gõ nhẹ lên tập tài liệu dày cộp bọc da màu xanh hải quân.",
    "\"Khoản nợ gốc 1.200 tỷ đồng của các người tại Agribank Chi nhánh Hà Ngoại đã bị phân loại vào nhóm 4 - nợ nghi ngờ mất vốn.\"",
    "\"Lý do là tài sản thế chấp - chính là quyền sử dụng đất của dự án Hà Ngoại Sky Line - đang bị tranh chấp ranh giới địa chính.\"",
    "\"Thêm vào đó, dòng tiền từ đợt mở bán căn hộ hình thành trong tương lai của các người đã bị phong tỏa tạm thời do thiếu chứng nhận kiểm định kết cấu.\"",
    "Lê Quốc Bảo đứng ngồi không yên, mồ hôi hột rịn ra đầy trên trán, hắn vội vàng cướp lời.",
    "\"Luật sư Trịnh, chuyện đó chỉ là thủ tục hành chính nhỏ nhặt thôi! Chúng tôi đã liên hệ với Tập đoàn Thịnh Phát rồi!\"",
    "\"Thiếu gia Trịnh Khắc Huy đã hứa sẽ dùng uy tín cá nhân để bảo lãnh khoản nợ này tại Agribank, đồng thời rót thêm 500 tỷ vốn lưu động!\"",
    "Trịnh Băng Dao khẽ ngước mắt lên nhìn Quốc Bảo, ánh mắt lạnh lẽo không một chút cảm xúc khiến hắn lập tức câm lặng.",
    "\"Lê phó giám đốc, anh quá ngây thơ hay thực sự không hiểu gì về tài chính doanh nghiệp cấp độ cao?\"",
    "\"Uy tín cá nhân của một thiếu gia chơi bời có thể thay thế được quy trình thẩm định nợ gốc của ngân hàng quốc doanh lớn nhất Việt Nam sao?\"",
    "\"Hơn nữa, báo cáo thẩm định kỹ thuật của tôi cho thấy một lỗ hổng chí mạng có thể đưa toàn bộ ban lãnh đạo Lê Gia vào vòng lao lý.\"",
    "Băng Dao rút ra một tập tài liệu phân tích quang phổ cơ tính của mẫu thép móng công trình Hà Ngoại Sky Line.",
    "\"Toàn bộ cấu kiện thép mà các người đã đóng cọc thử tải cho phần móng tháp chính không đạt mác CB400-V chịu lực cường độ cao như thiết kế.\"",
    "\"Các người đang sử dụng loại thép cacbon thấp SS400 thông thường, thậm chí là thép cán nóng chất lượng thấp nhập lậu qua biên giới.\"",
    "\"Loại thép này chỉ có giới hạn chảy tối thiểu khoảng 245 MPa, trong khi thiết kế chịu lực của móng tháp bắt buộc phải là CB400-V với giới hạn chảy trên 400 MPa.\"",
    "\"If đổ bê tông lên đống sắt vụn SS400 đó, tòa nhà 50 tầng này sẽ sụp đổ ngay khi xây dựng đến tầng thứ 20!\"",
    "\"Đây không còn là vấn đề tài chính nữa, đây là tội ác hủy hoại công trình an toàn quốc gia! Bộ Xây dựng sẽ niêm phong dự án này vĩnh viễn!\"",
    "Lời nói của Trịnh Băng Dao như những nhát búa tạ gõ thẳng vào ngực Lê Mỹ Hạnh.",
    "Sắc mặt cô cắt không còn một giọt máu, hai bàn tay nắm chặt vào nhau đến mức các đốt ngón tay trắng bệch.",
    "\"Không... không thể như thế được! Cậu Bảo, chuyện này là sao? Chẳng phải em nói số thép móng đó đã qua kiểm định rồi sao?\"",
    "Mỹ Hạnh quay sang chất vấn em trai bằng giọng hoảng loạn tột cùng.",
    "Quốc Bảo lúng túng, lắp bắp không ra hơi: \"Chị... chị ơi... số thép đó là do anh Trịnh Khắc Huy giới thiệu nguồn hàng giá rẻ...\"",
    "\"Họ bảo giấy tờ CO/CQ (chứng nhận xuất xứ và chất lượng) đều đầy đủ cả, em nghĩ tiết kiệm được vài chục tỷ tiền nguyên liệu nên mới...\"",
    "\"Ngu xuẩn!\" Lê Mỹ Hạnh giơ tay tát mạnh một cái vào mặt Lê Quốc Bảo.",
    "Tiếng chát chúa vang dội trong phòng họp, Quốc Bảo ôm mặt không dám ho he một lời.",
    "Trịnh Băng Dao lạnh lùng chứng kiến màn kịch gia đình này, khóe môi khẽ cong lên đầy châm biếm.",
    "\"Tổng giám đốc Lê, khóc lóc hay đánh đập lúc này không giải quyết được vấn đề gì cả.\"",
    "\"Hiện tại, ở miền Bắc chỉ có duy nhất một đơn vị nắm giữ công nghệ luyện thép lò thổi oxy hiện đại đạt chuẩn mác thép CB400-V chịu lực siêu cao.\"",
    "\"Đó chính là Tập đoàn Thép Đông Hải - gã khổng lồ nắm giữ 80% thị phần thép hình chịu lực và cấu kiện xây dựng đặc chủng.\"",
    "\"Chỉ cần có được hợp đồng cung ứng thép cam kết và thư bảo lãnh kỹ thuật từ Chủ tịch Tập đoàn Thép Đông Hải...\"",
    "\"Thì Agribank Hà Ngoại mới đồng ý tái cơ cấu khoản nợ 1.200 tỷ, và Bộ Xây dựng mới cấp phép cho các người tiếp tục thi công.\"",
    "\"If không có chữ ký của vị Chủ tịch huyền thoại đó, dự án Hà Ngoại Sky Line của các người chỉ là một đống phế thải thép hình vô giá trị.\"",
    "Lê Mỹ Hạnh như người sắp chết đuối vớ được cọc, cô vội vàng chồm người lên phía trước.",
    "\"Luật sư Trịnh! Cô có mối quan hệ với Tập đoàn Thép Đông Hải không? Xin cô hãy giúp chúng tôi kết nối với Chủ tịch Đông Hải!\"",
    "\"Dù phải trả bất kỳ giá nào, dù phải chi bao nhiêu tiền hoa hồng phí dịch vụ, Lê Gia cũng sẽ đáp ứng!\"",
    "Trịnh Băng Dao cười lạnh một tiếng, cất chiếc kính gọng titanium vào hộp da.",
    "\"Tổng giám đốc Lê, cô đang đùa tôi sao? Vị Chủ tịch của Đông Hải Steel là nhân vật thần bí bậc nhất giới kinh doanh công nghiệp nặng.\"",
    "\"Đế chế của ông ấy kiểm soát từ các mỏ quặng khai khoáng, lò cao blast furnace cho tới hệ thống phân phối thép xuất khẩu toàn quốc.\"",
    "\"Ngay cả tôi, muốn đại diện cho hãng luật Baker & Partners gặp trợ lý cấp cao của ông ấy còn phải đặt lịch trước ba tháng.\"",
    "\"Lê gia của các người, lấy tư cách gì để đòi vị vương giả ngành thép đó đứng ra bảo lãnh kỹ thuật và tài chính cho các người?\"",
    "\"Tôi khuyên cô nên chuẩn bị tinh thần tuyên bố phá sản và đối mặt với các cuộc điều tra kinh tế từ cơ quan chức năng thì hơn.\"",
    "Nói rồi, Băng Dao đứng dậy, thu dọn hồ sơ vào cặp da Hermes, khí chất kiêu sa lẫm liệt rời khỏi phòng họp.",
    "Để lại Lê Mỹ Hạnh ngồi thẫn thờ trên ghế, nước mắt tràn khóe mi, lòng tràn ngập sự hối hận và hoang mang tột độ.",
    "Cô không hề hay biết rằng, vị Chủ tịch huyền thoại, người nắm quyền sinh sát toàn bộ vận mệnh của cô và Lê gia...",
    "Vừa mới bị cô và em trai sỉ vả khinh miệt dưới hầm biệt thự, và vừa đặt bút ký vào tờ đơn ly hôn rẻ tiền chỉ vài giờ trước đó."
]

# Chapter 3 lines (Target ~1300-1400 words, strictly >= 1100)
chap3_lines = [
    "Khác hẳn với sự ngột ngạt và tuyệt vọng đang bao trùm lấy Lê gia tại Long Biên.",
    "Khu công nghiệp thép khổng lồ của Tập đoàn Thép Đông Hải tại vùng Hà Ngoại lại đang rền vang những âm thanh mạnh mẽ của sự sống.",
    "Tiếng còi hơi báo hiệu ca làm việc mới vang lên lảnh lót giữa bầu trời đông xám xịt.",
    "Những ống khói lò cao blast furnace khổng lồ vươn cao kiêu hãnh lên bầu trời, phun ra những làn hơi nước trắng xóa.",
    "Tiếng xích sắt của hệ thống băng tải quặng sắt rền rĩ, tiếng lò thổi oxy tinh luyện gang thành thép gầm rú như sấm truyền.",
    "Trần Đông Hải bước xuống từ chiếc xe taxi cỏ màu bạc dừng trước cổng chính của khu công nghiệp.",
    "Anh vẫn mặc chiếc quần jean sờn gối và chiếc áo khoác gió giản dị, tay xách chiếc hộp thiếc rỉ sét cũ kỹ.",
    "Nhưng ngay khi bóng dáng anh xuất hiện tại lối đi bộ dành cho nhân viên.",
    "Hàng chục nhân viên an ninh mặc đồng phục đen, trang bị công cụ hỗ trợ chuyên nghiệp lập tức đứng thẳng người.",
    "Họ đồng loạt cúi đầu góc chín mươi độ, cung kính hô vang: \"Chào Chủ tịch!\"",
    "Đông Hải khẽ gật đầu, ánh mắt thâm trầm không gợn chút sóng gió, sải bước đi thẳng vào tòa nhà điều hành trung tâm.",
    "Tòa nhà mười tầng được xây dựng hoàn toàn bằng kết cấu khung thép cường lực SS400 chịu tải siêu cao và kính hộp cản nhiệt hiện đại.",
    "Khi anh bước vào phòng điều hành trung tâm tại tầng cao nhất, toàn bộ ban giám đốc đã đứng xếp hàng chờ sẵn.",
    "On bức tường chính của căn phòng là một màn hình LED khổng lồ hiển thị thời gian thực thông số kỹ thuật của các lò luyện.",
    "Nhiệt độ lò thổi oxy đạt 1650 độ C, áp suất khí nén đạt chuẩn, mác thép CB400-V đang được cán nóng liên tục.",
    "Nguyễn Hoàng Nam - trợ lý cấp cao kiêm Giám đốc điều hành tổng bộ - lập tức bước lên dâng cốc cà phê đen nóng không đường.",
    "\"Chủ tịch, ngài đã về. Chúc mừng ngài đã hoàn toàn thoát khỏi vũng lầy Lê gia.\"",
    "Hoàng Nam cung kính cúi đầu, ánh mắt tràn đầy sự sùng bái dành cho người đàn ông đứng trước mặt.",
    "Đông Hải khẽ nhấp một ngụm cà phê đắng ngắt, đi đến trước bàn làm việc bằng gỗ mun nguyên khối.",
    "Anh đặt chiếc hộp thiếc rỉ sét lên bàn, khẽ ngả người ra chiếc ghế da chủ tịch êm ái.",
    "\"Báo cáo tình hình đi. Lê Quốc Bảo bên đó đã bắt đầu hành động chưa?\"",
    "Giọng nói của Đông Hải trầm thấp nhưng mang theo một uy quyền áp đảo, khiến nhiệt độ trong phòng như hạ xuống vài độ.",
    "Hoàng Nam lập tức mở máy tính bảng, trình chiếu một loạt tài liệu mật lên màn hình lớn.",
    "\"Báo cáo Chủ tịch, đúng như ngài dự đoán. Lê Quốc Bảo đang lâm vào đường cùng.\"",
    "\"Hắn đã bí mật thông qua một đường dây buôn lậu biên giới để nhập khẩu khẩn cấp 5.000 tấn thép thanh vằn CB300-V chất lượng kém.\"",
    "\"Số thép này được sản xuất từ các lò điện hồ quang dã ngoại, hàm lượng tạp chất lưu huỳnh và phốt pho cực cao, độ giòn lớn.\"",
    "\"Chúng định dùng công nghệ dập mác giả để biến số thép CB300-V này thành mác thép cường độ cao CB400-V đạt chuẩn.\"",
    "\"Mục đích là để qua mặt cơ quan thanh tra của Bộ Xây dựng tại dự án Hà Ngoại Sky Line vào ngày ký hợp đồng sắp tới.\"",
    "\"Toàn bộ chứng từ xuất xứ CO/CQ của lô hàng này đều là giả mạo được làm bởi một công ty ma tại Hải Phòng.\"",
    "Khóe môi Đông Hải khẽ nhếch lên thành một nụ cười lạnh lùng, ánh mắt anh lóe lên tia sát khí lạnh lẽo.",
    "\"Buôn lậu thép giả mác chịu lực cho siêu công trình dân dụng... Lê gia thực sự tự tìm đường chết.\"",
    "\"If để số thép phế thải đó đổ vào móng Hà Ngoại Sky Line, hàng ngàn sinh mạng người dân sẽ gặp nguy hiểm.\"",
    "\"Hoàng Nam, gửi toàn bộ hồ sơ bằng chứng pháp y buôn lậu xuất nhập khẩu mà chúng ta đã thu thập được cho Cục Cảnh sát kinh tế C03.\"",
    "\"Đồng thời phối hợp với Phòng Cảnh sát kinh tế C09 Hà Nội để họ xác lập chuyên án đấu tranh chống buôn lậu thép đặc biệt.\"",
    "\"Tôi muốn lô thép lậu đó bị bắt giữ ngay tại bến cảng trung chuyển Hà Ngoại khi chúng chuẩn bị bốc xếp lên xe tải.\"",
    "\"Rõ, thưa Chủ tịch! Tôi sẽ chuyển giao tài liệu mật ngay lập tức!\" Hoàng Nam dứt khoát ghi nhận mệnh lệnh.",
    "Đông Hải gõ nhẹ ngón tay lên mặt bàn gỗ mun, nhịp điệu đều đặn như tiếng đập của búa rèn thủy lực.",
    "\"Còn về phía Agribank Hà Ngoại thì sao? Khoản nợ 1.200 tỷ của họ đối với Lê gia đã xử lý thế nào rồi?\"",
    "Hoàng Nam mỉm cười đầy ẩn ý, lật sang trang tài liệu tài chính tiếp theo.",
    "\"Thưa Chủ tịch, theo chỉ thị trước đó của ngài, công ty tài chính thành viên của Đông Hải Steel đã hoàn tất việc mua lại khoản nợ xấu 1.200 tỷ này từ Agribank Chi nhánh Hà Ngoại.\"",
    "\"Hiện tại, chúng ta mới chính là chủ nợ hợp pháp duy nhất nắm giữ toàn bộ quyền sử dụng đất thế chấp của dự án Hà Ngoại Sky Line.\"",
    "\"Giám đốc Agribank Hà Ngoại - ông Trần Minh Tuấn - đang chờ đợi cuộc gọi trực tiếp từ ngài để phối hợp hành động.\"",
    "Đông Hải cầm điện thoại lên, trực tiếp quay số gọi cho vị Giám đốc chi nhánh ngân hàng quốc doanh lớn nhất vùng Hà Ngoại.",
    "\"Alo, anh Tuấn à? Tôi Đông Hải đây.\"",
    "Đầu dây bên kia lập tức truyền đến giọng nói vô cùng nhiệt tình và kính cẩn của ông Trần Minh Tuấn.",
    "\"Chủ tịch Trần! Tôi nghe đây ạ! Mọi việc đã chuẩn bị sẵn sàng, chỉ chờ mệnh lệnh của ngài thui!\"",
    "\"Anh Tuấn, ngày mai hãy cử đoàn kiểm toán nợ đặc biệt sang trụ sở Lê Gia.\"",
    "\"Hãy chính thức thông báo thu hồi nợ trước hạn do Lê Gia vi phạm nghiêm trọng điều khoản sử dụng vốn tín dụng.\"",
    "\"Đồng thời thực hiện phong tỏa khẩn cấp toàn bộ tài sản thế chấp và các tài khoản thanh toán của họ tại hệ thống ngân hàng.\"",
    "\"Tôi muốn Lê Gia hiểu thế nào là cảm giác bị siết nghẹt cổ họng tài chính.\"",
    "\"Chủ tịch Trần xin cứ yên tâm! Việc này nằm trong thẩm quyền hợp pháp của chúng tôi khi bên vay có dấu hiệu gian lận hồ sơ kỹ thuật kỹ thuật! Tôi sẽ làm thật triệt để!\"",
    "Đông Hải cúp máy, ánh mắt anh nhìn ra ngoài cửa sổ kính lớn, nơi những tia lửa thép nóng đỏ bắn ra từ lò thổi oxy rực rỡ như pháo hoa.",
    "Đế chế thép Đông Hải sừng sững như một ngọn núi sắt đá, sẵn sàng đè bẹp mọi sự ngạo mạn, ngu xuẩn của hào môn Lê gia.",
    "\"Lê Mỹ Hạnh, cô chê tôi vô dụng, khinh tôi nghèo hèn bẩn thỉu.\"",
    "\"Vậy thì hãy để tôi xem, khi không có dòng thép chịu lực của Trần Đông Hải tôi bảo lãnh...\"",
    "\"Cái hào môn rỗng tuếch của cô sẽ sụp đổ dưới chân Thịnh Phát và đống sắt vụn SS400 nhập lậu như thế nào.\""
]

# Chapter 4 lines (Target ~1300-1400 words, strictly >= 1100)
# We expand with detail about luxury elements, Mother-in-law insults, due diligence process, Rolls-Royce Phantom specs, and technical debt audit.
chap4_lines = [
    "Những ngày tiếp theo, không khí tại Hà Ngoại như có một cơn bão ngầm đang tích tụ sức mạnh khủng khiếp.",
    "Nhưng tại tổng bộ Công ty Bất động sản Lê Gia, niềm vui sướng hoang đường lại đang che mờ mắt tất cả mọi người.",
    "Lê gia đang rầm rộ chuẩn bị cho lễ ký kết hợp tác chiến lược thế kỷ giữa họ và Tập đoàn Bất động sản Thịnh Phát.",
    "Sự kiện được tổ chức tại Grand Ballroom - sảnh lớn sang trọng bậc nhất của Khách sạn năm sao JW Marriott Hà Nội.",
    "Lê Mỹ Hạnh đứng trước tấm gương lớn trong phòng thay đồ VIP của khách sạn, ngắm nhìn bản thân trong bộ váy dạ hội lộng lẫy màu vàng ánh kim.",
    "Bộ trang sức kim cương tự nhiên đắt giá lấp lánh trên cổ và tai cô càng tôn lên vẻ đẹp quý phái, kiêu sa của một nữ tổng tài kiêu ngạo.",
    "Cô khẽ mỉm cười đầy tự mãn, thầm nghĩ quyết định ly hôn gã chồng phế vật Trần Đông Hải là bước đi đúng đắn nhất đời mình.",
    "Mẹ đẻ của Mỹ Hạnh - bà Nguyễn Thị Tuyết - bước vào phòng thay đồ, diện bộ áo dài nhung đỏ thẫm thêu chim phượng bằng chỉ vàng.",
    "Bà ta đeo đầy nhẫn ngọc bích và vòng vàng lớn ở cổ tay, gương mặt hớn hở tột cùng, lớn tiếng cười nói hỉ hả.",
    "\"Mỹ Hạnh con gái yêu của mẹ! Con hôm nay đẹp lộng lẫy như một bà hoàng thực sự vậy!\"",
    "\"Mẹ đã bảo rồi mà, tống khứ được gã chồng phế vật Trần Đông Hải đi là phúc đức ba đời của Lê gia nhà ta!\"",
    "\"Gã đó ngoài việc quét dọn, lau chùi dầu mỡ blast furnace rỉ sét thì có tích sự gì cho cái hào môn này đâu?\"",
    "\"Nhìn sang thiếu gia Trịnh Khắc Huy mà xem, người ta là rồng trong loài người, môn đăng hộ đối với con gái mẹ!\"",
    "\"Lễ ký kết hôm nay sẽ là cái tát thẳng mặt vào lũ tiểu nhân Hà Ngoại từng khinh thường Lê gia chúng ta lâm vào nợ nần!\"",
    "Lê Mỹ Hạnh nghe mẹ nói thế thì càng thêm đắc ý, sự kiêu ngạo trong mắt cô ta càng thêm phần đậm đặc.",
    "\"Mỹ Hạnh, hôm nay sau khi ký kết hợp đồng này, vị thế của em trong giới thượng lưu Hà Ngoại sẽ không ai có thể lay chuyển.\"",
    "Lê Quốc Bảo mặc bộ vest Tuxedo lịch lãm, bước vào phòng thay đồ với gương mặt hớn hở tột cùng.",
    "\"Anh Trịnh Khắc Huy đã sắp xếp xong mọi việc rồi. Lô thép 'giá tốt' của chúng ta đã được tập kết an toàn tại kho bãi Hà Ngoại.\"",
    "\"Chỉ cần lễ ký kết này thành công, dòng vốn 500 tỷ của Thịnh Phát rót vào, chúng ta sẽ lập tức giải quyết xong khoản nợ ở Agribank!\"",
    "Lê Mỹ Hạnh gật đầu, ánh mắt lộ vẻ đắc ý: \"Đúng vậy, ba năm qua tôi đã chịu đựng quá đủ sự nghèo hèn và vô dụng của Trần Đông Hải rồi.\"",
    "\"Hôm nay tôi sẽ cho cả thế giới thấy, Lê Mỹ Hạnh tôi xứng đáng đứng ở đỉnh cao danh vọng, chứ không phải chui lủi dưới tầng hầm bẩn thỉu.\"",
    "Trong khi chị em Lê gia đang đắm chìm trong ảo tưởng vinh quang tột đỉnh.",
    "Tại văn phòng tổng bộ hãng luật Baker & Partners ở trung tâm Hà Nội, một cơn địa chấn thực sự đang diễn ra trong phòng làm việc của Trịnh Băng Dao.",
    "Nữ luật sư cao cấp Trịnh Băng Dao đang cầm trên tay bản báo cáo thẩm định pháp lý mật cuối cùng vừa được cơ quan đăng ký kinh doanh và hệ thống kiểm toán Agribank gửi tới.",
    "Cô vô cùng tỉ mỉ lật xem từng trang hồ sơ pháp lý, đặc biệt là tài liệu do-diligence về cấu trúc nợ chéo của Thịnh Phát.",
    "Trịnh Băng Dao phát hiện ra một sự thật kinh hoàng: Thịnh Phát thực chất đã đem dự án của bên thứ ba đi thế chấp chéo (cross-collateralization) để vay vốn khống.",
    "Và toàn bộ hồ sơ năng lực tài chính của Thịnh Phát chỉ là một quả bóng chứa đầy khí gas nợ xấu, sẵn sàng nổ tung bất cứ lúc nào.",
    "Nhưng điều làm cô sốc nặng nhất lại nằm ở trang phụ lục cuối cùng đóng dấu đỏ bảo mật của cơ quan nhà nước.",
    "Khi lật mở đến trang phụ lục xác nhận chủ sở hữu cuối cùng của Tập đoàn Thép Đông Hải, ngón tay sơn đỏ của cô bỗng run lên bần bật.",
    "Đôi mắt sắc bén sau gọng kính titanium mở to hết cỡ, gương mặt thanh tú tràn ngập sự bàng hoàng, kinh hãi tột độ.",
    "Trên tờ giấy đóng dấu đỏ bảo mật của cơ quan nhà nước, tại dòng chữ \"Chủ tịch Hội đồng quản trị kiêm đại diện pháp luật sở hữu 90% cổ phần\":",
    "Hiển thị rõ ràng ba chữ viết hoa sắc nét: \"TRẦN ĐÔNG HẢI\".",
    "Kèm theo đó là bản sao căn cước công dân và ảnh chân dung của anh - người đàn ông có ánh mắt thâm trầm, sâu thẳm.",
    "Chính là người đàn ông đã lặng lẽ ký vào tờ đơn ly hôn đơn phương của Lê Mỹ Hạnh cách đây vài ngày, hồ sơ mà chính hãng luật của cô đã làm chứng.",
    "Chưa dừng lại ở đó, trang tiếp theo của tài liệu kiểm toán nợ gốc cho thấy:",
    "Công ty đầu tư tài chính Đông Hải - công ty con do Trần Đông Hải kiểm soát 100% vốn - đã mua đứt toàn bộ khoản nợ xấu 1.200 tỷ của Lê Gia từ Agribank.",
    "Nói cách khác, Trần Đông Hải không chỉ là vị vua nắm giữ nguồn cung thép chịu lực CB400-V độc quyền của cả miền Bắc.",
    "Mà hiện tại, anh còn là chủ nợ tối cao nắm giữ quyền sinh sát đối với toàn bộ tài sản thế chấp và sinh mệnh pháp lý của Lê gia.",
    "\"Trời ơi... chuyện này làm sao có thể xảy ra được chứ?\" Trịnh Băng Dao hít một hơi lạnh sâu, da đầu tê dại vì kinh hãi.",
    "\"Trần Đông Hải... gã chồng bị Lê Mỹ Hạnh ruồng bỏ, khinh rẻ là kỹ thuật viên quèn bẩn thỉu...\"",
    "\"Lại chính là vị chủ tịch thần bí của đế chế thép Đông Hải vĩ đại sao?\"",
    "\"Lê Mỹ Hạnh đúng là đồ mắt mù! Cô ta đã tự tay vứt bỏ đi một con rồng thực sự, để rồi đi ôm chân một lũ rắn rết Thịnh Phát sắp chết chìm!\"",
    "Bằng kinh nghiệm thẩm định lão luyện của mình, Băng Dao lập tức nhận ra toàn bộ hồ sơ năng lực của Tập đoàn Thịnh Phát thực chất chỉ là một cái vỏ rỗng tuếch.",
    "Thịnh Phát đang bị nợ xấu bủa vây, và việc họ muốn thâu tóm Lê Gia thực chất chỉ là một âm mưu lừa đảo tài chính để chiếm đoạt dự án Hà Ngoại Sky Line.",
    "Và người đứng sau giật dây toàn bộ màn kịch siết nợ này để dồn Lê gia vào đường cùng, không ai khác chính là Trần Đông Hải.",
    "\"Mau chuẩn bị xe Rolls-Royce Phantom cho tôi! Đến khách sạn JW Marriott ngay lập tức!\" Băng Dao đứng bật dậy, lớn tiếng ra lệnh cho trợ lý.",
    "Trái tim cô đập liên hồi dưới lớp áo vest cao cấp, cô biết rằng lễ ký kết hôm nay sẽ không phải là ngày vinh quang của Lê gia.",
    "Mà đó sẽ là một pháp trường hành quyết tài chính tàn nhẫn nhất lịch sử Hà Ngoại, do chính tay vị vương giả ngành thép Trần Đông Hải thiết lập.",
    "Cô bước xuống tầng hầm đỗ xe VIP, nơi chiếc Rolls-Royce Phantom VIII màu xanh tím sẫm (midnight blue) đang đỗ sẵn.",
    "Động cơ V12 6.75L tăng áp kép hoạt động êm ái đến mức hoàn toàn không phát ra bất kỳ một rung động hay tiếng ồn nào.",
    "Khoang cabin sang trọng lót da bò cao cấp chọn lọc từ dãy Alps cùng trần xe ngàn sao lấp lánh (Starlight Headliner) phản chiếu khuôn mặt đầy lo lắng nhưng kiên định của Băng Dao.",
    "Chiếc xe siêu sang lướt đi trong cơn mưa phùn lạnh giá của Hà Nội, hướng thẳng về phía khách sạn JW Marriott.",
    "Băng Dao siết chặt tập tài liệu mật trong tay, biết rằng vận mệnh của Lê gia sắp sửa bị nghiền nát dưới gót chân của Trần Đông Hải."
]

# Chapter 5 lines (Target ~1300-1400 words, strictly >= 1100)
chap5_lines = [
    "Sảnh lớn Grand Ballroom của Khách sạn JW Marriott rực rỡ ánh đèn pha lê, chật kín giới báo chí truyền thông và các doanh nhân máu mặt.",
    "Lê Mỹ Hạnh đứng trên bục phát biểu cao quý, gương mặt tràn ngập sự kiêu hãnh và ngạo mạn tột cùng.",
    "Bên cạnh cô, thiếu gia Trịnh Khắc Huy của Thịnh Phát nở nụ cười đắc ý, tay cầm chiếc bút vàng chuẩn bị đặt bút ký vào bản hợp đồng tỷ đô.",
    "\"Lê Gia chúng tôi cam kết sẽ biến Hà Ngoại Sky Line thành biểu tượng kiến trúc vĩ đại nhất...\" Mỹ Hạnh dõng dạc tuyên bố vào micro.",
    "Nhưng khi cô chưa kịp dứt câu, hai cánh cửa gỗ gụ khổng lồ của sảnh lớn đột ngột bị đẩy mạnh ra từ bên ngoài.",
    "Một luồng khí lạnh buốt từ sảnh chờ tràn vào phòng tiệc ấm cúng, khiến toàn bộ quan khách bất giác rùng mình quay đầu lại nhìn.",
    "Trần Đông Hải sải bước bước vào.",
    "Anh không còn mặc chiếc áo bảo hộ sờn cũ hay chiếc quần jean lấm lem dầu mỡ lò cao nữa.",
    "Thay vào đó là bộ vest navy may đo thủ công hoàn mỹ từ chất liệu sợi len vicuna siêu xa xỉ, ôm sát vóc dáng cao lớn sừng sững như núi đá.",
    "Gương mặt góc cạnh của anh lạnh lùng, đôi mắt sâu thẳm toát lên một uy quyền uy nghiêm tột độ của kẻ đứng trên đỉnh cao danh vọng.",
    "Đi bên cạnh anh là ông Trần Minh Tuấn - Giám đốc Agribank Hà Ngoại, cùng một tổ công tác gồm năm điều tra viên mặc cảnh phục nghiêm nghị của Cục Cảnh sát kinh tế C03.",
    "Lê Quốc Bảo vừa nhìn thấy Đông Hải liền biến sắc, lập tức chạy xuống bục hét lớn đầy khinh miệt.",
    "\"Trần Đông Hải! Gã phế vật nhà nghèo này! Ai cho phép anh vác cái mặt bẩn thỉu đến đây làm loạn đại lễ của Lê gia hả?\"",
    "\"Bảo vệ đâu! Đuổi cổ gã kỹ thuật viên quèn chuyên ngửi mùi dầu mỡ lò thổi oxy này ra ngoài cho tôi! Đồ ăn mày!\"",
    "Nhưng lực lượng bảo vệ của khách sạn chưa kịp tiến lên, một bóng hình kiêu sa lẫm liệt đã nhanh chóng bước vào từ lối đi VIP.",
    "Nữ luật sư thượng lưu Trịnh Băng Dao vội vã đi tới, đứng trước mặt Trần Đông Hải và cúi đầu cung kính một góc chín mươi độ.",
    "\"Chủ tịch Trần! Tôi đã hoàn tất toàn bộ hồ sơ thẩm định pháp lý đặc biệt và lệnh phong tỏa khẩn cấp tài sản của Lê gia theo đúng chỉ thị của ngài!\"",
    "Âm thanh của Trịnh Băng Dao tuy không lớn nhưng qua hệ thống âm thanh của khán phòng lại vang dội rõ mồn một như một tiếng sét đánh ngang tai.",
    "Toàn bộ sảnh tiệc lập tức rơi vào trạng thái im lặng đến mức một cây kim rơi cũng có thể nghe thấy.",
    "Lê Mỹ Hạnh đứng chôn chân trên bục phát biểu, chiếc micro trên tay cô khẽ run rẩy, gương mặt xinh đẹp thanh tú cắt không còn một giọt máu.",
    "\"Luật sư Trịnh... cô... cô đang đùa cái gì thế? Vị Chủ tịch Trần nào cơ?\"",
    "\"Chẳng phải cô nói vị Chủ tịch thần bí của Tập đoàn Thép Đông Hải là người nắm quyền sinh sát dự án của chúng tôi sao?\"",
    "Trịnh Băng Dao khẽ ngẩng đầu lên, ánh mắt nhìn Lê Mỹ Hạnh tràn ngập sự thương hại và khinh bỉ tột cùng.",
    "\"Tổng giám đốc Lê, cô quả thực là người phụ nữ ngu xuẩn nhất mà tôi từng gặp trong đời!\"",
    "\"Người chồng cũ mà cô khinh rẻ là kẻ vô dụng, gã kỹ thuật viên quèn suốt ngày lấm lem dầu mỡ blast furnace...\"",
    "\"Chính là Trần Đông Hải - vị Chủ tịch tối cao của Tập đoàn Thép Đông Hải, hoàng đế ngành công nghiệp nặng miền Bắc!\"",
    "\"Đồng thời, anh ấy cũng là chủ nợ lớn nhất đang nắm giữ toàn bộ khoản nợ 1.200 tỷ đồng của các người thông qua việc mua đứt nợ xấu từ Agribank!\"",
    "\"Cái gì?!\" Lê Mỹ Hạnh như bị sét đánh trúng đỉnh đầu, hai tai ù đi, cả cơ thể lảo đảo suýt ngã quỵ trên bục.",
    "Lê Quốc Bảo trợn tròn mắt, mồm há hốc không thể tin nổi vào những gì mình vừa nghe thấy.",
    "Chưa kịp để hai chị em Lê gia hoàn hồn, ông Trần Minh Tuấn - Giám đốc Agribank Hà Ngoại - đã lạnh lùng bước lên phía trước.",
    "\"Tôi xin chính thức công bố quyết định của ngân hàng!\"",
    "\"Do phía Công ty Bất động sản Lê Gia có hành vi gian lận hồ sơ kỹ thuật kết cấu, sử dụng thép lậu SS400 chất lượng kém thay thế thép chịu lực CB400-V.\"",
    "\"Chúng tôi quyết định thu hồi toàn bộ khoản nợ gốc 1.200 tỷ đồng trước hạn, phong tỏa toàn bộ tài sản thế chấp là dự án Hà Ngoại Sky Line!\"",
    "Ngay sau đó, vị đại diện Cục Cảnh sát kinh tế C03 bước lên, rút ra chiếc còng số tám sáng loáng trước mặt Lê Quốc Bảo.",
    "\"Lê Quốc Bảo! Anh bị bắt khẩn cấp vì hành vi buôn lậu thép giả mác chịu lực qua biên giới và lừa đảo chiếm đoạt tài sản! Đề nghị đi theo chúng tôi!\"",
    "\"Chị ơi cứu em! Anh Huy ơi cứu em! Em không muốn đi tù đâu!\" Quốc Bảo hoảng loạn khóc lóc thảm thiết khi chiếc còng lạnh ngắt bóp chặt vào cổ tay.",
    "Nhưng thiếu gia Trịnh Khắc Huy của Thịnh Phát lúc này đã sợ đến mức mặt cắt không còn giọt máu.",
    "Hắn vội vàng giật phắt tay ra khỏi hợp đồng, lớn tiếng tuyên bố: \"Lễ ký kết này hủy bỏ! Thịnh Phát chúng tôi hoàn toàn không liên quan gì đến hành vi buôn lậu của Lê gia!\"",
    "Mọi hy vọng, mọi ảo tưởng về một tương lai hào môn rực rỡ của Lê Mỹ Hạnh hoàn toàn sụp đổ tan tành trong chớp mắt.",
    "Cô ngã quỵ xuống sàn đá cẩm thạch lạnh ngắt của khách sạn JW Marriott, bộ váy dạ hội vàng ánh kim đắt giá giờ đây lấm lem bùn nước.",
    "Cô ngước nhìn người đàn ông đang đứng sừng sững trước mặt mình - người chồng mà cô từng coi thường như một đống sắt vụn vô giá trị.",
    "\"Đông Hải... em sai rồi... em thực sự sai rồi... Xin anh hãy nghĩ đến tình nghĩa ba năm qua mà cứu lấy Lê gia...\"",
    "Mỹ Hạnh khóc nghẹn ngào, bò đến muốn nắm lấy gấu quần của anh để van xin sự tha thứ.",
    "Nhưng Trần Đông Hải chỉ nhìn cô bằng ánh mắt vô hồn, lạnh lẽo như băng tuyết ngàn năm trên đỉnh lò luyện.",
    "\"Tình nghĩa ba năm của chúng ta, đã bị cô tự tay chôn vùi dưới tờ đơn ly hôn rẻ tiền đó rồi, Lê Mỹ Hạnh.\"",
    "Nói rồi, anh lạnh lùng quay lưng bước đi, không một lần ngoảnh đầu lại nhìn đống tro tàn đổ nát phía sau.",
    "Trịnh Băng Dao cung kính che ô cho anh bước ra ngoài sảnh lớn khách sạn.",
    "Nơi chiếc Rolls-Royce Phantom VIII màu midnight blue đang đỗ sẵn, biểu tượng Spirit of Ecstasy mạ vàng khẽ thụt xuống kiêu hãnh.",
    "Chiếc xe siêu sang lăn bánh lướt đi trong màn mưa phùn Hà Ngoại, để lại sau lưng một Lê gia kiêu ngạo đã hoàn toàn bị xóa sổ khỏi bản đồ giới thượng lưu."
]

# Write draft_novel_2.json
novel["chapters"].append({"title": "Chương 1: Tờ Đơn Ly Hôn Rẻ Tiền", "content": "".join([f"<p>{line}</p>\n" for line in chap1_lines])})
novel["chapters"].append({"title": "Chương 2: Cuộc Thẩm Định Lạnh Lùng", "content": "".join([f"<p>{line}</p>\n" for line in chap2_lines])})
novel["chapters"].append({"title": "Chương 3: Lưới Sắt Siết Chặt", "content": "".join([f"<p>{line}</p>\n" for line in chap3_lines])})
novel["chapters"].append({"title": "Chương 4: Cơn Bão Trước Giờ G", "content": "".join([f"<p>{line}</p>\n" for line in chap4_lines])})
novel["chapters"].append({"title": "Chương 5: Vương Giả Quy Lai", "content": "".join([f"<p>{line}</p>\n" for line in chap5_lines])})

# Count words
def count_words(text):
    # strip HTML tags to count words accurately
    import re
    clean = re.compile('<.*?>')
    text_clean = re.sub(clean, '', text)
    return len(text_clean.split())

print("Word counts:")
for i, chap in enumerate(novel["chapters"]):
    wc = count_words(chap["content"])
    print(f"Chapter {i+1}: {wc} words")

output_path = "/Users/aaronnguyen/TN/App/doctieuthuyet/scratch/draft_novel_2.json"
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, "w", encoding="utf-8") as f:
    json.dump(novel, f, ensure_ascii=False, indent=2)

print(f"Successfully generated {output_path}")
