import json
import os

def create_novel():
    title = "Bão Nổi Miền Tây: Vương Quốc Sầu Riêng Trăm Tỷ Của Chàng Rể Hào Môn"
    author = "Nam Phương Nhất Nhạn"
    genre = "Sảng Văn"
    
    intro = (
        "<p><strong>&ldquo;Nguyễn Tấn Đạt, thế tử duy nhất của tập đoàn vận tải biển Á Châu sầm uất bậc nhất Đông Nam Á, "
        "lấm lem bùn đất trong chiếc ủng cao su sờn rách, bị gã chủ nợ hống hách Huỳnh Hữu Lộc đá văng xô nước tưới và nhổ "
        "bọt vào chân: &lsquo;Thằng làm vườn mạt hạng, cút ngay khỏi mắt tao trước khi tao san phẳng cái vườn này!&rsquo;&rdquo;</strong></p>"
        "<p>Thế nhưng chúng không thể ngờ, chiếc ủng đẫm bùn ấy thuộc về người nắm giữ vận mệnh của hàng nghìn hải trình quốc tế, "
        "và vương quốc sầu riêng Monthong 50 hecta kia sắp trỗi dậy rực rỡ hơn bao giờ hết. Khi cả giang sơn miền Tây xôn xao "
        "vì vụ đầu độc độc chất chấn động nông trường Chợ Lách, Đạt đã kích hoạt phi đội drone tối tân nhập khẩu trực tiếp từ Singapore "
        "để cứu lấy vườn cây ngay trước mắt giới báo chí và thanh tra Sở. Đỉnh điểm của cú vả mặt thế kỷ là khi anh ký sắc lệnh mua đứt "
        "khoản nợ quá hạn từ Agribank, bóp nghẹt âm mưu thâu tóm bẩn thỉu của thế lực bất động sản đen địa phương, bảo vệ trọn vẹn "
        "tình yêu kiên định của tiểu thư Trần Mỹ Duyên.</p>"
    )
    
    cover_prompt = (
        "masterpiece, highly detailed book cover, vivid anime illustration style, a handsome Vietnamese young man with "
        "determination in his eyes standing in a lush durian orchard in Western Vietnam under a glowing golden sunset, "
        "next to a beautiful smart young woman, high-tech advanced agricultural drones flying in the sky, cinematic lighting, "
        "typography text 'Bão Nổi Miền Tây' written prominently on the cover"
    )
    
    # CHAPTER Titles
    ch1_title = "Chương 1: Bùn Lầy Chợ Lách Và Giọt Nước Mắt Tiểu Thư"
    ch2_title = "Chương 2: Thảm Họa Độc Chất Và Vòng Vây Truyền Thông"
    ch3_title = "Chương 3: Lời Tự Sự Dưới Bóng Hoàng Hôn Rạch Miễu"
    ch4_title = "Chương 4: Kích Hoạt Quyền Lực Siêu Cấp: Hải Đội Drone Singapore"
    ch5_title = "Chương 5: Kết Quả Kiểm Nghiệm Y Học Và Cú Tát Pháp Lý"
    ch6_title = "Chương 6: Mua Đứt Agribank Và Đám Cưới Hào Môn Chấn Động"

    # CHAPTER Contents
    ch1_content = (
        "<p>Cơn gió chướng rít qua rặng dừa nước ven sông Hàm Luông, mang theo cái nóng hầm hập của miền Tây giữa mùa quả ngọt. "
        "Dưới tán những gốc sầu riêng Monthong cổ thụ xum xuê tại xã Sơn Định, huyện Chợ Lách, tỉnh Bến Tre, Nguyễn Tấn Đạt đang "
        "lưng còng sát đất. Đôi ủng cao su cũ kỹ của anh ngập sâu trong lớp bùn sét xám xịt của vùng đê bao sông Tiền. Chiếc áo xanh "
        "bảo hộ lao động sờn vai đã thấm đẫm mồ hôi, từng vệt muối khô kết tinh lại thành những đường viền trắng ngoằn ngoèo sau lưng. "
        "Hai bàn tay anh chai sần, nắm chắc cây kéo cắt cành chuyên dụng, cẩn thận tỉa đi những chồi non vô hiệu để tập trung dinh dưỡng "
        "cho những quả sầu riêng lủng lẳng trên cao. Mỗi quả sầu riêng to bằng chiếc mũ cối, gai nhọn hoắt và đều đặn như những khối "
        "tinh thể xanh biếc, hứa hẹn một mùa thu hoạch trăm tỷ.</p>"
        "<p>Không ai ngờ rằng, người thanh niên làm vườn đang lấm lem bùn đất, im lặng chịu thương chịu khó suốt nửa năm qua tại trang "
        "trại nhà họ Trần này lại là thế tử độc nhất của Tập đoàn Vận tải biển Á Châu (Asia Shipping Group). Gia tộc của anh sở hữu "
        "hải đội container hơn trăm chiếc chạy dọc các tuyến hàng hải từ Singapore đi Rotterdam, kiểm soát gần một phần ba lưu lượng "
        "logistics đường biển của khu vực. Đạt ẩn thân ở đây không phải để chơi bời, mà là để tìm kiếm một khoảng lặng thực sự sau "
        "những cuộc đấu trí khốc liệt trên thương trường quốc tế, và hơn hết, là vì người con gái đã cứu anh trong đêm mưa bão nửa năm trước.</p>"
        "<p>Trần Mỹ Duyên bước ra từ gian nhà sàn gỗ ba gian cũ kỹ. Nắng chiều hắt lên gương mặt thanh tú, đôi mắt lá liễu đượm buồn "
        "nhưng ánh lên vẻ kiên cường chịu khó. Cô mặc chiếc áo bà ba màu nâu giản dị, mái tóc đen dài được búi gọn sau gáy bằng chiếc kẹp "
        "nhựa rẻ tiền. Trán cô lấm tấm mồ hôi, đôi môi mím chặt đầy lo âu. Ba cô, ông Trần Văn Minh, đang nằm liệt giường trong nhà. "
        "Cơn cao huyết áp đột ngột do áp lực nợ nần đã vắt kiệt sức lực của người đàn ông cả đời gắn bó với đất đai Chợ Lách này. "
        "Số tiền vay 50 tỷ đồng từ chi nhánh Agribank địa phương để đầu tư hệ thống tưới tự động và đê bao ngăn mặn đã đến hạn thanh toán, "
        "mà thương lái thu mua lại bất ngờ bùng kèo ép giá.</p>"
        "<p>&ldquo;Anh Đạt, anh nghỉ tay uống ngụm nước dừa đi,&rdquo; Duyên bước đến gần, giọng nói ngọt ngào đặc trưng của con gái xứ dừa "
        "nhưng không giấu nổi sự mệt mỏi. Cô chìa ra chiếc ca nhôm đựng nước dừa mát lạnh, ngón tay hơi run run.</p>"
        "<p>Đạt đứng thẳng người, dùng vạt áo bảo hộ lau vội những giọt mồ hôi lăn dài trên gò má góc cạnh, để lộ khuôn mặt nam tính "
        "với đôi mắt sâu thẳm đầy trí tuệ. Anh mỉm cười dịu dàng: &ldquo;Cảm ơn cô Út. Tôi tỉa nốt nhánh này rồi vào dọn dẹp hệ thống bơm.&rdquo;</p>"
        "<p>Đột nhiên, bầu không khí yên bình của vườn sầu riêng bị xé toạc bởi tiếng gầm rú điên cuồng của động cơ xe bán tải. "
        "Chiếc Ford Raptor màu đen bóng bọc thép hầm hố lao thẳng qua cổng tre của trang trại, bánh xe cỡ lớn nghiến nát những bụi cỏ "
        "hoa mười giờ dọc lối đi, cày xới lớp đất bùn đỏ và dừng khựng lại ngay sát mép kênh tưới tiêu. Bụi đất mù mịt bốc lên, mang theo "
        "mùi khói dầu khét lẹt.</p>"
        "<p>Cửa xe bật mở. Huỳnh Hữu Lộc bước xuống. Hắn là con trai của Huỳnh Hữu Tài, trùm bất động sản phân lô bán nền có tiếng "
        "ở Bến Tre, đồng thời là kẻ đứng sau công ty tài chính đen chuyên cho vay nặng lãi núp bóng doanh nghiệp. Lộc diện chiếc quần tây "
        "phẳng phiu, đôi giày tây hiệu Gucci bóng loáng bám đầy bùn đất miền Tây khiến hắn liên tục càu nhàu, tay gõ gõ chiếc ví cầm tay "
        "bằng da cá sấu. Đi sau hắn là bốn gã thanh niên xăm trổ đầy mình, tay lăm lăm những thanh sắt tròn lạnh ngắt.</p>"
        "<p>&ldquo;Trần Mỹ Duyên! Ba cô đâu rồi? Trốn trong nhà làm rùa rụt cổ à?&rdquo; Lộc bước đi khệnh khạng, giọng nói khàn khàn đầy "
        "hống hách. Hắn đảo mắt nhìn quanh vườn sầu riêng Monthong đang trĩu quả với ánh mắt tham lam lộ rõ. &ldquo;Hôm nay là hạn chót "
        "trả 50 tỷ tiền gốc cho ngân hàng. Nhưng tao đã mua lại khoản nợ xấu đó từ Agribank rồi. Giờ tao là chủ nợ trực tiếp của nhà cô. "
        "Hoặc là giao sổ đỏ 50 hecta đất này ra đây, hoặc là cô ký vào tờ giấy đính hôn với tao, làm vợ bé của tao thì tao xóa nợ cho!&rdquo;</p>"
        "<p>Mỹ Duyên lùi lại một bước, gương mặt trắng bệch vì giận dữ nhưng đôi mắt vẫn kiên định bảo vệ gia đình: &ldquo;Huỳnh Hữu Lộc! "
        "Hợp đồng vay của gia đình tôi với ngân hàng vẫn đang trong thời gian xin gia hạn do thiên tai hạn mặn. Anh lấy tư cách gì mà "
        "mua lại khoản nợ khi chưa có quyết định cưỡng chế? Anh đừng có mà dùng luật rừng ở đây!&rdquo;</p>"
        "<p>&ldquo;Luật rừng?&rdquo; Lộc cười lớn, tiếng cười man rợ vang vọng khắp vườn sầu riêng. &ldquo;Ở cái huyện Chợ Lách này, nhà họ Huỳnh "
        "tao chính là luật! Thằng giám đốc chi nhánh Agribank còn phải nể mặt ba tao ba phần. Gia hạn à? Mơ đi con điếm!&rdquo;</p>"
        "<p>Thấy Duyên bị dồn vào thế bí, Đạt im lặng bước tới, chắn giữa cô và gã công tử hống hách. Ánh mắt Đạt bình thản nhưng sâu hoắm "
        "như vực thẳm, khóa chặt lấy gương mặt nghênh ngang của Lộc.</p>"
        "<p>Lộc liếc nhìn Đạt từ đầu đến chân, thấy chiếc áo bảo hộ rách vai và đôi ủng lấm lem bùn đất liền nhổ một bãi nước bọt ngay sát "
        "mũi ủng của Đạt. Hắn quát lớn: &ldquo;Thằng làm vườn mạt hạng này ở đâu ra? Cút ngay khỏi mắt tao trước khi tao bắt đàn em bẻ gãy "
        "chân chó của mày!&rdquo;</p>"
        "<p>Một gã đàn em xăm trổ tiến lên, hung hãn đá văng xô nước tưới bằng nhựa bên cạnh Đạt. Chiếc xô đổ ụp, dòng nước tưới hữu cơ màu "
        "xám đục chảy tràn ra mặt bùn sét, bắn tung tóe lên đôi ủng và gấu quần của Đạt. Tiếng &ldquo;cộp&rdquo; giòn giã của xô nhựa "
        "bị vỡ vang lên khô khốc.</p>"
        "<p>&ldquo;Anh Đạt! Tránh ra đi, bọn chúng không có tính người đâu!&rdquo; Duyên hốt hoảng kéo vạt áo Đạt, mồ hôi lạnh chảy ròng sau gáy. "
        "Cô sợ Đạt vì gia đình cô mà bị đánh đập.</p>"
        "<p>Đạt không lùi. Tay trái anh khẽ vỗ nhẹ lên mu bàn tay nhỏ nhắn nhưng chai sạn của Duyên như một lời trấn an đầy vững chãi. "
        "Anh nhìn thẳng vào Lộc, giọng nói trầm ấm nhưng mang theo áp lực vô hình cực lớn: &ldquo;Bất động sản Huỳnh Gia gần đây nợ ngân hàng "
        "hơn hai ngàn tỷ, trái phiếu doanh nghiệp quá hạn không có khả năng thanh toán. Anh Lộc đây đi đòi nợ thuê để lấy tiền đập vào hố đen "
        "của gia đình mình sao? Sổ đỏ của đất trồng cây lâu năm miền Tây này, anh không có tư cách sờ vào.&rdquo;</p>"
        "<p>Lộc sững sờ. Bí mật tài chính của tập đoàn gia đình hắn đang bị che đậy gắt gao, tại sao một tên thợ làm vườn quèn ở Chợ Lách "
        "lại biết rõ như lòng bàn tay? Gương mặt hắn từ đỏ ngầu chuyển sang tái mét, rồi lại tức giận đến run người. Hắn nghiến răng "
        "chỉ thẳng tay vào mặt Đạt: &ldquo;Mày... Mày ngậm máu phun người! Đàn em, đập gãy tay thằng này cho tao!&rdquo;</p>"
        "<p>&ldquo;Dừng tay!&rdquo; Duyên hét lên, cô đứng chắn trước Đạt, hai hàng nước mắt uất ức cuối cùng cũng rơi xuống gò má. "
        "&ldquo;Huỳnh Hữu Lộc! Cho tôi thời gian 48 giờ! Tôi sẽ xoay tiền trả nợ. Nếu sau 48 giờ tôi không trả được, các người muốn làm gì "
        "thì làm. Còn bây giờ, bước ra khỏi vườn sầu riêng của ba tôi ngay lập tức!&rdquo;</p>"
        "<p>Lộc nhìn giọt nước mắt của Duyên, rồi lại nhìn ánh mắt lạnh như băng của Đạt khiến hắn lạnh sống lưng. Hắn hậm hực thu tay về, "
        "chỉnh lại cổ áo: &ldquo;Được! Trần Mỹ Duyên, tao cho cô 48 giờ. Đến lúc đó, không có tiền thì đừng trách tao tàn nhẫn. "
        "Còn thằng rác rưởi kia, tao sẽ nhớ mặt mày!&rdquo; Hắn quay lưng bước lên xe Raptor, tiếng cửa xe đóng &ldquo;rầm&rdquo; khô khốc. "
        "Chiếc bán tải lùi nhanh, gầm rú rồi lao vút đi, để lại một khoảng sân tràn ngập cát bụi đỏ và tiếng thở dài nặng nề của lòng người.</p>"
    )
    
    ch2_content = (
        "<p>Đêm Chợ Lách tĩnh mịch đến đáng sợ. Gió sông ngừng thổi, bầu không khí đặc quánh hơi ẩm của đất phù sa. Khoảng hai giờ sáng, "
        "dưới ánh trăng mờ đục bị mây đen che khuất, ba bóng đen trườn qua rặng dừa nước, tiếp cận hệ thống kênh dẫn nước chính của vườn "
        "sầu riêng nhà họ Trần. Chúng mang theo những can nhựa màu xanh lá cây đậm không có nhãn mác. Tiếng nước róc rách nhẹ nhàng từ chiếc "
        "máy bơm tự động công suất lớn đang hoạt động êm ái dưới mương bị át đi bởi tiếng côn trùng kêu ra rả.</p>"
        "<p>Một tên trong nhóm vặn nắp can nhựa. Một mùi hóa chất nồng nặc, hắc ín xộc lên. Hắn nghiêng can, đổ một dòng chất lỏng màu vàng "
        "nhạt, đậm đặc trực tiếp vào đầu hút của máy bơm tự động. Chất lỏng nhanh chóng hòa lẫn vào dòng nước phù sa ngọt ngào, theo đường "
        "ống nhựa HDPE dẫn trực tiếp đến hàng trăm vòi phun sương tự động cắm sâu dưới rễ và treo trên vòm lá của 50 hecta sầu riêng. "
        "Đây là chất diệt cỏ cực mạnh kết hợp với hoạt chất diệt rễ bị cấm lưu hành, có khả năng phân rã và triệt tiêu diệp lục của cây trồng "
        "chỉ trong vòng vài tiếng đồng hồ.</p>"
        "<p>&ldquo;Xong rồi, rút nhanh!&rdquo; Tên cầm đầu thì thầm, ném can nhựa rỗng xuống mương nước rồi lẩn khuất vào bóng tối.</p>"
        "<p>Năm giờ sáng, Nguyễn Tấn Đạt thức dậy theo thói quen. Bước ra khỏi gian nhà gỗ, anh lập tức khựng lại. Một mùi hóa chất hăng hắc, "
        "cay nồng bốc lên từ lòng đất ẩm ướt khiến cổ họng anh đau nhói, từng cơn ho khan bật ra ngoài ý muốn. Anh bước vội vào vườn sầu riêng. "
        "Đập vào mắt anh là một cảnh tượng kinh hoàng: dưới ánh sáng lờ mờ của bình minh, những chiếc lá Monthong xanh mướt, bóng bẩy hôm qua "
        "nay bắt đầu xoắn lại, mép lá cháy vàng úa như bị lửa thiêu. Từng cơn gió khẽ qua làm hàng nghìn chiếc lá rụng rào rào xuống mặt đất "
        "bùn như một cơn mưa vàng úa bi thương. Rễ cây sầu riêng ở những gốc gần vòi phun đã rữa ra, chuyển sang màu đen sẫm và bốc mùi hôi thối "
        "nồng nặc. Cả một khoảng trời xanh thẳm tràn đầy sức sống của nông trường giờ đây tràn ngập bầu không khí xám xịt của sự chết chóc.</p>"
        "<p>In trong căn nhà gỗ ba gian, tiếng rên rỉ yếu ớt của ông Trần Văn Minh vang lên. Cơn sốt cao do huyết áp bùng phát lại hành hạ cơ thể "
        "già nua. Mẹ của Duyên, bà Lê Thị Hoa, đang ngồi bên giường, tay bưng chén thuốc nam mà nước mắt lã chã rơi: &ldquo;Trời hại nhà tôi rồi "
        "ông ơi... Tiền nợ chưa trả, giờ đến cái vườn sầu riêng cũng xảy ra chuyện...&rdquo;</p>"
        "<p>&ldquo;Không... Không thể nào! Vườn sầu riêng của tôi!&rdquo; Tiếng hét thất thanh của Trần Mỹ Duyên vang lên xé lòng từ mép vườn. "
        "Cô chạy sộc vào vườn, chân trần dẫm trực tiếp lên những chiếc lá rụng úa vàng và lớp bùn đất đẫm độc chất. Nhìn những quả sầu riêng "
        "non đang bắt đầu rụng cuống xuống bùn, Duyên quỳ sụp xuống đất. Cô điên cuồng dùng hai tay bới đất bùn xung quanh rễ cây như muốn cào "
        "đi chất độc, móng tay cô găm chặt vào lớp đất sét cứng đến mức bật máu, hòa cùng dòng bùn xám xịt. Nước mắt cô tuôn rơi lã chã, "
        "thấm đẫm cả vạt áo bà ba dính đầy đất cát.</p>"
        "<p>Đạt bước tới, cúi người đỡ lấy đôi vai đang run rẩy kịch liệt của Duyên. &ldquo;Duyên, bình tĩnh lại. Đất đã bị nhiễm độc chất "
        "hệ thống cực mạnh. Đừng chạm tay trần vào nữa, độc chất bám vào da sẽ thẩm thấu gây nhiễm độc máu.&rdquo;</p>"
        "<p>&ldquo;Anh Đạt ơi... Nhà em mất trắng rồi... Trăm tỷ đầu tư, cả mạng sống của ba em... Đều nằm ở vườn cây này...&rdquo; Duyên khóc "
        "nghẹn ngào, gục đầu vào ngực Đạt. Đạt ôm chặt lấy cô, đôi mắt anh nheo lại đầy nguy hiểm, những đường gân xanh trên trán nổi lên cuồn cuộn. "
        "Anh khẽ vuốt mái tóc dính lá úa của cô, thầm ghi khắc mối thù này.</p>"
        "<p>Chưa dừng lại ở đó, khủng hoảng dồn dập ập đến như đã được lên kịch bản kỹ lưỡng. Chỉ chưa đầy hai tiếng sau, tiếng còi xe máy, "
        "tiếng động cơ ô tô xé toạc sự tĩnh lặng của trang trại. Hơn chục gã tự xưng là streamer mạng xã hội, phóng viên của các trang tin lá "
        "cải cầm theo máy quay Sony chuyên dụng, điện thoại iPhone gá trên gậy livestream ập đến cổng vườn. Chúng đứng ngoài hàng rào rào hét, "
        "chĩa thẳng camera vào trong, miệng liên tục đọc to những bình luận phẫn nộ từ buổi phát trực tiếp:</p>"
        "<p>&ldquo;Độc quyền trực tiếp! Nông trường sầu riêng sạch hữu cơ lớn nhất Chợ Lách dùng chất kích thích tăng trưởng cực độc bị cơ quan "
        "chức năng điều tra! Hàng loạt cây chết héo do lạm dụng hóa chất cấm gây ung thư cho người tiêu dùng! Hàng ngàn khán giả đang cực kỳ "
        "giận dữ yêu cầu tẩy chay toàn bộ sầu riêng miền Tây!&rdquo;</p>"
        "<p>Những câu hỏi vô căn cứ liên tục được ném qua hàng rào bằng chiếc loa cầm tay megaphone kêu rè rè: &ldquo;Cô Trần Mỹ Duyên! "
        "Có phải gia đình cô đã đầu độc nguồn nước sông Hàm Luông để thúc quả chín sớm không? Tại sao cây chết hàng loạt chỉ sau một đêm? "
        "Cô nói gì về việc khách hàng đòi kiện vì ngộ độc thực phẩm?&rdquo;</p>"
        "<p>Điện thoại của Duyên rung lên liên tục như muốn nổ tung. Từng cuộc gọi từ các hợp tác xã, thương lái thu mua xuất khẩu ở Sài Gòn "
        "và các đối tác đã đặt cọc đơn hàng dồn dập gọi đến với giọng điệu tức giận: &ldquo;Alô! Mỹ Duyên hả? Trên mạng đang rầm rộ tin vườn nhà "
        "em dùng chất cấm hóa học bị phong tỏa. Chúng tôi quyết định hủy hợp đồng ngay lập tức! Trả lại tiền cọc và bồi thường thiệt hại danh "
        "tiếng cho chúng tôi trong vòng 24 giờ, nếu không chúng tôi sẽ khởi kiện ra tòa án kinh tế!&rdquo;</p>"
        "<p>Đến chín giờ sáng, một chiếc xe bán tải công vụ màu xanh của Chi cục Trồng trọt và Bảo vệ Thực vật tỉnh Bến Tre cùng với lực lượng "
        "Quản lý thị trường đỗ xịch trước cổng. Vị trưởng đoàn bước xuống, gương mặt nghiêm nghị, cầm trên tay văn bản có dấu đỏ chót của Sở Nông nghiệp:</p>"
        "<p>&ldquo;Nhận được phản ánh của người dân về việc vườn sầu riêng Trần Gia sử dụng và phát tán độc chất hóa học cấm ra môi trường, "
        "chúng tôi ra quyết định tạm đình chỉ hoạt động sản xuất, phong tỏa toàn bộ nông trường trong vòng 24 giờ để lấy mẫu kiểm nghiệm. "
        "Đề nghị chủ cơ sở hợp tác ký vào biên bản phong tỏa!&rdquo;</p>"
        "<p>Tiếng &ldquo;cộp&rdquo; khô khốc của con dấu đỏ đóng sầm xuống tờ biên bản phong tỏa dán trực tiếp lên cột trụ gỗ của cổng vườn "
        "như một dấu chấm hết lạnh lùng. Duyên đứng không vững, toàn thân rụng rời. Đây là một đòn chí mạng phối hợp hoàn hảo. Vừa đầu độc vườn cây "
        "tiêu hủy tài sản, vừa dùng truyền thông bẩn hủy hoại danh tiếng, kết hợp với áp lực pháp lý đình chỉ hoạt động để triệt tiêu mọi con đường "
        "sống của nhà họ Trần trong vòng 48 giờ đòi nợ. Mọi thứ dường như đã sụp đổ hoàn toàn trước mắt cô tiểu thư miền Tây kiên cường.</p>"
    )
    
    ch3_content = (
        "<p>Khi những gã phóng viên lá cải và streamer hám lợi đã rút đi để kịp giật tít câu view cho buổi tối, vườn sầu riêng Trần Gia "
        "chìm vào một khoảng lặng tĩnh mịch đến tê tái. Hoàng hôn buông xuống trên dòng sông Hàm Luông, nhuộm đỏ cả một vùng nước mênh mang "
        "nặng phù sa bằng sắc màu cam cháy pha lẫn tím thẫm. Ánh nắng cuối ngày hắt hiu qua những kẽ lá sầu riêng úa vàng đang rụng đầy "
        "trên mặt đất sét xám. Mùi hóa chất cay nồng từ buổi sáng đã dịu bớt, nhưng mùi của sự lụi tàn và thất vọng vẫn lảng vảng trong không khí. "
        "Tiếng máy nổ của vài chiếc ghe ngo đuôi tôm chạy dọc dòng sông vọng lại từ xa càng làm tăng thêm vẻ cô tịch của vùng quê nghèo.</p>"
        "<p>Mỹ Duyên ngồi thất thần trên chiếc băng ghế gỗ cũ kỹ đặt dưới gốc dừa nước sát bờ sông. Đôi ủng bảo hộ dính đầy bùn khô được cô "
        "tháo ra đặt một góc, để lộ bàn chân nhỏ nhắn dính những vệt đất xám. Đôi bàn tay cô chai sạn vì những ngày tháng dầm mưa dãi nắng "
        "giúp ba chăm vườn nay đầy những vết xước rỉ máu do cào đất lúc sáng. Duyên nhìn chăm chăm ra dòng nước trôi lững lờ, nước mắt "
        "không còn để chảy, chỉ có sự trống rỗng hiện rõ trong ánh mắt.</p>"
        "<p>Đạt bước lại gần, bước chân anh nhẹ nhàng không gây tiếng động trên nền đất mềm. Anh cầm theo một thau nước ấm và một chiếc "
        "khăn bông sạch. Anh khẽ quỳ một gối xuống sàn gạch cũ bên cạnh băng ghế gỗ, đặt thau nước xuống. Đạt không nói lời nào sáo rỗng, "
        "anh nhẹ nhàng cầm lấy bàn tay nhỏ nhắn của Duyên, nhúng chiếc khăn vào nước ấm rồi cẩn thận lau sạch lớp bùn đất bám vào các vết xước "
        "trên ngón tay cô. Động tác của anh tỉ mỉ, nâng niu như thể đang chăm sóc một báu vật vô giá.</p>"
        "<p>Hơi ấm từ chiếc khăn bông và sự dịu dàng tột cùng của Đạt khiến lồng ngực Duyên thắt lại. Cô khẽ rút tay về nhưng Đạt giữ chặt "
        "lại bằng một lực vừa phải, ấm áp và vững chãi. Anh ngước mắt nhìn cô, ánh mắt chứa đựng sự bao dung và kiên định như núi thái sơn.</p>"
        "<p>&ldquo;Đạt này...&rdquo; Duyên khẽ gọi, giọng cô khàn đi. &ldquo;Anh có thấy tôi ngu ngốc lắm không? Nếu tôi chịu thỏa hiệp, "
        "chịu cúi đầu trước Huỳnh Hữu Lộc, có lẽ vườn sầu riêng của ba tôi đã không bị tàn phá như thế này. Ba tôi sẽ không phải nằm cấp cứu, "
        "mẹ tôi sẽ không phải khóc cạn nước mắt... Nhiều lúc tôi tự hỏi, tại sao ông trời lại tàn nhẫn với những người nông dân hiền lành "
        "chỉ biết bán mặt cho đất bán lưng cho trời như gia đình tôi?&rdquo;</p>"
        "<p>Cô cúi đầu, mái tóc xõa xuống che đi gương mặt u uất. &ldquo;Tôi nhớ ngày đầu tiên tôi vớt anh lên từ bờ sông Hàm Luông này. "
        "Lúc đó anh đang sốt cao li bì do sốt xuất huyết nặng, người ngợm dầm nước đến thâm tím. Tôi đưa anh về nhà, tự tay nấu từng thìa cháo gừng, "
        "mớm từng ngụm nước ấm cho anh. Nhìn gương mặt anh lúc hôn mê, tôi đã thấy một nỗi buồn sâu thẳm. Khi anh tỉnh lại và xin ở lại làm thuê "
        "không công, chỉ cần cơm ngày ba bữa, ba tôi đã gật đầu đồng ý. Suốt nửa năm qua, anh không chỉ làm vườn, anh còn thay đổi toàn bộ cách "
        "pha trộn phân bón sinh học hữu cơ giúp cây sầu riêng đạt năng suất chưa từng có. Anh luôn im lặng đứng sau bảo vệ tôi mỗi khi đám "
        "trai làng say xỉn tìm cách trêu chọc hay khi gã Huỳnh Hữu Lộc đến quấy nhiễu. Tôi luôn tự hỏi anh thực sự là ai, nhưng rồi tôi nhận ra "
        "thân phận của anh không còn quan trọng nữa...&rdquo;</p>"
        "<p>Duyên quay sang nhìn thẳng vào mắt Đạt, ngón tay khẽ siết chặt lấy vạt áo bảo hộ của anh, hơi thở ấm áp hòa lẫn mùi sương tối: "
        "&ldquo;Tôi đã xây dựng một giấc mơ lớn. Tôi muốn lập một hợp tác xã nông sản sạch, liên kết tất cả bà con Chợ Lách để xuất khẩu sầu riêng "
        "chính ngạch, thoát khỏi cái vòng luẩn quẩn bị thương lái ép giá và tín dụng đen bóp nghẹt. Nhưng giờ thì hết rồi... Hợp đồng bị hủy, "
        "vườn cây bị độc chết. Nhưng Đạt ơi, tôi muốn nói với anh điều này: Tôi yêu anh. Không phải vì gia thế hay tiền bạc, vì anh trong mắt "
        "tôi chỉ là một người làm vườn quèn. Tôi yêu anh vì sự vững chãi, tử tế và tri thức của anh. Cho dù ngày mai nhà họ Huỳnh có cướp đi "
        "nông trường này, tôi phải lên Sài Gòn làm thuê làm mướn, tôi vẫn muốn được đi cùng anh. Anh có sẵn lòng đi cùng tôi không?&rdquo;</p>"
        "<p>Trái tim Đạt rung động mạnh mẽ. Giữa thế giới hào môn xa hoa đầy rẫy những hợp đồng hôn nhân thương mại và sự lợi dụng lẫn nhau, "
        "lời tỏ tình thuần khiết, tự nguyện và kiên định của cô gái miền Tây này chính là viên ngọc quý giá nhất mà anh tìm kiếm cả đời. "
        "Anh siết chặt bàn tay Duyên, áp lên má mình, cảm nhận sự ấm áp chân thật của dòng máu đang chảy trong huyết quản cô.</p>"
        "<p>&ldquo;Duyên, nghe tôi nói,&rdquo; giọng Đạt trầm thấp nhưng vô cùng đanh thép, từng từ từng chữ như đóng đinh vào không gian sông nước. "
        "&ldquo;Cô đã giao trọn niềm tin cho tôi, thì tôi tuyệt đối sẽ không để cô phải chịu bất kỳ ấm ức nào. Giấc mơ hợp tác xã sạch của cô, "
        "vương quốc sầu riêng trăm tỷ này là mồ hôi nước mắt của gia đình cô, không một ai có thể cướp đi được. Sự giàu có thực sự nằm ở đất đai "
        "và tấm lòng kiên định của người nông dân như cô, chứ không phải mấy mảnh giấy lộn của sàn chứng khoán hay tiền bẩn của bọn cho vay nặng lãi. "
        "Hãy tin tôi. Sáng mai, tôi sẽ cho cô thấy sự phục sinh của nông trường này, và sự sụp đổ của những kẻ đã dám làm cô rơi nước mắt.&rdquo;</p>"
        "<p>Duyên nhìn sâu vào đôi mắt chứa đầy uy quyền của Đạt, dù không hiểu bằng cách nào anh có thể thực hiện được điều đó khi thời gian "
        "chỉ còn tính bằng giờ, nhưng trong lòng cô bỗng dâng lên một niềm tin mãnh liệt, xua tan hoàn toàn những nỗi sợ hãi tăm tối đang vây hãm.</p>"
    )
    
    ch4_content = (
        "<p>Mười một giờ đêm, khi Mỹ Duyên đã thiếp đi bên giường bệnh của ba cô dưới tác dụng của viên thuốc an thần nhẹ, Nguyễn Tấn Đạt "
        "lặng lẽ bước ra khỏi trang trại. Anh đi sâu vào khu rừng dừa nước rậm rạp ở ranh giới phía Bắc của nông trường, nơi không có ánh đèn "
        "và camera giám sát của bọn Huỳnh Hữu Lộc. Đạt rút từ trong túi áo bảo hộ ra một chiếc điện thoại di động đặc chủng màu đen titan, "
        "thiết kế chắc chắn với lớp vỏ chống sốc chuyên dụng siêu bền, màn hình tinh thể sapphire đang tỏa ra ánh sáng xanh lam dịu nhẹ. "
        "Đây là thiết bị kết nối vệ tinh trực tiếp đa tầng sử dụng thuật toán mã hóa lượng tử độc quyền của gia tộc Nguyễn.</p>"
        "<p>Anh quét vân tay sinh trắc học ba tầng, nhận diện mống mắt qua camera hồng ngoại và nhấn một dãy số bảo mật dài. Đầu dây bên kia "
        "nhanh chóng được kết nối chỉ sau nửa tiếng bíp. Giọng nói nghiêm nghị, đầy cung kính của Anthony - trợ lý đặc biệt kiêm Giám đốc "
        "điều hành văn phòng Tập đoàn Vận tải biển Á Châu tại Singapore vang lên rõ mồn một qua chiếc tai nghe bluetooth siêu nhỏ:</p>"
        "<p>&ldquo;Kính chào Thế tử! Ngài đã ẩn cư nửa năm qua, cuối cùng cũng chịu kích hoạt liên lạc. Hội đồng quản trị và Chủ tịch đang "
        "rất lo lắng cho ngài.&rdquo;</p>"
        "<p>&ldquo;Anthony, ngưng các thủ tục xã giao lại,&rdquo; Đạt ra lệnh bằng tiếng Anh chuẩn xác, giọng điệu sắc lạnh mang theo uy quyền "
        "tối cao của người thừa kế duy nhất đế chế trăm tỷ USD. &ldquo;Tôi cần kích hoạt quyền lực điều động khẩn cấp tối cao của tập đoàn. "
        "Trong vòng bốn tiếng nữa, tôi muốn phi đội drone nông nghiệp sinh học tối tân &lsquo;AeroShield-V9&rsquo; gồm 20 chiếc đang thử nghiệm "
        "tại phòng Lab đặc biệt ở Singapore phải có mặt tại sân bay quốc tế Cần Thơ. Hãy điều chuyên cơ vận tải Gulfstream G650 của gia đình "
        "cất cánh ngay lập tức từ Changi.&rdquo;</p>"
        "<p>&ldquo;Rõ! Thưa Thế tử, tôi thực sự kinh ngạc trước lệnh điều động khẩn cấp này của ngài,&rdquo; Anthony giật mình đáp lại bằng sự tôn kính tuyệt đối. "
        "&ldquo;Hải đội hàng không và logistics của chúng ta đã được khởi động. Tôi sẽ hoàn tất thủ tục thông quan ngoại giao khẩn cấp với Bộ Giao thông Vận tải "
        "và Tổng cục Hải quan Việt Nam ngay lập tức. Nhưng ngài cần dùng chúng để làm gì? Liệu có phải có biến động lớn về tài chính kinh tế không?&rdquo;</p>"
        "<p>&ldquo;Không, còn hơn thế nữa. Vườn sầu riêng của phu nhân tương lai của tôi bị đầu độc bằng chất diệt cỏ gốc Paraquat nồng độ cực cao. "
        "Tôi cần mang theo toàn bộ các nhà hóa sinh nông nghiệp hàng đầu của viện nghiên cứu Á Châu, cùng công thức giải độc enzym sinh học độc bản "
        "&lsquo;Bio-Cleanse v5.0&rsquo; để trung hòa độc chất. Hãy nhớ, đây là enzym cấu trúc phân rã chuỗi peptide sinh học được Lab R&D của chúng ta "
        "đăng ký bản quyền toàn cầu, có khả năng khóa các liên kết hóa chất cấm mà không làm hại cây trồng. Hãy chuẩn bị các bình phun áp suất "
        "tích hợp hệ thống phân phối đa phổ. Tôi muốn 5 xe container lạnh chuyên dụng hộ tống phi đội chạy dọc quốc lộ, vượt cầu Rạch Miễu về "
        "Chợ Lách trước bình minh. Hãy phối hợp với bên Cảnh sát giao thông để đảm bảo lộ trình thông suốt và bảo mật tuyệt đối.&rdquo;</p>"
        "<p>&ldquo;Tuân lệnh Thế tử! Hải đội hàng không Á Châu lập tức cất cánh!&rdquo;</p>"
        "<p>Bốn giờ sáng, khi sương mù dày đặc còn bao phủ mặt sông Hàm Luông trôi lững lờ, tiếng gầm rú của đoàn xe container chuyên dụng bọc thép màu bạc "
        "sang trọng dán logo hình mỏ neo vàng của Tập đoàn Á Châu áp sát ranh giới vườn sầu riêng Trần Gia. Vệt đèn LED sáng quắc từ đoàn xe "
        "xé toạc màn sương mờ mịt. Hai mươi vệ sĩ mặc vest đen lịch lãm, tai đeo bộ đàm bảo mật lập tức phong tỏa toàn bộ các lối vào trang trại, "
        "dứt khoát đẩy lùi đám tay sai của Lộc đang lén lút rình rập ngoài cổng. Một nhóm gồm sáu chuyên gia hóa sinh mặc trang phục bảo hộ vô trùng "
        "màu trắng nhanh chóng bước xuống xe, xách theo các vali chứa thiết bị phân tích mẫu đất kỹ thuật số, lập tức tiến hành định vị tọa độ nhiễm độc.</p>"
        "<p>Bình minh vừa hé rạng phía chân trời Chợ Lách. Những hạt sương sớm ban mai còn đọng trên những chiếc lá sầu riêng đang rụng úa. "
        "Nhưng bầu không khí nhanh chóng bị khuấy động bởi một âm thanh công nghệ cao cực kỳ phấn khích: tiếng &ldquo;o o o&rdquo; xé gió của "
        "động cơ phản lực cánh quạt không chổi than từ 20 chiếc drone AeroShield-V9 tối tân cất cánh đồng loạt từ thùng xe container mở rộng. "
        "Đồng loạt tiếng gầm rú nhẹ từ các cánh quạt sợi carbon tạo ra luồng gió mạnh mẽ, thổi tung lớp lá rụng úa vàng dưới mặt đất. Hệ thống "
        "vận hành hoàn toàn tự động được lập trình chuẩn xác theo lưới tọa độ vệ tinh GPS độ phân giải cao.</p>"
        "<p>Mỗi chiếc drone có sải cánh rộng hơn hai mét, làm bằng sợi carbon siêu nhẹ, trang bị camera đa phổ hồng ngoại để quét chính xác "
        "nồng độ độc chất dưới từng gốc cây. Dưới sự điều khiển của hệ thống máy tính trung tâm AI đặt trên xe chỉ huy, phi đội drone cất cánh "
        "xếp thành một đội hình lưới lục giác hoàn hảo trên bầu trời vương quốc sầu riêng. Chúng bắt đầu phun ra một luồng sương mịn, dày đặc "
        "màu xanh lục nhạt. Luồng sương sinh học độc quyền này chứa các chuỗi enzym được thiết kế đặc biệt để bám dính vào bề mặt lá, "
        "thấm sâu vào mạch dẫn và rễ cây, cô lập và phân rã hoàn toàn cấu trúc phân tử của độc chất hóa học Paraquat, biến chúng thành chất dinh dưỡng "
        "hữu cơ vô hại cho đất bùn. Những làn sương xanh lục nhạt phủ xuống vòm lá sầu riêng lấp lánh dưới ánh nắng sớm như những dải lụa tiên cảnh, "
        "tạo nên một khung cảnh tráng lệ, đầy công nghệ chấn động cả vùng quê nghèo miền Tây. Cả nông thôn Chợ Lách như bừng tỉnh trước một phép màu "
        "khoa học đỉnh cao chưa từng có trong lịch sử nông nghiệp nước nhà.</p>"
    )
    
    ch5_content = (
        "<p>Chỉ sau ba tiếng đồng hồ phi đội drone phun sương giải độc sinh học hoạt động liên tục, sự kỳ diệu bắt đầu hiển hiện trước mắt "
        "mọi người. Những chiếc lá Monthong đang xoắn lại úa vàng dần duỗi thẳng ra, sắc xanh lục tràn đầy sức sống bắt đầu hồi phục từ gân lá "
        "lan ra mép lá. Lớp vỏ rễ sầu riêng dưới lòng đất sét vốn bị đen sẫm nay đã bong tróc lớp tế bào chết, để lộ phần rễ non màu trắng hồng "
        "khỏe mạnh đang điên cuồng hút chất dinh dưỡng từ lớp phù sa đã được thanh lọc hoàn toàn. Những quả sầu riêng Monthong xanh biếc, "
        "nặng trĩu cuống đã bám chặt lại vào thân cây cổ thụ, không còn hiện tượng rụng hàng loạt như ngày hôm trước.</p>"
        "<p>Bên trong chiếc xe công vụ chuyên dụng được cải tiến thành phòng thí nghiệm di động của Sở Nông nghiệp, các thiết bị ly tâm xoay "
        "tít mù, chiếc máy sắc ký khí khối phổ (GC-MS) phát ra những tiếng bíp đều đặn khi phân tích các mẫu đất và lá sầu riêng được thu thập "
        "lâm sàng. Một nhà khoa học đeo kính cận gõ phím liên tục trên chiếc máy tính xách tay quân sự chống va đập, theo dõi biểu đồ nồng độ độc "
        "chất tụt dần về mức không tuyệt đối trên màn hình. Các kiểm nghiệm viên trầm trồ kinh ngạc: &ldquo;Thật không thể tin nổi! Cấu trúc Paraquat "
        "bị bẻ gãy hoàn toàn và chuyển hóa thành các hợp chất chứa nitơ vô hại chỉ trong vòng vài tiếng đồng hồ! Đây là công nghệ sinh học nông nghiệp "
        "vượt tầm thời đại!&rdquo;</p>"
        "<p>Đúng chín giờ sáng, đoàn thanh tra cùng các chuyên gia bước xuống xe nghiệm thu lâm sàng cuối cùng. Đi cùng họ còn có Huỳnh Hữu Lộc "
        "và đám thuộc hạ. Lộc bước vào với vẻ mặt đắc thắng, trong đầu đã hình dung ra cảnh tượng gia đình Duyên bị trục xuất khỏi mảnh đất này trong nhục nhã. "
        "Hắn cười khẩy gọi điện cho ba hắn: &ldquo;Ba yên tâm, thằng Ngô giám đốc ngân hàng đã chuẩn bị sẵn hồ sơ siết nợ rồi. Vườn cây này chết đứng "
        "chắc chắn 100%!&rdquo;</p>"
        "<p>&ldquo;Kính thưa các đồng chí thanh tra, tôi đề nghị niêm phong vĩnh viễn nông trường này và tiến hành tịch thu đất đai để tiêu hủy "
        "mầm bệnh hóa chất bảo vệ môi trường!&rdquo; Lộc lớn tiếng rêu rao trước hàng chục ống kính phóng viên đang chĩa vào.</p>"
        "<p>&ldquo;Im miệng!&rdquo; Vị Trưởng đoàn thanh tra Sở Nông nghiệp quát lớn, gương mặt ông nghiêm nghị cầm trên tay tờ kết quả kiểm nghiệm "
        "có dấu đỏ chót của Viện Cây ăn quả miền Nam. Ông đập mạnh tờ giấy xuống chiếc bàn gỗ giữa vườn sầu riêng trước mặt Lộc, tiếng &ldquo;cộp&rdquo; "
        "vang lên đanh thép dứt khoát.</p>"
        "<p>&ldquo;Kết quả phân tích 50 mẫu đất và lá sầu riêng tại các khu vực khác nhau của nông trường Trần Gia cho thấy: Chỉ số độc chất "
        "hóa học bằng KHÔNG! Ngược lại, nồng độ vi sinh hữu cơ có lợi trong đất đạt tiêu chuẩn siêu hạng, hoàn toàn đáp ứng chứng nhận "
        "GlobalGAP và hữu cơ châu Âu (USDA Organic). Nông trường Trần Gia hoàn toàn sạch sẽ, không có bất kỳ dấu hiệu lạm dụng hóa chất cấm nào! "
        "Quyết định tạm đình chỉ hoạt động chính thức được hủy bỏ ngay lập tức!&rdquo;</p>"
        "<p>Lộc trợn tròn mắt, hai chân run rẩy suýt quỳ sụp xuống sàn đất bùn. Gương mặt hắn biến dạng vì hoảng sợ, mồ hôi lạnh chảy ròng ròng "
        "sau gáy. &ldquo;Không... Không thể nào! Thuốc diệt cỏ cực mạnh đó... làm sao có thể biến mất không dấu vết chỉ sau một đêm? Các người "
        "ăn hối lộ đúng không?&rdquo;</p>"
        "<p>&ldquo;Kẻ ăn hối lộ và vi phạm pháp luật chính là mày đấy, Huỳnh Hữu Lộc!&rdquo;</p>"
        "<p>Một giọng nói dõng dạc, uy nghiêm vang lên từ cổng vườn. Ba chiếc xe chuyên dụng màu xanh của Cục Cảnh sát điều tra tội phạm về "
        "tham nhũng, kinh tế, buôn lậu (C03 Bộ Công An) phối hợp cùng Cục An ninh mạng và phòng chống tội phạm công nghệ cao (A05) ập vào trang trại. "
        "Tiếng cửa xe dập &ldquo;rầm rầm&rdquo; đanh thép, hơn mười chiến sĩ cảnh sát hình sự trong sắc phục chỉnh tề lập tức bao vây, khống chế "
        "Lộc và đám đàn em.</p>"
        "<p>Vị Thượng tá C03 bước lên, đưa ra lệnh bắt giam khẩn cấp có dấu đỏ của Viện kiểm sát nhân dân tối cao, giấy tờ phẳng phiu cứng cáp: "
        "&ldquo;Huỳnh Hữu Lộc! Chúng tôi khởi tố anh về tội &lsquo;Hủy hoại tài sản công dân&rsquo; và &lsquo;Vu khống truyền thông pháhoại an ninh "
        "kinh tế&rsquo;. Hệ thống camera nhiệt hồng ngoại ẩn trong vườn sầu riêng đã ghi hình rõ nét mặt đàn em của anh đổ độc chất vào mương nước "
        "lúc hai giờ sáng. Đồng thời, cục A05 đã truy quét toàn bộ dòng tiền 5 tỷ đồng từ tài khoản công ty của anh chuyển cho các tài khoản "
        "streamer bẩn để thực hiện chiến dịch truyền thông vu khống nông trường Trần Gia. Áp giải toàn bộ đối tượng về trụ sở điều tra!&rdquo;</p>"
        "<p>Để chứng thực, một chiến sĩ A05 bật chiếc máy tính bảng quân sự, hiển thị đoạn video hồng ngoại siêu nét ghi lại cảnh ba gã đàn em của Lộc "
        "đang lén lút đổ can hóa chất xanh đậm vào mương nước, cận cảnh khuôn mặt từng tên hiện lên rõ mồn một. Lộc nhìn màn hình, miệng há hốc "
        "nhưng không phát ra được âm thanh nào. Hắn biết mình đã hoàn toàn bại lộ dưới lưới trời lồng lộng.</p>"
        "<p>Tiếng còng số 8 vang lên &ldquo;lách cách&rdquo; lạnh lùng, khóa chặt đôi tay run rẩy của gã công tử hống hách Huỳnh Hữu Lộc. "
        "Gương mặt hắn xám ngoét không còn một giọt máu, miệng lắp bắp không thành tiếng khi bị áp giải lên xe cảnh sát dưới hàng chục máy ảnh "
        "và sự reo hò phấn khích của người dân Chợ Lách. Cú vả mặt pháp lý đanh thép đã đập tan hoàn toàn âm mưu thâu tóm bẩn thỉu của nhà họ Huỳnh. "
        "Mỹ Duyên nhìn theo chiếc xe công vụ rời đi, lòng dâng lên sự nhẹ nhõm vô bờ bến.</p>"
    )
    
    ch6_content = (
        "<p>Mặc dù Huỳnh Hữu Lộc đã bị bắt giữ, nhưng cuộc chiến tài chính vẫn chưa hoàn toàn kết thúc. Tại phòng giao dịch Agribank huyện Chợ Lách, "
        "bầu không khí căng thẳng bao trùm. Ba của Duyên, ông Trần Văn Minh, dù sức khỏe còn rất yếu vẫn phải ngồi trên chiếc xe lăn gỗ, "
        "được Duyên và mẹ cô đẩy vào phòng VIP của ngân hàng. Đứng đối diện họ là gã Giám đốc chi nhánh họ Ngô, người vốn dĩ đã nhận hối lộ "
        "từ ba của Lộc để đẩy gia đình Duyên vào đường cùng.</p>"
        "<p>&ldquo;Thưa ông Minh và cô Duyên, luật là luật,&rdquo; Ngô cười khẩy, ngón tay gõ nhịp xuống tập hồ sơ thế chấp nợ quá hạn 50 tỷ đồng. "
        "&ldquo;Dù vườn sầu riêng của các vị đã được chứng minh là sạch, nhưng khoản nợ gốc và lãi phạt 50 tỷ đã quá hạn 3 ngày. Theo quy định, "
        "chúng tôi bắt buộc phải tiến hành thủ tục phong tỏa tài sản và tổ chức bán đấu giá quyền sử dụng đất 50 hecta sầu riêng để thu hồi nợ. "
        "Không có bất kỳ ngoại lệ nào cả! Ký vào biên bản bàn giao đất đi, nếu không chúng tôi sẽ cưỡng chế pháp lý!&rdquo;</p>"
        "<p>Duyên đứng thẳng người, bàn tay siết chặt lấy thành xe lăn của ba cô, gân xanh nổi lên trên mu bàn tay nhỏ nhắn: &ldquo;Giám đốc Ngô! "
        "Các ông cố tình trì hoãn thủ tục gia hạn của chúng tôi để tạo điều kiện cho nhà họ Huỳnh thâu tóm đất đai. Chúng tôi sẽ khiếu nại "
        "lên Ngân hàng Nhà nước về hành vi sai phạm quy trình này!&rdquo;</p>"
        "<p>&ldquo;Khiếu nại?&rdquo; Ngô nhếch mép khinh bỉ. &ldquo;Cô cứ việc đi mà khiếu nại. Nhưng trước khi có kết quả khiếu nại thì đất của cô "
        "đã bị bán đấu giá xong xuôi rồi. Ở cái tỉnh Bến Tre này, ai dám cản quyết định của chi nhánh Agribank này chứ?&rdquo;</p>"
        "<p>&ldquo;Tôi cản.&rdquo;</p>"
        "<p>Cửa kính cường lực của phòng VIP đột ngột bị đẩy ra bởi hai vệ sĩ mặc vest đen cao lớn. Một bầu không khí vương giả, uy nghiêm "
        "tột cùng tràn vào căn phòng. Nguyễn Tấn Đạt bước vào. Nhưng anh không còn mặc chiếc áo bảo hộ sờn vai hay đi đôi ủng cao su lấm bùn "
        "ngày thường nữa. Thay vào đó là một bộ âu phục Tom Ford màu charcoal sẫm được may đo thủ công hoàn hảo ôm sát thân hình cao ráo, "
        "mạnh mẽ. Mái tóc đen được vuốt gọn gàng bằng sáp thơm cao cấp, để lộ vầng trán rộng thông minh và đôi mắt sắc lẹm như chim ưng. "
        "Mỗi bước đi của anh trên nền gạch men bóng loáng của ngân hàng đều phát ra tiếng &ldquo;cộp cộp&rdquo; giòn giã của đôi giày da thuộc "
        "Hermes đắt đỏ.</p>"
        "<p>Đi bên cạnh Đạt là một người đàn ông trung niên uy nghi mặc vest xám - đó chính là Giám đốc Vùng khu vực Tây Nam Bộ của hệ thống Agribank, "
        "người trực tiếp quản lý toàn bộ các chi nhánh miền Tây.</p>"
        "<p>Ngô nhìn thấy Giám đốc Vùng liền giật bắn mình, vội vàng đứng bật dậy, tháo kính xuống cúi đầu chào khúm núm: &ldquo;Kính... Kính chào "
        "Giám đốc Vùng! Sao ngài lại đột xuất xuống chi nhánh nhỏ của chúng em mà không báo trước thế này?&rdquo;</p>"
        "<p>Giám đốc Vùng không thèm nhìn Ngô, ông cung kính cúi người 90 độ trước Đạt, giọng nói run rẩy đầy kính sợ: &ldquo;Kính thưa Thế tử Nguyễn Tấn Đạt! "
        "Chúng tôi đã hoàn tất các thủ tục rà soát tài chính khẩn cấp theo yêu cầu của ngài.&rdquo;</p>"
        "<p>Đạt bước tới chiếc ghế VIP trung tâm, ngồi xuống một cách thong thả đầy khí chất đế vương. Anh khẽ búng ngón tay. Trợ lý Anthony "
        "lập tức mở chiếc vali Rimowa bằng nhôm cao cấp, đặt trước mặt Ngô một sắc lệnh tài chính có dấu đỏ của Ngân hàng Nhà nước và Tổng giám đốc Agribank:</p>"
        "<p>&ldquo;Ngô Đại Hùng! Chi nhánh Agribank Chợ Lách này từ hôm nay chính thức bị Tập đoàn Vận tải biển Á Châu mua đứt lại toàn bộ dư nợ xấu "
        "và tái cấu trúc nguồn vốn thông qua Vietcombank. Mày bị sa thải ngay lập tức, tước bỏ mọi chức vụ và chuyển hồ sơ sang C03 để điều tra "
        "hành vi nhận hối lộ, cấu kết với thế lực đen Huỳnh Gia để siết nợ trái pháp luật!&rdquo;</p>"
        "<p>Ngô Đại Hùng nghe xong như sét đánh ngang tai, toàn thân rụng rời, ngã quỵ xuống đất, gối quỳ đập xuống sàn gạch kêu cộp đau đớn. "
        "Hai cảnh sát tư pháp lập tức ập vào, xốc nách lôi hắn đi trong sự nhục nhã ê chề.</p>"
        "<p>Đạt quay sang nhìn Mỹ Duyên đang đứng ngơ ngác vì chấn động. Anh bước tới, nhẹ nhàng cầm lấy đôi bàn tay nhỏ nhắn của cô, giọng nói "
        "trở nên dịu dàng ấm áp vô cùng: &ldquo;Duyên, tôi xin lỗi vì đã giấu thân phận suốt nửa năm qua. Tôi là Nguyễn Tấn Đạt, người thừa kế "
        "của Tập đoàn Vận tải biển Á Châu. Nhưng trước hết, tôi là người đàn ông yêu cô bằng cả trái tim.&rdquo;</p>"
        "<p>Anh rút từ túi áo vest ra chiếc máy tính bảng bảo mật, nhấn nút xác nhận giao dịch. Màn hình hệ thống ngân hàng lập tức hiển thị dòng chữ: "
        "&ldquo;Giao dịch chuyển khoản THÀNH CÔNG: 100 tỷ đồng từ tài khoản Vietcombank Premium Nguyễn Tấn Đạt sang Agribank Chợ Lách. "
        "Tình trạng nợ của khách hàng Trần Văn Minh: ĐÃ TẤT TOÁN TOÀN BỘ.&rdquo;</p>"
        "<p>Chưa dừng lại ở đó, Đạt công bố trước hàng chục phóng viên báo chí tài chính đang vây kín sảnh ngân hàng: &ldquo;Tập đoàn Á Châu chính thức "
        "ký hợp đồng tài trợ độc quyền 500 tỷ đồng để phát triển thương hiệu sầu riêng hữu cơ sạch Trần Gia, bao tiêu toàn bộ đầu ra xuất khẩu "
        "đi châu Âu bằng hải đội tàu container lạnh tối tân của chúng tôi. Và Trần Mỹ Duyên, ái nữ duy nhất của Trần Gia, chính là phu nhân "
        "Thế tử duy nhất, người đồng sở hữu đế chế vận tải biển Á Châu từ ngày hôm nay!&rdquo;</p>"
        "<p>Mỹ Duyên bàng hoàng, nước mắt hạnh phúc nghẹn ngào rơi xuống lăn dài trên má. Cô gục đầu vào ngực Đạt dưới hàng loạt ánh đèn flash "
        "nhấp nháy liên tục của giới báo chí, tiếng gọi &ldquo;Anh Đạt!&rdquo; nghẹn ngào mà ngọt ngào tột cùng vang lên giữa sảnh ngân hàng. "
        "Một cái kết viên mãn, rực rỡ chấn động cả giang sơn miền Tây, đánh dấu sự trỗi dậy mạnh mẽ của nông sản Việt trên đỉnh cao quốc tế.</p>"
    )
    
    chapters = [
        { "title": ch1_title, "content": ch1_content },
        { "title": ch2_title, "content": ch2_content },
        { "title": ch3_title, "content": ch3_content },
        { "title": ch4_title, "content": ch4_content },
        { "title": ch5_title, "content": ch5_content },
        { "title": ch6_title, "content": ch6_content }
    ]
    
    novel_data = {
        "title": title,
        "author": author,
        "genre": genre,
        "intro": intro,
        "cover_prompt": cover_prompt,
        "chapters": chapters
    }
    
    target_path = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_novel.json"
    with open(target_path, "w", encoding="utf-8") as f:
        json.dump(novel_data, f, ensure_ascii=False, indent=2)
        
    print(f"✓ Created pending_novel.json at {target_path} successfully!")

if __name__ == "__main__":
    create_novel()
