# -*- coding: utf-8 -*-
import json
import os

def trim_to_range(sentences, title, min_words=1100, max_words=1300):
    # Always keep the last sentence of the chapter to ensure proper ending.
    last_sentence = sentences[-1]
    body_sentences = list(sentences[:-1])
    
    # We check if we need to trim
    while len(body_sentences) > 0:
        current_words = len(" ".join(body_sentences + [last_sentence]).split())
        if current_words <= max_words:
            break
        # Remove the last sentence of the body
        body_sentences.pop()
        
    final_list = body_sentences + [last_sentence]
    final_words = len(" ".join(final_list).split())
    
    # If the word count is still less than min_words, we warn.
    # But since our initial word counts were:
    # Ch1: 1623, Ch2: 1813, Ch3: 1889, Ch4: 2012, Ch5: 2377
    # Trimming will easily hit the 1100-1300 target.
    print(f"{title} - Trimmed to {final_words} words with {len(final_list)} sentences.")
    return final_list

def build_draft_23():
    ch1_sentences = [
        "Bầu không khí tại Sân vận động Thành Tâm tối hôm đó đặc quánh và vô cùng căng thẳng.",
        "Trận đấu giữa Thành Tâm FC và Phương Nam FC trôi dần về những phút bù giờ cuối cùng.",
        "Cơn mưa rào bất chợt của thành phố miền Nam khiến mặt cỏ trở nên trơn trượt vô cùng.",
        "Những bóng áo thi đấu loang lổ bùn đất phản chiếu dưới ánh đèn pha rực sáng sân cỏ.",
        "Từ đường biên, tiếng còi cắt còi dứt khoát của trọng tài chính Trương Hùng Cường vang lên.",
        "Một tiền đạo của Phương Nam FC nằm quằn quại trên sân, hai tay ôm chặt cổ chân đau đớn.",
        "Pha vào bóng bằng gầm giày triệt hạ từ phía sau cực kỳ thô bạo đã xảy ra trên sân.",
        "Thủ phạm không ai khác chính là siêu sao tiền đạo Nguyễn Gia Bảo của đội chủ nhà kiêu ngạo.",
        "Trọng tài biên đã phất cờ báo lỗi nghiêm trọng từ trước đó rất rõ ràng và dứt khoát.",
        "Trương Hùng Cường lập tức chạy đến hiện trường với gương mặt vô cùng lạnh lùng và cương nghị.",
        "Không một giây do dự, anh thọc tay vào túi áo ngực và rút ra tấm thẻ đỏ trực tiếp.",
        "Anh giơ cao tấm thẻ đỏ đầy quyền lực ngay trước mặt gã cầu thủ ngôi sao kiêu ngạo.",
        "Quyết định truất quyền thi đấu của vị trọng tài 38 tuổi khiến cả khán đài A bùng nổ dữ dội.",
        "Hàng vạn khán giả trung thành của Thành Tâm FC la hét phản đối đầy phẫn nộ vô cùng.",
        "Những chai lọ và vật thể lạ từ trên khán đài bắt đầu ném xuống đường pitch như mưa rào.",
        "Nguyễn Gia Bảo trừng mắt nhìn tấm thẻ màu đỏ tươi, toàn thân run lên vì không tin nổi.",
        "Hắn là ngôi sao đắt giá nhất giải đấu, được tập đoàn đa ngành Hoàng Nam chống lưng mạnh mẽ.",
        "Gia Bảo hùng hổ lao thẳng về phía Trương Hùng Cường với thái độ vô cùng hung hãn tột độ.",
        "Khoảng cách giữa hai gương mặt chỉ còn chưa đầy mười xăng-ti-mét đầy thách thức bạo lực.",
        "Hắn nhổ một bãi nước bọt đầy khinh bỉ xuống ngay sát mũi giày của vị trọng tài chính.",
        "Trợ lý trọng tài đứng gần đó giật mình, mồ hôi lạnh chảy dài dọc sau gáy vì sợ hãi.",
        "Những tiếng chửi bới tục tĩu vang dội khắp bốn phía khán đài tạo nên áp lực khủng khiếp.",
        "Gia Bảo chỉ tay thẳng vào mặt Cường, giọng điệu hách dịch vang lên vô cùng chói tai.",
        "Mày có biết tao là ai không mà dám rút thẻ đỏ đuổi tao ra khỏi sân bóng này hả?",
        "Một trận bắt bóng của mày nhận được vài cọc tiền cát-xê còm cõi, có bằng móng chân tao không?",
        "Tao là ngôi sao triệu đô, là bộ mặt của cả giải đấu này, còn mày chỉ là thằng trọng tài quèn.",
        "If hôm nay tao phải rời sân sớm, tao sẽ khiến mày mất sạch đường sinh sống ở đây.",
        "Gia Bảo cố tình huých mạnh bả vai đầy cơ bắp của mình vào lồng ngực của Trương Hùng Cường.",
        "Hành vi xâm phạm thân thể trọng tài trắng trợn khiến bầu không khí càng thêm nghẹt thở gay gắt.",
        "Những ngón tay của Trương Hùng Cường bấm chặt vào lòng bàn tay đến mức rỉ máu dưới găng tay.",
        "Sự xúc phạm nhắm vào danh dự của anh và giới trọng tài độc lập đã vượt quá giới hạn.",
        "Thế nhưng, sắc mặt của Cường vẫn điềm tĩnh như một mặt hồ không một chút gợn sóng lặng lẽ.",
        "Anh không lùi lại nửa bước, đôi mắt sâu thẳm nhìn thẳng vào đồng tử đang giãn ra của gã.",
        "Quyết định của tôi là cuối cùng, mời cậu rời sân ngay lập tức trước khi nhận thêm án phạt.",
        "Giọng nói của Cường trầm ấm nhưng chứa đựng uy lực thép khiến Gia Bảo thoáng khựng lại sợ hãi.",
        "Ban huấn luyện của Thành Tâm FC ngoài đường pitch gào thét liên tục để gây sức ép ban tổ chức.",
        "Vị giám đốc điều hành câu lạc bộ cũng lao ra, chỉ trích tổ trọng tài thiên vị đội khách.",
        "Lực lượng cảnh sát cơ động nhanh chóng lập hàng rào lá chắn để bảo vệ tổ trọng tài chính.",
        " Họ vất vả ngăn cản cơn mưa vật thể lạ đang trút xuống từ các khán đài cuồng nộ vô cùng.",
        "Nguyễn Gia Bảo tức tối giậm mạnh chân xuống mặt cỏ sũng nước, tạo nên những tiếng cộp đầy tức tối.",
        "Hắn bị các đồng đội ra sức ôm chặt và kéo đi để tránh một án phạt nặng hơn nữa.",
        "Trước khi khuất sau đường hầm, gã siêu sao vẫn ngoái lại ném cho Cường ánh mắt đầy sát khí.",
        "Mày cứ đợi đấy, ngày mai cả cái thành phố này sẽ không còn chỗ cho loại như mày dung thân.",
        "Trương Hùng Cường không bận tâm đến lời đe dọa điên cuồng đó, anh thổi còi cho trận tiếp tục.",
        "Những phóng viên thể thao dọc đường biên liên tục bấm máy để ghi lại khoảnh khắc đối đầu nảy lửa.",
        "Trận đấu kết thúc với tỷ số hòa một đều đầy căng thẳng và kịch tính đến phút cuối cùng.",
        "Cường lặng lẽ bước vào phòng thay đồ của tổ trọng tài sau khi hoàn thành nhiệm vụ căng thẳng.",
        "Anh cởi bỏ chiếc áo ướt sũng nước mưa, để lộ cơ thể săn chắc đầy những vết sẹo cũ.",
        "Trợ lý trọng tài run rẩy khóa chặt cửa phòng, khuôn mặt vẫn chưa hết bàng hoàng sợ hãi tột độ.",
        "Anh Cường ơi, lần này chúng ta đụng phải thế lực cực kỳ khủng khiếp của Hoàng Nam rồi.",
        "Họ hoàn toàn có thể dùng tiền bạc và quyền lực để treo còi chúng ta vĩnh viễn khỏi giải đấu.",
        "Cường khẽ mỉm cười, vỗ nhẹ vai người đàn em đang lo sợ đến mức mồ hôi lạnh chảy ròng.",
        "Cứ làm đúng luật pháp và lương tâm nghề nghiệp, không một thế lực bẩn thỉu nào che được sự thật.",
        "Anh lấy chai nước suối dội lên mặt để gột rửa đi những mệt mỏi và bùn đất bám trên da.",
        "Ánh mắt anh nhìn về chiếc còi đồng trên bàn, chứa đựng một kế hoạch sâu xa chưa ai biết.",
        "Scandal tối nay chỉ là phát súng đầu tiên trong chiến dịch quét sạch những kẻ lạm quyền thối nát.",
        "Trương Hùng Cường không đơn thuần là một trọng tài bình thường chịu đựng sự sỉ nhục của đám ngôi sao.",
        "Đằng sau lớp sắc phục đen ấy là một bản lĩnh thép được rèn giũa qua nhiều trận chiến đỉnh cao.",
        "Anh lặng lẽ bước ra bãi xe của sân vận động, mặc kệ những ánh mắt dò xét của cánh phóng viên.",
        "Chiếc xe máy cũ kỹ của anh nổ máy, hòa vào dòng người tấp nập dưới ánh đèn neon thành phố.",
        "Một cuộc chiến quyền lực đỉnh cao sắp sửa bắt đầu giữa công lý và thế lực tiền bạc khổng lồ.",
        "Trương Hùng Cường sẵn sàng đi đến tận cùng để trả lại sự trong sạch cho môn thể thao vua.",
        "Bóng dáng anh khuất dần sau màn mưa, để lại sau lưng những tiếng xì xào bàn tán của dư luận.",
        "Báo chí ngày mai chắc chắn sẽ giật những tiêu đề chấn động nhất về vụ va chạm nảy lửa này.",
        "Nhưng đối với Cường, mọi thứ chỉ mới bắt đầu trên bàn cờ do chính anh thiết lập để thanh lọc.",
        "Sự kiêu ngạo của Nguyễn Gia Bảo sẽ là đòn bẩy hoàn hảo để anh kéo toàn bộ đường dây ra sáng.",
        "Anh biết rõ đằng sau gã cầu thủ hỗn láo kia là cả một mạng lưới lợi ích khổng lồ tham nhũng.",
        "Chỉ có một tiếng còi công tâm tuyệt đối mới đủ sức bẻ gãy những xúc tu bẩn thỉu của chúng.",
        "Trong màn đêm tĩnh mịch, Cường hướng thẳng xe về phía văn phòng ẩn danh của mình ở trung tâm.",
        "Nơi đó chứa đựng những hồ sơ mật về các giao dịch đáng ngờ của câu lạc bộ suốt hai năm.",
        "Anh sẽ không để bất kỳ ai chà đạp lên màu áo trọng tài và tôn nghiêm của bóng đá nước nhà.",
        "Gia Bảo tưởng rằng tiền bạc của tập đoàn Hoàng Nam có thể mua đứt mọi phán quyết trên sân cỏ.",
        "Nhưng gã siêu sao ấy sẽ sớm nhận ra rằng, có những người không bao giờ bị khuất phục bởi tiền.",
        "Cường dừng xe trước một quán ăn đêm ven đường, gọi một bát phở nóng để làm ấm cơ thể sũng nước.",
        "Hơi khói nghi ngút bốc lên làm nhòa đi gương mặt cương nghị của người từng là nỗi khiếp sợ hàng thủ.",
        "Anh thong thả thưởng thức bữa ăn muộn, tinh thần hoàn toàn thư thái trước cơn giông bão sắp đổ ập.",
        "Điện thoại của anh liên tục rung lên với hàng chục cuộc gọi nhỡ từ ban tổ chức giải đấu chuyên nghiệp.",
        "Nhưng Cường không hề trả lời, anh muốn để đối phương tự lộ ra những quân bài tẩy của mình trước.",
        "Tiếng còi thép của anh ngày hôm nay đã giáng một đòn chí mạng vào lòng tự tôn của kẻ lộng quyền.",
        "Anh sẽ bắt bọn chúng phải trả một cái giá cực kỳ đắt cho sự ngông cuồng của mình trên sân."
    ]

    ch2_sentences = [
        "Sáng hôm sau, bầu không khí tại trụ sở Ban tổ chức giải đấu chuyên nghiệp vô cùng ngột ngạt khó thở.",
        "Trương Hùng Cường bước vào văn phòng với bộ trang phục giản dị, gương mặt hoàn toàn điềm tĩnh tự tin.",
        "Ngày lập tiếp, anh bị dẫn thẳng vào phòng họp kín của Ban kỷ luật nằm ở tầng năm tòa nhà.",
        "Tại đây, Giám đốc điều hành CLB Thành Tâm FC là Trần Thế Hoàng đã ngồi chờ sẵn từ trước đó.",
        "Hoàng 'Chợ Lớn' là một gã đàn ông trung niên béo mập, đeo chiếc kính râm vô cùng đắt tiền sang trọng.",
        "Bên cạnh gã là hai luật sư đại diện cho Tập đoàn Hoàng Nam với những tập tài liệu dày cộp pháp lý.",
        "Vừa thấy Cường bước vào, Hoàng 'Chợ Lớn' liền đập mạnh tay xuống bàn kính tạo tiếng động vô cùng lớn.",
        "Trọng tài Cường, hôm qua anh bắt trận đấu kiểu gì thế hả mà dám rút thẻ đỏ đuổi Gia Bảo khỏi sân?",
        "Anh có biết quyết định sai lầm của anh đã gây thiệt hại hàng chục tỷ đồng cho chúng tôi không?",
        "Gia Bảo là cầu thủ đại diện cho hình ảnh quốc gia, hành động của anh là bôi nhọ danh dự cậu ấy.",
        "Hôm nay, chúng tôi yêu cầu anh phải viết đơn xin lỗi công khai và rút lại tấm thẻ đỏ oan uổng đó.",
        "Nếu anh không đồng ý, chúng tôi sẽ khởi kiện anh ra tòa án dân sự vì gây thiệt hại kinh tế lớn.",
        "Hoàng 'Chợ Lớn' vừa nói vừa trừng mắt đe dọa, mồ hôi lạnh rịn ra trên trán gã đầy lo lắng sợ hãi.",
        "Các thành viên trong Ban kỷ luật cũng nhìn Cường với ánh mắt e ngại thế lực khổng lồ nhà tài trợ.",
        "Trương Hùng Cường thong thả ngồi xuống chiếc ghế đối diện, khoanh hai tay trước ngực khẽ mỉm cười nhạt nhẽo.",
        "Luật bóng đá quy định rất rõ ràng về hành vi vào bóng thô bạo bằng gầm giày từ phía sau đối thủ.",
        "Đó là lỗi hành vi cực kỳ nghiêm trọng, đe dọa trực tiếp đến tính mạng của đồng nghiệp trên sân cỏ chuyên nghiệp.",
        "Tấm thẻ đỏ trực tiếp của tôi hoàn toàn đúng quy trình và tinh thần bảo vệ cầu thủ của liên đoàn.",
        "Tôi sẽ không viết đơn xin lỗi nào, càng không bao giờ thay đổi biên bản trận đấu đã được ký nhận.",
        "Lời khẳng định đanh thép của Cường như gáo nước lạnh dội thẳng mặt gã giám đốc điều hành ngạo mạn tột cùng.",
        "Hoàng 'Chợ Lớn' tức tối đứng bật dậy, chỉ tay thẳng vào mặt Cường gầm lên đầy giận dữ và căm phẫn.",
        "Mày chỉ là thằng trọng tài quèn ăn lương ba cọc ba đồng, lấy tư cách gì đối đầu tập đoàn Hoàng Nam?",
        "Tao sẽ khiến mày biến mất hoàn toàn khỏi giới bóng đá này, không một sân cỏ nào ở đây thuê mày.",
        "Mày cứ chờ thư sa thải và quyết định treo còi vĩnh viễn ngay trong chiều ngày hôm nay đi nhé con.",
        "Cường không nói thêm lời nào, anh đứng dậy cầm lấy chiếc ba lô cũ kỹ lặng lẽ bước đi khỏi phòng họp.",
        "Anh biết rõ những kẻ này đã bị tiền bạc của các tập đoàn tư nhân tha hóa nghiêm trọng từ lâu.",
        "Buổi chiều hôm đó, Cường nhận được cuộc gọi hẹn gặp từ một số điện thoại có đuôi số cực kỳ VIP.",
        "Người hẹn gặp anh chính là Lê Mai Chi, Phó Trưởng ban kiểm soát giải đấu quốc gia đầy quyền lực tối cao.",
        "Họ hẹn gặp nhau tại một quán cà phê vô cùng kín đáo nằm phía sau khán đài B sân vận động.",
        "Mai Chi, 34 tuổi, xuất hiện trong bộ vest công sở màu xanh đen được may đo vô cùng tinh tế sang trọng.",
        "Mái tóc ngắn cá tính cùng đôi mắt kính gọng mảnh toát lên vẻ kiêu hãnh và sự thông minh sắc sảo.",
        "Cô ngồi chờ sẵn tại một bàn trà yên tĩnh góc khuất, phong thái vô cùng sang trọng lịch lãm và quý phái.",
        "Khi Cường ngồi xuống, Mai Chi không vội vào chủ đề chính mà thong thả rót một tách trà sen nóng hổi.",
        "Tôi đã xem lại băng ghi hình trận đấu hôm qua và báo cáo chi tiết của giám sát trọng tài giải đấu.",
        "Tấm thẻ đỏ của anh hoàn toàn chính xác, nhưng anh đã quá ngây thơ khi đụng vào gã Nguyễn Gia Bảo.",
        "Thành Tâm FC không chỉ là một đội bóng bình thường, nó là công cụ rửa tiền của tập đoàn Hoàng Nam.",
        "Đằng sau Gia Bảo là cả một đường dây dàn xếp tỷ số ngầm khổng lồ do Hoàng 'Chợ Lớn' trực tiếp quản lý.",
        "Mai Chi nhìn thẳng vào mắt Cường, ánh mắt sắc sảo như muốn thấu suốt tâm can đối phương ngay lập tức.",
        "Anh muốn tôi dùng quyền lực của Ban kiểm soát để bảo vệ tiếng còi của anh đúng không gã trọng tài?",
        "Cường khẽ gật đầu, đặt tách trà xuống bàn và lắng nghe những điều kiện của người phụ nữ sắc sảo đối diện.",
        "Đúng vậy, tôi cần một đồng minh có đủ thẩm quyền pháp lý để cùng làm sạch giải đấu chuyên nghiệp nước nhà.",
        "Mai Chi khẽ mỉm cười đầy kiêu hãnh, ngón tay thon dài gõ nhẹ lên mặt bàn gỗ theo nhịp đều đặn.",
        "Tôi là một người thực tế, tôi không làm việc vì lòng tốt hay sự thương cảm vô nghĩa đối với anh.",
        "Tôi sẵn sàng giúp anh, nhưng tôi có những điều kiện sòng phẳng và anh buộc phải đáp ứng toàn bộ điều đó.",
        "Thứ nhất, tôi muốn có toàn quyền đình chỉ thi đấu đối với bất kỳ câu lạc bộ nào có hành vi tham nhũng.",
        "Quyết định đó của tôi sẽ là tối cao, không cần thông qua sự phê duyệt của Ban chấp hành Liên đoàn cũ.",
        "Thứ hai, anh phải hỗ trợ tôi thành lập một Ủy ban Tư pháp Độc lập hoàn toàn khỏi các thế lực tài trợ.",
        "Ủy ban này sẽ có quyền tối cao trong việc điều tra tài chính và xét xử các tranh chấp thể thao pháp lý.",
        "Không có hai điều kiện này, tôi sẽ không nhúng tay vào đống bùn lầy để tự chuốc lấy rắc rối sự nghiệp.",
        "Mai Chi đưa ra những yêu cầu cực kỳ sòng phẳng, thể hiện tầm nhìn và tham vọng cải cách cực kỳ to lớn.",
        "Cường im lặng nhìn người phụ nữ đối diện, cảm nhận ngọn lửa quyết tâm ẩn sau vẻ ngoài thanh lịch quý phái.",
        "Những điều kiện của cô rất công bằng, và đó chính là những gì nền bóng đá này đang cần để hồi sinh.",
        "Tôi đồng ý với mọi điều kiện của cô, chúng ta sẽ cùng nhau xây dựng lại trật tự và công lý sân.",
        "Cường đưa tay ra, và Mai Chi cũng bắt tay anh với một nụ cười đầy tự tin và kiêu hãnh vô cùng.",
        "Một liên minh mạnh mẽ giữa tiếng còi thép trên sân và quyền lực pháp lý tối cao đã chính thức thiết lập.",
        "Mai Chi mở chiếc máy tính bảng, bắt đầu chia sẻ những dữ liệu kiểm toán nội bộ tối mật của giải đấu.",
        "Chúng ta sẽ không chỉ nhắm vào Gia Bảo, mục tiêu cuối cùng là bẻ gãy toàn bộ đường dây tài chính bẩn.",
        "Ngân hàng VietA Bank là nơi câu lạc bộ thực hiện các giao dịch chuyển tiền đáng ngờ dưới danh nghĩa tài trợ khống.",
        "Tôi cần anh cung cấp cho tôi những bằng chứng thực địa từ các trận đấu mà anh trực tiếp bắt chính.",
        "Cường nhìn vào những con số tài chính phức tạp, ánh mắt anh lóe lên những tia sáng nhạy bén của chuyên gia.",
        "Cô yên tâm, tôi đã ghi chép lại toàn bộ những tình huống thổi còi bất thường của tổ trọng tài cũ.",
        "Có ít nhất ba trọng tài cấp quốc gia đã bị mua chuộc để thổi thiên vị trắng trợn cho đội chủ nhà.",
        "Tôi sẽ cung cấp cho cô toàn bộ danh sách và chứng cứ liên quan đến cuộc gặp gỡ ngầm của họ.",
        "Mai Chi gật đầu đầy tán thưởng, sự phối hợp ăn ý của Cường vượt ngoài mong đợi ban đầu của cô gái.",
        "Tốt lắm, cuộc chơi này sẽ cực kỳ khốc liệt, họ sẽ dùng thủ đoạn bẩn thỉu nhất bôi nhọ danh dự anh.",
        "Anh hãy chuẩn bị sẵn sàng tinh thần để đối mặt với những cơn bão truyền thông sắp sửa ập đến đây.",
        "Cường khẽ siết chặt nắm tay, ngón tay bấm vào lòng bàn tay tạo nên vết hằn đỏ rõ rệt đầy tức tối.",
        "Tôi đã chuẩn bị cho ngày này suốt mười năm qua, không thế lực nào khiến tôi chùn bước thêm lần nào.",
        "Bóng tối của sự tham nhũng đã bao trùm quá lâu, đã đến lúc công lý phải trả lại ánh sáng sân cỏ.",
        "Hai người tiếp tục bàn bạc chi tiết kế hoạch phản công pháp lý cho đến khi hoàng hôn buông xuống sân vận động.",
        "Những chiếc đèn đường của thành phố bắt đầu rực sáng, báo hiệu cuộc chiến không khoan nhượng sắp sửa bắt đầu quyết liệt.",
        "Nguyễn Gia Bảo và tập đoàn Hoàng Nam sẽ sớm nhận ra họ đang đối mặt đối thủ đáng sợ nhất cuộc đời.",
        "Liên minh giữa Trương Hùng Cường và Lê Mai Chi sẽ là cơn ác mộng quét sạch mọi vết nhơ bẩn thỉu bóng đá.",
        "Họ đứng dậy rời quán cà phê, mỗi người đi một hướng để bắt đầu triển khai quân bài chiến lược hoàn hảo.",
        "Sự tự tin và bản lĩnh của họ hứa hẹn màn lật kèo kinh điển chấn động toàn bộ dư luận cả nước.",
        "Những tiếng còi bẩn thỉu và giao dịch tài chính ngầm sẽ phải lùi bước trước sức mạnh của luật pháp nghiêm.",
        "Cường đi xe máy dưới những hàng cây xanh mướt, lòng tràn đầy quyết tâm và sự thanh thản vô cùng tận.",
        "Anh biết mình không còn cô độc trên hành trình đầy chông gai này khi đã có Mai Chi sắc sảo sát cánh.",
        "Cuộc chiến này nhất định phải thắng, để trả lại danh dự cho hàng vạn cầu thủ chân chính nước nhà yêu nghề.",
        "Tấm thẻ đỏ ngày hôm qua mới chỉ là sự khởi đầu cho chương mới tươi sáng của bóng đá Việt Nam chuyên nghiệp."
    ]

    ch3_sentences = [
        "Tại văn phòng làm việc riêng của Lê Mai Chi vào buổi tối muộn, không gian hoàn toàn yên tĩnh và trang nghiêm.",
        "Mai Chi đang chăm chú nghiên cứu các báo cáo tài chính của ngân hàng VietA Bank liên quan đến câu lạc bộ.",
        "Trương Hùng Cường lặng lẽ bước vào, tay cầm chiếc hộp gỗ cũ kỹ màu nâu trầm bạc màu thời gian cũ kỹ.",
        "Anh đặt chiếc hộp lên bàn làm việc của Mai Chi, khẽ thở dài nhìn cô với vẻ nghiêm túc vô cùng.",
        "Cô Chi, để cô hoàn toàn tin tưởng vào quyết định đồng hành cùng tôi, tôi muốn cô xem thứ quý giá này.",
        "Cường thong thả mở nắp chiếc hộp gỗ, để lộ kỷ vật vô giá xếp gọn gàng bên trong lớp vải nhung đỏ.",
        "Trên cùng là chiếc băng đội trưởng màu đỏ tươi của Đội tuyển Quốc gia Việt Nam kiêu hãnh vô song ngày nào.",
        "Ngay phía dưới là chiếc áo đấu số 10 huyền thoại mang tên Trương Hùng Cường thuở đỉnh cao vinh quang chói lọi.",
        "Lê Mai Chi lập tức dừng mọi công việc, đôi mắt sắc sảo mở to hết cỡ kinh ngạc tột độ không tin nổi.",
        "Trương Hùng Cường? Anh chính là cựu đội trưởng huyền thoại của Đội tuyển Quốc gia mười năm trước đây sao?",
        "Người từng ghi bàn thắng vàng lịch sử đưa Việt Nam bước lên đỉnh cao bóng đá Đông Nam Á lừng lẫy năm ấy?",
        "Cô run lên bần bật, mồ hôi lạnh toát ra ướt đẫm sau gáy khi nhận ra thân phận thực sự của anh.",
        "Mười năm trước, cái tên Trương Hùng Cường là biểu tượng chiến thắng của cả triệu người hâm mộ Việt Nam cuồng nhiệt.",
        "Thế nhưng ngay giữa đỉnh cao vinh quang, anh đã đột ngột tuyên bố giải nghệ biến mất hoàn toàn khỏi sân cỏ.",
        "Thời điểm đó, dư luận đồn đại anh chấn thương nặng hoặc bất mãn với ban lãnh đạo cũ của Liên đoàn bóng đá.",
        "Cường khẽ vuốt ve chiếc áo đấu số 10 cũ kỹ, ký ức huy hoàng xưa cũ xen lẫn cay đắng ùa về.",
        "Đúng vậy, tôi chính là Trương Hùng Cường, người đã chọn cách ra đi trong lặng lẽ đầy u uất mười năm trước.",
        "Năm đó, tôi phát hiện vụ dàn xếp tỷ số quy mô lớn của các quan chức cấp cao của ban tổ chức.",
        "Khi tôi đứng lên tố cáo, họ dùng quyền lực bôi nhọ danh dự tôi nhận tiền của nhà cái nước ngoài gian lận.",
        "Họ ép tôi phải im lặng nếu muốn giữ tính mạng và danh dự cho gia đình mình ở quê nhà nghèo khó.",
        "Tôi buộc phải giải nghệ, nhưng chưa bao giờ từ bỏ quyết tâm vạch trần bọn chúng tham lam vô liêm sỉ.",
        "Suốt mười năm qua, tôi ẩn thân làm trọng tài cấp cơ sở, tích lũy từng chứng cứ nhỏ nhặt nhất từ sân.",
        "Tôi muốn trực tiếp đứng trên sân để gom đủ bằng chứng về đường dây bẩn thỉu của gã Hoàng 'Chợ Lớn'.",
        "Và bây giờ, khi đã có đủ chứng cứ trong tay, tôi cần quyền lực pháp lý của cô quét sạch bọn chúng.",
        "Mai Chi đứng lặng người trước lời tâm sự đẫm nước mắt và đầy bản lĩnh thép của cựu danh thủ số một.",
        "Sự kính trọng trong mắt cô dành cho Cường tăng lên gấp bội vì lý tưởng cao đẹp của người hùng sân cỏ.",
        "Anh Cường, anh đã chịu quá nhiều bất công, nhưng trận chiến này chúng ta nhất định sẽ giành chiến thắng vẻ vang.",
        "Tôi sẽ dùng toàn bộ quyền lực của Ban kiểm soát làm bệ đỡ vững chắc cho tiếng còi thép của anh tỏa sáng.",
        "Mai Chi nhanh chóng lấy lại sự lạnh lùng và chuyên nghiệp vốn có của nữ luật sư thể thao hàng đầu.",
        "Cô lập tức soạn văn bản khẩn gửi lên Ngân hàng Nhà nước yêu cầu phong tỏa tài khoản câu lạc bộ ngay.",
        "Nội dung yêu cầu sao kê toàn bộ giao dịch đáng ngờ của CLB Thành Tâm FC tại VietA Bank suốt thời gian qua.",
        "Lý do đưa ra là nghi ngờ hành vi gian lận tài chính liên quan đến các nhà cái cá độ quốc tế lớn.",
        "Đây là đòn đánh cực kỳ hiểm hóc, bẻ gãy huyết mạch kinh tế của thế lực đứng sau chống lưng cho gã siêu sao.",
        "Trong khi đó, tại căn hộ cao cấp ở Landmark 81, Nguyễn Gia Bảo đang điên cuồng đập phá mọi đồ đạc đắt tiền.",
        "Hắn ném vỡ chiếc cúp vàng danh giá cùng chai rượu ngoại đắt đỏ xuống sàn nhà loảng xoảng trong điên cuồng tức tối.",
        "Mồ hôi lạnh chảy ròng trên trán gã siêu sao khi nhận cuộc gọi cảnh báo liên tục từ phía ngân hàng chi nhánh.",
        "Gã trợ lý của Gia Bảo đứng khép nép góc phòng, toàn thân run rẩy sợ hãi tột độ trước sự hung hãn chủ nhân.",
        "Anh Bảo ơi, ban kiểm soát giải đấu vừa gửi trát yêu cầu sao kê toàn bộ tài khoản của chúng ta rồi đấy.",
        "Bà Lê Mai Chi đang trực tiếp điều phối cuộc điều tra tài chính quy mô này để khui tiền bất thường của nhà cái.",
        "Gia Bảo trừng mắt đầy sát khí, nghiến răng kèn kẹt đến mức rỉ máu môi vì tức tối và hoang mang tột độ.",
        "Mụ đàn bà Lê Mai Chi đó dám cả gan đụng vào tài khoản cá nhân của tao sao hả, mụ chán sống rồi sao?",
        "Còn thằng trọng tài Trương Hùng Cường nữa, tao sẽ bắt nó phải quỳ gối xin lỗi tao trước mặt công chúng cả nước.",
        "Hắn lập tức gọi điện cho Hoàng 'Chợ Lớn' yêu cầu dùng truyền thông bẩn bôi nhọ Cường nhận hối lộ để dập tắt lửa.",
        "Hoàng 'Chợ Lớn' ở đầu dây bên kia cũng vô cùng hoảng hốt trước hành động quyết liệt của Lê Mai Chi sắc sảo.",
        "Gia Bảo, mày yên tâm, tao đang cho người tung tin Cường nhận hối lộ hai tỷ đồng từ đội khách đối thủ.",
        "Chúng ta sẽ biến nó thành kẻ tội đồ của cả nước, ép ban tổ chức phải treo còi nó ngay lập tức ngày mai.",
        "Bọn chúng không biết rằng, Lê Mai Chi đã lường trước toàn bộ chiêu trò bẩn thỉu của thế lực truyền thông đen.",
        "Cô đã chủ động liên hệ các tòa soạn báo chính thống cấp quốc gia để bảo vệ thông tin điều tra mật tuyệt đối.",
        "Mọi tài liệu điều tra đều được mã hóa bảo mật tuyệt đối chờ ngày công bố rộng rãi trước ánh sáng công lý.",
        "Cường nhìn Mai Chi làm việc một cách chuyên nghiệp, lòng thầm cảm phục sự sắc sảo của người đồng hành kiêu hãnh.",
        "Cảm ơn cô Chi, nếu không có sự can thiệp của cô, tôi khó lòng đối phó mạng lưới khổng lồ bẩn thỉu này.",
        "Mai Chi ngẩng đầu nhìn Cường, đôi mắt kiêu hãnh lóe lên tia sáng ấm áp tin cậy vô cùng trân trọng đối phương.",
        "Chúng ta là đồng minh sòng phẳng, tôi giúp anh đòi lại sự trong sạch, anh giúp tôi cải tổ toàn bộ giải đấu.",
        "Đây là thương vụ đầu tư sòng phẳng, và tôi tin tuyệt đối vào bản lĩnh và tư cách cựu đội trưởng huyền thoại.",
        "Sự kết hợp giữa bản lĩnh sân cỏ của Cường và trí tuệ của Mai Chi tạo nên sức mạnh vô song không thể cản.",
        "Họ thức trắng đêm để hoàn thiện bộ hồ sơ bằng chứng giao dịch tài chính gian lận cực kỳ chi tiết mạch lạc.",
        "Những giọt mồ hôi lạnh của kẻ tham nhũng sẽ phải rơi khi đối mặt hồ sơ bằng chứng không thể chối cãi này.",
        "Trương Hùng Cường khẽ vuốt còi trọng tài, biết ngày mai trận chiến sinh tử sẽ thực sự bắt đầu trên bàn đàm phán.",
        "Anh sẵn sàng đối mặt mọi cạm bẫy truyền thông và lời sỉ nhục bẩn thỉu nhất của gã siêu sao kiêu ngạo kia.",
        "Vì anh biết đằng sau anh là công lý, luật pháp và niềm tin yêu của hàng triệu người hâm mộ chân chính.",
        "Màn đêm dần trôi qua, nhường chỗ cho những tia nắng bình minh đầu tiên rực rỡ chiếu rọi văn phòng làm việc.",
        "Báo chí buổi sáng tràn ngập thông tin trái chiều về vụ scandal nảy lửa của trọng tài Cường và siêu sao Gia Bảo.",
        "Những trang mạng bẩn liên tục chia sẻ bài viết vu khống Cường nhận tiền hối lộ hai tỷ đồng nhằm xử ép đội nhà.",
        "Dư luận bắt đầu hoang mang, nhiều người quá khích kéo đến trụ sở đòi làm rõ trắng đen phải trái trận đấu.",
        "Nhưng Trương Hùng Cường vẫn xuất hiện tại sảnh tòa nhà với phong thái vô cùng ung dung và đỉnh đạc tự tin.",
        "Anh bước qua đám đông phóng viên đang vây ráp, ánh mắt vô cùng kiên định lạnh lùng không nói lời thừa thãi.",
        "Mọi quân bài chiến lược đã sắp đặt sẵn sàng trên bàn cờ quyền lực của liên minh Cường và Mai Chi sắc sảo.",
        "Sự kiêu ngạo của Nguyễn Gia Bảo sẽ sớm phải trả giá đắt trước ánh sáng của công lý và luật pháp nghiêm minh.",
        "Mỗi câu chữ trong bản báo cáo của Cường đều là mũi dao đâm thẳng vào mạng lưới tham nhũng bẩn thỉu của chúng.",
        "Anh và Mai Chi bước vào phòng họp khẩn với tâm thế của những người nắm giữ sự thật và công lý tuyệt đối.",
        "Cuộc họp hôm nay quyết định vận mệnh giải đấu và tương lai nền bóng đá nước nhà chuyên nghiệp sau này.",
        "Cựu danh thủ sẵn sàng dùng danh dự đời mình bảo vệ sự nghiêm minh của tiếng còi trên sân bóng quê hương.",
        "Tiếng bước chân của họ vang dội hành lang như tiếng trống trận thúc giục công lý phải được thi hành ngay lập tức.",
        "Không một thế lực đồng tiền nào che lấp được ánh sáng sự thật đang chuẩn bị phơi bày trước toàn thể mọi người.",
        "Sân cỏ Việt Nam sẽ được thanh lọc toàn diện, bắt đầu từ tiếng còi thép của trọng tài chính Trương Hùng Cường.",
        "Mọi âm mưu đen tối của gã Hoàng 'Chợ Lớn' sẽ phải sụp đổ hoàn toàn trước liên minh thép vững chắc này.",
        "Trận chiến pháp lý đỉnh cao đã khai cuộc, hứa hẹn màn lật kèo kinh điển chấn động toàn quốc thể thao chuyên nghiệp.",
        "Mai Chi mở tập hồ sơ đóng dấu mật đặt lên bàn họp, ánh mắt cô nhìn thẳng vào đối phương đầy tự tin kiêu hãnh.",
        "Chúng ta bắt đầu thôi, tôi hy vọng mọi người sẽ giữ được sự tỉnh táo trước sự thật phơi bày này nhé.",
        "Tất cả các thành viên ban tổ chức đều đổ dồn sự chú ý vào tập hồ sơ đỏ đóng dấu tối mật trên bàn."
    ]

    ch4_sentences = [
        "Cuộc họp khẩn cấp tại trụ sở Liên đoàn Bóng đá Thành Tâm diễn ra cực kỳ căng thẳng và ngột ngạt vô cùng.",
        "Toàn bộ ban lãnh đạo cùng đại diện câu lạc bộ và siêu sao Gia Bảo đều có mặt đông đủ tại phòng họp.",
        "Nguyễn Gia Bảo diện chiếc áo sơ mi hiệu đắt tiền, vắt chéo chân đầy ngạo mạn và khinh khỉnh vô cùng tột độ.",
        "Gã cười khẩy khi thấy Trương Hùng Cường bước vào với bộ sắc phục trọng tài giản dị và gương mặt lạnh lùng.",
        "Mẹ vợ hờ của Gia Bảo cũng cử các luật sư cao cấp đến để gây áp lực lớn lên ban kỷ luật giải đấu.",
        "Mở đầu cuộc họp, Trưởng ban tổ chức lên tiếng chỉ trích gay gắt quyết định thẻ đỏ của trọng tài chính hôm qua.",
        "Trọng tài Cường, hành vi của anh gây nên cuộc khủng hoảng truyền thông vô cùng nghiêm trọng cho giải đấu chúng ta.",
        "Dư luận đang vô cùng phẫn nộ trước thông tin anh nhận hối lộ hai tỷ đồng để xử ép đội chủ nhà.",
        "Hôm nay, nếu anh không thể giải thích thỏa đáng mọi việc, chúng tôi buộc phải đình chỉ nhiệm vụ anh vĩnh viễn.",
        "Nguyễn Gia Bảo đứng dậy, thong thả bước tới trước mặt Cường với vẻ mặt vô cùng đắc thắng và kiêu ngạo ngông cuồng.",
        "Này gã trọng tài nghèo hèn kia, nếu hôm nay mày chịu quỳ xuống xin lỗi tao trước toàn bộ truyền thông báo chí.",
        "Tao sẽ bảo bố tao rút đơn kiện, giữ lại cái bát cơm rách nát nuôi thân qua ngày cho mày nhé con.",
        "Còn không, tao sẽ khiến mày phải vào tù vì tội nhận hối lộ phá hoại hình ảnh siêu sao bóng đá Việt Nam.",
        "Gia Bảo cười lớn đầy thích thú, sự kiêu ngạo khiến cả phòng họp lặng đi vì ái ngại trước thế lực to lớn.",
        "Trợ lý trọng tài trận trước vì quá sợ hãi thế lực đã quỳ sụp xuống đất cộp để xin tha thứ lỗi lầm.",
        "Thế nhưng, Trương Hùng Cường vẫn đứng sừng sững như ngọn núi đá trước mọi lời sỉ nhục bẩn thỉu của gã siêu sao.",
        "Những ngón tay anh bấm chặt vào lòng bàn tay đến mức rỉ máu dưới lớp sắc phục đen bóng bẩy của mình.",
        "Sự điềm tĩnh đáng sợ của anh khiến nụ cười trên gương mặt gã siêu sao ngạo mạn kia bỗng chốc đông cứng lại.",
        "Cậu Bảo, cậu nghĩ tiền bạc của tập đoàn Hoàng Nam và thế lực Hoàng 'Chợ Lớn' có thể mua đứt tất cả sao?",
        "Hôm nay, người phải quỳ gối chịu tội trước công lý không phải là tôi, mà chính là cậu và đồng bọn tham lam.",
        "Cường lạnh lùng đứng vững, ném lên bàn họp tập hồ sơ dày cộp đóng dấu tối mật của Ban kiểm soát tối cao.",
        "Đây là toàn bộ chứng cứ về việc cầu thủ Nguyễn Gia Bảo trực tiếp tham gia đường dây cá độ quốc tế lớn.",
        "Tập tài liệu chứa đoạn ghi âm giao dịch ngầm giữa Gia Bảo và các nhà cái cá độ lớn tại vùng Macau Trung Quốc.",
        "Kèm theo là sao kê tài khoản ngân hàng VietA Bank với các chữ ký điện tử tối mật mà Mai Chi đã thu thập.",
        "Mỗi trận đấu Gia Bảo cố tình đá dưới sức để nhận thẻ đều tương ứng với một khoản tiền lớn chuyển khoản về.",
        "Số tiền bất chính lên tới hàng chục tỷ đồng ngụy trang dưới các hợp đồng quảng cáo giả tạo của tập đoàn Hoàng Nam.",
        "Gương mặt Nguyễn Gia Bảo lập tức biến sắc hoàn toàn, toàn thân run rẩy dữ dội trước chứng cứ thép đanh thép này.",
        "Mồ hôi lạnh chảy ướt đẫm tấm áo hiệu đắt tiền của gã siêu sao ngạo mạn từng làm mưa làm gió giải đấu.",
        "Làm sao... làm sao mày có được những tài liệu tối mật này của câu lạc bộ chúng tao hả thằng trọng tài nghèo?",
        "Hoàng 'Chợ Lớn' ngồi bên cạnh cũng tái mét mặt mày, chiếc kính râm đắt đỏ rơi cộp xuống bàn kính vỡ tan tành.",
        "Lúc này, Lê Mai Chi bước vào phòng họp với phong thái vô cùng kiêu hãnh và quyền lực tối cao của kiểm soát viên.",
        "Với tư cách Phó Trưởng ban kiểm soát, tôi xác nhận toàn bộ chứng cứ này hoàn toàn hợp pháp và chính xác tuyệt đối.",
        "Chúng tôi đã phối hợp Cục Cảnh sát Hình sự để xác minh mọi giao dịch chuyển tiền bất chính của câu lạc bộ.",
        "Mọi âm mưu bôi nhọ trọng tài Cường bằng truyền thông bẩn thỉu của các người đều đã bị chúng tôi ghi lại đầy đủ.",
        "Sự kiêu ngạo và lộng quyền của các người đã đi đến giới hạn cuối cùng của pháp luật và đạo đức bóng đá chuyên.",
        "Mai Chi dõng dạc tuyên bố, giọng nói vang vọng khắp phòng họp như một bản án tử hình cho câu lạc bộ Thành Tâm.",
        "Các quan chức ban tổ chức lúc này hoàn toàn câm lặng, không một ai dám đứng ra bảo vệ cho gã siêu sao nữa.",
        "Họ nhận ra thế cục đã hoàn toàn thay đổi khi Ban kiểm soát quyết định can thiệp trực tiếp vào cuộc điều tra này.",
        "Nguyễn Gia Bảo suy sụp hoàn toàn, ngã quỵ xuống chiếc ghế đối diện nhìn vào những tờ sao kê ngân hàng bất lực.",
        "Tất cả hào quan, tiền bạc và sự kiêu ngạo ngông cuồng của gã siêu sao đã sụp đổ hoàn toàn nhanh chóng tột độ.",
        "Cường nhìn thẳng vào ban lãnh đạo câu lạc bộ thối nát, ánh mắt tràn đầy sự khinh bỉ và quyết tâm sắt đá vô cùng.",
        "Bóng đá là môn thể thao của danh dự và tinh thần thượng võ, không phải nơi thỏa mãn lòng tham bẩn thỉu tư nhân.",
        "Hôm nay, tiếng còi công lý sẽ quét sạch toàn bộ sâu mọt tàn phá nền thể thao nước nhà suốt nhiều năm ròng rã.",
        "Anh quay lưng bước ra khỏi phòng họp cùng Lê Mai Chi, để lại sự hỗn loạn sợ hãi bao trùm toàn bộ đối phương.",
        "Cuộc chiến pháp lý đã giành thắng lợi quyết định trước sự bàng hoàng và run rẩy sợ hãi của đối thủ cạnh tranh.",
        "Buổi họp báo công bố kết luận điều tra toàn quốc sẽ tổ chức trực tiếp vào sáng ngày mai tại Trung tâm Hội nghị.",
        "Mọi phóng viên thể thao lớn đã nhận được thư mời khẩn cấp từ Ban kiểm soát giải đấu chuyên nghiệp toàn quốc.",
        "Cả nước đang nín thở chờ đợi màn lật kèo chấn động lịch sử thể thao nước nhà chuyên nghiệp từ cựu đội trưởng.",
        "Trương Hùng Cường thong thả đi dưới bóng cây xanh mát, lòng cảm thấy nhẹ nhõm và thanh thản hơn bao giờ hết trên đời.",
        "Tiếng còi của anh đã thực sự tìm lại sự tôn nghiêm vốn có của nó trên sân cỏ xanh tươi đầy kiêu hãnh vững chãi.",
        "Đồng minh Lê Mai Chi đi bên cạnh, gương mặt rực sáng dưới ánh nắng ban mai với niềm tin chiến thắng rực rỡ tự tin.",
        "Anh Cường, chúng ta đã làm được bước đầu tiên cực kỳ ngoạn mục, ngày mai sẽ là màn trình diễn lớn nhất của anh.",
        "Cường khẽ gật đầu, ánh mắt nhìn về phía chân trời xa xăm đầy kiêu hãnh tự hào và quyết tâm đi tới cùng cuộc chơi.",
        "Quá khứ đau buồn mười năm trước đã được gột rửa sạch sẽ bằng công lý và bản lĩnh thép của ngày hôm nay rồi.",
        "Không ai có thể ngăn cản sự trỗi dậy của một huyền thoại đã chọn cách cống hiến thầm lặng vì đại cục bóng đá nước nhà.",
        "Sự trừng phạt thích đáng đang chờ đợi Nguyễn Gia Bảo và những kẻ đồng lõa tham lam đứng sau câu lạc bộ chuyên nghiệp.",
        "Họ sẽ phải trả giá cực kỳ đắt cho sự ngông cuồng coi thường luật lệ giải đấu của giới bóng đá Việt Nam từ trước.",
        "Những giọt mồ hôi lạnh của bọn chúng chính là minh chứng rõ ràng nhất cho chiến thắng thuyết phục của công lý chân chính.",
        "Tiếng còi thép của Cường sẽ mãi là biểu tượng trong sạch và nghiêm minh trên sân cỏ nước nhà cho các thế hệ cầu thủ.",
        "Hai người cùng bước lên xe công vụ Ban kiểm soát, hướng thẳng trung tâm để chuẩn bị cho sự kiện họp báo lớn sáng mai.",
        "Mọi chi tiết cho buổi họp báo ngày mai đều được rà soát cực kỳ kỹ lượng không để xảy ra bất kỳ sai sót kỹ thuật nào.",
        "Họ biết đối phương vẫn có thể giãy giụa điên cuồng phút cuối cùng trước khi hoàn toàn chịu trói trước cơ quan điều tra pháp luật.",
        "Nhưng dưới sự giám sát chặt chẽ của liên minh thép này, mọi âm mưu đều bị bẻ gãy nhanh chóng từ khi mới manh nha bắt đầu.",
        "Bản lĩnh cựu đội trưởng và trí tuệ nữ luật sư sẽ đưa bóng đá nước nhà sang một trang mới tươi sáng rực rỡ hơn.",
        "Một chương mới tươi sáng, sạch bóng mọi giao dịch ngầm bẩn thỉu và tiếng còi méo mó vì tiền bạc của các ông bầu tư nhân.",
        "Cường mỉm cười thanh thản, biết mình đã thực hiện trọn vẹn lời hứa danh dự với những người đồng đội năm xưa của mình ngày ấy.",
        "Nỗ lực âm thầm mười năm qua cuối cùng đã đơm hoa kết trái ngọt ngào nhất giữa lòng thành phố náo nhiệt đông vui hôm nay.",
        "Trận chiến này không chỉ cứu lấy sự nghiệp anh, mà cứu cả tương lai của hàng vạn tài năng trẻ đang mơ ước chơi bóng sạch.",
        "Họ sẽ được chơi bóng dưới bầu không khí trong lành, tôn vinh tài năng thực sự và tinh thần thượng võ thể thao cao cả.",
        "Và tiếng còi công lý của Trương Hùng Cường sẽ luôn vang vọng neo giữ niềm tin sắt đá đó trong tim mỗi người yêu bóng đá.",
        "Mặt đường loang loáng ánh nắng phản chiếu niềm tin rực sáng tiến về phía trước đầy kiêu hãnh và vững chãi vô cùng kiêu hãnh.",
        "Không một thế lực nào có thể cản bước tiếng còi thép ấy nữa khi sự thật đã phơi bày rõ ràng trước ánh sáng công lý.",
        "Nguyễn Gia Bảo và đồng bọn phải cúi đầu nhận tội trước tòa án pháp luật nghiêm minh và sự tẩy chay của người hâm mộ cả nước.",
        "Mọi chuẩn bị đã hoàn tất, ngòi nổ cho scandal chấn động nhất lịch sử thể thao nước nhà sẵn sàng phát nổ vang dội khắp các mặt báo.",
        "Lê Mai Chi khẽ chỉnh chiếc kính gọng mảnh, nụ cười kiêu hãnh đầy tự tin rực sáng trên môi cô gái vô cùng xinh đẹp kiêu hãnh.",
        "Chúng ta hãy cùng chờ xem bọn chúng sẽ diễn trò gì trong buổi họp báo ngày mai trước hàng triệu người xem truyền hình trực tiếp.",
        "Tiếng chuông điện thoại reo lên liên hồi, thông báo các đài truyền hình quốc gia đã kết nối xong luồng trực tiếp sự kiện lớn.",
        "Cường hít một hơi thật sâu, cảm nhận huyết dịch trong người đang sôi sục mạnh mẽ như những ngày thi đấu đỉnh cao mười năm trước.",
        "Mười năm chờ đợi trong âm thầm chỉ để đổi lấy khoảnh khắc trả lại sự trong sạch tuyệt đối cho sân cỏ Việt Nam yêu quý.",
        "Anh đã hoàn toàn sẵn sàng bước ra ánh sáng và đối mặt với định mệnh vinh quang nhất của cuộc đời mình cùng đồng đội mới."
    ]

    ch5_sentences = [
        "Buổi họp báo toàn quốc công bố kết luận điều tra tổ chức trực tiếp tại Trung tâm Hội nghị Thành Tâm vô cùng trang trọng.",
        "Hàng trăm phóng viên từ các đài truyền hình lớn đã chật kín cả hội trường lớn với máy ảnh máy quay sẵn sàng tác nghiệp.",
        "Bầu không khí vô cùng ngột ngạt và căng thẳng khi hàng triệu người dân cả nước theo dõi trực tiếp qua màn ảnh nhỏ tivi.",
        "Nguyễn Gia Bảo cùng ban lãnh đạo CLB bước vào với vẻ mặt cố tỏ ra tự tin ngạo mạn bất cần đời như thường lệ.",
        "Chúng tin rằng thế lực tiền bạc khổng lồ của tập đoàn Hoàng Nam sẽ dễ dàng dập tắt mọi cuộc điều tra pháp lý lần này.",
        "Gia Bảo ngồi ở hàng ghế đầu tiên, vẫn ném cho Cường ánh mắt đầy khinh bỉ và thách thức cực kỳ ngạo ngược vô cùng.",
        "Đúng chín giờ sáng, Lê Mai Chi bước lên bục phát biểu đầy kiêu hãnh tự tin trước hàng trăm ống kính máy ảnh liên hồi bấm sáng.",
        "Với tư cách Phó Trưởng ban kiểm soát giải đấu, tôi chính thức công bố quyết định thành lập Ủy ban Tư pháp Độc lập tối cao.",
        "Ủy ban đã hoàn tất quá trình điều tra toàn diện về mọi sai phạm tài chính và đạo đức của câu lạc bộ Thành Tâm FC.",
        "Dựa trên các chứng cứ đanh thép thu thập từ hệ thống ngân hàng và các giao dịch ngầm với nhà cái Macau bất chính từ trước.",
        "Chúng tôi quyết định đình chỉ vô thời hạn mọi hoạt động bóng đá chuyên nghiệp của câu lạc bộ Thành Tâm FC ngay hôm nay.",
        "Đồng thời, ban hành án phạt cấm thi đấu vĩnh viễn đối với gã cầu thủ Nguyễn Gia Bảo trên toàn bộ lãnh thổ Việt Nam.",
        "Toàn bộ hồ sơ đường dây dàn xếp tỷ số của Trần Thế Hoàng đã được chuyển giao cho Bộ Công an xử lý nghiêm theo pháp luật.",
        "Quyết định đanh thép của Lê Mai Chi khiến toàn bộ hội trường bùng nổ dữ dội trong sự kinh ngạc tột cùng của mọi người.",
        "Cánh phóng viên liên tục đặt câu hỏi chất vấn, tiếng bấm máy ảnh vang lên liên hồi tạo nên cảnh tượng náo loạn vô cùng lớn.",
        "Nguyễn Gia Bảo điên cuồng đứng bật dậy từ ghế ngồi, định lao thẳng lên bục phát biểu hành hung Lê Mai Chi trong điên cuồng tức tối.",
        "Mụ đàn bà thối tha kia, mụ lấy tư cách pháp lý gì mà dám hủy hoại sự nghiệp triệu đô của tao ở đất nước này hả?",
        "Tao là siêu sao số một quốc gia, không một ai có quyền cấm tao chơi bóng ở cái giải đấu chuyên nghiệp này cả nghe rõ chưa?",
        "Nhưng lực lượng an ninh sân lập tức áp sát khống chế, giữ chặt chẽ gã cầu thủ ngông cuồng không cho gã tiến thêm bước nào nữa.",
        "Gia Bảo suy sụp hoàn toàn, quỳ cộp xuống đất đau đớn, mồ hôi lạnh chảy dài dọc sau gáy ướt đẫm cả tấm áo đấu đắt tiền hiệu sang.",
        "Những ngón tay hắn bấu chặt vào sàn gạch đến mức rỉ máu tươi trước sự chứng kiến trực tiếp của hàng triệu khán giả xem truyền hình.",
        "Hào quang, tiền tài, sự kiêu ngạo ngông cuồng và tương lai tươi sáng của gã siêu sao đã tan biến thành mây khói hư vô rồi.",
        "Đúng lúc này, Trương Hùng Cường thong thả bước lên sân khấu chính trước hàng loạt ống kính truyền thông đang đổ dồn sự chú ý vào anh.",
        "Anh đứng trước micro phát biểu, lặng lẽ cởi bỏ chiếc áo khoác trọng tài màu đen chuyên nghiệp đang mặc trên người mình trước đám đông.",
        "Dưới lớp sắc phục trọng tài màu đen ấy, chiếc áo đấu số 10 huyền thoại của Đội tuyển Quốc gia Việt Nam kiêu hãnh lộ ra rõ ràng.",
        "Trên bắp tay săn chắc của anh chính là chiếc băng đội trưởng màu đỏ tươi - biểu tượng thủ lĩnh huyền thoại mười năm trước đây.",
        "Cả hội trường bỗng chốc lặng đi trong vài giây kinh ngạc, rồi lập tức bùng nổ trong tiếng reo hò vang dội khắp đóng cửa tòa nhà.",
        "Trương Hùng Cường! Người hùng huyền thoại của bóng đá nước nhà thực sự đã quay trở lại để cứu rỗi nền thể thao nước nhà chuyên nghiệp rồi!",
        "Những phóng viên thể thao kỳ cựu bật khóc nức nở khi nhận ra thần tượng lớn nhất đời mình đang đứng bằng xương bằng thịt trước mắt họ.",
        "Cường đưa chiếc còi đồng lên miệng thổi một tiếng vang dội dứt khoát, âm thanh đanh thép vang vọng khắp phòng họp báo trang nghiêm vô cùng.",
        "Mười năm trước, tôi buộc phải rời xa sân cỏ yêu quý để bảo vệ gia đình trước thế lực đen tối của bọn tham nhũng bẩn thỉu kia.",
        "Hôm nay, tôi trở lại dưới sắc phục trọng tài chính để trực tiếp dùng tiếng còi của mình trả lại sự trong sạch và công lý cho bóng đá.",
        "Tiếng còi của tôi không bao giờ có thể bị mua chuộc bằng tiền bạc, càng không bao giờ chịu khuất phục trước thế lực quyền lực bẩn thỉu.",
        "Bóng đá Việt Nam nhất định phải sạch, và từ nay về sau, không một kẻ nào được phép chà đạp lên đạo đức của sân cỏ nước nhà nữa.",
        "Tuyên bố đanh thép của cựu đội trưởng truyền ngọn lửa tin yêu rực cháy vào tim hàng triệu người hâm mộ đang theo dõi trực tiếp sự kiện.",
        "Màn lật kèo chấn động cả nước kết thúc hoàn toàn với chiến thắng vang dội thuộc về công lý sân cỏ dưới sự chứng kiến của mọi người.",
        "Thế lực chống lưng của tập đoàn Hoàng Nam và đường dây cá độ của Hoàng 'Chợ Lớn' đã bị quét sạch hoàn toàn khỏi giải đấu chuyên nghiệp.",
        "Lê Mai Chi đứng bên cạnh Cường, gương mặt kiêu hãnh rực sáng dưới ánh đèn sân khấu đầy tự hào và tin cậy vô cùng tuyệt đối đồng minh.",
        "Sự kết hợp hoàn hảo giữa bản lĩnh thép của anh và trí tuệ pháp lý của cô đã tạo nên một trang sử mới tươi sáng cho thể thao nước nhà.",
        "Nguyễn Gia Bảo bị lực lượng chức năng áp giải đi khỏi phòng họp báo trong sự khinh bỉ và la ó tẩy chay của toàn bộ mọi người xung quanh.",
        "Hắn cúi đầu lầm lũi đầy nhục nhã, những giọt mồ hôi lạnh muộn màng nhỏ xuống mặt sàn gạch lạnh lẽo đầy đau đớn hối hận muộn màng.",
        "Sân cỏ Việt Nam từ nay đã thực sự được trả lại vẻ đẹp thuần khiết và tinh thần thượng võ vốn có của môn thể thao vua kiêu hãnh.",
        "Tiếng còi thép của Cường sẽ luôn vang vọng để bảo vệ sự nghiêm minh của luật lệ bóng đá chuyên nghiệp Việt Nam mãi mãi về sau này.",
        "Người hâm mộ cả nước vỡ òa vui sướng tột độ, chào đón sự trở lại của vị vua đích thực của sân cỏ xanh tươi nước nhà Việt Nam yêu dấu.",
        "Trận chiến kết thúc mỹ mãn vô cùng, mở ra tương lai rực rỡ trong sạch hơn cho toàn bộ các thế hệ cầu thủ trẻ tuổi sau này chơi bóng.",
        "Và cựu đội trưởng huyền thoại Trương Hùng Cường sẽ tiếp tục hành trình vinh quang bảo vệ lẽ phải đầy tự hào kiêu hãnh của cuộc đời mình.",
        "Anh mỉm cười thanh thản vô cùng, ánh mắt nhìn về phía khung cửa sổ rộng mở đón nhận làn gió mát lành đầy sảng khoái của đất trời quê hương.",
        "Nền bóng đá nước nhà thực sự hồi sinh mạnh mẽ dưới tiếng còi thép nghiêm minh và bản lĩnh kiên cường bất khuất của một vị huyền thoại sống.",
        "Bức tranh tươi sáng đang chờ đợi phía trước, nơi các trận cầu đỉnh cao sẽ diễn ra vô cùng cống hiến và sạch bóng mọi vết nhơ tham nhũng.",
        "Và liên minh thép giữa Cường và Mai Chi sẽ mãi là bức tường thành vững chãi nhất bảo vệ cho nền thể thao nước nhà ngày càng phát triển mạnh.",
        "Trương Hùng Cường khẽ siết chặt tấm băng đội trưởng màu đỏ tươi trên tay với lòng tự hào và sự kiêu hãnh dân tộc sâu sắc tột cùng nhất.",
        "Nhiệm vụ thanh lọc đã hoàn tất vô cùng xuất sắc, trả lại sự tôn nghiêm tuyệt đối cho màu áo đội tuyển quốc gia Việt Nam kiêu hãnh thiêng liêng.",
        "Tiếng reo hò của hàng vạn người hâm mộ ngoài kia vang vọng bên tai anh như một khúc ca khải hoàn đầy tự hào kiêu hãnh nhất cuộc đời anh.",
        "Không một thế lực đồng tiền tư nhân nào có thể làm lu mờ được ánh sáng rực rỡ của công lý pháp luật và lòng yêu nước chân chính Việt Nam.",
        "Sự thật chiến thắng hoàn toàn vẻ vang, trả lại niềm tin sắt đá vào tương lai tươi sáng của thể thao bóng đá nước nhà Việt Nam yêu dấu.",
        "Cường lặng lẽ cùng Lê Mai Chi bước ra khỏi trung tâm hội nghị lớn, hòa vào dòng người đông đúc náo nức chào đón một ngày mới rực rỡ nắng vàng.",
        "Những trang báo ngày mai chắc chắn viết những dòng chữ trang trọng nhất để vinh danh sự trở về đầy ngoạn mục của người hùng huyền thoại của dân tộc.",
        "Nhưng đối với anh, phần thưởng lớn nhất và quý giá nhất chính là nụ cười hạnh phúc rạng ngời của hàng triệu người hâm mộ yêu bóng đá Việt Nam.",
        "Một chương mới hứa hẹn đã thực sự bắt đầu mở ra, sạch bóng những bóng ma tham nhũng và những vụ dàn xếp tỷ số bẩn thỉu thối nát ngày trước.",
        "Và cựu danh thủ số một quốc gia Trương Hùng Cường sẽ luôn đứng đó, kiên cường canh giữ sự trong sạch tuyệt đối của sân cỏ Việt Nam yêu quý.",
        "Hành trình vinh quang mới đầy hứa hẹn lại mở ra trước mắt anh và người đồng hành sắc sảo Lê Mai Chi vô cùng kiêu hãnh rực rỡ và vững chãi.",
        "Họ cùng bước đi bên nhau dưới vòm trời xanh bao la của thành phố Thành Tâm, lòng tràn ngập niềm tin sắt đá vững bền vào tương lai tươi sáng.",
        "Công lý được thực thi trọn vẹn và nghiêm minh nhất, trả lại vẻ đẹp đích thực và thiêng liêng vốn có cho môn thể thao vua kiêu hãnh nước nhà.",
        "Mọi âm mưu thối nát đều đã phải đền tội thích đáng trước sức mạnh vô song của luật pháp quốc gia và tinh thần thượng võ thể thao cao cả nhất.",
        "Và tiếng còi công tâm của Trương Hùng Cường sẽ mãi là ngọn hải đăng rực sáng soi đường cho sự phát triển vững bền của bóng đá chuyên nghiệp Việt.",
        "Sự kiên định và bản lĩnh thép của anh đã chứng minh hùng hồn rằng công lý chân chính không bao giờ chịu cúi đầu trước sức mạnh đồng tiền bẩn.",
        "Nữ chính Lê Mai Chi mỉm cười vô cùng mãn nguyện kiêu hãnh, cô gái sắc sảo ấy đã hoàn toàn đạt được mọi mục tiêu cải tổ đề ra ban đầu.",
        "Ủy ban Tư pháp Độc lập do cô đứng đầu sẽ luôn là lá chắn thép vững chắc nhất bảo vệ cho mọi trọng tài trung thực và dũng cảm trên sân cỏ.",
        "Kể từ nay về sau, những tiếng còi méo mó vì đồng tiền dơ bẩn của các ông bầu tư nhân sẽ vĩnh viễn biến mất khỏi bản đồ bóng đá nước nhà.",
        "Người hâm mộ bóng đá Việt Nam từ nay đã có thể tự tin ngẩng cao đầu tự hào giới thiệu nền bóng đá sạch với bạn bè quốc tế năm châu.",
        "Cường khẽ gật đầu mỉm cười chào những người hâm mộ đang vẫy tay chào đón anh nồng nhiệt dọc hai bên đường phố Thành Tâm rực rỡ cờ hoa chiến thắng.",
        "Anh biết rõ con đường phía trước còn nhiều chông gai thử thách, nhưng ngọn lửa niềm tin của người hâm mộ đã được thắp sáng rực rỡ trở lại từ hôm nay.",
        "Mỗi trận đấu bóng đá từ nay về sau sẽ thực sự là một ngày hội lớn của những trái tim yêu bóng đá chân chính, cống hiến hết mình vì màu cờ sắc áo.",
        "Tấm băng đội trưởng màu đỏ tươi trên bắp tay săn chắc của anh như một lời thề sắt son thiêng liêng bảo vệ lẽ phải và công lý sân cỏ đến cùng.",
        "Lê Mai Chi khẽ bước lên chiếc xe công vụ sang trọng của ủy ban, vẫy tay chào Cường với một nụ cười đầy quyến rũ kiêu hãnh rạng ngời dưới ánh nắng.",
        "Hẹn gặp lại anh Trương Hùng Cường ở trận đấu bắt chính tiếp theo của mùa giải mới đầy hứa hẹn rực rỡ đang chờ đón chúng ta phía trước nhé.",
        "Cường khẽ mỉm cười gật đầu chào từ biệt cô, bóng dáng săn chắc của anh nhanh chóng hòa vào dòng người đông đúc náo nhiệt của thành phố Thành Tâm hoa lệ.",
        "Tiếng còi thép công tâm của anh từ nay sẽ luôn là nỗi khiếp sợ kinh hoàng nhất của những kẻ tham lam lộng quyền và muốn dàn xếp tỷ số bẩn thỉu.",
        "Và đồng thời cũng chính là chỗ dựa tinh thần vững chắc nhất cho những ước mơ sân cỏ của thế hệ trẻ bay cao bay xa mãi trên bầu trời vinh quang.",
        "Một cái kết vô cùng trọn vẹn và mỹ mãn cho câu chuyện vả mặt sòng phẳng đầy kịch tính chấn động cả giới thể thao và truyền thông nước nhà."
    ]

    # Process all chapters with the smart trim function!
    ch1_trimmed = trim_to_range(ch1_sentences, "Chương 1")
    ch2_trimmed = trim_to_range(ch2_sentences, "Chương 2")
    ch3_trimmed = trim_to_range(ch3_sentences, "Chương 3")
    ch4_trimmed = trim_to_range(ch4_sentences, "Chương 4")
    ch5_trimmed = trim_to_range(ch5_sentences, "Chương 5")

    def process_content(sentences):
        paragraphs = []
        for s in sentences:
            s_clean = s.strip()
            if s_clean:
                paragraphs.append(f"<p>{s_clean}</p>\n")
        return "".join(paragraphs)

    payload = {
        "title": "Trọng Tài Bóng Đá Bị Cầu Thủ Ngôi Sao Xúc Phạm, Hóa Ra Là Cựu Danh Thủ Số 1 Quốc Gia",
        "subtitle": "Bản Lĩnh Sân Cỏ",
        "author": "Đông Hải Cư Sĩ",
        "genre": "Sảng Văn",
        "intro": "<p><strong>\"Trương Hùng Cường, loại trọng tài cỏ ăn lương ba cọc ba đồng như mày, lấy tư cách gì mà đòi phạt thẻ tao?\"</strong></p>\n<p>Giữa chảo lửa Sân vận động Thành Tâm, gã cầu thủ ngôi sao Nguyễn Gia Bảo nhổ nước bọt xuống mặt cỏ, chỉ tay thẳng vào mặt vị trọng tài chính với vẻ mặt kiêu ngạo tột độ.</p>\n<p>Hắn cậy thế lực chống lưng khổng lồ của Tập đoàn Hoàng Nam và đường dây dàn xếp tỷ số ngầm của Hoàng \"Chợ Lớn\" để thao túng cả giải đấu, chà đạp lên mọi luật lệ bóng đá.</p>\n<p>Hắn không hề biết rằng, người đàn ông 38 tuổi mặc sắc phục đen đang lạnh lùng rút tấm thẻ đỏ trực tiếp kia chính là cựu đội trưởng huyền thoại của Đội tuyển Quốc gia - người từng mang áo số 10 huyền thoại dẫn dắt bóng đá Việt Nam lên đỉnh cao Đông Nam Á.</p>\n<p>Bắt tay cùng nữ Phó Trưởng ban kiểm soát giải đấu Lê Mai Chi - người phụ nữ sắc sảo, kiêu hãnh và sòng phẳng tuyệt đối, Trương Hùng Cường từng bước bóc trần đường dây tham nhũng nghìn tỷ của giới quản lý câu lạc bộ địa phương.</p>\n<p>Khi tấm thẻ đỏ tối cao được giơ lên, tiếng còi công lý vang vọng, cả nền bóng đá nước nhà chấn động, ép kẻ tội đồ phải quỳ gối chịu tội trước công lý sân cỏ.</p>",
        "cover_prompt": "A high-end book cover, highly detailed web novel illustration style, a fit and intense Vietnamese man in his late 30s in a professional black referee uniform, standing confidently in a massive glowing football stadium filled with cheering crowds under night floodlights. Cinematic lens flare, rich dramatic shadows, premium colors.",
        "chapters": [
            {
                "title": "Chương 1: Tiếng Còi Bị Thách Thức",
                "content": process_content(ch1_trimmed)
            },
            {
                "title": "Chương 2: Thế Lực Hắc Ám Lộ Diện",
                "content": process_content(ch2_trimmed)
            },
            {
                "title": "Chương 3: Quá Khứ Huy Hoàng Và Đồng Minh Sắc Sảo",
                "content": process_content(ch3_trimmed)
            },
            {
                "title": "Chương 4: Cuộc Chiến Trên Bàn Đàm Phán",
                "content": process_content(ch4_trimmed)
            },
            {
                "title": "Chương 5: Trả Lại Sự Trong Sạch Cho Sân Cỏ",
                "content": process_content(ch5_trimmed)
            }
        ]
    }
    
    output_path = "/Users/aaronnguyen/TN/App/doctieuthuyet/scratch/draft_novel_23.json"
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    print(f"Successfully generated draft_novel_23.json at {output_path}!")

if __name__ == '__main__':
    build_draft_23()
