import json
import os

def count_words(text):
    # Strip HTML tags first to count actual words
    import re
    clean_text = re.sub(r'<[^>]+>', ' ', text)
    words = clean_text.split()
    return len(words)

def main():
    novel = {
        "title": "Độc Bản Dược Thần: Kẻ Lật Kèo Thế Kỷ",
        "author": "Nam Phái Gia Cát",
        "genre": "Sảng Văn",
        "intro": (
            "<p><strong>\"Năm năm trước, hắn giật lấy công trình nghiên cứu của tôi, bảo vệ ném hành lý của tôi ra đường đèo Đà Lạt dưới cơn mưa tuyết lạnh giá. Hắn đứng trên hiên cao, gõ tì tay lên lan can và mỉa mai: 'Mày chỉ là một thằng nghiên cứu quèn rách rưới, không có Khang Thị nâng đỡ thì mày chẳng là cái gì cả!'\"</strong></p>"
            "<p><strong>\"Nhưng hắn không ngờ, công thức thuốc gan 'Khóa Phân Tử' mà hắn cướp đi chỉ là bản lỗi. Không có enzyme xúc tác từ sâm Ngọc Linh được chiết xuất bằng quy trình chưng cất áp suất thấp độc quyền của tôi, thuốc gan ấy sẽ biến thành độc dược cực mạnh khi sản xuất quy mô lớn ở nhiệt độ cao!\"</strong></p>"
            "<hr />"
            "<p>Trần Huy Hoàng là một thiên tài dược lý ẩn dật, người đã dành cả thanh xuân để nghiên cứu ra liệu pháp điều trị xơ gan đột phá bằng cách khóa phân tử tế bào tổn thương. Sau khi bị kẻ thù Đường Vĩnh Khang cướp công thức và đuổi đi trong nhục nhã, anh được sự hậu thuẫn của Trần Tuệ Lâm – ái nữ sắc sảo của siêu quỹ đầu tư Thái Bình Capital. Hai người hợp tác thành lập Đại Đông Dược, bắt đầu một cuộc chiến tài chính, pháp lý và công nghệ nghẹt thở chống lại tập đoàn Khang Thị ngay trước thềm thương vụ IPO lịch sử trên sàn HoSE. Những màn lật kèo pháp lý sắc bén, những cuộc đấu trí y học thực tế và cú vả mặt kinh điển đang chờ đón bạn!</p>"
        ),
        "cover_prompt": "masterpiece, highly detailed book cover, anime illustration style, a handsome Vietnamese young scientist with glasses in a modern high-tech green herbal laboratory, alongside a beautiful sharp-eyed businesswoman in a business suit, vivid lighting, warm background sunset over mountains",
        "chapters": []
    }

    # Chapter 1
    chap1_title = "Chương 1: Đêm Tuyết Đà Lạt Và Nhát Dao Từ Sau Lưng"
    chap1_content = (
        "<p>Gió hú qua những rặng thông già quanh biệt thự Pháp cổ đầu đèo Prenn, mang theo cái lạnh buốt xương của đêm mùa đông Đà Lạt. Lúc này đã là tám giờ tối, sương mù dày đặc tràn vào qua khe cửa sổ gỗ đã mục ruỗng của Viện Nghiên cứu Dược phẩm Khang Thị chi nhánh Tây Nguyên. Trong phòng thí nghiệm trung tâm, ánh đèn huỳnh quang mắt mèo tỏa ra thứ ánh sáng trắng nhợt nhạt, soi rõ bóng lưng gầy guộc nhưng thẳng tắp của Trần Huy Hoàng. Anh đang chăm chú nhìn vào ống nghiệm thủy tinh trên tay, nơi chất lỏng màu xanh lục nhạt đang sủi những bong bóng li ti dưới ngọn lửa đèn cồn. Đôi mắt anh hằn lên những tia máu đỏ quạch vì năm ngày liên tục không ngủ, nhưng nụ cười trên môi lại rạng rỡ hơn bao giờ hết.</p>"
        "<p>\"Thành công rồi... Khóa phân tử đã hoạt động ổn định. Tế bào xơ hóa đã bị bao vây hoàn toàn!\" Huy Hoàng lẩm bẩm, giọng nói khản đặc vì thiếu nước nhưng tràn đầy sự phấn khích. Năm năm qua, anh sống như một kẻ lập dị, ăn mì tôm qua ngày, ngủ ngay trên chiếc ghế xếp rách nát để hoàn thiện công trình \"Đại Can Linh\" – bài thuốc đột phá giúp đảo ngược quá trình xơ gan bằng công nghệ hướng mục tiêu phân tử phối hợp thảo dược Việt Nam.</p>"
        "<p>Rầm! Cánh cửa gỗ nặng nề bị đẩy mạnh ra, đập vào tường nghe một tiếng chói tai. Huy Hoàng giật mình quay lại. Đường Vĩnh Khang – Tổng giám đốc Tập đoàn Dược phẩm Khang Thị – bước vào với chiếc áo khoác lông cừu sang trọng, theo sau là Hoàng Thế Dũng, trợ lý đắc lực kiêm em họ của hắn. Khuôn mặt Khang lộ rõ vẻ đắc ý, trong khi Dũng cầm trên tay một xấp tài liệu dày cộp cùng một chiếc USB màu đỏ.</p>"
        "<p>\"Huy Hoàng, cậu vất vả rồi. Từ ngày mai, cậu không cần đến viện nghiên cứu nữa.\" Đường Vĩnh Khang thản nhiên nói, giọng nói lạnh lùng như băng giá ngoài kia. Hắn rút từ trong túi áo ra một tờ quyết định đóng dấu đỏ chót của tập đoàn và ném thẳng xuống bàn thí nghiệm đầy hóa chất.</p>"
        "<p>Huy Hoàng sững sờ, các ngón tay siết chặt lấy ống nghiệm đến mức khớp xương kêu răng rắc. \"Giám đốc Đường, ý ông là sao? Đề tài 'Khóa Phân Tử' này đang ở giai đoạn thử nghiệm lâm sàng cuối cùng. Tôi là người duy nhất nắm giữ tiến trình này!\"</p>"
        "<p>Hoàng Thế Dũng bước lên, cười khẩy một tiếng đầy khinh bỉ. Hắn giơ chiếc USB màu đỏ lên trước mặt Huy Hoàng. \"Anh Hoàng ơi anh Hoàng, anh ngây thơ thật hay giả vờ thế? Toàn bộ cơ sở dữ liệu nghiên cứu, công thức hóa học, log thí nghiệm và cả bản quyền sáng chế mang tên Khang Thị đã được tôi sao chép sạch sẽ vào đây rồi. Hợp đồng lao động của anh đã hết hạn từ tuần trước, và hội đồng quản trị quyết định không gia hạn. Nói cách khác, anh đã bị sa thải!\"</p>"
        "<p>Huy Hoàng cảm thấy lồng ngực mình nghẹn lại, một luồng khí lạnh chạy dọc sống lưng. \"Hoàng Thế Dũng! Cậu là học trò của tôi, chính tôi đã cầm tay chỉ việc cho cậu! Công thức đó là mồ hôi nước mắt của tôi suốt năm năm! Các người không thể cướp trắng trợn như vậy!\"</p>"
        "<p>Anh lao về phía chiếc bàn để giật lại ổ cứng lưu trữ gốc, nhưng Hoàng Thế Dũng đã nhanh tay hơn, gạt mạnh tay anh ra. Cú gạt mạnh khiến chiếc bình thủy tinh đựng dung dịch trung hòa rơi xuống đất, vỡ tan tành thành trăm mảnh sắc nhọn. Huy Hoàng mất đà ngã nhào, lòng bàn tay phải của anh đập mạnh vào những mảnh thủy tinh vỡ. Cảm giác đau đớn nhói buốt ập đến lập tức. Máu tươi đỏ thẫm trào ra, chảy ròng ròng qua các kẽ ngón tay, nhuộm đỏ cả vạt áo blouse trắng và những tờ giấy nháp nghiên cứu trên sàn nhà.</p>"
        "<p>Đường Vĩnh Khang nhìn vũng máu trên sàn bằng ánh mắt vô cảm, rồi ra hiệu cho hai gã bảo vệ to khỏe đang đứng chờ ngoài cửa. \"Kéo nó ra ngoài. Kể từ giây phút này, Trần Huy Hoàng không còn liên quan đến Khang Thị. Nếu nó dám bén mảng đến đây hoặc rò rỉ bất kỳ thông tin nào, bộ phận pháp lý của chúng ta sẽ kiện nó đến mức khuynh gia bại sản!\"</p>"
        "<p>Hai gã bảo vệ bước vào, thô bạo túm lấy hai vai Huy Hoàng, kéo lê anh dọc theo hành lang lát đá lạnh lẽo. Lòng bàn tay phải của anh vẫn không ngừng chảy máu, để lại những vệt đỏ dài ghê rợn trên nền đất. Họ ném anh ra ngoài cổng sắt lớn của viện nghiên cứu. Huy Hoàng ngã quỵ xuống thảm lá thông mục ướt sũng sương đêm. Cánh cổng sắt lạnh lùng đóng sập lại, khóa xích kêu loảng xoảng.</p>"
        "<p>Mưa phùn bắt đầu rơi, lẫn lộn với những hạt sương muối buốt giá tạt thẳng vào mặt Huy Hoàng. Anh ngồi im trong bóng tối, bàn tay trái nắm chặt lấy cổ tay phải để ngăn máu chảy. Cơn đau thể xác không thấm tháp gì so với ngọn lửa phẫn nộ đang bùng cháy trong lồng ngực. Nhưng kỳ lạ thay, sau vài phút im lặng, Huy Hoàng không hề gào thét hay khóc lóc. Anh từ từ ngẩng đầu lên nhìn tòa biệt thự Pháp cổ đang sáng đèn rực rỡ, rồi bật ra những tiếng cười nhỏ lạnh lẽo.</p>"
        "<p>\"Đường Vĩnh Khang, Hoàng Thế Dũng... Các người tưởng rằng cướp được cái USB đó là cướp được tất cả sao?\" Huy Hoàng thì thầm, giọng nói thì thầm bị tiếng gió ngàn thông nuốt chửng. Hắn biết rất rõ một bí mật mà không một ai trong Khang Thị biết được. Công thức mà Hoàng Thế Dũng vừa sao chép chỉ là bản phác thảo cũ cách đây hai năm. Công thức đó có một lỗi chí mạng liên quan đến \"Khóa Phân Tử\". Khi sản xuất ở quy mô phòng thí nghiệm nhỏ với nhiệt độ phòng, các phân tử liên kết rất hoàn hảo. Nhưng nếu đưa vào dây chuyền sản xuất công nghiệp hàng loạt dưới áp suất lớn và nhiệt độ cao vượt quá 85 độ C của Khang Thị nhằm chuẩn bị sản phẩm cho đợt IPO sắp tới trên sàn HoSE, cấu trúc phân tử của thuốc sẽ bị bẻ gãy hoàn toàn. Không có loại enzyme xúc tác tự nhiên được chiết xuất từ sâm Ngọc Linh phối hợp theo tỉ lệ vàng chưng cất chân không áp suất thấp mà anh giữ kín trong đầu, thuốc trị gan \"Khang Can Linh\" của họ sẽ biến đổi thành một chất đồng phân độc hại cực mạnh, gây hoại tử tế bào gan diện rộng chỉ sau vài ngày sử dụng.</p>"
        "<p>Khang Thị Pharma đang vội vã nộp hồ sơ IPO lên Sở Giao dịch Chứng khoán TP.HCM (HoSE) để nâng định giá công ty lên hàng ngàn tỷ đồng. Họ đã tự tay châm ngòi cho quả bom hẹn giờ khủng khiếp nhất lịch sử ngành dược phẩm Việt Nam, và ngòi nổ đang nằm gọn trong bàn tay đang rỉ máu của Trần Huy Hoàng.</p>"
    )

    # Chapter 2
    chap2_title = "Chương 2: Buổi Thẩm Định Trong Sương Mù Và Ca Cấp Cứu Chợ Rẫy"
    chap2_content = (
        "<p>Ba ngày sau đêm bị đuổi khỏi viện nghiên cứu, Trần Huy Hoàng sống ẩn dật trong một căn nhà gỗ nhỏ tuềnh toàng nằm sâu dưới thung lũng tình yêu Đà Lạt. Lòng bàn tay phải của anh đã được băng bó sơ sài bằng một lớp gạc y tế giá rẻ mua ở hiệu thuốc đầu đèo. Căn phòng ngập tràn mùi thảo dược khô, những bình gốm chưng cất thủ công và sách vở nghiên cứu chất đống. Huy Hoàng đang ngồi sắc một ấm thuốc bắc bằng bếp than củi thì tiếng động cơ gầm rú phá vỡ sự tĩnh lặng của thung lũng hoang vu. Một chiếc Mercedes-Benz S450 màu đen bóng loáng, gầm thấp, đang từ từ bò qua con đường mòn đầy bùn đất đỏ sũng nước sau cơn mưa, dừng lại ngay trước sân nhà anh.</p>"
        "<p>Cửa xe mở ra, một đôi giày cao gót màu đen tuyền bước xuống, dẫm lên nền đất sình lầy mà không hề lưỡng lự. Đó là Trần Tuệ Lâm – Tổng giám đốc của Quỹ đầu tư Thái Bình Capital, một trong những siêu quỹ thác có tầm ảnh hưởng lớn nhất khu vực phía Nam. Cô mặc một chiếc áo măng tô màu kem thanh lịch, mái tóc đen dài được búi cao gọn gàng, để lộ gương mặt thanh tú nhưng toát lên vẻ sắc sảo, lạnh lùng của một nhà tài phiệt thực thụ. Đi sau cô là hai trợ lý mặc vest đen lịch lãm và một vệ sĩ cao lớn.</p>"
        "<p>Tuệ Lâm bước vào căn nhà gỗ, đôi mắt phượng quét nhanh qua không gian bừa bộn rồi dừng lại trên gương mặt điềm tĩnh của Huy Hoàng. Cô không vòng vo mà đi thẳng vào vấn đề: \"Trần Huy Hoàng, cựu trưởng nhóm nghiên cứu cốt lõi của Khang Thị Pharma. Tôi biết anh vừa bị sa thải ba ngày trước. Tôi cũng biết công thức 'Khóa Phân Tử' thực chất là do một tay anh phát triển, không phải của Đường Vĩnh Khang hay Hoàng Thế Dũng.\"</p>"
        "<p>Huy Hoàng không đứng dậy, anh nhẹ nhàng rót chén trà thảo dược nóng bốc khói nghi ngút ra chiếc cốc sứ sứt quai, đẩy về phía cô. \"Trần tiểu thư tìm đến tận nơi này, chắc không phải chỉ để chia buồn với một kẻ thất nghiệp chứ?\"</p>"
        "<p>Tuệ Lâm đón lấy chén trà, nhưng cô không uống mà đặt xuống mặt bàn gỗ thô ráp. \"Thái Bình Capital đang muốn rót vốn vào ngành dược phẩm độc bản. Tôi đã theo dõi đề tài của anh từ lâu. Tuy nhiên, tôi là một nhà đầu tư lý tính. Tôi không rót tiền chỉ vì sự thương hại hay lời hứa suông. Tôi cần chứng minh năng lực thực tế của anh ngay lập tức. Nếu anh đồng ý, hãy đi cùng tôi xuống Sài Gòn ngay bây giờ. Ông nội tôi đang nằm viện.\"</p>"
        "<p>Nghe đến đây, Huy Hoàng khẽ nhíu mày. Ông nội của Trần Tuệ Lâm chính là Trần Thế Xương – cựu ngoại giao cao cấp, người có tầm ảnh hưởng cực lớn trong giới chính trị và kinh doanh Việt Nam. Chuyến đi diễn ra trong sự im lặng tuyệt đối. Chiếc xe lao vun vút từ cao nguyên Lang Biang xuống Sài Gòn, dừng bánh trước cổng Bệnh viện Chợ Rẫy tại Quận 5 vào lúc nửa đêm.</p>"
        "<p>Khi họ bước vào phòng hồi sức tích cực (ICU) dành cho VIP, bầu không khí ở đây vô cùng căng thẳng. Máy thở kêu tít tít dồn dập, các màn hình chỉ số sinh tồn liên tục nhấp nháy đèn đỏ báo động. Ông cụ Trần Thế Xương đang nằm trên giường bệnh, da mặt vàng như nghệ do bilirubin tích tụ, hơi thở đứt quãng và đã rơi vào trạng thái hôn mê sâu. Đứng xung quanh giường là các bác sĩ đầu ngành, dẫn đầu bởi Tiến sĩ, Bác sĩ Nguyễn Văn Hải – Trưởng khoa Hồi sức tích cực của Chợ Rẫy. Sắc mặt ai nấy đều xám xịt.</p>"
        "<p>\"Chỉ số men gan ALT và AST của cụ đã vượt quá 2600 U/L, gấp hơn 50 lần mức bình thường. Gan đã bị suy hủy diện rộng do độc tính của loại thuốc thử nghiệm nước ngoài mà cụ dùng trước đó. Lọc máu liên tục (CRRT) và thay huyết tương (PE) ba lần vẫn không ngăn được đà hoại tử tế bào. Chúng tôi e rằng... cụ khó qua khỏi đêm nay,\" bác sĩ Hải lắc đầu, giọng nói đầy bất lực.</p>"
        "<p>Tuệ Lâm siết chặt nắm tay, mồ hôi lạnh rịn ra trên trán nhưng cô vẫn cố giữ giọng điệu bình tĩnh: \"Trần Huy Hoàng, đến lượt anh rồi. Hãy chứng minh cho tôi thấy công nghệ khóa phân tử của anh không phải là bánh vẽ trên giấy.\"</p>"
        "<p>Bác sĩ Hải lập tức quay lại, nhìn Huy Hoàng bằng ánh mắt đầy hoài nghi và giận dữ khi thấy một thanh niên mặc đồ giản dị, tay quấn băng gạc bước vào. \"Trần tiểu thư, đây là phòng ICU vô trùng! Cụ Trần đang ở ranh giới sinh tử, cô không thể để một kẻ không rõ lai lịch can thiệp bằng những phương pháp phản khoa học được!\"</p>"
        "<p>Huy Hoàng không thèm để ý đến lời nói của bác sĩ Hải. Anh tiến sát lại giường bệnh, nhẹ nhàng lật mí mắt của cụ Trần, áp ngón tay trỏ và ngón giữa lên mạch cổ tay của cụ để bắt mạch. Mạch tượng cực kỳ hỗn loạn, như sợi chỉ sắp đứt, can hỏa bùng phát dữ dội. Anh thở dài nhẹ: \"Máy móc Tây y rất hiện đại, nhưng nó chỉ lọc được các độc tố tự do trong dòng tuần hoàn mạch máu. Độc tố tích tụ ở đây đã tạo thành một liên kết cộng hóa trị chặt chẽ với các thụ thể trên màng tế bào gan, liên tục kích hoạt chuỗi phản ứng tự hủy. Lọc máu vô ích.\"</p>"
        "<p>Nói rồi, Huy Hoàng mở chiếc túi da nhỏ đeo bên hông, rút ra ba cây kim bạc dài mảnh lấp lánh dưới ánh đèn phòng bệnh. Bàn tay trái của anh di chuyển cực nhanh, đâm chuẩn xác vào ba huyệt vị chủ chốt: Kỳ Môn, Chương Môn và Thái Xung. Ngón tay anh khẽ búng nhẹ vào đuôi kim, khiến thân kim bạc rung lên tạo ra những âm thanh vo ve siêu nhỏ mà mắt thường khó thấy.</p>"
        "<p>\"Anh làm cái gì thế! Dừng lại ngay!\" Bác sĩ Hải định lao lên ngăn cản, nhưng vệ sĩ của Tuệ Lâm đã bước lên một bước, chặn đứng ông ta lại bằng một ánh mắt cảnh cáo lạnh lùng.</p>"
        "<p>\"Yên tâm, đây chỉ là phương pháp đả thông kinh lạc, thông can khí để giữ mạng tạm thời trong vòng ba giờ,\" Huy Hoàng bình thản nói khi rút kim ra. Trên đầu các cây kim bạc bám một vệt dịch màu đen xám xịt, bốc lên mùi hôi nhẹ. Tiếp đó, anh rút từ trong túi ra một lọ dung dịch nhỏ màu hổ phách – đây là mẫu thử duy nhất của bài thuốc Đại Can Linh chưng cất áp suất thấp mà anh kịp mang đi từ viện nghiên cứu trước khi bị đuổi. Anh hòa dung dịch vào một ít nước cất vô trùng rồi ra hiệu cho y tá bơm trực tiếp qua ống thông dạ dày của cụ Trần.</p>"
        "<p>\"Bác sĩ Hải, hãy cho chạy xét nghiệm máu lại sau đúng ba giờ nữa. Kết quả lâm sàng từ các máy móc hiện đại nhất của các ông sẽ là câu trả lời khách quan nhất cho tài năng của tôi,\" Huy Hoàng quay sang nhìn Tuệ Lâm, đôi mắt anh sáng lên sự tự tin tuyệt đối dưới ánh đèn bệnh viện.</p>"
    )

    # Chapter 3
    chap3_title = "Chương 3: Bản Hợp Đồng Trăm Tỷ Và Thế Trận Đại Đông Dược"
    chap3_content = (
        "<p>Đúng ba giờ sáng, không khí bên ngoài phòng ICU của Bệnh viện Chợ Rẫy lạnh lẽo và yên tĩnh lạ thường. Trần Tuệ Lâm đứng tựa lưng vào bức tường kính, đôi mắt phượng không rời khỏi cánh cửa phòng xét nghiệm trung tâm. Trong khi đó, Trần Huy Hoàng vẫn ngồi thản nhiên trên hàng ghế chờ bằng inox, lật xem một cuốn tạp chí y học cũ như thể sự sống chết của siêu tỷ phú Trần Thế Xương không hề liên quan đến anh.</p>"
        "<p>Cạch! Cánh cửa phòng xét nghiệm bật mở. Một nữ bác sĩ trẻ chạy ra, gương mặt tái nhợt vì xúc động, trên tay cầm tờ phiếu kết quả xét nghiệm còn nóng hổi từ máy in. Cô chạy thẳng đến trước mặt Trưởng khoa Nguyễn Văn Hải, lắp bắp không thành tiếng: \"Trưởng khoa... Trưởng khoa xem này! Thật không thể tin nổi!\"</p>"
        "<p>Bác sĩ Hải giật phắt tờ giấy, đeo kính lão lên đọc. Đôi mắt ông ta trợn trừng, hai tay run lên bần bật đến mức tờ giấy phẳng phiu bị vò nát một góc. \"Cái gì? Chỉ số ALT giảm từ 2600 xuống còn 750 U/L? Chỉ số bilirubin toàn phần từ 350 đột ngột đi ngang và có xu hướng giảm sâu xuống 210? Lượng nước tiểu đạt 800ml chỉ trong ba giờ? Các chỉ số suy thận cấp cũng đang đảo chiều tự phục hồi? Có nhầm lẫn gì ở phòng Lab không?!\"</p>"
        "<p>\"Chúng em đã chạy máy kiểm tra ba lần trên hai hệ thống máy Cobas khác nhau rồi ạ! Kết quả hoàn toàn chính xác! Cụ Trần Thế Xương đã thoát khỏi trạng thái hôn mê sâu, huyết áp ổn định ở mức 120/80 mmHg và cụ vừa mới mở mắt tỉnh lại!\" Nữ bác sĩ y tá reo lên đầy phấn khích.</p>"
        "<p>Bác sĩ Hải đờ người ra, tờ phiếu xét nghiệm rơi khỏi tay, bay nhè nhẹ xuống sàn nhà lát gạch men trắng. Ông ta quay đầu lại nhìn Huy Hoàng bằng ánh mắt như nhìn thấy một vị thần y bước ra từ truyền thuyết cổ đại. Sự kiêu ngạo của một Tiến sĩ y học Tây y tu nghiệp tại Pháp hoàn toàn đổ vỡ trước kết quả lâm sàng chuẩn xác không thể chối cãi được in bằng máy móc hiện đại.</p>"
        "<p>Trần Tuệ Lâm lập tức bước đến bên giường bệnh của ông nội. Nhìn thấy cụ Trần Thế Xương đã có thể khẽ gật đầu nhận ra cháu gái, giọt nước mắt hiếm hoi lăn dài trên gò má thanh tú của cô rồi nhanh chóng được cô lau đi. Cô quay lại nhìn Huy Hoàng, giọng nói mang theo một sự tôn kính và quyết đoán rõ rệt: \"Trần Huy Hoàng, anh đã chứng minh được giá trị sáng chế của mình. Sáng mai, mười giờ, hãy đến văn phòng của tôi tại Landmark 81. Chúng ta sẽ ký hợp đồng.\"</p>"
        "<p>Sáng hôm sau, tại tầng cao nhất của tòa tháp Landmark 81 (Quận Bình Thạnh), trong phòng làm việc ngập tràn ánh sáng với vách kính suốt ngắm toàn cảnh dòng sông Sài Gòn uốn lượn bên dưới. Trần Tuệ Lâm ngồi đối diện Huy Hoàng qua chiếc bàn gỗ sồi nhập khẩu từ Ý. Đội ngũ pháp lý gồm năm luật sư cao cấp của Thái Bình Capital đã túc trực sẵn xung quanh.</p>"
        "<p>\"Tôi đã cho đội ngũ chuyên gia pháp lý và sở hữu trí tuệ rà soát độc lập. Trước khi anh vào làm việc tại Khang Thị, anh đã nộp đơn đăng ký ba bằng sáng chế độc lập về quy trình chiết xuất hoạt chất hướng đích từ sâm Ngọc Linh phối hợp thảo dược dưới danh nghĩa cá nhân. Khang Thị chỉ cướp được phần cơ sở dữ liệu ứng dụng mà không hề có quyền sở hữu ba bằng sáng chế gốc này. Đây là điểm mấu chốt pháp lý giúp chúng ta nghiền nát họ,\" Tuệ Lâm phân tích sắc bén, đẩy tập hồ sơ dày cộp sang phía anh.</p>"
        "<p>Huy Hoàng khẽ mỉm cười, nhấp một ngụm cà phê đen không đường. \"Trần tiểu thư quả là danh bất hư truyền. Vậy còn 'Khóa Phân Tử' của Khang Thị thì sao?\"</p>"
        "<p>\"Tôi muốn nghe chính xác từ anh về lỗi chí mạng của họ,\" Tuệ Lâm chăm chú nhìn vào mắt anh.</p>"
        "<p>Huy Hoàng giải thích cặn kẽ: \"Để khóa được các phân tử xơ hóa gan mà không gây độc, hoạt chất bắt buộc phải có sự tham gia của một loại enzyme xúc tác tự nhiên được chiết xuất từ sâm Ngọc Linh Đà Lạt bằng quy trình chưng cất chân không áp suất thấp ở nhiệt độ không quá 45 độ C. Hoàng Thế Dũng chỉ cướp được công thức cấu tạo phân tử tĩnh. Khi Khang Thị Pharma đưa công thức này vào dây chuyền sản xuất công nghiệp quy mô lớn để chuẩn bị sản phẩm thương mại cho đợt IPO sắp tới trên sàn HoSE, họ bắt buộc phải dùng các lò phản ứng áp suất lớn với nhiệt độ vượt quá 85 độ C để đẩy nhanh sản lượng. Dưới nhiệt độ và áp suất đó, liên kết hóa học của hoạt chất sẽ bị biến tính hoàn toàn thành một dạng đồng phân quang học cực độc, gây hoại tử tế bào gan cấp tính. Nói cách khác, thuốc của họ không phải là thần dược cứu người, mà là một lọ độc dược được bọc trong vỏ bọc lấp lánh của thương vụ nghìn tỷ.\"</p>"
        "<p>Tuệ Lâm khẽ gõ nhẹ ngón tay thon dài lên mặt bàn gỗ sồi. Sự thông minh tuyệt đỉnh giúp cô nhìn thấy ngay một cơ hội vàng để thiết lập lại bản đồ ngành dược phẩm Việt Nam. Cô tuyên bố dứt khoát: \"Chúng ta sẽ thành lập Công ty Cổ phần Đại Đông Dược. Thái Bình Capital sẽ rót vốn đối ứng ban đầu trị giá 100 tỷ đồng, sở hữu 40% cổ phần. Anh sở hữu 60% cổ phần bằng giá trị trí tuệ, công thức độc bản và quyền sử dụng bằng sáng chế. Tôi sẽ lo liệu toàn bộ việc xây dựng xưởng sản xuất chuẩn GMP-WHO tại Khu công nghệ cao Quận 9 và hoàn tất các thủ tục cấp phép khẩn cấp của Bộ Y tế dựa trên hồ sơ lâm sàng của ông nội tôi. Anh đồng ý chứ?\"</p>"
        "<p>\"Rất sòng phẳng. Hợp tác vui vẻ,\" Huy Hoàng cầm bút ký tên dứt khoát lên bản hợp đồng hợp tác thế kỷ.</p>"
        "<p>Chỉ năm phút sau khi chữ ký được ký xuống, chiếc điện thoại thông minh của Huy Hoàng báo tin nhắn biến động số dư từ ứng dụng Vietcombank: 'Tài khoản công ty CP Đại Đông Dược nhận +100,000,000,000 VND từ Quy dau tu Thai Binh Capital. Noi dung chuyển khoản: Gop von dieu le sang lap'.</p>"
        "<p>Nhìn con số 11 chữ số dài dằng dặc hiển thị trên màn hình điện thoại dưới ánh nắng rực rỡ của tầng cao Landmark 81, Huy Hoàng khẽ chạm ngón tay vào vết sẹo mới kéo da non trong lòng bàn tay phải của mình. Kế hoạch lật kèo vĩ đại nhất lịch sử thương trường Việt Nam chính thức bắt đầu chuyển động bánh răng đầu tiên.</p>"
    )

    # Chapter 4
    chap4_title = "Chương 4: Trận Chiến Truyền Thông Bẩn Và Lệnh Đình Chỉ 24 Giờ"
    chap4_content = (
        "<p>Sau khi nhận được khoản vốn khủng 100 tỷ đồng từ Thái Bình Capital, Công ty Cổ phần Đại Đông Dược lập tức đi vào vận hành với tốc độ chóng mặt dưới sự điều hành quyết liệt của Trần Tuệ Lâm. Chỉ trong vòng chưa đầy một tháng, một xưởng bào chế thử nghiệm đạt chuẩn chất lượng quốc tế đã đi vào hoạt động tại Khu công nghệ cao Quận 9, phối hợp cùng hệ thống phòng khám y học cổ truyền cao cấp đặt tại trung tâm Quận 1. Tin tức Đại Đông Dược chuẩn bị ra mắt dòng sản phẩm điều trị gan cao cấp \"Đông Dược Độc Bản\" nhanh chóng lan truyền trong giới y học và đầu tư.</p>"
        "<p>Lúc này, tại văn phòng tổng công ty của Tập đoàn Dược phẩm Khang Thị ở Quận 1, Đường Vĩnh Khang đang như ngồi trên đống lửa. Hồ sơ IPO của Khang Thị Pharma (mã chứng khoán KTP) đã được phê duyệt và ngày niêm yết chính thức trên sàn chứng khoán TP.HCM (HoSE) đã được ấn định. Nếu để Đại Đông Dược ra mắt sản phẩm cạnh tranh trực tiếp và phanh phui sự thật về công thức gốc, bong bóng tài chính trị giá hàng ngàn tỷ đồng của Khang Thị sẽ nổ tung ngay lập tức.</p>"
        "<p>\"Thằng rác rưởi Trần Huy Hoàng đó lấy đâu ra gan lớn thế! Lại còn câu kết với Thái Bình Capital nữa!\" Đường Vĩnh Khang đập mạnh tay xuống bàn giám đốc, mặt đỏ gay sừng sộ. \"Thế Dũng! Cậu đã xử lý vụ truyền thông bẩn tôi giao chưa?\"</p>"
        "<p>Hoàng Thế Dũng đứng bên cạnh, nụ cười xảo quyệt hiện rõ trên khuôn mặt đầy mụn thịt. \"Giám đốc yên tâm đi ạ. Tôi đã chi ra mười lăm tỷ đồng để thuê công ty truyền thông bẩn hàng đầu Sài Gòn xử lý rồi. Bọn họ đã làm giả một bộ hồ sơ bệnh án của một cụ già tám mươi tuổi ở Quận 3, dựng chuyện cụ bị suy gan cấp tính và qua đời sau khi uống trà thảo dược giải độc của Đại Đông Dược. Các trang báo lá cải, hội nhóm mạng xã hội và hàng chục streamer biến chất đang đồng loạt lên bài. Lần này em bảo đảm Đại Đông Dược sẽ chết yểu từ trong trứng nước!\"</p>"
        "<p>Đúng như âm mưu của chúng, chỉ sau một đêm, khắp các trang mạng xã hội và trang tin điện tử tràn ngập các tiêu đề giật gân: \"Nghi vấn cụ già tử vong sau khi dùng sản phẩm của Đại Đông Dược?\", \"Thảm họa đông y độc bản: Thần y hay lang băm lừa đảo?\". Dưới sự dẫn dắt của các tài khoản ảo, làn sóng phẫn nộ của dư luận bùng phát dữ dội. Sáng hôm sau, hơn hai mươi phóng viên bẩn cùng hàng trăm streamer cầm điện thoại, thiết bị ghi hình vây kín cổng xưởng sản xuất của Đại Đông Dược tại Quận 9 và phòng khám ở Quận 1, la hét, quay phim tạo nên một cảnh tượng vô cùng hỗn loạn, gây mất an ninh trật tự nghiêm trọng.</p>"
        "<p>Trước áp lực khủng khiếp của dư luận xã hội và các cuộc gọi chất vấn liên tục từ các cơ quan quản lý, Sở Y tế TP.HCM đã phải ban hành một quyết định khẩn cấp: Tạm thời đình chỉ hoạt động xưởng sản xuất và phòng khám của Đại Đông Dược trong vòng 24 giờ để tiến hành thanh tra liên ngành toàn diện.</p>"
        "<p>Tại phòng họp nội bộ của Đại Đông Dược ở trung tâm Quận 1, bầu không khí căng thẳng bao trùm. Các nhân viên cấp dưới mặt mày tái mét, lo sợ công ty sẽ bị phá sản trước khi kịp ra mắt sản phẩm thương mại. Trái ngược hoàn toàn với sự hoảng loạn đó, Trần Huy Hoàng và Trần Tuệ Lâm vẫn ngồi uống trà vô cùng bình thản tại bàn họp.</p>"
        "<p>\"Tuệ Lâm, em đã tìm ra nguồn gốc của bệnh án giả chưa?\" Huy Hoàng đặt chén trà xuống, giọng điệu nhẹ nhàng.</p>"
        "<p>Tuệ Lâm lật chiếc máy tính bảng iPad Pro lên, ngón tay lướt nhanh trên màn hình hiển thị sơ đồ phân tích mạng lưới truyền thông. Cô mỉm cười sắc sảo: \"Đội ngũ an ninh mạng và pháp lý của Thái Bình Capital đã lần ra địa chỉ IP phát tán bài viết đầu tiên. Nó xuất phát từ một máy chủ ảo do công ty truyền thông bẩn của Đường Vĩnh Khang tài trợ. Về cụ già tử vong ở Quận 3, chúng tôi đã có được hồ sơ bệnh án gốc từ Bệnh viện Ung bướu TP.HCM. Cụ bị ung thư phổi giai đoạn cuối di căn xương, đã qua đời tại nhà riêng và chưa từng sử dụng bất kỳ sản phẩm nào của Đại Đông Dược. Con trai của cụ cũng đã ký vào đơn cam kết xác nhận sự thật và sẵn sàng đứng ra đối chất trước cơ quan điều tra.\"</p>"
        "<p>\"Tuyệt vời. Còn về phía Sở Y tế, anh đã chuẩn bị đầy đủ chứng cứ kỹ thuật rồi,\" Huy Hoàng đứng dậy, chỉnh lại cổ áo sơ mi.</p>"
        "<p>Đúng mười giờ sáng, đoàn thanh tra liên ngành của Sở Y tế phối hợp cùng lực lượng Cảnh sát Kinh tế bước vào phòng khám Đại Đông Dược. Huy Hoàng chủ động đón tiếp họ với thái độ hợp tác và chuyên nghiệp nhất. Anh trình ra toàn bộ nhật ký thí nghiệm chi tiết được lưu trữ trên nền tảng đám mây có chữ ký số bảo mật của chính phủ, báo cáo kết quả thử nghiệm lâm sàng chuẩn xác có đóng dấu đỏ của Bệnh viện Chợ Rẫy, và đặc biệt là chứng nhận đạt chuẩn ISO-9001 cùng tiêu chuẩn thực hành sản xuất tốt GMP-WHO của xưởng sản xuất.</p>"
        "<p>Quy trình kiểm tra kỹ lưỡng kéo dài suốt mười tám giờ liên tục. Đến ba giờ sáng ngày hôm sau, Trưởng đoàn thanh tra chính thức ký vào biên bản kết luận thanh tra: \"Không phát hiện bất kỳ sai phạm nào trong quy trình bào chế, sản xuất và khám chữa bệnh của Đại Đông Dược. Sản phẩm an toàn tuyệt đối và đạt mọi tiêu chuẩn y tế khắt khe nhất của Việt Nam.\"</p>"
        "<p>Đồng thời, lực lượng Cảnh sát Phòng chống tội phạm công nghệ cao cũng lập tức thực hiện lệnh bắt giữ khẩn cấp đối với giám đốc công ty truyền thông bẩn và ba phóng viên biến chất vì hành vi vu khống, bôi nhọ danh dự doanh nghiệp. Cuộc họp báo khẩn cấp được Đại Đông Dược tổ chức vào lúc tám giờ sáng hôm sau đã phơi bày toàn bộ sự thật trước công chúng, đập tan âm mưu bẩn thỉu của Khang Thị Pharma và biến cuộc khủng hoảng truyền thông thành một chiến dịch quảng bá miễn phí cực kỳ thành công cho Đại Đông Dược.</p>"
    )

    # Chapter 5
    chap5_title = "Chương 5: Ngày IPO HoSE Và Cú Sập Nguồn Của Khang Can Linh"
    chap5_content = (
        "<p>Ngày hai mươi tháng năm năm hai ngàn không trăm hai mươi sáu – một mốc thời gian lịch sử đối với ngành dược phẩm và toàn bộ thị trường tài chính Việt Nam. Sảnh giao dịch lớn của Sở Giao dịch Chứng khoán TP.HCM (HoSE) tọa lạc trên con đường Võ Văn Kiệt sầm uất tại Quận 1 được trang hoàng lộng lẫy chưa từng có. Những lẵng hoa tươi rực rỡ nhập khẩu từ châu Âu xếp thành hai hàng dài dọc lối đi, và những tấm băng rôn đỏ chót in chữ vàng rực chúc mừng sự kiện niêm yết chính thức của Tập đoàn Dược phẩm Khang Thị với mã cổ phiếu KTP nổi bật trên các bức tường kính. Giá chào sàn dự kiến được ấn định ở mức cực kỳ cao: 45,000 VND cho mỗi cổ phiếu, đẩy mức định giá tổng thể của Khang Thị vượt ngưỡng 5,000 tỷ đồng ngay trong ngày đầu tiên của đợt niêm yết này.</p>"
        "<p>Đường Vĩnh Khang và Hoàng Thế Dũng mặc những bộ comple đặt may riêng đắt đỏ từ các thương hiệu thời trang hàng đầu thế giới, gương mặt tràn ngập niềm kiêu hãnh và nụ cười tự mãn tột cùng. Họ đứng ở vị trí trung tâm sảnh lớn, tay nâng ly rượu sâm-panh pha lê lấp lánh, vây quanh bởi hàng chục phóng viên báo đài, các nhà đầu tư tổ chức sừng sỏ và các nhà môi giới chứng khoán đang liên tục nói những lời chúc tụng bay bổng. Tiếng ly thủy tinh va vào nhau lách cách, mùi nước hoa đắt tiền hòa quyện cùng tiếng xì xào bàn tán của giới đầu cơ về việc cổ phiếu KTP sẽ tăng kịch trần bao nhiêu phiên liên tục tạo nên một bầu không khí náo nhiệt, say sưa và tràn đầy lòng tham của thế giới tài chính.</p>"
        "<p>\"Hôm nay không chỉ là ngày Khang Thị bước lên đỉnh cao vinh quang của thị trường tài chính, mà còn là cột mốc khẳng định vị thế bá chủ của chúng tôi. Dòng sản phẩm điều trị gan cao cấp 'Khang Can Linh' của chúng tôi sẽ sớm chiếm lĩnh toàn bộ thị trường Đông Nam Á, mang về doanh thu hàng ngàn tỷ đồng mỗi năm,\" Đường Vĩnh Khang dõng dạc phát biểu trước hàng chục ống kính máy quay truyền hình đang phát sóng trực tiếp cho hàng triệu khán giả cả nước xem.</p>"
        "<p>Thế nhưng, ngay giữa bầu không khí hân hoan tột đỉnh đó, cả Đường Vĩnh Khang và Hoàng Thế Dũng đều không hề biết rằng một thảm họa kinh hoàng đang lặng lẽ nhưng vô cùng tàn khốc ập xuống đầu họ. Trước đó đúng ba tuần, Trần Huy Hoàng đã gửi một bộ hồ sơ kỹ thuật cực kỳ chi tiết kèm theo các mẫu thử nghiệm hóa học độc lập lên Cục Quản lý Dược trực thuộc Bộ Y tế. Bộ hồ sơ phơi bày toàn bộ dữ liệu khoa học về sự biến đổi cấu trúc phân tử nguy hiểm của thuốc Khang Can Linh khi sản xuất thương mại ở quy mô công nghiệp lớn mà không có sự kiểm soát của quy trình đặc thù.</p>"
        "<p>Dưới sự chỉ đạo khẩn cấp và bảo mật tuyệt đối của lãnh đạo Bộ Y tế, một đợt hậu kiểm tra an toàn sinh học độc lập đã được tiến hành khẩn cấp trên ba lô thuốc Khang Can Linh lấy ngẫu nhiên từ các đại lý phân phối chính thức của Khang Thị tại Sài Gòn. Kết quả phân tích sắc ký lỏng hiệu năng cao phối hợp phổ khối lượng từ Viện Kiểm nghiệm Thuốc Trung ương đã cho ra một kết luận chấn động toàn bộ ban lãnh đạo ngành y tế: Do sản xuất trong các bồn phản ứng công nghiệp áp suất cao lên tới 3 atmospheres và nhiệt độ gia nhiệt nhanh vượt quá 95 độ C để kịp sản lượng cho đợt IPO, hoạt chất trong Khang Can Linh đã bị bẻ gãy hoàn toàn liên kết vòng thơm đặc trưng. Không có loại enzyme xúc tác tự nhiên được trích xuất từ sâm Ngọc Linh Đà Lạt theo tỉ lệ vàng chưng cất áp suất thấp như công thức cải tiến của Huy Hoàng để bảo vệ, các phân tử thuốc đã tự động tái sắp xếp cấu trúc thành một hợp chất dinitrophenyl độc hại cực mạnh.</p>"
        "<p>Trong quá trình thử nghiệm khẩn cấp độc lập trên mười động vật linh trưởng tại phòng thí nghiệm trung ương, kết quả vô cùng thảm khốc: tất cả mười đối tượng đều xuất hiện tình trạng hoại tử tế bào gan cấp tính diện rộng chỉ sau bảy ngày sử dụng liên tục. Các chỉ số men gan AST và ALT tăng vọt vượt quá giới hạn đo của máy móc hiện đại (trên 5000 U/L), đi kèm với tình trạng suy thận cấp nghiêm trọng do kết tủa tinh thể độc tố trong ống thận. Mức độ độc tính này tương đương với các chất độc hủy hoại nội tạng cực mạnh, có thể tước đoạt mạng sống của người bệnh chỉ trong thời gian ngắn ngủi.</p>"
        "<p>Tại nhà máy sản xuất của Khang Thị ở Khu công nghệ cao, khi các kỹ sư phát hiện hệ thống cảm biến nhiệt độ báo đỏ liên tục do phản ứng phụ ngoài kiểm soát, Hoàng Thế Dũng đã ra lệnh thô bạo: \"Bỏ qua các cảnh báo an toàn! Tắt còi báo động đi! Chúng ta phải sản xuất đủ một triệu hộp trước ngày IPO để báo cáo số liệu bán hàng! Không được phép dừng dây chuyền dù chỉ một giây!\" Sự tham lam vô độ của họ đã tự tay châm ngòi cho quả bom nguyên tử pháp lý nguy hiểm này.</p>"
        "<p>Tám giờ ba mươi phút sáng, chỉ đúng ba mươi phút trước khi tiếng chuông khai mạc phiên giao dịch khớp lệnh xác định giá mở cửa (ATO) trên sàn chứng khoán HoSE bắt đầu rung lên. Bất ngờ, một đoàn xe ô tô chuyên dụng màu đen gồm năm chiếc SUV dẫn động bốn bánh của Cục Cảnh sát điều tra tội phạm về tham nhũng, kinh tế, buôn lậu (C03) thuộc Bộ Công An đỗ xịch ngay trước sảnh chính của tòa nhà HoSE tại Quận 1. Hơn hai mươi điều tra viên và cảnh sát cơ động mặc sắc phục chỉnh tề, thần thái nghiêm nghị bước nhanh vào sảnh lớn của tòa nhà, dẫn đầu là một vị Thượng tá cảnh sát với gương mặt sắt đá vô cảm lạnh lùng.</p>"
        "<p>Bầu không khí náo nhiệt, ồn ào trong sảnh HoSE bỗng chốc im bặt như có một dòng nước đá dội xuống từ trên cao. Hàng trăm ánh mắt ngơ ngác, kinh ngạc đổ dồn về phía đoàn cảnh sát đang tiến thẳng tới khu vực bục phát biểu trung tâm, nơi Đường Vĩnh Khang và Hoàng Thế Dũng đang chuẩn bị tiến hành nghi thức gõ chuông vàng niêm yết cổ phiếu KTP.</p>"
        "<p>Thượng tá cảnh sát bước lên bục phát biểu, rút từ trong cặp tài liệu ra tờ lệnh bắt giữ khẩn cấp có chữ ký đóng dấu đỏ tươi của Viện Kiểm sát Nhân dân Tối cao và dõng dạc công bố trước toàn thể hội trường: \"Đường Vĩnh Khang! Hoàng Thế Dũng! Hai người bị bắt giữ khẩn cấp để điều tra về hành vi sản xuất, buôn bán hàng giả là thuốc chữa bệnh theo Điều 194 Bộ luật Hình sự Việt Nam, và hành vi cố ý công bố thông tin sai lệch, thao túng thị trường chứng khoán gây hậu quả đặc biệt nghiêm trọng!\"</p>"
        "<p>Cạch! Hai chiếc còng số tám bằng thép sáng loáng, lạnh lùng lập tức được cảnh sát khóa chặt vào cổ tay của Đường Vĩnh Khang và Hoàng Thế Dũng trước sự chứng kiến của hàng trăm ống kính máy ảnh đang nhấp nháy đèn flash liên tục như bão giông. Ly rượu sâm-panh trên tay Đường Vĩnh Khang rơi tự do xuống đất, vỡ tan tành thành trăm mảnh, bọt sâm-panh tung tóe khắp đôi giày da cá sấu đắt tiền của hắn. Khuôn mặt Khang từ đỏ gay do men rượu bỗng chốc chuyển sang tái nhợt như không còn giọt máu, hai đầu gối run rẩy dữ dội rồi quỵ sụp xuống nền đá hoa cương bóng loáng của sảnh giao dịch trong sự ngỡ ngàng tột độ của toàn bộ giới tài chính Việt Nam.</p>"
    )

    # Chapter 6
    chap6_title = "Chương 6: Trắng Bên Mua Trên Sàn Chứng Khoán Và Bản Đính Ước Dưới Hoàng Hôn"
    chap6_content = (
        "<p>Chín giờ đúng, tiếng chuông phiên giao dịch khớp lệnh ATO trên sàn chứng khoán TP.HCM (HoSE) chính thức vang lên. Trên bảng điện tử khổng lồ hiển thị thông tin giao dịch, mã cổ phiếu KTP của Tập đoàn Dược phẩm Khang Thị bắt đầu xuất hiện. Thế nhưng, trái ngược hoàn toàn với kịch bản tăng trần rực rỡ mà giới đầu cơ kỳ vọng trước đó, một cảnh tượng thảm khốc chưa từng có trong lịch sử chứng khoán Việt Nam đã diễn ra.</p>"
        "<p>Dưới tác động khủng khiếp từ thông tin C03 bắt giữ khẩn cấp ban lãnh đạo Khang Thị Pharma ngay tại sảnh HoSE và quyết định thu hồi khẩn cấp trên toàn quốc, cấm lưu hành vĩnh viễn thuốc Khang Can Linh của Bộ Y tế được phát đi trên các phương tiện truyền thông chính thống, làn sóng hoảng loạn tột độ bao trùm toàn bộ thị trường. Hàng vạn nhà đầu tư cá nhân và tổ chức đồng loạt đặt lệnh bán bằng mọi giá. Trên bảng điện tử, cột \"Bên mua\" của mã KTP hoàn toàn trống trơn, trắng xóa không có một lệnh mua đối ứng nào (\"trắng bên mua\"). Trong khi đó, cột \"Bên bán\" bị chặn cứng bởi hơn năm mươi triệu cổ phiếu chất đống ở mức giá sàn giảm hết biên độ (giảm sàn xanh lơ). Vốn hóa trị giá hơn năm ngàn tỷ đồng của Khang Thị Pharma chính thức bốc hơi hoàn toàn chỉ trong vòng vài giây ngắn ngủi, biến thành một đống giấy lộn không hơn không kém.</p>"
        "<p>Lúc này, tại sảnh ngoài của tòa nhà HoSE Quận 1, Đường Vĩnh Khang đang bị hai cảnh sát áp giải ra xe chuyên dụng dưới sự bao vây của hàng trăm phóng viên đang liên tục chĩa micro vào mặt hỏi dồn dập. Đúng lúc đó, Trần Huy Hoàng và Trần Tuệ Lâm từ trên chiếc xe Rolls-Royce Ghost của Thái Bình Capital bước xuống. Huy Hoàng mặc bộ vest đen lịch lãm, phong thái ung dung tự tại, bên cạnh là Tuệ Lâm xinh đẹp kiêu sa tỏa sáng rực rỡ.</p>"
        "<p>Nhìn thấy Huy Hoàng, Đường Vĩnh Khang như kẻ sắp chết đuối vớ được cọc, hắn cố sức vùng vẫy thoát khỏi sự kiềm tỏa của cảnh sát, quỳ sụp gối xuống nền đường nhựa nóng bỏng ngay trước mũi giày của Huy Hoàng. Hắn gào khóc thảm thiết, nước mắt nước mũi giàn giụa: \"Huy Hoàng! Anh Hoàng ơi! Tôi sai rồi! Tôi là con chó mắt mù mới đi cướp công trình của anh! Xin anh cứu lấy Khang Thị! Chỉ cần anh ra mặt sửa lại công thức, tôi sẵn sàng chuyển giao toàn bộ cổ phần tập đoàn cho anh! Xin anh cứu tôi với!\"</p>"
        "<p>Huy Hoàng dừng bước chân, cúi đầu nhìn kẻ từng đuổi mình đi dưới đêm tuyết lạnh giá Đà Lạt bằng ánh mắt vô cảm như nhìn một hạt bụi vô danh. Anh khẽ nghiêng đầu, giọng nói bình thản nhưng lạnh thấu xương tủy: \"Đường Vĩnh Khang, nhân quả tuần hoàn, báo ứng nhãn tiền. Từ giây phút ông ném hành lý của tôi ra đường đèo và giật đi mẫu thử, ông đã tự tay ký vào bản án tử hình cho chính mình rồi.\"</p>"
        "<p>Nói rồi, Huy Hoàng không thèm liếc nhìn thêm một cái, ung dung bước qua Đường Vĩnh Khang đang gào khóc tuyệt vọng trong tiếng còi hú vang trời của xe cảnh sát chuyên dụng. Cùng ngày hôm đó, Công ty Cổ phần Đại Đông Dược chính thức ra mắt sản phẩm \"Đông Dược Độc Bản\", được giới y học đón nhận nồng nhiệt với chứng nhận an toàn và kết quả điều trị thần kỳ được xác nhận bởi Bệnh viện Chợ Rẫy. Cổ phiếu của các doanh nghiệp liên kết với Thái Bình Capital tăng vọt, trong khi Tuệ Lâm tuyên bố quỹ sẽ tiến hành thâu tóm toàn bộ hệ thống nhà máy sản xuất chuẩn GMP và chuỗi nhà thuốc phân phối bán lẻ đang trong quá trình phá sản của Khang Thị với giá rẻ như cho để sáp nhập vào hệ sinh thái của Đại Đông Dược.</p>"
        "<p>Chiều muộn hôm sau, tại Đà Lạt, nơi Đại Đông Dược vừa khánh thành Viện Nghiên cứu Dược liệu Cao cấp mới trên một ngọn đồi thông thơ mộng ngập tràn sương mù. Ánh hoàng hôn buông xuống cao nguyên, nhuộm đỏ cả một góc trời bằng thứ ánh sáng màu cam tím ấm áp và lãng mạn vô cùng. Trong khu vườn sâm Ngọc Linh xanh mướt ngập tràn hương thảo dược thanh khiết, Trần Tuệ Lâm và Trần Huy Hoàng đang chậm rãi đi dạo cạnh nhau.</p>"
        "<p>Tuệ Lâm dừng bước, cô quay người lại đối diện với Huy Hoàng. Dưới ánh hoàng hôn dịu dàng, đôi mắt sắc sảo thường ngày của nữ tổng tài tài phiệt bỗng chốc trở nên vô cùng dịu dàng, sâu lắng. Cô chủ động đưa bàn tay thon mềm của mình ra, khẽ nắm lấy bàn tay phải vẫn còn nguyên vết sẹo nhạt của anh.</p>"
        "<p>\"Huy Hoàng, mọi thế trận thương trường chúng ta đều đã thắng lợi hoàn mỹ. Nhưng hôm nay, em đứng ở đây đối diện với anh, không phải với tư cách là Tổng giám đốc Thái Bình Capital thẩm định dự án, cũng không phải vì lợi ích kinh tế ràng buộc của gia tộc,\" Tuệ Lâm khẽ mỉm cười, giọng nói ấm áp rung động tận tâm can. \"Em yêu anh vì đức độ, tài năng và sự rung động tự nguyện chân thật nhất của trái tim em trước một người đàn ông kiên cường như anh. Em muốn từ nay về sau, chúng ta sẽ cùng nhau đi trên mọi nẻo đường đời, không chỉ là những thương vụ bạc tỷ.\"</p>"
        "<p>Huy Hoàng nhìn cô gái thông minh tuyệt đỉnh nhưng vô cùng chân thành trước mặt, lòng bàn tay anh cảm nhận rõ rệt hơi ấm từ các ngón tay mềm mại của cô truyền qua. Anh mỉm cười ấm áp, siết nhẹ tay cô: \"Tuệ Lâm, cảm ơn em đã luôn đứng bên cạnh anh từ những ngày tăm tối nhất dưới thung lũng đèo Prenn. Có em đồng hành, đời này của anh không còn gì hối tiếc.\"</p>"
        "<p>Dưới ánh hoàng hôn lãng mạn của cao nguyên Đà Lạt, họ trao nhau một cái hẹn ước sâu sắc tự nguyện. Sáng ngày hôm sau, tại buổi họp báo thế kỷ được tổ chức ở khách sạn năm sao tại trung tâm Sài Gòn trước hàng trăm phóng viên báo chí trong nước và quốc tế, Trần Tuệ Lâm chính thức công bố quyết định đính hôn cùng Trần Huy Hoàng, mở ra một chương mới rực rỡ cho đế chế dược phẩm độc bản hàng đầu Việt Nam.</p>"
    )

    novel["chapters"].append({"title": chap1_title, "content": chap1_content})
    novel["chapters"].append({"title": chap2_title, "content": chap2_content})
    novel["chapters"].append({"title": chap3_title, "content": chap3_content})
    novel["chapters"].append({"title": chap4_title, "content": chap4_content})
    novel["chapters"].append({"title": chap5_title, "content": chap5_content})
    novel["chapters"].append({"title": chap6_title, "content": chap6_content})

    # Validate word counts
    print("=" * 40)
    print("📏 CHECKING CHAPTER WORD COUNTS (1000 - 1500 limit)")
    print("=" * 40)
    for i, ch in enumerate(novel["chapters"]):
        w_count = count_words(ch["content"])
        print(f"Chapter {i+1}: {w_count} words | Title: {ch['title']}")
        if w_count < 1000 or w_count > 1500:
            print(f"⚠️ Chapter {i+1} word count ({w_count}) is outside the 1000-1500 range!")
    
    # Save file
    pending_file = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_novel.json"
    with open(pending_file, "w", encoding="utf-8") as f:
        json.dump(novel, f, ensure_ascii=False, indent=2)
    print("✓ Successfully saved novel to", pending_file)

if __name__ == "__main__":
    main()
