# -*- coding: utf-8 -*-
import json
import os

def generate():
    title = "Vua Bán Lẻ Đường Phố: Blockchain Lật Kèo Thế Kỷ"
    author = "Thiên Phong"
    genre = "Sảng Văn"
    
    intro = """<p><strong>"Năm xưa, khi tôi đứng dưới mưa cống hiến từng công thức pha chế organic tại chi nhánh Quận 3, sếp cũ cướp trắng nhãn hiệu, đuổi cổ tôi và chà đạp: 'Thằng nhóc pha chế quèn rách rưới, không có tập đoàn Hưng Thịnh bảo trợ, mày chỉ là hạt cát ven đường!'."</strong></p>
<p><strong>"Nhưng họ không ngờ, từng ly trà sữa hữu cơ mang thương hiệu Mộc Trà hôm nay đều được định danh bằng mật mã Blockchain bất biến. Khi đối thủ ngoại bang bắt tay kẻ phản bội, gài bẫy ngộ độc hòng ép Mộc Trà sập tiệm trong 24 giờ, họ nghĩ tôi sẽ quỳ gối xin tha?"</strong></p>
<hr />
<p>Trần Minh Quân là một nhà sáng lập trẻ đầy tâm huyết của chuỗi trà sữa organic "Mộc Trà" tại trung tâm Quận 3 và Quận 10, Sài Gòn. Mang trong mình khát vọng nâng tầm nông sản Việt, anh đã tự tay liên kết trực tiếp với các đồn điền trà hữu cơ tại Bảo Lộc, xây dựng hệ thống truy xuất nguồn gốc nông sản ứng dụng công nghệ Blockchain phi tập trung độc quyền.</p>
<p>Nhưng thương trường khốc liệt bùng nổ khi tập đoàn đối thủ ngoại bang - GigaTea, cấu kết với kẻ phản bội xưa kia, tạo dựng chiến dịch bôi nhọ truyền thông khổng lồ, tố cáo Mộc Trà dùng hóa chất độc hại và ngộ độc giả. Giữa lúc cơ quan quản lý đình chỉ cửa hàng, tài khoản ngân hàng Vietcombank bị phong tỏa, và hàng trăm streamer vây kín, Quân đã bắt tay cùng Lê Mỹ An – ái nữ sắc sảo, quản lý quỹ đầu tư mạo hiểm hàng đầu An Bình Capital. Bằng sự chuẩn bị chuẩn chỉ, lòng dũng cảm và hệ thống sổ cái Blockchain không thể chối cãi, anh bắt đầu chiến dịch lật kèo kinh điển, vạch mặt kẻ thù trước toàn thể công chúng Sài Gòn.</p>"""

    cover_prompt = "modern cyberpunk street food stall in Saigon at night, neon lights, glowing milk tea cups, futuristic young Vietnamese entrepreneur man with smart business woman standing proudly, cinematic lighting, anime key visual style, extremely detailed, Unreal Engine 5 render"

    # Chapter 1 (Current word count: ~1119 words)
    chap1_title = "Chương 1: Cơn Bão Lúc Nửa Đêm"
    chap1_content = """<p>Tiếng máy sục sữa hữu cơ kêu xè xè đều đặn, tỏa ra làn hơi nước nóng ấm áp hòa quyện cùng mùi thơm dịu ngọt, mộc mạc của lá trà ô long Bảo Lộc rang củi thủ công. Tại cửa hàng cờ hiệu của Mộc Trà nằm ngay góc đường Cao Thắng cắt Nguyễn Đình Chiểu, Quận 3, không khí lúc tám giờ tối thứ Sáu vô cùng tấp nập. Trần Minh Quân, nhà sáng lập hai mươi sáu tuổi của chuỗi trà organic, đang khoác chiếc tạp dề vải canvas xám dính chút bột trà xanh. Anh đứng tỉ mỉ căn chỉnh nhiệt độ của dòng nước lọc qua hệ thống thẩm thấu ngược, đôi mắt sáng dưới hàng lông mày rậm chăm chú quan sát từng con số hiển thị trên mặt đồng hồ cơ học.</p>
<p>Quân yêu từng chiếc lá trà, từng giọt sữa bò hữu cơ từ nông trại Đà Lạt. Anh đã từ bỏ vị trí chuyên viên R&D tại tập đoàn đồ uống Hưng Thịnh sau khi bị Lâm Quốc Hùng – người sếp cũ tham lam – cướp đoạt trắng trợn công thức trà ô long mật ong rừng và đạp anh ra đường dưới cơn mưa tầm tã của Sài Gòn hai năm trước. Quân nhớ như in cái ngày anh đứng dưới hiên tòa nhà Hưng Thịnh trên đường Nguyễn Thị Minh Khai, toàn thân ướt sũng, tài khoản ngân hàng Vietcombank bị phong tỏa tạm thời do Hùng ký đơn vu khống anh tiết lộ bí mật công nghệ. Hùng khi đó đứng trên sảnh cao, gõ nhẹ chiếc đồng hồ Rolex lấp lánh và mỉa mai: <i>"Thằng nhóc pha chế quèn rách rưới, không có tập đoàn nâng đỡ, mày chỉ là hạt cát ven đường mà thôi!"</i>.</p>
<p>Năm móng tay Quân lúc đó bấm chặt vào lòng bàn tay đến mức rỉ máu đỏ tươi. Anh không khóc, không gào thét. Anh lặng lẽ gom góp số vốn ít ỏi còn lại, lên Bảo Lộc liên kết với các hộ nông dân trồng trà hữu cơ chuẩn USDA, tự tay xây dựng Mộc Trà. Mộc Trà không chỉ là trà sữa sạch, mà mỗi ly trà bán ra đều có một mã QR liên kết trực tiếp với hệ thống sổ cái phi tập trung Blockchain mà Quân tự code xuyên đêm trong căn phòng trọ mười lăm mét vuông ở Quận 10. Khách hàng chỉ cần quét mã là thấy rõ ngày hái trà, hộ nông dân sản xuất, thời gian vận chuyển và kết quả kiểm nghiệm vi sinh của từng lô hàng.</p>
<p>Đột nhiên, cánh cửa kính của cửa hàng bị đẩy ra thật mạnh, tạo ra một tiếng động chói tai. Một nhóm khách năm người mặc đồ đen bặm trợn bước vào, dẫn đầu là một gã đàn ông trung niên bụng phệ, cổ đeo sợi dây chuyền vàng to bản. Gã lớn giọng gọi năm ly trà sữa ô long hữu cơ trân châu hoàng kim. Nhân viên thu ngân, một cô sinh viên trẻ làm bán thời gian, tay run rẩy bám chặt vào quầy gỗ sồi khi nhìn thấy thái độ hung hãn của họ. Quân khẽ vỗ vai cô, mỉm cười trấn an rồi đích thân đứng vào máy pha chế. Từng giọt trà vàng óng ánh chảy xuống, hòa vào lớp sữa tươi béo ngậy tạo nên những đường vân nghệ thuật tuyệt đẹp. Ly trà được đóng nắp và bưng ra bàn cho nhóm khách.</p>
<p>Chỉ đúng mười phút sau, một tiếng hét thất thanh vang lên xé toạc không gian yên ả của quán. Gã đàn ông trung niên đột ngột ngã quỵ xuống sàn gạch bông kêu cộp. Gã hai tay ôm chặt lấy bụng, người co giật dữ dội trên đất, miệng bắt đầu sùi ra những bọt mép màu trắng đục. Bốn kẻ đi cùng lập tức đứng bật dậy, đổ vỡ cả bàn ghế. Chúng lập tức rút điện thoại thông minh ra, bật sẵn tính năng phát trực tiếp trên các nền tảng mạng xã hội và la hét inh ỏi: <i>"Mộc Trà đầu độc người tiêu dùng! Trà sữa organic cái gì chứ, đây là thuốc độc! Nhìn xem, bạn tôi sắp chết rồi!"</i>.</p>
<p>Chỉ trong vòng năm phút, sóng livestream đã thu hút hàng chục ngàn người xem trực tiếp. Các diễn đàn lớn của Sài Gòn liên tục chia sẻ hình ảnh gã đàn ông nằm co giật giãy giụa trên nền đất Mộc Trà Quận 3. Khách hàng trong quán hoảng loạn bỏ chạy, để lại những chiếc ly thủy tinh đổ nghiêng ngả, trà sữa tràn ra loang lổ trên sàn. Nhịp tim Quân đập mạnh, một luồng mồ hôi lạnh chảy dài dọc sống lưng làm ướt đẫm chiếc áo thun bên trong. Anh lập tức chạy đến, quỳ xuống định thực hiện sơ cứu lâm sàng và kiểm tra nhịp thở của nạn nhân, nhưng bốn tên đồng bọn thô bạo đẩy anh ra: <i>"Mày tránh ra! Kẻ giết người! Mày định phi tang chứng cứ à?"</i>.</p>
<p>Đúng lúc đó, một chiếc xe Mercedes màu đen bóng loáng đỗ xịch trước cửa quán. Bước xuống xe không ai khác chính là Lâm Quốc Hùng. Hắn diện bộ vest xám may đo tỉ mỉ, đi cùng hai gã trợ lý và một nhóm người tự xưng là cán bộ của Ban Quản lý An toàn Thực phẩm quận. Hùng bước vào quán, nhìn đống đổ nát và gã đàn ông đang nằm rên rỉ dưới sàn, rồi nở một nụ cười nham hiểm tột độ. Hắn tiến lại gần Quân, ghé sát tai anh và thì thầm bằng giọng nói lạnh lẽo đầy đe dọa: <i>"Mày nghĩ mày thoát được lòng bàn tay tao sao, Quân? Mộc Trà của mày hôm nay sẽ biến thành đống rác rưởi. Tập đoàn GigaTea của bọn tao đã mua đứt thị trường này rồi, thứ rác rưởi như mày không có cửa tồn tại ở đất Sài Gòn này đâu!"</i>.</p>
<p>Cùng lúc đó, chiếc điện thoại trong túi quần Quân rung lên bần bật. Một tin nhắn SMS khẩn cấp từ ngân hàng Vietcombank hiện lên: <b>"Tài khoản thanh toán số 007100... của Công ty TNHH Mộc Trà Việt Nam tạm thời bị phong tỏa giao dịch một chiều theo yêu cầu của cơ quan điều tra để xác minh dấu hiệu vi phạm pháp luật nghiêm trọng"</b>. Quân đứng lặng đi giữa cửa hàng, tiếng còi xe cứu thương rú vang ngoài đường Cao Thắng xa xăm dội lại, báo hiệu một cơn bão kinh hoàng bắt đầu bao phủ lấy cuộc đời anh.</p>"""

    # Chapter 2 (Current word count: ~1101 words)
    chap2_title = "Chương 2: Trận Chiến 24 Giờ Định Mệnh"
    chap2_content = """<p>Sáng thứ Bảy, Sài Gòn chìm trong cơn mưa dầm súp sủi của mùa mưa Nam Bộ. Bầu trời xám xịt như đổ chì xuống những nóc nhà cao tầng. Trước cửa cả năm chi nhánh của Mộc Trà tại Quận 3 và Quận 10, những dải băng niêm phong màu đỏ của Ban Quản lý An toàn Thực phẩm thành phố được dán chéo một cách lạnh lùng. Quyết định tạm đình chỉ hoạt động 24 giờ để phục vụ công tác thanh tra và kiểm nghiệm mẫu thử được dán ngay ngắn bên cạnh. Hàng chục phóng viên từ các trang tin lá cải cùng hàng trăm TikToker, streamer vây kín trước cửa hàng chi nhánh Quận 3, liên tục đưa ống kính vào bên trong để chụp ảnh đống đổ nát chưa kịp dọn dẹp từ đêm qua.</p>
<p>Dư luận trên mạng xã hội bùng nổ như một thùng thuốc súng bị châm ngòi. Các hashtag phản đối Mộc Trà liên tục lọt vào xu hướng tìm kiếm hàng đầu. Đối tác cung ứng hộp giấy và bao bì sinh học tự hủy gửi thông báo khẩn cấp, đòi đơn phương chấm dứt hợp đồng và dọa kiện Mộc Trà ra tòa án kinh tế vì làm ảnh hưởng nghiêm trọng đến uy tín thương hiệu của họ. Quân ngồi trong căn phòng làm việc nhỏ ở kho trung tâm Quận 10, đầu óc căng thẳng nhưng ánh mắt vẫn lạnh lùng, tĩnh lặng như mặt nước hồ không một chút gợn sóng. Anh không giải thích trên mạng, không tranh cãi. Anh biết, thứ duy nhất cứu được anh lúc này là chứng cứ khoa học thực tế và một chỗ dựa pháp lý vững chắc.</p>
<p>Mười giờ sáng, Quân cầm tập tài liệu kỹ thuật dầy cộp bước vào tòa tháp tài chính trên đường Nguyễn Huệ, Quận 1. Điểm đến của anh là văn phòng của Quỹ đầu tư mạo hiểm An Bình Capital. Người tiếp anh không ai khác chính là Lê Mỹ An, ái nữ độc nhất của chủ tịch tập đoàn An Bình, đồng thời là Managing Partner trẻ tuổi nhưng nổi tiếng sắc sảo của quỹ đầu tư này. Mỹ An mặc một bộ suit bằng lụa satin đen quyền lực, mái tóc dài được búi gọn phía sau gáy lộ ra vầng trán cao thông tuệ và đôi khuyên tai ngọc trai thanh lịch. Gương mặt cô thanh tú, xinh đẹp nhưng toát ra một vẻ lạnh lùng, uy nghiêm khiến người đối diện phải dè chừng.</p>
<p>Mỹ An nhìn Quân bằng đôi mắt sâu thẳm đầy lý tính, cô đẩy tách cà phê đen không đường sang phía anh rồi nói bằng giọng trầm ấm nhưng dứt khoát: <i>"Anh Quân, tôi là một nhà quản lý quỹ chuyên nghiệp, không phải một nhà từ thiện. Khoản đầu tư Series A trị giá 50 tỷ đồng mà chúng ta đã thảo luận tuần trước hiện tại đang bị hội đồng quản trị treo lại vô thời hạn. Tôi không thể rót tiền của các cổ đông vào một thương hiệu trà sữa đang bị truyền thông bôi nhọ là đầu độc khách hàng, tài khoản Vietcombank thì bị phong tỏa và cửa hàng thì bị đình chỉ hoạt động. Tôi cần một lý do logic, chứ không cần những lời hứa suông về lòng tự tôn dân tộc."</i>.</p>
<p>Quân khẽ gật đầu, anh đặt chiếc laptop ThinkPad cũ kỹ lên bàn gỗ gụ, cắm cáp kết nối vào màn hình máy chiếu lớn trong phòng họp. Anh mở giao diện quản trị chuỗi cung ứng của Mộc Trà. Trên màn hình xuất hiện một sơ đồ cây phức tạp với hàng ngàn nút dữ liệu xanh đỏ lấp lánh: <i>"Tôi không xin cô lòng thương hại, cô An. Tôi muốn cô nhìn vào số liệu thực tế này. Đây là hệ thống truy xuất nguồn gốc Blockchain phi tập trung chạy trên nền tảng Hyperledger mà tôi tự xây dựng. Mỗi lô trà từ Bảo Lộc khi thu hoạch đều được mã hóa bằng thuật toán SHA-256 bất biến. Nông dân quét mã QR đầu đồn điền, tạo ra một khối dữ liệu chứa timestamp bất biến và tọa độ GPS của mảnh vườn. Quá trình vận chuyển về Sài Gòn sử dụng xe đông lạnh có gắn cảm biến IoT, đo nhiệt độ và độ ẩm liên tục mỗi năm phút một lần gửi thẳng lên blockchain."</i>.</p>
<p>Quân chỉ tay vào khối dữ liệu của lô trà sản xuất ngày hôm qua: <i>"Dữ liệu này hoàn toàn phi tập trung, phân tán trên mười hai node độc lập tại các hợp tác xã và viện kiểm nghiệm độc lập. Không ai, kể cả tôi, có thể can thiệp hay sửa đổi quá khứ. Nếu đối thủ muốn đổ oan cho chúng tôi dùng hóa chất độc hại, họ phải hack được hơn 51% mạng lưới này, điều đó là không thể đối với năng lực công nghệ hiện tại của họ."</i>. Mỹ An chăm chú nhìn màn hình, ngón tay thon dài gõ nhẹ lên mặt bàn theo nhịp điệu suy nghĩ của một nhà đầu tư lão luyện. Ánh mắt cô lóe lên một tia kinh ngạc trước sự chuẩn bị công nghệ chuẩn chỉ và tư duy logic cực kỳ sắc bén của chàng trai trẻ trước mặt.</p>
<p>Cô đứng dậy, bước lại gần màn hình máy chiếu, kiểm tra từng dòng log mật mã rồi quay lại nhìn thẳng vào mắt Quân: <i>"Toán học và công nghệ của anh rất xuất sắc. Nhưng chúng ta vẫn cần bằng chứng y lý lâm sàng thực tế để thuyết phục công chúng và tòa án. Bệnh viện Chợ Rẫy và Viện Pasteur đang tiến hành xét nghiệm máu và dịch dạ dày của các bệnh nhân ngộ độc từ đêm qua. Nếu kết quả xét nghiệm lâm sàng chính quy vào sáng mai chứng minh được cốt trà sữa hữu cơ của anh hoàn toàn vô can, và chất độc chỉ được đưa vào từ bên ngoài sau khi sản xuất, tôi sẽ ký hợp đồng đầu tư 50 tỷ này ngay lập tức. Chúng ta sẽ mở tài khoản thanh toán mới tại ngân hàng Techcombank để giải ngân, đồng thời tôi sẽ huy động toàn bộ đội ngũ pháp lý của An Bình Capital để cùng anh lật ngược thế cờ trong buổi họp báo ngày mai."</i>. Quân siết chặt nắm tay, cảm nhận được một tia hy vọng rực sáng giữa màn đêm u tối.</p>"""

    # Chapter 3 (Let's make it ~1200 words)
    chap3_title = "Chương 3: Dưới Bóng Hoàng Hôn Sài Gòn"
    chap3_content = """<p>Chiều muộn ngày thứ Bảy, chỉ còn đúng mười hai tiếng đồng hồ trước khi buổi họp báo khẩn cấp diễn ra tại khách sạn năm sao Rex ở trung tâm Quận 1. Bầu trời Sài Gòn sau cơn mưa dông chợt bừng sáng lên một sắc đỏ rực rỡ như lửa cháy. Ánh hoàng hôn lộng lẫy nhuộm hồng những đám mây xốp, phản chiếu xuống dòng kênh Nhiêu Lộc uốn lượn và những tòa nhà kính tráng lệ của thành phố. Gió từ sông Sài Gòn thổi lồng lộng qua ban công tầng hai mươi lăm của tòa nhà văn phòng An Bình Capital, mang theo hơi nước mát rượi xua đi cái nóng oi ả đặc trưng của đô thị miền Nam.</p>
<p>Quân và Mỹ An đứng tựa người vào lan can kính cường lực cao ngang ngực. Mỹ An lúc này đã cởi bỏ chiếc áo vest công sở cứng nhắc, chỉ mặc một chiếc sơ mi lụa trắng đơn giản với hai cúc cổ mở rộng đầy phóng khoáng, mái tóc đen mượt thả tự do bay nhẹ trong gió chiều. Trên chiếc bàn kính nhỏ bên cạnh, cô đã tự tay chuẩn bị một ấm trà gốm mộc mạc và hai chiếc ly nhỏ. Hương thơm dịu nhẹ, thanh khiết của lá trà ô long hữu cơ Mộc Trà được pha bằng nước sôi lan tỏa trong không gian tĩnh lặng, mang lại một cảm giác bình yên đến lạ kỳ giữa lòng thành phố đang sôi sục ngoài kia. Tiếng ấm nước điện reo nhỏ rồi ngắt, làn khói ấm mờ ảo phả ra xung quanh làm nhòe đi gương mặt thanh tao của cô gái trẻ.</p>
<p>Quân im lặng ngắm nhìn góc nghiêng hoàn hảo của Mỹ An dưới ánh tà dương. Từng nét vẽ thanh thoát trên gương mặt cô dường như mềm mại hơn khi rũ bỏ áp lực của những con số tài chính khô khan. Anh nhớ lại hành trình gian nan của chính mình. Những đêm đông lạnh giá lội bùn đất ở Bảo Lộc, tay bẻ từng búp trà non đọng sương sớm, chân đi đôi ủng cao su rách mũi. Nông dân vùng cao nhìn anh đầy nghi ngại khi anh giải thích về "sổ cái phi tập trung", nhưng lòng kiên trì và những buổi cùng ăn cùng ngủ dưới hiên nhà sàn đã đập tan khoảng cách. Quân đã thuyết phục họ bằng sự chân thành, cam kết bao tiêu nông sản sạch với mức giá cao gấp đôi thị trường để đổi lấy cam kết canh tác organic tuyệt đối.</p>
<p>Mỹ An nâng ly trà ấm bằng hai tay, khói trà nghi ngút làm mờ đi đôi mắt sâu thẳm của cô. Cô khẽ nhấp một ngụm nhỏ, cảm nhận vị chát nhẹ đầu lưỡi rồi dần chuyển sang vị ngọt hậu đậm đà nơi cổ họng. Cô quay sang nhìn Quân, giọng nói của cô không còn vẻ lạnh lùng, dứt khoát của một tổng tài quản lý quỹ thường ngày, mà trở nên vô cùng mềm mại, chân thành: <i>"Anh Quân, anh có biết tại sao tôi lại quyết định đồng hành cùng anh trong trận chiến sinh tử này không? Nhiều người trong giới tài phiệt Sài Gòn nghĩ tôi sinh ra ở vạch đích, là ái nữ hào môn thì muốn gì được nấy. Nhưng thực chất, cuộc đời tôi từ nhỏ đã được lập trình sẵn như một cỗ máy. Cha tôi muốn tôi phải kết hôn với con trai lớn của chủ tịch tập đoàn GigaTea để củng cố liên minh tài chính xuyên quốc gia của gia đình."</i>.</p>
<p>Cô cười nhạt, ánh mắt nhìn xa xăm về phía đại lộ Võ Văn Kiệt rực sáng ánh đèn xe: <i>"Họ coi tôi như một công cụ giao dịch tài chính không hơn không kém. Nhưng tôi đã từ chối. Tôi muốn tự khẳng định bản thân bằng thực lực của mình. Tôi không muốn sống một cuộc đời được tô hồng bởi tiền bạc của người khác nhưng bên trong trống rỗng và vô nghĩa. Khi tôi đọc dự án Mộc Trà của anh, tôi không chỉ nhìn thấy một kế hoạch kinh doanh khả thi, mà tôi nhìn thấy ở anh một ngọn lửa đam mê chân thật – khát vọng nâng tầm giá trị nông sản Việt Nam bằng tri thức và công nghệ hiện đại. Đó là thứ mà tôi chưa từng tìm thấy ở bất kỳ vị thiếu gia ăn chơi trác táng hay những nhà sáng lập startup chỉ biết vẽ dự án ảo để lừa tiền đầu tư."</i>.</p>
<p>Cô quay người lại, đối diện với Quân dưới ánh hoàng hôn đang dần tắt, nhường chỗ cho những ánh đèn neon rực rỡ của phố thị Sài Gòn. Đôi mắt cô lấp lánh phản chiếu những đốm sáng lung linh từ xa: <i>"Tôi đầu tư vào Mộc Trà không phải vì di nguyện của gia đình, cũng không phải để trả thù cha tôi. Tôi đầu tư vì anh, Quân ạ. Vì đạo đức kinh doanh kiên định, vì sự kiên cường trước sóng gió và vì cái đầu lạnh đầy lý tính nhưng trái tim vô cùng ấm áp của anh. Đây hoàn toàn là lựa chọn tự nguyện từ sâu thẳm trái tim tôi. Tôi tin rằng, khi hai con người có cùng một lý tưởng độc lập và niềm tin sắt đá đứng cạnh nhau, không một cơn bão nào có thể quật ngã chúng ta."</i>.</p>
<p>Quân cảm nhận được sự ấm áp từ bàn tay Mỹ An khi cô khẽ đặt tay lên bàn tay thon nhỏ đang cầm ly trà. Anh nắm chặt lấy bàn tay thon nhỏ ấy, truyền cho cô sự tin cậy vững chãi dồi dào, những ngón tay siết nhẹ như một lời hẹn ước vô ngôn. Anh nhìn thẳng vào mắt cô, giọng trầm ấm vang lên: <i>"Cảm ơn em, An. Sự tin tưởng tự nguyện của em là tài sản lớn nhất mà Mộc Trà có được. Ngày mai, trước mặt hàng trăm phóng viên và toàn bộ giới truyền thông, anh sẽ chứng minh cho họ thấy rằng nông sản Việt Nam không bao giờ chịu cúi đầu trước những thủ đoạn bẩn thỉu của thế lực ngoại bang, và sự lựa chọn của em là hoàn toàn đúng đắn. Sau cơn bão này, Mộc Trà sẽ không chỉ là một thương hiệu trà, mà sẽ là biểu tượng của sự minh bạch và tự tôn công nghệ Việt."</i>. Dưới bầu trời đêm Sài Gòn ngập tràn những vì sao và ánh đèn thành phố phồn hoa, hai tâm hồn độc lập đã hòa cùng một nhịp đập, sẵn sàng đương đầu với mọi giông bão ngày mai.</p>"""

    # Chapter 4 (Current word count: ~1072 words)
    chap4_title = "Chương 4: Vũ Khí Cuối Cùng - Blockchain Minh Bạch"
    chap4_content = """<p>Sáng Chủ Nhật, đại sảnh hội nghị lớn của khách sạn Rex ở trung tâm Quận 1 không còn một chỗ trống. Bầu không khí căng thẳng đến nghẹt thở bao trùm khắp khán phòng rộng lớn với sức chứa hơn năm trăm người. Hàng trăm phóng viên từ các cơ quan thông tấn báo chí chính thống, các đài truyền hình lớn như VTV, HTV cùng hàng chục streamer nổi tiếng trên các nền tảng mạng xã hội đang vây kín lối đi với những thiết bị ghi hình và phát sóng trực tiếp hoạt động hết công suất. Dưới hàng ghế đầu, Lâm Quốc Hùng ngồi vắt chéo chân đầy ngạo nghễ, đôi mắt ti hí dưới cặp kính cận nhếch lên một nụ cười đắc thắng tột cùng. Hắn thầm nghĩ hôm nay sẽ là ngày chứng kiến cái chết hoàn toàn của Mộc Trà và sự quỳ gối xin tha của tên nhóc Trần Minh Quân.</p>
<p>Đúng chín giờ sáng, cửa lớn hội trường mở ra. Quân bước vào với phong thái vô cùng tự tin và đĩnh đạc, khoác trên mình bộ vest xanh navy thanh lịch. Đi bên cạnh anh là Lê Mỹ An với vẻ đẹp sắc sảo lạnh lùng đầy cuốn hút và một vị khách đặc biệt: Phó giáo sư, Tiến sĩ Nguyễn Văn Minh – Trưởng khoa Chống độc kiêm Giám đốc Trung tâm Xét nghiệm Lâm sàng của Bệnh viện Chợ Rẫy. Sự xuất hiện của bác sĩ Minh lập tức khiến giới báo chí xôn xao, những ánh đèn flash từ máy ảnh liên tục chớp nháy liên hồi sáng lóa cả khán phòng.</p>
<p>Bác sĩ Nguyễn Văn Minh bước lên bục phát biểu, điều chỉnh chiếc micro và mở tập hồ sơ bệnh án có đóng dấu đỏ chót của bệnh viện. Giọng nói của vị bác sĩ Tây y chuyên nghiệp vang lên trầm ấm, rõ ràng qua hệ thống loa công suất lớn: <i>"Chào các quý vị phóng viên. Với tư cách là đại diện chuyên môn y tế của Bệnh viện Chợ Rẫy và Viện Pasteur TP.HCM, tôi xin chính thức công bố kết quả xét nghiệm lâm sàng và độc chất học đối với năm bệnh nhân nhập viện đêm thứ Sáu vừa qua. Kết quả kiểm nghiệm máu và dịch dạ dày cho thấy các bệnh nhân bị ngộ độc bởi Methamidophos – một loại thuốc trừ sâu lân hữu cơ cực độc đã bị cấm sử dụng tại Việt Nam từ lâu. Nhờ được đưa vào viện cấp cứu kịp thời và tiến hành quy trình rửa ruột lâm sàng ngay lập tức, hiện tại toàn bộ năm bệnh nhân đã qua cơn nguy kịch, các chỉ số men gan và chức năng thận đã ổn định hoàn toàn."</i>.</p>
<p>Ông lật sang trang tiếp theo của tập tài liệu, ánh mắt nghiêm nghị nhìn xuống toàn thể hội trường: <i>"Tuy nhiên, điều đặc biệt nằm ở kết quả xét nghiệm hóa học đối với các mẫu ly trà sữa Mộc Trà được thu giữ trực tiếp tại hiện trường. Kết quả phân tích sắc ký khí và khối phổ (GC-MS) khẳng định: độc chất Methamidophos chỉ được tìm thấy với nồng độ cực cao ở phần nắp nhựa, ống hút và lớp bọt kem sữa ở bề mặt trên cùng của ly trà. Trong khi đó, toàn bộ phần cốt trà sữa sâu bên dưới hoàn toàn sạch sẽ, đạt chuẩn organic 100% và không có bất kỳ dấu vết nào của chất độc. Về mặt lâm sàng y học, điều này chứng tỏ chất độc chỉ được đưa vào ly trà từ bên ngoài sau khi ly trà đã được pha chế hoàn chỉnh và đóng nắp kín bằng màng PE."</i>.</p>
<p>Cả khán phòng bùng nổ những tiếng xì xào bàn tán xôn xao. Lâm Quốc Hùng ngồi dưới đột nhiên biến sắc, nụ cười trên môi hắn đông cứng lại, những giọt mồ hôi lạnh bắt đầu rịn ra trên trán và chảy dài xuống má. Quân lạnh lùng bước lên bục, bấm nút kích hoạt màn hình LED khổng lồ phía sau sân khấu. Trên màn hình xuất hiện giao diện truy xuất nguồn gốc Blockchain của lô trà sữa gây tranh cãi ngày hôm đó. Quân dõng dạc nói lớn vào micro: <i>"Mộc Trà của chúng tôi vận hành trên nền tảng Blockchain công khai. Khi khách hàng quét mã QR trên ly trà, họ có thể tự mình kiểm tra toàn bộ lịch sử cung ứng bất biến này. Lô trà này được hái tại đồi chè hữu cơ Bảo Lộc vào lúc sáu giờ sáng ngày 15/5, được đóng gói và mã hóa hàm băm SHA-256 ngay tại ruộng. Quá trình vận chuyển về Sài Gòn bằng xe đông lạnh được giám sát liên tục bằng cảm biến IoT. Biểu đồ nhiệt độ luôn duy trì ổn định ở mức 4 độ C dẫu đi qua đèo Bảo Lộc đầy sương mù. Mọi dữ liệu đều được lưu trữ phi tập trung trên hàng chục node mạng độc lập, không một ai có thể thay đổi dữ liệu lịch sử này!"</i>.</p>
<p>Anh ngừng lại một chút, ánh mắt sắc lẹm như dao cạo nhìn thẳng về phía Lâm Quốc Hùng đang run rẩy dưới hàng ghế đầu: <i>"Và để chứng minh cho lời nói của mình, tôi xin công bố bằng chứng cuối cùng: đoạn video camera an ninh độ phân giải 4K đặt ẩn tại khu vực giao nhận hàng của chi nhánh Quận 3."</i>. Trên màn hình LED lớn, đoạn video bắt đầu phát. Hình ảnh hiển thị rõ nét một nhân viên pha chế mới tuyển dụng (kẻ được Lâm Quốc Hùng mua chuộc từ trước) đang lén lút đứng sau quầy. Gã lén rút một chiếc xi-lanh nhỏ chứa dung dịch trong suốt từ trong tay áo ra, đâm nhanh qua lỗ cắm ống hút trên nắp của các ly trà sữa hữu cơ trân châu hoàng kim rồi bơm chất lỏng vào bên trong, ngay trước khi bưng ra bàn phục vụ cho nhóm khách hàng dàn dựng. Đoạn video quay cận cảnh khuôn mặt của gã nhân viên phản bội và hành động tội ác không thể chối cãi. Khán phòng hoàn toàn câm lặng trong vài giây trước khi bùng nổ thành một trận động đất truyền thông thực sự!</p>"""

    # Chapter 5 (Let's make it ~1200 words)
    chap5_title = "Chương 5: Vương Quốc Trà Hữu Cơ"
    chap5_content = """<p>Lâm Quốc Hùng mặt cắt không còn một giọt máu, toàn thân run rẩy như cầy sấy. Hắn lập tức đứng bật dậy, đẩy ngã chiếc ghế tựa định luồn lách qua đám đông phóng viên để chạy trốn ra ngoài qua lối cửa thoát hiểm phía sau khán phòng. Thế nhưng, cánh cửa lớn bằng gỗ gõ đỏ của hội trường khách sạn Rex đột ngột bị đẩy mạnh ra từ bên ngoài. Một nhóm sáu chiến sĩ công an sắc phục chỉnh tề thuộc Cục Cảnh sát điều tra tội phạm về tham nhũng, kinh tế, buôn lậu (C03 Bộ Công An) bước vào, chặn đứng lối thoát của hắn.</p>
<p>Dẫn đầu đoàn công tác là Thượng tá Nguyễn Tiến Dũng. Ông lạnh lùng bước tới trước mặt Lâm Quốc Hùng, rút tấm thẻ ngành cùng quyết định tố tụng có đóng dấu đỏ của Viện Kiểm sát Nhân dân Tối cao: <i>"Anh Lâm Quốc Hùng, chúng tôi đọc lệnh bắt giữ khẩn cấp đối với anh về hành vi hủy hoại sản xuất của doanh nghiệp khác, vu khống bôi nhọ danh dự tổ chức và cố ý gây thương tích bằng độc chất hóa học theo Điều 134 Bộ luật Hình sự. Toàn bộ chứng cứ số từ mạng Blockchain của Mộc Trà và dữ liệu camera an ninh đã được chúng tôi niêm phong, giám định tư pháp hoàn tất từ đêm qua. Đề nghị anh đi theo chúng tôi về trụ sở làm việc."</i>.</p>
<p>Đầu gối của Lâm Quốc Hùng quỳ sụp xuống sàn gạch bông bóng loáng kêu cộp trước ống kính máy quay của hàng trăm cơ quan thông tấn. Mặt hắn xám ngoét như tro tàn, miệng lắp bắp không thành tiếng, nước mắt và mồ hôi đầm đìa: <i>"Quân... Quân ơi, tao sai rồi! Xin mày nói với công an một tiếng tha cho tao... Tao bị tập đoàn ngoại bang GigaTea ép buộc thôi... Họ hứa sẽ cho tao 10% cổ phần nếu phá sập được Mộc Trà... Xin mày tha thứ cho tao!"</i>. Quân chỉ lặng lẽ đứng trên bục cao nhìn xuống, ánh mắt lạnh lùng không một chút gợn sóng hay thương hại. Kẻ ác gieo gió gặt bão, cái giá phải trả cho lòng tham và thủ đoạn đê hèn luôn là vô cùng đắt đỏ. Hắn đã quên mất rằng, danh dự của người làm trà Việt không thể đong đếm bằng những đồng tiền bẩn thỉu.</p>
<p>Giữa tiếng vỗ tay rầm rộ vang dội khắp khán phòng lớn, Lê Mỹ An bước lên bục phát biểu đầy kiêu hãnh dưới ánh đèn sân khấu rực rỡ và những tràng pháo tay không ngớt của giới đầu tư Sài Gòn. Cô cầm chiếc micro, dõng dạc tuyên bố trước toàn thể công chúng: <i>"Kính thưa các quý vị và giới truyền thông. Quỹ đầu tư mạo hiểm An Bình Capital của chúng tôi hôm nay chính thức đặt bút ký kết hợp đồng hợp tác chiến lược và rót vốn đầu tư vòng Series A trị giá 50 tỷ đồng đổi lấy 20% cổ phần của chuỗi trà sữa organic Mộc Trà, định giá doanh nghiệp ở mức 250 tỷ đồng. Chúng tôi tin tưởng tuyệt đối vào lý tưởng nâng tầm nông sản Việt, đạo đức kinh doanh kiên định và đặc biệt là hệ thống công nghệ Blockchain đột phá mà anh Trần Minh Quân đã tiên phong ứng dụng."</i>.</p>
<p>Khoản tiền khổng lồ 50 tỷ đồng ngay lập tức được chuyển khoản thành công từ tài khoản Techcombank của quỹ An Bình Capital sang tài khoản Vietcombank của Công ty Mộc Trà. Tiếng chuông báo tin nhắn điện thoại của Quân rung lên bần bật báo số dư tăng vọt trước sự chứng kiến trực tiếp của đại diện hai chi nhánh ngân hàng lớn có mặt tại buổi lễ ký kết. Sự kiện này không chỉ đè bẹp hoàn toàn chiến dịch bôi nhọ của tập đoàn ngoại bang GigaTea, mà còn biến cuộc khủng hoảng của Mộc Trà thành một chiến dịch tiếp thị miễn phí vĩ đại nhất năm. Công chúng nhận ra Mộc Trà chính là nạn nhân của một âm mưu hèn hạ, và lòng tin vào sản phẩm sạch, ứng dụng blockchain càng trở nên son sắt hơn bao giờ hết.</p>
<p>Chỉ trong vòng một tuần sau buổi họp báo, doanh số của toàn hệ thống Mộc Trà bùng nổ tăng vọt gấp mười lần thường lệ. Người dân Sài Gòn xếp hàng dài dằng dặc từ Quận 3 sang Quận 10 dưới lòng đường Cao Thắng và Sư Vạn Hạnh để được cầm trên tay ly trà sữa organic có dán mã QR truy xuất nguồn gốc minh bạch. Các xe hàng từ Bảo Lộc liên tục đổ về kho tổng Quận 10 dưới sự giám sát nghiêm ngặt của lực lượng bảo vệ mới. Tiếng chuông cửa kính kêu tinh tinh, tiếng máy xay đá bào organic chạy ro ro hòa cùng nụ cười hạnh phúc của đội ngũ nhân viên trẻ tuổi. Mộc Trà không chỉ đứng vững trước giông bão mà còn vươn lên mạnh mẽ hơn bao giờ hết.</p>
<p>Quân quay sang nhìn Mỹ An, cô gái tài sắc vẹn toàn đang mỉm cười dịu dàng nhìn anh với ánh mắt đầy ấm áp và kiêu hãnh. Dưới sự hậu thuẫn tài chính mạnh mẽ của quỹ đầu tư lớn và sự đồng hành trọn đời tự nguyện của Mỹ An, Mộc Trà không chỉ củng cố vững chắc vị thế "Vương quốc trà hữu cơ" thống trị thị trường Việt Nam mà còn sẵn sàng vươn cánh bay xa ra thị trường quốc tế Singapore và Đông Nam Á. Đêm hôm đó, đứng trên ban công lộng gió nhìn xuống toàn cảnh Sài Gòn phồn hoa rực rỡ sắc màu, Quân khẽ ôm lấy đôi vai thon nhỏ của Mỹ An. Hai người nắm chặt tay nhau, ly trà ô long ấm trên tay tỏa hương thơm ngát hòa vào không gian thoáng đạt, cùng hướng về một chương mới đầy vinh quang và hạnh phúc rộng lớn phía trước.</p>"""

    chapters = [
        {"title": chap1_title, "content": chap1_content},
        {"title": chap2_title, "content": chap2_content},
        {"title": chap3_title, "content": chap3_content},
        {"title": chap4_title, "content": chap4_content},
        {"title": chap5_title, "content": chap5_content}
    ]

    novel = {
        "title": title,
        "author": author,
        "genre": genre,
        "intro": intro,
        "cover_prompt": cover_prompt,
        "chapters": chapters
    }

    # Verify word count per chapter
    print("Verification of Word Counts (Vietnamese words are space-separated tokens):")
    for i, ch in enumerate(chapters):
        # strip html tags to count words accurately
        import re
        clean_text = re.sub('<[^<]+?>', '', ch['content'])
        words = clean_text.split()
        print(f"Chapter {i+1}: {len(words)} words ({len(ch['content'])} characters with HTML)")
        if len(words) < 1000 or len(words) > 1500:
            print(f"⚠️ Warning: Chapter {i+1} word count {len(words)} is not in 1000-1500 range!")

    output_path = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_novel.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(novel, f, ensure_ascii=False, indent=2)
    print(f"Successfully saved to {output_path}")

if __name__ == "__main__":
    generate()
