import json
import os

# Định nghĩa các chương dưới dạng danh sách các câu ngắn gọn theo chuẩn V12
# Mỗi câu sẽ được bọc trong thẻ <p>...</p>\n

ch1_sentences = [
    "Cơn mưa rào trút xuống trung tâm Thành Tâm xối xả như trút nước.",
    "Đại lộ Hai Bà Trưng ngập tràn trong ánh đèn neon nhấp nháy từ các tòa nhà chọc trời.",
    "Bên ngoài khách sạn năm sao Park Hyatt Saigon, thảm đỏ sang trọng đã được trải dài từ sảnh đón khách ra đến sát vỉa hè.",
    "Từng chiếc xe siêu sang nối đuôi nhau đỗ xịch trước cổng chào lộng lẫy.",
    "Những chiếc Mercedes-Maybach, Porsche Panamera và Bentley Continental GT bóng loáng phản chiếu ánh đèn chùm pha lê rực rỡ.",
    "Giới thượng lưu Thành Tâm hôm nay đổ dồn về đây để tham dự lễ cưới thế kỷ của Lê Gia.",
    "Đó là hôn lễ của Lê Huy, người thừa kế duy nhất của tập đoàn dệt may Lê Gia danh tiếng.",
    "Trong góc tối của sảnh đón khách, một cô gái trẻ đứng nép mình bên cạnh cột đá cẩm thạch lớn.",
    "Cô mặc một chiếc áo khoác jeans bạc màu, chiếc nón lá cũ kỹ hơi sụp xuống che khuất nửa khuôn mặt.",
    "Trên tay cô là một giỏ mây đựng những bông hoa hồng màu đỏ nhung đậm đà.",
    "Đó là Phạm Thị Hương, hai mươi chín tuổi.",
    "Không ai có thể ngờ rằng, cô gái có vẻ ngoài lam lũ này lại chính là Chủ tịch kiêm CEO của Tập đoàn nông nghiệp công nghệ cao GreenFlora.",
    "GreenFlora là một đế chế xuất khẩu hoa hữu cơ khổng lồ, sở hữu hàng trăm hecta nhà kính thông minh tại vùng cao nguyên Hội Nguyên.",
    "Hôm nay, Hương cải trang thành một người bán hoa hồng dạo ngoài sảnh tiệc.",
    "Cô muốn trực tiếp quan sát phản ứng của giới thượng lưu đối với giống hoa hồng organic mới nhất của mình.",
    "Đây là giống hoa hồng có tên thương mại là 'Eternal Grace', thành quả của năm năm nghiên cứu R&D liên tục.",
    "Eternal Grace có khả năng chống chọi sâu bệnh tuyệt vời và giữ tươi đến mười lăm ngày không cần hóa chất.",
    "Cô cần những dữ liệu thị trường thực tế cuối cùng này để chuẩn bị cho buổi IPO lịch sử của GreenFlora vào sáng nay.",
    "Bên cạnh cô là dòng người tấp nập bước qua, ai nấy đều khoác trên mình những bộ đồ hiệu đắt tiền.",
    "Họ nhìn cô bằng ánh mắt dò xét, đầy vẻ kỳ thị đối với một người bán hàng dạo ở nơi sang trọng.",
    "Hương không bận tâm đến những ánh mắt đó, cô chỉ tập trung ghi chép lại cách họ ngắm nhìn những đóa hoa mẫu thử.",
    "Bỗng nhiên, một chiếc Lexus LS500h đời mới nhất màu đen bóng đỗ xịch trước thảm đỏ.",
    "Cửa xe mở ra, một người phụ nữ trung niên sang trọng bước xuống.",
    "Bà ta mặc chiếc áo dài nhung đen thêu chỉ vàng quý phái, tay đeo chiếc nhẫn kim cương năm carat lấp lánh.",
    "Đó chính là bà Nguyễn Thị Liên, năm mươi lăm tuổi, mẹ của Lê Huy.",
    "Bà Liên đi cùng cô dâu mới của con trai mình, Vy, một thiên kim tiểu thư kiêu ngạo của chuỗi bán lẻ nội địa.",
    "Vy liếc nhìn giỏ hoa của Hương và che mũi đầy vẻ ghê tởm.",
    "\"Mẹ xem kìa, khách sạn năm sao sao lại để loại người bán hoa dạo bẩn thỉu này đứng đây?\"",
    "\"Lễ cưới của chúng ta toàn khách quý, nhìn cô ta thật là mất mỹ quan.\"",
    "Bà Liên quay sang nhìn, gương mặt bà ta lập tức biến dạng khi nhận ra Hương dưới vành nón lá.",
    "Ba năm trước, Hương và Lê Huy từng yêu nhau thắm thiết khi cô còn là sinh viên nghèo ngành Công nghệ sinh học.",
    "Bà Liên đã đích thân ném tập chi phiếu năm mươi triệu đồng vào mặt Hương, sỉ nhục gia thế nghèo hèn của cô và đuổi cô đi.",
    "\"Hương? Là cô sao?\" - Giọng bà Liên rít qua kẽ răng, tràn đầy sự khinh bỉ.",
    "\"Cô mò đến tận đây làm gì? Định phá hoại đám cưới của con trai tôi để tống tiền sao?\"",
    "\"Hạng người nghèo hèn như cô thì cả đời cũng chỉ đáng đi bán hoa dạo lề đường mà thôi.\"",
    "Hương khẽ ngẩng đầu lên, ánh mắt cô lạnh lùng như giếng cổ không một chút gợn sóng.",
    "\"Tôi chỉ đang khảo sát thị trường hoa tươi, không hề có hứng thú với đám cưới của các người.\"",
    "\"Thành phố Thành Tâm rất rộng lớn, không phải nơi nào cũng thuộc về Lê Gia các người.\"",
    "Lê Huy từ phía sau bước tới, diện bộ tuxedo đặt may riêng trị giá hàng ngàn đô la.",
    "Nhưng khi nhìn thấy Hương, ánh mắt anh ta chỉ có sự lẩn tránh và khó chịu tột cùng.",
    "\"Hương, em đi đi, đừng làm tôi xấu hổ trước mặt gia đình Vy nữa.\"",
    "\"Chúng ta đã kết thúc từ lâu rồi, em có cầu xin cũng vô ích mà thôi.\"",
    "\"Lê Gia là hào môn, em không thể trèo cao được đâu.\"",
    "Nghe những lời cạn tình của người yêu cũ, ngón tay Hương khẽ siết chặt vào quai giỏ mây.",
    "Móng tay cô bấm sâu vào lòng bàn tay đến mức rỉ ra một giọt máu đỏ tươi ấm nóng.",
    "Một luồng mồ hôi lạnh chảy dài sau gáy cô dưới làn gió điều hòa lạnh buốt của sảnh khách sạn.",
    "Cô không oán giận, chỉ cảm thấy một sự ghê tởm sâu sắc đối với sự hèn nhát của người đàn ông này.",
    "Bà Liên thấy Hương im lặng, càng thêm lấn lướt và hung hăng.",
    "\"Đồ con gái không có giáo dục, cút ngay cho tôi!\"",
    "Vy giật lấy giỏ hoa hồng 'Eternal Grace' trong tay Hương và cười chế giễu.",
    "\"Hoa hồng gì mà cánh hoa thô ráp thế này, chắc chắn là loại hoa cỏ dại ven đường mang về nhuộm phẩm màu.\"",
    "\"Thứ hoa rẻ tiền này mang vào tiệc cưới chỉ làm bẩn không khí sang trọng ở đây.\"",
    "Bà Liên không tiếc lời sỉ nhục, giật phắt giỏ hoa từ tay Vy rồi ném mạnh xuống đất.",
    "Chiếc giỏ mây lộn nhào, những đóa hồng hữu cơ quý giá vương vãi trên nền thảm đỏ đẫm nước mưa.",
    "Bà Liên nhấc gót giày cao gót nhọn hoắt của mình, giẫm đạp điên cuồng lên những cánh hoa hồng nhung tội nghiệp.",
    "Cánh hoa nát bấy, dịch hoa màu đỏ thẫm hòa cùng bùn đất và nước mưa chảy tràn trên thảm đỏ.",
    "\"Nhìn xem, thứ hoa rác rưởi của cô cũng chỉ đáng nằm dưới gót giày của tôi mà thôi!\"",
    "Đám đông khách mời xung quanh bắt đầu chỉ trỏ và xì xầm bàn tán cười nhạo Hương.",
    "Họ thích thú khi thấy một kẻ nghèo khổ bị hào môn chà đạp.",
    "Hương khẽ cúi đầu nhìn những bông hoa nát dưới đất.",
    "Đây là thành quả của hàng ngàn giờ lao động của các kỹ sư nông nghiệp hàng đầu tại Hội Nguyên.",
    "Cô khẽ thở ra một hơi, lồng ngực phập phồng nhưng ánh mắt đã chuyển sang sự sắc lạnh tột cùng.",
    "\"Bà Liên, Lê Huy. Các người có biết bản thân vừa giẫm nát thứ gì không?\"",
    "\"Đây là giống hoa hồng hữu cơ đã được cấp bằng bảo hộ sở hữu trí tuệ toàn cầu của GreenFlora.\"",
    "\"Giỏ hoa này là hàng mẫu đặc biệt phục vụ cho buổi ký kết IPO sáng nay.\"",
    "\"Trị giá tổn thất của nó không chỉ là vài cành hoa, mà là uy tín thương hiệu trị giá mười triệu USD.\"",
    "\"Lê Gia các người hãy chuẩn bị hầu tòa và đền bù thiệt hại này đi.\"",
    "Bà Liên cười phá lên như thể nghe thấy một câu chuyện đùa nực cười nhất thế gian.",
    "\"Ha ha! Mười triệu USD? Cô bị điên rồi đúng không?\"",
    "\"Một đứa bán hoa dạo đầu óc có vấn đề, bảo vệ đâu? Đuổi cổ nó ra ngoài ngay cho tôi!\"",
    "Hai nhân viên bảo vệ của khách sạn Park Hyatt bước tới với vẻ mặt ái ngại nhưng đầy nghiêm nghị.",
    "Hương không hề nao núng, cô đứng thẳng lưng, phong thái kiêu hãnh như một nữ hoàng.",
    "Đúng lúc đó, một chiếc Rolls-Royce Phantom màu đen bóng loáng đỗ xịch ngay trước sảnh thảm đỏ.",
    "Chiếc xe mang biển số VIP của Thành Tâm, thu hút mọi ánh nhìn của quan khách.",
    "Cửa xe mở ra, hai hàng vệ sĩ mặc suit đen sang trọng nhanh chóng bước xuống lập thành hàng rào bảo vệ.",
    "Một người đàn ông trẻ tuổi bước ra từ ghế sau, phong thái đĩnh đạc và đầy quyền lực.",
    "Anh ta mặc bộ vest màu xám tro của hãng Brioni lịch lãm, mái tóc chải chuốt gọn gàng.",
    "Đó chính là Trần Minh Anh, ba mươi ba tuổi, Giám đốc điều hành mảng Ngân hàng Đầu tư của CTCK Bản Việt (VCSC).",
    "Minh Anh lướt mắt qua hiện trường, nhìn thấy những cành hoa nát dưới đất và Hương đang đứng đó.",
    "Anh ta lập tức sải bước tiến về phía cô, cúi đầu chào một cách đầy kính cẩn trước sự chứng kiến của tất cả mọi người.",
    "\"Chủ tịch Phạm, xe đã chuẩn bị xong, các thành viên Hội đồng quản trị và đại diện Sở Giao dịch đang đợi cô ở phòng họp VIP.\"",
    "\"Chúng ta chỉ còn đúng hai tiếng trước khi tiếng chuông niêm yết của GreenFlora bắt đầu.\"",
    "Lời nói của Minh Anh như một tiếng sét đánh ngang tai giữa bầu không khí yên lặng của sảnh tiệc.",
    "Bà Liên nghẹn họng, gương mặt quý phái bỗng chốc cứng đờ, đôi mắt trợn ngược lên vì kinh ngạc.",
    "Lê Huy cũng lùi lại một bước, mặt cắt không còn giọt máu, miệng lắp bắp không thành tiếng.",
    "\"Trần... Trần tổng? Anh gọi cô ta là gì?\"",
    "Minh Anh không thèm nhìn Lê Huy, chỉ lạnh lùng chỉnh lại tay áo của mình.",
    "\"Đây chính là Chủ tịch Phạm Thị Hương của Tập đoàn Vạn Hoa GreenFlora, đơn vị sắp niêm yết với định giá ba ngàn tỷ đồng ngày hôm nay.\"",
    "\"Lê Gia các người có gan lớn lắm, dám phá hoại tài sản mẫu thử của đợt IPO này.\"",
    "Hương khẽ rút một chiếc khăn giấy từ túi áo, nhẹ nhàng lau đi vệt máu rỉ trên lòng bàn tay mình.",
    "Cô quay sang nhìn bà Liên và Lê Huy bằng ánh mắt thương hại tột cùng.",
    "\"Lễ cưới của các người cứ tiếp tục đi.\"",
    "\"Nhưng tôi e rằng, sau ngày hôm nay, Lê Gia sẽ không còn tiền để thanh toán chi phí cho sảnh tiệc này nữa đâu.\"",
    "Hương quay lưng bước đi, gót giày của cô giẫm lên nền thảm đỏ một cách dứt khoát và kiêu hãnh.",
    "Minh Anh nhanh chóng mở cửa chiếc Rolls-Royce Phantom cho cô bước vào.",
    "Chiếc xe sang trọng từ từ lăn bánh, để lại phía sau một đám đông đang xôn xao kinh hoàng.",
    "Mẹ con bà Liên đứng chết trân dưới cơn mưa nặng hạt, trong lòng trào dâng một cảm giác bất an tột cùng.",
    "Họ không biết rằng, bánh xe của số phận đã bắt đầu quay, và Lê Gia sắp phải đối mặt với một cơn bão tài chính khủng khiếp."
]

ch2_sentences = [
    "Không gian bên trong chiếc Rolls-Royce Phantom yên tĩnh đến mức có thể nghe thấy tiếng gió rít nhẹ bên ngoài lớp kính cách âm hai lớp.",
    "Mùi hương gỗ đàn hương tự nhiên lan tỏa dịu nhẹ, xoa dịu đi bầu không khí căng thẳng vừa rồi.",
    "Trần Minh Anh lấy từ ngăn lạnh một chiếc khăn ấm, nhẹ nhàng đưa cho Hương.",
    "\"Chủ tịch Phạm, tay cô đang chảy máu.\"",
    "Hương khẽ giật mình, cô nhìn xuống lòng bàn tay right của mình.",
    "Nơi lòng bàn tay, bốn vết móng tay găm sâu vào da thịt, máu đỏ tươi đã bắt đầu đông lại thành những vệt thẫm.",
    "Cơn đau buốt lúc này mới thực sự truyền đến đại não, khiến đôi vai cô khẽ run lên.",
    "Cô nhận lấy chiếc khăn ấm từ tay Minh Anh, nhẹ nhàng lau đi vết máu lạnh buốt.",
    "\"Cảm ơn Trần tổng, tôi không sao.\"",
    "Giọng cô vẫn đều đều, lạnh lùng và bình thản như chưa từng có chuyện gì xảy ra.",
    "Minh Anh nhìn cô bằng ánh mắt đầy thâm trầm, trong lòng không khỏi dâng lên một sự nể phục sâu sắc.",
    "Anh đã gặp rất nhiều CEO lớn tuổi, nhưng chưa từng thấy một cô gái hai mươi chín tuổi nào có được sự nhẫn nhịn và kiên định đáng sợ như vậy.",
    "\"Đối với những kẻ ngu muội đó, cô không cần phải đích thân ra tay.\"",
    "\"After hôm nay, Bản Việt sẽ giúp cô thu dọn bọn họ.\"",
    "Hương khẽ nhếch môi, ánh mắt hướng ra ngoài cửa kính, nơi những tòa nhà chọc trời của Thành Tâm đang lướt nhanh qua.",
    "\"Bà Liên tưởng rằng đồng tiền của Lê Gia có thể đè bẹp tất cả.\"",
    "\"Bà ta không biết rằng, thời đại của dệt may truyền thống thâm dụng lao động đã hết.\"",
    "\"Nếu không có chuỗi cung ứng lạnh và công nghệ lai tạo giống độc quyền, Lê Gia chỉ là một cái vỏ rỗng.\"",
    "Chiếc xe Rolls-Royce dừng lại trước sảnh tòa nhà văn phòng hạng A+ Bitexco Financial Tower.",
    "Nơi đây chính là trụ sở của Công ty Cổ phần Chứng khoán Bản Việt (VCSC).",
    "Hai người nhanh chóng di chuyển bằng thang máy tốc độ cao lên tầng năm mươi hai, nơi đặt phòng họp VIP của ban lãnh đạo.",
    "Bầu không khí trong phòng họp cực kỳ trang nghiêm với dãy bàn gỗ mun dài và các trang thiết bị hội nghị trực tuyến hiện đại.",
    "Hồ sơ IPO dày cộp của Tập đoàn GreenFlora đã được xếp ngăn nắp trước mỗi chiếc ghế da.",
    "Thương vụ niêm yết này có quy mô lên tới một ngàn năm trăm tỷ đồng, là một trong những deal lớn nhất quý này của thị trường tài chính Việt Nam.",
    "Minh Anh bước đến vị trí chủ tọa, phong thái chuyên nghiệp và lạnh lùng của một tay chơi sừng sỏ trong giới đầu tư lập tức trở lại.",
    "Anh gõ nhẹ ngón tay xuống tập tài liệu dày cộp, ánh mắt sắc bén nhìn thẳng vào Hương.",
    "\"Chủ tịch Phạm, chúng ta chỉ còn đúng chín mươi phút trước giờ G.\"",
    "\"Mọi thủ tục với Ủy ban Chứng khoán Nhà nước và Sở Giao dịch HOSE đã hoàn tất.\"",
    "\"Tuy nhiên, điều khoản về mức phí bảo lãnh phát hành và quyền kiểm soát sau IPO vẫn cần phải chốt lại.\"",
    "\"Phía Bản Việt yêu cầu mức phí bảo lãnh phát hành cố định là hai phẩy năm phần trăm tổng giá trị IPO.\"",
    "\"Đây là mức phí hợp lý để đảm bảo việc phân phối thành công cho các quỹ đầu tư nước ngoài.\"",
    "\"Đồng thời, chúng tôi bắt buộc phải giữ một ghế trực tiếp trong Hội đồng quản trị của liên doanh xuất khẩu hoa công nghệ cao sang thị trường EU và Nhật Bản sau khi niêm yết.\"",
    "\"Đây là điều kiện tiên quyết để chúng tôi bảo vệ dòng vốn đầu tư mạo hiểm của các cổ đông tổ chức quốc tế.\"",
    "\"Chúng tôi cần có quyền kiểm soát rủi ro tài chính và vận hành của liên doanh này.\"",
    "Hương nghe xong, nét mặt không hề thay đổi, cô khẽ mỉm cười và dựa lưng vào ghế da cao cấp.",
    "Ngón tay trỏ của cô gõ nhịp nhàng xuống mặt bàn kính chịu lực, tạo ra những âm thanh cộc cộc đều đặn.",
    "\"Trần tổng, hai phẩy năm phần trăm là một con số quá cao đối với một tập đoàn có biên lợi nhuận ròng lên tới bốn mươi phần trăm như GreenFlora.\"",
    "\"Phí bảo lãnh phát hành trung bình của thị trường Việt Nam hiện nay chỉ dao động từ một phẩy năm đến hai phần trăm.\"",
    "\"Hơn nữa, quyền kiểm soát trực tiếp Hội đồng quản trị liên doanh là ranh giới đỏ của tôi.\"",
    "\"GreenFlora sở hữu một trăm phần trăm bản quyền sở hữu trí tuệ đối với ba giống hoa hồng organic chịu nhiệt đã đăng ký tại Hà Lan.\"",
    "\"Chúng tôi không thể để một tổ chức tài chính can thiệp sâu vào các quyết định kỹ thuật và bảo mật R&D của chúng tôi.\"",
    "Minh Anh khẽ nhướn mày, người hơi đổ về phía trước, tạo ra một áp lực vô hình trong phòng họp.",
    "Mồ hôi lạnh rỉ ra trên trán của các trợ lý pháp lý đứng xung quanh hai bên bàn đàm phán.",
    "\"Chủ tịch Phạm, cô phải hiểu rằng thị trường EU và Nhật Bản có những tiêu chuẩn kiểm dịch thực vật cực kỳ ngặt nghèo.\"",
    "\"Nếu không có sự bảo trợ tài chính và mạng lưới đối tác quốc tế của Bản Việt, chuỗi cung ứng lạnh của cô sẽ gặp khó khăn lớn khi thông quan.\"",
    "\"Hai phẩy năm phần trăm phí bảo lãnh phát hành là hoàn toàn xứng đáng cho sự an toàn đó.\"",
    "\"Chúng tôi mang lại giá trị gia tăng vượt trội chứ không chỉ là tiền bạc.\"",
    "Hương không hề chớp mắt, cô nhìn thẳng vào đôi mắt sắc bén của Minh Anh với một bản lĩnh sòng phẳng tột cùng.",
    "\"Tôi chấp nhận mức phí hai phẩy năm phần trăm với một điều kiện đi kèm.\"",
    "\"Bản Việt phải ký cam kết hỗ trợ toàn bộ chuỗi cung ứng lạnh cold chain logistics kết nối trực tiếp với các hãng hàng không vận tải chuyên dụng sang châu Âu.\"",
    "\"Các người phải đảm bảo thời gian vận chuyển từ nhà kính Hội Nguyên đến Frankfurt không quá ba mươi sáu tiếng.\"",
    "\"Về chiếc ghế trong Hội đồng quản trị liên doanh, tôi chỉ có thể trao cho Bản Việt quyền biểu quyết tài chính, không có quyền phủ quyết đối với quy trình kỹ thuật R&D.\"",
    "\"Quy trình lai tạo giống hoa hồng Eternal Grace là tài sản trí tuệ độc quyền của GreenFlora, không ai được phép chạm vào.\"",
    "\"If Trần tổng không đồng ý, tôi sẵn sàng dừng buổi IPO này ngay lập tức.\"",
    "\"Tập đoàn nông nghiệp quốc tế của Singapore đã sẵn sàng mua lại ba mươi phần trăm cổ phần của chúng tôi với định giá cao hơn.\"",
    "Lời nói của Hương đanh thép, từng từ từng chữ vang lên như búa gõ vào lòng ngực những người có mặt.",
    "Minh Anh chăm chú nhìn cô gái trước mặt, bàn tay anh vô thức miết chặt lên mặt giấy hợp đồng dày cộp.",
    "Sự im lặng bao trùm phòng họp suốt ba mươi giây dài đằng đẵng như cả thế kỷ.",
    "Minh Anh bỗng chốc bật cười nhẹ, ánh mắt tràn đầy sự tán thưởng và khuất phục trước trí tuệ và sự kiên định của cô.",
    "\"Chủ tịch Phạm quả thực rất sòng phẳng và sắc sảo.\"",
    "\"Tôi đồng ý với điều kiện của cô.\"",
    "\"Bản Việt sẽ đồng hành cùng GreenFlora với tư cách là đối tác chiến lược tôn trọng quyền sở hữu trí tuệ.\"",
    "\"Chúng ta sẽ ký bản phụ lục hợp đồng này ngay lập tức để kịp giờ niêm yết.\"",
    "Hương khẽ thở phào nhẹ nhõm, nhưng cô vẫn giữ nguyên nụ cười tự tin và bản lĩnh trên môi.",
    "Cô cầm chiếc bút máy Montblanc bằng vàng ròng, ký tên mình lên bản hợp đồng bằng những nét vẽ dứt khoát và kiêu hãnh.",
    "Bản hợp đồng tỷ đô chính thức được thiết lập, đặt viên gạch vững chắc cho đế chế hoa tươi công nghệ cao vươn ra toàn cầu."
]

ch3_sentences = [
    "Đúng chín giờ sáng, không khí tại văn phòng VIP của Sở Giao dịch Chứng khoán Thành Tâm trở nên căng thẳng tột độ.",
    "Chỉ còn đúng hai tiếng nữa là đến thời khắc gõ chuông khai mạc phiên giao dịch lịch sử của GreenFlora.",
    "Các kỹ thuật viên đang kiểm tra lại hệ thống bảng điện tử và đường truyền dữ liệu trực tuyến.",
    "Đột nhiên, chiếc điện thoại chuyên dụng của Hương trên bàn họp rung lên bần bật.",
    "Màn hình hiện lên số gọi từ Hội Nguyên, đầu cầu trung tâm sản xuất của tập đoàn.",
    "Hương nhấn nút nghe, ngay lập tức, tiếng la hét hoảng loạn của Hoàng, Giám đốc sản xuất đầu cầu Hội Nguyên vang lên chói tai.",
    "\"Chủ tịch Phạm! Xảy ra chuyện lớn rồi!\"",
    "\"Hệ thống điện trung tâm của tổng kho lạnh bỗng nhiên bị cắt hoàn toàn!\"",
    "\"Nhiệt độ trong mười container chứa năm triệu cành hoa hồng Eternal Grace xuất khẩu đi Tokyo đang tăng lên vùn vụt!\"",
    "\"Hiện tại nhiệt độ đã tăng từ hai độ C lên đến sáu độ C!\"",
    "\"Nếu vượt quá bốn độ C trong vòng một tiếng, toàn bộ cành hoa sẽ bị héo úa và rụng cánh trước khi kịp lên máy bay!\"",
    "\"Chúng ta sẽ mất trắng mười triệu USD và đối mặt với khoản phạt vi phạm hợp đồng khổng lồ từ các đối tác Nhật Bản!\"",
    "\"Hơn nữa, uy tín sở hữu trí tuệ của chúng ta với khách hàng quốc tế sẽ hoàn toàn bị hủy hoại!\"",
    "Nghe tiếng khóc lóc đầy bất lực của Hoàng, các thành viên Hội đồng quản trị trong phòng họp mặt mày xám ngoét.",
    "Mồ hôi lạnh chảy ròng ròng sau gáy của mọi người, không khí ngột ngạt đến mức khó thở.",
    "Thương vụ IPO trị giá một ngàn năm trăm tỷ đồng có nguy cơ sụp đổ hoàn toàn trước khi kịp bắt đầu.",
    "Hương hít một hơi thật sâu, ngón tay cô bóp chặt chiếc bút máy đến mức các khớp xương kêu răng rắc.",
    "Nhưng gương mặt cô vẫn giữ được sự bình tĩnh đến đáng sợ, ánh mắt sắc lẹm như dao cạo.",
    "\"Hoàng, anh nghe rõ lệnh của tôi, tuyệt đối không được hoảng loạn!\"",
    "\"Hãy lập tức kích hoạt hệ thống điện dự phòng độc lập từ các tấm pin mặt trời áp mái năm trăm kW tại khu nhà kính R&D!\"",
    "\"Hệ thống này được trang bị công nghệ điều biến lưới điện cục bộ mà tôi đã đăng ký sáng chế độc quyền năm ngoái!\"",
    "\"Nó có thể tự động cô lập lưới điện bị hỏng và cấp nguồn trực tiếp cho tổng kho lạnh trong vòng ba mươi giây!\"",
    "Đầu dây bên kia, Hoàng vội vàng gạt mồ hôi lạnh, chạy đi thực hiện mệnh lệnh của cô.",
    "\"Nhưng thưa Chủ tịch, hệ thống pin mặt trời chỉ có thể duy trì được tối đa bốn mươi lăm phút trong điều kiện thời tiết nhiều mây ở Hội Nguyên hôm nay!\"",
    "\"Chúng ta vẫn cần nguồn điện lưới ổn định hoặc các container lạnh dự phòng khẩn cấp!\"",
    "Hương quay sang nhìn Trần Minh Anh, người cũng đang nhíu mày suy nghĩ đầy căng thẳng.",
    "\"Trần tổng, tôi cần sự hỗ trợ của Bản Việt ngay lập tức.\"",
    "\"Đây chắc chắn là một âm mưu chơi bẩn có chủ đích.\"",
    "\"Nhà cung cấp thiết bị lạnh Nam Phong Logistics chính là công ty con vừa được Lê Gia mua lại tuần trước.\"",
    "\"Họ đã cố tình cắt điện lưới trung tâm và chặn các xe bảo trì của chúng ta vào khu công nghệ cao Hội Nguyên.\"",
    "\"Tôi cần anh điều động đội xe container lạnh dự phòng của tập đoàn đối tác để trung chuyển hàng hóa khẩn cấp ra sân bay Liên Khương.\"",
    "Minh Anh lập tức hiểu ra tính nghiêm trọng của vấn đề, anh cầm điện thoại lên và gọi một cuộc gọi trực tiếp cho Chủ tịch Tập đoàn Vận tải Hàng không miền Nam.",
    "\"Alo, anh Sơn phải không? Tôi là Minh Anh đây.\"",
    "\"Tôi cần anh điều động gấp hai mươi xe container lạnh chuyên dụng đang túc trực tại sân bay Liên Khương di chuyển đến tổng kho GreenFlora ở Hội Nguyên ngay lập tức.\"",
    "\"Tất cả chi phí và trách nhiệm pháp lý Bản Việt sẽ đứng ra bảo lãnh toàn bộ.\"",
    "\"Làm việc này ngay trong vòng mười lăm phút! Chúng ta đang đua với thời gian!\"",
    "Cùng lúc đó, Hương mở chiếc iPad của mình ra, truy cập vào hệ thống dữ liệu sở hữu trí tuệ toàn cầu.",
    "Cô nhanh chóng soạn thảo một email khẩn cấp gửi cho Cục Sở hữu Trí tuệ và Bộ Công Thương tại Thành Tâm.",
    "\"Bà Liên tưởng rằng có thể dùng Nam Phong Logistics để bóp nghẹt chuỗi cung ứng của tôi sao?\"",
    "\"Nam Phong Logistics đang sử dụng công nghệ làm mát nhái lại sáng chế bộ điều biến nhiệt của GreenFlora đã được bảo hộ.\"",
    "\"Họ đã vận hành nhà kho bên cạnh với công suất quá tải để gián tiếp gây sụt áp lưới điện của chúng ta.\"",
    "\"Đây là hành vi vi phạm pháp luật sở hữu trí tuệ nghiêm trọng và phá hoại tài sản doanh nghiệp có tổ chức.\"",
    "\"Tôi yêu cầu các cơ quan chức năng lập tức phong tỏa nhà kho của Nam Phong để điều tra làm rõ.\"",
    "Điện thoại của Hương lại vang lên tiếng của Hoàng, giọng anh ta đã bớt run rẩy hơn.",
    "\"Chủ tịch! Hệ thống điện mặt trời dự phòng đã kích hoạt thành công!\"",
    "\"Nhiệt độ đã tạm thời đứng yên ở mức ba phẩy tám độ C, chưa vượt quá ngưỡng nguy hiểm!\"",
    "\"Đội xe container lạnh của Bản Việt cũng vừa áp sát vào sảnh kho lạnh, các công nhân đang nhanh chóng bốc xếp hoa lên xe!\"",
    "\"Chúng ta đã kiểm soát được tình hình rồi! Năm triệu cành hoa hồng đã an toàn!\"",
    "Cả phòng họp thở phào nhẹ nhõm, nhiều người ngồi phịch xuống ghế như vừa từ cõi chết trở về.",
    "Mồ hôi lạnh trên trán Hoàng dần khô đi, anh không ngớt lời cảm ơn sự quyết đoán của vị CEO trẻ tuổi.",
    "Minh Anh nhìn Hương với ánh mắt tràn đầy sự kinh ngạc và thán phục vô hạn.",
    "Sự kết hợp hoàn hảo giữa công nghệ R&D độc lập và phản ứng pháp lý nhanh nhạy của cô đã dập tắt cuộc khủng hoảng chỉ trong vòng bốn mươi lăm phút.",
    "Hương đóng chiếc iPad lại, đứng dậy chỉnh lại chiếc áo vest light beige sang trọng của mình.",
    "\"Lê Gia đã tung ra con bài tẩy cuối cùng của họ và thất bại thảm hại.\"",
    "\"Bây giờ, đến lượt chúng ta lên sàn giao dịch gõ chuông khai tử bọn họ.\"",
    "\"Hãy để thế giới thấy sức mạnh thực sự của một đế chế hoa tươi công nghệ cao.\"",
    "\"Mọi âm mưu hèn hạ sẽ phải quỳ gối trước trí tuệ và sự chuẩn bị kỹ lưỡng của chúng ta.\""
]

ch4_sentences = [
    "Sảnh chính của Sở Giao dịch Chứng khoán Thành Tâm (HOSE) ngập tràn trong ánh sáng trắng rực rỡ của các ngọn đèn spotlight.",
    "Bảng điện tử khổng lồ hiển thị hàng trăm mã chứng khoán xanh đỏ liên tục nhấp nháy chỉ số.",
    "Hôm nay là một ngày đặc biệt khi rất nhiều doanh nghiệp lớn và giới đầu tư tài chính túc trực từ sáng sớm.",
    "Trong số đám đông đó, bà Nguyễn Thị Liên và Lê Huy cũng đang đứng đợi ở khu vực sảnh chờ VIP dành cho doanh nghiệp nộp hồ sơ.",
    "Gương mặt bà Liên hiện rõ sự lo lắng, mồ hôi lạnh rỉ ra trên trán dù phòng điều hòa đang bật ở nhiệt độ thấp.",
    "Tập đoàn dệt may Lê Gia đang gặp khủng hoảng dòng tiền nghiêm trọng khi ngân hàng VietinBank đột ngột đình chỉ khoản vay bổ sung hai trăm tỷ đồng.",
    "Lý do ngân hàng đưa ra là Lê Gia đang vướng vào đơn kiện vi phạm bản quyền công nghệ lạnh và phá hoại tài sản của một tập đoàn lớn.",
    "Họ không ngờ rằng đơn kiện của GreenFlora lại có sức nặng pháp lý khủng khiếp đến như vậy.",
    "Bà Liên nắm chặt chiếc gậy chống nạm bạc, đôi môi run rẩy nói với con trai.",
    "\"Huy, con đã liên hệ được với người của Nam Phong Logistics chưa?\"",
    "\"Tại sao họ lại để xảy ra rắc rối pháp lý lớn như vậy vào đúng lúc này?\"",
    "Lê Huy nét mặt cũng đầy lo âu, anh ta liên tục bấm điện thoại nhưng đầu dây bên kia chỉ có tiếng thuê bao kéo dài.",
    "\"Con không liên lạc được với bọn họ, mẹ ạ.\"",
    "\"Hình như Cục Sở hữu Trí tuệ và lực lượng Quản lý Thị trường đã phong tỏa toàn bộ nhà kho của họ ở Hội Nguyên rồi.\"",
    "\"Mọi tài sản của họ đã bị niêm phong để điều tra hành vi phá hoại lưới điện của GreenFlora.\"",
    "Đúng lúc đó, một tiếng ồn ào lớn vang lên từ phía cửa chính của Sở Giao dịch.",
    "Một dàn vệ sĩ mặc suit đen sang trọng sải bước mở đường, tạo nên một lối đi rộng lớn giữa sảnh chính.",
    "Trần Minh Anh, Giám đốc điều hành mảng Ngân hàng Đầu tư của Bản Việt, đi bên cạnh hộ tống một cô gái trẻ.",
    "Bà Liên nheo mắt nhìn kỹ, rồi cả người bà ta bỗng chốc đông cứng lại như tượng đá.",
    "Cô gái đi bên cạnh Minh Anh mặc một bộ vest light beige sang trọng, mái tóc đen được búi cao quý phái.",
    "Từng bước đi của cô đều toát lên vẻ kiêu sa, tự tin và đầy uy quyền của một nhà lãnh đạo đỉnh cao.",
    "Đó chính là Phạm Thị Hương, người mà chỉ vài tiếng trước còn bị bà Liên giẫm nát giỏ hoa dưới gót giày.",
    "Bà Liên lẩm bẩm trong sự kinh hoàng tột độ, đôi môi mấp máy không thành tiếng.",
    "\"Hương? Tại sao nó lại ở đây?\"",
    "\"Lại còn đi cùng với Trần tổng của Bản Việt? Thật không thể tin nổi!\"",
    "Vy đứng bên cạnh khịt mũi một cái đầy khinh bỉ, cố gắng che giấu sự ghen tị đang bùng cháy trong lòng.",
    "\"Mẹ ơi, chắc chắn là con nhỏ đó ráng thuê xe sang và bám lấy Trần tổng để vào đây làm màu thôi!\"",
    "\"Một đứa bán hoa dạo thì làm sao có tư cách bước vào sảnh HOSE này!\"",
    "Nhưng lời nói của Vy chưa kịp dứt thì tiếng loa phóng thanh của Sở Giao dịch đã vang lên dõng dạc khắp đại sảnh.",
    "\"Xin trân trọng kính mời toàn thể quý quan khách và giới truyền thông di chuyển vào khán phòng chính để tham dự lễ niêm yết!\"",
    "\"Hôm nay, Sở Giao dịch Chứng khoán Thành Tâm vinh dự chào đón sự kiện niêm yết chính thức của Công ty Cổ phần Tập đoàn GreenFlora!\"",
    "\"Mã chứng khoán giao dịch chính thức: GFL!\"",
    "\"Xin trân trọng kính mời vị Chủ tịch kiêm Tổng giám đốc sáng lập - bà Phạm Thị Hương bước lên bục danh dự để thực hiện nghi thức gõ chuông!\"",
    "Tiếng loa vừa dứt, chiếc gậy chống nạm bạc trên tay bà Liên rơi xuống sàn gạch cộp một tiếng vang dội.",
    "Đầu gối bà ta run rẩy, cả người lảo đảo như sắp quỵ xuống đất nếu Lê Huy không kịp thời đỡ lấy.",
    "Lê Huy mặt cắt không còn giọt máu, đôi mắt trợn ngược lên nhìn bóng dáng Hương đang tự tin bước lên bục danh dự dưới ánh đèn flash của hàng chục phóng viên.",
    "Anh ta nhận ra rằng, người con gái mình từng ruồng bỏ nay đã ở một đẳng cấp hoàn toàn khác biệt.",
    "Hương đứng trước micro, phong thái kiêu hãnh ngút ngàn, cô bắt đầu bài phát biểu bằng tiếng Việt và tiếng Anh vô cùng trôi chảy.",
    "\"Kính thưa quý vị đại biểu, các cổ đông và đối tác quốc tế.\"",
    "\"GreenFlora không chỉ là một doanh nghiệp xuất khẩu hoa tươi đơn thuần.\"",
    "\"Chúng tôi là sự kết hợp giữa nông nghiệp hữu cơ bền vững và công nghệ sinh học độc quyền của người Việt.\"",
    "\"Với việc niêm yết ngày hôm nay, chúng tôi cam kết sẽ đưa thương hiệu hoa công nghệ cao của Việt Nam vươn tầm thế giới.\"",
    "Trần Minh Anh đứng dưới khán đài, giơ ngón tay cái chúc mừng cô với một nụ cười đầy tự hào.",
    "Hương cầm chiếc búa gỗ nạm vàng, nhìn thẳng xuống hàng ghế khán giả, nơi mẹ con bà Liên đang đứng chết trân.",
    "Cô dùng lực gõ mạnh xuống chiếc chuông đồng cổ kính ba tiếng vang dội: Cộp! Cộp! Cộp!",
    "Tiếng chuông ngân vang báo hiệu phiên giao dịch chính thức của mã GFL bắt đầu.",
    "Ngay lập tức, trên bảng điện tử khổng lồ, mã cổ phiếu GFL hiện lên sắc tím hoa cà rực rỡ.",
    "Mức giá mở cửa hai mươi tám ngàn đồng đã lập tức nhảy vọt lên mức giá trần ba mươi ba ngàn sáu trăm đồng, tăng kịch trần hai mươi phần trăm.",
    "Dòng lệnh mua khổng lồ của các quỹ đầu tư nước ngoài đổ vào quét sạch hàng triệu cổ phiếu trong vòng vài giây.",
    "Chỉ trong chớp mắt, vốn hóa của GreenFlora đã vượt ngưỡng ba ngàn tỷ đồng.",
    "Giá trị tài sản ròng cá nhân của Phạm Thị Hương, người nắm giữ bảy mươi lăm phần trăm cổ phần, tăng thêm hơn hai ngàn tỷ đồng chỉ sau một tiếng chuông.",
    "Lê Huy đứng dưới khán đài, hai đầu gối run rẩy khuỵu xuống đất, trong lòng tràn ngập sự hối hận và sợ hãi tột cùng.",
    "Anh ta nhận ra rằng, người con gái mà anh ta từng ruồng rẫy và khinh thường nay đã vươn lên thành một đỉnh núi mà cả đời anh ta cũng không thể chạm tới.",
    "Sức mạnh của trí tuệ, công nghệ và sự kiêu hãnh của cô đã chiến thắng hoàn toàn thế lực hào môn kiêu ngạo."
]

ch5_sentences = [
    "Khán phòng tiệc VIP của Sở Giao dịch Chứng khoán Thành Tâm tràn ngập tiếng nhạc champagne nhẹ nhàng và tiếng cười nói vui vẻ.",
    "Các nhà đầu tư lớn, đại diện ngân hàng và các quỹ ngoại liên tục tiến đến chúc mừng Phạm Thị Hương và Trần Minh Anh.",
    "GreenFlora đã có một buổi IPO thành công ngoài mong đợi, khẳng định vị thế dẫn đầu trong ngành nông nghiệp công nghệ cao.",
    "Giữa đám đông sang trọng đó, bà Nguyễn Thị Liên và Lê Huy chật vật chen lấn qua hàng rào bảo vệ để tiếp cận Hương.",
    "Gương mặt kiêu ngạo ngày thường của bà Liên giờ đây chỉ còn lại sự tái nhợt và hoảng loạn tột độ.",
    "Mái tóc quý phái của bà ta hơi rối loạn, chiếc áo dài nhung đen đắt tiền giờ trông thật thảm hại.",
    "Lê Huy đi bên cạnh, đôi mắt đỏ ngầu, người run bần bật như một kẻ mất hồn.",
    "\"Hương! Xin cô hãy cho tôi gặp Chủ tịch Phạm một phút thôi!\" - Giọng bà Liên khàn đặc, không còn chút kiêu căng nào.",
    "Hương khẽ quay người lại, ánh mắt cô lạnh lùng nhìn hai mẹ con họ qua mép ly champagne pha lê lấp lánh.",
    "Vệ sĩ của Sở Giao dịch ngay lập tức bước lên định ngăn cản, nhưng Hương khẽ giơ tay ra hiệu cho họ lùi lại.",
    "\"Bà Liên, Lê tổng. Có chuyện gì mà hai người phải vội vàng tìm tôi như vậy?\"",
    "Lê Huy nhìn thấy Hương đứng đó, kiêu sa và quyền lực, lòng tự trọng cuối cùng của anh ta hoàn toàn sụp đổ.",
    "Anh ta bước tới một bước, rồi quỳ sụp xuống sàn gạch cộp một tiếng vang dội trước sự kinh ngạc của những người xung quanh.",
    "\"Hương! Anh xin lỗi! Là anh có mắt không tròng!\"",
    "\"Anh vẫn luôn yêu em, tất cả là do mẹ anh ép buộc anh phải kết hôn với Vy!\"",
    "\"Xin em hãy nhớ đến tình nghĩa ba năm qua của chúng ta, hãy rút đơn kiện vi phạm bản quyền đối với Nam Phong Logistics!\"",
    "\"If em không rút đơn, VietinBank và BIDV sẽ phong tỏa toàn bộ tài sản của Lê Gia để thu hồi nợ trước hạn!\"",
    "\"Tập đoàn dệt may của gia đình anh sẽ bị phá sản hoàn toàn chỉ trong vòng bốn mươi tám tiếng nữa!\"",
    "\"Xin em cứu lấy Lê Gia, anh sẵn sàng làm tất cả mọi thứ vì em!\"",
    "\"Chúng ta có thể quay lại với nhau, anh sẽ bù đắp cho em suốt quãng đời còn lại!\"",
    "Nhìn người đàn ông từng là chỗ dựa của mình nay quỳ dưới chân khóc lóc thảm hại, Hương chỉ cảm thấy một sự khinh bỉ sâu sắc.",
    "Cô lùi lại một bước đầy ghê tởm, né tránh bàn tay đang muốn bám lấy tạt áo vest của cô.",
    "\"Lê Huy, đứng lên đi. Đừng làm trò hề ở đây nữa.\"",
    "\"Khi bà Liên giẫm nát giỏ hoa hồng Eternal Grace của tôi ở sảnh Park Hyatt, các người đã tự tay giẫm nát cơ hội sống sót cuối cùng của Lê Gia rồi.\"",
    "\"Thương trường như chiến trường, không có chỗ cho sự hèn nhát và những lời xin lỗi rẻ rách.\"",
    "\"Giỏ hoa hồng đó là kết quả của năm năm nghiên cứu công nghệ sinh học của hàng trăm kỹ sư.\"",
    "\"Hành vi phá hoại chuỗi cung ứng lạnh của Nam Phong Logistics đã vi phạm nghiêm trọng luật pháp sở hữu trí tuệ.\"",
    "\"Tất cả hồ sơ chứng cứ đã được chuyển sang cơ quan điều tra kinh tế.\"",
    "\"Tôi sẽ không rút đơn kiện, và tôi sẽ đòi bồi thường đến đồng xu cuối cùng của Lê Gia.\"",
    "Bà Liên run rẩy tiến lên, hai tay chắp lại cầu khẩn đầy hèn hạ.",
    "\"Chủ tịch Phạm! Tôi van xin cô! Tôi là kẻ có mắt không tròng!\"",
    "\"Tôi xin quỳ xuống tạ lỗi với cô, xin cô hãy chừa cho Lê Gia một con đường sống!\"",
    "Hương nhìn bà Liên bằng ánh mắt sắc lạnh như băng, giọng nói đều đều nhưng đanh thép.",
    "\"Bà Liên, bà từng nói hoa hồng hữu cơ của tôi chỉ đáng nằm dưới gót giày của bà.\"",
    "\"Bây giờ, bà lại cầu xin thứ hoa rác rưởi đó cứu mạng Lê Gia sao?\"",
    "\"Tôi là một doanh nhân sòng phẳng, kinh doanh là kinh doanh, pháp lý là pháp lý.\"",
    "\"Hãy chuẩn bị tinh thần hầu tòa và gánh chịu hậu quả từ những việc mình đã làm đi.\"",
    "Trần Minh Anh bước đến bên cạnh Hương, gương mặt đĩnh đạc lạnh lùng ra hiệu cho đội an ninh.",
    "\"Đưa hai người này ra ngoài, đừng để họ làm phiền buổi tiệc ăn mừng của chúng tôi.\"",
    "Bốn vệ sĩ suit đen lập tức bước tới, kéo bà Liên và Lê Huy ra ngoài sảnh tiệc mặc cho họ khóc lóc van xin thảm thiết.",
    "Minh Anh quay sang nhìn Hương, giơ chiếc ly champagne của mình lên đầy vẻ chúc mừng.",
    "\"Chúc mừng Chủ tịch Phạm, cô đã giải quyết một cách rất sòng phẳng và xuất sắc.\"",
    "\"Bản Việt đã hoàn tất thủ tục cam kết hỗ trợ gói tài chính năm mươi triệu USD từ các quỹ ngoại cho liên doanh của chúng ta.\"",
    "\"Toàn bộ chuỗi cung ứng lạnh chuyên dụng sang Frankfurt và Tokyo sẽ được vận hành chính thức vào tuần tới.\"",
    "Hương khẽ chạm ly với Minh Anh, tiếng pha lê vang lên thanh mảnh và ngọt ngào.",
    "\"Cảm ơn Trần tổng. Sự kết hợp giữa sức mạnh tài chính của Bản Việt và công nghệ của GreenFlora chắc chắn sẽ đưa chúng ta đi xa hơn.\"",
    "Cô bước đến bên cửa kính sát đất của phòng VIP tầng cao, ngắm nhìn toàn cảnh thành phố Thành Tâm tráng lệ dưới ánh nắng vàng.",
    "Cơn mưa giông đã qua đi, để lại một bầu trời trong xanh rực rỡ và tràn đầy sức sống.",
    "Đế chế hoa tươi hữu cơ của cô đã chính thức vươn mình đứng dậy từ đống tro tàn của giỏ hoa bị chà đạp.",
    "Tương lai rực rỡ đang mở rộng trước mắt cô, và không một thế lực nào có thể ngăn cản bước chân của người phụ nữ kiên định ấy.",
    "Đó chính là câu trả lời đanh thép nhất cho những kẻ từng chà đạp lên ước mơ và công sức của cô.",
    "Hương hít một hơi sâu đầy sảng khoái, cảm nhận làn gió mát lướt nhẹ qua làn da.",
    "Cô biết rằng, hành trình vươn ra đại dương lớn của GreenFlora giờ đây mới chỉ thực sự bắt đầu.",
    "Mọi khó khăn thử thách phía trước sẽ chỉ làm bệ phóng cho vị thế độc tôn của đế chế hoa tươi công nghệ cao này."
]

def make_html(sentences):
    # Mỗi câu/dòng được bọc trong thẻ <p>...</p>\n riêng biệt
    return "\n".join([f"<p>{s}</p>" for s in sentences]) + "\n"

payload = {
    "title": "Cô Gái Bán Hoa Bị Đám Cưới Nhà Giàu Đuổi Ra, Tập Đoàn Hoa Tươi Của Cô Niêm Yết Ngay Hôm Đó",
    "subtitle": "Đế Chế Hoa Tươi",
    "author": "Đông Hải Cư Sĩ",
    "genre": "Sảng Văn",
    "intro": "<p><strong>\"Bà Liên, Lê Huy. Các người có biết bản thân vừa giẫm nát thứ gì không?\"</strong></p>\n<p>Giỏ hoa hồng organic 'Eternal Grace' - thành quả R&D 5 năm của cô gái bán hoa dạo Phạm Thị Hương bị hào môn giẫm nát không thương tiếc.</p>\n<p>Nhưng ngay hôm đó, tiếng chuông gõ sàn HOSE vang lên, tập đoàn nông nghiệp công nghệ cao GreenFlora trị giá hàng ngàn tỷ đồng của cô chính thức niêm yết.</p>\n<p>Một câu chuyện vả mặt hào môn cực kỳ sòng phẳng và kịch tính trên chiến trường tài chính công nghệ cao.</p>\n",
    "cover_prompt": "A high-end book cover, highly detailed web novel illustration style, a beautiful and confident young Vietnamese woman in a elegant light beige business suit standing in a massive modern high-tech greenhouse filled with colorful premium roses. Soft cinematic lighting, golden sun rays filtering through glass windows, premium colors.",
    "chapters": [
        {
            "title": "Chương 1: Tiệc Cưới Hào Môn Và Giỏ Hoa Nát",
            "content": make_html(ch1_sentences)
        },
        {
            "title": "Chương 2: Đối Tác Đầu Tư Và Bản Hợp Đồng Sòng Phẳng",
            "content": make_html(ch2_sentences)
        },
        {
            "title": "Chương 3: Khủng Hoảng Chuỗi Cung Ứng Lạnh Ở Hội Nguyên",
            "content": make_html(ch3_sentences)
        },
        {
            "title": "Chương 4: Hào Môn Kinh Biến Và Tiếng Chuông Gõ Sàn",
            "content": make_html(ch4_sentences)
        },
        {
            "title": "Chương 5: Vả Mặt Sòng Phẳng Và Đế Chế Vươn Tầm",
            "content": make_html(ch5_sentences)
        }
    ]
}

# Kiểm tra số từ tiếng Việt của từng chương
for idx, ch in enumerate(payload["chapters"], 1):
    words = len(ch["content"].replace("<p>", "").replace("</p>", "").replace("\n", " ").split())
    print(f"Chương {idx}: {words} từ")

# Lưu ra file JSON chỉ định
target_dir = "/Users/aaronnguyen/TN/App/doctieuthuyet/scratch"
os.makedirs(target_dir, exist_ok=True)
target_file = os.path.join(target_dir, "draft_novel_22.json")

with open(target_file, "w", encoding="utf-8") as f:
    json.dump(payload, f, ensure_ascii=False, indent=2)

print(f"Đã lưu bản thảo thành công vào: {target_file}")
