# -*- coding: utf-8 -*-
import json
import os

def create_novel():
    novel = {
        "title": "Thần Y Phòng Khám Quận 5",
        "author": "Thanh Phong",
        "genre": "Sảng Văn",
        "intro": "<p>Lâm Trần là một bác sĩ thực tập thiên tài tại phòng khám đa khoa An Tâm ở Quận 5, người đã cống hiến cả thanh xuân để nghiên cứu ra liệu pháp đột phá tái tạo tế bào gan bằng thảo dược tự nhiên. Thế nhưng, sự thật tàn nhẫn ập đến khi Trưởng khoa Hoàng Vĩnh – một kẻ tham lam và xảo quyệt – đã cướp đoạt toàn bộ công trình của anh, biến nó thành của riêng rồi đuổi anh ra khỏi phòng khám trong nhục nhã.</p><p>Giữa cơn mưa tầm tã của Sài Gòn, Lâm Trần gặp gỡ Minh Thư, ái nữ sắc sảo của siêu tập đoàn y tế Trịnh Gia. Được sự hậu thuẫn mạnh mẽ của cô, anh quyết định mở phòng khám y học cổ truyền \"Nhân Y Đường\" ngay đối diện kẻ thù, bắt đầu hành trình lấy lại danh dự và vươn lên đỉnh cao y học. Những trận chiến y lý nghẹt thở, những cú lật kèo pháp lý ngoạn mục và sự trừng phạt đích đáng cho kẻ phản bội đang chờ đón bạn trong tác phẩm này.</p>",
        "cover_prompt": "masterpiece, highly detailed book cover, professional anime illustration, a handsome young Vietnamese doctor in a white coat holding an ancient acupuncture needle, standing next to a beautiful and confident female executive in a modern high-end office overlooking Ho Chi Minh City skyline, bright dramatic lighting, cinematic composition",
        "chapters": []
    }

    # Chapter 1: Kẻ Ăn Cắp Công Trình
    chap1_content = """<p>Mùi cồn sát trùng nồng nặc quyện với không khí oi bức của buổi trưa Sài Gòn tháng Năm tạo nên một cảm giác ngột ngạt đến khó thở. Bên trong phòng làm việc khang trang của Trưởng khoa Nội kiêm Phó Giám đốc Phòng khám Đa khoa An Tâm tại Quận 5, tiếng máy điều hòa chạy rì rầm không đủ làm dịu đi cái nóng trong lòng Lâm Trần. Anh đứng sững giữa nền gạch men trắng bóng, hai bàn tay siết chặt đến mức các đầu ngón tay trắng bệch, mồ hôi lạnh rịn ra ướt sũng chiếc áo blouse mỏng dính sau lưng.</p>
<p>Trước mặt anh, Hoàng Vĩnh – một người đàn ông ngoài năm mươi tuổi với cái bụng phệ và cặp kính gọng vàng đạo mạo – đang thong thả lật giở xấp tài liệu dày cộm. Đó chính là toàn bộ công trình nghiên cứu suốt ba năm qua của Lâm Trần: liệu pháp đột phá hỗ trợ tái tạo tế bào gan bằng cách kết hợp enzyme tự nhiên và các vị thảo dược Nam dược đặc hữu. Đây là niềm hy vọng cứu sống hàng ngàn bệnh nhân xơ gan giai đoạn cuối mà Lâm Trần đã thức trắng hàng trăm đêm trong phòng thí nghiệm chật hẹp để hoàn thành.</p>
<p>"Đề tài này thực sự rất xuất sắc," Hoàng Vĩnh chậc lưỡi, ngước mắt lên nhìn Lâm Trần bằng ánh mắt đầy ẩn ý. "Phương pháp tối ưu hóa hoạt lực của nhân trần và diệp hạ châu thông qua công nghệ nano sinh học... Rất có triển vọng thương mại hóa. Đề tài cấp Bộ này chắc chắn sẽ giúp phòng khám chúng ta nâng cao vị thế."</p>
<p>Lâm Trần nén sự hồi hộp, tiến lên một bước: "Thưa Trưởng khoa, em đã hoàn thành báo cáo lâm sàng giai đoạn ba trên năm mươi bệnh nhân tình nguyện. Kết quả phục hồi mô gan đạt tới tám mươi lăm phần trăm. Em hy vọng hồ sơ nghiệm thu sẽ ghi nhận đúng công sức của em để em có cơ hội được xét duyệt làm bác sĩ chính thức."</p>
<p>Hoàng Vĩnh bỗng dừng lại, nụ cười trên môi gã vụt tắt, thay vào đó là một vẻ mặt lạnh lùng đến đáng sợ. Gã đóng sập tập tài liệu lại, phát ra một tiếng "bạch" khô khốc trên mặt bàn gỗ mahogany sang trọng. Gã dựa lưng vào ghế, đan hai tay vào nhau rồi thong thả nói:</p>
<p>"Cậu Lâm Trần này, hình như cậu đang có một sự hiểu lầm rất lớn ở đây. Đề tài này là do tôi – Hoàng Vĩnh, Trưởng khoa Nội trực tiếp định hướng và chỉ đạo nghiên cứu. Cậu chỉ là một thằng thực tập sinh quèn, nhiệm vụ hằng ngày là lau dọn ống nghiệm và nhập liệu máy tính. Lấy tư cách gì mà đòi đứng tên làm tác giả chính?"</p>
<p>Lâm Trần như bị một gáo nước đá dội thẳng vào đầu giữa trưa nắng. Tai anh ù đi, lồng ngực phập phồng dữ dội: "Trưởng khoa! Sao ông có thể nói thế? Từ việc chọn mẫu thảo dược ở vùng núi cao Đà Lạt, đến việc chiết tách enzyme trong phòng thí nghiệm lúc ba giờ sáng, tất cả đều do một tay em làm! Bản thảo gốc viết tay của em vẫn còn lưu ngày giờ rõ ràng trên máy tính!"</p>
<p>"Câm miệng!" Hoàng Vĩnh đập bàn đứng phắt dậy, gương mặt gã đỏ gay vì tức giận giả tạo. "Cậu định vu khống cấp trên ăn cắp công trình à? Máy tính của cậu là tài sản của phòng khám An Tâm. Mọi dữ liệu trong đó đều thuộc quyền sở hữu của chúng tôi. Hơn nữa, tôi đã chính thức nộp hồ sơ đăng ký bản quyền lên Cục Sở hữu Trí tuệ sáng nay dưới tên của tôi và Giám đốc phòng khám. Cậu có bằng chứng gì để chứng minh đây là của cậu?"</p>
<p>Đúng lúc này, cửa phòng làm việc mở ra. Hai nhân viên bảo vệ đô con cùng với y tá trưởng bước vào. Hoàng Vĩnh chỉ tay vào mặt Lâm Trần, giọng nói đầy lạnh lùng và tàn nhẫn:</p>
<p>"Lâm Trần, cậu bị sa thải ngay lập tức vì hành vi trộm cắp tài liệu mật của phòng khám và có thái độ vô lễ, xúc phạm lãnh đạo. Bảo vệ! Lục soát người nó, thu hồi toàn bộ thẻ nhân viên, usb và đuổi thẳng cổ ra khỏi đây!"</p>
<p>"Hoàng Vĩnh! Ông là đồ vô liêm sỉ! Luật pháp sẽ không để ông yên!" Lâm Trần hét lên, nhưng hai gã bảo vệ to khỏe đã nhanh chóng khóa chặt hai tay anh ra sau lưng. Họ thô bạo lục soát túi quần, giật lấy chiếc điện thoại cũ kỹ và chiếc ví của anh, ném toàn bộ giấy tờ tùy thân xuống sàn nhà.</p>
<p>Chưa dừng lại ở đó, Hoàng Vĩnh còn nở nụ cười thâm độc: "À, tôi quên chưa nói cho cậu biết. Tài khoản ngân hàng Techcombank của cậu – nơi cậu nhận tiền hỗ trợ thực tập ít ỏi – cũng đã bị phòng khám yêu cầu tạm khóa để phục vụ điều tra nội bộ về việc thất thoát quỹ nghiên cứu. Cậu muốn kiện? Cứ tự nhiên. Để xem một thằng sinh viên nghèo y khoa không xu dính túi như cậu sẽ đấu thế nào với đội ngũ luật sư của An Tâm."</p>
<p>Mười phút sau, Lâm Trần bị đẩy mạnh ra khỏi cổng Phòng khám Đa khoa An Tâm. Chiếc hòm tôn cũ kỹ đựng vài bộ quần áo sờn vai và cuốn sổ tay y thuật viết tay của người ông quá cố bị ném mạnh ra vỉa hè đường Nguyễn Trãi. Ngay lập tức, bầu trời Sài Gòn vốn đang nắng gắt bỗng đổ sập xuống một cơn mưa giông tầm tã. Nước mưa lạnh buốt tuôn xối xả, hòa cùng những giọt nước mắt uất hận lăn dài trên má Lâm Trần. Anh quỳ sụp xuống bên chiếc hòm tôn, nước mưa thấm đẫm mái tóc và bộ quần áo blouse trắng giờ đã lấm lem bùn đất. Hai bàn tay anh bấm chặt vào mép vỉa hè đến bật máu, ánh mắt nhìn trân trân vào biển hiệu đèn LED rực rỡ của phòng khám An Tâm. Một lời thề uất hận khắc sâu vào tận xương tủy: Hoàng Vĩnh, những gì ông đã cướp của tôi hôm nay, tôi nhất định sẽ bắt ông phải trả lại gấp trăm lần!</p>"""

    # Chapter 2: Người Bạn Đồng Hành Kỳ Lạ
    chap2_content = """<p>Cơn mưa chiều Sài Gòn mỗi lúc một nặng hạt, bong bóng nước vỡ phập phồng trên mặt đường nhựa Nguyễn Trãi đen kịt. Lâm Trần ngồi co ro dưới mái hiên di động của một cửa hàng thời trang đã đóng cửa, tấm lưng gầy tựa sát vào bức tường xi măng lạnh ngắt. Chiếc áo blouse trắng sũng nước dính chặt vào da thịt khiến anh không ngừng run lên bần bật. Số dư tài khoản bằng không, ví tiền trống rỗng, ngay cả chiếc điện thoại liên lạc cũng bị Hoàng Vĩnh giữ lại với lý do bảo mật dữ liệu. Vào khoảnh khắc tuyệt vọng nhất của cuộc đời, Lâm Trần cảm thấy mình như một con chó hoang bị bỏ rơi giữa lòng đô thị hoa lệ.</p>
<p>Bỗng nhiên, một tiếng gầm rú trầm thấp, uy lực của động cơ xe thể thao vang lên, xé toạc màn mưa trắng xóa. Một chiếc Porsche Panamera màu đen bóng bẩy lướt tới với tốc độ cực nhanh, rồi thực hiện một cú phanh hoàn hảo, dừng lại sát mép vỉa hè ngay trước mặt Lâm Trần. Ánh đèn pha LED ma trận cực sáng của chiếc xe chiếu thẳng vào màn mưa, tạo nên một luồng sáng lung linh như trên sân khấu.</p>
<p>Cửa xe phía sau từ từ mở ra. Một chiếc ô màu đen bản lớn vươn ra trước, che đi những hạt mưa đang xối xả. Bước xuống xe là một cô gái trẻ tầm hai mươi lăm tuổi. Gương mặt cô thanh tú nhưng vô cùng sắc sảo, đôi mắt phượng dài toát lên vẻ thông minh và kiên định. Cô mặc một bộ vest công sở màu xanh navy cắt may thủ công tinh tế, ôm sát vóc dáng cao ráo, chân đi đôi giày cao gót Louboutin đế đỏ quyền lực. Sự xuất hiện của cô như mang theo một luồng sinh khí hoàn toàn khác biệt giữa khung cảnh ảm đạm của cơn mưa.</p>
<p>"Bác sĩ Lâm Trần, tôi đã tìm anh suốt hai tiếng qua," cô gái cất giọng, âm vực trong trẻo nhưng mang một sức nặng không thể chối từ.</p>
<p>Lâm Trần ngơ ngác ngước nhìn lên, nước mưa chảy ròng ròng trên trán làm nhòe đi tầm nhìn: "Cô... cô là ai? Sao lại biết tên tôi?"</p>
<p>"Tôi là Trịnh Minh Thư, Giám đốc điều hành của Quỹ đầu tư Y tế Trịnh Thị," cô gái tự giới thiệu, khom người xuống che chiếc ô cho anh. "Tôi biết anh đang gặp chuyện gì. Hoàng Vĩnh đã ăn cắp công trình nghiên cứu tế bào gan của anh. Nhưng anh yên tâm, kẻ cắp thì mãi mãi chỉ là kẻ cắp, hắn không bao giờ nắm giữ được cốt lõi của công thức. Đi theo tôi, đây không phải là nơi để nói chuyện."</p>
<p>Nhìn vào đôi mắt kiên định và đầy sự tin cậy của Minh Thư, Lâm Trần như tìm thấy một chiếc phao cứu sinh giữa dòng nước lũ. Anh ôm chặt chiếc hòm tôn cũ kỹ, bước theo cô vào bên trong không gian ấm áp, thơm mùi da thuộc Alcantara cao cấp của chiếc Porsche Panamera. Chiếc xe nhanh chóng khởi hành, bỏ lại sau lưng phòng khám An Tâm dần mờ nhạt trong màn mưa.</p>
<p>Bên trong xe, Minh Thư đưa cho Lâm Trần một chiếc khăn bông khô mềm mại và một tách trà gừng nóng hổi. Hơi ấm từ tách trà dần xua đi cái lạnh đang đông cứng trong huyết quản của anh. Minh Thư thong thả bấm nút trên bảng điều khiển, hạ nhiệt độ điều hòa xuống mức vừa phải rồi quay sang nhìn Lâm Trần:</p>
<p>"Tôi đã theo dõi đề tài nghiên cứu của anh từ giai đoạn thử nghiệm lâm sàng lần thứ nhất. Tôi biết rõ tài năng của anh. Cha tôi – ông Trịnh Văn Hùng, Chủ tịch tập đoàn Trịnh Thị – đang bị bệnh xơ gan mất bù rất nặng, các bác sĩ hàng đầu tại Bệnh viện Chợ Rẫy đều đã lắc đầu. Khi tôi đọc được bản tóm tắt đề tài mà Hoàng Vĩnh công bố sáng nay dưới tên hắn, tôi đã biết ngay đó là công trình của anh, bởi vì một kẻ bất tài chỉ biết loay hoay với các mối quan hệ ngoại giao như Hoàng Vĩnh không bao giờ viết nổi những dòng phân tích sâu sắc về cơ chế kích hoạt tế bào gốc bằng thảo dược Nam bộ."</p>
<p>Lâm Trần siết chặt tách trà, giọng nói vẫn còn run nhẹ vì xúc động: "Cảm ơn cô đã tin tưởng tôi. Nhưng bây giờ tôi đã trắng tay. Hoàng Vĩnh đã khóa tài khoản của tôi, giữ hết tài liệu lâm sàng, tôi thậm chí không có tiền để mua nổi một chiếc bánh mì..."</p>
<p>Minh Thư nở một nụ cười tự tin, phong thái của một nữ cường nhân thực thụ lộ rõ: "Trắng tay? Không, Lâm Trần. Bộ óc thiên tài của anh và cuốn sổ tay y thuật kia mới là tài sản vô giá. Hoàng Vĩnh cướp được xấp giấy tờ, nhưng hắn không biết cách phối ngũ các vị thuốc để đạt hiệu quả tối đa mà không gây độc tính. Tôi muốn đề nghị một thỏa thuận hợp tác sòng phẳng với anh."</p>
<p>Cô lấy từ trong túi xách hiệu Hermes ra một chiếc máy tính bảng, mở một file bản đồ quy hoạch đô thị Quận 1 lên trước mặt anh: "Tôi đã thuê sẵn một tòa nhà ba tầng mặt tiền nằm ngay ngã tư đường lớn, đối diện chéo qua phòng khám An Tâm của Hoàng Vĩnh. Tôi sẽ đầu tư toàn bộ trang thiết bị y tế hiện đại nhất, hoàn tất mọi thủ tục pháp lý để thành lập phòng khám y học cổ truyền công nghệ cao mang tên 'Nhân Y Đường'. Anh sẽ là Giám đốc chuyên môn kiêm cổ đông sở hữu bốn mươi phần trăm cổ phần."</p>
<p>Nói rồi, cô đặt vào tay Lâm Trần một chiếc điện thoại iPhone mới tinh và một chiếc thẻ ngân hàng màu đen quyền lực của Vietcombank: "Trong tài khoản Vietcombank này đã đứng tên anh, tôi đã nạp sẵn năm tỷ đồng để anh tự do chi tiêu cá nhân và chuẩn bị cho việc khai trương phòng khám. Tôi tin rằng, cách trả thù tốt nhất chính là đứng ở vị trí cao hơn kẻ thù, dùng chính năng lực thực sự của mình để giẫm bẹp sự tự tôn giả tạo của hắn. Anh có dám cùng tôi thực hiện điều này không?"</p>
<p>Lâm Trần nhìn chiếc thẻ Vietcombank trong tay, cảm nhận được một luồng sức mạnh mới đang trỗi dậy mạnh mẽ trong lồng ngực. Ánh mắt anh trở nên sắc bén và kiên định hơn bao giờ hết. Anh ngước lên nhìn Minh Thư, dứt khoát gật đầu: "Được! Tôi đồng ý. Nhân Y Đường sẽ là nơi chôn cất sự nghiệp của Hoàng Vĩnh!"</p>"""

    # Chapter 3: Khai Trương Đối Đầu
    chap3_content = """<p>Nắng sớm của Sài Gòn rực rỡ trải dài trên các tuyến phố sầm uất của Quận 1. Tại ngã tư giao lộ sầm uất, không khí buổi sáng hôm nay bỗng trở nên vô cùng náo nhiệt. Ngay đối diện chéo qua Phòng khám Đa khoa An Tâm – nơi vốn dĩ độc chiếm lượng bệnh nhân khu vực này – một bảng hiệu bằng gỗ mun khắc chữ mạ vàng ròng sang trọng vừa được khánh thành: "Nhân Y Đường - Phòng Khám Y Học Cổ Truyền Công Nghệ Cao". Sự xuất hiện của Nhân Y Đường như một cái tát trực diện vào sự kiêu ngạo của An Tâm.</p>
<p>Không có hoa chúc mừng rầm rộ, không có tiếng trống lân ồn ào, Nhân Y Đường mở cửa đón những bệnh nhân đầu tiên bằng chương trình khám và điều trị miễn phí hoàn toàn cho người nghèo và người có hoàn cảnh khó khăn trong vòng một tuần đầu tiên. Lâm Trần mặc bộ quần áo blouse trắng phẳng phiu, ngồi ở vị trí bàn khám chính. Gương mặt anh điềm tĩnh, thần thái tự tin, đôi mắt sáng ngời tinh anh khác hẳn với hình ảnh người thanh niên co ro dưới mưa một tháng trước.</p>
<p>Bên kia đường, đứng sau tấm kính lớn của phòng làm việc trên tầng ba phòng khám An Tâm, Hoàng Vĩnh đang nhìn chằm chằm sang Nhân Y Đường với gương mặt tối sầm lại. Hắn đập mạnh ly cà phê xuống bàn làm nước sóng sánh văng ra ngoài, giọng gầm lên với gã trợ lý đứng bên cạnh:</p>
<p>"Cái phòng khám rách nát đó ở đâu ra? Sao thằng ranh con Lâm Trần lại có thể mở được phòng khám ngay trước mũi tôi thế này? Ai đã cấp phép cho nó?"</p>
<p>"Dạ... thưa Trưởng khoa, theo thám tử của chúng ta báo lại, người đứng sau chống lưng cho Lâm Trần chính là Trịnh Minh Thư – ái nữ của Trịnh Gia. Toàn bộ mặt bằng và thiết bị y tế đều do Quỹ đầu tư Trịnh Thị tài trợ," gã trợ lý run rẩy báo cáo.</p>
<p>"Trịnh Gia sao?" Hoàng Vĩnh biến sắc, nhưng ngay lập tức gã nghiến răng cười khẩy. "Hừ, Trịnh Gia thì đã sao? Liệu pháp phục hồi gan kia đã được tôi đăng ký sở hữu trí tuệ cấp Bộ. Thằng ranh đó dám hành nghề y học cổ truyền mà không có thuốc đặc trị thì lấy gì để đấu với danh tiếng của An Tâm? Để tôi xem nó chịu đựng được bao lâu!"</p>
<p>Thế nhưng, những gì diễn ra tại Nhân Y Đường trong những ngày tiếp theo đã khiến Hoàng Vĩnh hoàn toàn mất ngủ. Lâm Trần không cần dùng đến những loại thuốc tây đắt tiền hay những liệu trình máy móc phức tạp của An Tâm. Anh chẩn đoán bệnh bằng phương pháp "Vọng - Văn - Vấn - Thiết" tinh thông kết hợp với máy quét hồng ngoại tầm nhiệt hiện đại để định vị chính xác vùng tổn thương. Mỗi bệnh nhân đến với anh đều được châm cứu giải độc, đắp thuốc nam đặc trị và uống những thang thuốc do chính tay anh bốc.</p>
<p>Một ca bệnh điển hình là ông Sáu, một tài xế xe ôm công nghệ ở Quận 5 bị xơ gan cổ trướng giai đoạn cuối, bụng phình to như trống, da vàng vọt như sáp. Ông Sáu từng đến phòng khám An Tâm và bị Hoàng Vĩnh thẳng tay đuổi về vì không có đủ một trăm triệu đồng đóng tiền viện phí ban đầu. Khi được người quen giới thiệu đến Nhân Y Đường, ông Sáu chỉ còn thoi thóp thở. Lâm Trần đã dùng bộ châm cứu bằng bạc gia truyền, thực hiện kỹ thuật châm cứu liên hoàn trục độc vào các đại huyệt. Chỉ sau ba ngày điều trị kết hợp uống thuốc đặc trị của Lâm Trần, bụng ông Sáu đã xẹp hẳn, làn da hồng hào trở lại, ông có thể tự đi lại và ăn uống ngon miệng trước sự ngỡ ngàng của cả gia đình.</p>
<p>Tin đồn về "Thần y trẻ tuổi" chữa khỏi bệnh gan nan y lan truyền nhanh chóng như vết dầu loang khắp Sài Gòn. Lượng bệnh nhân từ khắp nơi đổ về Nhân Y Đường ngày một đông, xếp hàng dài từ sáng sớm đến tối mịt, trong khi phòng khám An Tâm bên kia đường bỗng trở nên vắng vẻ, đìu hiu chưa từng thấy.</p>
<p>Điên cuồng vì bị cướp mất thị phần và lòng tự tôn bị chà đạp, Hoàng Vĩnh quyết định tung ra đòn hiểm. Hắn bỏ ra hai trăm triệu đồng thuê một nhóm phóng viên bẩn và một số tài khoản mạng xã hội lớn chuyên viết bài câu view để tung tin đồn thất thiệt. Sáng ngày thứ năm, một bài báo giật gân xuất hiện trên mạng xã hội với tiêu đề: "Kinh hoàng phòng khám Nhân Y Đường Quận 1 sử dụng thảo dược chứa độc chất thạch tín vượt ngưỡng, lừa đảo bệnh nhân!". Đồng thời, một nhóm người lạ mặt xuất hiện trước cổng Nhân Y Đường, căng băng rôn la hét cáo buộc Lâm Trần chữa bệnh làm người nhà họ suýt chết.</p>
<p>Ngay lập tức, đám đông phóng viên báo chí và người dân hiếu kỳ ùa tới vây kín Nhân Y Đường. Giữa lúc không khí đang vô cùng căng thẳng, Lâm Trần vẫn giữ vẻ điềm tĩnh ngồi trong phòng khám. Cửa chính mở ra, Trịnh Minh Thư bước xuống từ chiếc Porsche Panamera quen thuộc, phong thái đầy kiêu sa và quyền lực. Cô đi thẳng vào giữa đám đông phóng viên, ra hiệu cho đội bảo vệ chặn đứng nhóm người gây rối. Minh Thư cầm micro, giọng nói dõng dạc vang lên đầy đanh thép:</p>
<p>"Xin mọi người trật tự! Tôi là Trịnh Minh Thư, đại diện pháp luật của Nhân Y Đường. Về những cáo buộc vô căn cứ sáng nay, chúng tôi đã chuẩn bị đầy đủ bằng chứng pháp lý để trả lời trước dư luận."</p>
<p>Cô quay sang gật đầu với trợ lý, lập tức những tập hồ sơ dày cộm được phát cho tất cả các phóng viên có mặt: "Đây là phiếu kiểm nghiệm thành phần dược liệu của Viện Kiểm nghiệm Thuốc Trung ương, chứng minh toàn bộ thảo dược của Nhân Y Đường đều đạt chuẩn sạch 100%, không hề có độc chất. Và đặc biệt hơn..."</p>
<p>Minh Thư bấm nút hiển thị một tài liệu trên màn hình LED lớn trước sảnh phòng khám: "Đây là bằng chứng nhận sở hữu trí tuệ công thức độc quyền 'Thanh Can Hoạt Tế Bào' của bác sĩ Lâm Trần, được nộp và đóng dấu lưu trữ tại Cục Sở hữu Trí tuệ từ một năm trước, khi anh ấy còn là sinh viên nghiên cứu – hoàn toàn trước thời điểm Hoàng Vĩnh ăn cắp và công bố công trình giả mạo cấp Bộ. Chúng tôi cũng đã gửi đơn khởi kiện Hoàng Vĩnh về hành vi vu khống và vi phạm bản quyền sáng chế lên Tòa án Nhân dân TP.HCM sáng nay. Kẻ nào cố tình bôi nhọ Nhân Y Đường sẽ phải đối mặt với pháp luật!"</p>
<p>Lời tuyên bố đanh thép của Minh Thư cùng những bằng chứng sắt đá như sấm sét giữa trời quang, đánh sụp hoàn toàn âm mưu truyền thông bẩn của Hoàng Vĩnh. Đám đông phóng viên xôn xao, nhanh chóng quay ống kính camera sang phía phòng khám An Tâm để chất vấn. Hoàng Vĩnh đứng bên kia đường, nhìn cảnh tượng bại trận qua cửa kính, gương mặt gã xám ngoét như tro tàn, hai hàm răng nghiến chặt đến phát ra tiếng kêu kèn kẹt.</p>"""

    # Chapter 4: Đỉnh Điểm Khủng Hoảng
    chap4_content = """<p>Sự thất bại thảm hại trong chiến dịch bôi nhọ truyền thông đã đẩy Phòng khám An Tâm và cá nhân Hoàng Vĩnh vào con đường cùng. Doanh thu của An Tâm sụt giảm nghiêm trọng, các nhà đầu tư bắt đầu rút vốn liên tục, và thanh tra y tế đã chính thức vào cuộc để làm rõ vụ bê bối ăn cắp bản quyền sáng chế. Đứng trước nguy cơ mất trắng sự nghiệp và phải đối mặt với án tù, Hoàng Vĩnh như một con thú dữ bị dồn vào chân tường, gã quyết định thực hiện một kế hoạch tàn độc nhất để lật ngược thế cờ.</p>
<p>Hắn bí mật liên hệ với một tổ chức y tế ngầm nước ngoài biến chất để mua một loại độc chất sinh học mới cực mạnh có tên là 'TX-9'. Đây là chất độc không màu, không mùi, khi đi vào cơ thể sẽ kích thích tế bào gan suy hoại nhanh chóng, gây triệu chứng suy đa tạng tương tự như một ca suy gan cấp tính do ngộ độc thảo dược cấp tính, rất khó để phát hiện bằng các phương pháp xét nghiệm thông thường.</p>
<p>"Chỉ cần thằng ranh Lâm Trần chữa chết người ngay tại phòng khám của nó, Nhân Y Đường sẽ bị niêm phong vĩnh viễn, mọi danh tiếng của nó sẽ biến thành mây khói, và tôi sẽ là người duy nhất nắm giữ công thức giải độc cứu người!" Hoàng Vĩnh cười điên cuồng trong bóng tối của phòng làm việc.</p>
<p>Cơ hội đã đến khi gã biết được một thông tin cực kỳ quan trọng: Ông Trịnh Văn Hùng – Chủ tịch Trịnh Gia, cha ruột của Minh Thư – sau một thời gian theo dõi hiệu quả thần kỳ của Nhân Y Đường, quyết định sẽ trực tiếp đến phòng khám này để bác sĩ Lâm Trần bắt mạch và điều trị dứt điểm căn bệnh xơ gan mất bù của ông. Đây là một sự kiện lớn, thu hút sự chú ý của giới tài chính và truyền thông y tế Sài Gòn.</p>
<p>Hoàng Vĩnh đã bỏ ra hai tỷ đồng để mua chuộc gã hộ lý tên Tuấn – người chịu trách nhiệm chuẩn bị nước uống và các dụng cụ y tế phụ trợ tại phòng VIP của Nhân Y Đường. Đúng 9 giờ sáng ngày hẹn, ông Trịnh Văn Hùng bước vào phòng khám trong sự đón tiếp chu đáo của Lâm Trần và Minh Thư. Gương mặt ông Hùng tuy mệt mỏi do bệnh tật nhưng ánh mắt vẫn vô cùng sáng suốt, sắc sảo của một vị tỷ phú lăn lộn thương trường nhiều năm.</p>
<p>"Bác sĩ Lâm Trần, tôi đã nghe con gái tôi nói rất nhiều về cậu. Hy vọng hôm nay cậu có thể giúp ông già này kéo dài thêm vài năm tuổi thọ," ông Hùng cười hào sảng nói.</p>
<p>"Chủ tịch Trịnh cứ yên tâm, tôi sẽ cố gắng hết sức," Lâm Trần điềm tĩnh đáp rồi bắt đầu bắt mạch cho ông.</p>
<p>Trong lúc Lâm Trần đang tập trung kiểm tra mạch tượng, gã hộ lý Tuấn run rẩy bưng vào một khay nước lọc ấm. Minh Thư tự tay đỡ lấy ly nước, đưa cho cha mình uống một ngụm nhỏ để làm dịu cơn ho. Không ai ngờ rằng, bên trong ly nước ấm tinh khiết ấy đã được Tuấn lén nhỏ ba giọt độc chất TX-9 cực độc.</p>
<p>Chỉ mười phút sau khi uống nước, biến cố kinh hoàng bỗng dưng ập đến. Ông Trịnh Văn Hùng đang trò chuyện bỗng sắc mặt biến đổi dữ dội. Ông ôm chặt lấy lồng ngực bên phải, gương mặt tím tái đi vì đau đớn, mồ hôi hột chảy ra như tắm. Ông ho khan dữ dội rồi phun ra một ngụm máu tươi đỏ sẫm ngay trên bàn khám. Các chỉ số nhịp tim và huyết áp trên máy đo phụ trợ lập tức sụt giảm thê thảm, tiếng còi cảnh báo tít tít vang lên dồn dập.</p>
<p>"Ba! Ba bị làm sao thế này?!" Minh Thư thất thanh hét lên, cô lao đến đỡ lấy cơ thể đang dần co giật của cha mình.</p>
<p>Lâm Trần lập tức biến sắc, anh lao tới áp tay vào mạch cổ của ông Hùng. Mạch tượng đập loạn xạ, yếu ớt và có dấu hiệu ngưng trệ hoàn toàn – đây rõ ràng là biểu hiện của việc trúng độc cấp tính phá hủy hệ thống tế bào gan chứ không phải là biến chứng tự nhiên của bệnh xơ gan!</p>
<p>Đúng lúc này, cửa phòng khám Nhân Y Đường bỗng bị đập mạnh từ bên ngoài. Hoàng Vĩnh xuất hiện dẫn theo một nhóm người tự xưng là Thanh tra Sở Y tế và lực lượng cảnh sát Quận 5 ập vào bên trong phòng khám. Hoàng Vĩnh chỉ tay vào Lâm Trần, giọng hét lớn đầy đắc ý:</p>
<p>"Chúng tôi nhận được tin báo khẩn cấp: Phòng khám Nhân Y Đường sử dụng thuốc lậu, cố ý đầu độc giết chết bệnh nhân Trịnh Văn Hùng! Yêu cầu lực lượng công an lập tức phong tỏa hiện trường, bắt giam Lâm Trần để điều tra tội cố ý giết người!"</p>
<p>Đám đông phóng viên bám đuôi phía sau lập tức ùa vào, máy ảnh nháy liên tục, tạo nên một khung cảnh cực kỳ hỗn loạn. Minh Thư nước mắt giàn giụa, nhưng cô vẫn kiên cường đứng chắn trước giường bệnh của cha, ánh mắt sắc lạnh như dao nhìn thẳng vào Hoàng Vĩnh:</p>
<p>"Hoàng Vĩnh! Ông dám bày mưu hại cha tôi! Các người ai dám bước lên một bước khi bác sĩ Lâm Trần chưa cứu sống cha tôi?!"</p>
<p>"Cứu sống sao? Hahaha! Ông Hùng đã suy gan cấp tính giai đoạn cuối, lại uống phải độc dược của thằng ranh này thì chỉ có chết chắc! Đừng chống cự vô ích nữa!" Hoàng Vĩnh cười lớn, đắc ý tột cùng. Lúc này, tính mạng của tỷ phú Trịnh Văn Hùng chỉ còn tính bằng từng giây, và số phận của Nhân Y Đường cũng như Lâm Trần đang ngàn cân treo sợi tóc.</p>"""

    # Chapter 5: Bàn Tay Vàng Lật Kèo
    chap5_content = """<p>Không gian bên trong phòng cấp cứu VIP của Nhân Y Đường ngột ngạt đến mức tưởng chừng như một đốm lửa nhỏ cũng có thể làm bùng nổ bầu không khí. Tiếng còi cảnh báo của máy đo nhịp tim kêu tít tít dồn dập mỗi lúc một yếu ớt, chỉ số oxy trong máu của tỷ phú Trịnh Văn Hùng đã tụt xuống mức báo động đỏ: sáu mươi lăm phần trăm. Bên ngoài cửa kính, Hoàng Vĩnh đang đắc ý cười nói với các phóng viên báo chí, trong khi lực lượng bảo vệ của Nhân Y Đường đang ra sức ngăn cản đám đông cảnh sát cố gắng xông vào niêm phong phòng khám.</p>
<p>Lâm Trần nhắm chặt mắt, hít một hơi thật sâu để ép bản thân phải hoàn toàn bình tĩnh giữa cơn bão. Anh biết rõ, chỉ cần một tích tắc dao động, tính mạng của ông Hùng sẽ tiêu tan và bản thân anh sẽ phải gánh chịu nỗi oan khiên suốt đời. Khi mở mắt ra, ánh mắt Lâm Trần đã trở nên lạnh lùng và tập trung cao độ như một lưỡi dao mổ.</p>
<p>"Minh Thư! Hãy giúp tôi giữ chặt vai của Chủ tịch! Bất kể có chuyện gì xảy ra, không được phép để ai làm gián đoạn!" Lâm Trần hét lớn.</p>
<p>Minh Thư gạt đi giọt nước mắt trên má, kiên định gật đầu. Cô dùng cả hai tay giữ chặt bả vai của cha mình, đôi mắt nhìn chằm chằm vào Lâm Trần đầy sự tin tưởng tuyệt đối.</p>
<p>Lâm Trần nhanh chóng mở chiếc hộp gỗ mun cổ kính, lấy ra bộ châm cứu bằng bạc ròng gia truyền. Anh không cần nhìn, ngón tay lướt nhanh trên cơ thể ông Hùng để xác định huyệt đạo. "Vút! Vút! Vút!" – ba tiếng gió rít nhẹ vang lên, ba cây kim bạc dài ba tấc đã cắm sâu vào các đại huyệt Kỳ Môn, Chương Môn và Thái Xung trên vùng sườn phải của ông Hùng. Ngay lập tức, Lâm Trần dùng ngón tay vê nhẹ chuôi kim, truyền một luồng khí lực ấm áp thông qua kim bạc để kích thích hệ tuần hoàn gan đang bị tê liệt.</p>
<p>Chưa dừng lại ở đó, Lâm Trần tiếp tục châm liên tiếp mười hai cây kim vào các huyệt đạo ở tay và chân để phong tỏa đường đi của độc chất TX-9, ngăn không cho nó xâm nhập vào tim và não. Mồ hôi trên trán Lâm Trần chảy ra thành dòng, ướt đẫm cả mi mắt, nhưng tay anh vẫn giữ một độ chuẩn xác tuyệt đối đến từng milimet.</p>
<p>"Mau đưa cho tôi bát thuốc bắc đã sắc sẵn trong tủ sấy khẩn cấp!" Lâm Trần ra lệnh cho y tá.</p>
<p>Đó là bát thuốc chứa tinh chất "Thanh Can Hoạt Tế Bào" nồng độ cao kết hợp với hoa kim ngân rừng và nhân trần độc bản do chính tay Lâm Trần điều chế. Anh đỡ đầu ông Hùng lên, cẩn thận đổ từng thìa thuốc ấm vào miệng ông. Dòng thuốc đi đến đâu, cơ thể ông Hùng bớt co giật đến đó.</p>
<p>Đúng lúc này, Hoàng Vĩnh bên ngoài phòng kính mất kiên nhẫn, gã hét lớn với cảnh sát: "Báo cáo cán bộ! Thằng ranh Lâm Trần đang dùng phương pháp châm cứu phản khoa học để tiêu hủy chứng cứ đầu độc! Yêu cầu phá cửa xông vào bắt giữ ngay lập tức!"</p>
<p>Cánh cửa phòng cấp cứu bị đẩy mạnh, Hoàng Vĩnh cùng hai gã cảnh sát lao vào bên trong. Nhưng ngay khi họ vừa bước qua ngưỡng cửa, một tiếng "hộc" lớn vang lên từ trên giường bệnh. Ông Trịnh Văn Hùng bỗng ngồi phắt dậy, lồng ngực phập phồng dữ dội, rồi phun mạnh ra một ngụm dịch đen ngòm có mùi hôi tanh nồng nặc ngay xuống sàn nhà. Ngay sau ngụm dịch độc ấy, sắc mặt ông Hùng từ tím tái bỗng chốc hồng hào trở lại một cách thần kỳ. Tiếng còi cảnh báo của máy đo nhịp tim dừng hẳn, thay vào đó là những tiếng bíp bíp đều đặn, chỉ số oxy trong máu nhảy vọt lên chín mươi tám phần trăm.</p>
<p>Ông Hùng thở hắt ra một hơi dài, mở to mắt nhìn xung quanh rồi cất giọng trầm ấm: "Minh Thư... Ta đang ở đâu thế này? Cảm giác trong người chưa bao giờ nhẹ nhõm như bây giờ..."</p>
<p>"Ba! Ba tỉnh lại rồi!" Minh Thư òa khóc nức nở, ôm chặt lấy cha mình.</p>
<p>Gương mặt Hoàng Vĩnh lúc này xám ngoét như người chết trôi. Gã lùi lại hai bước, miệng lắp bắp không thành tiếng: "Không... không thể nào! Chất độc TX-9... sao có thể giải được dễ dàng như thế?!"</p>
<p>"Hoàng Vĩnh! Cuối cùng ông cũng tự khai ra tên chất độc rồi sao?" Lâm Trần đứng thẳng người, ánh mắt sắc bén như chim ưng nhìn thẳng vào gã.</p>
<p>Đúng lúc này, Minh Thư lạnh lùng bấm nút trên chiếc máy tính bảng của mình. Màn hình lớn ở sảnh phòng khám và toàn bộ các trang phát trực tiếp của phóng viên lập tức hiển thị một đoạn video sắc nét. Trong video, gã hộ lý Tuấn đang lén lút nhận một bọc tiền dày từ Hoàng Vĩnh tại một con hẻm tối ở Quận 5, kèm theo lời dặn dò: 'Bỏ ba giọt này vào cốc nước của ông Hùng, mọi việc còn lại tao lo'.</p>
<p>"Hoàng Vĩnh! Ông không ngờ chiếc camera ẩn dạng nút áo trên ngực áo của hộ lý Tuấn đã ghi lại toàn bộ sự việc đúng không? Tuấn đã bị chúng tôi bắt giữ và khai nhận toàn bộ cách đây nửa tiếng trước khi ông dẫn cảnh sát tới đây," Minh Thư đanh thép tuyên bố.</p>
<p>Cùng lúc đó, một đoàn người mặc cảnh phục uy nghiêm bước vào phòng khám. Dẫn đầu là một vị trung tá cảnh sát thuộc Cục Cảnh sát điều tra tội phạm về tham nhũng, kinh tế, buôn lậu (C03) Bộ Công An. Ông bước tới trước mặt Hoàng Vĩnh, trưng ra một quyết định có đóng dấu đỏ chói:</p>
<p>"Hoàng Vĩnh! Ông bị bắt khẩn cấp về tội cố ý giết người, vu khống, và hành vi buôn lậu thiết bị y tế giả quy mô lớn thông qua tài khoản Vietcombank của công ty bình phong do ông đứng tên. Yêu cầu ông đi theo chúng tôi về trụ sở để làm việc!"</p>
<p>Hoàng Vĩnh nghe xong như bị sét đánh ngang tai. Hai chân gã bủn rủn, không còn chút sức lực nào, gục sụp xuống nền nhà lát gạch men. Chiếc kính gọng vàng rơi xuống đất vỡ tan tành, cũng giống như giấc mộng vinh hoa phú quý dơ bẩn của gã đã hoàn toàn sụp đổ dưới chân Lâm Trần. Gã bị các chiến sĩ C03 khóa tay và áp giải đi giữa những tiếng la ó, phẫn nộ của hàng trăm người dân vây quanh phòng khám.</p>
<p>Đêm hôm đó, dưới ánh đèn rực rỡ của các tòa nhà chọc trời Sài Gòn, Lâm Trần đứng bên ban công phòng làm việc của Nhân Y Đường, làn gió đêm mát rượi thổi bay mái tóc anh. Minh Thư bước đến bên cạnh, đưa cho anh một ly vang đỏ, nụ cười rạng rỡ như đóa hoa hướng dương:</p>
<p>"Chúc mừng anh, bác sĩ Lâm Trần. Từ hôm nay, anh đã chính thức trở thành huyền thoại y học của thành phố này."</p>
<p>Lâm Trần chạm ly với cô, ánh mắt nhìn xa xăm về phía chân trời rực sáng của thành phố: "Không, đây mới chỉ là sự khởi đầu của chúng ta!"</p>"""

    novel["chapters"].append({
        "title": "Chương 1: Kẻ Ăn Cắp Công Trình",
        "content": chap1_content
    })
    novel["chapters"].append({
        "title": "Chương 2: Người Bạn Đồng Hành Kỳ Lạ",
        "content": chap2_content
    })
    novel["chapters"].append({
        "title": "Chương 3: Khai Trương Đối Đầu",
        "content": chap3_content
    })
    novel["chapters"].append({
        "title": "Chương 4: Đỉnh Điểm Khủng Hoảng",
        "content": chap4_content
    })
    novel["chapters"].append({
        "title": "Chương 5: Bàn Tay Vàng Lật Kèo",
        "content": chap5_content
    })

    # Let's count words for verification
    for i, ch in enumerate(novel["chapters"]):
        # strip tags and count words
        import re
        text_only = re.sub(r'<[^>]+>', ' ', ch["content"])
        words = text_only.split()
        print(f"Chapter {i+1} word count: {len(words)} words (~ {len(text_only)} characters)")

    output_path = "/Users/aaronnguyen/TN/App/doctieuthuyet/pending_novel.json"
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(novel, f, ensure_ascii=False, indent=2)
    print("✓ Successfully wrote pending_novel.json!")

if __name__ == "__main__":
    create_novel()
